# El álgebra $\mathfrak{D}=\mathcal{D}(\mathcal{FK}_m\# \Bbbk\mathbb{S}_{3})$
Sea $\mathcal{FK}_m$ el álgebra presentada por generadores

$$
\{ x_{(ij)} \mid i<j \in \mathbb{I}_m \}
$$
y relaciones
$$
\begin{align*}
x_{(ij)}^2 &= 0, && i<j \in \mathbb{I}_m, \\
x_{(ij)}x_{(kl)} - x_{(kl)}x_{(ij)} &= 0, && i,j,k,l \in \mathbb{I}_m, \text{ todos distintos}, \\
x_{(jk)}x_{(ik)} - x_{(ij)}x_{(jk)} + x_{(ik)}x_{(ij)} &= 0, && i<j<k \in \mathbb{I}_m, \\
x_{(ik)}x_{(jk)} - x_{(jk)}x_{(ij)} + x_{(ij)}x_{(ik)} &= 0, && i<j<k \in \mathbb{I}_m.
\end{align*}
$$

## El álgebra $\mathcal{FK}_3$


Para $m=3$, el álgebra $\mathcal{FK}_3$ está generada por
$$
x_{(12)},\quad x_{(13)},\quad x_{(23)}
$$
y las relaciones son:
$$
\begin{aligned}
x_{(12)}^2 &= 0, \\
x_{(13)}^2 &= 0, \\
x_{(23)}^2 &= 0, \\
x_{(23)}x_{(13)} - x_{(12)}x_{(23)} + x_{(13)}x_{(12)} &= 0, \\
x_{(13)}x_{(23)} - x_{(23)}x_{(12)} + x_{(12)}x_{(13)} &= 0.
\end{aligned}
$$

In [1]:
LoadPackage("SCSCP");

true

In [2]:
t0 := NanosecondsSinceEpoch();;

In [3]:
LoadPackage("GBNP");

true

In [4]:
GBNP.ConfigPrint(
    "X0",    # 1
    "X1",    # 2
    "X2",    # 3
    "σ",     # 4   σ      (0, g)   (1,2)
    "τ",     # 5   τ      (1, 0)   (1,2,3)
    "De",    # 6   e      (0, 0)   ()  
    "D12",   # 7   F1     (0, g)   (1,2)
    "D123",  # 8   F2     (1, 0)   (1,2,3)
    "D13",   # 9   F1F2^2 (1, g)   (1,3)
    "D132",  # 10  F2^2   (w, 0)   (1,3,2)
    "D23",   # 11  F1F2   (w, g)   (2,3)
    "Y0",    # 12
    "Y1",    # 13
    "Y2"     # 14
);

In [12]:
nX       := 3;;
nGensOfG := 2;;
nDelta   := 6;;
nY       := 3;;
nTotal   := nX + nGensOfG  +  nDelta + nY;;
F        := FreeAssociativeAlgebraWithOne( Rationals, nTotal );;
gens     := GeneratorsOfAlgebra(F);;
e        := gens[1];;

In [15]:
# Generators 𝓑(V) #
X12 := gens[2];;
X13 := gens[3];;
X23 := gens[4];;

### Generadores of Group G

In [15]:
# Generators k(S_3) #
F1 := gens[5];;
F2 := gens[6];;

In [23]:
# Generators k^(S_3) #
De   := gens[7];;   # 6   e      (0, 0)   ()  
D12  := gens[8];;   # 7   F1     (0, g)   (1,2)
D123 := gens[9];;   # 8   F2     (1, 0)   (1,2,3)
D13  := gens[10];;  # 9   F1F2^2 (1, g)   (1,3)
D132 := gens[11];;  # 10  F2^2   (w, 0)   (1,3,2)
D23  := gens[12];;  # 11  F1F2   (w, g)   (2,3)

In [26]:
# Generators 𝓑(V) Dual #
Y12 := gens[13];;
Y13 := gens[14];;
Y23 := gens[15];;

In [30]:
gensX      := GP2NPList( gens{[2..4]} );;
gensG      := GP2NPList( gens{[5, 6]} );;
gensDeltas := GP2NPList( gens{[7..12]} );;
gensY      := GP2NPList( gens{[13..15]} );;

In [31]:
PrintNPList( gensX );

 X0
 X1
 X2

In [32]:
PrintNPList( gensG );

 σ
 τ

In [33]:
PrintNPList( gensDeltas );

 De
 D12
 D123
 D13
 D132
 D23

In [33]:
PrintNPList( gensY );

 Y0
 Y1
 Y2

In [39]:
xIndex        := [1..3];;
groupElemsInF := [
    e,               #1 1      (0, 0)  e
    F1,              #2 F1     (0, g)  (1,2)
    F2,              #5 F2     (1, 0)  (1,2,3)
    F1*F2^2,         #1 F1F2^2 (1, g)  (1,3)
    F2^2,            #4 F2^2   (w, 0)  (1,3,2)
    F1*F2            #8 F1F2   (w, g)  (2,3)
];;
groupIndex     := List(groupElemsInF, elm -> GP2NP(elm)[1][1]);;
deltaIndex     := [6..11];;
yIndex         := [12..14];;

## Relaciones en el álgebra $\mathcal{FK}_3$

### *Nilpotencia cuadrática*:
$$
\begin{align*}
x_{(12)}^2 = x_{(13)}^2 = x_{(23)}^2 = 0,
\end{align*}
$$
Para nosotros serán:
$$
\begin{align*}
x_{12}^2 = x_{13}^2 = x_{23}^2 = 0.
\end{align*}
$$

### Relaciones triples para $i<j<k$:

- Para $1<2<3$:
$$
x^{2}_{(ij)} \;=\; x_{(ij)}x_{(ik)} \;+\; x_{(jk)}x_{(ij)} \;+\; x_{(ik)}x_{(jk)}
\;=\;
x_{(ik)}x_{(ij)} \;+\; x_{(ij)}x_{(jk)} \;+\; x_{(jk)}x_{(ik)}
\;=\; 0,
\quad \text{(dada por } B(V)).
$$

$$
\begin{aligned}
x_{(12)}x_{(13)} + x_{(23)}x_{(12)} + x_{(13)}x_{(23)} 
\quad \text{y} \quad 
x_{(13)}x_{(12)} + x_{(12)}x_{(23)} + x_{(23)}x_{(13)}.
\end{aligned}
$$

In [51]:
###############################################################################
# x_(ij)^2 = 0, x_(ij)x_(jk)+x_(jk)x_(ik)+x_(ik)x_(ij)=0, etc. 
# (álgebra Fomin-Kirillov n=3,
###############################################################################

# Generadores x_(ij)
gensFK3      := [ (1,2), (1,3), (2,3) ];;
generators   := gens{[2..4]};;
relationsFK3 := List( generators, s -> s^2);;
i            := 1;;
j            := 2;;
k            := 3;;
Xij          := generators[Position(gensFK3, (i,j))];;
Xik          := generators[Position(gensFK3, (i,k))];;
Xjk          := generators[Position(gensFK3, (j,k))];;
# primera relación: x_(ij)x_(jk) + x_(jk)x_(ik) + x_(ik)x_(ij) = 0
Add(relationsFK3, Xij*Xjk + Xjk*Xik + Xik*Xij );
# segunda relación: x_(jk)x_(ij) + x_(ik)x_(jk) + x_(ij)x_(ik) = 0
Add(relationsFK3, Xjk*Xij + Xik*Xjk + Xij*Xik );
relsFK3 := GP2NPList(relationsFK3);;

In [52]:

PrintNPList( relsFK3 );
#X12^2 
#X13^2 
#X23^2 
#X12X23 + X23X13 + X13X12 
#X23X12 + X13X23 + X12X13

 X0^2
 X1^2
 X2^2
 X2X1 + X1X0 + X0X2
 X2X0 + X1X2 + X0X1

In [54]:
J_FK3 := SGrobner( relsFK3 );;
PrintNPList( J_FK3 );

 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2X1 + X1X0 + X0X2
 X2^2
 X1X0X1 - X0X1X0

In [55]:
DimQA( J_FK3, 3 );

12

In [57]:
Base_FK3 := BaseQA( J_FK3, 3, 0 );;
PrintNPList( Base_FK3 );

 1
 X0
 X1
 X2
 X0X1
 X0X2
 X1X0
 X1X2
 X0X1X0
 X0X1X2
 X1X0X2
 X0X1X0X2

## Relaciones en el álgebra $\mathcal{FK}_3$ dual

### *Nilpotencia cuadrática*:
$$
\begin{align*}
y_{(12)}^2 = y_{(13)}^2 = y_{(23)}^2 = 0.\\
\end{align*}
$$
Para nosotros serán:
$$
\begin{align*}
y_{12}^2 = y_{13}^2 = y_{23}^2 = 0.
\end{align*}
$$

### Relaciones triples para $i<j<k$:

- Para $1<2<3$:
$$
\begin{align*}
    y_{(23)}y_{(13)} + y_{(12)}y_{(23)} + y_{(13)}y_{(12)} &= 0,&&\Rightarrow& y_3y_1 + y_0y_3 + y_1y_0 &= 0, \\
    y_{(13)}x_{(23)} + y_{(23)}y_{(12)} + y_{(12)}y_{(13)} &= 0,&&\Rightarrow& y_1y_3 + y_3y_0 + y_0y_1 &= 0.
\end{align*}
$$

In [62]:
###############################################################################
# y_(ij)^2 = 0, y_(ij)y_(jk)+y_(jk)y_(ik)+y_(ik)y_(ij)=0, etc. 
# (álgebra Fomin-Kirillov n=3,
###############################################################################

# Generadores x_(ij)
gensFK3     := [ (1,2), (1,3), (2,3) ];;
relsFK3dual := [];;
# Paso 1: Relaciones cuadráticas x_(ij)^2 = 0
for k in [1..Length(gensFK3 )] do
    Add(relsFK3dual, [[ [yIndex[k], yIndex[k]] ], [1]]);;
od;
# Paso 2: Relaciones cúbicas de tres índices distintos
triples := [[1,2,3]];;  # único triple distinto para n=3
for t in triples do
    i := t[1];
    j := t[2];
    k := t[3];
    ij := Position(gensFK3, (i,j));
    ik := Position(gensFK3, (i,k));
    jk := Position(gensFK3, (j,k));
    # primera relación: y_(ij)y_(jk) + y_(jk)y_(ik) + y_(ik)y_(ij) = 0
    Add(relsFK3dual,[[[yIndex[ij],yIndex[jk]],[yIndex[jk],yIndex[ik]],[yIndex[ik],yIndex[ij]]],[1,1,1]]);
    # segunda relación: y_(jk)y_(ij) + y_(ik)y_(jk) + y_(ij)y_(ik) = 0
    Add(relsFK3dual,[[[yIndex[jk],yIndex[ij]],[yIndex[ik],yIndex[jk]],[yIndex[ij],yIndex[ik]]],[1,1,1]]);
od;

In [63]:
# Imprimir las relaciones
PrintNPList(relsFK3dual);

 Y0^2
 Y1^2
 Y2^2
 Y0Y2 + Y2Y1 + Y1Y0
 Y2Y0 + Y1Y2 + Y0Y1

In [63]:
I := Concatenation(
    gensX,
    gensG,
    gensDeltas,
    relsFK3dual    # 9 rels
);;

In [65]:
J := SGrobner( I );;

In [66]:
DimQA(J, 14);

12

In [68]:
Base_FK3dual := BaseQA( J, 14, 0 );;
PrintNPList( Base_FK3dual );

 1
 Y0
 Y1
 Y2
 Y0Y1
 Y0Y2
 Y1Y0
 Y1Y2
 Y0Y1Y0
 Y0Y1Y2
 Y1Y0Y2
 Y0Y1Y0Y2

## Presentación concreta para $\mathbb{S}_{3}$.

Tomemos la presentación habitual
$$
\mathbb{S}_{3} = \langle \sigma, \tau \mid \sigma^2 = e,\ \tau^3 = e,\ \sigma\tau\sigma = \tau^{-1} \rangle,
$$
por ejemplo con $\sigma = (12)$ y $\tau = (123)$.

Entonces, los elementos de $\mathbb{S}_{3}$ son
$$
\mathbb{S}_{3} = \{\, e, (12), (13), (23), (123), (132) \,\}.
$$

En términos de los generadores $\sigma$ y $\tau$, podemos escribir:
$$
\begin{aligned}
e &= e, \\
\sigma &= (12), \\
\tau &= (123), \\
\tau^{2} &= (132)\\
\sigma \tau &= (23), \\
\sigma \tau^{2} &= (13), \\
\end{aligned}
$$

In [69]:
relsGroup := [
    F1^2-e,            # 1
    F2^3-e,            # 2
    F1*F2*F1-F2^2        # 3
];;

In [71]:
relsGroup := GP2NPList( relsGroup );;
PrintNPList( relsGroup );

 σ^2 - 1
 τ^3 - 1
 στσ - τ^2

In [72]:
J := SGrobner(Concatenation(
    relsGroup,
    gensX,
    # gensG,
    gensDeltas,
    gensY
    )
);;

In [73]:
PrintNPList( J );

 X0
 X1
 X2
 De
 D12
 D123
 D13
 D132
 D23
 Y0
 Y1
 Y2
 σ^2 - 1
 στσ - τ^2
 στ^2 - τσ
 τστ - σ
 τ^2σ - στ
 τ^3 - 1

In [74]:
DimQA(J, 14);

6

In [75]:
PrintNPList(BaseQA(J, 14, 0));

 1
 σ
 τ
 στ
 τσ
 τ^2

## Relaciones dadas por $\Bbbk^{\mathbb{S}_{3}}$.

In [76]:
LoadPackage( "QGNAG" );

true

In [77]:
config := rec(
    m            := 2,                   # Valor para m
    q            := 3,                   # Valor para q := p^n
    xIndex       := xIndex,
    groupIndex   := groupIndex,
    deltaIndex   := deltaIndex,
    yIndex       := yIndex,
    nX           := nX,
    nGensOfG     := nGensOfG,
    nDelta       := nDelta,
    nY           := nY,
    DEFAULT      := false,
    TEST         := false,
    PROD         := false,
    DEV          := true,
);;

In [78]:
QGNAGSetConfig(config);

In [79]:
QGNAGShowConfig();

========================================
         QGNAG CONFIGURATION
========================================

Base Structures
---------------
Cyclic group order (C_m)     : 2
Finite field size (q = p^n)  : 3

Derived Objects
---------------
Cyclic ring            : Z/2Z
Finite field           : GF(3)

Index Sets
----------
xIndex     : [ 1 .. 3 ]
groupIndex : [ [  ], [ 4 ], [ 5 ], [ 4, 5, 5 ], [ 5, 5 ], [ 4, 5 ] ]
deltaIndex : [ 6 .. 11 ]
yIndex     : [ 12 .. 14 ]

Dimensions
----------
Number of x generators       : 3
Number of group generators   : 2
Number of delta generators   : 6
Number of y generators       : 3

Elements Of Group
---------------
Elements:
( 0 , 0 )
( 0 , 1 )
( 1 , 0 )
( 1 , 1 )
( ζ_2 , 0 )
( ζ_2 , 1 )

Nichols Algebra
---------------
Number of j generators: [ 0, 1, ζ_2 ]

========================================

In [79]:
relskG := RelationsOfkGdual(deltaIndex);;

In [82]:
Print("Se generaron ", Length(relskG), " relaciones en k^G.\n");
PrintNPList( relskG );

Se generaron 37 relaciones en k^G.
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 DeD23
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D12D23
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D123D23
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D13D23
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 D132D23
 D23De
 D23D12
 D23D123
 D23D13
 D23D132
 D23^2 - D23
 De + D12 + D123 + D13 + D132 + D23 - 1

In [83]:
J := SGrobner(Concatenation(
    relskG,
    gensX,
    gensG,
    # gensDeltas,
    gensY
    )
);;

In [84]:
DimQA(J, 14);

6

In [85]:
PrintNPList(BaseQA(J, 14, 0));

 1
 De
 D12
 D123
 D13
 D132

## Relaciones dadas por $\mathcal{D}(\mathbb{S}_{3})$ 2

Sea $\mathbb{S}_{3} = \{ e, (12), (13), (23), (123), (132) \}$. 

La multiplicación en $\mathcal{D}(\mathbb{S}_{3})$ está dada por
$$
\delta_h g = g\, \delta_{g^{-1}hg}.
$$
Por lo tanto, la tabla queda:
$$
\begin{array}{c|cccccc}
g \backslash h 
& \delta_{e} 
& \delta_{(12)} 
& \delta_{(123)} 
& \delta_{(132)}
& \delta_{(23)} 
& \delta_{(13)} 
\\ \hline
e 
& e\,\delta_{e} 
& e\,\delta_{(12)} 
& e\,\delta_{(123)} 
& e\,\delta_{(132)}
& e\,\delta_{(23)}
& e\,\delta_{(13)}  
\\[4pt]

(12) 
& (12)\,\delta_{e} 
& (12)\,\delta_{(12)} 
& (12)\,\delta_{(132)} 
& (12)\,\delta_{(123)}
& (12)\,\delta_{(13)}
& (12)\,\delta_{(23)} 
\\[4pt]

(123) 
& (123)\,\delta_{e} 
& (123)\,\delta_{(13)}
& (123)\,\delta_{(123)} 
& (123)\,\delta_{(132)} 
& (123)\,\delta_{(12)}
& (123)\,\delta_{(23)} 
\\[4pt]

(132) 
& (132)\,\delta_{e} 
& (132)\,\delta_{(23)}
& (132)\,\delta_{(123)} 
& (132)\,\delta_{(132)} 
& (132)\,\delta_{(13)} 
& (132)\,\delta_{(12)} 
\\[4pt]

(23) 
& (23)\,\delta_{e} 
& (23)\,\delta_{(13)}
& (23)\,\delta_{(132)} 
& (23)\,\delta_{(123)}
& (23)\,\delta_{(23)} 
& (23)\,\delta_{(12)}  
\\[4pt]

(13) 
& (13)\,\delta_{e} 
& (13)\,\delta_{(23)}
& (13)\,\delta_{(132)} 
& (13)\,\delta_{(123)} 
& (13)\,\delta_{(12)}
& (13)\,\delta_{(13)} 
\end{array}
$$

La siguiente lista verifica la identidad 
$$
\delta_h g - g\,\delta_{g^{-1}hg} = 0:
$$

$$
\begin{align*}
1.\; \delta_e e - e\delta_e &= 0, &&&
7.\; \delta_{(12)} e - e\delta_e &= 0, &&&
13.\; \delta_{(123)} e - e\delta_e &= 0,\\
2.\; \delta_e \sigma - \sigma\delta_{e} &= 0, &&&
8.\; \delta_{(12)}\sigma - \sigma\delta_{(12)} &= 0, &&&
14.\; \delta_{(123)}\sigma - \sigma\delta_{(132)} &= 0,\\
3.\; \delta_e\tau - \tau\delta_{e} &= 0, &&&
9.\; \delta_{(12)}\tau - \tau\delta_{(13)} &= 0, &&&
15.\; \delta_{(123)}\tau - \tau\delta_{(123)} &= 0,\\
4.\; \delta_e \tau^2 - \tau^2\delta_{e} &= 0, &&&
10.\; \delta_{(12)}\tau^2 - \tau^2\delta_{(23)} &= 0, &&&
16.\; \delta_{(123)}\tau^2 - \tau^2\delta_{(123)} &= 0,\\
5.\; \delta_e \sigma\tau - \sigma\tau\delta_{e} &= 0, &&&
11.\; \delta_{(12)}\sigma\tau - \sigma\tau\delta_{(13)} &= 0, &&&
17.\; \delta_{(123)}\sigma\tau - \sigma\tau\delta_{(132)} &= 0,\\
6.\; \delta_e \sigma\tau^2 - \sigma\tau^2\delta_{e} &= 0, &&&
12.\; \delta_{(12)}\sigma\tau^2 - \sigma\tau^2\delta_{(23)} &= 0, &&&
18.\; \delta_{(123)}\sigma\tau^2 - \sigma\tau^2\delta_{(132)} &= 0,\\[4pt]
19.\; \delta_{(132)} e - e \delta_{(132)} &= 0, &&&
25.\; \delta_{(23)} e - e \delta_{(23)} &= 0, &&&
31.\; \delta_{(13)} e - e \delta_{(13)} &= 0,\\
20.\; \delta_{(132)}\sigma - \sigma\delta_{(132)} &= 0, &&&
26.\; \delta_{(23)}\sigma - \sigma\delta_{(13)} &= 0, &&&
32.\; \delta_{(13)}\sigma - \sigma\delta_{(23)} &= 0,\\
21.\; \delta_{(132)}\tau - \tau\delta_{(132)} &= 0, &&&
27.\; \delta_{(23)}\tau - \tau\delta_{(12)} &= 0, &&&
33.\; \delta_{(13)}\tau - \tau\delta_{(23)} &= 0,\\
22.\; \delta_{(132)}\tau^2 - \tau^2\delta_{(132)} &= 0, &&&
28.\; \delta_{(23)}\tau^2 - \tau^2\delta_{(13)} &= 0, &&&
34.\; \delta_{(13)}\tau^2 - \tau^2\delta_{(12)} &= 0,\\
23.\; \delta_{(132)}\sigma\tau - \sigma\tau\delta_{(123)} &= 0, &&&
29.\; \delta_{(23)}\sigma\tau - \sigma\tau\delta_{(23)} &= 0, &&&
35.\; \delta_{(13)}\sigma\tau - \sigma\tau\delta_{(12)} &= 0,\\
24.\; \delta_{(132)}\sigma\tau^2 - \sigma\tau^2\delta_{(123)}  &= 0, &&&
30.\; \delta_{(23)}\sigma\tau^2 - \sigma\tau^2\delta_{(12)} &= 0, &&&
36.\; \delta_{(13)}\sigma\tau^2 - \sigma\tau^2\delta_{(13)} &= 0.
\end{align*}
$$

In [95]:
K           := CyclicGroup(3);;
H           := CyclicGroup(2);;
AutK        := AutomorphismGroup(K);;
gensAutK    := GeneratorsOfGroup(AutK);;
T           := GroupHomomorphismByImages(H, AutK, [H.1], gensAutK);;
G           := SemidirectProduct(H, T, K);;
embK        := Embedding(G, 2);;
embH        := Embedding(G, 1);;
HinG        := List([0 .. Size(H) - 1], x -> embH(H.1^x));;
allPairsInG := Concatenation(List(K, x -> List(HinG, y -> embK(x) * y)));;

In [96]:
relsDG := CommutationRelationsGroupAndDeltas(allPairsInG, groupIndex, deltaIndex);

[ [ [ [ 6 ], [ 6 ] ], [ 1, -1 ] ], [ [ [ 7 ], [ 7 ] ], [ 1, -1 ] ],   [ [ [ 8 ], [ 8 ] ], [ 1, -1 ] ], [ [ [ 9 ], [ 9 ] ], [ 1, -1 ] ],   [ [ [ 10 ], [ 10 ] ], [ 1, -1 ] ], [ [ [ 11 ], [ 11 ] ], [ 1, -1 ] ],   [ [ [ 6, 4 ], [ 4, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 4 ], [ 4, 7 ] ], [ 1, -1 ] ]    , [ [ [ 8, 4 ], [ 4, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4 ], [ 4, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 4 ], [ 4, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4 ], [ 4, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 5 ], [ 5, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 5 ], [ 5, 9 ] ], [ 1, -1 ] ]    , [ [ [ 8, 5 ], [ 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5 ], [ 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 5 ], [ 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5 ], [ 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5, 5 ], [ 4, 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5, 5 ], [ 4, 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5, 5 ], [ 4, 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5, 5 ], [ 4, 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5, 5 ], [ 4, 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5, 5 ], [ 4, 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 5, 5 ], [ 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 5, 5 ], [ 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 5, 5 ], [ 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 5 ], [ 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 5 ], [ 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 5 ], [ 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5 ], [ 4, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5 ], [ 4, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5 ], [ 4, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5 ], [ 4, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5 ], [ 4, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5 ], [ 4, 5, 11 ] ], [ 1, -1 ] ] ]

In [98]:
Print("Se generaron ", Length(relsDG), " relaciones δ_h g = g δ_{g*h*g^-1}.\n");
PrintNPList(relsDG);

Se generaron 36 relaciones δ_h g = g δ_{g*h*g^-1}.
 De - De
 D12 - D12
 D123 - D123
 D13 - D13
 D132 - D132
 D23 - D23
 Deσ - σDe
 D12σ - σD12
 D123σ - σD132
 D13σ - σD23
 D132σ - σD123
 D23σ - σD13
 Deτ - τDe
 D12τ - τD13
 D123τ - τD123
 D13τ - τD23
 D132τ - τD132
 D23τ - τD12
 Deστ^2 - στ^2De
 D12στ^2 - στ^2D23
 D123στ^2 - στ^2D132
 D13στ^2 - στ^2D13
 D132στ^2 - στ^2D123
 D23στ^2 - στ^2D12
 Deτ^2 - τ^2De
 D12τ^2 - τ^2D23
 D123τ^2 - τ^2D123
 D13τ^2 - τ^2D12
 D132τ^2 - τ^2D132
 D23τ^2 - τ^2D13
 Deστ - στDe
 D12στ - στD13
 D123στ - στD132
 D13στ - στD12
 D132στ - στD123
 D23στ - στD23

In [99]:
J := SGrobner(Concatenation(
    relsGroup,
    relskG,
    relsDG,
    gensX,
    gensY
    )
);;

In [100]:
DimQA(J, 14);

36

In [101]:
PrintNPList(BaseQA(J, 14, 0));

 1
 σ
 τ
 De
 D12
 D123
 D13
 D132
 στ
 σDe
 σD12
 σD123
 σD13
 σD132
 τσ
 τ^2
 τDe
 τD12
 τD123
 τD13
 τD132
 στDe
 στD12
 στD123
 στD13
 στD132
 τσDe
 τσD12
 τσD123
 τσD13
 τσD132
 τ^2De
 τ^2D12
 τ^2D123
 τ^2D13
 τ^2D132

## Relaciones dadas por la the bosonizaciones $\mathcal{FK}_3\#\Bbbk\mathbb{S}_{3}$

## Relaciones $gx_{(ij)} = sgn(g) x_{g(ij)g^{-1}} g$, evaluadas para todos los $g \in S_3$

### En términos de $x_{(ij)}$ para todo $g \in \mathbb{S}_3$


- Caso $(ij) = (12)$:

$$
\begin{aligned}
e\,x_{(12)} &= x_{(12)}\,e, \\[4pt]
(12)\,x_{(12)} &= -\,x_{(12)}\,(12), \\[4pt]
(123)\,x_{(12)} &= x_{(23)}\,(123), \\[4pt]
(132)\,x_{(12)} &= x_{(13)}\,(132), \\[4pt]
(23)\,x_{(12)} &= -\,x_{(13)}\,(23), \\[4pt]
(13)\,x_{(12)} &= -\,x_{(23)}\,(13).
\end{aligned}
$$

- Caso $(ij) = (13)$

$$
\begin{aligned}
e\,x_{(13)} &= x_{(13)}\,e, \\[4pt]
(12)\,x_{(13)} &= -\,x_{(23)}\,(12), \\[4pt]
(123)\,x_{(13)} &= x_{(12)}\,(123), \\[4pt]
(132)\,x_{(13)} &= x_{(23)}\,(132), \\[4pt]
(23)\,x_{(13)} &= -\,x_{(12)}\,(23), \\[4pt]
(13)\,x_{(13)} &= -\,x_{(13)}\,(13).
\end{aligned}
$$

- Caso $(ij) = (23)$:

$$
\begin{aligned}
e\,x_{(23)} &= x_{(23)}\,e, \\[4pt]
(12)\,x_{(23)} &= -\,x_{(13)}\,(12), \\[4pt]
(123)\,x_{(23)} &= x_{(13)}\,(123), \\[4pt]
(132)\,x_{(23)} &= x_{(12)}\,(132), \\[4pt]
(23)\,x_{(23)} &= -\,x_{(23)}\,(23), \\[4pt]
(13)\,x_{(23)} &= -\,x_{(12)}\,(13).
\end{aligned}
$$

In [102]:
elmsG := GetElementsOfG();;

In [103]:
gensA:=QGNAG.Config.gensA;

[ 0*Z(3), Z(3)^0, Z(3) ]

In [105]:
rels0 := RelationsGivenByNicholsSmashkG(gensA[1], elmsG);;
PrintNPList(rels0);

 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ

In [107]:
rels1 := RelationsGivenByNicholsSmashkG(gensA[2], elmsG);;
PrintNPList(rels1);

 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ

In [109]:
relsOmega := RelationsGivenByNicholsSmashkG(gensA[3], elmsG);;
PrintNPList(relsOmega);

 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ

In [110]:
relsxBos:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [112]:
# Probar la primera relación
Print("Se generaron ", Length(relsxBos), " relaciones en total.\n");
PrintNPList(relsxBos);

Se generaron 18 relaciones en total.
 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ
 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ
 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ

In [113]:
J := SGrobner(Concatenation(
    relsFK3,
    relsxBos,
    relsGroup,
    gensDeltas,
    gensY
    )
);;

In [114]:
DimQA(J, 14);

72

# El algebra $\mathfrak{B}(\overline{V})\#\Bbbk G$

## Relaciones $y_{(ij)} g = sign(g)  g  y_{g(ij)g^{-1}}$, evaluadas para todos los $g \in S_3$

### En términos de $y_{(ij)}$ para todo $g \in \mathbb{S}_3$

- Caso $(ij)=(12)$:
$$
\begin{aligned}
y_{(12)}\, e &= e\, y_{(12)}, \\[1mm]
y_{(12)}\, (12) &= - (12)\, y_{(12)}, \\[1mm]
y_{(12)}\, (123) &= (123)\, y_{(23)}, \\[1mm]
y_{(12)}\, (132) &= (132)\, y_{(13)}, \\[1mm]
y_{(12)}\, (23) &= - (23)\, y_{(13)}, \\[1mm]
y_{(12)}\, (13) &= - (13)\, y_{(23)}.
\end{aligned}
$$

- Caso $(ij)=(13)$:
$$
\begin{aligned}
y_{(13)}\, e &= e\, y_{(13)}, \\[1mm]
y_{(13)}\, (12) &= - (12)\, y_{(23)}, \\[1mm]
y_{(13)}\, (123) &= (123)\, y_{(12)}, \\[1mm]
y_{(13)}\, (132) &= (132)\, y_{(23)}, \\[1mm]
y_{(13)}\, (23) &= - (23)\, y_{(12)}, \\[1mm]
y_{(13)}\, (13) &= - (13)\, y_{(13)}.
\end{aligned}
$$

- Caso $(ij)=(23)$:
$$
\begin{aligned}
y_{(23)}\, e &= e\, y_{(23)}, \\[1mm]
y_{(23)}\, (12) &= - (12)\, y_{(13)}, \\[1mm]
y_{(23)}\, (123) &= (123)\, y_{(13)}, \\[1mm]
y_{(23)}\, (132) &= (132)\, y_{(12)}, \\[1mm]
y_{(23)}\, (23) &= - (23)\, y_{(23)}, \\[1mm]
y_{(23)}\, (13) &= - (13)\, y_{(12)}.
\end{aligned}
$$

In [115]:
rels0 := RelationsGivenByNicholsDualSmashkG(gensA[1], elmsG);;

In [116]:
rels1 := RelationsGivenByNicholsDualSmashkG(gensA[2], elmsG);;

In [117]:
relsOmega:=RelationsGivenByNicholsDualSmashkG(gensA[3], elmsG);;

In [118]:
relsyBos:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [120]:
# Probar la primera relación
Print("Se generaron ", Length(relsyBos), " relaciones en total.\n");
PrintNPList(relsyBos);

Se generaron 18 relaciones en total.
 Y0 - Y0
 Y0σ + σY0
 Y0τ - τY1
 Y0στ^2 + στ^2Y2
 Y0τ^2 - τ^2Y2
 Y0στ + στY1
 Y1 - Y1
 Y1σ + σY2
 Y1τ - τY2
 Y1στ^2 + στ^2Y1
 Y1τ^2 - τ^2Y0
 Y1στ + στY0
 Y2 - Y2
 Y2σ + σY1
 Y2τ - τY0
 Y2στ^2 + στ^2Y0
 Y2τ^2 - τ^2Y1
 Y2στ + στY2

In [121]:
I := Concatenation(
    gensX,
    gensDeltas,
    relsGroup,    # 7 rels
    relsyBos,     # 96 rels
    relsFK3dual    # 9 rels
);;

In [122]:
# =====================================================
# Paso 5: Calcular la base de Gröbner
# =====================================================
J := SGrobner(I);;

In [123]:
DimQA(J, 14);

72

# El algebra $\mathfrak{B}(V)\#\Bbbk^G$
## Relaciones $\delta_h x_{(ij)} = x_{(ij)} \delta_{(ij)h}$
con $h$ escrito en términos de los generadores
$\sigma = (12), \tau = (123)$ de 
$\mathbb{S}_3 = \{ e, \sigma, \tau, \tau^2, \sigma\tau, \sigma\tau^2 \}$
y sabiendo que $\sigma\tau = (23)$, $\sigma\tau^2 = (13)$


- Caso $(ij) = (12)$:
$$
\begin{aligned}
\delta_{e}\,x_{(12)} &= x_{(12)}\,\delta_{(12)}, \\[4pt]
\delta_{(12)}\,x_{(12)} &= x_{(12)}\,\delta_{e}, \\[4pt]
\delta_{(123)}\,x_{(12)} &= x_{(12)}\,\delta_{(23)}, \\[4pt]
\delta_{(132)}\,x_{(12)} &= x_{(12)}\,\delta_{(13)}, \\[4pt]
\delta_{(23)}\,x_{(12)} &= x_{(12)}\,\delta_{(123)}, \\[4pt]
\delta_{(13)}\,x_{(12)} &= x_{(12)}\,\delta_{(132)}.
\end{aligned}
$$

- Caso $(ij) = (13)$:
$$
\begin{aligned}
\delta_{e}\,x_{(13)} &= x_{(13)}\,\delta_{(13)}, \\[4pt]
\delta_{(12)}\,x_{(13)} &= x_{(13)}\,\delta_{(123)}, \\[4pt]
\delta_{(123)}\,x_{(13)} &= x_{(13)}\,\delta_{(12)}, \\[4pt]
\delta_{(132)}\,x_{(13)} &= x_{(13)}\,\delta_{(23)}, \\[4pt]
\delta_{(23)}\,x_{(13)} &= x_{(13)}\,\delta_{(132)}, \\[4pt]
\delta_{(13)}\,x_{(13)} &= x_{(13)}\,\delta_{e}.
\end{aligned}
$$

- Caso $(ij) = (23)$:
$$
\begin{aligned}
\delta_{e}\,x_{(23)} &= x_{(23)}\,\delta_{(23)}, \\[4pt]
\delta_{(12)}\,x_{(23)} &= x_{(23)}\,\delta_{(132)}, \\[4pt]
\delta_{(123)}\,x_{(23)} &= x_{(23)}\,\delta_{(13)}, \\[4pt]
\delta_{(132)}\,x_{(23)} &= x_{(23)}\,\delta_{(12)}, \\[4pt]
\delta_{(23)}\,x_{(23)} &= x_{(23)}\,\delta_{e}, \\[4pt]
\delta_{(13)}\,x_{(23)} &= x_{(23)}\,\delta_{(123)}.
\end{aligned}
$$

In [123]:
rels0 := RelationsGivenByNicholsSmashkGDual(gensA[1], elmsG);;

In [125]:
PrintNPList(rels0);

 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123

In [126]:
rels1 := RelationsGivenByNicholsSmashkGDual(gensA[2], elmsG);;

In [127]:
PrintNPList(rels1);

 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132

In [128]:
relsOmega := RelationsGivenByNicholsSmashkGDual(gensA[3], elmsG);;

In [129]:
PrintNPList(relsOmega);

 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De

In [130]:
relsDx:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [132]:
Print("Se generaron ", Length(relsDx), " relaciones δ_h x_(ij) = x_(ij) δ_{(ij)h}.\n");
PrintNPList(relsDx);

Se generaron 18 relaciones δ_h x_(ij) = x_(ij) δ_{(ij)h}.
 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123
 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132
 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De

In [133]:
J := SGrobner(Concatenation(
    relsFK3,
    relskG,
    relsDx,
    gensG,
    gensY
    )
);;

In [134]:
DimQA(J, 14);

72

## Relaciones $\delta_g y_{(ij)} = y_{(ij)} \delta_{(ij)g}$
con $g$ escrito en términos de los generadores
$\sigma = (12), \tau = (123)$ de 
$\mathbb{S}_3 = \{ e, \sigma, \tau, \tau^2, \sigma\tau, \sigma\tau^2 \}$
y sabiendo que $\sigma\tau = (23)$, $\sigma\tau^2 = (13)$

- Caso $(ij) = (12)$:
$$
\begin{aligned}
\delta_{e}\,y_{(12)} &= y_{(12)}\,\delta_{(12)}, \\[2mm]
\delta_{(12)}\,y_{(12)} &= y_{(12)}\,\delta_{e}, \\[2mm]
\delta_{(123)}\,y_{(12)} &= y_{(12)}\,\delta_{(23)}, \\[2mm]
\delta_{(132)}\,y_{(12)} &= y_{(12)}\,\delta_{(13)}, \\[2mm]
\delta_{(23)}\,y_{(12)} &= y_{(12)}\,\delta_{(123)}, \\[2mm]
\delta_{(13)}\,y_{(12)} &= y_{(12)}\,\delta_{(132)}.
\end{aligned}
$$

- Caso $(ij) = (13)$:
$$
\begin{aligned}
\delta_{e}\,y_{(13)} &= y_{(13)}\,\delta_{(13)}, \\[2mm]
\delta_{(12)}\,y_{(13)} &= y_{(13)}\,\delta_{(123)}, \\[2mm]
\delta_{(123)}\,y_{(13)} &= y_{(13)}\,\delta_{(12)}, \\[2mm]
\delta_{(132)}\,y_{(13)} &= y_{(13)}\,\delta_{(23)}, \\[2mm]
\delta_{(23)}\,y_{(13)} &= y_{(13)}\,\delta_{(132)}, \\[2mm]
\delta_{(13)}\,y_{(13)} &= y_{(13)}\,\delta_{e}.
\end{aligned}
$$

- Caso $(ij) = (23)$:

$$
\begin{aligned}
\delta_{e}\,y_{(23)} &= y_{(23)}\,\delta_{(23)}, \\[2mm]
\delta_{(12)}\,y_{(23)} &= y_{(23)}\,\delta_{(132)}, \\[2mm]
\delta_{(123)}\,y_{(23)} &= y_{(23)}\,\delta_{(13)}, \\[2mm]
\delta_{(132)}\,y_{(23)} &= y_{(23)}\,\delta_{(12)}, \\[2mm]
\delta_{(23)}\,y_{(23)} &= y_{(23)}\,\delta_{e}, \\[2mm]
\delta_{(13)}\,y_{(23)} &= y_{(23)}\,\delta_{(123)}.
\end{aligned}
$$

In [137]:
rels0 := RelationsGivenByNicholsDualSmashkGDual(gensA[1], elmsG);;
rels1 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], elmsG);;
rels3 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], elmsG);;

In [138]:
relsDy:=Concatenation(
    rels0,
    rels1,
    rels3
);;

In [140]:
Print("Se generaron ", Length(relsDy), " relaciones δ_g y_(ij) = y_(ij) δ_{(ij)g}.\n");
PrintNPList(relsDy);

Se generaron 18 relaciones δ_g y_(ij) = y_(ij) δ_{(ij)g}.
 DeY0 - Y0D12
 D12Y0 - Y0De
 D123Y0 - Y0D23
 D13Y0 - Y0D132
 D132Y0 - Y0D13
 D23Y0 - Y0D123
 DeY1 - Y1D13
 D12Y1 - Y1D123
 D123Y1 - Y1D12
 D13Y1 - Y1De
 D132Y1 - Y1D23
 D23Y1 - Y1D132
 DeY2 - Y2D23
 D12Y2 - Y2D132
 D123Y2 - Y2D13
 D13Y2 - Y2D123
 D132Y2 - Y2D12
 D23Y2 - Y2De

In [141]:
J := SGrobner(Concatenation(
    relsFK3dual,
    relskG,
    relsDy,
    gensG,
    gensX
    )
);;

In [142]:
DimQA(J, 14);

72

# Calculo $\mathfrak{B}(V)\#D(G)$

In [143]:
I := Concatenation(
    relsFK3,      # 5 rels
    # ------------------------
    relsGroup,    # 3 rels
    relskG,       # 37 rels
    relsDG,       # 36 rels
    # ------------------------
    relsxBos,     # 18 rels
    relsDx,       # 18 rels
    # ------------------------
    gensY         # 3 gens
);

[ [ [ [ 1, 1 ] ], [ 1 ] ], [ [ [ 2, 2 ] ], [ 1 ] ], [ [ [ 3, 3 ] ], [ 1 ] ],   [ [ [ 3, 2 ], [ 2, 1 ], [ 1, 3 ] ], [ 1, 1, 1 ] ],   [ [ [ 3, 1 ], [ 2, 3 ], [ 1, 2 ] ], [ 1, 1, 1 ] ],   [ [ [ 4, 4 ], [  ] ], [ 1, -1 ] ], [ [ [ 5, 5, 5 ], [  ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 4 ], [ 5, 5 ] ], [ 1, -1 ] ], [ [ [ 6, 6 ], [ 6 ] ], [ 1, -1 ] ]    , [ [ [ 6, 7 ] ], [ 1 ] ], [ [ [ 6, 8 ] ], [ 1 ] ],   [ [ [ 6, 9 ] ], [ 1 ] ], [ [ [ 6, 10 ] ], [ 1 ] ], [ [ [ 6, 11 ] ], [ 1 ] ],  [ [ [ 7, 6 ] ], [ 1 ] ], [ [ [ 7, 7 ], [ 7 ] ], [ 1, -1 ] ],   [ [ [ 7, 8 ] ], [ 1 ] ], [ [ [ 7, 9 ] ], [ 1 ] ], [ [ [ 7, 10 ] ], [ 1 ] ],   [ [ [ 7, 11 ] ], [ 1 ] ], [ [ [ 8, 6 ] ], [ 1 ] ], [ [ [ 8, 7 ] ], [ 1 ] ],   [ [ [ 8, 8 ], [ 8 ] ], [ 1, -1 ] ], [ [ [ 8, 9 ] ], [ 1 ] ],   [ [ [ 8, 10 ] ], [ 1 ] ], [ [ [ 8, 11 ] ], [ 1 ] ], [ [ [ 9, 6 ] ], [ 1 ] ],  [ [ [ 9, 7 ] ], [ 1 ] ], [ [ [ 9, 8 ] ], [ 1 ] ],   [ [ [ 9, 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 9, 10 ] ], [ 1 ] ],   [ [ [ 9, 11 ] ], [ 1 ] ], [ [ [ 10, 6 ] ], [ 1 ] ],   [ [ [ 10, 7 ] ], [ 1 ] ], [ [ [ 10, 8 ] ], [ 1 ] ],   [ [ [ 10, 9 ] ], [ 1 ] ], [ [ [ 10, 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 10, 11 ] ], [ 1 ] ], [ [ [ 11, 6 ] ], [ 1 ] ],   [ [ [ 11, 7 ] ], [ 1 ] ], [ [ [ 11, 8 ] ], [ 1 ] ],   [ [ [ 11, 9 ] ], [ 1 ] ], [ [ [ 11, 10 ] ], [ 1 ] ],   [ [ [ 11, 11 ], [ 11 ] ], [ 1, -1 ] ],   [ [ [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ], [  ] ],       [ 1, 1, 1, 1, 1, 1, -1 ] ], [ [ [ 6 ], [ 6 ] ], [ 1, -1 ] ],   [ [ [ 7 ], [ 7 ] ], [ 1, -1 ] ], [ [ [ 8 ], [ 8 ] ], [ 1, -1 ] ],   [ [ [ 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 11 ], [ 11 ] ], [ 1, -1 ] ], [ [ [ 6, 4 ], [ 4, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4 ], [ 4, 7 ] ], [ 1, -1 ] ],   [ [ [ 8, 4 ], [ 4, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4 ], [ 4, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 4 ], [ 4, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4 ], [ 4, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 5 ], [ 5, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 5 ], [ 5, 9 ] ], [ 1, -1 ] ]    , [ [ [ 8, 5 ], [ 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5 ], [ 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 5 ], [ 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5 ], [ 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5, 5 ], [ 4, 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5, 5 ], [ 4, 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5, 5 ], [ 4, 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5, 5 ], [ 4, 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5, 5 ], [ 4, 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5, 5 ], [ 4, 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 5, 5 ], [ 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 5, 5 ], [ 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 5, 5 ], [ 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 5 ], [ 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 5 ], [ 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 5 ], [ 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5 ], [ 4, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5 ], [ 4, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5 ], [ 4, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5 ], [ 4, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5 ], [ 4, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5 ], [ 4, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 1 ], [ 1 ] ], [ 1, -1 ] ], [ [ [ 4, 1 ], [ 1, 4 ] ], [ 1, 1 ] ],   [ [ [ 5, 1 ], [ 3, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 5, 1 ], [ 3, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 1 ], [ 2, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 1 ], [ 2, 4, 5 ] ], [ 1, 1 ] ], [ [ [ 2 ], [ 2 ] ], [ 1, -1 ] ],  [ [ [ 4, 2 ], [ 3, 4 ] ], [ 1, 1 ] ], [ [ [ 5, 2 ], [ 1, 5 ] ], [ 1, -1 ] ],  [ [ [ 4, 5, 5, 2 ], [ 2, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 2 ], [ 3, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 2 ], [ 1, 4, 5 ] ], [ 1, 1 ] ], [ [ [ 3 ], [ 3 ] ], [ 1, -1 ] ],  [ [ [ 4, 3 ], [ 2, 4 ] ], [ 1, 1 ] ], [ [ [ 5, 3 ], [ 2, 5 ] ], [ 1, -1 ] ],  [ [ [ 4, 5, 5, 3 ], [ 1, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 3 ], [ 1, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 3 ], [ 3, 4, 5 ] ], [ 1, 1 ] ],   [ [ [ 6, 1 ], [ 1, 7 ] ], [ 1, -1 ] ], [ [ [ 7, 1 ], [ 1, 6 ] ], [ 1, -1 ] ]    , [ [ [ 8, 1 ], [ 1, 11 ] ], [ 1, -1 ] ],   [ [ [ 9, 1 ], [ 1, 10 ] ], [ 1, -1 ] ],   [ [ [ 10, 1 ], [ 1, 9 ] ], [ 1, -1 ] ],   [ [ [ 11, 1 ], [ 1, 8 ] ], [ 1, -1 ] ],   [ [ [ 6, 2 ], [ 2, 9 ] ], [ 1, -1 ] ], [ [ [ 7, 2 ], [ 2, 8 ] ], [ 1, -1 ] ]    , [ [ [ 8, 2 ], [ 2, 7 ] ], [ 1, -1 ] ],   [ [ [ 9, 2 ], [ 2, 6 ] ], [ 1, -1 ] ],   [ [ [ 10, 2 ], [ 2, 11 ] ], [ 1, -1 ] ],   [ [ [ 11, 2 ], [ 2, 10 ] ], [ 1, -1 ] ],   [ [ [ 6, 3 ], [ 3, 11 ] ], [ 1, -1 ] ],   [ [ [ 7, 3 ], [ 3, 10 ] ], [ 1, -1 ] ],   [ [ [ 8, 3 ], [ 3, 9 ] ], [ 1, -1 ] ], [ [ [ 9, 3 ], [ 3, 8 ] ], [ 1, -1 ] ]    , [ [ [ 10, 3 ], [ 3, 7 ] ], [ 1, -1 ] ],   [ [ [ 11, 3 ], [ 3, 6 ] ], [ 1, -1 ] ], [ [ [ 12 ] ], [ 1 ] ],   [ [ [ 13 ] ], [ 1 ] ], [ [ [ 14 ] ], [ 1 ] ] ]

In [145]:
5 + 3 + 37 + 36 + 2*18 + 3;
Length(I);

120

120

In [146]:
J_D_ge_0 := SGrobner(I);;

In [147]:
12*6^2;

432

In [148]:
DimQA(J_D_ge_0, 14);

432

## Relaciones dadas de la definción de $\mathfrak{D}$,
$$
\begin{aligned}
y_{(ij)} x_{(ij)} + x_{(ij)} y_{(ij)} &= 1 + (ij)(\delta_{(ij)} - \delta_e), \\
y_{(ik)} x_{(ij)} + x_{(ij)} y_{(jk)} &= (ij)(\delta_{(ik)} - \delta_{(ik)(ij)}),
\end{aligned}
$$
para todas las transposiciones $(ij), (ik) \in \mathbb{S}_{3}$.

- Relaciones del tipo $y_{(ij)}x_{(ij)} + x_{(ij)}y_{(ij)} = 1 + (ij)(\delta_{(ij)} - \delta_e)$:
$$
\begin{aligned}
y_{(12)}x_{(12)} + x_{(12)}y_{(12)} &= 1 + (12)(\delta_{(12)} - \delta_e),\\
y_{(13)}x_{(13)} + x_{(13)}y_{(13)} &= 1 + (13)(\delta_{(13)} - \delta_e),\\
y_{(23)}x_{(23)} + x_{(23)}y_{(23)} &= 1 + (23)(\delta_{(23)} - \delta_e),
\end{aligned}
$$

- Relaciones del tipo $y_{(ik)}x_{(ij)} + x_{(ij)}y_{(jk)} = (ij)(\delta_{(ik)} - \delta_{(ik)(ij)})$:
$$
\begin{aligned}
y_{(13)}x_{(12)} + x_{(12)}y_{(23)} &= (12)(\delta_{(13)} - \delta_{(123)}),\\
y_{(23)}x_{(12)} + x_{(12)}y_{(13)} &= (12)(\delta_{(23)} - \delta_{(132)}),\\
y_{(12)}x_{(13)} + x_{(13)}y_{(23)} &= (13)(\delta_{(12)} - \delta_{(132)}),\\
y_{(23)}x_{(13)} + x_{(13)}y_{(12)} &= (13)(\delta_{(23)} - \delta_{(123)}),\\
y_{(12)}x_{(23)} + x_{(23)}y_{(13)} &= (23)(\delta_{(12)} - \delta_{(123)}),\\
y_{(13)}x_{(23)} + x_{(23)}y_{(12)} &= (23)(\delta_{(13)} - \delta_{(132)}).
\end{aligned}
$$

In [149]:
PrintNP(GetConmutationRules(gensA[2], gensA[2]));

 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13

In [151]:
relsQG:=[];;
for i in gensA do
    for j in gensA do
       resl_ij := GetConmutationRules(i, j);;
       Add(relsQG, resl_ij);
    od;
od;

In [153]:
Print("Total relations generated: ", Length(relsQG), ".\n");
PrintNPList(relsQG);

Total relations generated: 9.
 Y0X0 + X0Y0 - 1 + σDe - σD12
 Y1X0 + X0Y2 + σD123 - σD13
 Y2X0 + X0Y1 + σD132 - σD23
 Y0X1 + X1Y2 + στ^2D132 - στ^2D12
 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13
 Y2X1 + X1Y0 - στ^2D23 + στ^2D123
 Y0X2 + X2Y1 - στD12 + στD123
 Y1X2 + X2Y0 - στD13 + στD132
 Y2X2 + X2Y2 - 1 + στDe - στD23

Para concluir, afirmamos que los elementos de $V$ y $\overline{V}$ satisfacen la relación \eqref{4.5}.
En efecto, si $x \in V$ e $y \in \overline{V}$, se cumple que
$$
yx - (y_{(-1)} \cdot x)y_{(0)} =  \langle y, x \rangle - \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
por \eqref{3.5}. Por otro lado, la regla de conmutación \eqref{3.4} implica que
$$
y_{(-1)}x_{(-1)} \langle y_{(0)}, x_{(0)} \rangle = \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
donde $\langle y_{(-2)}, x_{(-3)} \rangle$ denota el emparejamiento \eqref{3.2}; comparar con \cite[eq.~(21)]{33}. \qed

In [154]:
I := Concatenation(
    relsFK3,      # 5 rels
    relsGroup,    # 3 rels
    relskG,       # 37 rels
    relsDG,       # 36 rels
    relsxBos,     # 18 rels
    relsDx,       # 18 rels
    relsDy,       # 18 rels
    relsyBos,     # 18 rels
    relsQG,       # 9 rels
    relsFK3dual   # 5 rels
);;

In [155]:
Length(I);

167

In [156]:
PrintNPList( I );

 X0^2
 X1^2
 X2^2
 X2X1 + X1X0 + X0X2
 X2X0 + X1X2 + X0X1
 σ^2 - 1
 τ^3 - 1
 στσ - τ^2
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 DeD23
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D12D23
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D123D23
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D13D23
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 D132D23
 D23De
 D23D12
 D23D123
 D23D13
 D23D132
 D23^2 - D23
 De + D12 + D123 + D13 + D132 + D23 - 1
 De - De
 D12 - D12
 D123 - D123
 D13 - D13
 D132 - D132
 D23 - D23
 Deσ - σDe
 D12σ - σD12
 D123σ - σD132
 D13σ - σD23
 D132σ - σD123
 D23σ - σD13
 Deτ - τDe
 D12τ - τD13
 D123τ - τD123
 D13τ - τD23
 D132τ - τD132
 D23τ - τD12
 Deστ^2 - στ^2De
 D12στ^2 - στ^2D23
 D123στ^2 - στ^2D132
 D13στ^2 - στ^2D13
 D132στ^2 - στ^2D123
 D23στ^2 - στ^2D12
 Deτ^2 - τ^2De
 D12τ^2 - τ^2D23
 D123τ^2 - τ^2D123
 D13τ^2 - τ^2D12
 D132τ^2 - τ^2D132
 D23τ^2 - τ^2D13
 Deστ - στDe
 D12στ - στD13
 D123στ - στD132
 D13στ - στD12
 D132στ - στD123
 D23στ - στD23
 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ
 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ
 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ
 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123
 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132
 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De
 DeY0 - Y0D12
 D12Y0 - Y0De
 D123Y0 - Y0D23
 D13Y0 - Y0D132
 D132Y0 - Y0D13
 D23Y0 - Y0D123
 DeY1 - Y1D13
 D12Y1 - Y1D123
 D123Y1 - Y1D12
 D13Y1 - Y1De
 D132Y1 - Y1D23
 D23Y1 - Y1D132
 DeY2 - Y2D23
 D12Y2 - Y2D132
 D123Y2 - Y2D13
 D13Y2 - Y2D123
 D132Y2 - Y2D12
 D23Y2 - Y2De
 Y0 - Y0
 Y0σ + σY0
 Y0τ - τY1
 Y0στ^2 + στ^2Y2
 Y0τ^2 - τ^2Y2
 Y0στ + στY1
 Y1 - Y1
 Y1σ + σY2
 Y1τ - τY2
 Y1στ^2 + στ^2Y1
 Y1τ^2 - τ^2Y0
 Y1στ + στY0
 Y2 - Y2
 Y2σ + σY1
 Y2τ - τY0
 Y2στ^2 + στ^2Y0
 Y2τ^2 - τ^2Y1
 Y2στ + στY2
 Y0X0 + X0Y0 - 1 + σDe - σD12
 Y1X0 + X0Y2 + σD123 - σD13
 Y2X0 + X0Y1 + σD132 - σD23
 Y0X1 + X1Y2 + στ^2D132 - στ^2D12
 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13
 Y2X1 + X1Y0 - στ^2D23 + στ^2D123
 Y0X2 + X2Y1 - στD12 + στD123
 Y1X2 + X2Y0 - στD13 + στD132
 Y2X2 + X2Y2 - 1 + στDe - στD23
 Y0^2
 Y1^2
 Y2^2
 Y0Y2 + Y2Y1 + Y1Y0
 Y2Y0 + Y1Y2 + Y0Y1

In [157]:
J_QG := SGrobner( I );;

In [158]:
Length(J_QG);

327

In [159]:
PrintNPList( J_QG );

 D23 + D132 + D13 + D123 + D12 + De - 1
 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2X1 + X1X0 + X0X2
 X2^2
 σX0 + X0σ
 σX1 + X2σ
 σX2 + X1σ
 σ^2 - 1
 τX0 - X2τ
 τX1 - X0τ
 τX2 - X1τ
 DeX0 - X0D12
 DeX1 - X1D13
 DeX2 + X2D132 + X2D13 + X2D123 + X2D12 + X2De - X2
 Deσ - σDe
 Deτ - τDe
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 D12X0 - X0De
 D12X1 - X1D123
 D12X2 - X2D132
 D12σ - σD12
 D12τ - τD13
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D123X0 + X0D132 + X0D13 + X0D123 + X0D12 + X0De - X0
 D123X1 - X1D12
 D123X2 - X2D13
 D123σ - σD132
 D123τ - τD123
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D13X0 - X0D132
 D13X1 - X1De
 D13X2 - X2D123
 D13σ + σD132 + σD13 + σD123 + σD12 + σDe - σ
 D13τ + τD132 + τD13 + τD123 + τD12 + τDe - τ
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D132X0 - X0D13
 D132X1 + X1D132 + X1D13 + X1D123 + X1D12 + X1De - X1
 D132X2 - X2D12
 D132σ - σD123
 D132τ - τD132
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 Y0X0 - σD12 + σDe + X0Y0 - 1
 Y0σ + σY0
 Y0τ - τY1
 Y0De - D12Y0
 Y0D12 - DeY0
 Y0D123 + D132Y0 + D13Y0 + D123Y0 + D12Y0 + DeY0 - Y0
 Y0D13 - D132Y0
 Y0D132 - D13Y0
 Y0^2
 Y1X0 - σD13 + σD123 + X0Y2
 Y1σ + σY2
 Y1τ - τY2
 Y1De - D13Y1
 Y1D12 - D123Y1
 Y1D123 - D12Y1
 Y1D13 - DeY1
 Y1D132 + D132Y1 + D13Y1 + D123Y1 + D12Y1 + DeY1 - Y1
 Y1^2
 Y2X0 + 2σD132 + σD13 + σD123 + σD12 + σDe + X0Y1 - σ
 Y2σ + σY1
 Y2τ - τY0
 Y2De + D132Y2 + D13Y2 + D123Y2 + D12Y2 + DeY2 - Y2
 Y2D12 - D132Y2
 Y2D123 - D13Y2
 Y2D13 - D123Y2
 Y2D132 - D12Y2
 Y2Y0 + Y1Y2 + Y0Y1
 Y2Y1 + Y1Y0 + Y0Y2
 Y2^2
 X1X0X1 - X0X1X0
 στσ - τ^2
 στ^2 - τσ
 στD123 - στD12 + Y0X2 + X2Y1
 στD13 + στD12 + στDe + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ + 1/2X2Y2 \
- 1/2X2Y1 - 1/2X2Y0 - 1/2
 στD132 + στD12 + στDe + 1/2Y2X2 + 1/2Y1X2 - 1/2Y0X2 - 1/2στ + 1/2X2Y2\
 - 1/2X2Y1 + 1/2X2Y0 - 1/2
 σY0X2 - X1σY1 + τD123 - τD12
 σY1X2 - X1σY0 + τD132 - τD13
 σY2X2 - X1σY2 + τD132 + τD13 + τD123 + τD12 + 2τDe - τ - σ
 τστ - σ
 τσD123 + τσD12 + τσDe + 1/2Y2X1 + 1/2Y1X1 - 1/2Y0X1 - 1/2τσ - 1/2X1Y2\
 + 1/2X1Y1 + 1/2X1Y0 - 1/2
 τσD13 - τσDe - Y1X1 - X1Y1 + 1
 τσD132 - τσD12 + Y0X1 + X1Y2
 τ^2σ - στ
 τ^3 - 1
 τ^2D123 + τ^2D12 + τ^2De + 1/2σY2X1 + 1/2σY1X1 - 1/2σY0X1 + 1/2X2σY2 -\
 1/2X2σY1 - 1/2X2σY0 - 1/2τ^2 - 1/2σ
 τ^2D13 - τ^2De - σY1X1 + X2σY1 + σ
 τ^2D132 - τ^2D12 + σY0X1 - X2σY2
 τY0X1 - 2στD12 - στDe + X0τY2 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ -\
 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 τY0X2 + X1τY1 + σD123 - σD12
 τY1X1 + στD12 + 2στDe + X0τY1 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ +\
 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - τ - 1/2
 τY1X2 + X1τY0 + σD132 - σD13
 τY2X1 + στD12 - στDe + X0τY0 - Y2X2 - Y0X2 - X2Y2 - X2Y1 + 1
 τY2X2 + X1τY2 + σD132 + σD13 + σD123 + σD12 + 2σDe - τ - σ
 DeY0X1 + X1D13Y2
 DeY0X2 - X2D132Y1 - X2D13Y1 - X2D123Y1 - X2D12Y1 - X2DeY1 + X2Y1
 DeY1X1 + τσDe + X1D13Y1 - De
 DeY1X2 - X2D132Y0 - X2D13Y0 - X2D123Y0 - X2D12Y0 - X2DeY0 + X2Y0
 DeY2X1 + X1D13Y0
 DeY2X2 + στDe - X2D132Y2 - X2D13Y2 - X2D123Y2 - X2D12Y2 - X2DeY2 + X2Y2 - D\
e
 D12Y0X1 + X1D123Y2
 D12Y0X2 + X2D132Y1
 D12Y1X1 + X1D123Y1 - D12
 D12Y1X2 + στD12 + στDe + X2D132Y0 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ\
 + 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - 1/2
 D12Y2X1 + τσD12 + τσDe + X1D123Y0 - 1/2Y2X1 + 1/2Y1X1 - 1/2Y0X1 - 1/2τσ\
 - 1/2X1Y2 + 1/2X1Y1 - 1/2X1Y0 - 1/2
 D12Y2X2 + X2D132Y2 - D12
 D123Y0X1 + τσD12 + X1D12Y2 - Y0X1 - X1Y2
 D123Y0X2 + X2D13Y1
 D123Y1X1 + X1D12Y1 - D123
 D123Y1X2 - στD12 - στDe + X2D13Y0 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ\
 - 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 D123Y2X1 + X1D12Y0
 D123Y2X2 + X2D13Y2 - D123
 D13Y0X1 + X1DeY2
 D13Y0X2 - στD12 + X2D123Y1
 D13Y1X1 - τσDe + X1DeY1 - Y1X1 - X1Y1 - D13 + 1
 D13Y1X2 + X2D123Y0
 D13Y2X1 + X1DeY0
 D13Y2X2 + X2D123Y2 - D13
 D132Y0X1 - X1D132Y2 - X1D13Y2 - X1D123Y2 - X1D12Y2 - X1DeY2 + X1Y2
 D132Y0X2 + στD12 + X2D12Y1 - Y0X2 - X2Y1
 D132Y1X1 - X1D132Y1 - X1D13Y1 - X1D123Y1 - X1D12Y1 - X1DeY1 + X1Y1 - D132
 D132Y1X2 + X2D12Y0
 D132Y2X1 - τσD12 - τσDe - X1D132Y0 - X1D13Y0 - X1D123Y0 - X1D12Y0 - X1DeY\
0 - 1/2Y2X1 - 1/2Y1X1 + 1/2Y0X1 + 1/2τσ + 1/2X1Y2 - 1/2X1Y1 + 1/2X1Y0 + 1/2
 D132Y2X2 + X2D12Y2 - D132
 Y0X1X0 - X2Y1X1 - 2X1σD132 - X1σD13 - X1σD123 - X1σD12 - X1σDe + X0X2Y1 \
+ X1σ + X2
 Y0X1X2 + X1Y2X2 - X0Y0X1 - X0X1Y2
 Y0X1σ - X1σY1 + τD123 - τD12
 Y0X1τ + X1τY0 + σD132 - σD13
 Y0X1De - X1D132Y2 - X1D13Y2 - X1D123Y2 - X1D12Y2 - X1DeY2 + X1Y2
 Y0X1D12 - τσD12 + X1D132Y2
 Y0X1D123 + X1D13Y2
 Y0X1D13 + X1D123Y2
 Y0X1D132 + τσD12 + X1D12Y2 - Y0X1 - X1Y2
 Y0X2σ - σY0X1
 Y0X2τ - τσD12 - 2τσDe + X2τY2 - 1/2Y2X1 - 3/2Y1X1 + 1/2Y0X1 + 1/2τσ +\
 1/2X1Y2 - 3/2X1Y1 - 1/2X1Y0 + 3/2
 Y0X2De + X2D13Y1
 Y0X2D12 - στD12 + X2D123Y1
 Y0X2D123 + στD12 + X2D12Y1 - Y0X2 - X2Y1
 Y0X2D13 + X2DeY1
 Y0X2D132 - X2D132Y1 - X2D13Y1 - X2D123Y1 - X2D12Y1 - X2DeY1 + X2Y1
 Y1X1X0 - X2Y0X1 + X1σD13 - X1σD123 + X0X2Y2 - X0
 Y1X1X2 + X1Y1X2 - X0Y2X1 - X0X1Y0 - X2
 Y1X1σ - X1σY2 + τD132 + τD13 + τD123 + τD12 + 2τDe - τ - σ
 Y1X1τ + X1τY2 + σD132 + σD13 + σD123 + σD12 + 2σDe - τ - σ
 Y1X1De + τσDe + X1D13Y1 - De
 Y1X1D12 + X1D123Y1 - D12
 Y1X1D123 + X1D12Y1 - D123
 Y1X1D13 - τσDe + X1DeY1 - Y1X1 - X1Y1 - D13 + 1
 Y1X1D132 - X1D132Y1 - X1D13Y1 - X1D123Y1 - X1D12Y1 - X1DeY1 + X1Y1 - D132
 Y1X1Y2 - Y0Y2X1 - Y0X1Y0 + X1Y1Y2 - Y2
 Y1X2σ - σY2X1
 Y1X2τ + 2τσD12 + τσDe + X2τY1 - 1/2Y2X1 + 1/2Y1X1 - 3/2Y0X1 - 1/2τσ -\
 3/2X1Y2 + 1/2X1Y1 - 1/2X1Y0 - 1/2
 Y1X2De + X2D12Y0
 Y1X2D12 + X2DeY0
 Y1X2D123 - X2D132Y0 - X2D13Y0 - X2D123Y0 - X2D12Y0 - X2DeY0 + X2Y0
 Y1X2D13 + στD12 + στDe + X2D132Y0 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ\
 + 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - 1/2
 Y1X2D132 - στD12 - στDe + X2D13Y0 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ\
 - 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 Y1X2Y1 - Y0Y2X2 - Y0X2Y2 + X2Y0Y1 + Y0
 Y1Y0Y1 - Y0Y1Y0
 Y1Y2X1 + Y1X1Y0 - Y0X1Y1 + X1Y1Y0 + X1Y0Y2
 Y1Y2X2 + Y1X2Y2 - Y0X2Y0 - X2Y1Y0 - Y1
 Y2X1X0 - X2Y2X1 + X1σD12 - X1σDe + X0X2Y0 + X1
 Y2X1X2 + X1Y0X2 - X0Y1X1 - X0X1Y1 + X0
 Y2X1σ - X1σY0 + τD132 - τD13
 Y2X1τ + X1τY1 + σD123 - σD12
 Y2X1De + X1D12Y0
 Y2X1D12 + X1DeY0
 Y2X1D123 - τσD12 - τσDe - X1D132Y0 - X1D13Y0 - X1D123Y0 - X1D12Y0 - X1DeY\
0 - 1/2Y2X1 - 1/2Y1X1 + 1/2Y0X1 + 1/2τσ + 1/2X1Y2 - 1/2X1Y1 + 1/2X1Y0 + 1/2
 Y2X1D13 + X1D132Y0
 Y2X1D132 + X1D13Y0
 Y2X1Y1 - Y1Y0X1 - Y0Y2X1 - Y0X1Y0 + X1Y1Y2 + X1Y0Y1 - Y2
 Y2X1Y2 - Y0Y1X1 - Y0X1Y1 + X1Y0Y2 + Y0
 Y2X2σ - σY1X1
 Y2X2τ - τσD12 + τσDe + X2τY0 - τ
 Y2X2De + στDe - X2D132Y2 - X2D13Y2 - X2D123Y2 - X2D12Y2 - X2DeY2 + X2Y2 - D\
e
 Y2X2D12 + X2D132Y2 - D12
 Y2X2D123 + X2D13Y2 - D123
 Y2X2D13 + X2D123Y2 - D13
 Y2X2D132 + X2D12Y2 - D132
 Y2X2Y0 - Y1Y0X2 - Y0Y2X2 - Y0X2Y2 - X2Y1Y2
 Y2X2Y1 - Y0Y1X2 - Y0X2Y0 - X2Y1Y0 - X2Y0Y2 - Y1
 σY0Y1X2 + X1σY1Y0 + τD132Y1 + τD13Y1 + τD123Y1 - τD123Y0 + τD12Y1 + τ\
D12Y0 + 2τDeY1 - τY1
 σY0Y2X2 + X1σY1Y2 + τD132Y1 - τD13Y1 - τD123Y2 + τD12Y2 - σY0
 σY1Y0X2 + X1σY0Y1 - τD132Y1 + τD132Y0 + τD13Y1 + τD13Y0 + τD123Y0 + τ\
D12Y0 + 2τDeY0 - τY0
 τσY0X1 - X1τσY2 + D132 - D12
 τσY1X1 - X1τσY1 - τσ - D13 + De
 τσY2X1 - X1τσY0 + D132 + D13 + 2D123 + D12 + De - 1
 τY0Y1X1 + στD12Y2 + 2στD12Y1 - στDeY2 + στDeY1 + X0τY1Y0 + X0τY0Y2\
 - Y2X2Y2 + 1/2Y0Y2X2 + 1/2Y0Y1X2 - 1/2Y0X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2σÏ\
Y1 - X2Y1Y2 - τY0 + Y2 - 1/2Y0
 τY0Y1X2 - X1τY1Y0 + σD132Y1 + σD13Y1 + σD123Y1 - σD123Y0 + σD12Y1 + σ\
D12Y0 + 2σDeY1 - σY1
 τY0Y2X1 + στD12Y2 + 2στD12Y0 + 2στDeY2 + στDeY0 + X0τY1Y2 + X0τY0Y\
1 + 1/2Y2X2Y2 + 1/2Y1Y0X2 - 1/2Y1X2Y2 + 1/2Y1X2Y0 + 1/2Y0Y2X2 - 1/2Y0X2Y0 - 1/\
2στY2 - 1/2στY0 - 1/2X2Y1Y2 - 1/2X2Y1Y0 - 1/2X2Y0Y2 - 1/2X2Y0Y1 - 1/2Y2 - \
1/2Y0
 τY0Y2X2 - X1τY1Y2 + σD132Y1 - σD13Y1 - σD123Y2 + σD12Y2 - τY0
 τY1Y0X1 - στD12Y2 + στD12Y1 - 2στDeY2 - στDeY1 - X0τY1Y2 - 1/2Y2X2Y\
2 + 1/2Y1X2Y2 - Y0Y1X2 + 1/2Y0X2Y2 - Y0X2Y1 - Y0X2Y0 + 1/2στY2 + 1/2X2Y1Y2 +\
 1/2X2Y0Y2 + τY2 + 1/2Y2
 τY1Y0X2 - X1τY0Y1 - σD132Y1 + σD132Y0 + σD13Y1 + σD13Y0 + σD123Y0 + σ\
D12Y0 + 2σDeY0 - σY0
 DeY0Y1X1 + X1D13Y1Y0 + X1D13Y0Y2 - DeY0
 DeY0Y1X2 + στDeY1 + X2D132Y1Y0 + X2D13Y1Y0 + X2D123Y1Y0 + X2D12Y1Y0 + X2DeY\
1Y0 - X2Y1Y0
 DeY0Y2X1 + τσDeY2 + X1D13Y1Y2 + X1D13Y0Y1
 DeY0Y2X2 + X2D132Y1Y2 + X2D13Y1Y2 + X2D123Y1Y2 + X2D12Y1Y2 + X2DeY1Y2 - X2Y1Y\
2 - DeY0
 DeY1Y0X1 - τσDeY2 - X1D13Y1Y2 + DeY2
 DeY1Y0X2 + στDeY0 + X2D132Y0Y1 + X2D13Y0Y1 + X2D123Y0Y1 + X2D12Y0Y1 + X2DeY\
0Y1 - X2Y0Y1
 D12Y0Y1X1 + τσD12Y2 + τσDeY2 + X1D123Y1Y0 + X1D123Y0Y2 + 1/2Y0Y2X1 - 1/2Y\
0Y1X1 - 1/2Y0X1Y2 - 1/2Y0X1Y1 + 1/2Y0X1Y0 - 1/2τσY2 - D12Y0 + 1/2Y0
 D12Y0Y1X2 - X2D132Y1Y0
 D12Y0Y2X1 + X1D123Y1Y2 + X1D123Y0Y1
 D12Y0Y2X2 + στD12Y1 + στDeY1 - X2D132Y1Y2 - 1/2Y0Y2X2 + 1/2Y0Y1X2 - 1/2Y0\
X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2στY1 - D12Y0 + 1/2Y0
 D12Y1Y0X1 + τσD12Y1 + τσDeY1 - X1D123Y1Y2 - 1/2Y1Y0X1 + 1/2Y1X1Y1 - 1/2Y0\
Y2X1 - 1/2Y0X1Y1 - 1/2Y0X1Y0 - 1/2τσY1 + 1/2X1Y1Y2 + 1/2X1Y1Y0 + 1/2X1Y0Y2 +\
 D12Y2 - 1/2Y2 - 1/2Y1
 D12Y1Y0X2 - στD12Y1 - στDeY1 - X2D132Y0Y1 + 1/2Y0Y2X2 - 1/2Y0Y1X2 + 1/2Y0\
X2Y2 + 1/2Y0X2Y1 - 1/2Y0X2Y0 + 1/2στY1 - 1/2Y0
 D123Y0Y1X1 - τσD12Y1 + X1D12Y1Y0 + X1D12Y0Y2 + Y0X1Y1 - X1Y1Y0 - X1Y0Y2 - D\
123Y0
 D123Y0Y1X2 - X2D13Y1Y0
 D123Y0Y2X1 - τσD12Y0 + X1D12Y1Y2 + X1D12Y0Y1 + Y0X1Y0 - X1Y1Y2 - X1Y0Y1
 D123Y0Y2X2 - στD12Y1 - στDeY1 - X2D13Y1Y2 - 1/2Y0Y2X2 - 1/2Y0Y1X2 - 1/2Y0\
X2Y2 + 1/2Y0X2Y1 - 1/2Y0X2Y0 + 1/2στY1 - D123Y0 + 1/2Y0
 D123Y1Y0X1 - X1D12Y1Y2 + D123Y2
 D123Y1Y0X2 + στD12Y1 + στDeY1 - X2D13Y0Y1 + 1/2Y0Y2X2 + 1/2Y0Y1X2 + 1/2Y0\
X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2στY1 - 1/2Y0
 D13Y0Y1X1 + X1DeY1Y0 + X1DeY0Y2 - D13Y0
 D13Y0Y1X2 + στD12Y0 - X2D123Y1Y0
 D13Y0Y2X1 - τσDeY2 + X1DeY1Y2 + X1DeY0Y1 - Y0Y2X1 - Y0X1Y0
 D13Y0Y2X2 + στD12Y2 - X2D123Y1Y2 - D13Y0
 D13Y1Y0X1 + τσDeY2 - X1DeY1Y2 + Y0Y2X1 + Y0X1Y0 + D13Y2
 D13Y1Y0X2 - X2D123Y0Y1
 D132Y0Y1X1 - τσD12Y2 - τσDeY2 - X1D132Y1Y0 - X1D132Y0Y2 - X1D13Y1Y0 - X1D\
13Y0Y2 - X1D123Y1Y0 - X1D123Y0Y2 - X1D12Y1Y0 - X1D12Y0Y2 - X1DeY1Y0 - X1DeY0Y2\
 - 1/2Y0Y2X1 - 1/2Y0Y1X1 + 1/2Y0X1Y2 - 1/2Y0X1Y1 - 1/2Y0X1Y0 + 1/2τσY2 + X1Y\
1Y0 + X1Y0Y2 - D132Y0 + 1/2Y0
 D132Y0Y1X2 - στD12Y0 - X2D12Y1Y0 + Y0X2Y0 + X2Y1Y0
 D132Y0Y2X1 - X1D132Y1Y2 - X1D132Y0Y1 - X1D13Y1Y2 - X1D13Y0Y1 - X1D123Y1Y2 - X\
1D123Y0Y1 - X1D12Y1Y2 - X1D12Y0Y1 - X1DeY1Y2 - X1DeY0Y1 + X1Y1Y2 + X1Y0Y1
 D132Y0Y2X2 - στD12Y2 - X2D12Y1Y2 + Y0X2Y2 + X2Y1Y2 - D132Y0
 D132Y1Y0X1 - τσD12Y1 - τσDeY1 + X1D132Y1Y2 + X1D13Y1Y2 + X1D123Y1Y2 + X1D\
12Y1Y2 + X1DeY1Y2 - 1/2Y1Y0X1 - 1/2Y1X1Y1 - 1/2Y0Y2X1 + 1/2Y0X1Y1 - 1/2Y0X1Y0 \
+ 1/2τσY1 - 1/2X1Y1Y2 - 1/2X1Y1Y0 - 1/2X1Y0Y2 + D132Y2 - 1/2Y2 + 1/2Y1
 D132Y1Y0X2 - X2D12Y0Y1
 Y0X1Y0X1 + X1Y1X1Y0 - X1Y0
 Y0X1Y0X2 + X1Y1X2Y2 - X1Y0Y1X2 - X1Y0X2Y0 - X1X2Y1Y0 + X0Y0X1Y1 - X0X1Y1Y0 - \
X0X1Y0Y2 + τ^2D12 + τ^2De + 1/2σY2X1 + 1/2σY1X1 - 1/2σY0X1 + 1/2X2σY2 - \
1/2X2σY1 - 1/2X2σY0 - 1/2τ^2 - X1Y1 - 1/2σ
 Y0X1Y1X1 + X1Y0X1Y0 - Y0X1
 Y0X1Y1X2 - X1Y1Y0X2 - X1Y0Y2X2 + X0Y0X1Y0 - X0X1Y1Y2 - X0X1Y0Y1 - τ^2De - σ\
Y1X1 + X2σY1 + σ
 Y0X1Y2X1 + X1Y2X1Y0 + D132 + D13 + D12 + De - 1
 Y0X1Y2X2 + X0Y0X1Y2 - Y0X1 - X1Y2
 Y0X2Y0X1 + X2Y1Y0X1 + X0Y0X2Y2 + X0X2Y1Y2 - τD132
 Y0X2Y0X2 + X2Y1Y0X2 + X2Y0Y2X2 + X2Y0X2Y2 - X2Y0
 Y0X2Y1X1 + X0Y0X2Y1 - Y0X2 - X2Y1
 Y0X2Y1X2 + X2Y1X2Y0 - D132 - D13
 Y0X2Y2X1 - X2Y1X1Y0 + X2Y0X1Y1 + X1X0Y1Y0 + X1X0Y0Y2 + X0Y0X2Y0 + 2X0X2Y1Y0 +\
 X0X2Y0Y2 + τD132 + τD13 + τD123 + τD12 + τDe - τ
 Y0X2Y2X2 + X2Y0X2Y0 - Y0X2
 Y1X1Y0X1 + X1Y1Y0X1 + X1Y0Y2X1 + X1Y0X1Y0 - Y0X1
 Y1X1Y0X2 + X1Y1Y0X2 + X0Y1Y0X1 + X0Y0Y2X1 + X0Y0X1Y0 - X0X1Y1Y2 - τ^2D12 - Y\
0X2 + X0Y2
 Y1X1Y1X1 + X1Y1X1Y1 - 2Y1X1 - 2X1Y1 - D13 - De + 1
 Y1X1Y1X2 + X0Y2X1Y0 - Y1X2
 Y1X1Y1Y0 + Y1X1Y0Y2 + Y0Y1Y0X1 - Y0X1Y1Y2 + X1Y1Y0Y2 - Y1Y0
 Y1X1Y1Y2 + Y1X1Y0Y1 + Y0Y2X1Y0 + X1Y0Y1Y0 - Y1Y2 - Y0Y1
 Y1X2Y0X1 + X0Y2X2Y2 - X0Y2
 Y1X2Y0X2 + X2Y0X2Y1 - D123 - D12
 Y1X2Y2X1 + X2Y0Y2X1 + X0Y1Y0X2 + X0Y0Y2X2 + X0Y0X2Y2 - X0X2Y0Y1 - τD123 - X0\
Y0
 Y1X2Y2X2 + X2Y0Y2X2 + X2Y0X2Y2 - Y1X2 - X2Y0
 Y1Y0X1Y1 + Y0Y1Y0X1 - Y0X1Y1Y2 + X1Y1Y0Y2 - Y1Y0
 Y1Y0X2Y0 + Y0Y1Y0X2 - Y0X2Y0Y1 - X2Y0Y1Y0
 Y1Y0Y2X1 + Y1Y0X1Y0 + Y1X1Y0Y1 + Y0Y2X1Y0 + X1Y0Y1Y0 - Y0Y1
 Y1Y0Y2X2 + Y1Y0X2Y2 - Y1X2Y0Y1 - Y1Y0
 Y2X1Y0X1 + X1Y0X1Y2 - D132 - D12
 Y2X1Y0X2 + X0Y1X1Y1 - X0Y1
 Y2X1Y0Y1 + Y1Y0X1Y2 + Y0Y1X1Y0 + Y0X1Y1Y0
 Y2X1Y0Y2 + Y1Y0X1Y0 + Y0Y2X1Y0 + Y0Y1X1Y1 + X1Y0Y1Y0 - Y1Y2 - 2Y0Y1
 Y2X2Y2X1 + X0Y1X2Y0 - Y2X1
 Y2X2Y2X2 + X2Y2X2Y2 - 2Y2X2 - 2X2Y2 + D132 + D13 + D123 + D12
 σY0Y1Y0X2 - X1σY0Y1Y0 + τD132Y1Y0 - τD13Y1Y0 + τD123Y0Y1 - τD12Y0Y1
 τσY0Y1X1 - X1τσY1Y0 - X1τσY0Y2 - τσY0 + D132Y2 - D132Y1 + D13Y2 + 2D1\
23Y2 + D12Y2 + D12Y1 + DeY2 - Y2
 τσY0Y2X1 - X1τσY1Y2 - X1τσY0Y1 - D132Y0 - D13Y2 + D12Y0 + DeY2
 τσY1Y0X1 + X1τσY1Y2 + τσY2 + D132Y1 + D13Y2 + D13Y1 + 2D123Y1 + D12Y1 -\
 DeY2 + DeY1 - Y1
 τY0Y1Y0X1 - 2στD12Y1Y2 - στD12Y1Y0 - στD12Y0Y2 - στDeY1Y2 - 2στDeY\
1Y0 - 2στDeY0Y2 - X0τY1Y0Y2 - 1/2Y1Y0X2Y2 + 1/2Y1X2Y0Y2 - Y0Y2X2Y2 + 1/2Y0Y\
1Y0X2 - 1/2Y0Y1X2Y2 - 1/2Y0Y1X2Y0 + 1/2Y0X2Y1Y2 + 1/2Y0X2Y1Y0 - 1/2Y0X2Y0Y1 + \
1/2στY1Y2 + 1/2στY1Y0 + 1/2στY0Y2 + 1/2X2Y1Y0Y2 + 1/2X2Y0Y1Y2 + τY0Y2 +\
 Y0Y2
 τY0Y1Y0X2 + X1τY0Y1Y0 + σD132Y1Y0 - σD13Y1Y0 + σD123Y0Y1 - σD12Y0Y1
 DeY0Y1Y0X1 - τσDeY1Y0 - τσDeY0Y2 - X1D13Y1Y0Y2 + DeY0Y2
 DeY0Y1Y0X2 - X2D132Y0Y1Y0 - X2D13Y0Y1Y0 - X2D123Y0Y1Y0 - X2D12Y0Y1Y0 - X2DeY0\
Y1Y0 + X2Y0Y1Y0
 D12Y0Y1Y0X1 - X1D123Y1Y0Y2 + D12Y0Y2
 D12Y0Y1Y0X2 + στD12Y1Y0 + στDeY1Y0 + X2D132Y0Y1Y0 - 1/2Y0Y1Y0X2 + 1/2Y0Y1\
X2Y0 - 1/2Y0X2Y1Y0 + 1/2Y0X2Y0Y1 - 1/2στY1Y0
 D123Y0Y1Y0X1 + τσD12Y1Y2 - X1D12Y1Y0Y2 - Y0X1Y1Y2 + X1Y1Y0Y2 + D123Y0Y2
 D123Y0Y1Y0X2 - στD12Y1Y0 - στDeY1Y0 + X2D13Y0Y1Y0 - 1/2Y0Y1Y0X2 - 1/2Y0Y1\
X2Y0 + 1/2Y0X2Y1Y0 + 1/2Y0X2Y0Y1 + 1/2στY1Y0
 D13Y0Y1Y0X1 + τσDeY1Y0 + τσDeY0Y2 - X1DeY1Y0Y2 - Y0Y1Y0X1 + Y0X1Y1Y2 + D1\
3Y0Y2 - Y0Y2
 D13Y0Y1Y0X2 - στD12Y0Y1 + X2D123Y0Y1Y0
 D132Y0Y1Y0X1 + X1D132Y1Y0Y2 + X1D13Y1Y0Y2 + X1D123Y1Y0Y2 + X1D12Y1Y0Y2 + X1De\
Y1Y0Y2 - X1Y1Y0Y2 + D132Y0Y2
 D132Y0Y1Y0X2 + στD12Y0Y1 + X2D12Y0Y1Y0 - Y0X2Y0Y1 - X2Y0Y1Y0
 Y0X1Y0Y1X1 - X1Y1Y0X1Y0 - X1Y1X1Y0Y1 - X1Y0Y2X1Y0 - X1Y0Y1X1Y1 - Y0X1Y0 + X1Y\
1Y2 + 3X1Y0Y1 + D132Y2 + D13Y2 + D12Y2 + DeY2 - Y2
 Y0X1Y0Y1X2 - X1Y1Y0X2Y2 + X1Y1X2Y0Y1 - X0Y0X1Y1Y0 - X0X1Y0Y1Y2 - τ^2D12Y0 - \
τ^2DeY0 - 1/2σY2X1Y0 - 1/2σY1X1Y0 + 1/2σY0X1Y0 + 1/2X2σY1Y2 + 1/2X2σY1Y0\
 + 1/2X2σY0Y1 + 1/2τ^2Y0 + X1Y1Y0 + 1/2σY0
 Y0X1Y0Y2X1 + X1Y0X1Y0Y2
 Y0X1Y0Y2X2 + X1Y0Y1X2Y2 - X1Y0X2Y1Y0 - X0Y0X1Y1Y2 + X0X1Y1Y0Y2 - τ^2D12Y2 - \
τ^2DeY2 - τ^2DeY1 - σY1X1Y1 - 1/2σY0Y2X1 - 1/2σY0Y1X1 + 1/2σY0X1Y2 - 1/2\
σY0X1Y1 - 1/2σY0X1Y0 - Y0X1Y0 + 1/2τ^2Y2 + X1Y1Y2 + σY1 + 1/2σY0
 Y0X1Y1Y0X1 - X1Y1Y0X1Y2 - X1Y0Y1X1Y0 - X1Y0X1Y1Y0 - X1Y0X1Y0Y2 + Y0X1Y2 + D13\
2Y1 + D13Y1 + D12Y1 + DeY1 - Y1
 Y0X1Y1Y0X2 - X1Y0Y1X2Y2 + X1Y0X2Y1Y0 - X0Y0X1Y0Y1 - X0X1Y1Y0Y2 + τ^2DeY1 + Ï\
Y1X1Y1 + X1Y0Y1 - σY1
 Y0X2Y0Y1X1 + X2Y0Y1Y0X1 + X0Y0X2Y1Y0 + X0Y0X2Y0Y2 + X0X2Y1Y0Y2 - Y0X2Y0 + τD\
132Y2 + τD132Y1 + τD13Y2 + τD123Y2 + τD12Y2 + τDeY2 - X2Y1Y0 - τY2
 Y0X2Y0Y1X2 + X2Y0X2Y0Y1
 Y0X2Y0Y2X1 - X2Y1Y0X1Y0 - X2Y1X1Y0Y1 - X2Y0Y2X1Y0 + X1X0Y0Y1Y0 + X0Y0X2Y1Y2 +\
 X0Y0X2Y0Y1 + 2X0X2Y0Y1Y0 + τD132Y0 + X2Y0Y1
 Y0X2Y0Y2X2 - X2Y1Y0X2Y2 + X2Y1X2Y0Y1 - X2Y0Y2X2Y2 - Y0X2Y0 + X2Y0Y2 - D132Y1 \
- D13Y1
 Y0X2Y1Y0X1 - X0Y0X2Y1Y2 + Y0X2Y2 + τD132Y1 + τD13Y1 + τD123Y1 + τD12Y1 + \
τDeY1 + X2Y1Y2 - τY1
 Y0X2Y1Y0X2 - X2Y1X2Y0Y1 + D132Y1 + D13Y1
 Y1X1Y0Y1X1 + X1Y0X1Y1Y2 - Y1X1Y0 - Y0Y1X1 - X1Y1Y0 - X1Y0Y2 + Y0
 Y1X1Y0Y1X2 + X1Y0Y1Y0X2 - X0Y1Y0X1Y0 - X0Y0Y2X1Y0 - X0X1Y0Y1Y0 + τ^2D12Y0 - \
τ^2DeY1 - Y0Y1X2 + X0Y1Y2 + X0Y0Y1
 Y1X1Y0Y1Y2 - Y0Y1Y0X1Y0 - Y0X1Y0Y1Y0 + X1Y0Y1Y0Y2
 Y1X1Y0Y2X1 - X1Y1Y0X1Y0 - X1Y1X1Y0Y1 - 2X1Y0Y2X1Y0 - Y0Y2X1 + X1Y0Y1 - D13Y2 \
- DeY2
 Y1X1Y0Y2X2 - X1Y1Y0X2Y2 + X1Y1X2Y0Y1 - X0Y1Y0X1Y2 + τ^2D12Y2 - Y1X1Y0 - Y0Y2\
X2 + Y0
 Y1X2Y0Y1X1 + X0Y1Y0X2Y2 + X0Y0Y2X2Y2 + X0Y0Y1X2Y0 - X0X2Y0Y1Y2 - Y1X2Y0 - τD\
123Y2 - X0Y0Y2
 Y1X2Y0Y1X2 - X2Y0X2Y1Y0 + D123Y0 + D12Y0
 Y1X2Y0Y1Y0 - Y0Y1Y0X2Y1
 Y1X2Y0Y2X1 + X0Y1Y0X2Y1 + X0Y0Y1X2Y2 + X0Y0X2Y0Y2 - τD13Y2
 Y1X2Y0Y2X2 - X2Y0X2Y1Y2 - Y1X2Y0 + D123Y2 + D12Y2
 Y1Y0X1Y0Y2 - Y0Y1Y0X1Y0 - Y0Y1X1Y0Y1 - 2Y0X1Y0Y1Y0 + X1Y0Y1Y0Y2
 Y1Y0X2Y1Y0 - Y0Y1X2Y0Y1
 τσY0Y1Y0X1 + X1τσY1Y0Y2 + τσY0Y2 + D132Y1Y2 + D13Y1Y0 + D13Y0Y2 - D12Y1\
Y2 - DeY1Y0 - DeY0Y2
 Y0X1Y0Y1Y0X1 + X1Y0Y1Y0X1Y0 + Y0X1Y0Y2 - X1Y0Y1Y2
 Y0X1Y0Y1Y0X2 + X1Y0Y1Y0X2Y2 - X1Y0Y1X2Y0Y1 + X0Y0X1Y0Y1Y0 - X0X1Y0Y1Y0Y2 + τ\
^2D12Y0Y1 - τ^2DeY1Y0 + τ^2DeY0Y1 - 1/2σY1Y0X1Y2 + σY1X1Y0Y2 + 1/2σY1X1Y0\
Y1 + σY0Y1Y0X1 - 1/2σY0Y1X1Y0 - σY0X1Y1Y2 - 1/2σY0X1Y1Y0 - 1/2σY0X1Y0Y1 -\
 1/2X2σY1Y0Y2 - 1/2X2σY0Y1Y0 - 1/2τ^2Y0Y1 - X1Y0Y1Y0 - 1/2σY0Y1
 Y0X2Y0Y1Y0X1 - X0Y0X2Y1Y0Y2 + Y0X2Y0Y2 - τD132Y1Y2 + X2Y1Y0Y2
 Y0X2Y0Y1Y0X2 + X2Y0Y1Y0X2Y1 - D132Y1Y0 - D13Y1Y0
 Y1X1Y0Y1Y0X1 + X1Y0Y1Y0X1Y2 + Y1X1Y0Y2 - Y0Y1Y0X1 + X1Y1Y0Y2 + D13Y1Y0 + D13Y\
0Y2 + DeY1Y0 + DeY0Y2 - Y0Y2
 Y1X1Y0Y1Y0X2 + X0Y1Y0X1Y0Y1 - X0Y0Y1Y0X1Y2 - τ^2D12Y0Y1 - Y0Y1Y0X2 + X0Y1Y0Y\
2
 Y1X1Y0Y1Y0Y2 + Y0Y1Y0X1Y0Y1
 Y1Y0X1Y0Y1Y0 + Y0Y1Y0X1Y0Y1
 Y1Y0X1Y0Y1Y2 + Y0Y1X1Y0Y1Y0

In [160]:
Length( BaseQA(J_QG, 14, 0) );

5184

In [161]:
DimQA(J_QG, 14);

5184

In [162]:
12*6*6*12;

5184

In [163]:
DimQA(J_QG, 14)=12*6*6*12;

true

In [164]:
PrintNPList( BaseQA(J_QG, 14, 0) );

 1
 X0
 X1
 X2
 σ
 τ
 De
 D12
 D123
 D13
 D132
 Y0
 Y1
 Y2
 X0X1
 X0X2
 X0σ
 X0τ
 X0De
 X0D12
 X0D123
 X0D13
 X0D132
 X0Y0
 X0Y1
 X0Y2
 X1X0
 X1X2
 X1σ
 X1τ
 X1De
 X1D12
 X1D123
 X1D13
 X1D132
 X1Y0
 X1Y1
 X1Y2
 X2σ
 X2τ
 X2De
 X2D12
 X2D123
 X2D13
 X2D132
 X2Y0
 X2Y1
 X2Y2
 στ
 σDe
 σD12
 σD123
 σD13
 σD132
 σY0
 σY1
 σY2
 τσ
 τ^2
 τDe
 τD12
 τD123
 τD13
 τD132
 τY0
 τY1
 τY2
 DeY0
 DeY1
 DeY2
 D12Y0
 D12Y1
 D12Y2
 D123Y0
 D123Y1
 D123Y2
 D13Y0
 D13Y1
 D13Y2
 D132Y0
 D132Y1
 D132Y2
 Y0X1
 Y0X2
 Y0Y1
 Y0Y2
 Y1X1
 Y1X2
 Y1Y0
 Y1Y2
 Y2X1
 Y2X2
 X0X1X0
 X0X1X2
 X0X1σ
 X0X1τ
 X0X1De
 X0X1D12
 X0X1D123
 X0X1D13
 X0X1D132
 X0X1Y0
 X0X1Y1
 X0X1Y2
 X0X2σ
 X0X2τ
 X0X2De
 X0X2D12
 X0X2D123
 X0X2D13
 X0X2D132
 X0X2Y0
 X0X2Y1
 X0X2Y2
 X0στ
 X0σDe
 X0σD12
 X0σD123
 X0σD13
 X0σD132
 X0σY0
 X0σY1
 X0σY2
 X0τσ
 X0τ^2
 X0τDe
 X0τD12
 X0τD123
 X0τD13
 X0τD132
 X0τY0
 X0τY1
 X0τY2
 X0DeY0
 X0DeY1
 X0DeY2
 X0D12Y0
 X0D12Y1
 X0D12Y2
 X0D123Y0
 X0D123Y1
 X0D123Y2
 X0D13Y0
 X0D13Y1
 X0D13Y2
 X0D132Y0
 X0D132Y1
 X0D132Y2
 X0Y0X1
 X0Y0X2
 X0Y0Y1
 X0Y0Y2
 X0Y1X1
 X0Y1X2
 X0Y1Y0
 X0Y1Y2
 X0Y2X1
 X0Y2X2
 X1X0X2
 X1X0σ
 X1X0τ
 X1X0De
 X1X0D12
 X1X0D123
 X1X0D13
 X1X0D132
 X1X0Y0
 X1X0Y1
 X1X0Y2
 X1X2σ
 X1X2τ
 X1X2De
 X1X2D12
 X1X2D123
 X1X2D13
 X1X2D132
 X1X2Y0
 X1X2Y1
 X1X2Y2
 X1στ
 X1σDe
 X1σD12
 X1σD123
 X1σD13
 X1σD132
 X1σY0
 X1σY1
 X1σY2
 X1τσ
 X1τ^2
 X1τDe
 X1τD12
 X1τD123
 X1τD13
 X1τD132
 X1τY0
 X1τY1
 X1τY2
 X1DeY0
 X1DeY1
 X1DeY2
 X1D12Y0
 X1D12Y1
 X1D12Y2
 X1D123Y0
 X1D123Y1
 X1D123Y2
 X1D13Y0
 X1D13Y1
 X1D13Y2
 X1D132Y0
 X1D132Y1
 X1D132Y2
 X1Y0X1
 X1Y0X2
 X1Y0Y1
 X1Y0Y2
 X1Y1X1
 X1Y1X2
 X1Y1Y0
 X1Y1Y2
 X1Y2X1
 X1Y2X2
 X2στ
 X2σDe
 X2σD12
 X2σD123
 X2σD13
 X2σD132
 X2σY0
 X2σY1
 X2σY2
 X2τσ
 X2τ^2
 X2τDe
 X2τD12
 X2τD123
 X2τD13
 X2τD132
 X2τY0
 X2τY1
 X2τY2
 X2DeY0
 X2DeY1
 X2DeY2
 X2D12Y0
 X2D12Y1
 X2D12Y2
 X2D123Y0
 X2D123Y1
 X2D123Y2
 X2D13Y0
 X2D13Y1
 X2D13Y2
 X2D132Y0
 X2D132Y1
 X2D132Y2
 X2Y0X1
 X2Y0X2
 X2Y0Y1
 X2Y0Y2
 X2Y1X1
 X2Y1X2
 X2Y1Y0
 X2Y1Y2
 X2Y2X1
 X2Y2X2
 στDe
 στD12
 στY0
 στY1
 στY2
 σDeY0
 σDeY1
 σDeY2
 σD12Y0
 σD12Y1
 σD12Y2
 σD123Y0
 σD123Y1
 σD123Y2
 σD13Y0
 σD13Y1
 σD13Y2
 σD132Y0
 σD132Y1
 σD132Y2
 σY0X1
 σY0Y1
 σY0Y2
 σY1X1
 σY1Y0
 σY1Y2
 σY2X1
 τσDe
 τσD12
 τσY0
 τσY1
 τσY2
 τ^2De
 τ^2D12
 τ^2Y0
 τ^2Y1
 τ^2Y2
 τDeY0
 τDeY1
 τDeY2
 τD12Y0
 τD12Y1
 τD12Y2
 τD123Y0
 τD123Y1
 τD123Y2
 τD13Y0
 τD13Y1
 τD13Y2
 τD132Y0
 τD132Y1
 τD132Y2
 τY0Y1
 τY0Y2
 τY1Y0
 τY1Y2
 DeY0Y1
 DeY0Y2
 DeY1Y0
 DeY1Y2
 D12Y0Y1
 D12Y0Y2
 D12Y1Y0
 D12Y1Y2
 D123Y0Y1
 D123Y0Y2
 D123Y1Y0
 D123Y1Y2
 D13Y0Y1
 D13Y0Y2
 D13Y1Y0
 D13Y1Y2
 D132Y0Y1
 D132Y0Y2
 D132Y1Y0
 D132Y1Y2
 Y0X1Y0
 Y0X1Y1
 Y0X1Y2
 Y0X2Y0
 Y0X2Y1
 Y0X2Y2
 Y0Y1X1
 Y0Y1X2
 Y0Y1Y0
 Y0Y1Y2
 Y0Y2X1
 Y0Y2X2
 Y1X1Y0
 Y1X1Y1
 Y1X2Y0
 Y1X2Y2
 Y1Y0X1
 Y1Y0X2
 Y1Y0Y2
 Y2X1Y0
 Y2X2Y2
 X0X1X0X2
 X0X1X0σ
 X0X1X0τ
 X0X1X0De
 X0X1X0D12
 X0X1X0D123
 X0X1X0D13
 X0X1X0D132
 X0X1X0Y0
 X0X1X0Y1
 X0X1X0Y2
 X0X1X2σ
 X0X1X2τ
 X0X1X2De
 X0X1X2D12
 X0X1X2D123
 X0X1X2D13
 X0X1X2D132
 X0X1X2Y0
 X0X1X2Y1
 X0X1X2Y2
 X0X1στ
 X0X1σDe
 X0X1σD12
 X0X1σD123
 X0X1σD13
 X0X1σD132
 X0X1σY0
 X0X1σY1
 X0X1σY2
 X0X1τσ
 X0X1τ^2
 X0X1τDe
 X0X1τD12
 X0X1τD123
 X0X1τD13
 X0X1τD132
 X0X1τY0
 X0X1τY1
 X0X1τY2
 X0X1DeY0
 X0X1DeY1
 X0X1DeY2
 X0X1D12Y0
 X0X1D12Y1
 X0X1D12Y2
 X0X1D123Y0
 X0X1D123Y1
 X0X1D123Y2
 X0X1D13Y0
 X0X1D13Y1
 X0X1D13Y2
 X0X1D132Y0
 X0X1D132Y1
 X0X1D132Y2
 X0X1Y0X1
 X0X1Y0X2
 X0X1Y0Y1
 X0X1Y0Y2
 X0X1Y1X1
 X0X1Y1X2
 X0X1Y1Y0
 X0X1Y1Y2
 X0X1Y2X1
 X0X1Y2X2
 X0X2στ
 X0X2σDe
 X0X2σD12
 X0X2σD123
 X0X2σD13
 X0X2σD132
 X0X2σY0
 X0X2σY1
 X0X2σY2
 X0X2τσ
 X0X2τ^2
 X0X2τDe
 X0X2τD12
 X0X2τD123
 X0X2τD13
 X0X2τD132
 X0X2τY0
 X0X2τY1
 X0X2τY2
 X0X2DeY0
 X0X2DeY1
 X0X2DeY2
 X0X2D12Y0
 X0X2D12Y1
 X0X2D12Y2
 X0X2D123Y0
 X0X2D123Y1
 X0X2D123Y2
 X0X2D13Y0
 X0X2D13Y1
 X0X2D13Y2
 X0X2D132Y0
 X0X2D132Y1
 X0X2D132Y2
 X0X2Y0X1
 X0X2Y0X2
 X0X2Y0Y1
 X0X2Y0Y2
 X0X2Y1X1
 X0X2Y1X2
 X0X2Y1Y0
 X0X2Y1Y2
 X0X2Y2X1
 X0X2Y2X2
 X0στDe
 X0στD12
 X0στY0
 X0στY1
 X0στY2
 X0σDeY0
 X0σDeY1
 X0σDeY2
 X0σD12Y0
 X0σD12Y1
 X0σD12Y2
 X0σD123Y0
 X0σD123Y1
 X0σD123Y2
 X0σD13Y0
 X0σD13Y1
 X0σD13Y2
 X0σD132Y0
 X0σD132Y1
 X0σD132Y2
 X0σY0X1
 X0σY0Y1
 X0σY0Y2
 X0σY1X1
 X0σY1Y0
 X0σY1Y2
 X0σY2X1
 X0τσDe
 X0τσD12
 X0τσY0
 X0τσY1
 X0τσY2
 X0τ^2De
 X0τ^2D12
 X0τ^2Y0
 X0τ^2Y1
 X0τ^2Y2
 X0τDeY0
 X0τDeY1
 X0τDeY2
 X0τD12Y0
 X0τD12Y1
 X0τD12Y2
 X0τD123Y0
 X0τD123Y1
 X0τD123Y2
 X0τD13Y0
 X0τD13Y1
 X0τD13Y2
 X0τD132Y0
 X0τD132Y1
 X0τD132Y2
 X0τY0Y1
 X0τY0Y2
 X0τY1Y0
 X0τY1Y2
 X0DeY0Y1
 X0DeY0Y2
 X0DeY1Y0
 X0DeY1Y2
 X0D12Y0Y1
 X0D12Y0Y2
 X0D12Y1Y0
 X0D12Y1Y2
 X0D123Y0Y1
 X0D123Y0Y2
 X0D123Y1Y0
 X0D123Y1Y2
 X0D13Y0Y1
 X0D13Y0Y2
 X0D13Y1Y0
 X0D13Y1Y2
 X0D132Y0Y1
 X0D132Y0Y2
 X0D132Y1Y0
 X0D132Y1Y2
 X0Y0X1Y0
 X0Y0X1Y1
 X0Y0X1Y2
 X0Y0X2Y0
 X0Y0X2Y1
 X0Y0X2Y2
 X0Y0Y1X1
 X0Y0Y1X2
 X0Y0Y1Y0
 X0Y0Y1Y2
 X0Y0Y2X1
 X0Y0Y2X2
 X0Y1X1Y0
 X0Y1X1Y1
 X0Y1X2Y0
 X0Y1X2Y2
 X0Y1Y0X1
 X0Y1Y0X2
 X0Y1Y0Y2
 X0Y2X1Y0
 X0Y2X2Y2
 X1X0X2σ
 X1X0X2τ
 X1X0X2De
 X1X0X2D12
 X1X0X2D123
 X1X0X2D13
 X1X0X2D132
 X1X0X2Y0
 X1X0X2Y1
 X1X0X2Y2
 X1X0στ
 X1X0σDe
 X1X0σD12
 X1X0σD123
 X1X0σD13
 X1X0σD132
 X1X0σY0
 X1X0σY1
 X1X0σY2
 X1X0τσ
 X1X0τ^2
 X1X0τDe
 X1X0τD12
 X1X0τD123
 X1X0τD13
 X1X0τD132
 X1X0τY0
 X1X0τY1
 X1X0τY2
 X1X0DeY0
 X1X0DeY1
 X1X0DeY2
 X1X0D12Y0
 X1X0D12Y1
 X1X0D12Y2
 X1X0D123Y0
 X1X0D123Y1
 X1X0D123Y2
 X1X0D13Y0
 X1X0D13Y1
 X1X0D13Y2
 X1X0D132Y0
 X1X0D132Y1
 X1X0D132Y2
 X1X0Y0X1
 X1X0Y0X2
 X1X0Y0Y1
 X1X0Y0Y2
 X1X0Y1X1
 X1X0Y1X2
 X1X0Y1Y0
 X1X0Y1Y2
 X1X0Y2X1
 X1X0Y2X2
 X1X2στ
 X1X2σDe
 X1X2σD12
 X1X2σD123
 X1X2σD13
 X1X2σD132
 X1X2σY0
 X1X2σY1
 X1X2σY2
 X1X2τσ
 X1X2τ^2
 X1X2τDe
 X1X2τD12
 X1X2τD123
 X1X2τD13
 X1X2τD132
 X1X2τY0
 X1X2τY1
 X1X2τY2
 X1X2DeY0
 X1X2DeY1
 X1X2DeY2
 X1X2D12Y0
 X1X2D12Y1
 X1X2D12Y2
 X1X2D123Y0
 X1X2D123Y1
 X1X2D123Y2
 X1X2D13Y0
 X1X2D13Y1
 X1X2D13Y2
 X1X2D132Y0
 X1X2D132Y1
 X1X2D132Y2
 X1X2Y0X1
 X1X2Y0X2
 X1X2Y0Y1
 X1X2Y0Y2
 X1X2Y1X1
 X1X2Y1X2
 X1X2Y1Y0
 X1X2Y1Y2
 X1X2Y2X1
 X1X2Y2X2
 X1στDe
 X1στD12
 X1στY0
 X1στY1
 X1στY2
 X1σDeY0
 X1σDeY1
 X1σDeY2
 X1σD12Y0
 X1σD12Y1
 X1σD12Y2
 X1σD123Y0
 X1σD123Y1
 X1σD123Y2
 X1σD13Y0
 X1σD13Y1
 X1σD13Y2
 X1σD132Y0
 X1σD132Y1
 X1σD132Y2
 X1σY0X1
 X1σY0Y1
 X1σY0Y2
 X1σY1X1
 X1σY1Y0
 X1σY1Y2
 X1σY2X1
 X1τσDe
 X1τσD12
 X1τσY0
 X1τσY1
 X1τσY2
 X1τ^2De
 X1τ^2D12
 X1τ^2Y0
 X1τ^2Y1
 X1τ^2Y2
 X1τDeY0
 X1τDeY1
 X1τDeY2
 X1τD12Y0
 X1τD12Y1
 X1τD12Y2
 X1τD123Y0
 X1τD123Y1
 X1τD123Y2
 X1τD13Y0
 X1τD13Y1
 X1τD13Y2
 X1τD132Y0
 X1τD132Y1
 X1τD132Y2
 X1τY0Y1
 X1τY0Y2
 X1τY1Y0
 X1τY1Y2
 X1DeY0Y1
 X1DeY0Y2
 X1DeY1Y0
 X1DeY1Y2
 X1D12Y0Y1
 X1D12Y0Y2
 X1D12Y1Y0
 X1D12Y1Y2
 X1D123Y0Y1
 X1D123Y0Y2
 X1D123Y1Y0
 X1D123Y1Y2
 X1D13Y0Y1
 X1D13Y0Y2
 X1D13Y1Y0
 X1D13Y1Y2
 X1D132Y0Y1
 X1D132Y0Y2
 X1D132Y1Y0
 X1D132Y1Y2
 X1Y0X1Y0
 X1Y0X1Y1
 X1Y0X1Y2
 X1Y0X2Y0
 X1Y0X2Y1
 X1Y0X2Y2
 X1Y0Y1X1
 X1Y0Y1X2
 X1Y0Y1Y0
 X1Y0Y1Y2
 X1Y0Y2X1
 X1Y0Y2X2
 X1Y1X1Y0
 X1Y1X1Y1
 X1Y1X2Y0
 X1Y1X2Y2
 X1Y1Y0X1
 X1Y1Y0X2
 X1Y1Y0Y2
 X1Y2X1Y0
 X1Y2X2Y2
 X2στDe
 X2στD12
 X2στY0
 X2στY1
 X2στY2
 X2σDeY0
 X2σDeY1
 X2σDeY2
 X2σD12Y0
 X2σD12Y1
 X2σD12Y2
 X2σD123Y0
 X2σD123Y1
 X2σD123Y2
 X2σD13Y0
 X2σD13Y1
 X2σD13Y2
 X2σD132Y0
 X2σD132Y1
 X2σD132Y2
 X2σY0X1
 X2σY0Y1
 X2σY0Y2
 X2σY1X1
 X2σY1Y0
 X2σY1Y2
 X2σY2X1
 X2τσDe
 X2τσD12
 X2τσY0
 X2τσY1
 X2τσY2
 X2τ^2De
 X2τ^2D12
 X2τ^2Y0
 X2τ^2Y1
 X2τ^2Y2
 X2τDeY0
 X2τDeY1
 X2τDeY2
 X2τD12Y0
 X2τD12Y1
 X2τD12Y2
 X2τD123Y0
 X2τD123Y1
 X2τD123Y2
 X2τD13Y0
 X2τD13Y1
 X2τD13Y2
 X2τD132Y0
 X2τD132Y1
 X2τD132Y2
 X2τY0Y1
 X2τY0Y2
 X2τY1Y0
 X2τY1Y2
 X2DeY0Y1
 X2DeY0Y2
 X2DeY1Y0
 X2DeY1Y2
 X2D12Y0Y1
 X2D12Y0Y2
 X2D12Y1Y0
 X2D12Y1Y2
 X2D123Y0Y1
 X2D123Y0Y2
 X2D123Y1Y0
 X2D123Y1Y2
 X2D13Y0Y1
 X2D13Y0Y2
 X2D13Y1Y0
 X2D13Y1Y2
 X2D132Y0Y1
 X2D132Y0Y2
 X2D132Y1Y0
 X2D132Y1Y2
 X2Y0X1Y0
 X2Y0X1Y1
 X2Y0X1Y2
 X2Y0X2Y0
 X2Y0X2Y1
 X2Y0X2Y2
 X2Y0Y1X1
 X2Y0Y1X2
 X2Y0Y1Y0
 X2Y0Y1Y2
 X2Y0Y2X1
 X2Y0Y2X2
 X2Y1X1Y0
 X2Y1X1Y1
 X2Y1X2Y0
 X2Y1X2Y2
 X2Y1Y0X1
 X2Y1Y0X2
 X2Y1Y0Y2
 X2Y2X1Y0
 X2Y2X2Y2
 στDeY0
 στDeY1
 στDeY2
 στD12Y0
 στD12Y1
 στD12Y2
 στY0Y1
 στY0Y2
 στY1Y0
 στY1Y2
 σDeY0Y1
 σDeY0Y2
 σDeY1Y0
 σDeY1Y2
 σD12Y0Y1
 σD12Y0Y2
 σD12Y1Y0
 σD12Y1Y2
 σD123Y0Y1
 σD123Y0Y2
 σD123Y1Y0
 σD123Y1Y2
 σD13Y0Y1
 σD13Y0Y2
 σD13Y1Y0
 σD13Y1Y2
 σD132Y0Y1
 σD132Y0Y2
 σD132Y1Y0
 σD132Y1Y2
 σY0X1Y0
 σY0X1Y1
 σY0X1Y2
 σY0Y1X1
 σY0Y1Y0
 σY0Y1Y2
 σY0Y2X1
 σY1X1Y0
 σY1X1Y1
 σY1Y0X1
 σY1Y0Y2
 σY2X1Y0
 τσDeY0
 τσDeY1
 τσDeY2
 τσD12Y0
 τσD12Y1
 τσD12Y2
 τσY0Y1
 τσY0Y2
 τσY1Y0
 τσY1Y2
 τ^2DeY0
 τ^2DeY1
 τ^2DeY2
 τ^2D12Y0
 τ^2D12Y1
 τ^2D12Y2
 τ^2Y0Y1
 τ^2Y0Y2
 τ^2Y1Y0
 τ^2Y1Y2
 τDeY0Y1
 τDeY0Y2
 τDeY1Y0
 τDeY1Y2
 τD12Y0Y1
 τD12Y0Y2
 τD12Y1Y0
 τD12Y1Y2
 τD123Y0Y1
 τD123Y0Y2
 τD123Y1Y0
 τD123Y1Y2
 τD13Y0Y1
 τD13Y0Y2
 τD13Y1Y0
 τD13Y1Y2
 τD132Y0Y1
 τD132Y0Y2
 τD132Y1Y0
 τD132Y1Y2
 τY0Y1Y0
 τY0Y1Y2
 τY1Y0Y2
 DeY0Y1Y0
 DeY0Y1Y2
 DeY1Y0Y2
 D12Y0Y1Y0
 D12Y0Y1Y2
 D12Y1Y0Y2
 D123Y0Y1Y0
 D123Y0Y1Y2
 D123Y1Y0Y2
 D13Y0Y1Y0
 D13Y0Y1Y2
 D13Y1Y0Y2
 D132Y0Y1Y0
 D132Y0Y1Y2
 D132Y1Y0Y2
 Y0X1Y0Y1
 Y0X1Y0Y2
 Y0X1Y1Y0
 Y0X1Y1Y2
 Y0X2Y0Y1
 Y0X2Y0Y2
 Y0X2Y1Y0
 Y0X2Y1Y2
 Y0Y1X1Y0
 Y0Y1X1Y1
 Y0Y1X2Y0
 Y0Y1X2Y2
 Y0Y1Y0X1
 Y0Y1Y0X2
 Y0Y1Y0Y2
 Y0Y2X1Y0
 Y0Y2X2Y2
 Y1X1Y0Y1
 Y1X1Y0Y2
 Y1X2Y0Y1
 Y1X2Y0Y2
 Y1Y0X1Y0
 Y1Y0X1Y2
 Y1Y0X2Y1
 Y1Y0X2Y2
 X0X1X0X2σ
 X0X1X0X2τ
 X0X1X0X2De
 X0X1X0X2D12
 X0X1X0X2D123
 X0X1X0X2D13
 X0X1X0X2D132
 X0X1X0X2Y0
 X0X1X0X2Y1
 X0X1X0X2Y2
 X0X1X0στ
 X0X1X0σDe
 X0X1X0σD12
 X0X1X0σD123
 X0X1X0σD13
 X0X1X0σD132
 X0X1X0σY0
 X0X1X0σY1
 X0X1X0σY2
 X0X1X0τσ
 X0X1X0τ^2
 X0X1X0τDe
 X0X1X0τD12
 X0X1X0τD123
 X0X1X0τD13
 X0X1X0τD132
 X0X1X0τY0
 X0X1X0τY1
 X0X1X0τY2
 X0X1X0DeY0
 X0X1X0DeY1
 X0X1X0DeY2
 X0X1X0D12Y0
 X0X1X0D12Y1
 X0X1X0D12Y2
 X0X1X0D123Y0
 X0X1X0D123Y1
 X0X1X0D123Y2
 X0X1X0D13Y0
 X0X1X0D13Y1
 X0X1X0D13Y2
 X0X1X0D132Y0
 X0X1X0D132Y1
 X0X1X0D132Y2
 X0X1X0Y0X1
 X0X1X0Y0X2
 X0X1X0Y0Y1
 X0X1X0Y0Y2
 X0X1X0Y1X1
 X0X1X0Y1X2
 X0X1X0Y1Y0
 X0X1X0Y1Y2
 X0X1X0Y2X1
 X0X1X0Y2X2
 X0X1X2στ
 X0X1X2σDe
 X0X1X2σD12
 X0X1X2σD123
 X0X1X2σD13
 X0X1X2σD132
 X0X1X2σY0
 X0X1X2σY1
 X0X1X2σY2
 X0X1X2τσ
 X0X1X2τ^2
 X0X1X2τDe
 X0X1X2τD12
 X0X1X2τD123
 X0X1X2τD13
 X0X1X2τD132
 X0X1X2τY0
 X0X1X2τY1
 X0X1X2τY2
 X0X1X2DeY0
 X0X1X2DeY1
 X0X1X2DeY2
 X0X1X2D12Y0
 X0X1X2D12Y1
 X0X1X2D12Y2
 X0X1X2D123Y0
 X0X1X2D123Y1
 X0X1X2D123Y2
 X0X1X2D13Y0
 X0X1X2D13Y1
 X0X1X2D13Y2
 X0X1X2D132Y0
 X0X1X2D132Y1
 X0X1X2D132Y2
 X0X1X2Y0X1
 X0X1X2Y0X2
 X0X1X2Y0Y1
 X0X1X2Y0Y2
 X0X1X2Y1X1
 X0X1X2Y1X2
 X0X1X2Y1Y0
 X0X1X2Y1Y2
 X0X1X2Y2X1
 X0X1X2Y2X2
 X0X1στDe
 X0X1στD12
 X0X1στY0
 X0X1στY1
 X0X1στY2
 X0X1σDeY0
 X0X1σDeY1
 X0X1σDeY2
 X0X1σD12Y0
 X0X1σD12Y1
 X0X1σD12Y2
 X0X1σD123Y0
 X0X1σD123Y1
 X0X1σD123Y2
 X0X1σD13Y0
 X0X1σD13Y1
 X0X1σD13Y2
 X0X1σD132Y0
 X0X1σD132Y1
 X0X1σD132Y2
 X0X1σY0X1
 X0X1σY0Y1
 X0X1σY0Y2
 X0X1σY1X1
 X0X1σY1Y0
 X0X1σY1Y2
 X0X1σY2X1
 X0X1τσDe
 X0X1τσD12
 X0X1τσY0
 X0X1τσY1
 X0X1τσY2
 X0X1τ^2De
 X0X1τ^2D12
 X0X1τ^2Y0
 X0X1τ^2Y1
 X0X1τ^2Y2
 X0X1τDeY0
 X0X1τDeY1
 X0X1τDeY2
 X0X1τD12Y0
 X0X1τD12Y1
 X0X1τD12Y2
 X0X1τD123Y0
 X0X1τD123Y1
 X0X1τD123Y2
 X0X1τD13Y0
 X0X1τD13Y1
 X0X1τD13Y2
 X0X1τD132Y0
 X0X1τD132Y1
 X0X1τD132Y2
 X0X1τY0Y1
 X0X1τY0Y2
 X0X1τY1Y0
 X0X1τY1Y2
 X0X1DeY0Y1
 X0X1DeY0Y2
 X0X1DeY1Y0
 X0X1DeY1Y2
 X0X1D12Y0Y1
 X0X1D12Y0Y2
 X0X1D12Y1Y0
 X0X1D12Y1Y2
 X0X1D123Y0Y1
 X0X1D123Y0Y2
 X0X1D123Y1Y0
 X0X1D123Y1Y2
 X0X1D13Y0Y1
 X0X1D13Y0Y2
 X0X1D13Y1Y0
 X0X1D13Y1Y2
 X0X1D132Y0Y1
 X0X1D132Y0Y2
 X0X1D132Y1Y0
 X0X1D132Y1Y2
 X0X1Y0X1Y0
 X0X1Y0X1Y1
 X0X1Y0X1Y2
 X0X1Y0X2Y0
 X0X1Y0X2Y1
 X0X1Y0X2Y2
 X0X1Y0Y1X1
 X0X1Y0Y1X2
 X0X1Y0Y1Y0
 X0X1Y0Y1Y2
 X0X1Y0Y2X1
 X0X1Y0Y2X2
 X0X1Y1X1Y0
 X0X1Y1X1Y1
 X0X1Y1X2Y0
 X0X1Y1X2Y2
 X0X1Y1Y0X1
 X0X1Y1Y0X2
 X0X1Y1Y0Y2
 X0X1Y2X1Y0
 X0X1Y2X2Y2
 X0X2στDe
 X0X2στD12
 X0X2στY0
 X0X2στY1
 X0X2στY2
 X0X2σDeY0
 X0X2σDeY1
 X0X2σDeY2
 X0X2σD12Y0
 X0X2σD12Y1
 X0X2σD12Y2
 X0X2σD123Y0
 X0X2σD123Y1
 X0X2σD123Y2
 X0X2σD13Y0
 X0X2σD13Y1
 X0X2σD13Y2
 X0X2σD132Y0
 X0X2σD132Y1
 X0X2σD132Y2
 X0X2σY0X1
 X0X2σY0Y1
 X0X2σY0Y2
 X0X2σY1X1
 X0X2σY1Y0
 X0X2σY1Y2
 X0X2σY2X1
 X0X2τσDe
 X0X2τσD12
 X0X2τσY0
 X0X2τσY1
 X0X2τσY2
 X0X2τ^2De
 X0X2τ^2D12
 X0X2τ^2Y0
 X0X2τ^2Y1
 X0X2τ^2Y2
 X0X2τDeY0
 X0X2τDeY1
 X0X2τDeY2
 X0X2τD12Y0
 X0X2τD12Y1
 X0X2τD12Y2
 X0X2τD123Y0
 X0X2τD123Y1
 X0X2τD123Y2
 X0X2τD13Y0
 X0X2τD13Y1
 X0X2τD13Y2
 X0X2τD132Y0
 X0X2τD132Y1
 X0X2τD132Y2
 X0X2τY0Y1
 X0X2τY0Y2
 X0X2τY1Y0
 X0X2τY1Y2
 X0X2DeY0Y1
 X0X2DeY0Y2
 X0X2DeY1Y0
 X0X2DeY1Y2
 X0X2D12Y0Y1
 X0X2D12Y0Y2
 X0X2D12Y1Y0
 X0X2D12Y1Y2
 X0X2D123Y0Y1
 X0X2D123Y0Y2
 X0X2D123Y1Y0
 X0X2D123Y1Y2
 X0X2D13Y0Y1
 X0X2D13Y0Y2
 X0X2D13Y1Y0
 X0X2D13Y1Y2
 X0X2D132Y0Y1
 X0X2D132Y0Y2
 X0X2D132Y1Y0
 X0X2D132Y1Y2
 X0X2Y0X1Y0
 X0X2Y0X1Y1
 X0X2Y0X1Y2
 X0X2Y0X2Y0
 X0X2Y0X2Y1
 X0X2Y0X2Y2
 X0X2Y0Y1X1
 X0X2Y0Y1X2
 X0X2Y0Y1Y0
 X0X2Y0Y1Y2
 X0X2Y0Y2X1
 X0X2Y0Y2X2
 X0X2Y1X1Y0
 X0X2Y1X1Y1
 X0X2Y1X2Y0
 X0X2Y1X2Y2
 X0X2Y1Y0X1
 X0X2Y1Y0X2
 X0X2Y1Y0Y2
 X0X2Y2X1Y0
 X0X2Y2X2Y2
 X0στDeY0
 X0στDeY1
 X0στDeY2
 X0στD12Y0
 X0στD12Y1
 X0στD12Y2
 X0στY0Y1
 X0στY0Y2
 X0στY1Y0
 X0στY1Y2
 X0σDeY0Y1
 X0σDeY0Y2
 X0σDeY1Y0
 X0σDeY1Y2
 X0σD12Y0Y1
 X0σD12Y0Y2
 X0σD12Y1Y0
 X0σD12Y1Y2
 X0σD123Y0Y1
 X0σD123Y0Y2
 X0σD123Y1Y0
 X0σD123Y1Y2
 X0σD13Y0Y1
 X0σD13Y0Y2
 X0σD13Y1Y0
 X0σD13Y1Y2
 X0σD132Y0Y1
 X0σD132Y0Y2
 X0σD132Y1Y0
 X0σD132Y1Y2
 X0σY0X1Y0
 X0σY0X1Y1
 X0σY0X1Y2
 X0σY0Y1X1
 X0σY0Y1Y0
 X0σY0Y1Y2
 X0σY0Y2X1
 X0σY1X1Y0
 X0σY1X1Y1
 X0σY1Y0X1
 X0σY1Y0Y2
 X0σY2X1Y0
 X0τσDeY0
 X0τσDeY1
 X0τσDeY2
 X0τσD12Y0
 X0τσD12Y1
 X0τσD12Y2
 X0τσY0Y1
 X0τσY0Y2
 X0τσY1Y0
 X0τσY1Y2
 X0τ^2DeY0
 X0τ^2DeY1
 X0τ^2DeY2
 X0τ^2D12Y0
 X0τ^2D12Y1
 X0τ^2D12Y2
 X0τ^2Y0Y1
 X0τ^2Y0Y2
 X0τ^2Y1Y0
 X0τ^2Y1Y2
 X0τDeY0Y1
 X0τDeY0Y2
 X0τDeY1Y0
 X0τDeY1Y2
 X0τD12Y0Y1
 X0τD12Y0Y2
 X0τD12Y1Y0
 X0τD12Y1Y2
 X0τD123Y0Y1
 X0τD123Y0Y2
 X0τD123Y1Y0
 X0τD123Y1Y2
 X0τD13Y0Y1
 X0τD13Y0Y2
 X0τD13Y1Y0
 X0τD13Y1Y2
 X0τD132Y0Y1
 X0τD132Y0Y2
 X0τD132Y1Y0
 X0τD132Y1Y2
 X0τY0Y1Y0
 X0τY0Y1Y2
 X0τY1Y0Y2
 X0DeY0Y1Y0
 X0DeY0Y1Y2
 X0DeY1Y0Y2
 X0D12Y0Y1Y0
 X0D12Y0Y1Y2
 X0D12Y1Y0Y2
 X0D123Y0Y1Y0
 X0D123Y0Y1Y2
 X0D123Y1Y0Y2
 X0D13Y0Y1Y0
 X0D13Y0Y1Y2
 X0D13Y1Y0Y2
 X0D132Y0Y1Y0
 X0D132Y0Y1Y2
 X0D132Y1Y0Y2
 X0Y0X1Y0Y1
 X0Y0X1Y0Y2
 X0Y0X1Y1Y0
 X0Y0X1Y1Y2
 X0Y0X2Y0Y1
 X0Y0X2Y0Y2
 X0Y0X2Y1Y0
 X0Y0X2Y1Y2
 X0Y0Y1X1Y0
 X0Y0Y1X1Y1
 X0Y0Y1X2Y0
 X0Y0Y1X2Y2
 X0Y0Y1Y0X1
 X0Y0Y1Y0X2
 X0Y0Y1Y0Y2
 X0Y0Y2X1Y0
 X0Y0Y2X2Y2
 X0Y1X1Y0Y1
 X0Y1X1Y0Y2
 X0Y1X2Y0Y1
 X0Y1X2Y0Y2
 X0Y1Y0X1Y0
 X0Y1Y0X1Y2
 X0Y1Y0X2Y1
 X0Y1Y0X2Y2
 X1X0X2στ
 X1X0X2σDe
 X1X0X2σD12
 X1X0X2σD123
 X1X0X2σD13
 X1X0X2σD132
 X1X0X2σY0
 X1X0X2σY1
 X1X0X2σY2
 X1X0X2τσ
 X1X0X2τ^2
 X1X0X2τDe
 X1X0X2τD12
 X1X0X2τD123
 X1X0X2τD13
 X1X0X2τD132
 X1X0X2τY0
 X1X0X2τY1
 X1X0X2τY2
 X1X0X2DeY0
 X1X0X2DeY1
 X1X0X2DeY2
 X1X0X2D12Y0
 X1X0X2D12Y1
 X1X0X2D12Y2
 X1X0X2D123Y0
 X1X0X2D123Y1
 X1X0X2D123Y2
 X1X0X2D13Y0
 X1X0X2D13Y1
 X1X0X2D13Y2
 X1X0X2D132Y0
 X1X0X2D132Y1
 X1X0X2D132Y2
 X1X0X2Y0X1
 X1X0X2Y0X2
 X1X0X2Y0Y1
 X1X0X2Y0Y2
 X1X0X2Y1X1
 X1X0X2Y1X2
 X1X0X2Y1Y0
 X1X0X2Y1Y2
 X1X0X2Y2X1
 X1X0X2Y2X2
 X1X0στDe
 X1X0στD12
 X1X0στY0
 X1X0στY1
 X1X0στY2
 X1X0σDeY0
 X1X0σDeY1
 X1X0σDeY2
 X1X0σD12Y0
 X1X0σD12Y1
 X1X0σD12Y2
 X1X0σD123Y0
 X1X0σD123Y1
 X1X0σD123Y2
 X1X0σD13Y0
 X1X0σD13Y1
 X1X0σD13Y2
 X1X0σD132Y0
 X1X0σD132Y1
 X1X0σD132Y2
 X1X0σY0X1
 X1X0σY0Y1
 X1X0σY0Y2
 X1X0σY1X1
 X1X0σY1Y0
 X1X0σY1Y2
 X1X0σY2X1
 X1X0τσDe
 X1X0τσD12
 X1X0τσY0
 X1X0τσY1
 X1X0τσY2
 X1X0τ^2De
 X1X0τ^2D12
 X1X0τ^2Y0
 X1X0τ^2Y1
 X1X0τ^2Y2
 X1X0τDeY0
 X1X0τDeY1
 X1X0τDeY2
 X1X0τD12Y0
 X1X0τD12Y1
 X1X0τD12Y2
 X1X0τD123Y0
 X1X0τD123Y1
 X1X0τD123Y2
 X1X0τD13Y0
 X1X0τD13Y1
 X1X0τD13Y2
 X1X0τD132Y0
 X1X0τD132Y1
 X1X0τD132Y2
 X1X0τY0Y1
 X1X0τY0Y2
 X1X0τY1Y0
 X1X0τY1Y2
 X1X0DeY0Y1
 X1X0DeY0Y2
 X1X0DeY1Y0
 X1X0DeY1Y2
 X1X0D12Y0Y1
 X1X0D12Y0Y2
 X1X0D12Y1Y0
 X1X0D12Y1Y2
 X1X0D123Y0Y1
 X1X0D123Y0Y2
 X1X0D123Y1Y0
 X1X0D123Y1Y2
 X1X0D13Y0Y1
 X1X0D13Y0Y2
 X1X0D13Y1Y0
 X1X0D13Y1Y2
 X1X0D132Y0Y1
 X1X0D132Y0Y2
 X1X0D132Y1Y0
 X1X0D132Y1Y2
 X1X0Y0X1Y0
 X1X0Y0X1Y1
 X1X0Y0X1Y2
 X1X0Y0X2Y0
 X1X0Y0X2Y1
 X1X0Y0X2Y2
 X1X0Y0Y1X1
 X1X0Y0Y1X2
 X1X0Y0Y1Y0
 X1X0Y0Y1Y2
 X1X0Y0Y2X1
 X1X0Y0Y2X2
 X1X0Y1X1Y0
 X1X0Y1X1Y1
 X1X0Y1X2Y0
 X1X0Y1X2Y2
 X1X0Y1Y0X1
 X1X0Y1Y0X2
 X1X0Y1Y0Y2
 X1X0Y2X1Y0
 X1X0Y2X2Y2
 X1X2στDe
 X1X2στD12
 X1X2στY0
 X1X2στY1
 X1X2στY2
 X1X2σDeY0
 X1X2σDeY1
 X1X2σDeY2
 X1X2σD12Y0
 X1X2σD12Y1
 X1X2σD12Y2
 X1X2σD123Y0
 X1X2σD123Y1
 X1X2σD123Y2
 X1X2σD13Y0
 X1X2σD13Y1
 X1X2σD13Y2
 X1X2σD132Y0
 X1X2σD132Y1
 X1X2σD132Y2
 X1X2σY0X1
 X1X2σY0Y1
 X1X2σY0Y2
 X1X2σY1X1
 X1X2σY1Y0
 X1X2σY1Y2
 X1X2σY2X1
 X1X2τσDe
 X1X2τσD12
 X1X2τσY0
 X1X2τσY1
 X1X2τσY2
 X1X2τ^2De
 X1X2τ^2D12
 X1X2τ^2Y0
 X1X2τ^2Y1
 X1X2τ^2Y2
 X1X2τDeY0
 X1X2τDeY1
 X1X2τDeY2
 X1X2τD12Y0
 X1X2τD12Y1
 X1X2τD12Y2
 X1X2τD123Y0
 X1X2τD123Y1
 X1X2τD123Y2
 X1X2τD13Y0
 X1X2τD13Y1
 X1X2τD13Y2
 X1X2τD132Y0
 X1X2τD132Y1
 X1X2τD132Y2
 X1X2τY0Y1
 X1X2τY0Y2
 X1X2τY1Y0
 X1X2τY1Y2
 X1X2DeY0Y1
 X1X2DeY0Y2
 X1X2DeY1Y0
 X1X2DeY1Y2
 X1X2D12Y0Y1
 X1X2D12Y0Y2
 X1X2D12Y1Y0
 X1X2D12Y1Y2
 X1X2D123Y0Y1
 X1X2D123Y0Y2
 X1X2D123Y1Y0
 X1X2D123Y1Y2
 X1X2D13Y0Y1
 X1X2D13Y0Y2
 X1X2D13Y1Y0
 X1X2D13Y1Y2
 X1X2D132Y0Y1
 X1X2D132Y0Y2
 X1X2D132Y1Y0
 X1X2D132Y1Y2
 X1X2Y0X1Y0
 X1X2Y0X1Y1
 X1X2Y0X1Y2
 X1X2Y0X2Y0
 X1X2Y0X2Y1
 X1X2Y0X2Y2
 X1X2Y0Y1X1
 X1X2Y0Y1X2
 X1X2Y0Y1Y0
 X1X2Y0Y1Y2
 X1X2Y0Y2X1
 X1X2Y0Y2X2
 X1X2Y1X1Y0
 X1X2Y1X1Y1
 X1X2Y1X2Y0
 X1X2Y1X2Y2
 X1X2Y1Y0X1
 X1X2Y1Y0X2
 X1X2Y1Y0Y2
 X1X2Y2X1Y0
 X1X2Y2X2Y2
 X1στDeY0
 X1στDeY1
 X1στDeY2
 X1στD12Y0
 X1στD12Y1
 X1στD12Y2
 X1στY0Y1
 X1στY0Y2
 X1στY1Y0
 X1στY1Y2
 X1σDeY0Y1
 X1σDeY0Y2
 X1σDeY1Y0
 X1σDeY1Y2
 X1σD12Y0Y1
 X1σD12Y0Y2
 X1σD12Y1Y0
 X1σD12Y1Y2
 X1σD123Y0Y1
 X1σD123Y0Y2
 X1σD123Y1Y0
 X1σD123Y1Y2
 X1σD13Y0Y1
 X1σD13Y0Y2
 X1σD13Y1Y0
 X1σD13Y1Y2
 X1σD132Y0Y1
 X1σD132Y0Y2
 X1σD132Y1Y0
 X1σD132Y1Y2
 X1σY0X1Y0
 X1σY0X1Y1
 X1σY0X1Y2
 X1σY0Y1X1
 X1σY0Y1Y0
 X1σY0Y1Y2
 X1σY0Y2X1
 X1σY1X1Y0
 X1σY1X1Y1
 X1σY1Y0X1
 X1σY1Y0Y2
 X1σY2X1Y0
 X1τσDeY0
 X1τσDeY1
 X1τσDeY2
 X1τσD12Y0
 X1τσD12Y1
 X1τσD12Y2
 X1τσY0Y1
 X1τσY0Y2
 X1τσY1Y0
 X1τσY1Y2
 X1τ^2DeY0
 X1τ^2DeY1
 X1τ^2DeY2
 X1τ^2D12Y0
 X1τ^2D12Y1
 X1τ^2D12Y2
 X1τ^2Y0Y1
 X1τ^2Y0Y2
 X1τ^2Y1Y0
 X1τ^2Y1Y2
 X1τDeY0Y1
 X1τDeY0Y2
 X1τDeY1Y0
 X1τDeY1Y2
 X1τD12Y0Y1
 X1τD12Y0Y2
 X1τD12Y1Y0
 X1τD12Y1Y2
 X1τD123Y0Y1
 X1τD123Y0Y2
 X1τD123Y1Y0
 X1τD123Y1Y2
 X1τD13Y0Y1
 X1τD13Y0Y2
 X1τD13Y1Y0
 X1τD13Y1Y2
 X1τD132Y0Y1
 X1τD132Y0Y2
 X1τD132Y1Y0
 X1τD132Y1Y2
 X1τY0Y1Y0
 X1τY0Y1Y2
 X1τY1Y0Y2
 X1DeY0Y1Y0
 X1DeY0Y1Y2
 X1DeY1Y0Y2
 X1D12Y0Y1Y0
 X1D12Y0Y1Y2
 X1D12Y1Y0Y2
 X1D123Y0Y1Y0
 X1D123Y0Y1Y2
 X1D123Y1Y0Y2
 X1D13Y0Y1Y0
 X1D13Y0Y1Y2
 X1D13Y1Y0Y2
 X1D132Y0Y1Y0
 X1D132Y0Y1Y2
 X1D132Y1Y0Y2
 X1Y0X1Y0Y1
 X1Y0X1Y0Y2
 X1Y0X1Y1Y0
 X1Y0X1Y1Y2
 X1Y0X2Y0Y1
 X1Y0X2Y0Y2
 X1Y0X2Y1Y0
 X1Y0X2Y1Y2
 X1Y0Y1X1Y0
 X1Y0Y1X1Y1
 X1Y0Y1X2Y0
 X1Y0Y1X2Y2
 X1Y0Y1Y0X1
 X1Y0Y1Y0X2
 X1Y0Y1Y0Y2
 X1Y0Y2X1Y0
 X1Y0Y2X2Y2
 X1Y1X1Y0Y1
 X1Y1X1Y0Y2
 X1Y1X2Y0Y1
 X1Y1X2Y0Y2
 X1Y1Y0X1Y0
 X1Y1Y0X1Y2
 X1Y1Y0X2Y1
 X1Y1Y0X2Y2
 X2στDeY0
 X2στDeY1
 X2στDeY2
 X2στD12Y0
 X2στD12Y1
 X2στD12Y2
 X2στY0Y1
 X2στY0Y2
 X2στY1Y0
 X2στY1Y2
 X2σDeY0Y1
 X2σDeY0Y2
 X2σDeY1Y0
 X2σDeY1Y2
 X2σD12Y0Y1
 X2σD12Y0Y2
 X2σD12Y1Y0
 X2σD12Y1Y2
 X2σD123Y0Y1
 X2σD123Y0Y2
 X2σD123Y1Y0
 X2σD123Y1Y2
 X2σD13Y0Y1
 X2σD13Y0Y2
 X2σD13Y1Y0
 X2σD13Y1Y2
 X2σD132Y0Y1
 X2σD132Y0Y2
 X2σD132Y1Y0
 X2σD132Y1Y2
 X2σY0X1Y0
 X2σY0X1Y1
 X2σY0X1Y2
 X2σY0Y1X1
 X2σY0Y1Y0
 X2σY0Y1Y2
 X2σY0Y2X1
 X2σY1X1Y0
 X2σY1X1Y1
 X2σY1Y0X1
 X2σY1Y0Y2
 X2σY2X1Y0
 X2τσDeY0
 X2τσDeY1
 X2τσDeY2
 X2τσD12Y0
 X2τσD12Y1
 X2τσD12Y2
 X2τσY0Y1
 X2τσY0Y2
 X2τσY1Y0
 X2τσY1Y2
 X2τ^2DeY0
 X2τ^2DeY1
 X2τ^2DeY2
 X2τ^2D12Y0
 X2τ^2D12Y1
 X2τ^2D12Y2
 X2τ^2Y0Y1
 X2τ^2Y0Y2
 X2τ^2Y1Y0
 X2τ^2Y1Y2
 X2τDeY0Y1
 X2τDeY0Y2
 X2τDeY1Y0
 X2τDeY1Y2
 X2τD12Y0Y1
 X2τD12Y0Y2
 X2τD12Y1Y0
 X2τD12Y1Y2
 X2τD123Y0Y1
 X2τD123Y0Y2
 X2τD123Y1Y0
 X2τD123Y1Y2
 X2τD13Y0Y1
 X2τD13Y0Y2
 X2τD13Y1Y0
 X2τD13Y1Y2
 X2τD132Y0Y1
 X2τD132Y0Y2
 X2τD132Y1Y0
 X2τD132Y1Y2
 X2τY0Y1Y0
 X2τY0Y1Y2
 X2τY1Y0Y2
 X2DeY0Y1Y0
 X2DeY0Y1Y2
 X2DeY1Y0Y2
 X2D12Y0Y1Y0
 X2D12Y0Y1Y2
 X2D12Y1Y0Y2
 X2D123Y0Y1Y0
 X2D123Y0Y1Y2
 X2D123Y1Y0Y2
 X2D13Y0Y1Y0
 X2D13Y0Y1Y2
 X2D13Y1Y0Y2
 X2D132Y0Y1Y0
 X2D132Y0Y1Y2
 X2D132Y1Y0Y2
 X2Y0X1Y0Y1
 X2Y0X1Y0Y2
 X2Y0X1Y1Y0
 X2Y0X1Y1Y2
 X2Y0X2Y0Y1
 X2Y0X2Y0Y2
 X2Y0X2Y1Y0
 X2Y0X2Y1Y2
 X2Y0Y1X1Y0
 X2Y0Y1X1Y1
 X2Y0Y1X2Y0
 X2Y0Y1X2Y2
 X2Y0Y1Y0X1
 X2Y0Y1Y0X2
 X2Y0Y1Y0Y2
 X2Y0Y2X1Y0
 X2Y0Y2X2Y2
 X2Y1X1Y0Y1
 X2Y1X1Y0Y2
 X2Y1X2Y0Y1
 X2Y1X2Y0Y2
 X2Y1Y0X1Y0
 X2Y1Y0X1Y2
 X2Y1Y0X2Y1
 X2Y1Y0X2Y2
 στDeY0Y1
 στDeY0Y2
 στDeY1Y0
 στDeY1Y2
 στD12Y0Y1
 στD12Y0Y2
 στD12Y1Y0
 στD12Y1Y2
 στY0Y1Y0
 στY0Y1Y2
 στY1Y0Y2
 σDeY0Y1Y0
 σDeY0Y1Y2
 σDeY1Y0Y2
 σD12Y0Y1Y0
 σD12Y0Y1Y2
 σD12Y1Y0Y2
 σD123Y0Y1Y0

## Data

In [166]:
Y12bis:=[];; 
for bi in Base_FK3 do
    Y0   := GP2NP(Y12);
    prod := StrongNormalFormNP(MulNP(Y0, bi), J);
    Add(Y12bis, rec(bi := bi, prod := prod, yj := Y0));
od;

In [168]:
Y13bis:=[];; 
for bi in Base_FK3 do
    Y1   := GP2NP(Y13);
    prod := StrongNormalFormNP(MulNP(Y1, bi), J);
    Add(Y13bis, rec(bi := bi, prod := prod, yj := Y1));
od;

In [170]:
Y23bis:=[];; 
for bi in Base_FK3 do
    Y2   := GP2NP(Y23);
    prod := StrongNormalFormNP(MulNP(Y2, bi), J);
    Add(Y23bis, rec(bi := bi, prod := prod, yj := Y2));
od;

## Calculo de $y_{top}x_{top}$

Las relaciones definitorias del álgebra de Nichols $\mathfrak{B}(V)$ son
$$
x_{(12)}^{2}, \quad x_{(13)}^{2}, \quad x_{(23)}^{2},
$$
$$
x_{(12)}x_{(13)} + x_{(23)}x_{(12)} + x_{(13)}x_{(23)} 
\quad \text{y} \quad 
x_{(13)}x_{(12)} + x_{(12)}x_{(23)} + x_{(23)}x_{(13)}.
$$

Denotamos por $\mathbb{B}$ a la base de $\mathfrak{B}(V)$, la cual se obtiene eligiendo un elemento por cada fila de la siguiente lista y multiplicándolos de arriba hacia abajo, véase *e.g.* [7]:

$$
\begin{array}{l}
1, \, x_{(12)}, \\[4pt]
1, \, x_{(13)}, \, x_{(13)}x_{(12)}, \\[4pt]
1, \, x_{(23)}.
\end{array}
$$

Sea $\mathbb{B}^n = \mathbb{B} \cap \mathfrak{B}^n(V)$, $n \geq 0$. 
El elemento de grado máximo en $\mathbb{B}$ es
$$
x_{\text{top}} = x_{(12)}x_{(13)}x_{(12)}x_{(23)} \in \mathbb{B}^4.
$$

# Kazhdan–Lusztig

In [171]:
NicholsGradingData := [
    rec( graded_i := 0, dimBi := 1 ),
    rec( graded_i := 1, dimBi := 3 ),
    rec( graded_i := 2, dimBi := 4 ),
    rec( graded_i := 3, dimBi := 3 ),
    rec( graded_i := 4, dimBi := 1 )
];

[ rec( dimBi := 1, graded_i := 0 ), rec( dimBi := 3, graded_i := 1 ),   rec( dimBi := 4, graded_i := 2 ), rec( dimBi := 3, graded_i := 3 ),   rec( dimBi := 1, graded_i := 4 ) ]

In [180]:
SimpleNames    := [ ];;
SimpleNames[1] := "M(e,+)";;
SimpleNames[2] := "M(e,-)";;
SimpleNames[3] := "M(e,\\rho)";;
SimpleNames[4] := "M(\\sigma,+)";;
SimpleNames[5] := "M(\\sigma,-)";;
SimpleNames[6] := "M(\\tau,0)";;
SimpleNames[7] := "M(\\tau,1)";;
SimpleNames[8] := "M(\\tau,2)";;

In [181]:
SimplesMn  := [];

[  ]

In [183]:
SimplesModAttachedToOne := GetSimplesModAttachedToElement(G, One(G), allPairsInG);
for s in SimplesModAttachedToOne do
    s:=AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

[ rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 1 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0 ] ] ) ], G := "S3",       Gamma_g := "S3", base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ], genimages := [ [ [ 1 ] ], [ [ 1 ] ] ],       group := S3, isSimple := true,       simple := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ) ),   rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 1 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0 ] ] ) ], G := "S3",       Gamma_g := "S3", base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ], genimages := [ [ [ -1 ] ], [ [ 1 ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ] ) ),   rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 1, 0 ], [ 0, 1 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ) ],       G := "S3", Gamma_g := "S3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 0, 1 ], (( 0*Z(3) , 0 )) ⊗ [ 1, 0 ] ]        , generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] ->             [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] ->             [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ] ) ) ]

In [184]:
UpdateSimpleBase := function(simple)
    local m, new_base, elems;

    m     := Length(simple.base);
    elems := Elements(GF(3));

    if m = 3 then
        new_base := [
            TensorElement(ElementSDP(elems[1], 0), [1]),
            TensorElement(ElementSDP(elems[3], 0), [1]),
            TensorElement(ElementSDP(elems[2], 0), [1])
        ];
        simple.base := new_base;
        return simple;
    else
        return simple;
    fi;
end;

function( simple ) ... end

In [186]:
SimplesModAttachedToSigma := GetSimplesModAttachedToElement(G, G.1, allPairsInG);
for s in SimplesModAttachedToSigma do
    # s             := UpdateSimpleBase(s);
    gens          := GeneratorsOfGroup(G);;
    mgens         := List(gens, x-> s.simple(x)^-1);
    s.simple      := GroupHomomorphismByImages( G, Group( mgens ), gens, mgens );
    s.gensimages  := mgens;
    s             := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

[ rec(       DeltaStructureMatrices :=         [           rec( element := ( 0*Z(3) , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( 0*Z(3) , 1 ),               matrix := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ] ),           rec( element := ( Z(3) , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3) , 1 ),               matrix := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ] ) ],       G := "S3", Gamma_g := "C2",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( Z(3)^0 , 0 )) ⊗ [ 1 ],           (( Z(3) , 0 )) ⊗ [ 1 ] ], generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ] ],       gensimages := [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ], group := S3,       isSimple := true,       simple := [ f1, f2 ] -> [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ],       weight := rec( g := f1, rho := [ f1 ] -> [ [ [ 1 ] ] ] ),       weightSDP := rec( g := ( 0*Z(3) , 1 ), rho := [ f1 ] -> [ [ [ 1 ] ] ] )      ),   rec(       DeltaStructureMatrices :=         [           rec( element := ( 0*Z(3) , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( 0*Z(3) , 1 ),               matrix := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ] ),           rec( element := ( Z(3) , 0 ),               matrix := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ),           rec( element := ( Z(3) , 1 ),               matrix := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ] ) ],       G := "S3", Gamma_g := "C2",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( Z(3)^0 , 0 )) ⊗ [ 1 ],           (( Z(3) , 0 )) ⊗ [ 1 ] ], generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ] ],       gensimages := [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ], group := S3,       isSimple := true,       simple := [ f1, f2 ] -> [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ],       weight := rec( g := f1, rho := [ f1 ] -> [ [ [ -1 ] ] ] ),       weightSDP := rec( g := ( 0*Z(3) , 1 ), rho := [ f1 ] -> [ [ [ -1 ] ] ]          ) ) ]

In [188]:
SimplesModAttachedToTau := GetSimplesModAttachedToElement(G, G.2, allPairsInG);
for s in SimplesModAttachedToTau do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

[ rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 1, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 1 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ) ],       G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ 1, 0 ], [ 0, 1 ] ] ],       group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ 1, 0 ], [ 0, 1 ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ 1 ] ] ] ),       weightSDP := rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ 1 ] ] ] )      ),   rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 1, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 1 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ) ],       G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3), 0 ], [ 0, E(3)^2 ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3), 0 ], [ 0, E(3)^2 ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ E(3) ] ] ] ),       weightSDP :=         rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ E(3) ] ] ] ) ),   rec(       DeltaStructureMatrices :=         [ rec( element := ( 0*Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( 0*Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 0 ), matrix := [ [ 1, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3)^0 , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ),           rec( element := ( Z(3) , 0 ), matrix := [ [ 0, 0 ], [ 0, 1 ] ] ),           rec( element := ( Z(3) , 1 ), matrix := [ [ 0, 0 ], [ 0, 0 ] ] ) ],       G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ E(3)^2 ] ] ] ),       weightSDP :=         rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ E(3)^2 ] ] ] ) ) ]

In [189]:
QGNAG_TestRelationsForDGModSimples(SimplesMn, relsGroup, relskG, relsDG);

Simple M4 failed:
   - Drinfeld Double relations

Simple M5 failed:
   - Drinfeld Double relations

false

In [191]:
M4_list_mat_in_DG := QGNAG_ConstructDGActionMatrices(SimplesMn[4], allPairsInG, Base_FK3);;
QGNAG_CheckRelationsShift( relsDG, M4_list_mat_in_DG, nX );

All relations are satisfied.

true

In [193]:
matrix_s4 := QGNAG_RepresentationMatrices(SimplesMn[4]);;
QGNAG_CheckRelationsShift( relsDG, matrix_s4, nX );

Some relations are not satisfied.

false

In [195]:
Length(M4_list_mat_in_DG) = Length(matrix_s4);;
for i in [1..Length(M4_list_mat_in_DG) ] do
   Print(M4_list_mat_in_DG[i] = matrix_s4[i], "\n");
od;

true
false
true
true
true
true
true
true

In [196]:
Display(matrix_s4[2]);

[ [  0,  1,  0 ],
  [  0,  0,  1 ],
  [  1,  0,  0 ] ]

In [197]:
Display(M4_list_mat_in_DG[2]);

[ [  0,  0,  1 ],
  [  1,  0,  0 ],
  [  0,  1,  0 ] ]

In [198]:
BUG_RepresentationMatrices:=function(simple)
    local genimages;
    if not IsBound(simple!.DeltaStructureMatrices) then
        Error("Run AttachDeltaStructureMatrices(simple) first.");
    fi;
    if simple.isSimple then
        genimages := List(GeneratorsOfGroup(Source(simple.simple)), x -> simple.simple(x) );
    else
        genimages := simple.genimages;
    fi;
    return Concatenation( simple.genimages, List( simple.DeltaStructureMatrices, r -> r.matrix ) );
end;

function( simple ) ... end

In [199]:
bug_matrix_s4:=BUG_RepresentationMatrices(SimplesMn[4]);

[ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],   [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ] ]

In [201]:
SimplesMn[4].genimages[1]=bug_matrix_s4[1];
SimplesMn[4].genimages[2]=bug_matrix_s4[2];

true

true

In [203]:
SimplesMn[4].genimages[1]=M4_list_mat_in_DG[1];
SimplesMn[4].genimages[2]=M4_list_mat_in_DG[2];

true

false

In [205]:
SimplesMn[4].genimages[1]=QGNAG_BuildGeneratorMatrices( SimplesMn[4], allPairsInG )[1].matrix;
SimplesMn[4].genimages[2]=QGNAG_BuildGeneratorMatrices( SimplesMn[4], allPairsInG )[2].matrix;

true

false

In [206]:
bug_matrix_s4=matrix_s4;

true

In [207]:
RecNames(GetSimplesModAttachedToElement(G, G.2, allPairsInG)[1]);

[ "group", "base", "genimages", "weight", "G", "isSimple", "weightSDP",   "simple", "generatorsofgroup", "Gamma_g" ]

In [208]:
M4_list_mat_in_DG;

[ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],   [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ] ]

In [210]:
M5_list_mat_in_DG := QGNAG_ConstructDGActionMatrices(SimplesMn[5], allPairsInG, Base_FK3);;
QGNAG_CheckRelationsShift( relsDG, M5_list_mat_in_DG, nX );

All relations are satisfied.

true

In [211]:
matrix_s5 := QGNAG_RepresentationMatrices(SimplesMn[4]);

[ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],   [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ] ]

In [212]:
M5_list_mat_in_DG = matrix_s5;

false

In [213]:
for i in [2..Length(SimplesMn)] do
    Print("--------------------------------------------------------------\n");
    for j in [i..Length(SimplesMn)] do
        MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[i], SimplesMn[j]);
        Print(QGNAG_FusionRuleToIndex( MtensorN, SimplesMn), "\n");
    od;
od;

--------------------------------------------------------------
M2 \otimes M2 \simeq M1
M2 \otimes M3 \simeq M3
M2 \otimes M4 \simeq M5
M2 \otimes M5 \simeq M4
M2 \otimes M6 \simeq M6
M2 \otimes M7 \simeq M7
M2 \otimes M8 \simeq M8
--------------------------------------------------------------
M3 \otimes M3 \simeq M1 \oplus M2 \oplus M3
M3 \otimes M4 \simeq M4 \oplus M5
M3 \otimes M5 \simeq M4 \oplus M5
M3 \otimes M6 \simeq M7 \oplus M8
M3 \otimes M7 \simeq M6 \oplus M8
M3 \otimes M8 \simeq M6 \oplus M7
--------------------------------------------------------------
M4 \otimes M4 \simeq M1 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M4 \otimes M5 \simeq M2 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M4 \otimes M6 \simeq M4 \oplus M5
M4 \otimes M7 \simeq M4 \oplus M5
M4 \otimes M8 \simeq M4 \oplus M5
--------------------------------------------------------------
M5 \otimes M5 \simeq M1 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M5 \otimes M6 \simeq M4 \oplus M5
M5 \otimes M7 \simeq M4 \oplus M5
M5 \otimes M8 \simeq M4 \oplus M5
--------------------------------------------------------------
M6 \otimes M6 \simeq M1 \oplus M2 \oplus M6
M6 \otimes M7 \simeq M3 \oplus M8
M6 \otimes M8 \simeq M3 \oplus M7
--------------------------------------------------------------
M7 \otimes M7 \simeq M1 \oplus M2 \oplus M7
M7 \otimes M8 \simeq M3 \oplus M6
--------------------------------------------------------------
M8 \otimes M8 \simeq M1 \oplus M2 \oplus M8

In [214]:
for i in [2..Length(SimplesMn)] do
    Print("--------------------------------------------------------------\n");
    for j in [i..Length(SimplesMn)] do
        MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[i], SimplesMn[j]);
        Print(QGNAG_FusionRuleToLaTeX( MtensorN, SimplesMn, SimpleNames), "\n");
    od;
od;

--------------------------------------------------------------
M(e,-) \otimes M(e,-) \simeq M(e,+)
M(e,-) \otimes M(e,\rho) \simeq M(e,\rho)
M(e,-) \otimes M(\sigma,+) \simeq M(\sigma,-)
M(e,-) \otimes M(\sigma,-) \simeq M(\sigma,+)
M(e,-) \otimes M(\tau,0) \simeq M(\tau,0)
M(e,-) \otimes M(\tau,1) \simeq M(\tau,1)
M(e,-) \otimes M(\tau,2) \simeq M(\tau,2)
--------------------------------------------------------------
M(e,\rho) \otimes M(e,\rho) \simeq M(e,+) \oplus M(e,-) \oplus M(e,\rho)
M(e,\rho) \otimes M(\sigma,+) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(e,\rho) \otimes M(\sigma,-) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(e,\rho) \otimes M(\tau,0) \simeq M(\tau,1) \oplus M(\tau,2)
M(e,\rho) \otimes M(\tau,1) \simeq M(\tau,0) \oplus M(\tau,2)
M(e,\rho) \otimes M(\tau,2) \simeq M(\tau,0) \oplus M(\tau,1)
--------------------------------------------------------------
M(\sigma,+) \otimes M(\sigma,+) \simeq M(e,+) \oplus M(e,\rho) \oplus M(\tau,0\
) \oplus M(\tau,1) \oplus M(\tau,2)
M(\sigma,+) \otimes M(\sigma,-) \simeq M(e,-) \oplus M(e,\rho) \oplus M(\tau,0\
) \oplus M(\tau,1) \oplus M(\tau,2)
M(\sigma,+) \otimes M(\tau,0) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(\sigma,+) \otimes M(\tau,1) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(\sigma,+) \otimes M(\tau,2) \simeq M(\sigma,+) \oplus M(\sigma,-)
--------------------------------------------------------------
M(\sigma,-) \otimes M(\sigma,-) \simeq M(e,+) \oplus M(e,\rho) \oplus M(\tau,0\
) \oplus M(\tau,1) \oplus M(\tau,2)
M(\sigma,-) \otimes M(\tau,0) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(\sigma,-) \otimes M(\tau,1) \simeq M(\sigma,+) \oplus M(\sigma,-)
M(\sigma,-) \otimes M(\tau,2) \simeq M(\sigma,+) \oplus M(\sigma,-)
--------------------------------------------------------------
M(\tau,0) \otimes M(\tau,0) \simeq M(e,+) \oplus M(e,-) \oplus M(\tau,0)
M(\tau,0) \otimes M(\tau,1) \simeq M(e,\rho) \oplus M(\tau,2)
M(\tau,0) \otimes M(\tau,2) \simeq M(e,\rho) \oplus M(\tau,1)
--------------------------------------------------------------
M(\tau,1) \otimes M(\tau,1) \simeq M(e,+) \oplus M(e,-) \oplus M(\tau,1)
M(\tau,1) \otimes M(\tau,2) \simeq M(e,\rho) \oplus M(\tau,0)
--------------------------------------------------------------
M(\tau,2) \otimes M(\tau,2) \simeq M(e,+) \oplus M(e,-) \oplus M(\tau,2)

### Para las matrices de $\mathfrak{B}(V)$

In [217]:
X12ActionOnBaseFK3 := List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X12),  bi ), J_FK3));;
X13ActionOnBaseFK3 := List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X13),  bi ), J_FK3));;
X23ActionOnBaseFK3 := List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X23),  bi ), J_FK3));;

In [220]:
X0_matrix_on_Nichols := StructureMatrixForXi( X12ActionOnBaseFK3, Base_FK3 );;
X1_matrix_on_Nichols := StructureMatrixForXi( X13ActionOnBaseFK3, Base_FK3 );;
X2_matrix_on_Nichols := StructureMatrixForXi( X23ActionOnBaseFK3, Base_FK3 );;

### Para las matrices de $\Bbbk G$

In [222]:
gensG     := GP2NPList([ F1, F2 ]);;
inv_gensG := GP2NPList([ F1, F2^2 ]);; # validar la lista

In [224]:
F1ConjugationOnNicholsBasis := List(Base_FK3, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[1], bi), inv_gensG[1]), J_D_ge_0));;
F2ConjugationOnNicholsBasis := List(Base_FK3, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[2], bi), inv_gensG[2]), J_D_ge_0));;

In [226]:
Ms_matrix_on_Nichols := StructureMatrixOfG(F1ConjugationOnNicholsBasis, Base_FK3);;
Mt_matrix_on_Nichols := StructureMatrixOfG(F2ConjugationOnNicholsBasis, Base_FK3);;

### Para las matrices de $\Bbbk^G$

In [232]:
De_functions   := QGNAG_DeltaFunctions(gensDeltas[1], Base_FK3);;
D12_functions  := QGNAG_DeltaFunctions(gensDeltas[2], Base_FK3);;
D123_functions := QGNAG_DeltaFunctions(gensDeltas[3], Base_FK3);;
D13_functions  := QGNAG_DeltaFunctions(gensDeltas[4], Base_FK3);;
D132_functions := QGNAG_DeltaFunctions(gensDeltas[5], Base_FK3);;
D23_functions  := QGNAG_DeltaFunctions(gensDeltas[6], Base_FK3);;

## $M_1$

In [234]:
index_s := 1;;
simpleM := GetSimplesModAttachedToElement(G, One(G), allPairsInG)[1];;

# Matrices de $\mathfrak{B}(V)$

In [239]:
X0_matrix := QGNAG_XiMatrixAction(X0_matrix_on_Nichols, simpleM);;
X1_matrix := QGNAG_XiMatrixAction(X1_matrix_on_Nichols, simpleM);;
X2_matrix := QGNAG_XiMatrixAction(X2_matrix_on_Nichols, simpleM);;
all_matrix_rep_nichols := [ X0_matrix, X1_matrix, X2_matrix ];;
QGNAG_CheckRelationsShift( relsFK3, all_matrix_rep_nichols, 0 );

All relations are satisfied.

true

# Matrices de $G$

In [243]:
Ms_matrix := QGNAG_GiMatrixAction(Ms_matrix_on_Nichols, simpleM.simple(G.1));;
Mt_matrix := QGNAG_GiMatrixAction(Mt_matrix_on_Nichols, simpleM.simple(G.2));;
all_matrix_rep_kG := [Ms_matrix, Mt_matrix];;
QGNAG_CheckRelationsShift( relsGroup, all_matrix_rep_kG, (nTotal-nGensOfG-nDelta-nY) );

All relations are satisfied.

true

## Matrices de $\delta_h$ con $h\in G$.

In [251]:
De_matrix   := QGNAG_DeltaMatrix(De_functions, simpleM);;
D12_matrix  := QGNAG_DeltaMatrix(D12_functions, simpleM);;
D123_matrix := QGNAG_DeltaMatrix(D123_functions, simpleM);;
D13_matrix  := QGNAG_DeltaMatrix(D13_functions, simpleM);;
D132_matrix := QGNAG_DeltaMatrix(D132_functions, simpleM);;
D23_matrix  := QGNAG_DeltaMatrix(D23_functions, simpleM);;
all_matrix_rep_kG_dual := [ De_matrix, D12_matrix, D123_matrix, D13_matrix, D132_matrix, D23_matrix ];;
QGNAG_CheckRelationsShift( relskG, all_matrix_rep_kG_dual, (nTotal-nDelta-nY) );

All relations are satisfied.

true

## Matrices de $Y_j$

In [257]:
list_mat_in_DG := QGNAG_ConstructDGActionMatrices(simpleM, allPairsInG, Base_FK3);;
Y0_matrix := MatrixActionYiOnNicholsBasis(Y12bis, simpleM, Base_FK3, list_mat_in_DG);;
Y1_matrix := MatrixActionYiOnNicholsBasis(Y13bis, simpleM, Base_FK3, list_mat_in_DG);;
Y2_matrix := MatrixActionYiOnNicholsBasis(Y23bis, simpleM, Base_FK3, list_mat_in_DG);;
all_matrix_rep_nichols_dual := [ Y0_matrix, Y1_matrix, Y2_matrix ];;
QGNAG_CheckRelationsShift( relsFK3dual, all_matrix_rep_nichols_dual, (nTotal-nY) );

All relations are satisfied.

true

In [259]:
all_matrix_rep_DG := Concatenation( all_matrix_rep_kG, all_matrix_rep_kG_dual );
all_matrix_rep    := Concatenation( all_matrix_rep_nichols, all_matrix_rep_DG, all_matrix_rep_nichols_dual );;

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [264]:
QGNAG_CheckRelationsShift( relsxBos, all_matrix_rep , 0 );
QGNAG_CheckRelationsShift( relsDx, all_matrix_rep , 0 );
QGNAG_CheckRelationsShift( relsyBos, all_matrix_rep , 0 );
QGNAG_CheckRelationsShift( relsDy, all_matrix_rep , 0 );
QGNAG_CheckRelationsShift( relsQG, all_matrix_rep , 0 );

All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.

true

true

true

true

false

## Verma Module

In [272]:
F                   := CF(6);;
D                   := AlgebraWithOne( F, all_matrix_rep );;
Nm                  := Length(simpleM.base)*Length(Base_FK3);;
L                   := LeftAlgebraModule(D, \*, F^Nm ); 
verma_char          := QGNAG_Character( L, simpleM, Base_FK3, NicholsGradingData );;
AllMatricesByDegree := QGNAG_AllMatricesByDegree( verma_char, all_matrix_rep_DG );;
record_data_decomp  := QGNAG_SimpleVermaModuleDecomposition( SimplesMn, allPairsInG, Base_FK3, AllMatricesByDegree );
rec_info := QGNAG_Decomposition(record_data_decomp);

[ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ]

rec( 4 := [ [ 1, 1 ] ] )

In [273]:
QGNAG_PrintDecomposition(rec_info);

degree 4 = M1

In [274]:
QGNAG_HilbertSeriesToLaTeX( StringFormatted("hilbert_{}.tex", index_s), verma_char );

In [275]:
QGNAG_CharacterSummaryToLaTeX( StringFormatted("character_{}.tex", index_s), rec_info, SimpleNames );

In [280]:
data_verma_char          := [];;
data_AllMatricesByDegree := [];;
data_record_data_decomp  := [];;
data_rec_info            := [];;
data_reps_mats           := [];;

## Bucle Principal

In [281]:
for index_s in [1..Length(SimplesMn)] do
    simpleM := SimplesMn[index_s];;

    ## Matrices de $\mathfrak{B}(V)$ 
    X0_matrix := QGNAG_XiMatrixAction(X0_matrix_on_Nichols, simpleM);;
    X1_matrix := QGNAG_XiMatrixAction(X1_matrix_on_Nichols, simpleM);;
    X2_matrix := QGNAG_XiMatrixAction(X2_matrix_on_Nichols, simpleM);;
    all_matrix_rep_nichols := [ X0_matrix, X1_matrix, X2_matrix ];;
    
    ## Matrices de $G$
    # 
    Ms_matrix := QGNAG_GiMatrixAction(Ms_matrix_on_Nichols, simpleM.simple(G.1));;
    Mt_matrix := QGNAG_GiMatrixAction(Mt_matrix_on_Nichols, simpleM.simple(G.2));;
    all_matrix_rep_kG := [Ms_matrix, Mt_matrix];;
    
    ## Matrices de $\delta_h$ con $h\in G$.
    # 
    De_matrix   := QGNAG_DeltaMatrix(De_functions, simpleM);;
    D12_matrix  := QGNAG_DeltaMatrix(D12_functions, simpleM);;
    D123_matrix := QGNAG_DeltaMatrix(D123_functions, simpleM);;
    D13_matrix  := QGNAG_DeltaMatrix(D13_functions, simpleM);;
    D132_matrix := QGNAG_DeltaMatrix(D132_functions, simpleM);;
    D23_matrix  := QGNAG_DeltaMatrix(D23_functions, simpleM);;
    all_matrix_rep_kG_dual := [ De_matrix, D12_matrix, D123_matrix, D13_matrix, D132_matrix, D23_matrix ];;
    
    # Matrices de $Y_j$
    # 
    list_mat_in_DG := QGNAG_ConstructDGActionMatrices(simpleM, allPairsInG, Base_FK3);;
    Y0_matrix := MatrixActionYiOnNicholsBasis(Y12bis, simpleM, Base_FK3, list_mat_in_DG);;
    Y1_matrix := MatrixActionYiOnNicholsBasis(Y13bis, simpleM, Base_FK3, list_mat_in_DG);;
    Y2_matrix := MatrixActionYiOnNicholsBasis(Y23bis, simpleM, Base_FK3, list_mat_in_DG);;
    all_matrix_rep_nichols_dual := [ Y0_matrix, Y1_matrix, Y2_matrix ];;
    
    # 
    all_matrix_rep_DG := Concatenation( all_matrix_rep_kG, all_matrix_rep_kG_dual );
    all_matrix_rep    := Concatenation( all_matrix_rep_nichols, all_matrix_rep_DG, all_matrix_rep_nichols_dual );;
    
    #
    Print("index s = ", index_s,"\n");
    QGNAG_CheckRelationsShift( relsxBos, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsDx, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsyBos, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsDy, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsQG, all_matrix_rep , 0 );
    
    # Verma Module
    # 
    F  := CF(6);;
    D  := AlgebraWithOne( F, all_matrix_rep );;
    Nm := Length(simpleM.base)*Length(Base_FK3);;
    L  := LeftAlgebraModule(D, \*, F^Nm );
    
    verma_char := QGNAG_Character( L, simpleM, Base_FK3, NicholsGradingData );;
    Add(data_verma_char, verma_char);;
    
    AllMatricesByDegree := QGNAG_AllMatricesByDegree( verma_char, all_matrix_rep_DG );;
    Add(data_AllMatricesByDegree, AllMatricesByDegree);;

    record_data_decomp := QGNAG_SimpleVermaModuleDecomposition( SimplesMn, allPairsInG, Base_FK3, AllMatricesByDegree );
    Add(data_record_data_decomp , record_data_decomp );;
    
    rec_info := QGNAG_Decomposition(record_data_decomp);
    # Guardamos un nuevo record en la clave M_s
    data_reps_mats[index_s]:= all_matrix_rep_DG;

    Add(data_rec_info, rec_info);;
od;

index s = 1
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 2
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 3
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 4
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 5
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 6
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 7
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.
index s = 8
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
Some relations are not satisfied.

## Hilbert Polynomials of Simple Verma Modules $L(s,\varrho)$

In [281]:
QGNAG_LoadHilbertPolynomialsToLaTeX( "hilbert_series.tex", data_verma_char, SimpleNames );;

## Characters of Simple Verma Modules $L(s,\varrho)$

In [282]:
QGNAG_LoadCharactersToLaTeX( "characters.tex", data_rec_info, SimpleNames );;

## Braided equivalence

In [284]:
sigma := QGNAG_PermutationFromRecInfo( data_rec_info );

()

In [285]:
QGNAG_TestPermutationFusion( sigma, SimplesMn );

========================================
  Permutation fusion test: PASSED
========================================
The permutation preserves all fusion rules.

true

## Vectors $\nu_{i,j}$

Let $\operatorname{char}(\mathcal{L}_i)=\sum_{d=0}^{\theta}\sum_{j=1}^{N}m_{j,d}\,M_j[d],$
where $m_{j,d}\in\mathbb{N}$ denotes the multiplicity of the simple module
$M_j$ in homogeneous degree $d$.

For each degree $d$, define the block vector
$L_d=(m_{1,d},m_{2,d},\ldots,m_{N,d})\in\mathbb{Q}^{N}.$

The function $\texttt{QGNAG\_CharToVector}$ associates to the graded character of
$\mathcal{L}_i$ the vector
$\nu_{i,0}=(L_0,L_1,\ldots,L_{\theta})\in\mathbb{Q}^{N(\theta+1)},$
obtained by concatenating the multiplicity vectors of each homogeneous degree.

To encode all cyclic shifts of the grading, we define, for every
$k\in\{0,\ldots,\theta\}$,
$\nu_{i,k}=(L_{\theta-k+1},\ldots,L_{\theta},L_0,\ldots,L_{\theta-k}),$
where the indices are understood modulo $\theta+1$.

Equivalently, $\nu_{i,k}=\bigl(L_{(-k)\bmod(\theta+1)},L_{(1-k)\bmod(\theta+1)},\ldots,L_{(\theta-k)\bmod(\theta+1)}\bigr).$

Hence,
\begin{align*}
\nu_{i,0}
    &= (L_0,L_1,\ldots,L_{\theta}),\\
\nu_{i,1}
    &= (L_{\theta},L_0,L_1,\ldots,L_{\theta-1}),\\
\nu_{i,2}
    &= (L_{\theta-1},L_{\theta},L_0,\ldots,L_{\theta-2}),\\
&\ \vdots\\
\nu_{i,\theta}
    &= (L_1,L_2,\ldots,L_{\theta},L_0).
\end{align*}

The function $\texttt{QGNAG\_CharToVector}$ computes the vector
$\nu_{i,0}$, while the function
$\texttt{QGNAG\_CharToShiftedVectors}$ returns the family
$
\{\nu_{i,0},\nu_{i,1},\ldots,\nu_{i,\theta}\},
$
consisting of all cyclic permutations of the block decomposition of the graded
character.

In [286]:
QGNAG_CharToVector := function( record_data_decomp )
    local N,
          degrees,
          ell,
          vector,
          d,
          i,
          degree;
    
    N       := Length(record_data_decomp);
    degrees := List(RecNames(record_data_decomp[1]), x -> Int(x));
    Sort(degrees);
    ell := Maximum(degrees);
    vector := [];
    for d in [0..ell] do
        degree := String(d);
        for i in [1..N] do
            Add(vector, record_data_decomp[i].(degree));
        od;
    od;
    return vector;
end;

function( record_data_decomp ) ... end

In [287]:
QGNAG_CharToGradedVectors := function(record_data_decomp)
    local N,       #
          degrees, #
          degree,  #
          ell,     #
          i,       #
          vectors, #
          vector;  #
    
    N := Length(record_data_decomp);
    degrees := List(
        RecNames(record_data_decomp[1]),
        x -> Int(x)
    );
    Sort(degrees);
    ell := Maximum(degrees);
    vectors := [];
    for degree in [0..ell] do
        vector := [];
        for i in [1..N] do
            Add(vector, record_data_decomp[i].(degree));
        od;
        Add(vectors, vector);
    od;
    return vectors;
end;

function( record_data_decomp ) ... end

In [288]:
data_record_data_decomp[1];

[ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ]

- $L(e,+)$
$$
\operatorname{Char}(e,+)=M(e,+)[4]
$$

In [289]:
nu_10 := QGNAG_CharToVector( data_record_data_decomp[1] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ]

In [290]:
nu_10_gradeed := QGNAG_CharToGradedVectors(data_record_data_decomp[1]);

[ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0 ] ]

In [291]:
QGNAG_CharToVector( data_record_data_decomp[1] )=Concatenation(nu_10_gradeed);

true

In [292]:
QGNAG_CharToShiftedVector := function( record_data_decomp, ell )
    local N,
          degrees,
          theta,
          vector,
          d,
          shifted_degree,
          i,
          degree;
    
    N       := Length(record_data_decomp);
    degrees := List(RecNames(record_data_decomp[1]), x -> Int(x));
    theta   := Maximum(degrees);
    ell     := ell mod (theta + 1);
    vector  := [];
    for d in [0..theta] do
        shifted_degree := (d - ell) mod (theta + 1);
        degree         := String(shifted_degree);
        for i in [1..N] do
            Add(vector, record_data_decomp[i].(degree));
        od;
    od;
    return vector;
end;

function( record_data_decomp, ell ) ... end

In [293]:
QGNAG_CharToShiftedGradeedVector := function( record_data_decomp, j )
    local N,
          degrees,
          degree,
          ell,
          shifted_vector,
          d,
          source_degree,
          block,
          i;

    N              := Length(record_data_decomp);
    degrees        := List(RecNames(record_data_decomp[1]), x -> Int(x));
    ell            := Maximum(degrees);
    shifted_vector := [];
    for d in [0..ell] do
        source_degree := (d - j) mod (ell + 1);
        degree        := String(source_degree);
        block := [];
        for i in [1..N] do
            Add(block, record_data_decomp[i].(degree));
        od;
        Add(shifted_vector, block);
    od;
    return shifted_vector;
end;

function( record_data_decomp, j ) ... end

In [294]:
nu_10=QGNAG_CharToShiftedVector( data_record_data_decomp[1], 0 );

true

In [295]:
nu_10{[1..8]}=QGNAG_CharToShiftedVector( data_record_data_decomp[1], 1 ){[9..16]};

true

In [296]:
QGNAG_CharToShiftedVector( data_record_data_decomp[1], 0 ){[1..8]}=QGNAG_CharToShiftedVector( data_record_data_decomp[1], 1 ){[9..16]};

true

In [297]:
QGNAG_CharToShiftedVector( data_record_data_decomp[1], 1 )=Concatenation(QGNAG_CharToShiftedGradeedVector( data_record_data_decomp[1], 1 ));

true

- $L(e,-)$
$$
\operatorname{Char}(e,-)=M(e,-)[0] + M(\sigma,+)[1] + M(\tau,1)[2] + M(\tau,2)[2] + M(\sigma,+)[3] + M(e,-)[4]
$$

In [298]:
QGNAG_CharToVector( data_record_data_decomp[2] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ]

In [299]:
nu_10_gradeed := QGNAG_CharToGradedVectors(data_record_data_decomp[2]);

[ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0 ] ]

- $L(e,\rho)$
$$
\operatorname{Char}(e,\rho)=M(\tau,0)[2] + M(\sigma,+)[3] + M(e,\rho)[4]
$$

In [300]:
QGNAG_CharToVector( data_record_data_decomp[3] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ]

- $L(\sigma,+)$
$$
\operatorname{Char}(\sigma,+)=M(\sigma,+)[0] + M(e,-)[1] + M(e,\rho)[1] + M(\tau,0)[1] + M(\tau,1)[1] + M(\tau,2)[1] + 2\,M(\sigma,+)[2] + 2\,M(\sigma,-)[2] + M(e,-)[3] + M(e,\rho)[3] + M(\tau,0)[3] + M(\tau,1)[3] + M(\tau,2)[3] + M(\sigma,+)[4]
$$

In [301]:
QGNAG_CharToVector( data_record_data_decomp[4] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ]

- $L(\sigma,-)$
$$
\operatorname{Char}(\sigma,-)=M(\sigma,-)[2] + M(\tau,1)[3] + M(\tau,2)[3] + M(\sigma,-)[4]
$$

In [302]:
QGNAG_CharToVector( data_record_data_decomp[5] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ]

- $L(\tau,0)$
$$
\operatorname{Char}(\tau,0)=M(e,\rho)[2] + M(\sigma,+)[3] + M(\tau,0)[4]
$$

In [303]:
QGNAG_CharToVector( data_record_data_decomp[6] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ]

- $L(\tau,1)$
\begin{align*}
\operatorname{Char}(\tau,1)&=M(\tau,1)[0] + M(\sigma,+)[1] + M(\sigma,-)[1] + M(e,+)[2] +\\
M(e,-)[2] &+ M(e,\rho)[2] + M(\tau,0)[2] + M(\tau,1)[2] + M(\sigma,+)[3] + M(\sigma,-)[3] + M(\tau,1)[4]
\end{align*}

In [304]:
QGNAG_CharToVector( data_record_data_decomp[7] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ]

- $L(\tau,2)$
\begin{align*}
\operatorname{Char}(\tau,2)&=M(\tau,2)[0] + M(\sigma,+)[1] + M(\sigma,-)[1] + M(e,+)[2] +\\
                 M(e,-)[2] &+ M(e,\rho)[2] + M(\tau,0)[2] + M(\tau,2)[2] + M(\sigma,+)[3] + M(\sigma,-)[3] + M(\tau,2)[4]
\end{align*}

In [305]:
QGNAG_CharToVector( data_record_data_decomp[8] );

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ]

In [306]:
QGNAG_CharToBasis := function( data_record_data_decomp )
    local theta, degrees, ell, basis, i, j, nu_ij;
    theta   := Length(data_record_data_decomp[1]);
    degrees := List(RecNames(data_record_data_decomp[1][1]), x -> Int(x));
    Sort(degrees);
    ell := Maximum(degrees);

    basis := [];
    for i in [1..theta] do
        for j in [0..ell] do
            nu_ij := QGNAG_CharToShiftedVector( data_record_data_decomp[i], j);
            Add(basis, nu_ij);
        od;
    od;
    return basis;
end;

function( data_record_data_decomp ) ... end

In [307]:
basis_nu_ij := QGNAG_CharToBasis( data_record_data_decomp );

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],   [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

Let
$
\mathcal{E}=
(e_{1,1}^{0},\ldots,e_{1,N}^{0},
e_{1,1}^{1},\ldots,e_{1,N}^{1},
\ldots,
e_{1,1}^{\ell},\ldots,e_{1,N}^{\ell})
$
be the standard graded basis, where the coordinates are ordered first by
degree and then by simple module. For each $i=1,\ldots,\theta$ and
$j=0,\ldots,\ell$, let $\nu_{i,j}$ be the shifted vector defined above,
and consider the ordered family
$
\mathcal{B}=
(\nu_{1,0},\ldots,\nu_{1,\ell},
 \nu_{2,0},\ldots,\nu_{2,\ell},
 \ldots,
 \nu_{\theta,0},\ldots,\nu_{\theta,\ell}).
$

Assuming that $\mathcal{B}$ is a basis of $V=\mathbb{Q}^{N(\ell+1)}$, construct the matrix
$
P=\begin{pmatrix}|&|&&|\\
\nu_{1,0}&\nu_{1,1}&\cdots&\nu_{\theta,\ell}\\
|&|&&|
\end{pmatrix}_{\mathcal{E}},
$
whose columns are the vectors of $\mathcal{B}$ written in the standard
basis $\mathcal{E}$. Thus, for
$\varepsilon_i=
(d_{i1}^{0},\ldots,d_{iN}^{0},
 d_{i1}^{1},\ldots,d_{iN}^{1},
 \ldots,
 d_{i1}^{\ell},\ldots,d_{iN}^{\ell})^{T},
$
its coordinates in the basis $\mathcal{B}$ are given by
$[\varepsilon_i]_{\mathcal{B}}=P^{-1}[\varepsilon_i]_{\mathcal{E}}.$
Equivalently,
$$
\varepsilon_i=
\sum_{r=1}^{\theta}\sum_{j=0}^{\ell}
c_{r,j}\nu_{r,j},
\,
[\varepsilon_i]_{\mathcal{B}}
=
(c_{1,0},\ldots,c_{1,\ell},
 c_{2,0},\ldots,c_{\theta,\ell})^{T}.
$$
If all vectors $\varepsilon_i$ are assembled as columns of a matrix
$$
E=
\begin{pmatrix}
|&|&&|\\
\varepsilon_1&\varepsilon_2&\cdots&\varepsilon_{\theta(\ell+1)}\\
|&|&&|
\end{pmatrix}_{\mathcal{E}},
$$
then the change-of-basis matrix is obtained simultaneously as $C=P^{-1}E$,
where the $i$-th column of $C$ contains the coordinates of
$\varepsilon_i$ with respect to $\mathcal{B}$.

# Descomposición de $\mathfrak{B}(V)$ como $D(G)-\text{mod}$

In [469]:
ActionMatrixByGenerator := function( BaseNichols, J_Nichols, gen )
    local N, Amat, Lt, genGi, bj, pol, mon, PolG2, PolG2Norm, pos, coeffss, bi;
    N := Length(BaseNichols);
    Amat := NullMat(N, N);
    # Precálculos fuera del bucle
    Lt := List(QGNAG.Config.gensA, ElementFq);
    genGi := QGNAG.Config.elmsG[Position( allPairsInG, gen )];
    for bj in [1..N] do
        pol := BaseNichols[bj];
        mon := pol[1];
        PolG2     := [[List(mon[1], m -> Position(Lt, genGi * QGNAG.Config.gensA[m]))], [1]];
        PolG2Norm := StrongNormalFormNP(PolG2, J_Nichols);
        pos       := List(PolG2Norm[1], tx -> Position(BaseNichols, [[tx], [1]]));
        coeffss   := PolG2Norm[2] * ChiForSemidirectProduct( genGi )^Length(pol[1][1]);
        for bi in pos do
            Amat[bi][bj] := coeffss[Position(pos, bi)];
        od;
    od;
    return Amat;
end;

function( BaseNichols, J_Nichols, gen ) ... end

In [ ]:
G1NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_FK3, allPairsInG, G.1 );;
G2NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_FK3, allPairsInG, G.2 );;

In [310]:
PolsNormF1 := List(G1NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_FK3));;
PolsNormF2 := List(G2NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_FK3));;

In [314]:
F1_mats := QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormF1, allPairsInG, G.1 );;
F2_mats := QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormF2, allPairsInG, G.2 );;

In [316]:
F1_mats = ActionMatrixByGenerator( Base_FK3, J_FK3, G.1 );
F2_mats = ActionMatrixByGenerator( Base_FK3, J_FK3, G.2 );

true

true

In [317]:
block_mats_s_via_pkg:=Concatenation(
        [
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormF1, allPairsInG, G.1 ),
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormF2, allPairsInG, G.2 )
        ],
        QGNAG_DeltaBlocksByDegree( Base_FK3 )
);

[ rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],       2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ],           [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ],       4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],       2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ],           [ -1, 0, 0, 0 ] ], 3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],      4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 1 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 1 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ) ]

In [318]:
QGNAG_TestRelationsForAllDegrees(block_mats_s_via_pkg, relsGroup, relskG, relsDG);

========================================
Testing degree 0
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 1
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 2
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 3
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 4
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Finished testing all degrees.
========================================

In [320]:
record_data_decomp_nichols:=[];;
for s in SimplesMn do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, block_mats_s_via_pkg );
    Add(record_data_decomp_nichols, decomp_char_s);
od;

In [321]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols, true);

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [322]:
rec_info_nichols := QGNAG_Decomposition(record_data_decomp_nichols);;

In [323]:
QGNAG_PrintDecomposition(rec_info_nichols);

degree 0 = M1
degree 1 = M5
degree 2 = M7 + M8
degree 3 = M5
degree 4 = M1

## Calculo de los $d_{s,k}^j$ con $s, k=1,2,\dots, \theta$ y $j=0,1,\dots,\ell$

For a fixed simple module $M_s \in \{M_1,M_2,...,M_\theta\}$, the function constructs the multiplicity table
$$
d_{sk}^{\,j}
=
\sum_{i=1}^{n} N_k^{i,s} b_{ij},
\qquad
0\leq j\leq \ell,\quad 1\leq k\leq n.
$$
The table has $\ell+1$ rows and $n$ columns: each row corresponds to a
degree $j$ of $\mathfrak{B}$, while each column corresponds to a simple
module $M_k$. Thus, the $(j,k)$-entry is the multiplicity of $M_k$ in
$M_s\otimes\mathfrak{B}_j$.

In [326]:
index_1   := 1;;
data_1k_j := QGNAG_GradedFusionByDegree( index_1, SimplesMn, rec_info_nichols );
QGNAG_RecordListToHTMLTable( data_1k_j, true );

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ]

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [329]:
index_1   := 1;;
epsilon_1 := QGNAG_GradedFusionVector( index_1, SimplesMn, rec_info_nichols );
Length(epsilon_1);

[ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,   0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ]

40

In [330]:
QGNAG_ExportGradedFusionByDegreeToLaTeX("filenamedij.tex", SimplesMn, rec_info_nichols);

In [332]:
data_record_data_decomp[1];
Length(data_record_data_decomp[1]);

[ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ]

8

In [333]:
nu_i0 := QGNAG_CharToShiftedVectorLeft( data_record_data_decomp[1], 0);

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ]

In [334]:
Length(nu_i0);

40

In [338]:
nu_i1 := QGNAG_CharToShiftedVectorLeft( data_record_data_decomp[1], 1);
nu_i2 := QGNAG_CharToShiftedVectorLeft( data_record_data_decomp[1], 2);
nu_i3 := QGNAG_CharToShiftedVectorLeft( data_record_data_decomp[1], 3);
nu_i4 := QGNAG_CharToShiftedVectorLeft( data_record_data_decomp[1], 4);

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

[ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

[ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

In [339]:
nu_ij := QGNAG_AllCharToShiftedVectorsLeft( data_record_data_decomp[1]);

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [340]:
nu_ij[0+1]=nu_i0;

true

In [341]:
nu_ij[1+1]=nu_i1;

true

In [342]:
nu_ij[2+1]=nu_i2;

true

In [343]:
nu_ij[3+1]=nu_i3;

true

In [344]:
QGNAG_CharToShiftedVector(data_record_data_decomp[1],0);

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ]

In [345]:
nu_ij[3+1]=nu_i3;

true

In [346]:
nu_ij[4+1]=nu_i4;

true

In [347]:
basis_nu_ij := QGNAG_CharToBasis( data_record_data_decomp );

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],   [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

$$
\begin{array}{c|c|c}
L_i & d_{\min}(L_i) & \text{Shift }(\nu_{ij}) \\ \hline

{L(e,+)}
& {4}
& \nu_{10} \\ 
&& \nu_{11} \\ 
&& \nu_{12} \\ 
&& \nu_{13} \\ 
&& \nu_{14} \\ \hline

L(e,-)
& 0
& \nu_{20} \\ \hline

{L(e,\rho)}
& {2}
& \nu_{30} \\ 
&& \nu_{31} \\ 
&& \nu_{32} \\ \hline

L(\sigma,+)
& 0
& \nu_{40} \\ \hline

{L(\sigma,-)}
& {2}
& \nu_{50} \\ 
&& \nu_{51} \\ 
&& \nu_{52} \\ \hline

{L(\tau,0)}
& {2}
& \nu_{60} \\ 
&& \nu_{61} \\ 
&& \nu_{62} \\ \hline

L(\tau,1)
& 0
& \nu_{70} \\ \hline

L(\tau,2)
& 0
& \nu_{80} \\ \hline

\text{Total}
&
&
\mathbf{18}
\end{array}
$$

\begin{align*}
\epsilon_1 &= \nu_{10} + \nu_{14} + \nu_{51}&&&
\epsilon_2 &= \nu_{20}&&&
\epsilon_3 &= \nu_{30} + \nu_{51} + \nu_{62}&&&
\epsilon_4 &= \nu_{40}&&&\\
\epsilon_5 &= \nu_{11} + \nu_{13} + \nu_{31} + \nu_{50} + \nu_{52} + \nu_{61}&&&
\epsilon_6 &= \nu_{32} + \nu_{51} + \nu_{60}&&&
\epsilon_7 &= \nu_{70}&&&\epsilon_8 &= \nu_{80}&&&&
\end{align*}

In [348]:
NuVectorNames:=QGNAG_NuVectorNames( data_record_data_decomp );

[ "\\nu_{10}", "\\nu_{11}", "\\nu_{12}", "\\nu_{13}", "\\nu_{14}",   "\\nu_{20}", "\\nu_{21}", "\\nu_{22}", "\\nu_{23}", "\\nu_{24}",   "\\nu_{30}", "\\nu_{31}", "\\nu_{32}", "\\nu_{33}", "\\nu_{34}",   "\\nu_{40}", "\\nu_{41}", "\\nu_{42}", "\\nu_{43}", "\\nu_{44}",   "\\nu_{50}", "\\nu_{51}", "\\nu_{52}", "\\nu_{53}", "\\nu_{54}",   "\\nu_{60}", "\\nu_{61}", "\\nu_{62}", "\\nu_{63}", "\\nu_{64}",   "\\nu_{70}", "\\nu_{71}", "\\nu_{72}", "\\nu_{73}", "\\nu_{74}",   "\\nu_{80}", "\\nu_{81}", "\\nu_{82}", "\\nu_{83}", "\\nu_{84}" ]

In [ ]:
QGNAG_PrintQP := function( coeffs, names )
    local terms, i, c, s, result;
    terms := [];
    for i in [1 .. Length(coeffs)] do
        c := coeffs[i];
        if c <> 0 then
            if c = 1 then
                s := names[i];
            elif c = -1 then
                s := Concatenation("-", names[i]);
            else
                s := Concatenation(String(c), " ", names[i]);
            fi;
            Add(terms, s);
        fi;
    od;
    
    if Length(terms) = 0 then
        result := "\\epsilon = 0";
    else
        result := "\\epsilon = ";
        for i in [1 .. Length(terms)] do
            if i = 1 then
                result := Concatenation(result, terms[i]);
            else
                if terms[i][1] = '-' then
                    result := Concatenation(result, " - ", terms[i]{[2 .. Length(terms[i])]});
                else
                    result := Concatenation(result, " + ", terms[i]);
                fi;
            fi;
        od;
    fi;
    Print(result, "\n");
    return result;
end;;

In [357]:
index   := 1;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat( nu );;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( nu , epsilon );;
coefficients;

true

[ 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 ]

In [358]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{10} + \nu_{14} + \nu_{51} + \nu_{53} + \nu_{72} + \nu_{82}

"\\epsilon = \\nu_{10} + \\nu_{14} + \\nu_{51} + \\nu_{53} + \\nu_{72} + \\nu_\{82}"

In [359]:
data_record_data_decomp;

[ [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ],   [ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),       rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ) ] ]

In [360]:
Length(data_record_data_decomp);

8

In [361]:
data_record_data_decomp[1];

[ rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ) ]

In [362]:
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;

In [363]:
nu;

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [364]:
Length(nu);

40

In [372]:
index   := 2;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;

true

[ 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 ]

In [373]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{20} + \nu_{24} + \nu_{41} + \nu_{43} + \nu_{72} + \nu_{82}

"\\epsilon = \\nu_{20} + \\nu_{24} + \\nu_{41} + \\nu_{43} + \\nu_{72} + \\nu_\{82}"

In [381]:
index   := 2;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;

true

[ 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 ]

In [382]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{20} + \nu_{24} + \nu_{41} + \nu_{43} + \nu_{72} + \nu_{82}

"\\epsilon = \\nu_{20} + \\nu_{24} + \\nu_{41} + \\nu_{43} + \\nu_{72} + \\nu_\{82}"

In [393]:
Length(data_record_data_decomp); # index va de [1..Length(data_record_data_decomp)];
index   := 4;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;
NuVectorNames:=QGNAG_NuVectorNames( data_record_data_decomp );
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{21} + \nu_{23} + \nu_{31} + \nu_{33} + \nu_{40} + 2 \nu_{42} +\
 \nu_{44} + 2 \nu_{52} + \nu_{61} + \nu_{63} + \nu_{71} + \nu_{73} + \nu_{81} \
+ \nu_{83}

8

true

[ 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 0,   0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0 ]

[ "\\nu_{10}", "\\nu_{11}", "\\nu_{12}", "\\nu_{13}", "\\nu_{14}",   "\\nu_{20}", "\\nu_{21}", "\\nu_{22}", "\\nu_{23}", "\\nu_{24}",   "\\nu_{30}", "\\nu_{31}", "\\nu_{32}", "\\nu_{33}", "\\nu_{34}",   "\\nu_{40}", "\\nu_{41}", "\\nu_{42}", "\\nu_{43}", "\\nu_{44}",   "\\nu_{50}", "\\nu_{51}", "\\nu_{52}", "\\nu_{53}", "\\nu_{54}",   "\\nu_{60}", "\\nu_{61}", "\\nu_{62}", "\\nu_{63}", "\\nu_{64}",   "\\nu_{70}", "\\nu_{71}", "\\nu_{72}", "\\nu_{73}", "\\nu_{74}",   "\\nu_{80}", "\\nu_{81}", "\\nu_{82}", "\\nu_{83}", "\\nu_{84}" ]

"\\epsilon = \\nu_{21} + \\nu_{23} + \\nu_{31} + \\nu_{33} + \\nu_{40} + 2 \\n\u_{42} + \\nu_{44} + 2 \\nu_{52} + \\nu_{61} + \\nu_{63} + \\nu_{71} + \\nu_{7\3} + \\nu_{81} + \\nu_{83}"

In [394]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{21} + \nu_{23} + \nu_{31} + \nu_{33} + \nu_{40} + 2 \nu_{42} +\
 \nu_{44} + 2 \nu_{52} + \nu_{61} + \nu_{63} + \nu_{71} + \nu_{73} + \nu_{81} \
+ \nu_{83}

"\\epsilon = \\nu_{21} + \\nu_{23} + \\nu_{31} + \\nu_{33} + \\nu_{40} + 2 \\n\u_{42} + \\nu_{44} + 2 \\nu_{52} + \\nu_{61} + \\nu_{63} + \\nu_{71} + \\nu_{7\3} + \\nu_{81} + \\nu_{83}"

In [402]:
index   := 5;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;

true

[ 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 0, 1,   0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0 ]

In [403]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{11} + \nu_{13} + \nu_{31} + \nu_{33} + 2 \nu_{42} + \nu_{50} +\
 2 \nu_{52} + \nu_{54} + \nu_{61} + \nu_{63} + \nu_{71} + \nu_{73} + \nu_{81} \
+ \nu_{83}

"\\epsilon = \\nu_{11} + \\nu_{13} + \\nu_{31} + \\nu_{33} + 2 \\nu_{42} + \\n\u_{50} + 2 \\nu_{52} + \\nu_{54} + \\nu_{61} + \\nu_{63} + \\nu_{71} + \\nu_{7\3} + \\nu_{81} + \\nu_{83}"

In [411]:
index   := 6;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;

true

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,   1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0 ]

In [412]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = 2 \nu_{32} + \nu_{41} + \nu_{43} + \nu_{51} + \nu_{53} + \nu_{60} +\
 \nu_{64} + \nu_{72} + \nu_{82}

"\\epsilon = 2 \\nu_{32} + \\nu_{41} + \\nu_{43} + \\nu_{51} + \\nu_{53} + \\n\u_{60} + \\nu_{64} + \\nu_{72} + \\nu_{82}"

In [420]:
index   := 7;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( TransposedMat(A), epsilon );;
coefficients;

true

[ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,   0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0 ]

In [421]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{12} + \nu_{22} + \nu_{32} + \nu_{41} + \nu_{43} + \nu_{51} + \
\nu_{53} + \nu_{62} + \nu_{70} + \nu_{72} + \nu_{74}

"\\epsilon = \\nu_{12} + \\nu_{22} + \\nu_{32} + \\nu_{41} + \\nu_{43} + \\nu_\{51} + \\nu_{53} + \\nu_{62} + \\nu_{70} + \\nu_{72} + \\nu_{74}"

In [429]:
# Length(data_record_data_decomp);
index   := 8;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );;
nu      := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );;
A       := TransposedMat(nu);;
A_aug   := TransposedMat( Concatenation( nu, [ epsilon ] ) );;
RankMat( A ) = RankMat( A_aug );
coefficients := SolutionMat( nu , epsilon );;
coefficients;

true

[ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,   0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ]

In [430]:
QGNAG_PrintQP(coefficients, NuVectorNames);

\epsilon = \nu_{12} + \nu_{22} + \nu_{32} + \nu_{41} + \nu_{43} + \nu_{51} + \
\nu_{53} + \nu_{62} + \nu_{80} + \nu_{82} + \nu_{84}

"\\epsilon = \\nu_{12} + \\nu_{22} + \\nu_{32} + \\nu_{41} + \\nu_{43} + \\nu_\{51} + \\nu_{53} + \\nu_{62} + \\nu_{80} + \\nu_{82} + \\nu_{84}"

In [431]:
QGNAG_QPToLaTeX:=function( coeffs, names, index )
    local terms, i, c, s, result;

    terms := [];
    for i in [1..Length(coeffs)] do
        c := coeffs[i];
        if c <> 0 then
            if c = 1 then
                s := names[i];
            elif c = -1 then
                s := Concatenation("-", names[i]);
            else
                s := Concatenation(String(c), "\\,", names[i]);
            fi;
            Add(terms, s);
        fi;
    od;
    if Length(terms) = 0 then
        result := Concatenation("\\epsilon_", String(index), " = 0");
    else
        result := Concatenation("\\epsilon_", String(index), " = ");
        for i in [1..Length(terms)] do
            if i = 1 then
                result := Concatenation(result, terms[i]);
            else
                if terms[i][1] = '-' then
                    result := Concatenation(
                        result,
                        " - ",
                        terms[i]{[2..Length(terms[i])]}
                    );
                else
                    result := Concatenation(
                        result,
                        " + ",
                        terms[i]
                    );
                fi;
            fi;
        od;
    fi;
    return result;
end;

function( coeffs, names, index ) ... end

In [432]:
QGNAG_SaveQPToLaTeX:=function(filename, coeffs, names, index)
    local out, result;
    out := OutputTextFile(filename, false);
    result := QGNAG_QPToLaTeX(coeffs, names, index);
    AppendTo(out, "\\[\n");
    AppendTo(out, result);
    AppendTo(out, "\n\\]\n");
    CloseStream(out);
end;

function( filename, coeffs, names, index ) ... end

In [ ]:
index   := 4;;
epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols);
nu := QGNAG_AllShiftedVectorsLeft(data_record_data_decomp);
A := TransposedMat(nu);
A_aug := TransposedMat( Concatenation(nu, [epsilon]));
RankMat(A) = RankMat(A_aug);
coefficients := SolutionMat( TransposedMat(A), epsilon );
NuVectorNames := QGNAG_NuVectorNames(data_record_data_decomp);

true

In [ ]:
QGNAG_SaveQPToLaTeX( "qp_index_4.tex", coefficients, NuVectorNames, index);

In [442]:
QGNAG_SaveAllQPToLaTeX:=function(filename, data_record_data_decomp, SimplesMn, rec_info_nichols )
    local out,
          nu,
          A,
          NuVectorNames,
          index,
          epsilon,
          coefficients,
          result;

    out := OutputTextFile(filename, false);
    nu  := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp);
    A   := TransposedMat(nu);
    NuVectorNames := QGNAG_NuVectorNames(data_record_data_decomp);
    for index in [1..Length(data_record_data_decomp)] do
        epsilon := QGNAG_GradedFusionVector( index, SimplesMn, rec_info_nichols );
        if RankMat(A) = RankMat( TransposedMat( Concatenation(nu, [epsilon]) ) ) then
            coefficients := SolutionMat( TransposedMat(A), epsilon );
            result := QGNAG_QPToLaTeX( coefficients, NuVectorNames, index );
            AppendTo(out, "\\[\n");
            AppendTo(out, result);
            AppendTo(out, "\n\\]\n\n");
        fi;
    od;
    CloseStream(out);
end;

function( filename, data_record_data_decomp, SimplesMn, rec_info_nichols ) ...\ end

In [443]:
QGNAG_SaveAllQPToLaTeX("qp_all_index.tex", data_record_data_decomp, SimplesMn, rec_info_nichols);

Polinomiso $t_{s, j}$

In [444]:
QGNAG_EpsilonPolynomials := function( data_record_data_decomp, SimplesMn, rec_info_nichols)
    local nu,
          A,
          result,
          index,
          epsilon,
          coefficients,
          N,
          j,
          number_of_shifts,
          polynomial,
          d,
          position,
          coeff,
          epsilon_data;

    nu := QGNAG_AllShiftedVectorsLeft( data_record_data_decomp );
    A := TransposedMat(nu);
    N := Length(data_record_data_decomp);
    result := [];
    for index in [1..N] do
        epsilon := QGNAG_GradedFusionVector(
            index,
            SimplesMn,
            rec_info_nichols
        );
        if RankMat(A) <> RankMat( TransposedMat( Concatenation(nu, [epsilon]) ) ) then
            Error( "epsilon_", index, " is not in the span of the shifted vectors" );
        fi;
        coefficients := SolutionMat( TransposedMat(A), epsilon );
        epsilon_data := rec(
            epsilon := index,
            coefficients := coefficients,
            polynomials := []
        );
        position := 1;
        for j in [1..N] do
            number_of_shifts := Length( QGNAG_AllCharToShiftedVectorsLeft( data_record_data_decomp[j] ) );
            polynomial := [];
            for d in [0..number_of_shifts-1] do
                coeff := coefficients[position];
                Add(polynomial, coeff);
                position := position + 1;
            od;
            Add( epsilon_data.polynomials, polynomial );
        od;
        Add(result, epsilon_data);
    od;
    return result;
end;

function( data_record_data_decomp, SimplesMn, rec_info_nichols ) ... end

In [445]:
epsilon_polynomials:=QGNAG_EpsilonPolynomials( data_record_data_decomp, SimplesMn, rec_info_nichols);

[ rec( coefficients := [ 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0          ], epsilon := 1,       polynomials := [ [ 1, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 0, 1, 0, 1, 0 ],           [ 0, 0, 0, 0, 0 ], [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ] ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0          ], epsilon := 2,       polynomials := [ [ 0, 0, 0, 0, 0 ], [ 1, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0 ], [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ] ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,           0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0          ], epsilon := 3,       polynomials := [ [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, 1 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ],           [ 0, 0, 2, 0, 0 ], [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ] ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,           2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0          ], epsilon := 4,       polynomials := [ [ 0, 0, 0, 0, 0 ], [ 0, 1, 0, 1, 0 ],           [ 0, 1, 0, 1, 0 ], [ 1, 0, 2, 0, 1 ], [ 0, 0, 2, 0, 0 ],           [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ] ] ),   rec( coefficients := [ 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,           2, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0          ], epsilon := 5,       polynomials := [ [ 0, 1, 0, 1, 0 ], [ 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 1, 0 ], [ 0, 0, 2, 0, 0 ], [ 1, 0, 2, 0, 1 ],           [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ] ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1,           0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0          ], epsilon := 6,       polynomials := [ [ 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0 ],           [ 0, 0, 2, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ],           [ 1, 0, 0, 0, 1 ], [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ] ] ),   rec( coefficients := [ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,           0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0          ], epsilon := 7,       polynomials := [ [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ],           [ 0, 0, 1, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ],           [ 0, 0, 1, 0, 0 ], [ 1, 0, 1, 0, 1 ], [ 0, 0, 0, 0, 0 ] ] ),   rec( coefficients := [ 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,           0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1          ], epsilon := 8,       polynomials := [ [ 0, 0, 1, 0, 0 ], [ 0, 0, 1, 0, 0 ],           [ 0, 0, 1, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ],           [ 0, 0, 1, 0, 0 ], [ 0, 0, 0, 0, 0 ], [ 1, 0, 1, 0, 1 ] ] ) ]

In [446]:
epsilon_polynomials[4];

rec( coefficients := [ 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0 ], epsilon := 4, polynomials := [ [ 0, 0, 0, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ], [ 1, 0, 2, 0, 1 ], [ 0, 0, 2, 0, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ], [ 0, 1, 0, 1, 0 ] ] )

In [447]:
epsilon_polynomials[5].polynomials[3];

[ 0, 1, 0, 1, 0 ]

In [448]:
epsilon_polynomials[4].polynomials[4];

[ 1, 0, 2, 0, 1 ]

In [449]:
QGNAG_EvaluateEpsilonPolynomialsAtOne:=function( epsilon_polynomials )
    local result, epsilon_data, values, polynomial;

    result := [];

    for epsilon_data in epsilon_polynomials do
        values := [];

        for polynomial in epsilon_data.polynomials do
            Add(values, Sum(polynomial));
        od;

        Add(
            result,
            rec(
                epsilon := epsilon_data.epsilon,
                values := values
            )
        );
    od;

    return result;
end;

function( epsilon_polynomials ) ... end

In [449]:
values_at_one :=
    QGNAG_EvaluateEpsilonPolynomialsAtOne(
        epsilon_polynomials
    );;

In [451]:
values_at_one;

[ rec( epsilon := 1, values := [ 2, 0, 0, 0, 2, 0, 1, 1 ] ),   rec( epsilon := 2, values := [ 0, 2, 0, 2, 0, 0, 1, 1 ] ),   rec( epsilon := 3, values := [ 0, 0, 2, 2, 2, 2, 1, 1 ] ),   rec( epsilon := 4, values := [ 0, 2, 2, 4, 2, 2, 2, 2 ] ),   rec( epsilon := 5, values := [ 2, 0, 2, 2, 4, 2, 2, 2 ] ),   rec( epsilon := 6, values := [ 0, 0, 2, 2, 2, 2, 1, 1 ] ),   rec( epsilon := 7, values := [ 1, 1, 1, 2, 2, 1, 3, 0 ] ),   rec( epsilon := 8, values := [ 1, 1, 1, 2, 2, 1, 0, 3 ] ) ]

In [452]:
epsilon_polynomials[8].polynomials[8];

[ 1, 0, 1, 0, 1 ]

In [453]:
QGNAG_NonzeroLinearCombinationVectors := function( nu, coefficients )
    return Filtered(
        [1..Length(nu)],
        j -> coefficients[j] <> 0
    );
end;

function( nu, coefficients ) ... end

In [454]:
QGNAG_NonzeroLinearCombinationVectors( nu, coefficients );

[ 7, 9, 12, 14, 16, 18, 20, 23, 27, 29, 32, 34, 37, 39 ]

In [455]:
QGNAG_NonzeroVectors := function( nu, coefficients )
    local indices;

    indices := Filtered(
        [1..Length(nu)],
        j -> coefficients[j] <> 0
    );

    return List(indices, j -> nu[j]);
end;

function( nu, coefficients ) ... end

In [456]:
QGNAG_NonzeroVectors( nu, coefficients );

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [468]:
# ================================
#   Fin del código principal
# ================================

t1 := NanosecondsSinceEpoch();;

# Calcular duración en segundos
dur := (t1 - t0) / 1000000000.0;;

# Convertir a horas, minutos y segundos
horas := Int(dur / 3600);;
minutos := Int((dur - horas * 3600) / 60);;
segundos := Round(dur - horas * 3600 - minutos * 60);;

# Mostrar resultado
Print("\n=====================================\n");
Print("Tiempo total de ejecución:\n");
Print(String(horas), " horas, ", String(minutos), " minutos, ", String(segundos), " segundos.\n");
Print("=====================================\n");
mem_kb := MemoryUsageByGAPinKbytes();;
mem_gb := mem_kb / (1024.0 * 1024.0);;
Print("Memoria usada por GAP: ", mem_gb, " GB\n");

=====================================
Tiempo total de ejecución:
0 horas, 0 minutos, 46. segundos.
=====================================
Memoria usada por GAP: 4.125347137451172 GB