# El álgebra $\mathfrak{D}=\mathcal{D}(\mathcal{FK}_m\# \Bbbk\mathbb{S}_{3})$
Sea $\mathcal{FK}_m$ el álgebra presentada por generadores

$$
\{ x_{(ij)} \mid i<j \in \mathbb{I}_m \}
$$
y relaciones
$$
\begin{align*}
x_{(ij)}^2 &= 0, && i<j \in \mathbb{I}_m, \\
x_{(ij)}x_{(kl)} - x_{(kl)}x_{(ij)} &= 0, && i,j,k,l \in \mathbb{I}_m, \text{ todos distintos}, \\
x_{(jk)}x_{(ik)} - x_{(ij)}x_{(jk)} + x_{(ik)}x_{(ij)} &= 0, && i<j<k \in \mathbb{I}_m, \\
x_{(ik)}x_{(jk)} - x_{(jk)}x_{(ij)} + x_{(ij)}x_{(ik)} &= 0, && i<j<k \in \mathbb{I}_m.
\end{align*}
$$

## El álgebra $\mathcal{FK}_3$


Para $m=3$, el álgebra $\mathcal{FK}_3$ está generada por
$$
x_{(12)},\quad x_{(13)},\quad x_{(23)}
$$
y las relaciones son:
$$
\begin{aligned}
x_{(12)}^2 &= 0, \\
x_{(13)}^2 &= 0, \\
x_{(23)}^2 &= 0, \\
x_{(23)}x_{(13)} - x_{(12)}x_{(23)} + x_{(13)}x_{(12)} &= 0, \\
x_{(13)}x_{(23)} - x_{(23)}x_{(12)} + x_{(12)}x_{(13)} &= 0.
\end{aligned}
$$

In [1332]:
LoadPackage("SCSCP");

true

In [1333]:
t0 := NanosecondsSinceEpoch();;

In [1334]:
LoadPackage("GBNP");

true

In [1335]:
GBNP.ConfigPrint(
    "X0",    # 1
    "X1",    # 2
    "X2",    # 3
    "σ",     # 4   σ      (0, g)   (1,2)
    "τ",     # 5   τ      (1, 0)   (1,2,3)
    "De",    # 6   e      (0, 0)   ()  
    "D12",   # 7   F1     (0, g)   (1,2)
    "D123",  # 8   F2     (1, 0)   (1,2,3)
    "D13",   # 9   F1F2^2 (1, g)   (1,3)
    "D132",  # 10  F2^2   (w, 0)   (1,3,2)
    "D23",   # 11  F1F2   (w, g)   (2,3)
    "Y0",    # 12
    "Y1",    # 13
    "Y2"     # 14
);

In [1343]:
nX       := 3;;
nGensOfG := 2;;
nDelta   := 6;;
nY       := 3;;
nTotal   := nX + nGensOfG  +  nDelta + nY;;
F        := FreeAssociativeAlgebraWithOne( Rationals, nTotal );;
gens     := GeneratorsOfAlgebra(F);;
e        := gens[1];;

In [1346]:
# Generators 𝓑(V) #
X12 := gens[2];;
X13 := gens[3];;
X23 := gens[4];;

### Generadores of Group G

In [1348]:
# Generators k(S_3) #
F1 := gens[5];;
F2 := gens[6];;

In [1354]:
# Generators k^(S_3) #
De   := gens[7];;   # 6   e      (0, 0)   ()  
D12  := gens[8];;   # 7   F1     (0, g)   (1,2)
D123 := gens[9];;   # 8   F2     (1, 0)   (1,2,3)
D13  := gens[10];;  # 9   F1F2^2 (1, g)   (1,3)
D132 := gens[11];;  # 10  F2^2   (w, 0)   (1,3,2)
D23  := gens[12];;  # 11  F1F2   (w, g)   (2,3)

In [1357]:
# Generators 𝓑(V) Dual #
Y12 := gens[13];;
Y13 := gens[14];;
Y23 := gens[15];;

In [1361]:
gensX      := GP2NPList( gens{[2..4]} );;
gensG      := GP2NPList( gens{[5, 6]} );;
gensDeltas := GP2NPList( gens{[7..12]} );;
gensY      := GP2NPList( gens{[13..15]} );;

In [1362]:
PrintNPList( gensX );

 X0
 X1
 X2

In [1363]:
PrintNPList( gensG );

 σ
 τ

In [1364]:
PrintNPList( gensDeltas );

 De
 D12
 D123
 D13
 D132
 D23

In [1365]:
PrintNPList( gensY );

 Y0
 Y1
 Y2

In [1370]:
xIndex        := [1..3];;
groupElemsInF := [
    e,               #1 1      (0, 0)  e
    F1,              #2 F1     (0, g)  (1,2)
    F2,              #5 F2     (1, 0)  (1,2,3)
    F1*F2^2,         #1 F1F2^2 (1, g)  (1,3)
    F2^2,            #4 F2^2   (w, 0)  (1,3,2)
    F1*F2            #8 F1F2   (w, g)  (2,3)
];;
groupIndex     := List(groupElemsInF, elm -> GP2NP(elm)[1][1]);;
deltaIndex     := [6..11];;
yIndex         := [12..14];;

## Relaciones en el álgebra $\mathcal{FK}_3$

### *Nilpotencia cuadrática*:
$$
\begin{align*}
x_{(12)}^2 = x_{(13)}^2 = x_{(23)}^2 = 0,
\end{align*}
$$
Para nosotros serán:
$$
\begin{align*}
x_{12}^2 = x_{13}^2 = x_{23}^2 = 0.
\end{align*}
$$

### Relaciones triples para $i<j<k$:

- Para $1<2<3$:
$$
x^{2}_{(ij)} \;=\; x_{(ij)}x_{(ik)} \;+\; x_{(jk)}x_{(ij)} \;+\; x_{(ik)}x_{(jk)}
\;=\;
x_{(ik)}x_{(ij)} \;+\; x_{(ij)}x_{(jk)} \;+\; x_{(jk)}x_{(ik)}
\;=\; 0,
\quad \text{(dada por } B(V)).
$$

$$
\begin{aligned}
x_{(12)}x_{(13)} + x_{(23)}x_{(12)} + x_{(13)}x_{(23)} 
\quad \text{y} \quad 
x_{(13)}x_{(12)} + x_{(12)}x_{(23)} + x_{(23)}x_{(13)}.
\end{aligned}
$$

In [1381]:
###############################################################################
# x_(ij)^2 = 0, x_(ij)x_(jk)+x_(jk)x_(ik)+x_(ik)x_(ij)=0, etc. 
# (álgebra Fomin-Kirillov n=3,
###############################################################################

# Generadores x_(ij)
gensFK3      := [ (1,2), (1,3), (2,3) ];;
generators   := gens{[2..4]};;
relationsFK3 := List( generators, s -> s^2);;
i            := 1;;
j            := 2;;
k            := 3;;
Xij          := generators[Position(gensFK3, (i,j))];;
Xik          := generators[Position(gensFK3, (i,k))];;
Xjk          := generators[Position(gensFK3, (j,k))];;
# primera relación: x_(ij)x_(jk) + x_(jk)x_(ik) + x_(ik)x_(ij) = 0
Add(relationsFK3, Xij*Xjk + Xjk*Xik + Xik*Xij );
# segunda relación: x_(jk)x_(ij) + x_(ik)x_(jk) + x_(ij)x_(ik) = 0
Add(relationsFK3, Xjk*Xij + Xik*Xjk + Xij*Xik );

In [1383]:
relsFK3 := GP2NPList(relationsFK3);;
PrintNPList( relsFK3 );
#X12^2 
#X13^2 
#X23^2 
#X12X23 + X23X13 + X13X12 
#X23X12 + X13X23 + X12X13

 X0^2
 X1^2
 X2^2
 X2X1 + X1X0 + X0X2
 X2X0 + X1X2 + X0X1

In [1385]:
J_FK3 := SGrobner( relsFK3 );;
PrintNPList( J_FK3 );

 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2X1 + X1X0 + X0X2
 X2^2
 X1X0X1 - X0X1X0

In [1386]:
DimQA( J_FK3, 3 );

12

In [1388]:
Base_FK3 := BaseQA( J_FK3, 3, 0 );;
PrintNPList( Base_FK3 );

 1
 X0
 X1
 X2
 X0X1
 X0X2
 X1X0
 X1X2
 X0X1X0
 X0X1X2
 X1X0X2
 X0X1X0X2

## Relaciones en el álgebra $\mathcal{FK}_3$ dual

### *Nilpotencia cuadrática*:
$$
\begin{align*}
y_{(12)}^2 = y_{(13)}^2 = y_{(23)}^2 = 0.\\
\end{align*}
$$
Para nosotros serán:
$$
\begin{align*}
y_{12}^2 = y_{13}^2 = y_{23}^2 = 0.
\end{align*}
$$

### Relaciones triples para $i<j<k$:

- Para $1<2<3$:
$$
\begin{align*}
    y_{(23)}y_{(13)} + y_{(12)}y_{(23)} + y_{(13)}y_{(12)} &= 0,&&\Rightarrow& y_3y_1 + y_0y_3 + y_1y_0 &= 0, \\
    y_{(13)}x_{(23)} + y_{(23)}y_{(12)} + y_{(12)}y_{(13)} &= 0,&&\Rightarrow& y_1y_3 + y_3y_0 + y_0y_1 &= 0.
\end{align*}
$$

In [1393]:
###############################################################################
# y_(ij)^2 = 0, y_(ij)y_(jk)+y_(jk)y_(ik)+y_(ik)y_(ij)=0, etc. 
# (álgebra Fomin-Kirillov n=3,
###############################################################################

# Generadores x_(ij)
gensFK3     := [ (1,2), (1,3), (2,3) ];;
relsFK3dual := [];;
# Paso 1: Relaciones cuadráticas x_(ij)^2 = 0
for k in [1..Length(gensFK3 )] do
    Add(relsFK3dual, [[ [yIndex[k], yIndex[k]] ], [1]]);;
od;
# Paso 2: Relaciones cúbicas de tres índices distintos
triples := [[1,2,3]];;  # único triple distinto para n=3
for t in triples do
    i := t[1];
    j := t[2];
    k := t[3];
    ij := Position(gensFK3, (i,j));
    ik := Position(gensFK3, (i,k));
    jk := Position(gensFK3, (j,k));
    # primera relación: y_(ij)y_(jk) + y_(jk)y_(ik) + y_(ik)y_(ij) = 0
    Add(relsFK3dual,[[[yIndex[ij],yIndex[jk]],[yIndex[jk],yIndex[ik]],[yIndex[ik],yIndex[ij]]],[1,1,1]]);
    # segunda relación: y_(jk)y_(ij) + y_(ik)y_(jk) + y_(ij)y_(ik) = 0
    Add(relsFK3dual,[[[yIndex[jk],yIndex[ij]],[yIndex[ik],yIndex[jk]],[yIndex[ij],yIndex[ik]]],[1,1,1]]);
od;

In [1394]:
# Imprimir las relaciones
PrintNPList(relsFK3dual);

 Y0^2
 Y1^2
 Y2^2
 Y0Y2 + Y2Y1 + Y1Y0
 Y2Y0 + Y1Y2 + Y0Y1

In [1395]:
I := Concatenation(
    gensX,
    gensG,
    gensDeltas,
    relsFK3dual    # 9 rels
);;

In [1396]:
J := SGrobner( I );;

In [1397]:
DimQA(J, 14);

12

In [1399]:
Base_FK3dual := BaseQA( J, 14, 0 );;
PrintNPList( Base_FK3dual );

 1
 Y0
 Y1
 Y2
 Y0Y1
 Y0Y2
 Y1Y0
 Y1Y2
 Y0Y1Y0
 Y0Y1Y2
 Y1Y0Y2
 Y0Y1Y0Y2

## Presentación concreta para $\mathbb{S}_{3}$.

Tomemos la presentación habitual
$$
\mathbb{S}_{3} = \langle \sigma, \tau \mid \sigma^2 = e,\ \tau^3 = e,\ \sigma\tau\sigma = \tau^{-1} \rangle,
$$
por ejemplo con $\sigma = (12)$ y $\tau = (123)$.

Entonces, los elementos de $\mathbb{S}_{3}$ son
$$
\mathbb{S}_{3} = \{\, e, (12), (13), (23), (123), (132) \,\}.
$$

En términos de los generadores $\sigma$ y $\tau$, podemos escribir:
$$
\begin{aligned}
e &= e, \\
\sigma &= (12), \\
\tau &= (123), \\
\tau^{2} &= (132)\\
\sigma \tau &= (23), \\
\sigma \tau^{2} &= (13), \\
\end{aligned}
$$

In [1400]:
relsGroup := [
    F1^2-e,            # 1
    F2^3-e,            # 2
    F1*F2*F1-F2^2        # 3
];;

In [1402]:
relsGroup := GP2NPList( relsGroup );;
PrintNPList( relsGroup );

 σ^2 - 1
 τ^3 - 1
 στσ - τ^2

In [1403]:
J := SGrobner(Concatenation(
    relsGroup,
    gensX,
    # gensG,
    gensDeltas,
    gensY
    )
);;

In [1404]:
PrintNPList( J );

 X0
 X1
 X2
 De
 D12
 D123
 D13
 D132
 D23
 Y0
 Y1
 Y2
 σ^2 - 1
 στσ - τ^2
 στ^2 - τσ
 τστ - σ
 τ^2σ - στ
 τ^3 - 1

In [1405]:
DimQA(J, 14);

6

In [1406]:
PrintNPList(BaseQA(J, 14, 0));

 1
 σ
 τ
 στ
 τσ
 τ^2

## Relaciones dadas por $\Bbbk^{\mathbb{S}_{3}}$.

In [1407]:
LoadPackage( "QGNAG" );

true

In [1408]:
config := rec(
    m            := 2,                   # Valor para m
    q            := 3,                   # Valor para q := p^n
    xIndex       := xIndex,
    groupIndex   := groupIndex,
    deltaIndex   := deltaIndex,
    yIndex       := yIndex,
    nX           := nX,
    nGensOfG     := nGensOfG,
    nDelta       := nDelta,
    nY           := nY,
    DEFAULT      := false,
    TEST         := false,
    PROD         := false,
    DEV          := true,
);;

In [1409]:
QGNAGSetConfig(config);

In [1410]:
QGNAGShowConfig();

========================================
         QGNAG CONFIGURATION
========================================

Base Structures
---------------
Cyclic group order (C_m)     : 2
Finite field size (q = p^n)  : 3

Derived Objects
---------------
Cyclic ring            : Z/2Z
Finite field           : GF(3)

Index Sets
----------
xIndex     : [ 1 .. 3 ]
groupIndex : [ [  ], [ 4 ], [ 5 ], [ 4, 5, 5 ], [ 5, 5 ], [ 4, 5 ] ]
deltaIndex : [ 6 .. 11 ]
yIndex     : [ 12 .. 14 ]

Dimensions
----------
Number of x generators       : 3
Number of group generators   : 2
Number of delta generators   : 6
Number of y generators       : 3

Elements Of Group
---------------
Elements:
( 0 , 0 )
( 0 , 1 )
( 1 , 0 )
( 1 , 1 )
( ζ_2 , 0 )
( ζ_2 , 1 )

Nichols Algebra
---------------
Number of j generators: [ 0, 1, ζ_2 ]

========================================

In [1411]:
relskG := RelationsOfkGdual(deltaIndex);;

In [1413]:
Print("Se generaron ", Length(relskG), " relaciones en k^G.\n");
PrintNPList( relskG );

Se generaron 37 relaciones en k^G.
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 DeD23
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D12D23
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D123D23
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D13D23
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 D132D23
 D23De
 D23D12
 D23D123
 D23D13
 D23D132
 D23^2 - D23
 De + D12 + D123 + D13 + D132 + D23 - 1

In [1414]:
J := SGrobner(Concatenation(
    relskG,
    gensX,
    gensG,
    # gensDeltas,
    gensY
    )
);;

In [1415]:
DimQA(J, 14);

6

In [1416]:
PrintNPList(BaseQA(J, 14, 0));

 1
 De
 D12
 D123
 D13
 D132

## Relaciones dadas por $\mathcal{D}(\mathbb{S}_{3})$ 2

Sea $\mathbb{S}_{3} = \{ e, (12), (13), (23), (123), (132) \}$. 

La multiplicación en $\mathcal{D}(\mathbb{S}_{3})$ está dada por
$$
\delta_h g = g\, \delta_{g^{-1}hg}.
$$
Por lo tanto, la tabla queda:
$$
\begin{array}{c|cccccc}
g \backslash h 
& \delta_{e} 
& \delta_{(12)} 
& \delta_{(123)} 
& \delta_{(132)}
& \delta_{(23)} 
& \delta_{(13)} 
\\ \hline
e 
& e\,\delta_{e} 
& e\,\delta_{(12)} 
& e\,\delta_{(123)} 
& e\,\delta_{(132)}
& e\,\delta_{(23)}
& e\,\delta_{(13)}  
\\[4pt]

(12) 
& (12)\,\delta_{e} 
& (12)\,\delta_{(12)} 
& (12)\,\delta_{(132)} 
& (12)\,\delta_{(123)}
& (12)\,\delta_{(13)}
& (12)\,\delta_{(23)} 
\\[4pt]

(123) 
& (123)\,\delta_{e} 
& (123)\,\delta_{(13)}
& (123)\,\delta_{(123)} 
& (123)\,\delta_{(132)} 
& (123)\,\delta_{(12)}
& (123)\,\delta_{(23)} 
\\[4pt]

(132) 
& (132)\,\delta_{e} 
& (132)\,\delta_{(23)}
& (132)\,\delta_{(123)} 
& (132)\,\delta_{(132)} 
& (132)\,\delta_{(13)} 
& (132)\,\delta_{(12)} 
\\[4pt]

(23) 
& (23)\,\delta_{e} 
& (23)\,\delta_{(13)}
& (23)\,\delta_{(132)} 
& (23)\,\delta_{(123)}
& (23)\,\delta_{(23)} 
& (23)\,\delta_{(12)}  
\\[4pt]

(13) 
& (13)\,\delta_{e} 
& (13)\,\delta_{(23)}
& (13)\,\delta_{(132)} 
& (13)\,\delta_{(123)} 
& (13)\,\delta_{(12)}
& (13)\,\delta_{(13)} 
\end{array}
$$

La siguiente lista verifica la identidad 
$$
\delta_h g - g\,\delta_{g^{-1}hg} = 0:
$$

$$
\begin{align*}
1.\; \delta_e e - e\delta_e &= 0, &&&
7.\; \delta_{(12)} e - e\delta_e &= 0, &&&
13.\; \delta_{(123)} e - e\delta_e &= 0,\\
2.\; \delta_e \sigma - \sigma\delta_{e} &= 0, &&&
8.\; \delta_{(12)}\sigma - \sigma\delta_{(12)} &= 0, &&&
14.\; \delta_{(123)}\sigma - \sigma\delta_{(132)} &= 0,\\
3.\; \delta_e\tau - \tau\delta_{e} &= 0, &&&
9.\; \delta_{(12)}\tau - \tau\delta_{(13)} &= 0, &&&
15.\; \delta_{(123)}\tau - \tau\delta_{(123)} &= 0,\\
4.\; \delta_e \tau^2 - \tau^2\delta_{e} &= 0, &&&
10.\; \delta_{(12)}\tau^2 - \tau^2\delta_{(23)} &= 0, &&&
16.\; \delta_{(123)}\tau^2 - \tau^2\delta_{(123)} &= 0,\\
5.\; \delta_e \sigma\tau - \sigma\tau\delta_{e} &= 0, &&&
11.\; \delta_{(12)}\sigma\tau - \sigma\tau\delta_{(13)} &= 0, &&&
17.\; \delta_{(123)}\sigma\tau - \sigma\tau\delta_{(132)} &= 0,\\
6.\; \delta_e \sigma\tau^2 - \sigma\tau^2\delta_{e} &= 0, &&&
12.\; \delta_{(12)}\sigma\tau^2 - \sigma\tau^2\delta_{(23)} &= 0, &&&
18.\; \delta_{(123)}\sigma\tau^2 - \sigma\tau^2\delta_{(132)} &= 0,\\[4pt]
19.\; \delta_{(132)} e - e \delta_{(132)} &= 0, &&&
25.\; \delta_{(23)} e - e \delta_{(23)} &= 0, &&&
31.\; \delta_{(13)} e - e \delta_{(13)} &= 0,\\
20.\; \delta_{(132)}\sigma - \sigma\delta_{(132)} &= 0, &&&
26.\; \delta_{(23)}\sigma - \sigma\delta_{(13)} &= 0, &&&
32.\; \delta_{(13)}\sigma - \sigma\delta_{(23)} &= 0,\\
21.\; \delta_{(132)}\tau - \tau\delta_{(132)} &= 0, &&&
27.\; \delta_{(23)}\tau - \tau\delta_{(12)} &= 0, &&&
33.\; \delta_{(13)}\tau - \tau\delta_{(23)} &= 0,\\
22.\; \delta_{(132)}\tau^2 - \tau^2\delta_{(132)} &= 0, &&&
28.\; \delta_{(23)}\tau^2 - \tau^2\delta_{(13)} &= 0, &&&
34.\; \delta_{(13)}\tau^2 - \tau^2\delta_{(12)} &= 0,\\
23.\; \delta_{(132)}\sigma\tau - \sigma\tau\delta_{(123)} &= 0, &&&
29.\; \delta_{(23)}\sigma\tau - \sigma\tau\delta_{(23)} &= 0, &&&
35.\; \delta_{(13)}\sigma\tau - \sigma\tau\delta_{(12)} &= 0,\\
24.\; \delta_{(132)}\sigma\tau^2 - \sigma\tau^2\delta_{(123)}  &= 0, &&&
30.\; \delta_{(23)}\sigma\tau^2 - \sigma\tau^2\delta_{(12)} &= 0, &&&
36.\; \delta_{(13)}\sigma\tau^2 - \sigma\tau^2\delta_{(13)} &= 0.
\end{align*}
$$

In [1426]:
K           := CyclicGroup(3);;
H           := CyclicGroup(2);;
AutK        := AutomorphismGroup(K);;
gensAutK    := GeneratorsOfGroup(AutK);;
T           := GroupHomomorphismByImages(H, AutK, [H.1], gensAutK);;
G           := SemidirectProduct(H, T, K);;
embK        := Embedding(G, 2);;
embH        := Embedding(G, 1);;
HinG        := List([0 .. Size(H) - 1], x -> embH(H.1^x));;
allPairsInG := Concatenation(List(K, x -> List(HinG, y -> embK(x) * y)));;

In [1427]:
relsDG := CommutationRelationsGroupAndDeltas(allPairsInG, groupIndex, deltaIndex);

[ [ [ [ 6 ], [ 6 ] ], [ 1, -1 ] ], [ [ [ 7 ], [ 7 ] ], [ 1, -1 ] ],   [ [ [ 8 ], [ 8 ] ], [ 1, -1 ] ], [ [ [ 9 ], [ 9 ] ], [ 1, -1 ] ],   [ [ [ 10 ], [ 10 ] ], [ 1, -1 ] ], [ [ [ 11 ], [ 11 ] ], [ 1, -1 ] ],   [ [ [ 6, 4 ], [ 4, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 4 ], [ 4, 7 ] ], [ 1, -1 ] ]    , [ [ [ 8, 4 ], [ 4, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4 ], [ 4, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 4 ], [ 4, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4 ], [ 4, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 5 ], [ 5, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 5 ], [ 5, 9 ] ], [ 1, -1 ] ]    , [ [ [ 8, 5 ], [ 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5 ], [ 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 5 ], [ 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5 ], [ 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5, 5 ], [ 4, 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5, 5 ], [ 4, 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5, 5 ], [ 4, 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5, 5 ], [ 4, 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5, 5 ], [ 4, 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5, 5 ], [ 4, 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 5, 5 ], [ 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 5, 5 ], [ 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 5, 5 ], [ 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 5 ], [ 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 5 ], [ 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 5 ], [ 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5 ], [ 4, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5 ], [ 4, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5 ], [ 4, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5 ], [ 4, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5 ], [ 4, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5 ], [ 4, 5, 11 ] ], [ 1, -1 ] ] ]

In [1429]:
Print("Se generaron ", Length(relsDG), " relaciones δ_h g = g δ_{g*h*g^-1}.\n");
PrintNPList(relsDG);

Se generaron 36 relaciones δ_h g = g δ_{g*h*g^-1}.
 De - De
 D12 - D12
 D123 - D123
 D13 - D13
 D132 - D132
 D23 - D23
 Deσ - σDe
 D12σ - σD12
 D123σ - σD132
 D13σ - σD23
 D132σ - σD123
 D23σ - σD13
 Deτ - τDe
 D12τ - τD13
 D123τ - τD123
 D13τ - τD23
 D132τ - τD132
 D23τ - τD12
 Deστ^2 - στ^2De
 D12στ^2 - στ^2D23
 D123στ^2 - στ^2D132
 D13στ^2 - στ^2D13
 D132στ^2 - στ^2D123
 D23στ^2 - στ^2D12
 Deτ^2 - τ^2De
 D12τ^2 - τ^2D23
 D123τ^2 - τ^2D123
 D13τ^2 - τ^2D12
 D132τ^2 - τ^2D132
 D23τ^2 - τ^2D13
 Deστ - στDe
 D12στ - στD13
 D123στ - στD132
 D13στ - στD12
 D132στ - στD123
 D23στ - στD23

In [1430]:
J := SGrobner(Concatenation(
    relsGroup,
    relskG,
    relsDG,
    gensX,
    gensY
    )
);;

In [1431]:
DimQA(J, 14);

36

In [1431]:
PrintNPList(BaseQA(J, 14, 0));

 1
 σ
 τ
 De
 D12
 D123
 D13
 D132
 στ
 σDe
 σD12
 σD123
 σD13
 σD132
 τσ
 τ^2
 τDe
 τD12
 τD123
 τD13
 τD132
 στDe
 στD12
 στD123
 στD13
 στD132
 τσDe
 τσD12
 τσD123
 τσD13
 τσD132
 τ^2De
 τ^2D12
 τ^2D123
 τ^2D13
 τ^2D132

## Relaciones dadas por la the bosonizaciones $\mathcal{FK}_3\#\Bbbk\mathbb{S}_{3}$

## Relaciones $gx_{(ij)} = sgn(g) x_{g(ij)g^{-1}} g$, evaluadas para todos los $g \in S_3$

### En términos de $x_{(ij)}$ para todo $g \in \mathbb{S}_3$


- Caso $(ij) = (12)$:

$$
\begin{aligned}
e\,x_{(12)} &= x_{(12)}\,e, \\[4pt]
(12)\,x_{(12)} &= -\,x_{(12)}\,(12), \\[4pt]
(123)\,x_{(12)} &= x_{(23)}\,(123), \\[4pt]
(132)\,x_{(12)} &= x_{(13)}\,(132), \\[4pt]
(23)\,x_{(12)} &= -\,x_{(13)}\,(23), \\[4pt]
(13)\,x_{(12)} &= -\,x_{(23)}\,(13).
\end{aligned}
$$

- Caso $(ij) = (13)$

$$
\begin{aligned}
e\,x_{(13)} &= x_{(13)}\,e, \\[4pt]
(12)\,x_{(13)} &= -\,x_{(23)}\,(12), \\[4pt]
(123)\,x_{(13)} &= x_{(12)}\,(123), \\[4pt]
(132)\,x_{(13)} &= x_{(23)}\,(132), \\[4pt]
(23)\,x_{(13)} &= -\,x_{(12)}\,(23), \\[4pt]
(13)\,x_{(13)} &= -\,x_{(13)}\,(13).
\end{aligned}
$$

- Caso $(ij) = (23)$:

$$
\begin{aligned}
e\,x_{(23)} &= x_{(23)}\,e, \\[4pt]
(12)\,x_{(23)} &= -\,x_{(13)}\,(12), \\[4pt]
(123)\,x_{(23)} &= x_{(13)}\,(123), \\[4pt]
(132)\,x_{(23)} &= x_{(12)}\,(132), \\[4pt]
(23)\,x_{(23)} &= -\,x_{(23)}\,(23), \\[4pt]
(13)\,x_{(23)} &= -\,x_{(12)}\,(13).
\end{aligned}
$$

In [1432]:
elmsG := GetElementsOfG();;

In [1434]:
gensA:=QGNAG.Config.gensA;

[ 0*Z(3), Z(3)^0, Z(3) ]

In [1434]:
rels0 := RelationsGivenByNicholsSmashkG(gensA[1], elmsG);;
PrintNPList(rels0);

 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ

In [1436]:
rels1 := RelationsGivenByNicholsSmashkG(gensA[2], elmsG);;
PrintNPList(rels1);

 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ

In [1438]:
relsOmega := RelationsGivenByNicholsSmashkG(gensA[3], elmsG);;
PrintNPList(relsOmega);

 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ

In [1440]:
relsxBos:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [1441]:
# Probar la primera relación
Print("Se generaron ", Length(relsxBos), " relaciones en total.\n");
PrintNPList(relsxBos);

Se generaron 18 relaciones en total.
 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ
 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ
 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ

In [1443]:
J := SGrobner(Concatenation(
    relsFK3,
    relsxBos,
    relsGroup,
    gensDeltas,
    gensY
    )
);;

In [1445]:
DimQA(J, 14);

72

# El algebra $\mathfrak{B}(\overline{V})\#\Bbbk G$

## Relaciones $y_{(ij)} g = sign(g)  g  y_{g(ij)g^{-1}}$, evaluadas para todos los $g \in S_3$

### En términos de $y_{(ij)}$ para todo $g \in \mathbb{S}_3$

- Caso $(ij)=(12)$:
$$
\begin{aligned}
y_{(12)}\, e &= e\, y_{(12)}, \\[1mm]
y_{(12)}\, (12) &= - (12)\, y_{(12)}, \\[1mm]
y_{(12)}\, (123) &= (123)\, y_{(23)}, \\[1mm]
y_{(12)}\, (132) &= (132)\, y_{(13)}, \\[1mm]
y_{(12)}\, (23) &= - (23)\, y_{(13)}, \\[1mm]
y_{(12)}\, (13) &= - (13)\, y_{(23)}.
\end{aligned}
$$

- Caso $(ij)=(13)$:
$$
\begin{aligned}
y_{(13)}\, e &= e\, y_{(13)}, \\[1mm]
y_{(13)}\, (12) &= - (12)\, y_{(23)}, \\[1mm]
y_{(13)}\, (123) &= (123)\, y_{(12)}, \\[1mm]
y_{(13)}\, (132) &= (132)\, y_{(23)}, \\[1mm]
y_{(13)}\, (23) &= - (23)\, y_{(12)}, \\[1mm]
y_{(13)}\, (13) &= - (13)\, y_{(13)}.
\end{aligned}
$$

- Caso $(ij)=(23)$:
$$
\begin{aligned}
y_{(23)}\, e &= e\, y_{(23)}, \\[1mm]
y_{(23)}\, (12) &= - (12)\, y_{(13)}, \\[1mm]
y_{(23)}\, (123) &= (123)\, y_{(13)}, \\[1mm]
y_{(23)}\, (132) &= (132)\, y_{(12)}, \\[1mm]
y_{(23)}\, (23) &= - (23)\, y_{(23)}, \\[1mm]
y_{(23)}\, (13) &= - (13)\, y_{(12)}.
\end{aligned}
$$

In [1445]:
rels0 := RelationsGivenByNicholsDualSmashkG(gensA[1], elmsG);;

In [1446]:
rels1 := RelationsGivenByNicholsDualSmashkG(gensA[2], elmsG);;

In [1447]:
relsOmega:=RelationsGivenByNicholsDualSmashkG(gensA[3], elmsG);;

In [1448]:
relsyBos:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [1451]:
# Probar la primera relación
Print("Se generaron ", Length(relsyBos), " relaciones en total.\n");
PrintNPList(relsyBos);

Se generaron 18 relaciones en total.
 Y0 - Y0
 Y0σ + σY0
 Y0τ - τY1
 Y0στ^2 + στ^2Y2
 Y0τ^2 - τ^2Y2
 Y0στ + στY1
 Y1 - Y1
 Y1σ + σY2
 Y1τ - τY2
 Y1στ^2 + στ^2Y1
 Y1τ^2 - τ^2Y0
 Y1στ + στY0
 Y2 - Y2
 Y2σ + σY1
 Y2τ - τY0
 Y2στ^2 + στ^2Y0
 Y2τ^2 - τ^2Y1
 Y2στ + στY2

In [1452]:
I := Concatenation(
    gensX,
    gensDeltas,
    relsGroup,    # 7 rels
    relsyBos,     # 96 rels
    relsFK3dual    # 9 rels
);;

In [1453]:
# =====================================================
# Paso 5: Calcular la base de Gröbner
# =====================================================
J := SGrobner(I);;

In [1454]:
DimQA(J, 14);

72

# El algebra $\mathfrak{B}(V)\#\Bbbk^G$
## Relaciones $\delta_h x_{(ij)} = x_{(ij)} \delta_{(ij)h}$
con $h$ escrito en términos de los generadores
$\sigma = (12), \tau = (123)$ de 
$\mathbb{S}_3 = \{ e, \sigma, \tau, \tau^2, \sigma\tau, \sigma\tau^2 \}$
y sabiendo que $\sigma\tau = (23)$, $\sigma\tau^2 = (13)$


- Caso $(ij) = (12)$:
$$
\begin{aligned}
\delta_{e}\,x_{(12)} &= x_{(12)}\,\delta_{(12)}, \\[4pt]
\delta_{(12)}\,x_{(12)} &= x_{(12)}\,\delta_{e}, \\[4pt]
\delta_{(123)}\,x_{(12)} &= x_{(12)}\,\delta_{(23)}, \\[4pt]
\delta_{(132)}\,x_{(12)} &= x_{(12)}\,\delta_{(13)}, \\[4pt]
\delta_{(23)}\,x_{(12)} &= x_{(12)}\,\delta_{(123)}, \\[4pt]
\delta_{(13)}\,x_{(12)} &= x_{(12)}\,\delta_{(132)}.
\end{aligned}
$$

- Caso $(ij) = (13)$:
$$
\begin{aligned}
\delta_{e}\,x_{(13)} &= x_{(13)}\,\delta_{(13)}, \\[4pt]
\delta_{(12)}\,x_{(13)} &= x_{(13)}\,\delta_{(123)}, \\[4pt]
\delta_{(123)}\,x_{(13)} &= x_{(13)}\,\delta_{(12)}, \\[4pt]
\delta_{(132)}\,x_{(13)} &= x_{(13)}\,\delta_{(23)}, \\[4pt]
\delta_{(23)}\,x_{(13)} &= x_{(13)}\,\delta_{(132)}, \\[4pt]
\delta_{(13)}\,x_{(13)} &= x_{(13)}\,\delta_{e}.
\end{aligned}
$$

- Caso $(ij) = (23)$:
$$
\begin{aligned}
\delta_{e}\,x_{(23)} &= x_{(23)}\,\delta_{(23)}, \\[4pt]
\delta_{(12)}\,x_{(23)} &= x_{(23)}\,\delta_{(132)}, \\[4pt]
\delta_{(123)}\,x_{(23)} &= x_{(23)}\,\delta_{(13)}, \\[4pt]
\delta_{(132)}\,x_{(23)} &= x_{(23)}\,\delta_{(12)}, \\[4pt]
\delta_{(23)}\,x_{(23)} &= x_{(23)}\,\delta_{e}, \\[4pt]
\delta_{(13)}\,x_{(23)} &= x_{(23)}\,\delta_{(123)}.
\end{aligned}
$$

In [1455]:
rels0 := RelationsGivenByNicholsSmashkGDual(gensA[1], elmsG);;

In [1456]:
PrintNPList(rels0);

 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123

In [1457]:
rels1 := RelationsGivenByNicholsSmashkGDual(gensA[2], elmsG);;

In [1458]:
PrintNPList(rels1);

 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132

In [1459]:
relsOmega := RelationsGivenByNicholsSmashkGDual(gensA[3], elmsG);;

In [1460]:
PrintNPList(relsOmega);

 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De

In [1461]:
relsDx:=Concatenation(
    rels0,
    rels1,
    relsOmega
);;

In [1463]:
Print("Se generaron ", Length(relsDx), " relaciones δ_h x_(ij) = x_(ij) δ_{(ij)h}.\n");
PrintNPList(relsDx);

Se generaron 18 relaciones δ_h x_(ij) = x_(ij) δ_{(ij)h}.
 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123
 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132
 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De

In [1464]:
J := SGrobner(Concatenation(
    relsFK3,
    relskG,
    relsDx,
    gensG,
    gensY
    )
);;

In [1465]:
DimQA(J, 14);

72

## Relaciones $\delta_g y_{(ij)} = y_{(ij)} \delta_{(ij)g}$
con $g$ escrito en términos de los generadores
$\sigma = (12), \tau = (123)$ de 
$\mathbb{S}_3 = \{ e, \sigma, \tau, \tau^2, \sigma\tau, \sigma\tau^2 \}$
y sabiendo que $\sigma\tau = (23)$, $\sigma\tau^2 = (13)$

- Caso $(ij) = (12)$:
$$
\begin{aligned}
\delta_{e}\,y_{(12)} &= y_{(12)}\,\delta_{(12)}, \\[2mm]
\delta_{(12)}\,y_{(12)} &= y_{(12)}\,\delta_{e}, \\[2mm]
\delta_{(123)}\,y_{(12)} &= y_{(12)}\,\delta_{(23)}, \\[2mm]
\delta_{(132)}\,y_{(12)} &= y_{(12)}\,\delta_{(13)}, \\[2mm]
\delta_{(23)}\,y_{(12)} &= y_{(12)}\,\delta_{(123)}, \\[2mm]
\delta_{(13)}\,y_{(12)} &= y_{(12)}\,\delta_{(132)}.
\end{aligned}
$$

- Caso $(ij) = (13)$:
$$
\begin{aligned}
\delta_{e}\,y_{(13)} &= y_{(13)}\,\delta_{(13)}, \\[2mm]
\delta_{(12)}\,y_{(13)} &= y_{(13)}\,\delta_{(123)}, \\[2mm]
\delta_{(123)}\,y_{(13)} &= y_{(13)}\,\delta_{(12)}, \\[2mm]
\delta_{(132)}\,y_{(13)} &= y_{(13)}\,\delta_{(23)}, \\[2mm]
\delta_{(23)}\,y_{(13)} &= y_{(13)}\,\delta_{(132)}, \\[2mm]
\delta_{(13)}\,y_{(13)} &= y_{(13)}\,\delta_{e}.
\end{aligned}
$$

- Caso $(ij) = (23)$:

$$
\begin{aligned}
\delta_{e}\,y_{(23)} &= y_{(23)}\,\delta_{(23)}, \\[2mm]
\delta_{(12)}\,y_{(23)} &= y_{(23)}\,\delta_{(132)}, \\[2mm]
\delta_{(123)}\,y_{(23)} &= y_{(23)}\,\delta_{(13)}, \\[2mm]
\delta_{(132)}\,y_{(23)} &= y_{(23)}\,\delta_{(12)}, \\[2mm]
\delta_{(23)}\,y_{(23)} &= y_{(23)}\,\delta_{e}, \\[2mm]
\delta_{(13)}\,y_{(23)} &= y_{(23)}\,\delta_{(123)}.
\end{aligned}
$$

In [1465]:
rels0 := RelationsGivenByNicholsDualSmashkGDual(gensA[1], elmsG);;
rels1 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], elmsG);;
rels3 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], elmsG);;

In [1468]:
relsDy:=Concatenation(
    rels0,
    rels1,
    rels3
);;

In [1471]:
Print("Se generaron ", Length(relsDy), " relaciones δ_g y_(ij) = y_(ij) δ_{(ij)g}.\n");
PrintNPList(relsDy);

Se generaron 18 relaciones δ_g y_(ij) = y_(ij) δ_{(ij)g}.
 DeY0 - Y0D12
 D12Y0 - Y0De
 D123Y0 - Y0D23
 D13Y0 - Y0D132
 D132Y0 - Y0D13
 D23Y0 - Y0D123
 DeY1 - Y1D13
 D12Y1 - Y1D123
 D123Y1 - Y1D12
 D13Y1 - Y1De
 D132Y1 - Y1D23
 D23Y1 - Y1D132
 DeY2 - Y2D23
 D12Y2 - Y2D132
 D123Y2 - Y2D13
 D13Y2 - Y2D123
 D132Y2 - Y2D12
 D23Y2 - Y2De

In [1472]:
J := SGrobner(Concatenation(
    relsFK3dual,
    relskG,
    relsDy,
    gensG,
    gensX
    )
);;

In [1473]:
DimQA(J, 14);

72

# Calculo $\mathfrak{B}(V)\#D(G)$

In [1474]:
I := Concatenation(
    relsFK3,      # 5 rels
    # ------------------------
    relsGroup,    # 3 rels
    relskG,       # 37 rels
    relsDG,       # 36 rels
    # ------------------------
    relsxBos,     # 18 rels
    relsDx,       # 18 rels
    # ------------------------
    gensY         # 3 gens
);

[ [ [ [ 1, 1 ] ], [ 1 ] ], [ [ [ 2, 2 ] ], [ 1 ] ], [ [ [ 3, 3 ] ], [ 1 ] ],   [ [ [ 3, 2 ], [ 2, 1 ], [ 1, 3 ] ], [ 1, 1, 1 ] ],   [ [ [ 3, 1 ], [ 2, 3 ], [ 1, 2 ] ], [ 1, 1, 1 ] ],   [ [ [ 4, 4 ], [  ] ], [ 1, -1 ] ], [ [ [ 5, 5, 5 ], [  ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 4 ], [ 5, 5 ] ], [ 1, -1 ] ], [ [ [ 6, 6 ], [ 6 ] ], [ 1, -1 ] ]    , [ [ [ 6, 7 ] ], [ 1 ] ], [ [ [ 6, 8 ] ], [ 1 ] ],   [ [ [ 6, 9 ] ], [ 1 ] ], [ [ [ 6, 10 ] ], [ 1 ] ], [ [ [ 6, 11 ] ], [ 1 ] ],  [ [ [ 7, 6 ] ], [ 1 ] ], [ [ [ 7, 7 ], [ 7 ] ], [ 1, -1 ] ],   [ [ [ 7, 8 ] ], [ 1 ] ], [ [ [ 7, 9 ] ], [ 1 ] ], [ [ [ 7, 10 ] ], [ 1 ] ],   [ [ [ 7, 11 ] ], [ 1 ] ], [ [ [ 8, 6 ] ], [ 1 ] ], [ [ [ 8, 7 ] ], [ 1 ] ],   [ [ [ 8, 8 ], [ 8 ] ], [ 1, -1 ] ], [ [ [ 8, 9 ] ], [ 1 ] ],   [ [ [ 8, 10 ] ], [ 1 ] ], [ [ [ 8, 11 ] ], [ 1 ] ], [ [ [ 9, 6 ] ], [ 1 ] ],  [ [ [ 9, 7 ] ], [ 1 ] ], [ [ [ 9, 8 ] ], [ 1 ] ],   [ [ [ 9, 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 9, 10 ] ], [ 1 ] ],   [ [ [ 9, 11 ] ], [ 1 ] ], [ [ [ 10, 6 ] ], [ 1 ] ],   [ [ [ 10, 7 ] ], [ 1 ] ], [ [ [ 10, 8 ] ], [ 1 ] ],   [ [ [ 10, 9 ] ], [ 1 ] ], [ [ [ 10, 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 10, 11 ] ], [ 1 ] ], [ [ [ 11, 6 ] ], [ 1 ] ],   [ [ [ 11, 7 ] ], [ 1 ] ], [ [ [ 11, 8 ] ], [ 1 ] ],   [ [ [ 11, 9 ] ], [ 1 ] ], [ [ [ 11, 10 ] ], [ 1 ] ],   [ [ [ 11, 11 ], [ 11 ] ], [ 1, -1 ] ],   [ [ [ 6 ], [ 7 ], [ 8 ], [ 9 ], [ 10 ], [ 11 ], [  ] ],       [ 1, 1, 1, 1, 1, 1, -1 ] ], [ [ [ 6 ], [ 6 ] ], [ 1, -1 ] ],   [ [ [ 7 ], [ 7 ] ], [ 1, -1 ] ], [ [ [ 8 ], [ 8 ] ], [ 1, -1 ] ],   [ [ [ 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 11 ], [ 11 ] ], [ 1, -1 ] ], [ [ [ 6, 4 ], [ 4, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4 ], [ 4, 7 ] ], [ 1, -1 ] ],   [ [ [ 8, 4 ], [ 4, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4 ], [ 4, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 4 ], [ 4, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4 ], [ 4, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 5 ], [ 5, 6 ] ], [ 1, -1 ] ], [ [ [ 7, 5 ], [ 5, 9 ] ], [ 1, -1 ] ]    , [ [ [ 8, 5 ], [ 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5 ], [ 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 10, 5 ], [ 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5 ], [ 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5, 5 ], [ 4, 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5, 5 ], [ 4, 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5, 5 ], [ 4, 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5, 5 ], [ 4, 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5, 5 ], [ 4, 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5, 5 ], [ 4, 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 6, 5, 5 ], [ 5, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 5, 5 ], [ 5, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 8, 5, 5 ], [ 5, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 5 ], [ 5, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 5 ], [ 5, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 5 ], [ 5, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 6, 4, 5 ], [ 4, 5, 6 ] ], [ 1, -1 ] ],   [ [ [ 7, 4, 5 ], [ 4, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 8, 4, 5 ], [ 4, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 9, 4, 5 ], [ 4, 5, 7 ] ], [ 1, -1 ] ],   [ [ [ 10, 4, 5 ], [ 4, 5, 8 ] ], [ 1, -1 ] ],   [ [ [ 11, 4, 5 ], [ 4, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 1 ], [ 1 ] ], [ 1, -1 ] ], [ [ [ 4, 1 ], [ 1, 4 ] ], [ 1, 1 ] ],   [ [ [ 5, 1 ], [ 3, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 5, 1 ], [ 3, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 1 ], [ 2, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 1 ], [ 2, 4, 5 ] ], [ 1, 1 ] ], [ [ [ 2 ], [ 2 ] ], [ 1, -1 ] ],  [ [ [ 4, 2 ], [ 3, 4 ] ], [ 1, 1 ] ], [ [ [ 5, 2 ], [ 1, 5 ] ], [ 1, -1 ] ],  [ [ [ 4, 5, 5, 2 ], [ 2, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 2 ], [ 3, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 2 ], [ 1, 4, 5 ] ], [ 1, 1 ] ], [ [ [ 3 ], [ 3 ] ], [ 1, -1 ] ],  [ [ [ 4, 3 ], [ 2, 4 ] ], [ 1, 1 ] ], [ [ [ 5, 3 ], [ 2, 5 ] ], [ 1, -1 ] ],  [ [ [ 4, 5, 5, 3 ], [ 1, 4, 5, 5 ] ], [ 1, 1 ] ],   [ [ [ 5, 5, 3 ], [ 1, 5, 5 ] ], [ 1, -1 ] ],   [ [ [ 4, 5, 3 ], [ 3, 4, 5 ] ], [ 1, 1 ] ],   [ [ [ 6, 1 ], [ 1, 7 ] ], [ 1, -1 ] ], [ [ [ 7, 1 ], [ 1, 6 ] ], [ 1, -1 ] ]    , [ [ [ 8, 1 ], [ 1, 11 ] ], [ 1, -1 ] ],   [ [ [ 9, 1 ], [ 1, 10 ] ], [ 1, -1 ] ],   [ [ [ 10, 1 ], [ 1, 9 ] ], [ 1, -1 ] ],   [ [ [ 11, 1 ], [ 1, 8 ] ], [ 1, -1 ] ],   [ [ [ 6, 2 ], [ 2, 9 ] ], [ 1, -1 ] ], [ [ [ 7, 2 ], [ 2, 8 ] ], [ 1, -1 ] ]    , [ [ [ 8, 2 ], [ 2, 7 ] ], [ 1, -1 ] ],   [ [ [ 9, 2 ], [ 2, 6 ] ], [ 1, -1 ] ],   [ [ [ 10, 2 ], [ 2, 11 ] ], [ 1, -1 ] ],   [ [ [ 11, 2 ], [ 2, 10 ] ], [ 1, -1 ] ],   [ [ [ 6, 3 ], [ 3, 11 ] ], [ 1, -1 ] ],   [ [ [ 7, 3 ], [ 3, 10 ] ], [ 1, -1 ] ],   [ [ [ 8, 3 ], [ 3, 9 ] ], [ 1, -1 ] ], [ [ [ 9, 3 ], [ 3, 8 ] ], [ 1, -1 ] ]    , [ [ [ 10, 3 ], [ 3, 7 ] ], [ 1, -1 ] ],   [ [ [ 11, 3 ], [ 3, 6 ] ], [ 1, -1 ] ], [ [ [ 12 ] ], [ 1 ] ],   [ [ [ 13 ] ], [ 1 ] ], [ [ [ 14 ] ], [ 1 ] ] ]

In [1476]:
5 + 3 + 37 + 36 + 2*18 + 3;
Length(I);

120

120

In [1477]:
J_D_ge_0 := SGrobner(I);;

In [1478]:
12*6^2;

432

In [1479]:
DimQA(J_D_ge_0, 14);

432

## Relaciones dadas de la definción de $\mathfrak{D}$,
$$
\begin{aligned}
y_{(ij)} x_{(ij)} + x_{(ij)} y_{(ij)} &= 1 + (ij)(\delta_{(ij)} - \delta_e), \\
y_{(ik)} x_{(ij)} + x_{(ij)} y_{(jk)} &= (ij)(\delta_{(ik)} - \delta_{(ik)(ij)}),
\end{aligned}
$$
para todas las transposiciones $(ij), (ik) \in \mathbb{S}_{3}$.

- Relaciones del tipo $y_{(ij)}x_{(ij)} + x_{(ij)}y_{(ij)} = 1 + (ij)(\delta_{(ij)} - \delta_e)$:
$$
\begin{aligned}
y_{(12)}x_{(12)} + x_{(12)}y_{(12)} &= 1 + (12)(\delta_{(12)} - \delta_e),\\
y_{(13)}x_{(13)} + x_{(13)}y_{(13)} &= 1 + (13)(\delta_{(13)} - \delta_e),\\
y_{(23)}x_{(23)} + x_{(23)}y_{(23)} &= 1 + (23)(\delta_{(23)} - \delta_e),
\end{aligned}
$$

- Relaciones del tipo $y_{(ik)}x_{(ij)} + x_{(ij)}y_{(jk)} = (ij)(\delta_{(ik)} - \delta_{(ik)(ij)})$:
$$
\begin{aligned}
y_{(13)}x_{(12)} + x_{(12)}y_{(23)} &= (12)(\delta_{(13)} - \delta_{(123)}),\\
y_{(23)}x_{(12)} + x_{(12)}y_{(13)} &= (12)(\delta_{(23)} - \delta_{(132)}),\\
y_{(12)}x_{(13)} + x_{(13)}y_{(23)} &= (13)(\delta_{(12)} - \delta_{(132)}),\\
y_{(23)}x_{(13)} + x_{(13)}y_{(12)} &= (13)(\delta_{(23)} - \delta_{(123)}),\\
y_{(12)}x_{(23)} + x_{(23)}y_{(13)} &= (23)(\delta_{(12)} - \delta_{(123)}),\\
y_{(13)}x_{(23)} + x_{(23)}y_{(12)} &= (23)(\delta_{(13)} - \delta_{(132)}).
\end{aligned}
$$

In [1479]:
PrintNP(GetConmutationRules(gensA[2], gensA[2]));

 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13

In [1482]:
relsQG:=[];;
for i in gensA do
    for j in gensA do
       resl_ij := GetConmutationRules(i, j);;
       Add(relsQG, resl_ij);
    od;
od;

In [1482]:
Print("Total relations generated: ", Length(relsQG), ".\n");
PrintNPList(relsQG);

Total relations generated: 9.
 Y0X0 + X0Y0 - 1 + σDe - σD12
 Y1X0 + X0Y2 + σD123 - σD13
 Y2X0 + X0Y1 + σD132 - σD23
 Y0X1 + X1Y2 + στ^2D132 - στ^2D12
 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13
 Y2X1 + X1Y0 - στ^2D23 + στ^2D123
 Y0X2 + X2Y1 - στD12 + στD123
 Y1X2 + X2Y0 - στD13 + στD132
 Y2X2 + X2Y2 - 1 + στDe - στD23

Para concluir, afirmamos que los elementos de $V$ y $\overline{V}$ satisfacen la relación \eqref{4.5}.
En efecto, si $x \in V$ e $y \in \overline{V}$, se cumple que
$$
yx - (y_{(-1)} \cdot x)y_{(0)} =  \langle y, x \rangle - \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
por \eqref{3.5}. Por otro lado, la regla de conmutación \eqref{3.4} implica que
$$
y_{(-1)}x_{(-1)} \langle y_{(0)}, x_{(0)} \rangle = \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
donde $\langle y_{(-2)}, x_{(-3)} \rangle$ denota el emparejamiento \eqref{3.2}; comparar con \cite[eq.~(21)]{33}. \qed

In [1484]:
I := Concatenation(
    relsFK3,      # 5 rels
    relsGroup,    # 3 rels
    relskG,       # 37 rels
    relsDG,       # 36 rels
    relsxBos,     # 18 rels
    relsDx,       # 18 rels
    relsDy,       # 18 rels
    relsyBos,     # 18 rels
    relsQG,       # 9 rels
    relsFK3dual   # 5 rels
);;

In [1486]:
Length(I);

167

In [1487]:
PrintNPList( I );

 X0^2
 X1^2
 X2^2
 X2X1 + X1X0 + X0X2
 X2X0 + X1X2 + X0X1
 σ^2 - 1
 τ^3 - 1
 στσ - τ^2
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 DeD23
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D12D23
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D123D23
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D13D23
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 D132D23
 D23De
 D23D12
 D23D123
 D23D13
 D23D132
 D23^2 - D23
 De + D12 + D123 + D13 + D132 + D23 - 1
 De - De
 D12 - D12
 D123 - D123
 D13 - D13
 D132 - D132
 D23 - D23
 Deσ - σDe
 D12σ - σD12
 D123σ - σD132
 D13σ - σD23
 D132σ - σD123
 D23σ - σD13
 Deτ - τDe
 D12τ - τD13
 D123τ - τD123
 D13τ - τD23
 D132τ - τD132
 D23τ - τD12
 Deστ^2 - στ^2De
 D12στ^2 - στ^2D23
 D123στ^2 - στ^2D132
 D13στ^2 - στ^2D13
 D132στ^2 - στ^2D123
 D23στ^2 - στ^2D12
 Deτ^2 - τ^2De
 D12τ^2 - τ^2D23
 D123τ^2 - τ^2D123
 D13τ^2 - τ^2D12
 D132τ^2 - τ^2D132
 D23τ^2 - τ^2D13
 Deστ - στDe
 D12στ - στD13
 D123στ - στD132
 D13στ - στD12
 D132στ - στD123
 D23στ - στD23
 X0 - X0
 σX0 + X0σ
 τX0 - X2τ
 στ^2X0 + X2στ^2
 τ^2X0 - X1τ^2
 στX0 + X1στ
 X1 - X1
 σX1 + X2σ
 τX1 - X0τ
 στ^2X1 + X1στ^2
 τ^2X1 - X2τ^2
 στX1 + X0στ
 X2 - X2
 σX2 + X1σ
 τX2 - X1τ
 στ^2X2 + X0στ^2
 τ^2X2 - X0τ^2
 στX2 + X2στ
 DeX0 - X0D12
 D12X0 - X0De
 D123X0 - X0D23
 D13X0 - X0D132
 D132X0 - X0D13
 D23X0 - X0D123
 DeX1 - X1D13
 D12X1 - X1D123
 D123X1 - X1D12
 D13X1 - X1De
 D132X1 - X1D23
 D23X1 - X1D132
 DeX2 - X2D23
 D12X2 - X2D132
 D123X2 - X2D13
 D13X2 - X2D123
 D132X2 - X2D12
 D23X2 - X2De
 DeY0 - Y0D12
 D12Y0 - Y0De
 D123Y0 - Y0D23
 D13Y0 - Y0D132
 D132Y0 - Y0D13
 D23Y0 - Y0D123
 DeY1 - Y1D13
 D12Y1 - Y1D123
 D123Y1 - Y1D12
 D13Y1 - Y1De
 D132Y1 - Y1D23
 D23Y1 - Y1D132
 DeY2 - Y2D23
 D12Y2 - Y2D132
 D123Y2 - Y2D13
 D13Y2 - Y2D123
 D132Y2 - Y2D12
 D23Y2 - Y2De
 Y0 - Y0
 Y0σ + σY0
 Y0τ - τY1
 Y0στ^2 + στ^2Y2
 Y0τ^2 - τ^2Y2
 Y0στ + στY1
 Y1 - Y1
 Y1σ + σY2
 Y1τ - τY2
 Y1στ^2 + στ^2Y1
 Y1τ^2 - τ^2Y0
 Y1στ + στY0
 Y2 - Y2
 Y2σ + σY1
 Y2τ - τY0
 Y2στ^2 + στ^2Y0
 Y2τ^2 - τ^2Y1
 Y2στ + στY2
 Y0X0 + X0Y0 - 1 + σDe - σD12
 Y1X0 + X0Y2 + σD123 - σD13
 Y2X0 + X0Y1 + σD132 - σD23
 Y0X1 + X1Y2 + στ^2D132 - στ^2D12
 Y1X1 + X1Y1 - 1 + στ^2De - στ^2D13
 Y2X1 + X1Y0 - στ^2D23 + στ^2D123
 Y0X2 + X2Y1 - στD12 + στD123
 Y1X2 + X2Y0 - στD13 + στD132
 Y2X2 + X2Y2 - 1 + στDe - στD23
 Y0^2
 Y1^2
 Y2^2
 Y0Y2 + Y2Y1 + Y1Y0
 Y2Y0 + Y1Y2 + Y0Y1

In [1488]:
J := SGrobner( I );;

In [1489]:
PrintNPList( J );

 D23 + D132 + D13 + D123 + D12 + De - 1
 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2X1 + X1X0 + X0X2
 X2^2
 σX0 + X0σ
 σX1 + X2σ
 σX2 + X1σ
 σ^2 - 1
 τX0 - X2τ
 τX1 - X0τ
 τX2 - X1τ
 DeX0 - X0D12
 DeX1 - X1D13
 DeX2 + X2D132 + X2D13 + X2D123 + X2D12 + X2De - X2
 Deσ - σDe
 Deτ - τDe
 De^2 - De
 DeD12
 DeD123
 DeD13
 DeD132
 D12X0 - X0De
 D12X1 - X1D123
 D12X2 - X2D132
 D12σ - σD12
 D12τ - τD13
 D12De
 D12^2 - D12
 D12D123
 D12D13
 D12D132
 D123X0 + X0D132 + X0D13 + X0D123 + X0D12 + X0De - X0
 D123X1 - X1D12
 D123X2 - X2D13
 D123σ - σD132
 D123τ - τD123
 D123De
 D123D12
 D123^2 - D123
 D123D13
 D123D132
 D13X0 - X0D132
 D13X1 - X1De
 D13X2 - X2D123
 D13σ + σD132 + σD13 + σD123 + σD12 + σDe - σ
 D13τ + τD132 + τD13 + τD123 + τD12 + τDe - τ
 D13De
 D13D12
 D13D123
 D13^2 - D13
 D13D132
 D132X0 - X0D13
 D132X1 + X1D132 + X1D13 + X1D123 + X1D12 + X1De - X1
 D132X2 - X2D12
 D132σ - σD123
 D132τ - τD132
 D132De
 D132D12
 D132D123
 D132D13
 D132^2 - D132
 Y0X0 - σD12 + σDe + X0Y0 - 1
 Y0σ + σY0
 Y0τ - τY1
 Y0De - D12Y0
 Y0D12 - DeY0
 Y0D123 + D132Y0 + D13Y0 + D123Y0 + D12Y0 + DeY0 - Y0
 Y0D13 - D132Y0
 Y0D132 - D13Y0
 Y0^2
 Y1X0 - σD13 + σD123 + X0Y2
 Y1σ + σY2
 Y1τ - τY2
 Y1De - D13Y1
 Y1D12 - D123Y1
 Y1D123 - D12Y1
 Y1D13 - DeY1
 Y1D132 + D132Y1 + D13Y1 + D123Y1 + D12Y1 + DeY1 - Y1
 Y1^2
 Y2X0 + 2σD132 + σD13 + σD123 + σD12 + σDe + X0Y1 - σ
 Y2σ + σY1
 Y2τ - τY0
 Y2De + D132Y2 + D13Y2 + D123Y2 + D12Y2 + DeY2 - Y2
 Y2D12 - D132Y2
 Y2D123 - D13Y2
 Y2D13 - D123Y2
 Y2D132 - D12Y2
 Y2Y0 + Y1Y2 + Y0Y1
 Y2Y1 + Y1Y0 + Y0Y2
 Y2^2
 X1X0X1 - X0X1X0
 στσ - τ^2
 στ^2 - τσ
 στD123 - στD12 + Y0X2 + X2Y1
 στD13 + στD12 + στDe + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ + 1/2X2Y2 \
- 1/2X2Y1 - 1/2X2Y0 - 1/2
 στD132 + στD12 + στDe + 1/2Y2X2 + 1/2Y1X2 - 1/2Y0X2 - 1/2στ + 1/2X2Y2\
 - 1/2X2Y1 + 1/2X2Y0 - 1/2
 σY0X2 - X1σY1 + τD123 - τD12
 σY1X2 - X1σY0 + τD132 - τD13
 σY2X2 - X1σY2 + τD132 + τD13 + τD123 + τD12 + 2τDe - τ - σ
 τστ - σ
 τσD123 + τσD12 + τσDe + 1/2Y2X1 + 1/2Y1X1 - 1/2Y0X1 - 1/2τσ - 1/2X1Y2\
 + 1/2X1Y1 + 1/2X1Y0 - 1/2
 τσD13 - τσDe - Y1X1 - X1Y1 + 1
 τσD132 - τσD12 + Y0X1 + X1Y2
 τ^2σ - στ
 τ^3 - 1
 τ^2D123 + τ^2D12 + τ^2De + 1/2σY2X1 + 1/2σY1X1 - 1/2σY0X1 + 1/2X2σY2 -\
 1/2X2σY1 - 1/2X2σY0 - 1/2τ^2 - 1/2σ
 τ^2D13 - τ^2De - σY1X1 + X2σY1 + σ
 τ^2D132 - τ^2D12 + σY0X1 - X2σY2
 τY0X1 - 2στD12 - στDe + X0τY2 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ -\
 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 τY0X2 + X1τY1 + σD123 - σD12
 τY1X1 + στD12 + 2στDe + X0τY1 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ +\
 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - τ - 1/2
 τY1X2 + X1τY0 + σD132 - σD13
 τY2X1 + στD12 - στDe + X0τY0 - Y2X2 - Y0X2 - X2Y2 - X2Y1 + 1
 τY2X2 + X1τY2 + σD132 + σD13 + σD123 + σD12 + 2σDe - τ - σ
 DeY0X1 + X1D13Y2
 DeY0X2 - X2D132Y1 - X2D13Y1 - X2D123Y1 - X2D12Y1 - X2DeY1 + X2Y1
 DeY1X1 + τσDe + X1D13Y1 - De
 DeY1X2 - X2D132Y0 - X2D13Y0 - X2D123Y0 - X2D12Y0 - X2DeY0 + X2Y0
 DeY2X1 + X1D13Y0
 DeY2X2 + στDe - X2D132Y2 - X2D13Y2 - X2D123Y2 - X2D12Y2 - X2DeY2 + X2Y2 - D\
e
 D12Y0X1 + X1D123Y2
 D12Y0X2 + X2D132Y1
 D12Y1X1 + X1D123Y1 - D12
 D12Y1X2 + στD12 + στDe + X2D132Y0 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ\
 + 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - 1/2
 D12Y2X1 + τσD12 + τσDe + X1D123Y0 - 1/2Y2X1 + 1/2Y1X1 - 1/2Y0X1 - 1/2τσ\
 - 1/2X1Y2 + 1/2X1Y1 - 1/2X1Y0 - 1/2
 D12Y2X2 + X2D132Y2 - D12
 D123Y0X1 + τσD12 + X1D12Y2 - Y0X1 - X1Y2
 D123Y0X2 + X2D13Y1
 D123Y1X1 + X1D12Y1 - D123
 D123Y1X2 - στD12 - στDe + X2D13Y0 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ\
 - 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 D123Y2X1 + X1D12Y0
 D123Y2X2 + X2D13Y2 - D123
 D13Y0X1 + X1DeY2
 D13Y0X2 - στD12 + X2D123Y1
 D13Y1X1 - τσDe + X1DeY1 - Y1X1 - X1Y1 - D13 + 1
 D13Y1X2 + X2D123Y0
 D13Y2X1 + X1DeY0
 D13Y2X2 + X2D123Y2 - D13
 D132Y0X1 - X1D132Y2 - X1D13Y2 - X1D123Y2 - X1D12Y2 - X1DeY2 + X1Y2
 D132Y0X2 + στD12 + X2D12Y1 - Y0X2 - X2Y1
 D132Y1X1 - X1D132Y1 - X1D13Y1 - X1D123Y1 - X1D12Y1 - X1DeY1 + X1Y1 - D132
 D132Y1X2 + X2D12Y0
 D132Y2X1 - τσD12 - τσDe - X1D132Y0 - X1D13Y0 - X1D123Y0 - X1D12Y0 - X1DeY\
0 - 1/2Y2X1 - 1/2Y1X1 + 1/2Y0X1 + 1/2τσ + 1/2X1Y2 - 1/2X1Y1 + 1/2X1Y0 + 1/2
 D132Y2X2 + X2D12Y2 - D132
 Y0X1X0 - X2Y1X1 - 2X1σD132 - X1σD13 - X1σD123 - X1σD12 - X1σDe + X0X2Y1 \
+ X1σ + X2
 Y0X1X2 + X1Y2X2 - X0Y0X1 - X0X1Y2
 Y0X1σ - X1σY1 + τD123 - τD12
 Y0X1τ + X1τY0 + σD132 - σD13
 Y0X1De - X1D132Y2 - X1D13Y2 - X1D123Y2 - X1D12Y2 - X1DeY2 + X1Y2
 Y0X1D12 - τσD12 + X1D132Y2
 Y0X1D123 + X1D13Y2
 Y0X1D13 + X1D123Y2
 Y0X1D132 + τσD12 + X1D12Y2 - Y0X1 - X1Y2
 Y0X2σ - σY0X1
 Y0X2τ - τσD12 - 2τσDe + X2τY2 - 1/2Y2X1 - 3/2Y1X1 + 1/2Y0X1 + 1/2τσ +\
 1/2X1Y2 - 3/2X1Y1 - 1/2X1Y0 + 3/2
 Y0X2De + X2D13Y1
 Y0X2D12 - στD12 + X2D123Y1
 Y0X2D123 + στD12 + X2D12Y1 - Y0X2 - X2Y1
 Y0X2D13 + X2DeY1
 Y0X2D132 - X2D132Y1 - X2D13Y1 - X2D123Y1 - X2D12Y1 - X2DeY1 + X2Y1
 Y1X1X0 - X2Y0X1 + X1σD13 - X1σD123 + X0X2Y2 - X0
 Y1X1X2 + X1Y1X2 - X0Y2X1 - X0X1Y0 - X2
 Y1X1σ - X1σY2 + τD132 + τD13 + τD123 + τD12 + 2τDe - τ - σ
 Y1X1τ + X1τY2 + σD132 + σD13 + σD123 + σD12 + 2σDe - τ - σ
 Y1X1De + τσDe + X1D13Y1 - De
 Y1X1D12 + X1D123Y1 - D12
 Y1X1D123 + X1D12Y1 - D123
 Y1X1D13 - τσDe + X1DeY1 - Y1X1 - X1Y1 - D13 + 1
 Y1X1D132 - X1D132Y1 - X1D13Y1 - X1D123Y1 - X1D12Y1 - X1DeY1 + X1Y1 - D132
 Y1X1Y2 - Y0Y2X1 - Y0X1Y0 + X1Y1Y2 - Y2
 Y1X2σ - σY2X1
 Y1X2τ + 2τσD12 + τσDe + X2τY1 - 1/2Y2X1 + 1/2Y1X1 - 3/2Y0X1 - 1/2τσ -\
 3/2X1Y2 + 1/2X1Y1 - 1/2X1Y0 - 1/2
 Y1X2De + X2D12Y0
 Y1X2D12 + X2DeY0
 Y1X2D123 - X2D132Y0 - X2D13Y0 - X2D123Y0 - X2D12Y0 - X2DeY0 + X2Y0
 Y1X2D13 + στD12 + στDe + X2D132Y0 + 1/2Y2X2 - 1/2Y1X2 - 1/2Y0X2 - 1/2στ\
 + 1/2X2Y2 - 1/2X2Y1 - 1/2X2Y0 - 1/2
 Y1X2D132 - στD12 - στDe + X2D13Y0 - 1/2Y2X2 - 1/2Y1X2 + 1/2Y0X2 + 1/2στ\
 - 1/2X2Y2 + 1/2X2Y1 - 1/2X2Y0 + 1/2
 Y1X2Y1 - Y0Y2X2 - Y0X2Y2 + X2Y0Y1 + Y0
 Y1Y0Y1 - Y0Y1Y0
 Y1Y2X1 + Y1X1Y0 - Y0X1Y1 + X1Y1Y0 + X1Y0Y2
 Y1Y2X2 + Y1X2Y2 - Y0X2Y0 - X2Y1Y0 - Y1
 Y2X1X0 - X2Y2X1 + X1σD12 - X1σDe + X0X2Y0 + X1
 Y2X1X2 + X1Y0X2 - X0Y1X1 - X0X1Y1 + X0
 Y2X1σ - X1σY0 + τD132 - τD13
 Y2X1τ + X1τY1 + σD123 - σD12
 Y2X1De + X1D12Y0
 Y2X1D12 + X1DeY0
 Y2X1D123 - τσD12 - τσDe - X1D132Y0 - X1D13Y0 - X1D123Y0 - X1D12Y0 - X1DeY\
0 - 1/2Y2X1 - 1/2Y1X1 + 1/2Y0X1 + 1/2τσ + 1/2X1Y2 - 1/2X1Y1 + 1/2X1Y0 + 1/2
 Y2X1D13 + X1D132Y0
 Y2X1D132 + X1D13Y0
 Y2X1Y1 - Y1Y0X1 - Y0Y2X1 - Y0X1Y0 + X1Y1Y2 + X1Y0Y1 - Y2
 Y2X1Y2 - Y0Y1X1 - Y0X1Y1 + X1Y0Y2 + Y0
 Y2X2σ - σY1X1
 Y2X2τ - τσD12 + τσDe + X2τY0 - τ
 Y2X2De + στDe - X2D132Y2 - X2D13Y2 - X2D123Y2 - X2D12Y2 - X2DeY2 + X2Y2 - D\
e
 Y2X2D12 + X2D132Y2 - D12
 Y2X2D123 + X2D13Y2 - D123
 Y2X2D13 + X2D123Y2 - D13
 Y2X2D132 + X2D12Y2 - D132
 Y2X2Y0 - Y1Y0X2 - Y0Y2X2 - Y0X2Y2 - X2Y1Y2
 Y2X2Y1 - Y0Y1X2 - Y0X2Y0 - X2Y1Y0 - X2Y0Y2 - Y1
 σY0Y1X2 + X1σY1Y0 + τD132Y1 + τD13Y1 + τD123Y1 - τD123Y0 + τD12Y1 + τ\
D12Y0 + 2τDeY1 - τY1
 σY0Y2X2 + X1σY1Y2 + τD132Y1 - τD13Y1 - τD123Y2 + τD12Y2 - σY0
 σY1Y0X2 + X1σY0Y1 - τD132Y1 + τD132Y0 + τD13Y1 + τD13Y0 + τD123Y0 + τ\
D12Y0 + 2τDeY0 - τY0
 τσY0X1 - X1τσY2 + D132 - D12
 τσY1X1 - X1τσY1 - τσ - D13 + De
 τσY2X1 - X1τσY0 + D132 + D13 + 2D123 + D12 + De - 1
 τY0Y1X1 + στD12Y2 + 2στD12Y1 - στDeY2 + στDeY1 + X0τY1Y0 + X0τY0Y2\
 - Y2X2Y2 + 1/2Y0Y2X2 + 1/2Y0Y1X2 - 1/2Y0X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2σÏ\
Y1 - X2Y1Y2 - τY0 + Y2 - 1/2Y0
 τY0Y1X2 - X1τY1Y0 + σD132Y1 + σD13Y1 + σD123Y1 - σD123Y0 + σD12Y1 + σ\
D12Y0 + 2σDeY1 - σY1
 τY0Y2X1 + στD12Y2 + 2στD12Y0 + 2στDeY2 + στDeY0 + X0τY1Y2 + X0τY0Y\
1 + 1/2Y2X2Y2 + 1/2Y1Y0X2 - 1/2Y1X2Y2 + 1/2Y1X2Y0 + 1/2Y0Y2X2 - 1/2Y0X2Y0 - 1/\
2στY2 - 1/2στY0 - 1/2X2Y1Y2 - 1/2X2Y1Y0 - 1/2X2Y0Y2 - 1/2X2Y0Y1 - 1/2Y2 - \
1/2Y0
 τY0Y2X2 - X1τY1Y2 + σD132Y1 - σD13Y1 - σD123Y2 + σD12Y2 - τY0
 τY1Y0X1 - στD12Y2 + στD12Y1 - 2στDeY2 - στDeY1 - X0τY1Y2 - 1/2Y2X2Y\
2 + 1/2Y1X2Y2 - Y0Y1X2 + 1/2Y0X2Y2 - Y0X2Y1 - Y0X2Y0 + 1/2στY2 + 1/2X2Y1Y2 +\
 1/2X2Y0Y2 + τY2 + 1/2Y2
 τY1Y0X2 - X1τY0Y1 - σD132Y1 + σD132Y0 + σD13Y1 + σD13Y0 + σD123Y0 + σ\
D12Y0 + 2σDeY0 - σY0
 DeY0Y1X1 + X1D13Y1Y0 + X1D13Y0Y2 - DeY0
 DeY0Y1X2 + στDeY1 + X2D132Y1Y0 + X2D13Y1Y0 + X2D123Y1Y0 + X2D12Y1Y0 + X2DeY\
1Y0 - X2Y1Y0
 DeY0Y2X1 + τσDeY2 + X1D13Y1Y2 + X1D13Y0Y1
 DeY0Y2X2 + X2D132Y1Y2 + X2D13Y1Y2 + X2D123Y1Y2 + X2D12Y1Y2 + X2DeY1Y2 - X2Y1Y\
2 - DeY0
 DeY1Y0X1 - τσDeY2 - X1D13Y1Y2 + DeY2
 DeY1Y0X2 + στDeY0 + X2D132Y0Y1 + X2D13Y0Y1 + X2D123Y0Y1 + X2D12Y0Y1 + X2DeY\
0Y1 - X2Y0Y1
 D12Y0Y1X1 + τσD12Y2 + τσDeY2 + X1D123Y1Y0 + X1D123Y0Y2 + 1/2Y0Y2X1 - 1/2Y\
0Y1X1 - 1/2Y0X1Y2 - 1/2Y0X1Y1 + 1/2Y0X1Y0 - 1/2τσY2 - D12Y0 + 1/2Y0
 D12Y0Y1X2 - X2D132Y1Y0
 D12Y0Y2X1 + X1D123Y1Y2 + X1D123Y0Y1
 D12Y0Y2X2 + στD12Y1 + στDeY1 - X2D132Y1Y2 - 1/2Y0Y2X2 + 1/2Y0Y1X2 - 1/2Y0\
X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2στY1 - D12Y0 + 1/2Y0
 D12Y1Y0X1 + τσD12Y1 + τσDeY1 - X1D123Y1Y2 - 1/2Y1Y0X1 + 1/2Y1X1Y1 - 1/2Y0\
Y2X1 - 1/2Y0X1Y1 - 1/2Y0X1Y0 - 1/2τσY1 + 1/2X1Y1Y2 + 1/2X1Y1Y0 + 1/2X1Y0Y2 +\
 D12Y2 - 1/2Y2 - 1/2Y1
 D12Y1Y0X2 - στD12Y1 - στDeY1 - X2D132Y0Y1 + 1/2Y0Y2X2 - 1/2Y0Y1X2 + 1/2Y0\
X2Y2 + 1/2Y0X2Y1 - 1/2Y0X2Y0 + 1/2στY1 - 1/2Y0
 D123Y0Y1X1 - τσD12Y1 + X1D12Y1Y0 + X1D12Y0Y2 + Y0X1Y1 - X1Y1Y0 - X1Y0Y2 - D\
123Y0
 D123Y0Y1X2 - X2D13Y1Y0
 D123Y0Y2X1 - τσD12Y0 + X1D12Y1Y2 + X1D12Y0Y1 + Y0X1Y0 - X1Y1Y2 - X1Y0Y1
 D123Y0Y2X2 - στD12Y1 - στDeY1 - X2D13Y1Y2 - 1/2Y0Y2X2 - 1/2Y0Y1X2 - 1/2Y0\
X2Y2 + 1/2Y0X2Y1 - 1/2Y0X2Y0 + 1/2στY1 - D123Y0 + 1/2Y0
 D123Y1Y0X1 - X1D12Y1Y2 + D123Y2
 D123Y1Y0X2 + στD12Y1 + στDeY1 - X2D13Y0Y1 + 1/2Y0Y2X2 + 1/2Y0Y1X2 + 1/2Y0\
X2Y2 - 1/2Y0X2Y1 + 1/2Y0X2Y0 - 1/2στY1 - 1/2Y0
 D13Y0Y1X1 + X1DeY1Y0 + X1DeY0Y2 - D13Y0
 D13Y0Y1X2 + στD12Y0 - X2D123Y1Y0
 D13Y0Y2X1 - τσDeY2 + X1DeY1Y2 + X1DeY0Y1 - Y0Y2X1 - Y0X1Y0
 D13Y0Y2X2 + στD12Y2 - X2D123Y1Y2 - D13Y0
 D13Y1Y0X1 + τσDeY2 - X1DeY1Y2 + Y0Y2X1 + Y0X1Y0 + D13Y2
 D13Y1Y0X2 - X2D123Y0Y1
 D132Y0Y1X1 - τσD12Y2 - τσDeY2 - X1D132Y1Y0 - X1D132Y0Y2 - X1D13Y1Y0 - X1D\
13Y0Y2 - X1D123Y1Y0 - X1D123Y0Y2 - X1D12Y1Y0 - X1D12Y0Y2 - X1DeY1Y0 - X1DeY0Y2\
 - 1/2Y0Y2X1 - 1/2Y0Y1X1 + 1/2Y0X1Y2 - 1/2Y0X1Y1 - 1/2Y0X1Y0 + 1/2τσY2 + X1Y\
1Y0 + X1Y0Y2 - D132Y0 + 1/2Y0
 D132Y0Y1X2 - στD12Y0 - X2D12Y1Y0 + Y0X2Y0 + X2Y1Y0
 D132Y0Y2X1 - X1D132Y1Y2 - X1D132Y0Y1 - X1D13Y1Y2 - X1D13Y0Y1 - X1D123Y1Y2 - X\
1D123Y0Y1 - X1D12Y1Y2 - X1D12Y0Y1 - X1DeY1Y2 - X1DeY0Y1 + X1Y1Y2 + X1Y0Y1
 D132Y0Y2X2 - στD12Y2 - X2D12Y1Y2 + Y0X2Y2 + X2Y1Y2 - D132Y0
 D132Y1Y0X1 - τσD12Y1 - τσDeY1 + X1D132Y1Y2 + X1D13Y1Y2 + X1D123Y1Y2 + X1D\
12Y1Y2 + X1DeY1Y2 - 1/2Y1Y0X1 - 1/2Y1X1Y1 - 1/2Y0Y2X1 + 1/2Y0X1Y1 - 1/2Y0X1Y0 \
+ 1/2τσY1 - 1/2X1Y1Y2 - 1/2X1Y1Y0 - 1/2X1Y0Y2 + D132Y2 - 1/2Y2 + 1/2Y1
 D132Y1Y0X2 - X2D12Y0Y1
 Y0X1Y0X1 + X1Y1X1Y0 - X1Y0
 Y0X1Y0X2 + X1Y1X2Y2 - X1Y0Y1X2 - X1Y0X2Y0 - X1X2Y1Y0 + X0Y0X1Y1 - X0X1Y1Y0 - \
X0X1Y0Y2 + τ^2D12 + τ^2De + 1/2σY2X1 + 1/2σY1X1 - 1/2σY0X1 + 1/2X2σY2 - \
1/2X2σY1 - 1/2X2σY0 - 1/2τ^2 - X1Y1 - 1/2σ
 Y0X1Y1X1 + X1Y0X1Y0 - Y0X1
 Y0X1Y1X2 - X1Y1Y0X2 - X1Y0Y2X2 + X0Y0X1Y0 - X0X1Y1Y2 - X0X1Y0Y1 - τ^2De - σ\
Y1X1 + X2σY1 + σ
 Y0X1Y2X1 + X1Y2X1Y0 + D132 + D13 + D12 + De - 1
 Y0X1Y2X2 + X0Y0X1Y2 - Y0X1 - X1Y2
 Y0X2Y0X1 + X2Y1Y0X1 + X0Y0X2Y2 + X0X2Y1Y2 - τD132
 Y0X2Y0X2 + X2Y1Y0X2 + X2Y0Y2X2 + X2Y0X2Y2 - X2Y0
 Y0X2Y1X1 + X0Y0X2Y1 - Y0X2 - X2Y1
 Y0X2Y1X2 + X2Y1X2Y0 - D132 - D13
 Y0X2Y2X1 - X2Y1X1Y0 + X2Y0X1Y1 + X1X0Y1Y0 + X1X0Y0Y2 + X0Y0X2Y0 + 2X0X2Y1Y0 +\
 X0X2Y0Y2 + τD132 + τD13 + τD123 + τD12 + τDe - τ
 Y0X2Y2X2 + X2Y0X2Y0 - Y0X2
 Y1X1Y0X1 + X1Y1Y0X1 + X1Y0Y2X1 + X1Y0X1Y0 - Y0X1
 Y1X1Y0X2 + X1Y1Y0X2 + X0Y1Y0X1 + X0Y0Y2X1 + X0Y0X1Y0 - X0X1Y1Y2 - τ^2D12 - Y\
0X2 + X0Y2
 Y1X1Y1X1 + X1Y1X1Y1 - 2Y1X1 - 2X1Y1 - D13 - De + 1
 Y1X1Y1X2 + X0Y2X1Y0 - Y1X2
 Y1X1Y1Y0 + Y1X1Y0Y2 + Y0Y1Y0X1 - Y0X1Y1Y2 + X1Y1Y0Y2 - Y1Y0
 Y1X1Y1Y2 + Y1X1Y0Y1 + Y0Y2X1Y0 + X1Y0Y1Y0 - Y1Y2 - Y0Y1
 Y1X2Y0X1 + X0Y2X2Y2 - X0Y2
 Y1X2Y0X2 + X2Y0X2Y1 - D123 - D12
 Y1X2Y2X1 + X2Y0Y2X1 + X0Y1Y0X2 + X0Y0Y2X2 + X0Y0X2Y2 - X0X2Y0Y1 - τD123 - X0\
Y0
 Y1X2Y2X2 + X2Y0Y2X2 + X2Y0X2Y2 - Y1X2 - X2Y0
 Y1Y0X1Y1 + Y0Y1Y0X1 - Y0X1Y1Y2 + X1Y1Y0Y2 - Y1Y0
 Y1Y0X2Y0 + Y0Y1Y0X2 - Y0X2Y0Y1 - X2Y0Y1Y0
 Y1Y0Y2X1 + Y1Y0X1Y0 + Y1X1Y0Y1 + Y0Y2X1Y0 + X1Y0Y1Y0 - Y0Y1
 Y1Y0Y2X2 + Y1Y0X2Y2 - Y1X2Y0Y1 - Y1Y0
 Y2X1Y0X1 + X1Y0X1Y2 - D132 - D12
 Y2X1Y0X2 + X0Y1X1Y1 - X0Y1
 Y2X1Y0Y1 + Y1Y0X1Y2 + Y0Y1X1Y0 + Y0X1Y1Y0
 Y2X1Y0Y2 + Y1Y0X1Y0 + Y0Y2X1Y0 + Y0Y1X1Y1 + X1Y0Y1Y0 - Y1Y2 - 2Y0Y1
 Y2X2Y2X1 + X0Y1X2Y0 - Y2X1
 Y2X2Y2X2 + X2Y2X2Y2 - 2Y2X2 - 2X2Y2 + D132 + D13 + D123 + D12
 σY0Y1Y0X2 - X1σY0Y1Y0 + τD132Y1Y0 - τD13Y1Y0 + τD123Y0Y1 - τD12Y0Y1
 τσY0Y1X1 - X1τσY1Y0 - X1τσY0Y2 - τσY0 + D132Y2 - D132Y1 + D13Y2 + 2D1\
23Y2 + D12Y2 + D12Y1 + DeY2 - Y2
 τσY0Y2X1 - X1τσY1Y2 - X1τσY0Y1 - D132Y0 - D13Y2 + D12Y0 + DeY2
 τσY1Y0X1 + X1τσY1Y2 + τσY2 + D132Y1 + D13Y2 + D13Y1 + 2D123Y1 + D12Y1 -\
 DeY2 + DeY1 - Y1
 τY0Y1Y0X1 - 2στD12Y1Y2 - στD12Y1Y0 - στD12Y0Y2 - στDeY1Y2 - 2στDeY\
1Y0 - 2στDeY0Y2 - X0τY1Y0Y2 - 1/2Y1Y0X2Y2 + 1/2Y1X2Y0Y2 - Y0Y2X2Y2 + 1/2Y0Y\
1Y0X2 - 1/2Y0Y1X2Y2 - 1/2Y0Y1X2Y0 + 1/2Y0X2Y1Y2 + 1/2Y0X2Y1Y0 - 1/2Y0X2Y0Y1 + \
1/2στY1Y2 + 1/2στY1Y0 + 1/2στY0Y2 + 1/2X2Y1Y0Y2 + 1/2X2Y0Y1Y2 + τY0Y2 +\
 Y0Y2
 τY0Y1Y0X2 + X1τY0Y1Y0 + σD132Y1Y0 - σD13Y1Y0 + σD123Y0Y1 - σD12Y0Y1
 DeY0Y1Y0X1 - τσDeY1Y0 - τσDeY0Y2 - X1D13Y1Y0Y2 + DeY0Y2
 DeY0Y1Y0X2 - X2D132Y0Y1Y0 - X2D13Y0Y1Y0 - X2D123Y0Y1Y0 - X2D12Y0Y1Y0 - X2DeY0\
Y1Y0 + X2Y0Y1Y0
 D12Y0Y1Y0X1 - X1D123Y1Y0Y2 + D12Y0Y2
 D12Y0Y1Y0X2 + στD12Y1Y0 + στDeY1Y0 + X2D132Y0Y1Y0 - 1/2Y0Y1Y0X2 + 1/2Y0Y1\
X2Y0 - 1/2Y0X2Y1Y0 + 1/2Y0X2Y0Y1 - 1/2στY1Y0
 D123Y0Y1Y0X1 + τσD12Y1Y2 - X1D12Y1Y0Y2 - Y0X1Y1Y2 + X1Y1Y0Y2 + D123Y0Y2
 D123Y0Y1Y0X2 - στD12Y1Y0 - στDeY1Y0 + X2D13Y0Y1Y0 - 1/2Y0Y1Y0X2 - 1/2Y0Y1\
X2Y0 + 1/2Y0X2Y1Y0 + 1/2Y0X2Y0Y1 + 1/2στY1Y0
 D13Y0Y1Y0X1 + τσDeY1Y0 + τσDeY0Y2 - X1DeY1Y0Y2 - Y0Y1Y0X1 + Y0X1Y1Y2 + D1\
3Y0Y2 - Y0Y2
 D13Y0Y1Y0X2 - στD12Y0Y1 + X2D123Y0Y1Y0
 D132Y0Y1Y0X1 + X1D132Y1Y0Y2 + X1D13Y1Y0Y2 + X1D123Y1Y0Y2 + X1D12Y1Y0Y2 + X1De\
Y1Y0Y2 - X1Y1Y0Y2 + D132Y0Y2
 D132Y0Y1Y0X2 + στD12Y0Y1 + X2D12Y0Y1Y0 - Y0X2Y0Y1 - X2Y0Y1Y0
 Y0X1Y0Y1X1 - X1Y1Y0X1Y0 - X1Y1X1Y0Y1 - X1Y0Y2X1Y0 - X1Y0Y1X1Y1 - Y0X1Y0 + X1Y\
1Y2 + 3X1Y0Y1 + D132Y2 + D13Y2 + D12Y2 + DeY2 - Y2
 Y0X1Y0Y1X2 - X1Y1Y0X2Y2 + X1Y1X2Y0Y1 - X0Y0X1Y1Y0 - X0X1Y0Y1Y2 - τ^2D12Y0 - \
τ^2DeY0 - 1/2σY2X1Y0 - 1/2σY1X1Y0 + 1/2σY0X1Y0 + 1/2X2σY1Y2 + 1/2X2σY1Y0\
 + 1/2X2σY0Y1 + 1/2τ^2Y0 + X1Y1Y0 + 1/2σY0
 Y0X1Y0Y2X1 + X1Y0X1Y0Y2
 Y0X1Y0Y2X2 + X1Y0Y1X2Y2 - X1Y0X2Y1Y0 - X0Y0X1Y1Y2 + X0X1Y1Y0Y2 - τ^2D12Y2 - \
τ^2DeY2 - τ^2DeY1 - σY1X1Y1 - 1/2σY0Y2X1 - 1/2σY0Y1X1 + 1/2σY0X1Y2 - 1/2\
σY0X1Y1 - 1/2σY0X1Y0 - Y0X1Y0 + 1/2τ^2Y2 + X1Y1Y2 + σY1 + 1/2σY0
 Y0X1Y1Y0X1 - X1Y1Y0X1Y2 - X1Y0Y1X1Y0 - X1Y0X1Y1Y0 - X1Y0X1Y0Y2 + Y0X1Y2 + D13\
2Y1 + D13Y1 + D12Y1 + DeY1 - Y1
 Y0X1Y1Y0X2 - X1Y0Y1X2Y2 + X1Y0X2Y1Y0 - X0Y0X1Y0Y1 - X0X1Y1Y0Y2 + τ^2DeY1 + Ï\
Y1X1Y1 + X1Y0Y1 - σY1
 Y0X2Y0Y1X1 + X2Y0Y1Y0X1 + X0Y0X2Y1Y0 + X0Y0X2Y0Y2 + X0X2Y1Y0Y2 - Y0X2Y0 + τD\
132Y2 + τD132Y1 + τD13Y2 + τD123Y2 + τD12Y2 + τDeY2 - X2Y1Y0 - τY2
 Y0X2Y0Y1X2 + X2Y0X2Y0Y1
 Y0X2Y0Y2X1 - X2Y1Y0X1Y0 - X2Y1X1Y0Y1 - X2Y0Y2X1Y0 + X1X0Y0Y1Y0 + X0Y0X2Y1Y2 +\
 X0Y0X2Y0Y1 + 2X0X2Y0Y1Y0 + τD132Y0 + X2Y0Y1
 Y0X2Y0Y2X2 - X2Y1Y0X2Y2 + X2Y1X2Y0Y1 - X2Y0Y2X2Y2 - Y0X2Y0 + X2Y0Y2 - D132Y1 \
- D13Y1
 Y0X2Y1Y0X1 - X0Y0X2Y1Y2 + Y0X2Y2 + τD132Y1 + τD13Y1 + τD123Y1 + τD12Y1 + \
τDeY1 + X2Y1Y2 - τY1
 Y0X2Y1Y0X2 - X2Y1X2Y0Y1 + D132Y1 + D13Y1
 Y1X1Y0Y1X1 + X1Y0X1Y1Y2 - Y1X1Y0 - Y0Y1X1 - X1Y1Y0 - X1Y0Y2 + Y0
 Y1X1Y0Y1X2 + X1Y0Y1Y0X2 - X0Y1Y0X1Y0 - X0Y0Y2X1Y0 - X0X1Y0Y1Y0 + τ^2D12Y0 - \
τ^2DeY1 - Y0Y1X2 + X0Y1Y2 + X0Y0Y1
 Y1X1Y0Y1Y2 - Y0Y1Y0X1Y0 - Y0X1Y0Y1Y0 + X1Y0Y1Y0Y2
 Y1X1Y0Y2X1 - X1Y1Y0X1Y0 - X1Y1X1Y0Y1 - 2X1Y0Y2X1Y0 - Y0Y2X1 + X1Y0Y1 - D13Y2 \
- DeY2
 Y1X1Y0Y2X2 - X1Y1Y0X2Y2 + X1Y1X2Y0Y1 - X0Y1Y0X1Y2 + τ^2D12Y2 - Y1X1Y0 - Y0Y2\
X2 + Y0
 Y1X2Y0Y1X1 + X0Y1Y0X2Y2 + X0Y0Y2X2Y2 + X0Y0Y1X2Y0 - X0X2Y0Y1Y2 - Y1X2Y0 - τD\
123Y2 - X0Y0Y2
 Y1X2Y0Y1X2 - X2Y0X2Y1Y0 + D123Y0 + D12Y0
 Y1X2Y0Y1Y0 - Y0Y1Y0X2Y1
 Y1X2Y0Y2X1 + X0Y1Y0X2Y1 + X0Y0Y1X2Y2 + X0Y0X2Y0Y2 - τD13Y2
 Y1X2Y0Y2X2 - X2Y0X2Y1Y2 - Y1X2Y0 + D123Y2 + D12Y2
 Y1Y0X1Y0Y2 - Y0Y1Y0X1Y0 - Y0Y1X1Y0Y1 - 2Y0X1Y0Y1Y0 + X1Y0Y1Y0Y2
 Y1Y0X2Y1Y0 - Y0Y1X2Y0Y1
 τσY0Y1Y0X1 + X1τσY1Y0Y2 + τσY0Y2 + D132Y1Y2 + D13Y1Y0 + D13Y0Y2 - D12Y1\
Y2 - DeY1Y0 - DeY0Y2
 Y0X1Y0Y1Y0X1 + X1Y0Y1Y0X1Y0 + Y0X1Y0Y2 - X1Y0Y1Y2
 Y0X1Y0Y1Y0X2 + X1Y0Y1Y0X2Y2 - X1Y0Y1X2Y0Y1 + X0Y0X1Y0Y1Y0 - X0X1Y0Y1Y0Y2 + τ\
^2D12Y0Y1 - τ^2DeY1Y0 + τ^2DeY0Y1 - 1/2σY1Y0X1Y2 + σY1X1Y0Y2 + 1/2σY1X1Y0\
Y1 + σY0Y1Y0X1 - 1/2σY0Y1X1Y0 - σY0X1Y1Y2 - 1/2σY0X1Y1Y0 - 1/2σY0X1Y0Y1 -\
 1/2X2σY1Y0Y2 - 1/2X2σY0Y1Y0 - 1/2τ^2Y0Y1 - X1Y0Y1Y0 - 1/2σY0Y1
 Y0X2Y0Y1Y0X1 - X0Y0X2Y1Y0Y2 + Y0X2Y0Y2 - τD132Y1Y2 + X2Y1Y0Y2
 Y0X2Y0Y1Y0X2 + X2Y0Y1Y0X2Y1 - D132Y1Y0 - D13Y1Y0
 Y1X1Y0Y1Y0X1 + X1Y0Y1Y0X1Y2 + Y1X1Y0Y2 - Y0Y1Y0X1 + X1Y1Y0Y2 + D13Y1Y0 + D13Y\
0Y2 + DeY1Y0 + DeY0Y2 - Y0Y2
 Y1X1Y0Y1Y0X2 + X0Y1Y0X1Y0Y1 - X0Y0Y1Y0X1Y2 - τ^2D12Y0Y1 - Y0Y1Y0X2 + X0Y1Y0Y\
2
 Y1X1Y0Y1Y0Y2 + Y0Y1Y0X1Y0Y1
 Y1Y0X1Y0Y1Y0 + Y0Y1Y0X1Y0Y1
 Y1Y0X1Y0Y1Y2 + Y0Y1X1Y0Y1Y0

In [1490]:
Length( BaseQA(J, 14, 0) );

5184

In [1491]:
DimQA(J, 14);

5184

In [1492]:
12*6*6*12;

5184

In [1493]:
DimQA(J, 14)=12*6*6*12;

true

In [1494]:
PrintNPList( BaseQA(J, 14, 0) );

 1
 X0
 X1
 X2
 σ
 τ
 De
 D12
 D123
 D13
 D132
 Y0
 Y1
 Y2
 X0X1
 X0X2
 X0σ
 X0τ
 X0De
 X0D12
 X0D123
 X0D13
 X0D132
 X0Y0
 X0Y1
 X0Y2
 X1X0
 X1X2
 X1σ
 X1τ
 X1De
 X1D12
 X1D123
 X1D13
 X1D132
 X1Y0
 X1Y1
 X1Y2
 X2σ
 X2τ
 X2De
 X2D12
 X2D123
 X2D13
 X2D132
 X2Y0
 X2Y1
 X2Y2
 στ
 σDe
 σD12
 σD123
 σD13
 σD132
 σY0
 σY1
 σY2
 τσ
 τ^2
 τDe
 τD12
 τD123
 τD13
 τD132
 τY0
 τY1
 τY2
 DeY0
 DeY1
 DeY2
 D12Y0
 D12Y1
 D12Y2
 D123Y0
 D123Y1
 D123Y2
 D13Y0
 D13Y1
 D13Y2
 D132Y0
 D132Y1
 D132Y2
 Y0X1
 Y0X2
 Y0Y1
 Y0Y2
 Y1X1
 Y1X2
 Y1Y0
 Y1Y2
 Y2X1
 Y2X2
 X0X1X0
 X0X1X2
 X0X1σ
 X0X1τ
 X0X1De
 X0X1D12
 X0X1D123
 X0X1D13
 X0X1D132
 X0X1Y0
 X0X1Y1
 X0X1Y2
 X0X2σ
 X0X2τ
 X0X2De
 X0X2D12
 X0X2D123
 X0X2D13
 X0X2D132
 X0X2Y0
 X0X2Y1
 X0X2Y2
 X0στ
 X0σDe
 X0σD12
 X0σD123
 X0σD13
 X0σD132
 X0σY0
 X0σY1
 X0σY2
 X0τσ
 X0τ^2
 X0τDe
 X0τD12
 X0τD123
 X0τD13
 X0τD132
 X0τY0
 X0τY1
 X0τY2
 X0DeY0
 X0DeY1
 X0DeY2
 X0D12Y0
 X0D12Y1
 X0D12Y2
 X0D123Y0
 X0D123Y1
 X0D123Y2
 X0D13Y0
 X0D13Y1
 X0D13Y2
 X0D132Y0
 X0D132Y1
 X0D132Y2
 X0Y0X1
 X0Y0X2
 X0Y0Y1
 X0Y0Y2
 X0Y1X1
 X0Y1X2
 X0Y1Y0
 X0Y1Y2
 X0Y2X1
 X0Y2X2
 X1X0X2
 X1X0σ
 X1X0τ
 X1X0De
 X1X0D12
 X1X0D123
 X1X0D13
 X1X0D132
 X1X0Y0
 X1X0Y1
 X1X0Y2
 X1X2σ
 X1X2τ
 X1X2De
 X1X2D12
 X1X2D123
 X1X2D13
 X1X2D132
 X1X2Y0
 X1X2Y1
 X1X2Y2
 X1στ
 X1σDe
 X1σD12
 X1σD123
 X1σD13
 X1σD132
 X1σY0
 X1σY1
 X1σY2
 X1τσ
 X1τ^2
 X1τDe
 X1τD12
 X1τD123
 X1τD13
 X1τD132
 X1τY0
 X1τY1
 X1τY2
 X1DeY0
 X1DeY1
 X1DeY2
 X1D12Y0
 X1D12Y1
 X1D12Y2
 X1D123Y0
 X1D123Y1
 X1D123Y2
 X1D13Y0
 X1D13Y1
 X1D13Y2
 X1D132Y0
 X1D132Y1
 X1D132Y2
 X1Y0X1
 X1Y0X2
 X1Y0Y1
 X1Y0Y2
 X1Y1X1
 X1Y1X2
 X1Y1Y0
 X1Y1Y2
 X1Y2X1
 X1Y2X2
 X2στ
 X2σDe
 X2σD12
 X2σD123
 X2σD13
 X2σD132
 X2σY0
 X2σY1
 X2σY2
 X2τσ
 X2τ^2
 X2τDe
 X2τD12
 X2τD123
 X2τD13
 X2τD132
 X2τY0
 X2τY1
 X2τY2
 X2DeY0
 X2DeY1
 X2DeY2
 X2D12Y0
 X2D12Y1
 X2D12Y2
 X2D123Y0
 X2D123Y1
 X2D123Y2
 X2D13Y0
 X2D13Y1
 X2D13Y2
 X2D132Y0
 X2D132Y1
 X2D132Y2
 X2Y0X1
 X2Y0X2
 X2Y0Y1
 X2Y0Y2
 X2Y1X1
 X2Y1X2
 X2Y1Y0
 X2Y1Y2
 X2Y2X1
 X2Y2X2
 στDe
 στD12
 στY0
 στY1
 στY2
 σDeY0
 σDeY1
 σDeY2
 σD12Y0
 σD12Y1
 σD12Y2
 σD123Y0
 σD123Y1
 σD123Y2
 σD13Y0
 σD13Y1
 σD13Y2
 σD132Y0
 σD132Y1
 σD132Y2
 σY0X1
 σY0Y1
 σY0Y2
 σY1X1
 σY1Y0
 σY1Y2
 σY2X1
 τσDe
 τσD12
 τσY0
 τσY1
 τσY2
 τ^2De
 τ^2D12
 τ^2Y0
 τ^2Y1
 τ^2Y2
 τDeY0
 τDeY1
 τDeY2
 τD12Y0
 τD12Y1
 τD12Y2
 τD123Y0
 τD123Y1
 τD123Y2
 τD13Y0
 τD13Y1
 τD13Y2
 τD132Y0
 τD132Y1
 τD132Y2
 τY0Y1
 τY0Y2
 τY1Y0
 τY1Y2
 DeY0Y1
 DeY0Y2
 DeY1Y0
 DeY1Y2
 D12Y0Y1
 D12Y0Y2
 D12Y1Y0
 D12Y1Y2
 D123Y0Y1
 D123Y0Y2
 D123Y1Y0
 D123Y1Y2
 D13Y0Y1
 D13Y0Y2
 D13Y1Y0
 D13Y1Y2
 D132Y0Y1
 D132Y0Y2
 D132Y1Y0
 D132Y1Y2
 Y0X1Y0
 Y0X1Y1
 Y0X1Y2
 Y0X2Y0
 Y0X2Y1
 Y0X2Y2
 Y0Y1X1
 Y0Y1X2
 Y0Y1Y0
 Y0Y1Y2
 Y0Y2X1
 Y0Y2X2
 Y1X1Y0
 Y1X1Y1
 Y1X2Y0
 Y1X2Y2
 Y1Y0X1
 Y1Y0X2
 Y1Y0Y2
 Y2X1Y0
 Y2X2Y2
 X0X1X0X2
 X0X1X0σ
 X0X1X0τ
 X0X1X0De
 X0X1X0D12
 X0X1X0D123
 X0X1X0D13
 X0X1X0D132
 X0X1X0Y0
 X0X1X0Y1
 X0X1X0Y2
 X0X1X2σ
 X0X1X2τ
 X0X1X2De
 X0X1X2D12
 X0X1X2D123
 X0X1X2D13
 X0X1X2D132
 X0X1X2Y0
 X0X1X2Y1
 X0X1X2Y2
 X0X1στ
 X0X1σDe
 X0X1σD12
 X0X1σD123
 X0X1σD13
 X0X1σD132
 X0X1σY0
 X0X1σY1
 X0X1σY2
 X0X1τσ
 X0X1τ^2
 X0X1τDe
 X0X1τD12
 X0X1τD123
 X0X1τD13
 X0X1τD132
 X0X1τY0
 X0X1τY1
 X0X1τY2
 X0X1DeY0
 X0X1DeY1
 X0X1DeY2
 X0X1D12Y0
 X0X1D12Y1
 X0X1D12Y2
 X0X1D123Y0
 X0X1D123Y1
 X0X1D123Y2
 X0X1D13Y0
 X0X1D13Y1
 X0X1D13Y2
 X0X1D132Y0
 X0X1D132Y1
 X0X1D132Y2
 X0X1Y0X1
 X0X1Y0X2
 X0X1Y0Y1
 X0X1Y0Y2
 X0X1Y1X1
 X0X1Y1X2
 X0X1Y1Y0
 X0X1Y1Y2
 X0X1Y2X1
 X0X1Y2X2
 X0X2στ
 X0X2σDe
 X0X2σD12
 X0X2σD123
 X0X2σD13
 X0X2σD132
 X0X2σY0
 X0X2σY1
 X0X2σY2
 X0X2τσ
 X0X2τ^2
 X0X2τDe
 X0X2τD12
 X0X2τD123
 X0X2τD13
 X0X2τD132
 X0X2τY0
 X0X2τY1
 X0X2τY2
 X0X2DeY0
 X0X2DeY1
 X0X2DeY2
 X0X2D12Y0
 X0X2D12Y1
 X0X2D12Y2
 X0X2D123Y0
 X0X2D123Y1
 X0X2D123Y2
 X0X2D13Y0
 X0X2D13Y1
 X0X2D13Y2
 X0X2D132Y0
 X0X2D132Y1
 X0X2D132Y2
 X0X2Y0X1
 X0X2Y0X2
 X0X2Y0Y1
 X0X2Y0Y2
 X0X2Y1X1
 X0X2Y1X2
 X0X2Y1Y0
 X0X2Y1Y2
 X0X2Y2X1
 X0X2Y2X2
 X0στDe
 X0στD12
 X0στY0
 X0στY1
 X0στY2
 X0σDeY0
 X0σDeY1
 X0σDeY2
 X0σD12Y0
 X0σD12Y1
 X0σD12Y2
 X0σD123Y0
 X0σD123Y1
 X0σD123Y2
 X0σD13Y0
 X0σD13Y1
 X0σD13Y2
 X0σD132Y0
 X0σD132Y1
 X0σD132Y2
 X0σY0X1
 X0σY0Y1
 X0σY0Y2
 X0σY1X1
 X0σY1Y0
 X0σY1Y2
 X0σY2X1
 X0τσDe
 X0τσD12
 X0τσY0
 X0τσY1
 X0τσY2
 X0τ^2De
 X0τ^2D12
 X0τ^2Y0
 X0τ^2Y1
 X0τ^2Y2
 X0τDeY0
 X0τDeY1
 X0τDeY2
 X0τD12Y0
 X0τD12Y1
 X0τD12Y2
 X0τD123Y0
 X0τD123Y1
 X0τD123Y2
 X0τD13Y0
 X0τD13Y1
 X0τD13Y2
 X0τD132Y0
 X0τD132Y1
 X0τD132Y2
 X0τY0Y1
 X0τY0Y2
 X0τY1Y0
 X0τY1Y2
 X0DeY0Y1
 X0DeY0Y2
 X0DeY1Y0
 X0DeY1Y2
 X0D12Y0Y1
 X0D12Y0Y2
 X0D12Y1Y0
 X0D12Y1Y2
 X0D123Y0Y1
 X0D123Y0Y2
 X0D123Y1Y0
 X0D123Y1Y2
 X0D13Y0Y1
 X0D13Y0Y2
 X0D13Y1Y0
 X0D13Y1Y2
 X0D132Y0Y1
 X0D132Y0Y2
 X0D132Y1Y0
 X0D132Y1Y2
 X0Y0X1Y0
 X0Y0X1Y1
 X0Y0X1Y2
 X0Y0X2Y0
 X0Y0X2Y1
 X0Y0X2Y2
 X0Y0Y1X1
 X0Y0Y1X2
 X0Y0Y1Y0
 X0Y0Y1Y2
 X0Y0Y2X1
 X0Y0Y2X2
 X0Y1X1Y0
 X0Y1X1Y1
 X0Y1X2Y0
 X0Y1X2Y2
 X0Y1Y0X1
 X0Y1Y0X2
 X0Y1Y0Y2
 X0Y2X1Y0
 X0Y2X2Y2
 X1X0X2σ
 X1X0X2τ
 X1X0X2De
 X1X0X2D12
 X1X0X2D123
 X1X0X2D13
 X1X0X2D132
 X1X0X2Y0
 X1X0X2Y1
 X1X0X2Y2
 X1X0στ
 X1X0σDe
 X1X0σD12
 X1X0σD123
 X1X0σD13
 X1X0σD132
 X1X0σY0
 X1X0σY1
 X1X0σY2
 X1X0τσ
 X1X0τ^2
 X1X0τDe
 X1X0τD12
 X1X0τD123
 X1X0τD13
 X1X0τD132
 X1X0τY0
 X1X0τY1
 X1X0τY2
 X1X0DeY0
 X1X0DeY1
 X1X0DeY2
 X1X0D12Y0
 X1X0D12Y1
 X1X0D12Y2
 X1X0D123Y0
 X1X0D123Y1
 X1X0D123Y2
 X1X0D13Y0
 X1X0D13Y1
 X1X0D13Y2
 X1X0D132Y0
 X1X0D132Y1
 X1X0D132Y2
 X1X0Y0X1
 X1X0Y0X2
 X1X0Y0Y1
 X1X0Y0Y2
 X1X0Y1X1
 X1X0Y1X2
 X1X0Y1Y0
 X1X0Y1Y2
 X1X0Y2X1
 X1X0Y2X2
 X1X2στ
 X1X2σDe
 X1X2σD12
 X1X2σD123
 X1X2σD13
 X1X2σD132
 X1X2σY0
 X1X2σY1
 X1X2σY2
 X1X2τσ
 X1X2τ^2
 X1X2τDe
 X1X2τD12
 X1X2τD123
 X1X2τD13
 X1X2τD132
 X1X2τY0
 X1X2τY1
 X1X2τY2
 X1X2DeY0
 X1X2DeY1
 X1X2DeY2
 X1X2D12Y0
 X1X2D12Y1
 X1X2D12Y2
 X1X2D123Y0
 X1X2D123Y1
 X1X2D123Y2
 X1X2D13Y0
 X1X2D13Y1
 X1X2D13Y2
 X1X2D132Y0
 X1X2D132Y1
 X1X2D132Y2
 X1X2Y0X1
 X1X2Y0X2
 X1X2Y0Y1
 X1X2Y0Y2
 X1X2Y1X1
 X1X2Y1X2
 X1X2Y1Y0
 X1X2Y1Y2
 X1X2Y2X1
 X1X2Y2X2
 X1στDe
 X1στD12
 X1στY0
 X1στY1
 X1στY2
 X1σDeY0
 X1σDeY1
 X1σDeY2
 X1σD12Y0
 X1σD12Y1
 X1σD12Y2
 X1σD123Y0
 X1σD123Y1
 X1σD123Y2
 X1σD13Y0
 X1σD13Y1
 X1σD13Y2
 X1σD132Y0
 X1σD132Y1
 X1σD132Y2
 X1σY0X1
 X1σY0Y1
 X1σY0Y2
 X1σY1X1
 X1σY1Y0
 X1σY1Y2
 X1σY2X1
 X1τσDe
 X1τσD12
 X1τσY0
 X1τσY1
 X1τσY2
 X1τ^2De
 X1τ^2D12
 X1τ^2Y0
 X1τ^2Y1
 X1τ^2Y2
 X1τDeY0
 X1τDeY1
 X1τDeY2
 X1τD12Y0
 X1τD12Y1
 X1τD12Y2
 X1τD123Y0
 X1τD123Y1
 X1τD123Y2
 X1τD13Y0
 X1τD13Y1
 X1τD13Y2
 X1τD132Y0
 X1τD132Y1
 X1τD132Y2
 X1τY0Y1
 X1τY0Y2
 X1τY1Y0
 X1τY1Y2
 X1DeY0Y1
 X1DeY0Y2
 X1DeY1Y0
 X1DeY1Y2
 X1D12Y0Y1
 X1D12Y0Y2
 X1D12Y1Y0
 X1D12Y1Y2
 X1D123Y0Y1
 X1D123Y0Y2
 X1D123Y1Y0
 X1D123Y1Y2
 X1D13Y0Y1
 X1D13Y0Y2
 X1D13Y1Y0
 X1D13Y1Y2
 X1D132Y0Y1
 X1D132Y0Y2
 X1D132Y1Y0
 X1D132Y1Y2
 X1Y0X1Y0
 X1Y0X1Y1
 X1Y0X1Y2
 X1Y0X2Y0
 X1Y0X2Y1
 X1Y0X2Y2
 X1Y0Y1X1
 X1Y0Y1X2
 X1Y0Y1Y0
 X1Y0Y1Y2
 X1Y0Y2X1
 X1Y0Y2X2
 X1Y1X1Y0
 X1Y1X1Y1
 X1Y1X2Y0
 X1Y1X2Y2
 X1Y1Y0X1
 X1Y1Y0X2
 X1Y1Y0Y2
 X1Y2X1Y0
 X1Y2X2Y2
 X2στDe
 X2στD12
 X2στY0
 X2στY1
 X2στY2
 X2σDeY0
 X2σDeY1
 X2σDeY2
 X2σD12Y0
 X2σD12Y1
 X2σD12Y2
 X2σD123Y0
 X2σD123Y1
 X2σD123Y2
 X2σD13Y0
 X2σD13Y1
 X2σD13Y2
 X2σD132Y0
 X2σD132Y1
 X2σD132Y2
 X2σY0X1
 X2σY0Y1
 X2σY0Y2
 X2σY1X1
 X2σY1Y0
 X2σY1Y2
 X2σY2X1
 X2τσDe
 X2τσD12
 X2τσY0
 X2τσY1
 X2τσY2
 X2τ^2De
 X2τ^2D12
 X2τ^2Y0
 X2τ^2Y1
 X2τ^2Y2
 X2τDeY0
 X2τDeY1
 X2τDeY2
 X2τD12Y0
 X2τD12Y1
 X2τD12Y2
 X2τD123Y0
 X2τD123Y1
 X2τD123Y2
 X2τD13Y0
 X2τD13Y1
 X2τD13Y2
 X2τD132Y0
 X2τD132Y1
 X2τD132Y2
 X2τY0Y1
 X2τY0Y2
 X2τY1Y0
 X2τY1Y2
 X2DeY0Y1
 X2DeY0Y2
 X2DeY1Y0
 X2DeY1Y2
 X2D12Y0Y1
 X2D12Y0Y2
 X2D12Y1Y0
 X2D12Y1Y2
 X2D123Y0Y1
 X2D123Y0Y2
 X2D123Y1Y0
 X2D123Y1Y2
 X2D13Y0Y1
 X2D13Y0Y2
 X2D13Y1Y0
 X2D13Y1Y2
 X2D132Y0Y1
 X2D132Y0Y2
 X2D132Y1Y0
 X2D132Y1Y2
 X2Y0X1Y0
 X2Y0X1Y1
 X2Y0X1Y2
 X2Y0X2Y0
 X2Y0X2Y1
 X2Y0X2Y2
 X2Y0Y1X1
 X2Y0Y1X2
 X2Y0Y1Y0
 X2Y0Y1Y2
 X2Y0Y2X1
 X2Y0Y2X2
 X2Y1X1Y0
 X2Y1X1Y1
 X2Y1X2Y0
 X2Y1X2Y2
 X2Y1Y0X1
 X2Y1Y0X2
 X2Y1Y0Y2
 X2Y2X1Y0
 X2Y2X2Y2
 στDeY0
 στDeY1
 στDeY2
 στD12Y0
 στD12Y1
 στD12Y2
 στY0Y1
 στY0Y2
 στY1Y0
 στY1Y2
 σDeY0Y1
 σDeY0Y2
 σDeY1Y0
 σDeY1Y2
 σD12Y0Y1
 σD12Y0Y2
 σD12Y1Y0
 σD12Y1Y2
 σD123Y0Y1
 σD123Y0Y2
 σD123Y1Y0
 σD123Y1Y2
 σD13Y0Y1
 σD13Y0Y2
 σD13Y1Y0
 σD13Y1Y2
 σD132Y0Y1
 σD132Y0Y2
 σD132Y1Y0
 σD132Y1Y2
 σY0X1Y0
 σY0X1Y1
 σY0X1Y2
 σY0Y1X1
 σY0Y1Y0
 σY0Y1Y2
 σY0Y2X1
 σY1X1Y0
 σY1X1Y1
 σY1Y0X1
 σY1Y0Y2
 σY2X1Y0
 τσDeY0
 τσDeY1
 τσDeY2
 τσD12Y0
 τσD12Y1
 τσD12Y2
 τσY0Y1
 τσY0Y2
 τσY1Y0
 τσY1Y2
 τ^2DeY0
 τ^2DeY1
 τ^2DeY2
 τ^2D12Y0
 τ^2D12Y1
 τ^2D12Y2
 τ^2Y0Y1
 τ^2Y0Y2
 τ^2Y1Y0
 τ^2Y1Y2
 τDeY0Y1
 τDeY0Y2
 τDeY1Y0
 τDeY1Y2
 τD12Y0Y1
 τD12Y0Y2
 τD12Y1Y0
 τD12Y1Y2
 τD123Y0Y1
 τD123Y0Y2
 τD123Y1Y0
 τD123Y1Y2
 τD13Y0Y1
 τD13Y0Y2
 τD13Y1Y0
 τD13Y1Y2
 τD132Y0Y1
 τD132Y0Y2
 τD132Y1Y0
 τD132Y1Y2
 τY0Y1Y0
 τY0Y1Y2
 τY1Y0Y2
 DeY0Y1Y0
 DeY0Y1Y2
 DeY1Y0Y2
 D12Y0Y1Y0
 D12Y0Y1Y2
 D12Y1Y0Y2
 D123Y0Y1Y0
 D123Y0Y1Y2
 D123Y1Y0Y2
 D13Y0Y1Y0
 D13Y0Y1Y2
 D13Y1Y0Y2
 D132Y0Y1Y0
 D132Y0Y1Y2
 D132Y1Y0Y2
 Y0X1Y0Y1
 Y0X1Y0Y2
 Y0X1Y1Y0
 Y0X1Y1Y2
 Y0X2Y0Y1
 Y0X2Y0Y2
 Y0X2Y1Y0
 Y0X2Y1Y2
 Y0Y1X1Y0
 Y0Y1X1Y1
 Y0Y1X2Y0
 Y0Y1X2Y2
 Y0Y1Y0X1
 Y0Y1Y0X2
 Y0Y1Y0Y2
 Y0Y2X1Y0
 Y0Y2X2Y2
 Y1X1Y0Y1
 Y1X1Y0Y2
 Y1X2Y0Y1
 Y1X2Y0Y2
 Y1Y0X1Y0
 Y1Y0X1Y2
 Y1Y0X2Y1
 Y1Y0X2Y2
 X0X1X0X2σ
 X0X1X0X2τ
 X0X1X0X2De
 X0X1X0X2D12
 X0X1X0X2D123
 X0X1X0X2D13
 X0X1X0X2D132
 X0X1X0X2Y0
 X0X1X0X2Y1
 X0X1X0X2Y2
 X0X1X0στ
 X0X1X0σDe
 X0X1X0σD12
 X0X1X0σD123
 X0X1X0σD13
 X0X1X0σD132
 X0X1X0σY0
 X0X1X0σY1
 X0X1X0σY2
 X0X1X0τσ
 X0X1X0τ^2
 X0X1X0τDe
 X0X1X0τD12
 X0X1X0τD123
 X0X1X0τD13
 X0X1X0τD132
 X0X1X0τY0
 X0X1X0τY1
 X0X1X0τY2
 X0X1X0DeY0
 X0X1X0DeY1
 X0X1X0DeY2
 X0X1X0D12Y0
 X0X1X0D12Y1
 X0X1X0D12Y2
 X0X1X0D123Y0
 X0X1X0D123Y1
 X0X1X0D123Y2
 X0X1X0D13Y0
 X0X1X0D13Y1
 X0X1X0D13Y2
 X0X1X0D132Y0
 X0X1X0D132Y1
 X0X1X0D132Y2
 X0X1X0Y0X1
 X0X1X0Y0X2
 X0X1X0Y0Y1
 X0X1X0Y0Y2
 X0X1X0Y1X1
 X0X1X0Y1X2
 X0X1X0Y1Y0
 X0X1X0Y1Y2
 X0X1X0Y2X1
 X0X1X0Y2X2
 X0X1X2στ
 X0X1X2σDe
 X0X1X2σD12
 X0X1X2σD123
 X0X1X2σD13
 X0X1X2σD132
 X0X1X2σY0
 X0X1X2σY1
 X0X1X2σY2
 X0X1X2τσ
 X0X1X2τ^2
 X0X1X2τDe
 X0X1X2τD12
 X0X1X2τD123
 X0X1X2τD13
 X0X1X2τD132
 X0X1X2τY0
 X0X1X2τY1
 X0X1X2τY2
 X0X1X2DeY0
 X0X1X2DeY1
 X0X1X2DeY2
 X0X1X2D12Y0
 X0X1X2D12Y1
 X0X1X2D12Y2
 X0X1X2D123Y0
 X0X1X2D123Y1
 X0X1X2D123Y2
 X0X1X2D13Y0
 X0X1X2D13Y1
 X0X1X2D13Y2
 X0X1X2D132Y0
 X0X1X2D132Y1
 X0X1X2D132Y2
 X0X1X2Y0X1
 X0X1X2Y0X2
 X0X1X2Y0Y1
 X0X1X2Y0Y2
 X0X1X2Y1X1
 X0X1X2Y1X2
 X0X1X2Y1Y0
 X0X1X2Y1Y2
 X0X1X2Y2X1
 X0X1X2Y2X2
 X0X1στDe
 X0X1στD12
 X0X1στY0
 X0X1στY1
 X0X1στY2
 X0X1σDeY0
 X0X1σDeY1
 X0X1σDeY2
 X0X1σD12Y0
 X0X1σD12Y1
 X0X1σD12Y2
 X0X1σD123Y0
 X0X1σD123Y1
 X0X1σD123Y2
 X0X1σD13Y0
 X0X1σD13Y1
 X0X1σD13Y2
 X0X1σD132Y0
 X0X1σD132Y1
 X0X1σD132Y2
 X0X1σY0X1
 X0X1σY0Y1
 X0X1σY0Y2
 X0X1σY1X1
 X0X1σY1Y0
 X0X1σY1Y2
 X0X1σY2X1
 X0X1τσDe
 X0X1τσD12
 X0X1τσY0
 X0X1τσY1
 X0X1τσY2
 X0X1τ^2De
 X0X1τ^2D12
 X0X1τ^2Y0
 X0X1τ^2Y1
 X0X1τ^2Y2
 X0X1τDeY0
 X0X1τDeY1
 X0X1τDeY2
 X0X1τD12Y0
 X0X1τD12Y1
 X0X1τD12Y2
 X0X1τD123Y0
 X0X1τD123Y1
 X0X1τD123Y2
 X0X1τD13Y0
 X0X1τD13Y1
 X0X1τD13Y2
 X0X1τD132Y0
 X0X1τD132Y1
 X0X1τD132Y2
 X0X1τY0Y1
 X0X1τY0Y2
 X0X1τY1Y0
 X0X1τY1Y2
 X0X1DeY0Y1
 X0X1DeY0Y2
 X0X1DeY1Y0
 X0X1DeY1Y2
 X0X1D12Y0Y1
 X0X1D12Y0Y2
 X0X1D12Y1Y0
 X0X1D12Y1Y2
 X0X1D123Y0Y1
 X0X1D123Y0Y2
 X0X1D123Y1Y0
 X0X1D123Y1Y2
 X0X1D13Y0Y1
 X0X1D13Y0Y2
 X0X1D13Y1Y0
 X0X1D13Y1Y2
 X0X1D132Y0Y1
 X0X1D132Y0Y2
 X0X1D132Y1Y0
 X0X1D132Y1Y2
 X0X1Y0X1Y0
 X0X1Y0X1Y1
 X0X1Y0X1Y2
 X0X1Y0X2Y0
 X0X1Y0X2Y1
 X0X1Y0X2Y2
 X0X1Y0Y1X1
 X0X1Y0Y1X2
 X0X1Y0Y1Y0
 X0X1Y0Y1Y2
 X0X1Y0Y2X1
 X0X1Y0Y2X2
 X0X1Y1X1Y0
 X0X1Y1X1Y1
 X0X1Y1X2Y0
 X0X1Y1X2Y2
 X0X1Y1Y0X1
 X0X1Y1Y0X2
 X0X1Y1Y0Y2
 X0X1Y2X1Y0
 X0X1Y2X2Y2
 X0X2στDe
 X0X2στD12
 X0X2στY0
 X0X2στY1
 X0X2στY2
 X0X2σDeY0
 X0X2σDeY1
 X0X2σDeY2
 X0X2σD12Y0
 X0X2σD12Y1
 X0X2σD12Y2
 X0X2σD123Y0
 X0X2σD123Y1
 X0X2σD123Y2
 X0X2σD13Y0
 X0X2σD13Y1
 X0X2σD13Y2
 X0X2σD132Y0
 X0X2σD132Y1
 X0X2σD132Y2
 X0X2σY0X1
 X0X2σY0Y1
 X0X2σY0Y2
 X0X2σY1X1
 X0X2σY1Y0
 X0X2σY1Y2
 X0X2σY2X1
 X0X2τσDe
 X0X2τσD12
 X0X2τσY0
 X0X2τσY1
 X0X2τσY2
 X0X2τ^2De
 X0X2τ^2D12
 X0X2τ^2Y0
 X0X2τ^2Y1
 X0X2τ^2Y2
 X0X2τDeY0
 X0X2τDeY1
 X0X2τDeY2
 X0X2τD12Y0
 X0X2τD12Y1
 X0X2τD12Y2
 X0X2τD123Y0
 X0X2τD123Y1
 X0X2τD123Y2
 X0X2τD13Y0
 X0X2τD13Y1
 X0X2τD13Y2
 X0X2τD132Y0
 X0X2τD132Y1
 X0X2τD132Y2
 X0X2τY0Y1
 X0X2τY0Y2
 X0X2τY1Y0
 X0X2τY1Y2
 X0X2DeY0Y1
 X0X2DeY0Y2
 X0X2DeY1Y0
 X0X2DeY1Y2
 X0X2D12Y0Y1
 X0X2D12Y0Y2
 X0X2D12Y1Y0
 X0X2D12Y1Y2
 X0X2D123Y0Y1
 X0X2D123Y0Y2
 X0X2D123Y1Y0
 X0X2D123Y1Y2
 X0X2D13Y0Y1
 X0X2D13Y0Y2
 X0X2D13Y1Y0
 X0X2D13Y1Y2
 X0X2D132Y0Y1
 X0X2D132Y0Y2
 X0X2D132Y1Y0
 X0X2D132Y1Y2
 X0X2Y0X1Y0
 X0X2Y0X1Y1
 X0X2Y0X1Y2
 X0X2Y0X2Y0
 X0X2Y0X2Y1
 X0X2Y0X2Y2
 X0X2Y0Y1X1
 X0X2Y0Y1X2
 X0X2Y0Y1Y0
 X0X2Y0Y1Y2
 X0X2Y0Y2X1
 X0X2Y0Y2X2
 X0X2Y1X1Y0
 X0X2Y1X1Y1
 X0X2Y1X2Y0
 X0X2Y1X2Y2
 X0X2Y1Y0X1
 X0X2Y1Y0X2
 X0X2Y1Y0Y2
 X0X2Y2X1Y0
 X0X2Y2X2Y2
 X0στDeY0
 X0στDeY1
 X0στDeY2
 X0στD12Y0
 X0στD12Y1
 X0στD12Y2
 X0στY0Y1
 X0στY0Y2
 X0στY1Y0
 X0στY1Y2
 X0σDeY0Y1
 X0σDeY0Y2
 X0σDeY1Y0
 X0σDeY1Y2
 X0σD12Y0Y1
 X0σD12Y0Y2
 X0σD12Y1Y0
 X0σD12Y1Y2
 X0σD123Y0Y1
 X0σD123Y0Y2
 X0σD123Y1Y0
 X0σD123Y1Y2
 X0σD13Y0Y1
 X0σD13Y0Y2
 X0σD13Y1Y0
 X0σD13Y1Y2
 X0σD132Y0Y1
 X0σD132Y0Y2
 X0σD132Y1Y0
 X0σD132Y1Y2
 X0σY0X1Y0
 X0σY0X1Y1
 X0σY0X1Y2
 X0σY0Y1X1
 X0σY0Y1Y0
 X0σY0Y1Y2
 X0σY0Y2X1
 X0σY1X1Y0
 X0σY1X1Y1
 X0σY1Y0X1
 X0σY1Y0Y2
 X0σY2X1Y0
 X0τσDeY0
 X0τσDeY1
 X0τσDeY2
 X0τσD12Y0
 X0τσD12Y1
 X0τσD12Y2
 X0τσY0Y1
 X0τσY0Y2
 X0τσY1Y0
 X0τσY1Y2
 X0τ^2DeY0
 X0τ^2DeY1
 X0τ^2DeY2
 X0τ^2D12Y0
 X0τ^2D12Y1
 X0τ^2D12Y2
 X0τ^2Y0Y1
 X0τ^2Y0Y2
 X0τ^2Y1Y0
 X0τ^2Y1Y2
 X0τDeY0Y1
 X0τDeY0Y2
 X0τDeY1Y0
 X0τDeY1Y2
 X0τD12Y0Y1
 X0τD12Y0Y2
 X0τD12Y1Y0
 X0τD12Y1Y2
 X0τD123Y0Y1
 X0τD123Y0Y2
 X0τD123Y1Y0
 X0τD123Y1Y2
 X0τD13Y0Y1
 X0τD13Y0Y2
 X0τD13Y1Y0
 X0τD13Y1Y2
 X0τD132Y0Y1
 X0τD132Y0Y2
 X0τD132Y1Y0
 X0τD132Y1Y2
 X0τY0Y1Y0
 X0τY0Y1Y2
 X0τY1Y0Y2
 X0DeY0Y1Y0
 X0DeY0Y1Y2
 X0DeY1Y0Y2
 X0D12Y0Y1Y0
 X0D12Y0Y1Y2
 X0D12Y1Y0Y2
 X0D123Y0Y1Y0
 X0D123Y0Y1Y2
 X0D123Y1Y0Y2
 X0D13Y0Y1Y0
 X0D13Y0Y1Y2
 X0D13Y1Y0Y2
 X0D132Y0Y1Y0
 X0D132Y0Y1Y2
 X0D132Y1Y0Y2
 X0Y0X1Y0Y1
 X0Y0X1Y0Y2
 X0Y0X1Y1Y0
 X0Y0X1Y1Y2
 X0Y0X2Y0Y1
 X0Y0X2Y0Y2
 X0Y0X2Y1Y0
 X0Y0X2Y1Y2
 X0Y0Y1X1Y0
 X0Y0Y1X1Y1
 X0Y0Y1X2Y0
 X0Y0Y1X2Y2
 X0Y0Y1Y0X1
 X0Y0Y1Y0X2
 X0Y0Y1Y0Y2
 X0Y0Y2X1Y0
 X0Y0Y2X2Y2
 X0Y1X1Y0Y1
 X0Y1X1Y0Y2
 X0Y1X2Y0Y1
 X0Y1X2Y0Y2
 X0Y1Y0X1Y0
 X0Y1Y0X1Y2
 X0Y1Y0X2Y1
 X0Y1Y0X2Y2
 X1X0X2στ
 X1X0X2σDe
 X1X0X2σD12
 X1X0X2σD123
 X1X0X2σD13
 X1X0X2σD132
 X1X0X2σY0
 X1X0X2σY1
 X1X0X2σY2
 X1X0X2τσ
 X1X0X2τ^2
 X1X0X2τDe
 X1X0X2τD12
 X1X0X2τD123
 X1X0X2τD13
 X1X0X2τD132
 X1X0X2τY0
 X1X0X2τY1
 X1X0X2τY2
 X1X0X2DeY0
 X1X0X2DeY1
 X1X0X2DeY2
 X1X0X2D12Y0
 X1X0X2D12Y1
 X1X0X2D12Y2
 X1X0X2D123Y0
 X1X0X2D123Y1
 X1X0X2D123Y2
 X1X0X2D13Y0
 X1X0X2D13Y1
 X1X0X2D13Y2
 X1X0X2D132Y0
 X1X0X2D132Y1
 X1X0X2D132Y2
 X1X0X2Y0X1
 X1X0X2Y0X2
 X1X0X2Y0Y1
 X1X0X2Y0Y2
 X1X0X2Y1X1
 X1X0X2Y1X2
 X1X0X2Y1Y0
 X1X0X2Y1Y2
 X1X0X2Y2X1
 X1X0X2Y2X2
 X1X0στDe
 X1X0στD12
 X1X0στY0
 X1X0στY1
 X1X0στY2
 X1X0σDeY0
 X1X0σDeY1
 X1X0σDeY2
 X1X0σD12Y0
 X1X0σD12Y1
 X1X0σD12Y2
 X1X0σD123Y0
 X1X0σD123Y1
 X1X0σD123Y2
 X1X0σD13Y0
 X1X0σD13Y1
 X1X0σD13Y2
 X1X0σD132Y0
 X1X0σD132Y1
 X1X0σD132Y2
 X1X0σY0X1
 X1X0σY0Y1
 X1X0σY0Y2
 X1X0σY1X1
 X1X0σY1Y0
 X1X0σY1Y2
 X1X0σY2X1
 X1X0τσDe
 X1X0τσD12
 X1X0τσY0
 X1X0τσY1
 X1X0τσY2
 X1X0τ^2De
 X1X0τ^2D12
 X1X0τ^2Y0
 X1X0τ^2Y1
 X1X0τ^2Y2
 X1X0τDeY0
 X1X0τDeY1
 X1X0τDeY2
 X1X0τD12Y0
 X1X0τD12Y1
 X1X0τD12Y2
 X1X0τD123Y0
 X1X0τD123Y1
 X1X0τD123Y2
 X1X0τD13Y0
 X1X0τD13Y1
 X1X0τD13Y2
 X1X0τD132Y0
 X1X0τD132Y1
 X1X0τD132Y2
 X1X0τY0Y1
 X1X0τY0Y2
 X1X0τY1Y0
 X1X0τY1Y2
 X1X0DeY0Y1
 X1X0DeY0Y2
 X1X0DeY1Y0
 X1X0DeY1Y2
 X1X0D12Y0Y1
 X1X0D12Y0Y2
 X1X0D12Y1Y0
 X1X0D12Y1Y2
 X1X0D123Y0Y1
 X1X0D123Y0Y2
 X1X0D123Y1Y0
 X1X0D123Y1Y2
 X1X0D13Y0Y1
 X1X0D13Y0Y2
 X1X0D13Y1Y0
 X1X0D13Y1Y2
 X1X0D132Y0Y1
 X1X0D132Y0Y2
 X1X0D132Y1Y0
 X1X0D132Y1Y2
 X1X0Y0X1Y0
 X1X0Y0X1Y1
 X1X0Y0X1Y2
 X1X0Y0X2Y0
 X1X0Y0X2Y1
 X1X0Y0X2Y2
 X1X0Y0Y1X1
 X1X0Y0Y1X2
 X1X0Y0Y1Y0
 X1X0Y0Y1Y2
 X1X0Y0Y2X1
 X1X0Y0Y2X2
 X1X0Y1X1Y0
 X1X0Y1X1Y1
 X1X0Y1X2Y0
 X1X0Y1X2Y2
 X1X0Y1Y0X1
 X1X0Y1Y0X2
 X1X0Y1Y0Y2
 X1X0Y2X1Y0
 X1X0Y2X2Y2
 X1X2στDe
 X1X2στD12
 X1X2στY0
 X1X2στY1
 X1X2στY2
 X1X2σDeY0
 X1X2σDeY1
 X1X2σDeY2
 X1X2σD12Y0
 X1X2σD12Y1
 X1X2σD12Y2
 X1X2σD123Y0
 X1X2σD123Y1
 X1X2σD123Y2
 X1X2σD13Y0
 X1X2σD13Y1
 X1X2σD13Y2
 X1X2σD132Y0
 X1X2σD132Y1
 X1X2σD132Y2
 X1X2σY0X1
 X1X2σY0Y1
 X1X2σY0Y2
 X1X2σY1X1
 X1X2σY1Y0
 X1X2σY1Y2
 X1X2σY2X1
 X1X2τσDe
 X1X2τσD12
 X1X2τσY0
 X1X2τσY1
 X1X2τσY2
 X1X2τ^2De
 X1X2τ^2D12
 X1X2τ^2Y0
 X1X2τ^2Y1
 X1X2τ^2Y2
 X1X2τDeY0
 X1X2τDeY1
 X1X2τDeY2
 X1X2τD12Y0
 X1X2τD12Y1
 X1X2τD12Y2
 X1X2τD123Y0
 X1X2τD123Y1
 X1X2τD123Y2
 X1X2τD13Y0
 X1X2τD13Y1
 X1X2τD13Y2
 X1X2τD132Y0
 X1X2τD132Y1
 X1X2τD132Y2
 X1X2τY0Y1
 X1X2τY0Y2
 X1X2τY1Y0
 X1X2τY1Y2
 X1X2DeY0Y1
 X1X2DeY0Y2
 X1X2DeY1Y0
 X1X2DeY1Y2
 X1X2D12Y0Y1
 X1X2D12Y0Y2
 X1X2D12Y1Y0
 X1X2D12Y1Y2
 X1X2D123Y0Y1
 X1X2D123Y0Y2
 X1X2D123Y1Y0
 X1X2D123Y1Y2
 X1X2D13Y0Y1
 X1X2D13Y0Y2
 X1X2D13Y1Y0
 X1X2D13Y1Y2
 X1X2D132Y0Y1
 X1X2D132Y0Y2
 X1X2D132Y1Y0
 X1X2D132Y1Y2
 X1X2Y0X1Y0
 X1X2Y0X1Y1
 X1X2Y0X1Y2
 X1X2Y0X2Y0
 X1X2Y0X2Y1
 X1X2Y0X2Y2
 X1X2Y0Y1X1
 X1X2Y0Y1X2
 X1X2Y0Y1Y0
 X1X2Y0Y1Y2
 X1X2Y0Y2X1
 X1X2Y0Y2X2
 X1X2Y1X1Y0
 X1X2Y1X1Y1
 X1X2Y1X2Y0
 X1X2Y1X2Y2
 X1X2Y1Y0X1
 X1X2Y1Y0X2
 X1X2Y1Y0Y2
 X1X2Y2X1Y0
 X1X2Y2X2Y2
 X1στDeY0
 X1στDeY1
 X1στDeY2
 X1στD12Y0
 X1στD12Y1
 X1στD12Y2
 X1στY0Y1
 X1στY0Y2
 X1στY1Y0
 X1στY1Y2
 X1σDeY0Y1
 X1σDeY0Y2
 X1σDeY1Y0
 X1σDeY1Y2
 X1σD12Y0Y1
 X1σD12Y0Y2
 X1σD12Y1Y0
 X1σD12Y1Y2
 X1σD123Y0Y1
 X1σD123Y0Y2
 X1σD123Y1Y0
 X1σD123Y1Y2
 X1σD13Y0Y1
 X1σD13Y0Y2
 X1σD13Y1Y0
 X1σD13Y1Y2
 X1σD132Y0Y1
 X1σD132Y0Y2
 X1σD132Y1Y0
 X1σD132Y1Y2
 X1σY0X1Y0
 X1σY0X1Y1
 X1σY0X1Y2
 X1σY0Y1X1
 X1σY0Y1Y0
 X1σY0Y1Y2
 X1σY0Y2X1
 X1σY1X1Y0
 X1σY1X1Y1
 X1σY1Y0X1
 X1σY1Y0Y2
 X1σY2X1Y0
 X1τσDeY0
 X1τσDeY1
 X1τσDeY2
 X1τσD12Y0
 X1τσD12Y1
 X1τσD12Y2
 X1τσY0Y1
 X1τσY0Y2
 X1τσY1Y0
 X1τσY1Y2
 X1τ^2DeY0
 X1τ^2DeY1
 X1τ^2DeY2
 X1τ^2D12Y0
 X1τ^2D12Y1
 X1τ^2D12Y2
 X1τ^2Y0Y1
 X1τ^2Y0Y2
 X1τ^2Y1Y0
 X1τ^2Y1Y2
 X1τDeY0Y1
 X1τDeY0Y2
 X1τDeY1Y0
 X1τDeY1Y2
 X1τD12Y0Y1
 X1τD12Y0Y2
 X1τD12Y1Y0
 X1τD12Y1Y2
 X1τD123Y0Y1
 X1τD123Y0Y2
 X1τD123Y1Y0
 X1τD123Y1Y2
 X1τD13Y0Y1
 X1τD13Y0Y2
 X1τD13Y1Y0
 X1τD13Y1Y2
 X1τD132Y0Y1
 X1τD132Y0Y2
 X1τD132Y1Y0
 X1τD132Y1Y2
 X1τY0Y1Y0
 X1τY0Y1Y2
 X1τY1Y0Y2
 X1DeY0Y1Y0
 X1DeY0Y1Y2
 X1DeY1Y0Y2
 X1D12Y0Y1Y0
 X1D12Y0Y1Y2
 X1D12Y1Y0Y2
 X1D123Y0Y1Y0
 X1D123Y0Y1Y2
 X1D123Y1Y0Y2
 X1D13Y0Y1Y0
 X1D13Y0Y1Y2
 X1D13Y1Y0Y2
 X1D132Y0Y1Y0
 X1D132Y0Y1Y2
 X1D132Y1Y0Y2
 X1Y0X1Y0Y1
 X1Y0X1Y0Y2
 X1Y0X1Y1Y0
 X1Y0X1Y1Y2
 X1Y0X2Y0Y1
 X1Y0X2Y0Y2
 X1Y0X2Y1Y0
 X1Y0X2Y1Y2
 X1Y0Y1X1Y0
 X1Y0Y1X1Y1
 X1Y0Y1X2Y0
 X1Y0Y1X2Y2
 X1Y0Y1Y0X1
 X1Y0Y1Y0X2
 X1Y0Y1Y0Y2
 X1Y0Y2X1Y0
 X1Y0Y2X2Y2
 X1Y1X1Y0Y1
 X1Y1X1Y0Y2
 X1Y1X2Y0Y1
 X1Y1X2Y0Y2
 X1Y1Y0X1Y0
 X1Y1Y0X1Y2
 X1Y1Y0X2Y1
 X1Y1Y0X2Y2
 X2στDeY0
 X2στDeY1
 X2στDeY2
 X2στD12Y0
 X2στD12Y1
 X2στD12Y2
 X2στY0Y1
 X2στY0Y2
 X2στY1Y0
 X2στY1Y2
 X2σDeY0Y1
 X2σDeY0Y2
 X2σDeY1Y0
 X2σDeY1Y2
 X2σD12Y0Y1
 X2σD12Y0Y2
 X2σD12Y1Y0
 X2σD12Y1Y2
 X2σD123Y0Y1
 X2σD123Y0Y2
 X2σD123Y1Y0
 X2σD123Y1Y2
 X2σD13Y0Y1
 X2σD13Y0Y2
 X2σD13Y1Y0
 X2σD13Y1Y2
 X2σD132Y0Y1
 X2σD132Y0Y2
 X2σD132Y1Y0
 X2σD132Y1Y2
 X2σY0X1Y0
 X2σY0X1Y1
 X2σY0X1Y2
 X2σY0Y1X1
 X2σY0Y1Y0
 X2σY0Y1Y2
 X2σY0Y2X1
 X2σY1X1Y0
 X2σY1X1Y1
 X2σY1Y0X1
 X2σY1Y0Y2
 X2σY2X1Y0
 X2τσDeY0
 X2τσDeY1
 X2τσDeY2
 X2τσD12Y0
 X2τσD12Y1
 X2τσD12Y2
 X2τσY0Y1
 X2τσY0Y2
 X2τσY1Y0
 X2τσY1Y2
 X2τ^2DeY0
 X2τ^2DeY1
 X2τ^2DeY2
 X2τ^2D12Y0
 X2τ^2D12Y1
 X2τ^2D12Y2
 X2τ^2Y0Y1
 X2τ^2Y0Y2
 X2τ^2Y1Y0
 X2τ^2Y1Y2
 X2τDeY0Y1
 X2τDeY0Y2
 X2τDeY1Y0
 X2τDeY1Y2
 X2τD12Y0Y1
 X2τD12Y0Y2
 X2τD12Y1Y0
 X2τD12Y1Y2
 X2τD123Y0Y1
 X2τD123Y0Y2
 X2τD123Y1Y0
 X2τD123Y1Y2
 X2τD13Y0Y1
 X2τD13Y0Y2
 X2τD13Y1Y0
 X2τD13Y1Y2
 X2τD132Y0Y1
 X2τD132Y0Y2
 X2τD132Y1Y0
 X2τD132Y1Y2
 X2τY0Y1Y0
 X2τY0Y1Y2
 X2τY1Y0Y2
 X2DeY0Y1Y0
 X2DeY0Y1Y2
 X2DeY1Y0Y2
 X2D12Y0Y1Y0
 X2D12Y0Y1Y2
 X2D12Y1Y0Y2
 X2D123Y0Y1Y0
 X2D123Y0Y1Y2
 X2D123Y1Y0Y2
 X2D13Y0Y1Y0
 X2D13Y0Y1Y2
 X2D13Y1Y0Y2
 X2D132Y0Y1Y0
 X2D132Y0Y1Y2
 X2D132Y1Y0Y2
 X2Y0X1Y0Y1
 X2Y0X1Y0Y2
 X2Y0X1Y1Y0
 X2Y0X1Y1Y2
 X2Y0X2Y0Y1
 X2Y0X2Y0Y2
 X2Y0X2Y1Y0
 X2Y0X2Y1Y2
 X2Y0Y1X1Y0
 X2Y0Y1X1Y1
 X2Y0Y1X2Y0
 X2Y0Y1X2Y2
 X2Y0Y1Y0X1
 X2Y0Y1Y0X2
 X2Y0Y1Y0Y2
 X2Y0Y2X1Y0
 X2Y0Y2X2Y2
 X2Y1X1Y0Y1
 X2Y1X1Y0Y2
 X2Y1X2Y0Y1
 X2Y1X2Y0Y2
 X2Y1Y0X1Y0
 X2Y1Y0X1Y2
 X2Y1Y0X2Y1
 X2Y1Y0X2Y2
 στDeY0Y1
 στDeY0Y2
 στDeY1Y0
 στDeY1Y2
 στD12Y0Y1
 στD12Y0Y2
 στD12Y1Y0
 στD12Y1Y2
 στY0Y1Y0
 στY0Y1Y2
 στY1Y0Y2
 σDeY0Y1Y0
 σDeY0Y1Y2
 σDeY1Y0Y2
 σD12Y0Y1Y0
 σD12Y0Y1Y2
 σD12Y1Y0Y2
 σD123Y0Y1Y0

## Data

In [1496]:
Y12bis:=[];; 
for bi in Base_FK3 do
    Y0   := GP2NP(Y12);
    prod := StrongNormalFormNP(MulNP(Y0, bi), J);
    Add(Y12bis, rec(bi := bi, prod := prod, yj := Y0));
od;

In [1498]:
Y13bis:=[];; 
for bi in Base_FK3 do
    Y1   := GP2NP(Y13);
    prod := StrongNormalFormNP(MulNP(Y1, bi), J);
    Add(Y13bis, rec(bi := bi, prod := prod, yj := Y1));
od;

In [1500]:
Y23bis:=[];; 
for bi in Base_FK3 do
    Y2   := GP2NP(Y23);
    prod := StrongNormalFormNP(MulNP(Y2, bi), J);
    Add(Y23bis, rec(bi := bi, prod := prod, yj := Y2));
od;

In [1501]:
PrintNPList(List(Y12bis, ys -> ys.prod));

 Y0
 σD12 - σDe - X0Y0 + 1
 Y0X1
 Y0X2
 X2σD13 - X2σD123 - X0Y0X1 + X1
 - 2X1σD132 - X1σD13 - X1σD123 - X1σD12 - X1σDe - X0Y0X2 + X1σ + X2
 X2Y1X1 + 2X1σD132 + X1σD13 + X1σD123 + X1σD12 + X1σDe - X0X2Y1 - X1σ - \
X2
 - X1Y2X2 + X0Y0X1 + X0X1Y2
 2X1X2σD132 + X1X2σD13 + X1X2σD123 + X1X2σD12 + X1X2σDe - X0X2Y1X1 - X1X2\
σ + X1X0 + X0X2
 - X1X0σD13 + X1X0σD123 - X0X2σD13 + X0X2σD123 + X0X1Y2X2 + X1X2
 - X1X2Y2X1 + X1X0Y1X2 + X1X0X2Y0 - X0X1Y2X1
 X1X0X2σD12 - X1X0X2σDe + X0X1X2Y2X1 - X0X1X0Y1X2 - X0X1X0X2Y0 + X1X0X2

In [1502]:
PrintNPList(List(Y13bis, ys -> ys.prod));

 Y1
 σD13 - σD123 - X0Y2
 Y1X1
 Y1X2
 X2σD12 - X2σDe - X0Y2X1
 X1σD13 - X1σD123 - X0Y2X2
 X2Y0X1 - X1σD13 + X1σD123 - X0X2Y2 + X0
 - X1Y1X2 + X0Y2X1 + X0X1Y0 + X2
 - X1X2σD12 + X1X2σDe - X0X2Y2X1 + X0X1
 2X1X0σD132 + X1X0σD13 + X1X0σD123 + X1X0σD12 + X1X0σDe + 2X0X2σD132 + X\
0X2σD13 + X0X2σD123 + X0X2σD12 + X0X2σDe + X0X1Y0X2 - X1X0σ - X0X2σ
 - X1X2Y0X1 + X1X0Y2X2 + X1X0X2Y2 - X0X1Y0X1 + X0X2
 - 2X1X0X2σD132 - X1X0X2σD13 - X1X0X2σD123 - X1X0X2σD12 - X1X0X2σDe + X0X\
1X2Y1X1 - X0X1X0Y0X2 - X0X1X0X2Y1 + X1X0X2σ

In [1503]:
PrintNPList(List(Y23bis, ys -> ys.prod));

 Y2
 - 2σD132 - σD13 - σD123 - σD12 - σDe - X0Y1 + σ
 Y2X1
 Y2X2
 - 2X2σD132 - X2σD13 - X2σD123 - X2σD12 - X2σDe - X0Y1X1 + X2σ
 X1σD12 - X1σDe - X0Y1X2
 X2Y2X1 - X1σD12 + X1σDe - X0X2Y0 - X1
 - X1Y0X2 + X0Y1X1 + X0X1Y1 - X0
 - X1X2σD13 + X1X2σD123 - X0X2Y0X1
 - X1X0σD12 + X1X0σDe - X0X2σD12 + X0X2σDe + X0X1Y1X2 - X0X2
 - X1X2Y1X1 + X1X0Y0X2 + X1X0X2Y1 - X0X1Y1X1 + X0X1
 X1X0X2σD13 - X1X0X2σD123 + X0X1X2Y0X1 - X0X1X0Y2X2 - X0X1X0X2Y2

## Calculo de $y_{top}x_{top}$

Las relaciones definitorias del álgebra de Nichols $\mathfrak{B}(V)$ son
$$
x_{(12)}^{2}, \quad x_{(13)}^{2}, \quad x_{(23)}^{2},
$$
$$
x_{(12)}x_{(13)} + x_{(23)}x_{(12)} + x_{(13)}x_{(23)} 
\quad \text{y} \quad 
x_{(13)}x_{(12)} + x_{(12)}x_{(23)} + x_{(23)}x_{(13)}.
$$

Denotamos por $\mathbb{B}$ a la base de $\mathfrak{B}(V)$, la cual se obtiene eligiendo un elemento por cada fila de la siguiente lista y multiplicándolos de arriba hacia abajo, véase *e.g.* [7]:

$$
\begin{array}{l}
1, \, x_{(12)}, \\[4pt]
1, \, x_{(13)}, \, x_{(13)}x_{(12)}, \\[4pt]
1, \, x_{(23)}.
\end{array}
$$

Sea $\mathbb{B}^n = \mathbb{B} \cap \mathfrak{B}^n(V)$, $n \geq 0$. 
El elemento de grado máximo en $\mathbb{B}$ es
$$
x_{\text{top}} = x_{(12)}x_{(13)}x_{(12)}x_{(23)} \in \mathbb{B}^4.
$$

In [1504]:

Xtop := [ [ [1, 2, 1, 3] ], [1] ];;

In [1505]:
Ytop := [ [ [12, 13, 12, 14] ], [1] ];;

In [1506]:
PrintNP(Xtop);

 X0X1X0X2

In [1507]:
Xtop=Last(Base_FK3);

true

In [1508]:
PrintNP(Ytop);

 Y0Y1Y0Y2

In [1509]:
Ytop=Last(Base_FK3dual);

true

In [1510]:
PrintNP(MulNP(Ytop, Xtop));

 Y0Y1Y0Y2X0X1X0X2

In [1511]:
YtopXtop := StrongNormalFormNP(MulNP(Ytop, Xtop), J);

[ [ [ 2, 1, 3, 4, 10, 12, 13, 14 ], [ 2, 1, 3, 4, 9, 12, 13, 14 ],       [ 2, 1, 3, 4, 9, 12, 13, 12 ], [ 2, 1, 3, 4, 8, 12, 13, 14 ],       [ 2, 1, 3, 4, 8, 12, 13, 12 ], [ 2, 1, 3, 4, 7, 13, 12, 14 ],       [ 2, 1, 3, 4, 7, 12, 13, 14 ], [ 2, 1, 3, 4, 6, 13, 12, 14 ],       [ 2, 1, 3, 4, 6, 12, 13, 14 ], [ 1, 2, 3, 12, 13, 12, 2, 12 ],       [ 1, 2, 3, 12, 13, 2, 12, 13 ], [ 1, 2, 3, 12, 2, 12, 13, 12 ],       [ 1, 2, 1, 12, 13, 12, 3, 14 ], [ 1, 2, 1, 12, 13, 3, 12, 13 ],       [ 1, 2, 1, 3, 12, 13, 12, 14 ], [ 2, 1, 5, 5, 7, 13, 14 ],       [ 2, 1, 5, 5, 7, 13, 12 ], [ 2, 1, 5, 5, 7, 12, 14 ],       [ 2, 1, 5, 5, 7, 12, 13 ], [ 2, 1, 5, 5, 6, 13, 14 ],       [ 2, 1, 5, 5, 6, 13, 12 ], [ 2, 1, 5, 5, 6, 12, 14 ],       [ 2, 1, 5, 5, 6, 12, 13 ], [ 2, 1, 4, 13, 12, 2, 12 ],       [ 2, 1, 4, 13, 2, 12, 14 ], [ 2, 1, 4, 12, 13, 12, 2 ],       [ 2, 1, 4, 12, 13, 2, 12 ], [ 2, 1, 4, 12, 2, 13, 14 ],       [ 2, 1, 4, 12, 2, 12, 13 ], [ 2, 1, 3, 4, 13, 12, 14 ],       [ 2, 1, 3, 4, 12, 13, 14 ], [ 2, 1, 3, 4, 12, 13, 12 ],       [ 1, 3, 5, 5, 7, 13, 14 ], [ 1, 3, 5, 5, 7, 13, 12 ],       [ 1, 3, 5, 5, 7, 12, 14 ], [ 1, 3, 5, 5, 7, 12, 13 ],       [ 1, 3, 5, 5, 6, 13, 14 ], [ 1, 3, 5, 5, 6, 13, 12 ],       [ 1, 3, 5, 5, 6, 12, 14 ], [ 1, 3, 5, 5, 6, 12, 13 ],       [ 1, 3, 4, 13, 12, 2, 14 ], [ 1, 3, 4, 13, 12, 2, 12 ],       [ 1, 3, 4, 13, 2, 12, 14 ], [ 1, 3, 4, 13, 2, 12, 13 ],       [ 1, 3, 4, 12, 14, 2, 12 ], [ 1, 3, 4, 12, 13, 12, 2 ],       [ 1, 3, 4, 12, 13, 2, 13 ], [ 1, 3, 4, 12, 13, 2, 12 ],       [ 1, 3, 4, 12, 2, 13, 14 ], [ 1, 3, 4, 12, 2, 13, 12 ],       [ 1, 3, 4, 12, 2, 12, 14 ], [ 1, 3, 4, 12, 2, 12, 13 ],       [ 2, 3, 12, 13, 12, 2 ], [ 2, 3, 5, 10, 13, 14 ],       [ 2, 3, 5, 10, 13, 12 ], [ 2, 3, 5, 9, 13, 14 ], [ 2, 3, 5, 9, 12, 13 ],      [ 2, 3, 5, 8, 13, 14 ], [ 2, 3, 5, 8, 13, 12 ], [ 2, 3, 5, 8, 12, 14 ],       [ 2, 3, 5, 7, 13, 14 ], [ 2, 3, 5, 7, 12, 13 ], [ 2, 3, 5, 6, 13, 14 ],       [ 2, 3, 5, 6, 12, 14 ], [ 2, 3, 4, 10, 12, 13 ], [ 2, 3, 4, 9, 12, 13 ],      [ 2, 3, 4, 8, 12, 13 ], [ 2, 3, 4, 7, 13, 12 ], [ 2, 3, 4, 7, 12, 13 ],       [ 2, 3, 4, 6, 13, 12 ], [ 2, 3, 4, 6, 12, 13 ], [ 2, 1, 12, 13, 3, 14 ],      [ 2, 1, 12, 3, 13, 12 ], [ 2, 1, 5, 5, 13, 14 ], [ 2, 1, 5, 5, 13, 12 ],      [ 2, 1, 5, 5, 12, 13 ], [ 2, 1, 4, 9, 12, 14 ], [ 2, 1, 4, 8, 12, 14 ],       [ 2, 1, 4, 7, 13, 14 ], [ 2, 1, 4, 7, 12, 13 ], [ 2, 1, 4, 6, 13, 14 ],       [ 2, 1, 4, 6, 12, 13 ], [ 2, 1, 3, 13, 12, 14 ],       [ 1, 3, 13, 12, 2, 12 ], [ 1, 3, 13, 2, 12, 13 ],       [ 1, 3, 12, 14, 2, 12 ], [ 1, 3, 5, 5, 12, 14 ], [ 1, 3, 5, 5, 12, 13 ],      [ 1, 3, 4, 9, 12, 14 ], [ 1, 3, 4, 8, 12, 14 ], [ 1, 3, 4, 7, 13, 14 ],       [ 1, 3, 4, 7, 12, 13 ], [ 1, 3, 4, 6, 13, 14 ], [ 1, 3, 4, 6, 12, 13 ],       [ 1, 2, 13, 12, 3, 14 ], [ 1, 2, 13, 3, 12, 13 ],       [ 1, 2, 12, 13, 12, 2 ], [ 1, 2, 5, 10, 13, 12 ],       [ 1, 2, 5, 10, 12, 14 ], [ 1, 2, 5, 10, 12, 13 ],       [ 1, 2, 5, 9, 13, 14 ], [ 1, 2, 5, 9, 12, 13 ], [ 1, 2, 5, 8, 12, 14 ],       [ 1, 2, 5, 8, 12, 13 ], [ 1, 2, 5, 7, 13, 14 ], [ 1, 2, 5, 7, 12, 13 ],       [ 1, 2, 5, 6, 13, 12 ], [ 1, 2, 5, 6, 12, 13 ], [ 1, 2, 3, 12, 13, 14 ],      [ 1, 2, 1, 12, 13, 12 ], [ 3, 5, 5, 7, 14 ], [ 3, 5, 5, 7, 13 ],       [ 3, 5, 5, 6, 14 ], [ 3, 5, 5, 6, 13 ], [ 3, 4, 13, 12, 2 ],       [ 3, 4, 13, 2, 13 ], [ 3, 4, 12, 13, 2 ], [ 3, 4, 12, 2, 14 ],       [ 2, 5, 5, 7, 13 ], [ 2, 5, 5, 7, 12 ], [ 2, 5, 5, 6, 13 ],       [ 2, 5, 5, 6, 12 ], [ 2, 4, 13, 12, 2 ], [ 2, 4, 13, 2, 13 ],       [ 2, 4, 13, 2, 12 ], [ 2, 4, 12, 14, 2 ], [ 2, 4, 12, 2, 13 ],       [ 2, 4, 12, 2, 12 ], [ 2, 3, 5, 13, 14 ], [ 2, 3, 4, 13, 14 ],       [ 2, 3, 4, 13, 12 ], [ 2, 3, 4, 12, 14 ], [ 2, 3, 4, 12, 13 ],       [ 2, 1, 4, 13, 14 ], [ 2, 1, 4, 12, 14 ], [ 2, 1, 4, 12, 13 ],       [ 1, 5, 5, 7, 14 ], [ 1, 5, 5, 7, 12 ], [ 1, 5, 5, 6, 14 ],       [ 1, 5, 5, 6, 12 ], [ 1, 4, 14, 2, 12 ], [ 1, 4, 13, 2, 12 ],       [ 1, 4, 12, 14, 2 ], [ 1, 4, 12, 13, 2 ], [ 1, 4, 12, 2, 14 ],       [ 1, 4, 12, 2, 13 ], [ 1, 4, 12, 2, 12 ], [ 1, 3, 4, 13, 14 ],       [ 1, 3, 4, 13, 12 ], [ 1, 3, 4, 12, 14 ], [ 1, 3, 4, 12, 13 ],       [ 1, 2, 5, 12, 13 ], [ 3, 14, 3, 14 ], [ 3, 13, 12, 2 ],       [ 3, 13, 3, 12 ], [ 3, 12, 14, 2 ], [ 3, 12, 3, 13 ], [ 3, 5, 10, 14 ],       [ 3, 5, 10, 12 ], [ 3, 5, 9, 12 ], [ 3, 5, 8, 14 ], [ 3, 5, 8, 12 ],       [ 3, 5, 7, 12 ], [ 3, 5, 6, 12 ], [ 3, 5, 5, 14 ], [ 3, 5, 5, 13 ],       [ 3, 4, 10, 12 ], [ 3, 4, 9, 13 ], [ 3, 4, 9, 12 ], [ 3, 4, 8, 13 ],       [ 3, 4, 8, 12 ], [ 3, 4, 7, 12 ], [ 3, 4, 6, 12 ], [ 2, 14, 2, 12 ],       [ 2, 13, 3, 14 ], [ 2, 13, 2, 13 ], [ 2, 12, 3, 12 ], [ 2, 12, 2, 14 ],       [ 2, 5, 10, 14 ], [ 2, 5, 10, 13 ], [ 2, 5, 9, 14 ], [ 2, 5, 8, 14 ],       [ 2, 5, 8, 13 ], [ 2, 5, 7, 14 ], [ 2, 5, 6, 14 ], [ 2, 5, 5, 13 ],       [ 2, 4, 10, 14 ], [ 2, 4, 9, 14 ], [ 2, 4, 9, 12 ], [ 2, 4, 8, 14 ],       [ 2, 4, 8, 12 ], [ 2, 4, 7, 14 ], [ 2, 4, 6, 14 ], [ 2, 3, 13, 12 ],       [ 2, 3, 12, 14 ], [ 1, 12, 14, 3 ], [ 1, 12, 13, 2 ], [ 1, 5, 10, 12 ],       [ 1, 5, 9, 13 ], [ 1, 5, 8, 12 ], [ 1, 5, 7, 13 ], [ 1, 5, 5, 14 ],       [ 1, 5, 5, 12 ], [ 1, 4, 10, 13 ], [ 1, 4, 9, 14 ], [ 1, 4, 9, 13 ],       [ 1, 4, 8, 14 ], [ 1, 4, 8, 13 ], [ 1, 4, 7, 13 ], [ 1, 4, 7, 12 ],       [ 1, 4, 6, 13 ], [ 1, 4, 6, 12 ], [ 1, 3, 13, 14 ], [ 1, 3, 12, 13 ],       [ 5, 5, 6 ], [ 4, 14, 2 ], [ 4, 13, 2 ], [ 4, 12, 2 ], [ 3, 5, 12 ],       [ 3, 4, 13 ], [ 3, 4, 12 ], [ 2, 5, 14 ], [ 2, 4, 14 ], [ 2, 4, 13 ],       [ 2, 4, 12 ], [ 1, 4, 13 ], [ 1, 4, 12 ], [ 14, 3 ], [ 13, 2 ],       [ 5, 10 ], [ 5, 8 ], [ 5, 6 ], [ 5, 5 ], [ 4, 7 ], [ 4, 6 ], [ 3, 14 ],       [ 2, 13 ], [ 1, 12 ], [ 4 ], [  ] ],   [ -2, -1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, -1, 1, -1, 2, -1, 1, 1, 1, -2,       -1, 2, 1/2, 1/2, 3/2, -1/2, -3, -1/2, -3/2, 1/2, -1/2, 1, 1, 2, 2, -1,       -1, 1, 1, -1/2, 1/2, 3/2, 1/2, 1/2, 1, 1/2, -1/2, -2, -1/2, -1/2, -3/2,       -1, 1, -1, 2, 1, 1, 1, 1, 1, -1, 1, -1, -2, -1, -1, 1, -1, -1, -1, 1,       -1, -1/2, 1/2, -1/2, -1, 1, 1, 1, -1, -1, -1, 1, 1, 1, -1/2, -1/2, -1,       1, 1, 1, -1, -1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, -1, -2, 1, -1,       -1, -1, 2, 1, 1, 2, -1/2, 3/2, 1/2, -3/2, 2, 1, 1, -1, 1/2, 1/2, -1,       1/2, -3/2, 1/2, -1, 1/2, -1/2, -3/2, 1, -1/2, 1, -1/2, -2, 2, -1, 1,       1/2, 1/2, -1/2, 1/2, 1/2, 1/2, -2, -2, -1/2, -1/2, -3, 1, 1, -1, 1, -1,       1, -1, 1, 1, 1, 1, 2, 1, -1/2, -1/2, 2, 1, 1, -1, 1, 1, 1, 1, -1, 1, 1,       1, -1, -1, -2, -1, 1, -1, -1, -1/2, -2, -1, -1, -1, 1, -1, -1, 1, -1,       1, 1, -1, 1, 1, -1, 1/2, -1/2, -2, 1, -1, -1, -1, -1, 1, -1, -1, -1,       -1, -3, -1/2, -1/2, -1/2, -1, -1, -1, 1, 3/2, -1/2, 1, 1, -1, -2, -2,       1, 1, -2, 1/2, -2, 2, -3, -2, -1, 1/2, 2 ] ]

In [1512]:
PrintNP(YtopXtop);

 - 2X1X0X2σD132Y0Y1Y2 - X1X0X2σD13Y0Y1Y2 - X1X0X2σD13Y0Y1Y0 - X1X0X2σD123Y\
0Y1Y2 + X1X0X2σD123Y0Y1Y0 + X1X0X2σD12Y1Y0Y2 - X1X0X2σD12Y0Y1Y2 - X1X0X2σD\
eY1Y0Y2 - X1X0X2σDeY0Y1Y2 + X0X1X2Y0Y1Y0X1Y0 + X0X1X2Y0Y1X1Y0Y1 + X0X1X2Y0X1Y\
0Y1Y0 - X0X1X0Y0Y1Y0X2Y2 + X0X1X0Y0Y1X2Y0Y1 - X0X1X0X2Y0Y1Y0Y2 + 2X1X0τ^2D12Y\
1Y2 - X1X0τ^2D12Y1Y0 + X1X0τ^2D12Y0Y2 + X1X0τ^2D12Y0Y1 + X1X0τ^2DeY1Y2 - 2\
X1X0τ^2DeY1Y0 - X1X0τ^2DeY0Y2 + 2X1X0τ^2DeY0Y1 + 1/2X1X0σY1Y0X1Y0 + 1/2X1X\
0σY1X1Y0Y2 + 3/2X1X0σY0Y1Y0X1 - 1/2X1X0σY0Y1X1Y0 - 3X1X0σY0X1Y1Y2 - 1/2X1X\
0σY0X1Y0Y1 - 3/2X1X0X2σY1Y0Y2 + 1/2X1X0X2σY0Y1Y2 - 1/2X1X0X2σY0Y1Y0 + X0X2\
τ^2D12Y1Y2 + X0X2τ^2D12Y1Y0 + 2X0X2τ^2D12Y0Y2 + 2X0X2τ^2D12Y0Y1 - X0X2τ^2\
DeY1Y2 - X0X2τ^2DeY1Y0 + X0X2τ^2DeY0Y2 + X0X2τ^2DeY0Y1 - 1/2X0X2σY1Y0X1Y2 \
+ 1/2X0X2σY1Y0X1Y0 + 3/2X0X2σY1X1Y0Y2 + 1/2X0X2σY1X1Y0Y1 + 1/2X0X2σY0Y2X1Y\
0 + X0X2σY0Y1Y0X1 + 1/2X0X2σY0Y1X1Y1 - 1/2X0X2σY0Y1X1Y0 - 2X0X2σY0X1Y1Y2 -\
 1/2X0X2σY0X1Y1Y0 - 1/2X0X2σY0X1Y0Y2 - 3/2X0X2σY0X1Y0Y1 - X1X2Y0Y1Y0X1 + X1\
X2τD132Y1Y2 - X1X2τD132Y1Y0 + 2X1X2τD13Y1Y2 + X1X2τD13Y0Y1 + X1X2τD123Y1Y\
2 + X1X2τD123Y1Y0 + X1X2τD123Y0Y2 + X1X2τD12Y1Y2 - X1X2τD12Y0Y1 + X1X2τDe\
Y1Y2 - X1X2τDeY0Y2 - 2X1X2σD132Y0Y1 - X1X2σD13Y0Y1 - X1X2σD123Y0Y1 + X1X2Ï\
D12Y1Y0 - X1X2σD12Y0Y1 - X1X2σDeY1Y0 - X1X2σDeY0Y1 + X1X0Y0Y1X2Y2 - X1X0Y0\
X2Y1Y0 - 1/2X1X0τ^2Y1Y2 + 1/2X1X0τ^2Y1Y0 - 1/2X1X0τ^2Y0Y1 - X1X0σD13Y0Y2 +\
 X1X0σD123Y0Y2 + X1X0σD12Y1Y2 + X1X0σD12Y0Y1 - X1X0σDeY1Y2 - X1X0σDeY0Y1 \
- X1X0X2Y1Y0Y2 + X0X2Y1Y0X1Y0 + X0X2Y1X1Y0Y1 + X0X2Y0Y2X1Y0 - 1/2X0X2τ^2Y0Y2 \
- 1/2X0X2τ^2Y0Y1 - X0X2σD13Y0Y2 + X0X2σD123Y0Y2 + X0X2σD12Y1Y2 + X0X2σD12\
Y0Y1 - X0X2σDeY1Y2 - X0X2σDeY0Y1 + X0X1Y1Y0X2Y2 - X0X1Y1X2Y0Y1 - X0X1Y0Y1Y0X\
1 - X0X1τD132Y1Y0 - X0X1τD132Y0Y2 - X0X1τD132Y0Y1 + X0X1τD13Y1Y2 - X0X1τD\
13Y0Y1 + X0X1τD123Y0Y2 - X0X1τD123Y0Y1 - X0X1τD12Y1Y2 - 2X0X1τD12Y0Y1 + X0\
X1τDeY1Y0 - X0X1τDeY0Y1 - X0X1X2Y0Y1Y2 - X0X1X0Y0Y1Y0 + 2X2τ^2D12Y2 + X2τ^\
2D12Y1 + X2τ^2DeY2 + 2X2τ^2DeY1 - 1/2X2σY1Y0X1 + 3/2X2σY1X1Y1 + 1/2X2σY0Y\
1X1 - 3/2X2σY0X1Y2 + 2X1τ^2D12Y1 + X1τ^2D12Y0 + X1τ^2DeY1 - X1τ^2DeY0 + 1\
/2X1σY1Y0X1 + 1/2X1σY1X1Y1 - X1σY1X1Y0 + 1/2X1σY0Y2X1 - 3/2X1σY0X1Y1 + 1/\
2X1σY0X1Y0 - X1X2τY1Y2 + 1/2X1X2σY1Y2 - 1/2X1X2σY1Y0 - 3/2X1X2σY0Y2 + X1X\
2σY0Y1 - 1/2X1X0σY1Y2 + X1X0σY0Y2 - 1/2X1X0σY0Y1 - 2X0τ^2D12Y2 + 2X0τ^2D\
12Y0 - X0τ^2DeY2 + X0τ^2DeY0 + 1/2X0σY2X1Y0 + 1/2X0σY1X1Y0 - 1/2X0σY0Y2X1\
 + 1/2X0σY0Y1X1 + 1/2X0σY0X1Y2 + 1/2X0σY0X1Y1 - 2X0σY0X1Y0 - 2X0X2σY1Y2 -\
 1/2X0X2σY1Y0 - 1/2X0X2σY0Y2 - 3X0X2σY0Y1 + X0X1τY0Y1 + X2Y2X2Y2 - X2Y1Y0X\
1 + X2Y1X2Y0 - X2Y0Y2X1 + X2Y0X2Y1 - X2τD132Y2 + X2τD132Y0 + X2τD13Y0 + X2Ï\
D123Y2 + X2τD123Y0 + 2X2τD12Y0 + X2τDeY0 - 1/2X2τ^2Y2 - 1/2X2τ^2Y1 + 2X2\
σD132Y0 + X2σD13Y1 + X2σD13Y0 - X2σD123Y1 + X2σD123Y0 + X2σD12Y0 + X2σD\
eY0 + X1Y2X1Y0 - X1Y1X2Y2 + X1Y1X1Y1 + X1Y0X2Y0 + X1Y0X1Y2 - X1τD132Y2 - X1τ\
D132Y1 - 2X1τD13Y2 - X1τD123Y2 + X1τD123Y1 - X1τD12Y2 - X1τDeY2 - 1/2X1τ\
^2Y1 - 2X1σD132Y2 - X1σD13Y2 - X1σD13Y0 - X1σD123Y2 + X1σD123Y0 - X1σD12\
Y2 - X1σDeY2 + X1X2Y1Y0 - X1X2Y0Y2 + X0Y0Y2X2 + X0Y0Y1X1 - X0τD132Y0 + X0τD\
13Y1 + X0τD123Y0 - X0τD12Y1 + 1/2X0τ^2Y2 - 1/2X0τ^2Y0 - 2X0σD132Y1 + X0σ\
D13Y2 - X0σD13Y1 - X0σD123Y2 - X0σD123Y1 - X0σD12Y1 + X0σD12Y0 - X0σDeY1\
 - X0σDeY0 - X0X2Y1Y2 - X0X2Y0Y1 - 3τ^2De - 1/2σY2X1 - 1/2σY1X1 - 1/2σY0X\
1 - X2τY0 - X2σY1 - X2σY0 + X1τY2 + 3/2X1σY2 - 1/2X1σY1 + X1σY0 + X0σY\
1 - X0σY0 - 2Y2X2 - 2Y1X1 + τD132 + τD123 - 2τDe + 1/2τ^2 - 2σD12 + 2σD\
e - 3X2Y2 - 2X1Y1 - X0Y0 + 1/2σ + 2

# conmutacion

In [1514]:
prod:=GP2NP(Y23*X23);;
PrintNP(CommuteYBeforeX(prod));

 1 - στDe + στD23

# Remover

In [1515]:
example_prod:=[ [ [ 1, 12 ], [  ], [ 4, 6 ], [ 4, 7 ] ], [ -1, 1, -1, 1 ] ];

[ [ [ 1, 12 ], [  ], [ 4, 6 ], [ 4, 7 ] ], [ -1, 1, -1, 1 ] ]

In [1516]:
PrintNP(example_prod);

 - X0Y0 + 1 - σDe + σD12

In [1517]:
PrintNP(RemoveYterms(example_prod));

 1 - σDe + σD12

In [1518]:
PrintNPList(RemoveAndCommuteYInYjBis(Y12bis));

 0
 σD12 - σDe + 1
 - στ^2D132 + στ^2D12
 στD12 - στD123
 X2σD13 - X2σD123 + X0στ^2D132 - X0στ^2D12 + X1
 - 2X1σD132 - X1σD13 - X1σD123 - X1σD12 - X1σDe - X0στD12 + X0στD123 \
+ X1σ + X2
 X2 - X2στ^2De + X2στ^2D13 + 2X1σD132 + X1σD13 + X1σD123 + X1σD12 + X1\
σDe - X1σ - X2
 - X1 + X1στDe - X1στD23 - X0στ^2D132 + X0στ^2D12
 2X1X2σD132 + X1X2σD13 + X1X2σD123 + X1X2σD12 + X1X2σDe - X0X2 + X0X2στ\
^2De - X0X2στ^2D13 - X1X2σ + X1X0 + X0X2
 - X1X0σD13 + X1X0σD123 - X0X2σD13 + X0X2σD123 + X0X1 - X0X1στDe + X0X1Ï\
τD23 + X1X2
 - X1X2στ^2D23 + X1X2στ^2D123 + X1X0στD13 - X1X0στD132 - X0X1στ^2D23\
 + X0X1στ^2D123
 X1X0X2σD12 - X1X0X2σDe + X0X1X2στ^2D23 - X0X1X2στ^2D123 - X0X1X0στD13\
 + X0X1X0στD132 + X1X0X2

In [1519]:
PrintNPList(RemoveAndCommuteYInYjBis(Y13bis));

 0
 σD13 - σD123
 1 - στ^2De + στ^2D13
 στD13 - στD132
 X2σD12 - X2σDe - X0στ^2D23 + X0στ^2D123
 X1σD13 - X1σD123 - X0 + X0στDe - X0στD23
 - X2στ^2D132 + X2στ^2D12 - X1σD13 + X1σD123 + X0
 - X1στD13 + X1στD132 + X0στ^2D23 - X0στ^2D123 + X2
 - X1X2σD12 + X1X2σDe - X0X2στ^2D23 + X0X2στ^2D123 + X0X1
 2X1X0σD132 + X1X0σD13 + X1X0σD123 + X1X0σD12 + X1X0σDe + 2X0X2σD132 + X\
0X2σD13 + X0X2σD123 + X0X2σD12 + X0X2σDe + X0X1στD12 - X0X1στD123 - X1\
X0σ - X0X2σ
 X1X2στ^2D132 - X1X2στ^2D12 + X1X0 - X1X0στDe + X1X0στD23 + X0X1στ^2\
D132 - X0X1στ^2D12 + X0X2
 - 2X1X0X2σD132 - X1X0X2σD13 - X1X0X2σD123 - X1X0X2σD12 - X1X0X2σDe + X0X\
1X2 - X0X1X2στ^2De + X0X1X2στ^2D13 - X0X1X0στD12 + X0X1X0στD123 + X1X0\
X2σ

In [1520]:
PrintNPList(RemoveAndCommuteYInYjBis(Y23bis));

 0
 - 2σD132 - σD13 - σD123 - σD12 - σDe + σ
 στ^2D23 - στ^2D123
 1 - στDe + στD23
 - 2X2σD132 - X2σD13 - X2σD123 - X2σD12 - X2σDe - X0 + X0στ^2De - X0σÏ\
^2D13 + X2σ
 X1σD12 - X1σDe - X0στD13 + X0στD132
 X2στ^2D23 - X2στ^2D123 - X1σD12 + X1σDe - X1
 - X1στD12 + X1στD123 + X0 - X0στ^2De + X0στ^2D13 - X0
 - X1X2σD13 + X1X2σD123 + X0X2στ^2D132 - X0X2στ^2D12
 - X1X0σD12 + X1X0σDe - X0X2σD12 + X0X2σDe + X0X1στD13 - X0X1στD132 - \
X0X2
 - X1X2 + X1X2στ^2De - X1X2στ^2D13 + X1X0στD12 - X1X0στD123 - X0X1 + X\
0X1στ^2De - X0X1στ^2D13 + X0X1
 X1X0X2σD13 - X1X0X2σD123 - X0X1X2στ^2D132 + X0X1X2στ^2D12 - X0X1X0 + X0\
X1X0στDe - X0X1X0στD23

In [1521]:
PrintNP(RemoveYterms(YtopXtop));

 3/2X1X0σY0Y1Y0X1 + X0X2σY0Y1Y0X1 - X1X2Y0Y1Y0X1 - X0X1Y0Y1Y0X1 - 1/2X2σY1Y\
0X1 + 1/2X2σY0Y1X1 + 1/2X1σY1Y0X1 + 1/2X1σY0Y2X1 - 1/2X0σY0Y2X1 + 1/2X0σY\
0Y1X1 - X2Y1Y0X1 - X2Y0Y2X1 + X0Y0Y2X2 + X0Y0Y1X1 - 3τ^2De - 1/2σY2X1 - 1/2Ï\
Y1X1 - 1/2σY0X1 - 2Y2X2 - 2Y1X1 + τD132 + τD123 - 2τDe + 1/2τ^2 - 2σD12\
 + 2σDe + 1/2σ + 2

In [1523]:
YtopXtop_res := RemoveYterms(YtopXtop);;
#YtopXtop_res := CommuteYBeforeX(RemoveYterms(YtopXtop, yIndex));;
PrintNP(YtopXtop_res);

 3/2X1X0σY0Y1Y0X1 + X0X2σY0Y1Y0X1 - X1X2Y0Y1Y0X1 - X0X1Y0Y1Y0X1 - 1/2X2σY1Y\
0X1 + 1/2X2σY0Y1X1 + 1/2X1σY1Y0X1 + 1/2X1σY0Y2X1 - 1/2X0σY0Y2X1 + 1/2X0σY\
0Y1X1 - X2Y1Y0X1 - X2Y0Y2X1 + X0Y0Y2X2 + X0Y0Y1X1 - 3τ^2De - 1/2σY2X1 - 1/2Ï\
Y1X1 - 1/2σY0X1 - 2Y2X2 - 2Y1X1 + τD132 + τD123 - 2τDe + 1/2τ^2 - 2σD12\
 + 2σDe + 1/2σ + 2

In [1524]:
YtopXtop_res2 := CommuteYBeforeX(YtopXtop_res);

[ [ [ 2, 1, 4, 12, 13, 4, 5, 5, 10 ], [ 2, 1, 4, 12, 13, 4, 5, 5, 7 ],       [ 1, 3, 4, 12, 13, 4, 5, 5, 10 ], [ 1, 3, 4, 12, 13, 4, 5, 5, 7 ],       [ 2, 3, 12, 13, 4, 5, 5, 10 ], [ 2, 3, 12, 13, 4, 5, 5, 7 ],       [ 1, 2, 12, 13, 4, 5, 5, 10 ], [ 1, 2, 12, 13, 4, 5, 5, 7 ],       [ 3, 4, 13, 4, 5, 5, 10 ], [ 3, 4, 13, 4, 5, 5, 7 ], [ 3, 4, 12 ],       [ 3, 4, 12, 4, 5, 5, 6 ], [ 3, 4, 12, 4, 5, 5, 9 ],       [ 2, 4, 13, 4, 5, 5, 10 ], [ 2, 4, 13, 4, 5, 5, 7 ],       [ 2, 4, 12, 4, 5, 5, 11 ], [ 2, 4, 12, 4, 5, 5, 8 ],       [ 1, 4, 12, 4, 5, 5, 11 ], [ 1, 4, 12, 4, 5, 5, 8 ], [ 1, 4, 12 ],       [ 1, 4, 12, 4, 5, 5, 6 ], [ 1, 4, 12, 4, 5, 5, 9 ],       [ 3, 13, 4, 5, 5, 10 ], [ 3, 13, 4, 5, 5, 7 ], [ 3, 12, 4, 5, 5, 11 ],       [ 3, 12, 4, 5, 5, 8 ], [ 1, 12 ], [ 1, 12, 4, 5, 6 ],       [ 1, 12, 4, 5, 11 ], [ 1, 12 ], [ 1, 12, 4, 5, 5, 6 ],       [ 1, 12, 4, 5, 5, 9 ], [ 5, 5, 6 ], [ 4, 4, 5, 5, 11 ],       [ 4, 4, 5, 5, 8 ], [ 4 ], [ 4, 4, 5, 5, 6 ], [ 4, 4, 5, 5, 9 ],       [ 4, 4, 5, 5, 10 ], [ 4, 4, 5, 5, 7 ], [  ], [ 4, 5, 6 ], [ 4, 5, 11 ],       [  ], [ 4, 5, 5, 6 ], [ 4, 5, 5, 9 ], [ 5, 10 ], [ 5, 8 ], [ 5, 6 ],       [ 5, 5 ], [ 4, 7 ], [ 4, 6 ], [ 4 ], [  ] ],   [ -3/2, 3/2, -1, 1, 1, -1, 1, -1, 1/2, -1/2, 1/2, -1/2, 1/2, -1/2, 1/2,       1/2, -1/2, -1/2, 1/2, 1/2, -1/2, 1/2, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1,       -3, -1/2, 1/2, -1/2, 1/2, -1/2, 1/2, -1/2, -2, 2, -2, -2, 2, -2, 1, 1,       -2, 1/2, -2, 2, 1/2, 2 ] ]

In [1526]:
subl:=[1..4];;
Print([YtopXtop_res2[1]{subl}, YtopXtop_res2[2]{subl}]);

[ [ [ 2, 1, 4, 12, 13, 4, 5, 5, 10 ], [ 2, 1, 4, 12, 13, 4, 5, 5, 7 ],
      [ 1, 3, 4, 12, 13, 4, 5, 5, 10 ], [ 1, 3, 4, 12, 13, 4, 5, 5, 7 ] ],
  [ -3/2, 3/2, -1, 1 ] ]

In [1527]:
YtopXtop_res;

[ [ [ 2, 1, 4, 12, 13, 12, 2 ], [ 1, 3, 4, 12, 13, 12, 2 ],       [ 2, 3, 12, 13, 12, 2 ], [ 1, 2, 12, 13, 12, 2 ], [ 3, 4, 13, 12, 2 ],       [ 3, 4, 12, 13, 2 ], [ 2, 4, 13, 12, 2 ], [ 2, 4, 12, 14, 2 ],       [ 1, 4, 12, 14, 2 ], [ 1, 4, 12, 13, 2 ], [ 3, 13, 12, 2 ],       [ 3, 12, 14, 2 ], [ 1, 12, 14, 3 ], [ 1, 12, 13, 2 ], [ 5, 5, 6 ],       [ 4, 14, 2 ], [ 4, 13, 2 ], [ 4, 12, 2 ], [ 14, 3 ], [ 13, 2 ],       [ 5, 10 ], [ 5, 8 ], [ 5, 6 ], [ 5, 5 ], [ 4, 7 ], [ 4, 6 ], [ 4 ],       [  ] ], [ 3/2, 1, -1, -1, -1/2, 1/2, 1/2, 1/2, -1/2, 1/2, -1, -1, 1, 1,       -3, -1/2, -1/2, -1/2, -2, -2, 1, 1, -2, 1/2, -2, 2, 1/2, 2 ] ]

In [1528]:
poly :=
    [ [ [ 2, 1, 4, 12, 13, 4, 5, 5, 7 ], 
        [ 2, 1, 4, 12, 13, 4, 5, 5, 11 ],
        [ 1, 3, 4, 12, 13, 4, 5, 5, 7 ],
        [ 1, 3, 4, 12, 13, 4, 5, 5, 11 ],
        [ 5, 9 ],
        [3] ], 
      [ 3/2, -3/2, 1, -1 , 3, -1 ] ];;

In [1529]:
PrintNP(poly);

 3/2X1X0σY0Y1στ^2D12 - 3/2X1X0σY0Y1στ^2D23 + X0X2σY0Y1στ^2D12 - X0X2Ï\
Y0Y1στ^2D23 + 3τD13 - X2

In [1530]:
FilterMonomials := function(poly, elemIndex)
    local monomials, coeffs, newmons, newcoeffs, i, mon, hasY;

    monomials := poly[1];
    coeffs    := poly[2];

    newmons   := [];
    newcoeffs := [];

    for i in [1 .. Length(monomials)] do
        mon := monomials[i];

        # Verifica si aparece alguna Y
        hasY := ForAny(mon, x -> x in elemIndex);

        # Si NO tiene Y's, lo conservamos
        if not hasY then
            Add(newmons, mon);
            Add(newcoeffs, coeffs[i]);
        fi;
    od;

    return [ newmons, newcoeffs ];
end;

function( poly, elemIndex ) ... end

In [1531]:
poly_filter:=FilterMonomials(poly, yIndex);

[ [ [ 5, 9 ], [ 3 ] ], [ 3, -1 ] ]

In [1532]:
PrintNP(poly_filter);

 3τD13 - X2

In [1533]:
YtopXtop_filter := FilterMonomials(YtopXtop_res2, yIndex);

[ [ [ 5, 5, 6 ], [ 4, 4, 5, 5, 11 ], [ 4, 4, 5, 5, 8 ], [ 4 ],       [ 4, 4, 5, 5, 6 ], [ 4, 4, 5, 5, 9 ], [ 4, 4, 5, 5, 10 ],       [ 4, 4, 5, 5, 7 ], [  ], [ 4, 5, 6 ], [ 4, 5, 11 ], [  ],       [ 4, 5, 5, 6 ], [ 4, 5, 5, 9 ], [ 5, 10 ], [ 5, 8 ], [ 5, 6 ],       [ 5, 5 ], [ 4, 7 ], [ 4, 6 ], [ 4 ], [  ] ],   [ -3, -1/2, 1/2, -1/2, 1/2, -1/2, 1/2, -1/2, -2, 2, -2, -2, 2, -2, 1, 1,       -2, 1/2, -2, 2, 1/2, 2 ] ]

In [1534]:
PrintNP(YtopXtop_filter);

 - 3τ^2De - 1/2σ^2τ^2D23 + 1/2σ^2τ^2D123 - 1/2σ + 1/2σ^2τ^2De - 1/2σ^\
2τ^2D13 + 1/2σ^2τ^2D132 - 1/2σ^2τ^2D12 - 2 + 2στDe - 2στD23 - 2 + 2σ\
τ^2De - 2στ^2D13 + τD132 + τD123 - 2τDe + 1/2τ^2 - 2σD12 + 2σDe + 1/2\
σ + 2

In [1535]:
Length(YtopXtop_filter[1]);

22

In [1536]:
prod_test := StrongNormalFormNP(YtopXtop_filter, J_D_ge_0);

[ [ [ 5, 5, 10 ], [ 5, 5, 8 ], [ 5, 5, 6 ], [ 5, 4, 9 ], [ 5, 4, 6 ],       [ 4, 5, 10 ], [ 4, 5, 9 ], [ 4, 5, 8 ], [ 4, 5, 7 ], [ 4, 5, 6 ],       [ 5, 10 ], [ 5, 8 ], [ 5, 6 ], [ 4, 7 ], [ 4, 6 ], [ 4, 5 ], [  ] ],   [ 1, 1, -2, -2, 2, 2, 2, 2, 2, 4, 1, 1, -2, -2, 2, -2, -2 ] ]

In [1537]:
PrintNP(prod_test);

 τ^2D132 + τ^2D123 - 2τ^2De - 2τσD13 + 2τσDe + 2στD132 + 2στD13 + 2\
στD123 + 2στD12 + 4στDe + τD132 + τD123 - 2τDe - 2σD12 + 2σDe - 2σ\
τ - 2

In [1538]:
PrintNP(FilterMonomials(prod_test, [7..10]));

 - 2τ^2De + 2τσDe + 4στDe - 2τDe + 2σDe - 2στ - 2

# The simple Verma modules

Let us take the expression
$$
\Omega := -2\tau^2\delta_e + 2\tau\sigma\delta_e + 4\sigma\tau\delta_e - 2\tau\delta_e + 2\sigma\delta_e - 2\sigma\tau - 2
4$$. 
Since $\delta_e$ acts as the identity in all cases, we can formally replace
$$
\delta_e \mapsto I.
$$ 
Then
$$
\Omega = -2\tau^2 + 2\tau\sigma + 4\sigma\tau - 2\tau + 2\sigma - 2\sigma\tau - 2.
$$
Grouping:
$$
\Omega = -2\tau^2 + 2\tau\sigma + 2\sigma\tau - 2\tau + 2\sigma - 2.
$$
We will use:
$$
\sigma = (12), \quad \tau = (123).
$$
In $\mathbb{S}_3$,
$$
\tau^2 = (132),
$$
and furthermore
\begin{align*}
\tau\sigma &= (123)(12) = (13), \\
\sigma\tau &= (12) (123) = (23).
\end{align*}
Therefore,
$$
\Omega = -2(132) + 2(13) + 2(23) - 2(123) + 2(12) - 2e.
$$

## The Verma modules $\mathrm{M}(e, +)$ isn't $\mathfrak{D}$-simple.

- 1) trivial representation on $|e\rangle_{+}$

The trivial representation satisfies
$$
\varepsilon(\text{transposition}) = 1, \quad \varepsilon(\text{3-cycle}) = 1.
$$

Then:
\begin{align*}
\varepsilon(\tau) = 1, \quad \varepsilon(\tau^2) = 1, \\
\varepsilon(\sigma) = 1, \quad \varepsilon(\tau\sigma) = 1, \quad \varepsilon(\sigma\tau) = 1.
\end{align*}
We apply this term by term:
\begin{align*}
-2\tau^2 &\mapsto -2(1) = -2, \\
2\tau\sigma &\mapsto 2(1) = 2, \\
2\sigma\tau &\mapsto 2(1) = 2, \\
-2\tau &\mapsto -2(1) = -2, \\
2\sigma &\mapsto 2(1) = 2, \\
-2e &\mapsto -2.
\end{align*}
Adding up:
$$
-2 + 2 + 2 - 2 + 2 - 2 = 0.
$$
Therefore,
$$
\Omega|e\rangle_{+} = 0 |e\rangle_{-} = 0.
$$

# Algoritmo fuerte

In [1540]:
all_elms_G := GetElementsOfG();;
all_deltas := List(GetElementsOfG(), x -> DeltaFunctionForSDP(x));;

In [1541]:
all_deltas;

[ function( elm2 ) ... end, function( elm2 ) ... end,   function( elm2 ) ... end, function( elm2 ) ... end,   function( elm2 ) ... end, function( elm2 ) ... end ]

In [1542]:
simpleM := GetSimplesModAttachedToElement(G, One(G), allPairsInG)[1];

rec( G := "S3", Gamma_g := "S3", base := [ (( 0 , 0 )) ⊗ [ 1 ] ], generatorsofgroup := [ f1, f2 ], genimages := [ [ [ 1 ] ], [ [ 1 ] ] ], group := Group( [ f1, f2 ] ), isSimple := true, simple := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ], weight := rec( g := <identity> of ..., rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ), weightSDP := rec( g := ( 0 , 0 ), rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ) )

In [1543]:
simpleM.base;

[ (( 0*Z(3) , 0 )) ⊗ [ 1 ] ]

In [1544]:
simpleM.weight.rho;

[ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ]

In [1545]:
A1 := simpleM.simple(G.1);

[ [ 1 ] ]

In [1546]:
A2 := simpleM.simple(G.2);

[ [ 1 ] ]

In [1547]:
Print(Conj4Basis(simpleM));

[ ( 0 , 0 ) ]

In [1553]:
DeltasForG            := List( GetElementsOfG(), x -> DeltaFunctionForSDP(x) );;
delta_mat_for_simpleM := List( DeltasForG, D_h -> StructureMatrixSimpleModule( D_h, simpleM ).matrix);;
gens_mat_for_simpleM  := List( GeneratorsOfGroup( G ), simpleM.simple);;
dimM                  := Length( simpleM.base );;
mats                  := List( [1..nX], i -> NullMat(dimM, dimM) );;
list_mat_in_DG        := Concatenation(mats, gens_mat_for_simpleM, delta_mat_for_simpleM);;

In [1554]:
Y0_matrix:=MatrixActionYiOnNicholsBasis(Y12bis, simpleM, Base_FK3, list_mat_in_DG);

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [1556]:
IsZero(Y0_matrix);
IsZero(Y0_matrix^2);

false

true

In [1557]:
Y1_matrix:=MatrixActionYiOnNicholsBasis(Y13bis, simpleM, Base_FK3, list_mat_in_DG);

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [1559]:
IsZero(Y1_matrix);
IsZero(Y1_matrix^2);

false

true

In [1560]:
Y2_matrix:=MatrixActionYiOnNicholsBasis(Y23bis, simpleM, Base_FK3, list_mat_in_DG);

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

In [1562]:
IsZero(Y2_matrix);
IsZero(Y2_matrix^2);

false

true

In [1562]:
Print("Y0Y2 + Y2Y1 + Y1Y0 = 0 es ", IsZero(Y0_matrix * Y2_matrix + Y2_matrix * Y1_matrix + Y1_matrix * Y0_matrix ), "\n" );
Print("Y2Y0 + Y1Y2 + Y0Y1 = 0 es ", IsZero(Y2_matrix * Y0_matrix + Y1_matrix * Y2_matrix + Y0_matrix * Y1_matrix ) );

Y0Y2 + Y2Y1 + Y1Y0 = 0 es true
Y2Y0 + Y1Y2 + Y0Y1 = 0 es true

In [1565]:
gensA;

[ 0*Z(3), Z(3)^0, Z(3) ]

In [1566]:
DeltaFromRelations(gensDeltas[2], Base_FK3[1], Base_FK3);

( 0*Z(3) , 1 )

In [1568]:
Nm := Length( Base_FK3 ) * Length( simpleM.base );;
List( List( gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3)), D -> D * D - D = NullMat( Nm, Nm ) );

[ true, true, true, true, true, true ]

In [1569]:
for i in List(gensDeltas, Dg->DeltaMatForReps(Dg, simpleM, Base_FK3)) do
    for j in List(gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3)) do 
        if i = j then
            Print(i * j - i = NullMat(Nm, Nm), "\n");
        else
            Print(IsZero(i*j), "\n" ) ;
        fi;
    od;
od;

true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true
true

In [1570]:
Trace(Sum(List(gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3))));

12

In [1571]:
Trace(Sum(List(gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3))))=Nm;

true

In [1572]:
IsOne(Sum(List(gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3))));

true

In [1573]:
ForAny(List(gensDeltas, Dg -> DeltaMatForReps(Dg, simpleM, Base_FK3)), IsZero);

false

In [1579]:
De_matrix   := DeltaMatForReps(gensDeltas[1], simpleM, Base_FK3);
D12_matrix  := DeltaMatForReps(gensDeltas[2], simpleM, Base_FK3);
D123_matrix := DeltaMatForReps(gensDeltas[3], simpleM, Base_FK3);
D13_matrix  := DeltaMatForReps(gensDeltas[4], simpleM, Base_FK3);
D132_matrix := DeltaMatForReps(gensDeltas[5], simpleM, Base_FK3);
D23_matrix  := DeltaMatForReps(gensDeltas[6], simpleM, Base_FK3);

[ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ]

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ]

# Matrices de $\mathfrak{B}(V)$

In [1581]:
X12ActionOnBaseFK3 := List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X12),  bi ), J_FK3));;
PrintNPList(X12ActionOnBaseFK3);

 X0
 0
 X0X1
 X0X2
 0
 0
 X0X1X0
 X0X1X2
 0
 0
 X0X1X0X2
 0

In [1583]:
X13ActionOnBaseFK3:=List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X13),  bi ), J_FK3));;
PrintNPList(X13ActionOnBaseFK3);

 X1
 X1X0
 0
 X1X2
 X0X1X0
 X1X0X2
 0
 0
 0
 X0X1X0X2
 0
 0

In [1585]:
X23ActionOnBaseFK3:=List(Base_FK3, bi-> StrongNormalFormNP( MulNP( GP2NP(X23),  bi ), J_FK3));;
PrintNPList(X23ActionOnBaseFK3);

 X2
 - X1X2 - X0X1
 - X1X0 - X0X2
 0
 X1X0X2
 - X0X1X2
 X0X1X2
 - X1X0X2
 - X0X1X0X2
 0
 0
 0

In [1587]:
X0_matrix := DirectSumMat(List([1..Length(simpleM.base)], i -> StructureMatrixForXi(X12ActionOnBaseFK3, Base_FK3)));;
Display(X0_matrix);

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0 ] ]

In [1589]:
X1_matrix := DirectSumMat(List([1..Length(simpleM.base)], i -> StructureMatrixForXi(X13ActionOnBaseFK3, Base_FK3)));;
Display(X1_matrix);

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ] ]

In [1591]:
X2_matrix := DirectSumMat(List([1..Length(simpleM.base)], i -> StructureMatrixForXi(X23ActionOnBaseFK3, Base_FK3)));;
Display(X2_matrix);

[ [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,  -1,   1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   1,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0 ] ]

In [1594]:
IsZero(X0_matrix - KroneckerProduct(IdentityMat(Length(simpleM.base)), StructureMatrixForXi(X12ActionOnBaseFK3, Base_FK3)));
IsZero(X1_matrix - KroneckerProduct(IdentityMat(Length(simpleM.base)), StructureMatrixForXi(X13ActionOnBaseFK3, Base_FK3)));
IsZero(X2_matrix - KroneckerProduct(IdentityMat(Length(simpleM.base)), StructureMatrixForXi(X23ActionOnBaseFK3, Base_FK3)));

true

true

true

In [1597]:
IsZero(X0_matrix^2); 
IsZero(X1_matrix^2); 
IsZero(X2_matrix^2);

true

true

true

In [1599]:
IsZero(X2_matrix * X1_matrix + X1_matrix * X0_matrix + X0_matrix * X2_matrix); 
IsZero(X2_matrix * X0_matrix + X1_matrix * X2_matrix + X0_matrix * X1_matrix);

true

true

# Matrces de G

In [1603]:
gensG                       := GP2NPList([ F1, F2 ]);;
inv_gensG                   := GP2NPList([ F1, F2^2 ]);; # validar la lista
F1ConjugationOnNicholsBasis := List(Base_FK3, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[1], bi), inv_gensG[1]), J_D_ge_0));
F2ConjugationOnNicholsBasis := List(Base_FK3, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[2], bi), inv_gensG[2]), J_D_ge_0));

[ [ [ [  ] ], [ 1 ] ], [ [ [ 1 ] ], [ -1 ] ], [ [ [ 3 ] ], [ -1 ] ],   [ [ [ 2 ] ], [ -1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2 ] ], [ 1 ] ],   [ [ [ 2, 3 ], [ 1, 2 ] ], [ -1, -1 ] ],   [ [ [ 2, 1 ], [ 1, 3 ] ], [ -1, -1 ] ], [ [ [ 1, 2, 3 ] ], [ 1 ] ],   [ [ [ 1, 2, 1 ] ], [ 1 ] ], [ [ [ 2, 1, 3 ] ], [ -1 ] ],   [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

[ [ [ [  ] ], [ 1 ] ], [ [ [ 3 ] ], [ 1 ] ], [ [ [ 1 ] ], [ 1 ] ],   [ [ [ 2 ] ], [ 1 ] ], [ [ [ 2, 3 ], [ 1, 2 ] ], [ -1, -1 ] ],   [ [ [ 2, 1 ], [ 1, 3 ] ], [ -1, -1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ],   [ [ [ 1, 2 ] ], [ 1 ] ], [ [ [ 1, 2, 3 ] ], [ -1 ] ],   [ [ [ 2, 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2, 1 ] ], [ -1 ] ],   [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

In [1604]:
Ms_matrix := KroneckerProduct(simpleM.simple(G.1), StructureMatrixOfG(F1ConjugationOnNicholsBasis, Base_FK3));

[ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ]

In [1605]:
Mt_matrix := KroneckerProduct(simpleM.simple(G.2), StructureMatrixOfG(F2ConjugationOnNicholsBasis, Base_FK3));

[ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ]

In [1608]:
IsOne(Ms_matrix^2);                                         # 1    F1^2-e,            
IsOne(Mt_matrix^3);                                         # 2    F2^2-e,            
IsZero(Ms_matrix*Mt_matrix*Ms_matrix-Mt_matrix^2);

true

true

true

In [1609]:
all_matrix_rep := [
    X0_matrix,
    X1_matrix,
    X2_matrix,
    Ms_matrix,
    Mt_matrix,
    De_matrix,
    D12_matrix,
    D123_matrix,
    D13_matrix,
    D132_matrix,
    D23_matrix,
    Y0_matrix,
    Y1_matrix,
    Y2_matrix
];

[ [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1610]:
Length(Filtered(List(relsxBos, rel->IsZero(EvalLinearCombination(rel, all_matrix_rep ))), x -> x = true));

18

In [1611]:
Length(Filtered(List(relsDx, rel->IsZero(EvalLinearCombination(rel, all_matrix_rep ))), x -> x = true));

18

In [1612]:
Length(Filtered(List(relsyBos, rel->IsZero(EvalLinearCombination(rel, all_matrix_rep ))), x -> x = true));

18

In [1613]:
Length(Filtered(List(relsDy, rel->IsZero(EvalLinearCombination(rel, all_matrix_rep ))), x -> x = true));

18

In [1614]:
Length(List(List(List(Cartesian([1..nX], [1..nX])), x -> GetConmutationRules(
    gensA[x[1]],
    gensA[x[1]]
    )), rule -> IsZero(EvalLinearCombination(rule, all_matrix_rep ))));

9

In [1616]:
F := CF(6);
D := AlgebraWithOne( F, all_matrix_rep );

CF(3)

In [1617]:
Nm;

12

In [1618]:
L := LeftAlgebraModule(D, \*, F^Nm );

In [1619]:
Dimension(L);

12

In [1620]:
Basis(L);

Basis( <12-dimensional left-module over <algebra-with-one over CF(3), with 14 generators>>, [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ] )

In [1622]:
S := SubAlgebraModule( L, List([1..Length(simpleM.base)], i -> BasisVectors( Basis( L ) )[Length(Base_FK3) * i]) );
Dimension( S );

1

In [1623]:
NicholsGradingData := [
    rec( graded_i := 0, dimBi := 1 ),
    rec( graded_i := 1, dimBi := 3 ),
    rec( graded_i := 2, dimBi := 4 ),
    rec( graded_i := 3, dimBi := 3 ),
    rec( graded_i := 4, dimBi := 1 )
];

[ rec( dimBi := 1, graded_i := 0 ), rec( dimBi := 3, graded_i := 1 ),   rec( dimBi := 4, graded_i := 2 ), rec( dimBi := 3, graded_i := 3 ),   rec( dimBi := 1, graded_i := 4 ) ]

In [1624]:
verma_data := QGNAG_HSData( L, simpleM, Base_FK3, NicholsGradingData );

rec( HScoeffs := [ rec( count := 0, graded_i := 0 ), rec( count := 0, graded_i := 1 ), rec( count := 0, graded_i := 2 ), rec( count := 0, graded_i := 3 ), rec( count := 1, graded_i := 4 ) ], Socle := <object>, VermaModule := <object> )

In [1625]:
Sum( List( verma_data.HScoeffs, x -> x.count ) );

1

In [1626]:
QGNAG_PrintHS( verma_data );

 Hilbert polynomial: H(t) = t^4.

The relation is a direct consequence of Schur's Lemma.

Given the decomposition $M \cong \bigoplus_{j=1}^n S_j^{\oplus t_j}$, applying the left-exact functor $\operatorname{Hom}_A(S_i, -)$ yields an isomorphism of vector spaces over the base field $k$:

$$\operatorname{Hom}_A(S_i, M) \cong \bigoplus_{j=1}^n \operatorname{Hom}_A(S_i, S_j)^{\oplus t_j}$$

Because the modules $\{S_1, \dots, S_n\}$ are irreducible and mutually non-isomorphic, Schur's Lemma dictates that $\operatorname{Hom}_A(S_i, S_j) = 0$ whenever $i \neq j$. Consequently, all cross-terms vanish, leaving:

$$\operatorname{Hom}_A(S_i, M) \cong \operatorname{Hom}_A(S_i, S_i)^{\oplus t_i}$$

By Schur's Lemma, $\operatorname{Hom}_A(S_i, S_i)$ is a division algebra over $k$. Taking dimensions over $k$ gives the explicit formula for the multiplicity $t_i$:

$$t_i = \frac{\dim_k \operatorname{Hom}_A(S_i, M)}{\dim_k \operatorname{Hom}_A(S_i, S_i)}$$

If the base field $k$ is algebraically closed, $\operatorname{Hom}_A(S_i, S_i) \cong k$, making its dimension $1$. In this case, the relation reduces entirely to:

$$t_i = \dim_k \operatorname{Hom}_A(S_i, M)$$

In [1635]:
# ================================
#   Fin del código principal
# ================================

t1 := NanosecondsSinceEpoch();;

# Calcular duración en segundos
dur := (t1 - t0) / 1000000000.0;;

# Convertir a horas, minutos y segundos
horas := Int(dur / 3600);;
minutos := Int((dur - horas * 3600) / 60);;
segundos := Round(dur - horas * 3600 - minutos * 60);;

# Mostrar resultado
Print("\n=====================================\n");
Print("Tiempo total de ejecución:\n");
Print(String(horas), " horas, ", String(minutos), " minutos, ", String(segundos), " segundos.\n");
Print("=====================================\n");

=====================================
Tiempo total de ejecución:
0 horas, 0 minutos, 34. segundos.
=====================================

In [1638]:
mem_kb := MemoryUsageByGAPinKbytes();;
mem_gb := mem_kb / (1024.0 * 1024.0);;
Print("Memoria usada por GAP: ", mem_gb, " GB\n");

Memoria usada por GAP: 4.125358581542969 GB

In [1639]:
verma_char := QGNAG_Character( L, simpleM, Base_FK3, NicholsGradingData );

rec( GradedBasis := rec( 0 := [  ], 1 := [  ], 2 := [  ], 3 := [  ], 4 := [ <object> ] ), HScoeffs := [ rec( count := 0, graded_i := 0 ), rec( count := 0, graded_i := 1 ), rec( count := 0, graded_i := 2 ), rec( count := 0, graded_i := 3 ), rec( count := 1, graded_i := 4 ) ], Socle := <object>, VermaModule := <object> )

In [1640]:
all_matrix_rep_DG := [
    # Group Algebra Matrices
    Ms_matrix,
    Mt_matrix,
    # Group Algebra dual Matrices
    De_matrix,
    D12_matrix,
    D123_matrix,
    D13_matrix,
    D132_matrix,
    D23_matrix
];

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1643]:
record_data_decomp  := [];;
SimplesMn  := [];;
AllMatricesByDegree := QGNAG_AllMatricesByDegree( verma_char, all_matrix_rep_DG );;

In [1645]:
SimplesModAttachedToOne := GetSimplesModAttachedToElement(G, One(G), allPairsInG);
for s in SimplesModAttachedToOne do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, AllMatricesByDegree );
    Add(record_data_decomp, decomp_char_s);
    Add(SimplesMn, s);
od;

[ rec( G := "S3", Gamma_g := "S3", base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ], genimages := [ [ [ 1 ] ], [ [ 1 ] ] ],       group := S3, isSimple := true,       simple := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] -> [ [ [ 1 ] ], [ [ 1 ] ] ] ) ),   rec( G := "S3", Gamma_g := "S3", base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ], genimages := [ [ [ -1 ] ], [ [ 1 ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] -> [ [ [ -1 ] ], [ [ 1 ] ] ] ) ),   rec( G := "S3", Gamma_g := "S3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 0, 1 ], (( 0*Z(3) , 0 )) ⊗ [ 1, 0 ] ]        , generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],       weight :=         rec( g := <identity> of ...,           rho := [ f1, f2 ] ->             [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ] ),       weightSDP :=         rec( g := ( 0*Z(3) , 0 ),           rho := [ f1, f2 ] ->             [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ] ) ) ]

In [1647]:
SimplesModAttachedToSigma := GetSimplesModAttachedToElement(G, G.1, allPairsInG);
for s in SimplesModAttachedToSigma do
    gens          := GeneratorsOfGroup(G);;
    mgens         := List(gens, x-> s.simple(x)^-1);
    s.simple      := GroupHomomorphismByImages( G, Group( mgens ), gens, mgens );
    s.gensimages  := mgens;
    DGActMat      := QGNAG_DGActionMatrices( s, allPairsInG,  Base_FK3 );
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, AllMatricesByDegree );
    Add(record_data_decomp, decomp_char_s);
    Add(SimplesMn, s);
od;

[ rec( G := "S3", Gamma_g := "C2",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( Z(3)^0 , 0 )) ⊗ [ 1 ],           (( Z(3) , 0 )) ⊗ [ 1 ] ], generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ] ],       gensimages := [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ], group := S3,       isSimple := true,       simple := [ f1, f2 ] -> [ [ [ 1, 0, 0 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ],       weight := rec( g := f1, rho := [ f1 ] -> [ [ [ 1 ] ] ] ),       weightSDP := rec( g := ( 0*Z(3) , 1 ), rho := [ f1 ] -> [ [ [ 1 ] ] ] )      ),   rec( G := "S3", Gamma_g := "C2",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( Z(3)^0 , 0 )) ⊗ [ 1 ],           (( Z(3) , 0 )) ⊗ [ 1 ] ], generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ] ],       gensimages := [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ], group := S3,       isSimple := true,       simple := [ f1, f2 ] -> [ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],           [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ] ],       weight := rec( g := f1, rho := [ f1 ] -> [ [ [ -1 ] ] ] ),       weightSDP := rec( g := ( 0*Z(3) , 1 ), rho := [ f1 ] -> [ [ [ -1 ] ] ]          ) ) ]

In [1649]:
SimplesModAttachedToTau := GetSimplesModAttachedToElement(G, G.2, allPairsInG);
for s in SimplesModAttachedToTau do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, AllMatricesByDegree );
    Add(record_data_decomp, decomp_char_s);
    Add(SimplesMn, s);
od;

[ rec( G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ 1, 0 ], [ 0, 1 ] ] ],       group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ 1, 0 ], [ 0, 1 ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ 1 ] ] ] ),       weightSDP := rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ 1 ] ] ] )      ),   rec( G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3), 0 ], [ 0, E(3)^2 ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3), 0 ], [ 0, E(3)^2 ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ E(3) ] ] ] ),       weightSDP :=         rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ E(3) ] ] ] ) ),   rec( G := "S3", Gamma_g := "C3",       base := [ (( 0*Z(3) , 0 )) ⊗ [ 1 ], (( 0*Z(3) , 1 )) ⊗ [ 1 ] ],       generatorsofgroup := [ f1, f2 ],       genimages := [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],      group := S3, isSimple := true,       simple := [ f1, f2 ] ->         [ [ [ 0, 1 ], [ 1, 0 ] ], [ [ E(3)^2, 0 ], [ 0, E(3) ] ] ],       weight := rec( g := f2, rho := [ f2 ] -> [ [ [ E(3)^2 ] ] ] ),       weightSDP :=         rec( g := ( Z(3)^0 , 0 ), rho := [ f2 ] -> [ [ [ E(3)^2 ] ] ] ) ) ]

In [1650]:
rec_info := QGNAG_Decomposition(record_data_decomp);;

In [1651]:
QGNAG_PrintDecomposition(rec_info);

degree 4 = M1

In [1652]:
QGNAG_CharacterSummary(rec_info, SimplesMn);

 Char(t) = M1[4]

 SUMMARY:

==================================================
Degree 4
==================================================
-------------------
Simple M1
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1661]:
SimpleNames    := [ ];;
SimpleNames[1] := "M(e,+)";;
SimpleNames[2] := "M(e,-)";;
SimpleNames[3] := "M(e,\\rho)";;
SimpleNames[4] := "M(\\sigma,+)";;
SimpleNames[5] := "M(\\sigma,-)";;
SimpleNames[6] := "M(\\tau,0)";;
SimpleNames[7] := "M(\\tau,1)";;
SimpleNames[8] := "M(\\tau,2)";;

In [1662]:
QGNAG_CharacterSummaryLaTeX(rec_info, SimplesMn, SimpleNames);
# L(e, +) = M (e, +) as D(S3)-modules and dim L(e, +) = 1, Corollary 27.

\operatorname{Char}(t) = M(e,+)[4]



==================================================
Degree 4
==================================================
-------------------
Simple M(e,+)
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1663]:
QGNAG_HilbertSeriesToLaTeX( "hilbert.tex", verma_char );

In [1664]:
QGNAG_CharacterSummaryToLaTeX( "character.tex", rec_info, SimpleNames );

## Coproducto

In [1665]:
List([1..Length(GeneratorsOfGroup(G))], x->[[1]]);

[ [ [ 1 ] ], [ [ 1 ] ] ]

In [1666]:
QGNAG_Coproduct:=function(g, groupElems)
    local relsxBos, h, pos_h, h_index, pos_j, action, chi_j_h,
          pos_action, leftMon, rightMon;

    relsxBos := [];;
    # Iterate over all elements g in the group structure
    for h in groupElems do
        action    := h * ElementFq( j ); # Compute the action of the group element on the field component of j
        pos_action := Position( QGNAG.Config.gensA, action!.FieldPart );
        pos_j     := Position( QGNAG.Config.gensA, j );
        chi_j_h   := ChiForSemidirectProduct( h ); # Compute the $\chi_{j}(g)$ factor for the semidirect product
        pos_h     := Position( QGNAG.Config.elmsG, h );
        h_index   := QGNAG.Config.groupIndex[pos_h];
        #Print("QGNAG.Config.groupIndex: ", QGNAG.Config.groupIndex[pos_g], "\n" );
        if pos_action <> fail then
            leftMon  := Concatenation( h_index, [ QGNAG.Config.xIndex[pos_j] ] );     # Construct the monomials: g * x_j           
            rightMon := Concatenation( [ QGNAG.Config.xIndex[pos_action] ], h_index ); # Construct the transformed monomials: x_{g * j} * g
            Add(relsxBos, [ [ leftMon, rightMon ], [1, -chi_j_h] ] );    # Add the relation in the form: leftMon - chi_j_g * rightMon = 0
        fi;
    od;
    return relsxBos;
end;

function( g, groupElems ) ... end

In [1669]:
X12 := gensX[1][1][1][1];
X13 := gensX[2][1][1][1];
X23 := gensX[3][1][1][1];

1

2

3

In [1670]:
for ps in Base_FK3 do
    PrintNP(ps);
    Print(ps);
    mon := ps[1];
    coe := ps[2];
    #Print(mon);
    Print("\n", coe, "\n");
od;

 1
[ [ [  ] ], [ 1 ] ]
[ 1 ]
 X0
[ [ [ 1 ] ], [ 1 ] ]
[ 1 ]
 X1
[ [ [ 2 ] ], [ 1 ] ]
[ 1 ]
 X2
[ [ [ 3 ] ], [ 1 ] ]
[ 1 ]
 X0X1
[ [ [ 1, 2 ] ], [ 1 ] ]
[ 1 ]
 X0X2
[ [ [ 1, 3 ] ], [ 1 ] ]
[ 1 ]
 X1X0
[ [ [ 2, 1 ] ], [ 1 ] ]
[ 1 ]
 X1X2
[ [ [ 2, 3 ] ], [ 1 ] ]
[ 1 ]
 X0X1X0
[ [ [ 1, 2, 1 ] ], [ 1 ] ]
[ 1 ]
 X0X1X2
[ [ [ 1, 2, 3 ] ], [ 1 ] ]
[ 1 ]
 X1X0X2
[ [ [ 2, 1, 3 ] ], [ 1 ] ]
[ 1 ]
 X0X1X0X2
[ [ [ 1, 2, 1, 3 ] ], [ 1 ] ]
[ 1 ]

In [1678]:
pol   := [ [ [ 2 ] ], [ 1 ] ];PrintNP(pol);
mon   := pol[1];
Lt    := List(QGNAG.Config.gensA, ElementFq);
PolG2 := [[List(mon[1], m -> Position(Lt, QGNAG.Config.elmsG[Position( allPairsInG, G.2 )] * QGNAG.Config.gensA[m]))],[1]];
PrintNP(PolG2);
PrintNP(StrongNormalFormNP(PolG2, J_FK3));
PrintNPList(Base_FK3);

 X1
 X0
 X0
 1
 X0
 X1
 X2
 X0X1
 X0X2
 X1X0
 X1X2
 X0X1X0
 X0X1X2
 X1X0X2
 X0X1X0X2

[ [ [ 2 ] ], [ 1 ] ]

[ [ 2 ] ]

[ 0*Z(3), Z(3)^0, Z(3) ]

[ [ [ 1 ] ], [ 1 ] ]

In [1680]:
Amat:=NullMat(Length(Base_FK3), Length(Base_FK3));
for bj in [1..Length(Base_FK3)] do
    pol   := Base_FK3[bj];
    PrintNP(pol);
    mon   := pol[1];
    Lt    := List(QGNAG.Config.gensA, ElementFq);
    genGi := QGNAG.Config.elmsG[Position( allPairsInG, G.2^-1 )];
    PolG2 := [[List(mon[1], m -> Position(Lt, genGi * QGNAG.Config.gensA[m]))],[1]];
    PrintNP(PolG2);
    PolG2Norm := StrongNormalFormNP(PolG2, J_FK3);
    PrintNP(PolG2Norm);
    Print("Position: ", List(PolG2Norm[1], tx -> Position(Base_FK3, [[tx], [1]])), "\n");
    Print("Coeff: ", PolG2Norm[2] * ChiForSemidirectProduct( genGi )^Length(pol[1][1]), "\n");
    coeffss:=PolG2Norm[2] * ChiForSemidirectProduct( genGi )^Length(pol[1][1]);
    pos:=List(PolG2Norm[1], tx -> Position(Base_FK3, [[tx], [1]]));
    for bi in pos do;
        Amat[bi][bj] := coeffss[Position(pos, bi)];
    od;
    #Print("ChiForSemidirectProduct: ", ChiForSemidirectProduct( genGi )^Length(pol[1][1]), "\n");
    #PrintNPList(Base_FK3);
od;

 1
 1
 1
Position: [ 1 ]
Coeff: [ 1 ]
 X0
 X1
 X1
Position: [ 3 ]
Coeff: [ 1 ]
 X1
 X2
 X2
Position: [ 4 ]
Coeff: [ 1 ]
 X2
 X0
 X0
Position: [ 2 ]
Coeff: [ 1 ]
 X0X1
 X1X2
 X1X2
Position: [ 8 ]
Coeff: [ 1 ]
 X0X2
 X1X0
 X1X0
Position: [ 7 ]
Coeff: [ 1 ]
 X1X0
 X2X1
 - X1X0 - X0X2
Position: [ 7, 6 ]
Coeff: [ -1, -1 ]
 X1X2
 X2X0
 - X1X2 - X0X1
Position: [ 8, 5 ]
Coeff: [ -1, -1 ]
 X0X1X0
 X1X2X1
 - X1X0X2
Position: [ 11 ]
Coeff: [ -1 ]
 X0X1X2
 X1X2X0
 - X0X1X0
Position: [ 9 ]
Coeff: [ -1 ]
 X1X0X2
 X2X1X0
 X0X1X2
Position: [ 10 ]
Coeff: [ 1 ]
 X0X1X0X2
 X1X2X1X0
 X0X1X0X2
Position: [ 12 ]
Coeff: [ 1 ]

[ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ]

In [1681]:
ActionMatrixByGenerator := function( BaseNichols, J_Nichols, gen )
    local N, Amat, Lt, genGi, bj, pol, mon, PolG2, PolG2Norm, pos, coeffss, bi;
    N := Length(BaseNichols);
    Amat := NullMat(N, N);
    # Precálculos fuera del bucle
    Lt := List(QGNAG.Config.gensA, ElementFq);
    genGi := QGNAG.Config.elmsG[Position( allPairsInG, gen )];
    for bj in [1..N] do
        pol := BaseNichols[bj];
        mon := pol[1];
        PolG2     := [[List(mon[1], m -> Position(Lt, genGi * QGNAG.Config.gensA[m]))], [1]];
        PolG2Norm := StrongNormalFormNP(PolG2, J_Nichols);
        pos       := List(PolG2Norm[1], tx -> Position(BaseNichols, [[tx], [1]]));
        coeffss   := PolG2Norm[2] * ChiForSemidirectProduct( genGi )^Length(pol[1][1]);
        for bi in pos do
            Amat[bi][bj] := coeffss[Position(pos, bi)];
        od;
    od;
    return Amat;
end;

function( BaseNichols, J_Nichols, gen ) ... end

In [1682]:
Display(ActionMatrixByGenerator(Base_FK3, J_FK3, G.1));

[ [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   1,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   1,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1 ] ]

In [1683]:
Display(ActionMatrixByGenerator(Base_FK3, J_FK3, G.2));

[ [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,  -1,   0,   0,   1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,  -1,   1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1 ] ]

In [1684]:
Display(Amat);

[ [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   1,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   1,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1 ] ]

In [1685]:
Print(Base_FK3);

[ [ [ [  ] ], [ 1 ] ], [ [ [ 1 ] ], [ 1 ] ], [ [ [ 2 ] ], [ 1 ] ],
  [ [ [ 3 ] ], [ 1 ] ], [ [ [ 1, 2 ] ], [ 1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ],
  [ [ [ 2, 1 ] ], [ 1 ] ], [ [ [ 2, 3 ] ], [ 1 ] ],
  [ [ [ 1, 2, 1 ] ], [ 1 ] ], [ [ [ 1, 2, 3 ] ], [ 1 ] ],
  [ [ [ 2, 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

In [1686]:
PrintNPList(J_FK3);

 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2X1 + X1X0 + X0X2
 X2^2
 X1X0X1 - X0X1X0

In [1687]:
PrintNPList(Base_FK3);

 1
 X0
 X1
 X2
 X0X1
 X0X2
 X1X0
 X1X2
 X0X1X0
 X0X1X2
 X1X0X2
 X0X1X0X2

In [1692]:

Base_Nichols := Base_FK3;; # Definimos la base y el ideal de forma genérica para que sirva para otra Nichols
J_Rel        := J_FK3;;
# 1. Determinar el grado máximo presente en la base
# En formato NP, la palabra está en p[1][1], y su longitud es el grado.
MaxDeg := Maximum(List(Base_Nichols, p -> Length(p[1][1])));;
# 2. Inicializar el record 
MatricesPorGrado := rec();;
for d in [0..MaxDeg] do
    # Filtramos solo los elementos de la base que tienen grado 'd'
    Base_d := Filtered(Base_Nichols, p -> Length(p[1][1]) = d);
    dim_d  := Length(Base_d);
    # Si no hay elementos en este grado (huecos), lo omitimos o dejamos vacío
    if dim_d = 0 then
        continue;
    fi;
    # Creamos la matriz nula para el bloque de grado d
    M_d := NullMat(dim_d, dim_d, Rationals);
    
    for j in [1..dim_d] do
        pol       := Base_d[j];
        mon       := pol[1];
        Lt        := List(gensA, ElementFq);
        genGi     := elmsG[Position( allPairsInG, G.2^-1 )];
        mon_act   := List(mon[1], m -> Position(Lt, genGi * gensA[m]));
        PolGd     := [[mon_act],[1]]; # Calcular el polinomio actuado
        PolGdNorm := StrongNormalFormNP(PolGd, J_Rel); # Reducción normal respecto al ideal de la Nichols (J_Rel)
        pos       := List(PolGdNorm[1], tx -> Position(Base_d, [[tx], [1]])); # ATENCIÓN: Extraemos posiciones buscando en Base_d, NO en la base total
        coeffs    := PolGdNorm[2] * ChiForSemidirectProduct( genGi )^d; # El grado del polinomio original es 'd'
        # Rellenar la sub-matriz de grado d
        for k in [1..Length(pos)] do
            row := pos[k];
            col := j;
            M_d[row][col] := coeffs[k];
        od;
    od;    
    # 3. Guardamos la matriz en el record usando el grado como clave
    MatricesPorGrado.(String(d)) := M_d;
od;

In [1693]:
ActionBlocksByGenerator := function( BaseNichols, J_Nichols, gen )
    local MaxDeg, MatricesPorGrado, Lt, genGi, d, Base_d, dim_d, M_d, j, pol, mon, mon_act, PolGd, PolGdNorm, pos, coeffs, k, row, col;

    # Precálculos fuera de los bucles de grado
    Lt := List(gensA, ElementFq);
    genGi := elmsG[Position( allPairsInG, gen )];

    # Determinar el grado máximo presente en la base
    MaxDeg := Maximum(List(BaseNichols, p -> Length(p[1][1])));
    MatricesPorGrado := rec();

    for d in [0..MaxDeg] do
        # Filtramos solo los elementos de la base con grado tensorial 'd'
        Base_d := Filtered(BaseNichols, p -> Length(p[1][1]) = d);
        dim_d := Length(Base_d);

        if dim_d = 0 then
            continue;
        fi;

        M_d := NullMat(dim_d, dim_d, Rationals);

        for j in [1..dim_d] do
            pol := Base_d[j];
            mon := pol[1];

            mon_act := List(mon[1], m -> Position(Lt, genGi * gensA[m]));
            PolGd := [[mon_act], [1]];
            PolGdNorm := StrongNormalFormNP(PolGd, J_Nichols);

            pos := List(PolGdNorm[1], tx -> Position(Base_d, [[tx], [1]]));
            coeffs := PolGdNorm[2] * ChiForSemidirectProduct( genGi )^d;

            for k in [1..Length(pos)] do
                row := pos[k];
                col := j;
                M_d[row][col] := coeffs[k];
            od;
        od;

        # Guardar el bloque matricial en el registro con la clave del grado
        MatricesPorGrado.(String(d)) := M_d;
    od;

    return MatricesPorGrado;
end;

function( BaseNichols, J_Nichols, gen ) ... end

In [1694]:
Display(ActionBlocksByGenerator( Base_FK3, J_FK3, G.1 ).4);

[ [  1 ] ]

In [1695]:
Display(ActionBlocksByGenerator( Base_FK3, J_FK3, G.2 ));

rec(
  0 := [ [ 1 ] ],
  1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],
  2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ] ],
  3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],
  4 := [ [ 1 ] ] )

In [1696]:
# Imprimir el record resultante
Display(ActionBlocksByGenerator( Base_FK3, J_FK3, G.2 ).1);

[ [  0,  1,  0 ],
  [  0,  0,  1 ],
  [  1,  0,  0 ] ]

## Deltas

In [1697]:
BaseNichols:=Base_FK3;

[ [ [ [  ] ], [ 1 ] ], [ [ [ 1 ] ], [ 1 ] ], [ [ [ 2 ] ], [ 1 ] ],   [ [ [ 3 ] ], [ 1 ] ], [ [ [ 1, 2 ] ], [ 1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ],   [ [ [ 2, 1 ] ], [ 1 ] ], [ [ [ 2, 3 ] ], [ 1 ] ],   [ [ [ 1, 2, 1 ] ], [ 1 ] ], [ [ [ 1, 2, 3 ] ], [ 1 ] ],   [ [ [ 2, 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

In [1698]:
Length(Base_FK3);

12

In [1702]:
g_is    := List(gensA, x -> ElementSDP( x, 1));;
degrees := [];;
for bi in Base_FK3 do
    if bi in Base_FK3 then
        monos := bi[1];
        coefs := bi[2];
        if Length(monos[1]) = 0 then
            g_i        := elmsG[1];
            Add(degrees, g_i);
        else
            list_rep_g_is := List(monos[1], j -> g_is[j]);
            g_i           := Product( list_rep_g_is );
            Add(degrees, g_i);
        fi;
    fi;
od;
Print(degrees);

[ ( 0 , 0 ), ( 0 , 1 ), ( 1 , 1 ), ( ζ_2 , 1 ), ( ζ_2 , 0 ), ( 1 , 0 ),
  ( 1 , 0 ), ( ζ_2 , 0 ), ( ζ_2 , 1 ), ( 1 , 1 ), ( 0 , 1 ), ( 0 , 0 ) ]

$$
\begin{array}{l|c|l}
\text{Element} & (a,b)\in C_3\rtimes C_2 & \text{Permutation in }S_3\\
\hline
1             &( 0 , 0 )        &()     \\
X_0           &( 0 , 1 )        &(1,2)  \\
X_1           &( 1 , 1 )        &(1,3)  \\
X_2           &( \zeta_2 , 1 )  &(2,3)  \\ 
X_0X_1        &( \zeta_2 , 0 )  &(1,3,2)\\
X_0X_2        &( 1 , 0 )        &(1,2,3)\\
X_1X_0        &( 1 , 0 )        &(1,2,3)\\
X_1X_2        &( \zeta_2 , 0 )  &(1,3,2)\\
X_0X_1X_0     &( \zeta_2 , 1 )  &(2,3)  \\
X_0X_1X_2     &( 1 , 1 )        &(1,3)  \\
X_1X_0X_2     &( 0 , 1 )        &(1,2)  \\
X_0X_1X_0X_2  &( 0 , 0 )        &()     \\
\end{array}
$$
Como
$$
\delta_h(v) = \begin{cases} 
v, & \text{si } \deg(v)=h \\ 
0, & \text{en otro caso} 
\end{cases}
$$
cada matriz es diagonal. Numeremos la base como
$$
B = \{1, X_0, X_1, X_2, X_0X_1, X_0X_2, X_1X_0, X_1X_2, X_0X_1X_0, X_0X_1X_2, X_1X_0X_2, X_0X_1X_0X_2\}.
$$
Entonces:
\begin{align*}
\delta_e &= \operatorname{diag}(1,0,0,0,0,0,0,0,0,0,0,1) \\
\delta_{(12)} &= \operatorname{diag}(0,1,0,0,0,0,0,0,0,0,1,0) \\
\delta_{(13)} &= \operatorname{diag}(0,0,1,0,0,0,0,0,0,1,0,0) \\
\delta_{(23)} &= \operatorname{diag}(0,0,0,1,0,0,0,0,1,0,0,0) \\
\delta_{(123)} &= \operatorname{diag}(0,0,0,0,0,1,1,0,0,0,0,0) \\
\delta_{(132)} &= \operatorname{diag}(0,0,0,0,1,0,0,1,0,0,0,0)
\end{align*}

Estas seis matrices satisfacen
$$
\sum_{h \in S_3} \delta_h = I_{12}, \quad \delta_h \delta_g = \delta_{h,g} \delta_h,
$$
como corresponde a los idempotentes de $k^{S_3}$.

In [1703]:
Length(degrees);

12

In [1706]:
N             := Length(Base_FK3);
deltaMatrices := List(GetElementsOfG(), g -> NullMat(N,N));
for i in [1..N] do
    pos := Position(GetElementsOfG(), degrees[i]);
    deltaMatrices[pos][i][i] := 1;
od;

12

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1707]:
Print(GetElementsOfG());

[ ( 0 , 0 ), ( 0 , 1 ), ( 1 , 0 ), ( 1 , 1 ), ( ζ_2 , 0 ), ( ζ_2 , 1 ) ]

$$
\begin{array}{l|c|l}
\text{Element} & (a,b)\in C_3\rtimes C_2 & \text{Permutation in }S_3\\
\hline
1             &( 0 , 0 )        &()     \\
X_0           &( 0 , 1 )        &(1,2)  \\
X_1           &( 1 , 0 )        &(1,2,3)\\
X_2           &( 1 , 1 )        &(1,3)  \\ 
X_0X_1        &( \zeta_2 , 0 )  &(1,3,2)\\
X_0X_2        &( \zeta_2 , 1 )  &(2,3)  \\
\end{array}
$$

In [1708]:
Display(deltaMatrices[1]); # () bien

[ [  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1 ] ]

In [1709]:
Display(deltaMatrices[2]); # (12)

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ] ]

In [1710]:
Display(deltaMatrices[3]); # (123)

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ] ]

In [1711]:
Display(deltaMatrices[4]); # (13)

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ] ]

In [1712]:
Display(deltaMatrices[5]); # (132)

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ] ]

In [1713]:
Display(deltaMatrices[6]); # (23)

[ [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ],
  [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ] ]

In [1714]:
Print(elmsG,"\n");

[ ( 0 , 0 ), ( 0 , 1 ), ( 1 , 0 ), ( 1 , 1 ), ( ζ_2 , 0 ), ( ζ_2 , 1 ) ]

In [1715]:
Print(List(elmsG, x->x^-1));

[ ( 0 , 0 ), ( 0 , 1 ), ( ζ_2 , 0 ), ( 1 , 1 ), ( 1 , 0 ), ( ζ_2 , 1 ) ]

In [1720]:
Base_Nichols := Base_FK3;;
J_Rel        := J_FK3;;
MaxDeg       := Maximum(List(Base_Nichols, p -> Length(p[1][1])));; # Grado tensorial máximo
DeltaBlocks  := [];;
for h in elmsG do
    R := rec();
    for d in [0..MaxDeg] do
        # Índices de la base con grado tensorial d
        idx_d := Filtered( [1..Length(Base_Nichols)], i -> Length(Base_Nichols[i][1][1]) = d);
        dim_d := Length(idx_d);
        if dim_d = 0 then
            continue;
        fi;
        M_d := NullMat(dim_d, dim_d);
        for j in [1..dim_d] do
            if degrees[idx_d[j]] = h then
                M_d[j][j] := 1;
            fi;
        od;
        R.(String(d)) := M_d;
    od;
    Add(DeltaBlocks, R);
od;

In [1721]:
for i in [1..Length(elmsG)] do
    Print(DeltaBlocks[i]=QGNAG_DeltaBlocksByDegree(Base_FK3)[i], "\n");
od;

true
true
true
true
true
true

In [1722]:
Display(DeltaBlocks[1]);

rec(
  0 := [ [ 1 ] ],
  1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],
  2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],
  3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],
  4 := [ [ 1 ] ] )

In [1723]:
Display(DeltaBlocks[2]);

rec(
  0 := [ [ 0 ] ],
  1 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],
  2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],
  3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],
  4 := [ [ 0 ] ] )

In [1724]:
Display(DeltaBlocks[3]);

rec(
  0 := [ [ 0 ] ],
  1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],
  2 := [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],
  3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],
  4 := [ [ 0 ] ] )

In [1725]:
elmsG[3];

( Z(3)^0 , 0 )

In [1726]:
Display(DeltaBlocks[4]);

rec(
  0 := [ [ 0 ] ],
  1 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],
  2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],
  3 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],
  4 := [ [ 0 ] ] )

In [1727]:
elmsG[4];

( Z(3)^0 , 1 )

In [1728]:
for i in [1..Length(elmsG)] do
    n := 0;
    for d in [0..MaxDeg] do
        M := DeltaBlocks[i].(String(d));
        n := n + RankMat(M);
    od;
    Print(i, " ", elmsG[i], "  ", n, "\n");
od;

1 ( 0 , 0 )  2
2 ( 0 , 1 )  2
3 ( 1 , 0 )  2
4 ( 1 , 1 )  2
5 ( ζ_2 , 0 )  2
6 ( ζ_2 , 1 )  2

In [1729]:
for d in [0..MaxDeg] do
    S := NullMat(
            NrRows(DeltaBlocks[1].(String(d))),
            NrCols(DeltaBlocks[1].(String(d)))
         );

    for i in [1..Length(elmsG)] do
        S := S + DeltaBlocks[i].(String(d));
    od;
    Display(S);
od;

[ [  1 ] ]
[ [  1,  0,  0 ],
  [  0,  1,  0 ],
  [  0,  0,  1 ] ]
[ [  1,  0,  0,  0 ],
  [  0,  1,  0,  0 ],
  [  0,  0,  1,  0 ],
  [  0,  0,  0,  1 ] ]
[ [  1,  0,  0 ],
  [  0,  1,  0 ],
  [  0,  0,  1 ] ]
[ [  1 ] ]

In [1730]:
BlockDiagonalMatrices := List(DeltaBlocks, QGNAG_BlockDiagonalMatrixForDeltas);

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1731]:
for i in [1..Length(deltaMatrices)] do
    Print(deltaMatrices[i]=BlockDiagonalMatrices[i],"\n");
od;

true
true
true
true
true
true

In [1732]:
NicholsBasisAction := function( BaseNichols, J_Nichols, gen )
    local genGi, PolNorm, bj, mon, Pol, PolN, Lt;
    genGi   := elmsG[Position(allPairsInG, gen)];
    PolNorm := [];
    Lt      := List(gensA, ElementFq);
    for bj in [1..Length(BaseNichols)] do
        mon  := BaseNichols[bj][1];
        Pol  := [ [ List(mon[1], m -> Position( Lt, genGi * gensA[m] ) ) ], [1] ];
        PolN := StrongNormalFormNP(Pol, J_Nichols);
        Add(PolNorm, PolN);

    od;
    return PolNorm;
end;

function( BaseNichols, J_Nichols, gen ) ... end

In [1733]:
PolsNormG1:=NicholsBasisAction( Base_FK3, J_FK3, G.1 );

[ [ [ [  ] ], [ 1 ] ], [ [ [ 1 ] ], [ 1 ] ], [ [ [ 3 ] ], [ 1 ] ],   [ [ [ 2 ] ], [ 1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2 ] ], [ 1 ] ],   [ [ [ 2, 3 ], [ 1, 2 ] ], [ -1, -1 ] ],   [ [ [ 2, 1 ], [ 1, 3 ] ], [ -1, -1 ] ], [ [ [ 1, 2, 3 ] ], [ -1 ] ],   [ [ [ 1, 2, 1 ] ], [ -1 ] ], [ [ [ 2, 1, 3 ] ], [ 1 ] ],   [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

In [1734]:
PrintNPList(PolsNormG1);

 1
 X0
 X2
 X1
 X0X2
 X0X1
 - X1X2 - X0X1
 - X1X0 - X0X2
 - X0X1X2
 - X0X1X0
 X1X0X2
 X0X1X0X2

In [1735]:
PolsNormG2:=NicholsBasisAction( Base_FK3, J_FK3, G.2 );

[ [ [ [  ] ], [ 1 ] ], [ [ [ 3 ] ], [ 1 ] ], [ [ [ 1 ] ], [ 1 ] ],   [ [ [ 2 ] ], [ 1 ] ], [ [ [ 2, 3 ], [ 1, 2 ] ], [ -1, -1 ] ],   [ [ [ 2, 1 ], [ 1, 3 ] ], [ -1, -1 ] ], [ [ [ 1, 3 ] ], [ 1 ] ],   [ [ [ 1, 2 ] ], [ 1 ] ], [ [ [ 1, 2, 3 ] ], [ -1 ] ],   [ [ [ 2, 1, 3 ] ], [ 1 ] ], [ [ [ 1, 2, 1 ] ], [ -1 ] ],   [ [ [ 1, 2, 1, 3 ] ], [ 1 ] ] ]

In [1736]:
PrintNPList(PolsNormG1);

 1
 X0
 X2
 X1
 X0X2
 X0X1
 - X1X2 - X0X1
 - X1X0 - X0X2
 - X0X1X2
 - X0X1X0
 X1X0X2
 X0X1X0X2

In [1738]:
mats_g1:=QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormG1, allPairsInG, G.1 );;
mats_g2:=QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormG2, allPairsInG, G.2 );;

In [1740]:
mats_g1=ActionMatrixByGenerator( Base_FK3, J_FK3, G.1 );
mats_g2=ActionMatrixByGenerator( Base_FK3, J_FK3, G.2 );

true

true

In [1741]:
MatricesNichols:=function( G, Base, J_Nichols )
    return Concatenation(
        List(
            GeneratorsOfGroup(G),
            gen -> ActionMatrixByGenerator( Base, J_Nichols, gen )
        ),
        QGNAG_DeltaMatricesNichols( Base )
    );
end;;

In [1742]:
matrix_s := MatricesNichols( G, Base_FK3, J_FK3 );

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1962]:
MatricesNichols( G, Base_FK3, J_FK3) =
    Concatenation(
        [
            QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormG1, allPairsInG, G.1 ),
            QGNAG_GroupActionOnNicholsBasis( Base_FK3, PolsNormG2, allPairsInG, G.2 )
        ],
        QGNAG_DeltaMatricesNichols( Base_FK3 )
    );

true

In [1743]:
QGNAG_TestRelationsForDGModSimple(matrix_s, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1963]:
QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG1, allPairsInG, G.1 );

( 0 , 1 )
-1

rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ], 2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ], [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ], 4 := [ [ 1 ] ] )

In [1964]:
QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG2, allPairsInG, G.2 );

( 1 , 0 )
1

rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ], 2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ] ], 3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ], 4 := [ [ 1 ] ] )

In [1744]:
ActionBlocksByGenerator( Base_FK3, J_FK3, G.1 );

rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ], 2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ], [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ], 4 := [ [ 1 ] ] )

In [1745]:
ActionBlocksByGenerator( Base_FK3, J_FK3, G.1 ) = QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG1, allPairsInG, G.1 );

( 0 , 1 )
-1

true

In [1746]:
ActionBlocksByGenerator( Base_FK3, J_FK3, G.2 ) = QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG2, allPairsInG, G.2 );

( 1 , 0 )
1

true

In [1746]:
BlockMatricesNichols := function( G, Base, J_Nichols )
    return Concatenation(
        List(
            GeneratorsOfGroup(G),
            gen -> ActionBlocksByGenerator( Base, J_Nichols, gen )
        ),
        QGNAG_DeltaBlocksByDegree( Base )
    );
end;;

In [1748]:
block_mats_s:=BlockMatricesNichols( G, Base_FK3, J_FK3 );

[ rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],       2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ],           [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ],       4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],       2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ],           [ -1, 0, 0, 0 ] ], 3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],      4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 1 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 1 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ) ]

In [1749]:
BlockMatricesNichols( G, Base_FK3, J_FK3 ) =
    Concatenation(
        [
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG1, allPairsInG, G.1 ),
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG2, allPairsInG, G.2 )
        ],
        QGNAG_DeltaBlocksByDegree( Base_FK3 )
);

( 0 , 1 )
-1
( 1 , 0 )
1

true

In [1750]:
Length(block_mats_s);

8

In [1753]:
mats_s_by_block := List(block_mats_s, QGNAG_BlockDiagonalMatrixForDeltas);
mats_s          := MatricesNichols( G, Base_FK3, J_FK3 );
for index_i in [1..Length(mats_s_by_block)] do
    Print(mats_s_by_block[index_i]=mats_s[index_i],"\n");
od;

true
true
true
true
true
true
true
true

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

[ [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ] ]

In [1754]:
QGNAG_TestRelationsForDGModSimple(mats_s, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1755]:
QGNAG_TestRelationsForDGModSimple(mats_s_by_block, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

## Esto esta bien

In [1756]:
block_mats_s:=BlockMatricesNichols( G, Base_FK3, J_FK3 );

[ rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],       2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ],           [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ],       4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],       2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ],           [ -1, 0, 0, 0 ] ], 3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],      4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 1 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 1 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ) ]

In [1757]:
QGNAG_TestRelationsForAllDegrees(block_mats_s, relsGroup, relskG, relsDG);

========================================
Testing degree 0
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 1
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 2
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 3
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 4
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Finished testing all degrees.
========================================

In [1758]:
block_mats_s_via_pkg:=Concatenation(
        [
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG1, allPairsInG, G.1 ),
            QGNAG_ActionBlocksByGenerator( Base_FK3, PolsNormG2, allPairsInG, G.2 )
        ],
        QGNAG_DeltaBlocksByDegree( Base_FK3 )
);

( 0 , 1 )
-1
( 1 , 0 )
1

[ rec( 0 := [ [ 1 ] ], 1 := [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],       2 := [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ],           [ 0, 0, -1, 0 ] ], 3 := [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ],       4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],       2 := [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ],           [ -1, 0, 0, 0 ] ], 3 := [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],      4 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 1 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],       2 := [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 1 ] ],      3 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ], 1 := [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],       2 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      3 := [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ], 4 := [ [ 0 ] ] ) ]

In [1759]:
QGNAG_TestRelationsForAllDegrees(block_mats_s_via_pkg, relsGroup, relskG, relsDG);

========================================
Testing degree 0
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 1
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 2
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 3
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 4
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Finished testing all degrees.
========================================

In [1760]:
mats0 := QGNAG_BlockMatricesByDegree(block_mats_s,0);

[ [ [ 1 ] ], [ [ 1 ] ], [ [ 1 ] ], [ [ 0 ] ], [ [ 0 ] ], [ [ 0 ] ],   [ [ 0 ] ], [ [ 0 ] ] ]

In [1761]:
QGNAG_TestRelationsForDGModSimple(mats0, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1762]:
mats1 := QGNAG_BlockMatricesByDegree(block_mats_s,1);

[ [ [ -1, 0, 0 ], [ 0, 0, -1 ], [ 0, -1, 0 ] ],   [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ] ]

In [1763]:
QGNAG_TestRelationsForDGModSimple(mats1, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1764]:
mats2 := QGNAG_BlockMatricesByDegree(block_mats_s,2);

[ [ [ 0, 1, -1, 0 ], [ 1, 0, 0, -1 ], [ 0, 0, 0, -1 ], [ 0, 0, -1, 0 ] ],   [ [ -1, 0, 0, 1 ], [ 0, -1, 1, 0 ], [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 0 ] ],   [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],   [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 1 ] ],   [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ] ]

In [1765]:
QGNAG_TestRelationsForDGModSimple(mats2, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1766]:
mats3 := QGNAG_BlockMatricesByDegree(block_mats_s,3);

[ [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ],   [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, 1, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 1 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 0 ] ],   [ [ 0, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ],   [ [ 1, 0, 0 ], [ 0, 0, 0 ], [ 0, 0, 0 ] ] ]

In [1767]:
QGNAG_TestRelationsForDGModSimple(mats3, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1768]:
mats4 := QGNAG_BlockMatricesByDegree(block_mats_s,4);

[ [ [ 1 ] ], [ [ 1 ] ], [ [ 1 ] ], [ [ 0 ] ], [ [ 0 ] ], [ [ 0 ] ],   [ [ 0 ] ], [ [ 0 ] ] ]

In [1769]:
QGNAG_TestRelationsForDGModSimple(mats4, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1771]:
record_data_decomp_nichols:=[];;
for s in SimplesMn do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, block_mats_s );
    Add(record_data_decomp_nichols, decomp_char_s);
od;

In [1773]:
record_data_decomp_nichols_via_pkg:=[];;
for s in SimplesMn do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, block_mats_s_via_pkg );
    Add(record_data_decomp_nichols_via_pkg, decomp_char_s);
od;

In [1774]:
record_data_decomp_nichols_via_pkg=record_data_decomp_nichols;

true

In [1774]:
rec_info := QGNAG_Decomposition(record_data_decomp_nichols);;

In [1775]:
QGNAG_PrintDecomposition(rec_info);

degree 0 = M1
degree 1 = M5
degree 2 = M7 + M8
degree 3 = M5
degree 4 = M1

In [1777]:
QGNAG_CharacterSummary(rec_info, SimplesMn);

 Char(t) = M1[0] + M5[1] + M7[2] + M8[2] + M5[3] + M1[4]

 SUMMARY:

==================================================
Degree 0
==================================================
-------------------
Simple M1
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

==================================================
Degree 1
==================================================
-------------------
Simple M5
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 2
==================================================
-------------------
Simple M7
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2
-------------------
Simple M8
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2

==================================================
Degree 3
==================================================
-------------------
Simple M5
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 4
==================================================
-------------------
Simple M1
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1778]:
QGNAG_CharacterSummaryLaTeX(rec_info, SimplesMn, SimpleNames);

\operatorname{Char}(t) = M(e,+)[0] + M(\sigma,-)[1] + M(\tau,1)[2] + M(\tau,2)\
[2] + M(\sigma,-)[3] + M(e,+)[4]



==================================================
Degree 0
==================================================
-------------------
Simple M(e,+)
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

==================================================
Degree 1
==================================================
-------------------
Simple M(\sigma,-)
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 2
==================================================
-------------------
Simple M(\tau,1)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2
-------------------
Simple M(\tau,2)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2

==================================================
Degree 3
==================================================
-------------------
Simple M(\sigma,-)
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 4
==================================================
-------------------
Simple M(e,+)
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1779]:
QGNAG_CharacterSummaryToLaTeX( "character_nichols.tex", rec_info, SimpleNames );

In [1780]:
Display(mats2[1]);

[ [   0,   1,  -1,   0 ],
  [   1,   0,   0,  -1 ],
  [   0,   0,   0,  -1 ],
  [   0,   0,  -1,   0 ] ]

In [1781]:
Display(mats2[2]);

[ [  -1,   0,   0,   1 ],
  [   0,  -1,   1,   0 ],
  [   0,  -1,   0,   0 ],
  [  -1,   0,   0,   0 ] ]

In [1782]:
Display(MatricesNichols( G, Base_FK3, J_FK3 )[1]);

[ [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   1,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   1,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1 ] ]

In [1783]:
Display(MatricesNichols( G, Base_FK3, J_FK3 )[2]);

[ [   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   1,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,  -1,   0,   0,   1,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,  -1,   1,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,  -1,   0,   0,   0,   0,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,  -1,   0,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,   0,   0 ],
  [   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1 ] ]

In [1784]:
QGNAG_TestRelationsForDGModSimple(MatricesNichols( G, Base_FK3, J_FK3 ), relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

In [1785]:
QGNAG_TestRelationsForDGModSimple(mats2, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

## Character for Nichols Algebra

In [1787]:
record_data_decomp_nichols_via_pkg:=[];;
for s in SimplesMn do
    DGActMat      := QGNAG_DGActionMatrices(s, allPairsInG,  Base_FK3);
    decomp_char_s := QGNAG_VermaModuleSocleDecomposition( DGActMat, block_mats_s_via_pkg );
    Add(record_data_decomp_nichols_via_pkg, decomp_char_s);
od;

In [1788]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols, true);

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [1789]:
QGNAG_RecordListToHTMLTableFiltered(record_data_decomp_nichols, true);

,M1,M5,M7,M8
0,1,0,0,0
1,0,1,0,0
2,0,0,1,1
3,0,1,0,0
4,1,0,0,0

In [1790]:
QGNAG_FilterZeroSimples( record_data_decomp_nichols );

rec( indices := [ 1, 5, 7, 8 ], records := [ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ), rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ), rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ), rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ] )

In [1791]:
record_data_decomp_nichols_filt := QGNAG_FilterZeroRows(record_data_decomp_nichols);

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ]

In [1792]:
record_data_decomp_nichols;

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ]

In [1793]:
Length(record_data_decomp_nichols);

8

In [1794]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols_filt, true);

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [1795]:
rec_info_nichols := QGNAG_Decomposition(record_data_decomp_nichols_via_pkg);;

In [1796]:
rec_info_nichols;

rec( 0 := [ [ 1, 1 ] ], 1 := [ [ 1, 5 ] ], 2 := [ [ 1, 7 ], [ 1, 8 ] ], 3 := [ [ 1, 5 ] ], 4 := [ [ 1, 1 ] ] )

In [1797]:
QGNAG_PrintDecomposition(rec_info_nichols);

degree 0 = M1
degree 1 = M5
degree 2 = M7 + M8
degree 3 = M5
degree 4 = M1

In [1798]:
QGNAG_CharacterSummary(rec_info_nichols, SimplesMn);

 Char(t) = M1[0] + M5[1] + M7[2] + M8[2] + M5[3] + M1[4]

 SUMMARY:

==================================================
Degree 0
==================================================
-------------------
Simple M1
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

==================================================
Degree 1
==================================================
-------------------
Simple M5
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 2
==================================================
-------------------
Simple M7
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2
-------------------
Simple M8
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2

==================================================
Degree 3
==================================================
-------------------
Simple M5
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 4
==================================================
-------------------
Simple M1
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1799]:
QGNAG_CharacterSummaryLaTeX(rec_info_nichols, SimplesMn, SimpleNames);

\operatorname{Char}(t) = M(e,+)[0] + M(\sigma,-)[1] + M(\tau,1)[2] + M(\tau,2)\
[2] + M(\sigma,-)[3] + M(e,+)[4]



==================================================
Degree 0
==================================================
-------------------
Simple M(e,+)
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

==================================================
Degree 1
==================================================
-------------------
Simple M(\sigma,-)
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 2
==================================================
-------------------
Simple M(\tau,1)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2
-------------------
Simple M(\tau,2)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2

==================================================
Degree 3
==================================================
-------------------
Simple M(\sigma,-)
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1 ]) -> [ [ [ -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 1 , 0 )) ⊗ [ 1 ],
  (( ζ_2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 3

==================================================
Degree 4
==================================================
-------------------
Simple M(e,+)
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [1800]:
QGNAG_CharacterSummaryToLaTeX( "character_nichols.tex", rec_info_nichols, SimpleNames );

fijemos $\mathcal{M}=\{M_1,\dots,M_\theta\}$

Supongamos que las *reglas de fusión* de $H$ son
$$
M_i\otimes M_s=\bigoplus_{k=1}^\theta M_k^{N^{i s}_k}
$$

aquí calculamos 
$$
{N^{i s}_k}=\dim \operatorname{Hom}_H(M_i\otimes M_s, M_k)
$$ 

Sea $\mathfrak{B}=\bigoplus\limits_{i,j} M_i[j]^{b_{i j}}$ la descomposición
de $\mathfrak{B}$ como $H$-módulo graduado.

aquí calculamos 
$$
{b_{i j}}=\dim \operatorname{Hom}_H(M_i, \mathfrak{B}^j)
$$ 

Dado $M_s$, calcular
$$
d_{kj}^s=\sum_{i=1}^{\theta}N_k^{i s}b_{ij}=\sum_{i=1}^{\theta}\dim \operatorname{Hom}_H(M_i\otimes M_s, M_k)\cdot\dim \operatorname{Hom}_H(M_i, \mathfrak{B}^j).
$$

- input $k, s=1,...,\theta$ y $j=0,...,\ell$
- output $d_{kj}^s$

1. Fijar $k, s$ en $\{1,2,\dots \theta\}$ y $j$ en $\{0,1,\dots,\ell\}$.

2. Dado $j$

   $$
   b_{i j}\gets \dim \operatorname{Hom}_H(M_i, \mathfrak{B}^j)
   $$
3. Dado $k, s$

   $M_k\gets$ simple de la familia $\mathcal{F}$

   $M_s\gets$ simple de la familia $\mathcal{F}$
   
   Calcular $N_k^{i s}=\dim \operatorname{Hom}_H(M_i\otimes M_s, M_k)$ para todo $i=1,2,3...,\theta$

## Paso 1: Fijar $k, s, j$

## Paso 2: cálculo de los $b_{ij}$

In [1801]:
SimplesMn:=List(SimplesMn, s-> AttachDeltaStructureMatrices(s));;

In [1802]:
index_k:=3;

3

In [1803]:
index_s:=5;

5

In [1804]:
index_j:=2;

2

In [1805]:
bi2:=QGNAG_MultiplicitiesAtDegree( index_j, SimplesMn, rec_info_nichols );

rec( 2 := [ 0, 0, 0, 0, 0, 0, 1, 1 ] )

In [1806]:
RecNames(bi2)[1];

"2"

In [1807]:
bijs_by_degree:=QGNAG_MultiplicitiesByDegree( SimplesMn, rec_info_nichols );

[ rec( 0 := [ 1, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( 1 := [ 0, 0, 0, 0, 1, 0, 0, 0 ] ),   rec( 2 := [ 0, 0, 0, 0, 0, 0, 1, 1 ] ),   rec( 3 := [ 0, 0, 0, 0, 1, 0, 0, 0 ] ),   rec( 4 := [ 1, 0, 0, 0, 0, 0, 0, 0 ] ) ]

In [1808]:
QGNAG_DecompositionFromMultiplicities( bijs_by_degree );

rec( 0 := [ [ 1, 1 ] ], 1 := [ [ 1, 5 ] ], 2 := [ [ 1, 7 ], [ 1, 8 ] ], 3 := [ [ 1, 5 ] ], 4 := [ [ 1, 1 ] ] )

In [1809]:
rec_info_nichols=QGNAG_DecompositionFromMultiplicities( bijs_by_degree );

true

In [1810]:
QGNAG_CharacterByDegreeSummaryLaTeX := function( bij, SimplesMn, SimpleNames )
    local i, j, mult, term, charstr, first, rec_info;

    charstr := "\\operatorname{Char}(t) = ";
    first   := true;
    j       := RecNames(bij)[1];

    # Construimos la expresión del carácter en grado j
    for i in [1 .. Length(bij.(j))] do
        mult := bij.(j)[i];
        if mult <> 0 then
            if mult = 1 then
                term := Concatenation( SimpleNames[i], "[", j, "]");
            else
                term := Concatenation(String(mult), "\\,", SimpleNames[i], "[", j, "]");
            fi;
            if first then
                charstr := Concatenation(charstr, term);
                first := false;
            else
                charstr := Concatenation( charstr, " + ", term );
            fi;
        fi;
    od;
    charstr := Concatenation(charstr, "\n");
    Print(charstr);
    # Construimos un rec_info solamente para este grado
    rec_info := rec();
    rec_info.(j) := [];
    for i in [1 .. Length(bij.(j))] do
        if bij.(j)[i] <> 0 then
            Add( rec_info.(j), [ bij.(j)[i], i ] );
        fi;
    od;
    # Mostrar los detalles de los simples
    QGNAG_DisplayDecompositionLaTeX( rec_info, SimplesMn, SimpleNames );
end;

function( bij, SimplesMn, SimpleNames ) ... end

In [1811]:
QGNAG_CharacterByDegreeSummaryLaTeX( bi2, SimplesMn, SimpleNames );

\operatorname{Char}(t) = M(\tau,1)[2] + M(\tau,2)[2]

==================================================
Degree 2
==================================================
-------------------
Simple M(\tau,1)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2
-------------------
Simple M(\tau,2)
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f2 ]) -> [ [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ] ]

* Dimension: 2

In [1812]:
Length(bijs_by_degree);

5

In [1813]:
index_j;

2

In [1816]:
bijs_by_degree := QGNAG_MultiplicitiesByDegree( SimplesMn, rec_info_nichols );
bijs_values := Filtered(bijs_by_degree, bijs -> RecNames(bijs)[1]=String(index_j))[1].((index_j));
for index_i in [1..Length(SimplesMn)] do
    Print("b", index_i, index_j, " = ", bijs_values[index_i], "\n");
od;

b12 = 0
b22 = 0
b32 = 0
b42 = 0
b52 = 0
b62 = 0
b72 = 1
b82 = 1

[ rec( 0 := [ 1, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( 1 := [ 0, 0, 0, 0, 1, 0, 0, 0 ] ),   rec( 2 := [ 0, 0, 0, 0, 0, 0, 1, 1 ] ),   rec( 3 := [ 0, 0, 0, 0, 1, 0, 0, 0 ] ),   rec( 4 := [ 1, 0, 0, 0, 0, 0, 0, 0 ] ) ]

[ 0, 0, 0, 0, 0, 0, 1, 1 ]

### $\texttt{QGNAG\_GradedNicholsMultiplicity}$

Sea $\mathfrak{B}=\bigoplus_{i,j} M_i[j]^{\,b_{ij}}$
la descomposición de la álgebra de Nichols $\mathfrak{B}$ como
$D(G)$-módulo graduado, donde $M_i$ denota el $i$-ésimo módulo simple de
$D(G)$ y $M_i[j]$ indica que dicho módulo aparece en grado $j$.

La información correspondiente a esta descomposición se almacena en el
record $\texttt{rec\_info\_nichols}$. Para cada grado $j$, el componente
$\texttt{rec\_info\_nichols}.j$ contiene una lista de pares $[b_{ij},i]$
para aquellos índices $i$ tales que $b_{ij}\neq 0$. En otras palabras,
$\texttt{rec\_info\_nichols}.j=\bigl\{[b_{ij},i] : b_{ij}\neq 0\bigr\}.$

Por ejemplo, si $\texttt{rec\_info\_nichols.2 = [[1,43],[1,44]]},$
esto significa que $\mathfrak{B}^2 \simeq M_{43}[2]\oplus M_{44}[2].$
Por lo tanto, $b_{43,2}=1, \qquad b_{44,2}=1,$ mientras que $b_{i,2}=0$
para todo $i\notin\{43,44\}$.

La función
$
\texttt{QGNAG\_GradedNicholsMultiplicity}(i,j,
\texttt{rec\_info\_nichols})
$
permite recuperar directamente la multiplicidad $b_{ij}$ a partir de
esta información.

Su implementación es
```python
InstallGlobalFunction(QGNAG_GradedNicholsMultiplicity, function( i, j, rec_info_nichols )
        local decomposition, pair;

        if not IsBound( rec_info_nichols.(String(j)) ) then
            return 0;
        fi;
        decomposition := rec_info_nichols.(String(j));
        for pair in decomposition do
            if pair[2] = i then
                return pair[1];
            fi;
        od;
        return 0;
    end
);
```

La función primero verifica si el grado $j$ aparece en
$\texttt{rec\_info\_nichols}$. Si no aparece, entonces el correspondiente
componente homogéneo es nulo y se devuelve $b_{ij}=0.$
Si el grado está presente, se recorre la lista
$\texttt{rec\_info\_nichols}.j$ buscando un par cuya segunda componente sea $i$. Si se encuentra el par
$[b_{ij},i],$ la función devuelve su primera componente, es decir, $b_{ij}$.
Si no se encuentra dicho índice, entonces $M_i[j]$ no aparece en la
descomposición y se devuelve $0$.

Por ejemplo, $\texttt{QGNAG\_GradedNicholsMultiplicity}(43,2,\texttt{rec\_info\_nichols})$
devuelve $1,$ pues $[1,43]\in\texttt{rec\_info\_nichols}.2.$
En cambio,$\texttt{QGNAG\_GradedNicholsMultiplicity}(1,2,\texttt{rec\_info\_nichols})$ devuelve $0,$ pues $[b_{1,2},1]$ no aparece en la descomposición de $\mathfrak{B}_2$.

In [1817]:
QGNAG_GradedMultiplicity:=function( i, j, rec_info )
    local decomposition, pair;
    if not IsBound( rec_info.(String(j)) ) then
        return 0;
    fi;
    decomposition := rec_info.(String(j));
    for pair in decomposition do
        if pair[2] = i then
            return pair[1];
        fi;
    od;
    return 0;
end;

function( i, j, rec_info ) ... end

In [1818]:
rec_info_nichols;

rec( 0 := [ [ 1, 1 ] ], 1 := [ [ 1, 5 ] ], 2 := [ [ 1, 7 ], [ 1, 8 ] ], 3 := [ [ 1, 5 ] ], 4 := [ [ 1, 1 ] ] )

In [1819]:
index_j;

2

In [1821]:
index_i:=8;;
QGNAG_GradedMultiplicity( index_i, index_j, rec_info_nichols );

1

## Paso 3: Calcular $N_k^{i s}=\dim \operatorname{Hom}_H(M_i\otimes M_s, M_k)$ para todo $i=1,2,3...,\theta$

In [1822]:
index_s;

5

In [1823]:
index_k;

3

In [1824]:
for i in [2..Length(SimplesMn)] do
    Print("--------------------------------------------------------------\n");
    for j in [i..Length(SimplesMn)] do
        MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[i], SimplesMn[j]);
        Print(QGNAG_FusionRuleToIndex( MtensorN, SimplesMn), "\n");
    od;
od;

--------------------------------------------------------------
M2 \otimes M2 \simeq M1
M2 \otimes M3 \simeq M3
M2 \otimes M4 \simeq M5
M2 \otimes M5 \simeq M4
M2 \otimes M6 \simeq M6
M2 \otimes M7 \simeq M7
M2 \otimes M8 \simeq M8
--------------------------------------------------------------
M3 \otimes M3 \simeq M1 \oplus M2 \oplus M3
M3 \otimes M4 \simeq M4 \oplus M5
M3 \otimes M5 \simeq M4 \oplus M5
M3 \otimes M6 \simeq M7 \oplus M8
M3 \otimes M7 \simeq M6 \oplus M8
M3 \otimes M8 \simeq M6 \oplus M7
--------------------------------------------------------------
M4 \otimes M4 \simeq M1 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M4 \otimes M5 \simeq M2 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M4 \otimes M6 \simeq M4 \oplus M5
M4 \otimes M7 \simeq M4 \oplus M5
M4 \otimes M8 \simeq M4 \oplus M5
--------------------------------------------------------------
M5 \otimes M5 \simeq M1 \oplus M3 \oplus M6 \oplus M7 \oplus M8
M5 \otimes M6 \simeq M4 \oplus M5
M5 \otimes M7 \simeq M4 \oplus M5
M5 \otimes M8 \simeq M4 \oplus M5
--------------------------------------------------------------
M6 \otimes M6 \simeq M1 \oplus M2 \oplus M6
M6 \otimes M7 \simeq M3 \oplus M8
M6 \otimes M8 \simeq M3 \oplus M7
--------------------------------------------------------------
M7 \otimes M7 \simeq M1 \oplus M2 \oplus M7
M7 \otimes M8 \simeq M3 \oplus M6
--------------------------------------------------------------
M8 \otimes M8 \simeq M1 \oplus M2 \oplus M8

In [1825]:
QGNAG_TestRelationsForDGModSimples(SimplesMn, relsGroup, relskG, relsDG);

Simple M4 failed:
   - Drinfeld Double relations

Simple M5 failed:
   - Drinfeld Double relations

false

In [1830]:
MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[3], SimplesMn[index_s]);;
decomposition := QGNAG_DecomposeDGRepresentation(MtensorN, [SimplesMn[index_k]]);;
decom:=[];;
for term in decomposition do
    mult   := term[1];
    simple := term[2];
    pos    := Position(SimplesMn, simple);
    rhs    := [mult, pos] ;
    Add(decom, rhs);
od;
Print(decom);

[  ]

In [1831]:
for index_i in [1..Length(SimplesMn)] do
    MtensorN    := QGNAG_TensorProductOfSimples(SimplesMn[index_i], SimplesMn[index_s]);;
    mats_rep    := QGNAG_RepresentationMatrices(MtensorN);;
    mats_simple := QGNAG_RepresentationMatrices(SimplesMn[index_k]);;
    Print("i = ", index_i, ", s = ", index_s, ", k = ", index_k, ", N^{", index_i," ", index_s, "}_{", index_k ,"} = ", QGNAG_DimHomAModules(mats_rep, mats_simple), "\n");
od;

i = 1, s = 5, k = 3, N^{1 5}_{3} = 0
i = 2, s = 5, k = 3, N^{2 5}_{3} = 0
i = 3, s = 5, k = 3, N^{3 5}_{3} = 0
i = 4, s = 5, k = 3, N^{4 5}_{3} = 1
i = 5, s = 5, k = 3, N^{5 5}_{3} = 1
i = 6, s = 5, k = 3, N^{6 5}_{3} = 0
i = 7, s = 5, k = 3, N^{7 5}_{3} = 0
i = 8, s = 5, k = 3, N^{8 5}_{3} = 0

La multiplicidad de $M_k$ en el producto tensorial $M_i\otimes M_s$
está dada por $N_k^{i,s}=\dim\operatorname{Hom}_{D(G)}\left(M_i\otimes M_s,M_k\right).$
Por lo tanto, $\texttt{QGNAG\_FusionMultiplicity}$ calcula directamente
el coeficiente $N_k^{i,s}$ de la descomposición de $M_i\otimes M_s$ en
módulos simples.

In [1832]:
QGNAG_FusionMultiplicity:=function( i, s, k, SimplesMn )
    local MtensorN, mats_rep, mats_simple;

    MtensorN := QGNAG_TensorProductOfSimples( SimplesMn[i], SimplesMn[s]);
    mats_rep := QGNAG_RepresentationMatrices(MtensorN);
    mats_simple := QGNAG_RepresentationMatrices(SimplesMn[k]);
    return QGNAG_DimHomAModules( mats_rep, mats_simple);
end;

function( i, s, k, SimplesMn ) ... end

In [1834]:
index_i:=8;;
QGNAG_FusionMultiplicity( index_i, index_s, index_k, SimplesMn );

0

In [1839]:
Print("index_i: ", index_i,"\n");
Print("index_s: ", index_s,"\n");
Print("index_k: ", index_k,"\n");
Print("N^{", index_i," ", index_s, "}_{", index_k, "} = ", QGNAG_FusionMultiplicity( index_i, index_s, index_k, SimplesMn ), "\n");
Print(QGNAG_FusionRuleToIndex( QGNAG_TensorProductOfSimples( SimplesMn[index_i], SimplesMn[index_s]), SimplesMn), "\n");

index_i: 8
index_s: 5
index_k: 3
N^{8 5}_{3} = 0
M8 \otimes M5 \simeq M4 \oplus M5

In [1840]:
record_data_decomp_nichols;

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ]

In [1841]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols, true);

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [1842]:
record_data_decomp_nichols;

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 1, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0 ) ]

In [1843]:
QGNAG_RecordListToHTMLTableFiltered( record_data_decomp_nichols, true );

,M1,M5,M7,M8
0,1,0,0,0
1,0,1,0,0
2,0,0,1,1
3,0,1,0,0
4,1,0,0,0

In [1844]:
QGNAG_FusionMultiplicityData := function( s, k, SimplesMn )
    local data, i, value, r, index;
    data := [];
    for i in [1 .. Length(SimplesMn)] do
        value := QGNAG_FusionMultiplicity( i, s, k, SimplesMn );
        r         := rec();
        index     := StringFormatted("M{}xM{}", s, k);
        r.("0") := value;
        Add(data, r);
    od;
    return data;
end;

function( s, k, SimplesMn ) ... end

In [1845]:
index_s;

5

In [1846]:
index_k;

3

In [1847]:
data := QGNAG_FusionMultiplicityData(index_s, index_k, SimplesMn);

[ rec( 0 := 0 ), rec( 0 := 0 ), rec( 0 := 0 ), rec( 0 := 1 ), rec( 0 := 1 ),   rec( 0 := 0 ), rec( 0 := 0 ), rec( 0 := 0 ) ]

In [1848]:
QGNAG_RecordListToHTMLTable(data, true);

,1,2,3,4,5,6,7,8
0,0,0,0,1,1,0,0,0

In [1849]:
QGNAG_RecordListToHTMLTableFiltered( data, true );

,M4,M5
0,1,1

In [1850]:
QGNAG_FilterByDegree:=function( record_list, degree )
    local filtered_list, r;
    
    if Length(record_list) = 0 then
        return [];
    fi;

    filtered_list := List(record_list,
                            function(r)
                                local new_rec;
                                
                                new_rec := rec();
                                new_rec.(String(degree)) := r.(String(degree));
                                    
                                return new_rec;
                            end);
    return filtered_list;
end;

function( record_list, degree ) ... end

In [1851]:
record_data_decomp_nichols_by_degree:=QGNAG_FilterByDegree( record_data_decomp_nichols, index_j );

[ rec( 2 := 0 ), rec( 2 := 0 ), rec( 2 := 0 ), rec( 2 := 0 ), rec( 2 := 0 ),   rec( 2 := 0 ), rec( 2 := 1 ), rec( 2 := 1 ) ]

In [1852]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols_by_degree, true );

,1,2,3,4,5,6,7,8
2,0,0,0,0,0,0,1,1

In [1853]:
QGNAG_GradedFusionMultiplicity:=function( s, k, j, SimplesMn, rec_info_nichols )
    local i, N_iks, b_ij, result;
    result := 0;
    for i in [1 .. Length(SimplesMn)] do
        N_iks  := QGNAG_FusionMultiplicity( i, s, k, SimplesMn );
        b_ij   := QGNAG_GradedMultiplicity( i, j, rec_info_nichols );
        result := result + N_iks * b_ij;
    od;
    return result;
end;

function( s, k, j, SimplesMn, rec_info_nichols ) ... end

In [1857]:
Print("index_s: ", index_s,"\n");
Print("index_k: ", index_k,"\n");
Print("index_j: ", index_j,"\n");
QGNAG_GradedFusionMultiplicity(index_s, index_k, index_j, SimplesMn, rec_info_nichols );

index_s: 5
index_k: 3
index_j: 2

0

In [1858]:
QGNAG_GradedFusionMatrix:=function( j, SimplesMn, rec_info_nichols )
    local n, data, s, k, r;
    n    := Length(SimplesMn);
    data := [];
    for s in [1 .. n] do
        r := rec();
        for k in [1 .. n] do
            r.(String(k)) := QGNAG_GradedFusionMultiplicity( s, k, j, SimplesMn, rec_info_nichols );
        od;
        Add(data, r);
    od;
    return data;
end;

function( j, SimplesMn, rec_info_nichols ) ... end

In [1859]:
data_index_j := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );

[ rec( 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 1, 8 := 1 ),   rec( 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 1, 8 := 1 ),   rec( 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 2, 7 := 1, 8 := 1 ),   rec( 1 := 0, 2 := 0, 3 := 0, 4 := 2, 5 := 2, 6 := 0, 7 := 0, 8 := 0 ),   rec( 1 := 0, 2 := 0, 3 := 0, 4 := 2, 5 := 2, 6 := 0, 7 := 0, 8 := 0 ),   rec( 1 := 0, 2 := 0, 3 := 2, 4 := 0, 5 := 0, 6 := 0, 7 := 1, 8 := 1 ),   rec( 1 := 1, 2 := 1, 3 := 1, 4 := 0, 5 := 0, 6 := 1, 7 := 1, 8 := 0 ),   rec( 1 := 1, 2 := 1, 3 := 1, 4 := 0, 5 := 0, 6 := 1, 7 := 0, 8 := 1 ) ]

In [1860]:
data_index_j[index_s].(index_k);

0

In [1861]:
index_j;

2

In [1862]:
QGNAG_RecordListToHTMLTable(data_index_j, true );

,1,2,3,4,5,6,7,8
1,0,0,0,0,0,0,1,1
2,0,0,0,0,0,0,1,1
3,0,0,0,0,0,2,1,1
4,0,0,0,2,2,0,0,0
5,0,0,0,2,2,0,0,0
6,0,0,2,0,0,0,1,1
7,1,1,1,0,0,1,1,0
8,1,1,1,0,0,1,0,1

### $d^j_{s k}$ con $j= 0, 2, \dots, \ell$ fijo.

In [1865]:
index_j      := 0;;
data_index_0 := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable(data_index_0, true );

,1,2,3,4,5,6,7,8
1,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0
5,0,0,0,0,1,0,0,0
6,0,0,0,0,0,1,0,0
7,0,0,0,0,0,0,1,0
8,0,0,0,0,0,0,0,1

In [1868]:
index_j      := 1;;
data_index_1 := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable(data_index_1, true );

,1,2,3,4,5,6,7,8
1,0,0,0,0,1,0,0,0
2,0,0,0,1,0,0,0,0
3,0,0,0,1,1,0,0,0
4,0,1,1,0,0,1,1,1
5,1,0,1,0,0,1,1,1
6,0,0,0,1,1,0,0,0
7,0,0,0,1,1,0,0,0
8,0,0,0,1,1,0,0,0

In [1871]:
index_j      := 2;;
data_index_2 := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable(data_index_2, true );

,1,2,3,4,5,6,7,8
1,0,0,0,0,0,0,1,1
2,0,0,0,0,0,0,1,1
3,0,0,0,0,0,2,1,1
4,0,0,0,2,2,0,0,0
5,0,0,0,2,2,0,0,0
6,0,0,2,0,0,0,1,1
7,1,1,1,0,0,1,1,0
8,1,1,1,0,0,1,0,1

In [1874]:
index_j      := 3;;
data_index_3 := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable(data_index_3, true );

,1,2,3,4,5,6,7,8
1,0,0,0,0,1,0,0,0
2,0,0,0,1,0,0,0,0
3,0,0,0,1,1,0,0,0
4,0,1,1,0,0,1,1,1
5,1,0,1,0,0,1,1,1
6,0,0,0,1,1,0,0,0
7,0,0,0,1,1,0,0,0
8,0,0,0,1,1,0,0,0

In [1877]:
index_j      := 4;;
data_index_4 := QGNAG_GradedFusionMatrix( index_j, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable(data_index_4, true );

,1,2,3,4,5,6,7,8
1,1,0,0,0,0,0,0,0
2,0,1,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0
4,0,0,0,1,0,0,0,0
5,0,0,0,0,1,0,0,0
6,0,0,0,0,0,1,0,0
7,0,0,0,0,0,0,1,0
8,0,0,0,0,0,0,0,1

For a fixed simple module $M_s$, the function constructs the multiplicity table
$$
d_{sk}^{\,j}
=
\sum_{i=1}^{n} N_k^{i,s} b_{ij},
\qquad
0\leq j\leq \ell,\quad 1\leq k\leq n.
$$
The table has $\ell+1$ rows and $n$ columns: each row corresponds to a
degree $j$ of $\mathfrak{B}$, while each column corresponds to a simple
module $M_k$. Thus, the $(j,k)$-entry is the multiplicity of $M_k$ in
$M_s\otimes\mathfrak{B}_j$.

In [1878]:
QGNAG_GradedFusionByDegree:=function( s, SimplesMn, rec_info )
    local theta, data, j, k, r;
    theta := Maximum( List( RecNames(rec_info), Int ) );
    data  := [];
    for k in [1 .. Length(SimplesMn)] do
        r := rec();
        for j in [0 .. theta] do
            r.(String(j)) := QGNAG_GradedFusionMultiplicity( s, k, j, SimplesMn, rec_info );
        od;
        Add(data, r);
    od;
    return data;
end;

function( s, SimplesMn, rec_info ) ... end

In [1881]:
index_s := 1;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,1,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,0,1,0,0,0
4,1,0,0,0,0,0,0,0

In [1884]:
index_s := 2;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,1,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,1,1
3,0,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0,0

In [1887]:
index_s := 3;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,1,0,0,0,0,0
1,0,0,0,1,1,0,0,0
2,0,0,0,0,0,2,1,1
3,0,0,0,1,1,0,0,0
4,0,0,1,0,0,0,0,0

In [1890]:
index_s := 4;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,1,0,0,0,0
1,0,1,1,0,0,1,1,1
2,0,0,0,2,2,0,0,0
3,0,1,1,0,0,1,1,1
4,0,0,0,1,0,0,0,0

In [1893]:
index_s := 5;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,0,1,0,0,0
1,1,0,1,0,0,1,1,1
2,0,0,0,2,2,0,0,0
3,1,0,1,0,0,1,1,1
4,0,0,0,0,1,0,0,0

In [1896]:
index_s := 6;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,0,0,1,0,0
1,0,0,0,1,1,0,0,0
2,0,0,2,0,0,0,1,1
3,0,0,0,1,1,0,0,0
4,0,0,0,0,0,1,0,0

In [1899]:
index_s := 7;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,0,0,0,1,0
1,0,0,0,1,1,0,0,0
2,1,1,1,0,0,1,1,0
3,0,0,0,1,1,0,0,0
4,0,0,0,0,0,0,1,0

In [1902]:
index_s := 8;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,0,0,0,0,1
1,0,0,0,1,1,0,0,0
2,1,1,1,0,0,1,0,1
3,0,0,0,1,1,0,0,0
4,0,0,0,0,0,0,0,1

For a fixed simple module $M_s$, the function retrieves the entry
$d_{sk}^{\,j}$ from the precomputed table $\texttt{data\_s}$.
The index $k$ selects the row corresponding to the simple module $M_k$,
while $j$ selects the column corresponding to the degree $j$.
Thus,
$
\texttt{data\_s}[k].(j)=d_{sk}^{\,j},
\qquad
1\leq k\leq N,\quad 0\leq j\leq\theta.
$

In [1903]:
QGNAG_GradedFusionMultiplicityFromData:=function( data_s, k, j )
    return data_s[k].(String(j));
end;

function( data_s, k, j ) ... end

In [1906]:
index_s := 3;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_GradedFusionMultiplicityFromData(data_s, 8, 4);

0

In [1907]:
Length(data_s);

8

In [1907]:
data_s

Syntax error: ; expected in stream:1

For a fixed simple module $M_s$, the function vectorizes row-wise the
multiplicity table
$$
\bigl(d_{sk}^{\,j}\bigr)_{\substack{1\leq k\leq \theta\\0\leq j\leq\ell}},
$$
where the rows are indexed by the simple modules $M_k$ and the columns
by the degrees $j$. The vector is constructed degree by degree, and for
each degree $j$ it lists the multiplicities for $k=1,\ldots,\theta$:
$$
\varepsilon_s=
\left(
d_{s1}^{0},\ldots,d_{s \theta}^{0},
d_{s1}^{1},\ldots,d_{s \theta}^{1},
\ldots,
d_{s1}^{\ell},\ldots,d_{s \theta}^{\ell}
\right)
\in\mathbb{Q}^{\theta(\ell+1)}.
$$

In [1908]:
QGNAG_GradedFusionVector := function( s, SimplesMn, rec_info )
    local data, epsilon, j, k, theta;
    data    := QGNAG_GradedFusionByDegree( s, SimplesMn, rec_info );
    theta   := Maximum( List( RecNames(rec_info), Int ) );
    epsilon := [];
    for j in [0 .. theta] do
        for k in [1 .. Length(SimplesMn)] do
            Add(epsilon, data[k].(String(j)));
        od;
    od;
    return epsilon;
end;

function( s, SimplesMn, rec_info ) ... end

In [1910]:
index_s   := 1;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,   0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ]

In [1912]:
index_s   := 2;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,   0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ]

In [1914]:
index_s   := 3;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0,   0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ]

In [1916]:
index_s   := 4;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 0,   1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0 ]

In [1918]:
index_s   := 5;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1,   0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0 ]

In [1920]:
index_s   := 6;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0,   0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ]

In [1922]:
index_s   := 7;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,   0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ]

In [1924]:
index_s   := 8;;
epsilon_s := QGNAG_GradedFusionVector( index_s, SimplesMn, rec_info_nichols );

[ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,   0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ]

For a fixed simple module $M_s$, where $s=1,\ldots,\theta$, the data structure
$\texttt{data\_s}$ stores the graded fusion multiplicities
$
\texttt{data\_s}[k].(j)=d_{sk}^{\,j},
\qquad
k=1,\ldots,\theta,\quad j=0,\ldots,\ell.
$
Thus, $\texttt{data\_s}$ is an $(\ell+1)\times \theta$ table whose rows are
indexed by the simple modules $M_k$ and whose columns are indexed by
the degrees $j$.

The function $\texttt{QGNAG\_GradedFusionVectorFromData}$ vectorizes this
precomputed table degree by degree, producing
$$
\varepsilon_s=
\left(
d_{s1}^{0},\ldots,d_{s\theta}^{0},
d_{s1}^{1},\ldots,d_{s\theta}^{1},
\ldots,
d_{s1}^{\ell},\ldots,d_{s\theta}^{\ell}
\right)
\in\mathbb{Q}^{N(\ell+1)}.
$$
Here, $s,k=1,\ldots,N$ index the simple modules, while
$j=0,\ldots,\ell$ indexes the grading of the Nichols algebra.

In [1925]:
QGNAG_GradedFusionVectorFromData := function(data_s, SimplesMn )
    local epsilon, degrees, j, k;
    degrees := List( RecNames(data_s[1]), Int);
    Sort(degrees);
    epsilon := [];
    for j in degrees do
        for k in [1 .. Length(SimplesMn)] do
            Add( epsilon, data_s[k].(String(j)) );
        od;
    od;
    return epsilon;
end;

function( data_s, SimplesMn ) ... end

In [1928]:
index_s := 8;;
data_s  := QGNAG_GradedFusionByDegree( index_s, SimplesMn, rec_info_nichols );;
QGNAG_RecordListToHTMLTable( data_s, true );

,1,2,3,4,5,6,7,8
0,0,0,0,0,0,0,0,1
1,0,0,0,1,1,0,0,0
2,1,1,1,0,0,1,0,1
3,0,0,0,1,1,0,0,0
4,0,0,0,0,0,0,0,1

In [1929]:
QGNAG_GradedFusionVectorFromData(data_s, SimplesMn );

[ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,   0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ]

In [1930]:
TransposedMat([QGNAG_GradedFusionVectorFromData(data_s, SimplesMn )]);

[ [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 1 ], [ 0 ], [ 0 ],   [ 0 ], [ 1 ], [ 1 ], [ 0 ], [ 0 ], [ 0 ], [ 1 ], [ 1 ], [ 1 ], [ 0 ],   [ 0 ], [ 1 ], [ 0 ], [ 1 ], [ 0 ], [ 0 ], [ 0 ], [ 1 ], [ 1 ], [ 0 ],   [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 0 ], [ 1 ] ]

In [1931]:
QGNAG_TestGradedFusionVectorFromData := function( data_s, SimplesMn )
    local expected, actual, degrees, j, k;
    degrees := List( RecNames(data_s[1]), Int );
    Sort(degrees);
    expected := [];
    for j in degrees do
        for k in [1 .. Length(SimplesMn)] do
            Add( expected, data_s[k].(String(j)));
        od;
    od;
    actual   := QGNAG_GradedFusionVectorFromData( data_s, SimplesMn);
    if actual = expected then
        Print("Test passed.\n");
        return true;
    else
        Print("Test failed.\n");
        Print("Expected: ", expected, "\n");
        Print("Actual:   ", actual, "\n");
        return false;
    fi;
end;

function( data_s, SimplesMn ) ... end

In [1932]:
QGNAG_TestGradedFusionVectorFromData( data_s, SimplesMn );

Test passed.

true

In [1933]:
QGNAG_TestGradedFusionVectorFromData := function( data_s, SimplesMn )
    local epsilon, degrees, N, j, k, p;
    epsilon := QGNAG_GradedFusionVectorFromData( data_s, SimplesMn );
    degrees := List( RecNames(data_s[1]), Int );
    Sort(degrees);
    N       := Length(SimplesMn);
    for j in degrees do
        for k in [1 .. N] do
            p := j * N + k;
            if epsilon[p] <> data_s[k].(String(j)) then
                Print("Test failed at j = ", j, ", k = ", k, ".\n");
                return false;
            fi;
        od;
    od;
    Print("Test passed.\n");
    return true;
end;

function( data_s, SimplesMn ) ... end

In [1934]:
QGNAG_TestGradedFusionVectorFromData( data_s, SimplesMn );

Test passed.

true

In [1935]:
QGNAG_Coproduct:=function()
   return;
end;

function(  ) ... end

In [1946]:
nX       := 3;;
nGensOfG := 2;;
nDelta   := 6;;
nY       := 3;;
nTotal   := nX + nGensOfG  +  nDelta + nY;;
F        := FreeAssociativeAlgebraWithOne( Rationals, nTotal );;
gens     := GeneratorsOfAlgebra(F);;
gens := GeneratorsOfAlgebra(F);;
X12 := gens[2];;
X13 := gens[3];;
X23 := gens[4];;

In [1948]:
VW:=GP2NP(X12*X13);
XY:=GP2NP(X13*X23);

[ [ [ 1, 2 ] ], [ 1 ] ]

[ [ [ 2, 3 ] ], [ 1 ] ]

In [1952]:
monos_vw  := VW[1][1];
coeffs_vw := VW[2];
monos_xy  := XY[1][1];
coeffs_xy := XY[2];

[ 1, 2 ]

[ 1 ]

[ 2, 3 ]

[ 1 ]

In [1956]:
idx_v := monos_vw[1];
idx_w := monos_vw[2];
idx_x := monos_xy[1];
idx_y := monos_xy[2];

1

2

2

3

In [1961]:
Print("w_(-1)       := ", ElementSDP(gensA[idx_w], 1), "\n");
Print("X_i          := X_{", gensA[idx_x],"}\n");
Print("w_(-1) * X_i := ", ElementSDP(gensA[idx_w], 1) * gensA[idx_x],"\n");
PrintNP(gensX[idx_x]); 
PrintNP(gensX[Position(gensA, FieldPart(ElementSDP(gensA[idx_w], 1) * gensA[idx_x]))]); 

# falta evaluar chi(w_{(-1)})

w_(-1)       := ( 1 , 1 )
X_i          := X_{Z(3)^0}
w_(-1) * X_i := 1
 X1
 X1