In [ ]:
#LoadPackage("SCSCP");

In [1]:
t0 := NanosecondsSinceEpoch();;

In [2]:
LoadPackage("GBNP");

true

In [3]:
GBNP.ConfigPrint(
    "X0",    # 1 "X_0 = X_0"
    "X1",    # 2 "X_1 = X_1"
    "X2",    # 3 "X_2 = X_w"
    "X3",    # 4 "X_3 = X_{w^2}"
    "t",     # 5 "t = (0, g)"
    "x",     # 6 "x = (0, g^2)"
    "y",     # 7 "y = (w, 0)"
    "z",     # 8 "z = (1, 0)"
    "De",
    "D_(0,1)",
    "D_(0,2)",
    "D_(0,3)",
    "D_(0,4)",
    "D_(0,5)",
    "D_(1,0)",
    "D_(1,1)",
    "D_(1,2)",
    "D_(1,3)",
    "D_(1,4)",
    "D_(1,5)",
    "D_(w,0)",
    "D_(w,1)",
    "D_(w,2)",
    "D_(w,3)",
    "D_(w,4)",
    "D_(w,5)",
    "D_(w^2,0)",
    "D_(w^2,1)",
    "D_(w^2,2)",
    "D_(w^2,3)",
    "D_(w^2,4)",
    "D_(w^2,5)",
    "Y0",        # 1 "Y_0 = Y_0"
    "Y1",        # 2 "Y_1 = Y_1"
    "Y2",        # 3 "Y_2 = Y_w"
    "Y3"         # 4 "Y_3 = Y_{w^2}"
);

## Free Algebra over $\mathbb{Q}$

In [11]:
nX       := 4;;
nGensOfG := 4;;
nDelta   := 24;;
nY       := 4;;
nTotal   := nX + nGensOfG +  nDelta + nY;;
F        := FreeAssociativeAlgebraWithOne(Rationals, nTotal);;
gens     := GeneratorsOfAlgebra(F);;
e        := gens[1];;

### $X_j's$ Generators

In [15]:
X0 := gens[2];;
X1 := gens[3];;
X2 := gens[4];;
X3 := gens[5];;

### Generadores of Group G

In [19]:
F1 := gens[6];;
F2 := gens[7];;
F3 := gens[8];;
F4 := gens[9];;

### Generatos of $\Bbbk^{G}$

In [43]:
De          := gens[10];;  #1 e           (0, 0)
DF1         := gens[11];;  #2 F1          (0, g)
DF2         := gens[12];;  #3 F2          (0, g^2)
DF1F2       := gens[13];;  #6 F1F2        (0, g^3) 
DF2F2       := gens[14];;  #9 F2^2        (0, g^4)
DF1F2F2     := gens[15];;  #13 F1F2^2     (0, g^5) 
DF4         := gens[16];;  #5 F4          (1, 0)
DF4F1       := gens[17];;  #16 F4F1       (1, g)
DF2F3       := gens[18];;  #10 F2F3       (1, g^2)
DF1F2F4     := gens[19];;  #15 F1F2F4     (1, g^3)
DF2F3F2     := gens[20];;  #23 F2F3F2     (1, g^4) 
DF1F2F2F3   := gens[21];;  #20 F1F2^2F3   (1, g^5)
DF3         := gens[22];;  #4 F3          (w, 0)
DF1F4       := gens[23];;  #8 F1F4        (w, g)
DF3F2       := gens[24];;  #19 F3F2       (w, g^2)
DF1F2F3     := gens[25];;  #14 F1F2F3     (w, g^3)
DF2F2F4     := gens[26];;  #18 F2^2F4     (w, g^4)
DF1F2F3F2   := gens[27];;  #24 F1F2F3F2   (w, g^5)
DF3F4       := gens[28];;  #12 F3F4       (w^2, 0)
DF1F3       := gens[29];;  #7 F1F3        (w^2, g)
DF2F4       := gens[30];;  #11 F2F4       (w^2, g^2)
DF1F3F2     := gens[31];;  #22 F1F3F2     (w^2, g^3) 
DF2F2F3     := gens[32];;  #17 F2^2F3     (w^2, g^4)
DF1F2F2F4   := gens[33];;  #23 F1F2^2F4   (w^2, g^5)

### Generatos of $\mathfrak{B}(\overline{V})$

In [43]:
Y0 := gens[34];;
Y1 := gens[35];;
Y2 := gens[36];;
Y3 := gens[37];;

- Generators lists

In [51]:
gensX      := GP2NPList(gens{[2..5]});;
gensG      := GP2NPList(gens{[6..9]});;
gensDeltas := GP2NPList(gens{[10..33]});;
gensY      := GP2NPList(gens{[34..37]});;

In [56]:
xIndex        := [1..4];;
groupElemsInF:=[
    e,               #1 1           (0, 0)
    F1,              #2 F1          (0, g)
    F2,              #3 F2          (0, g^2)
    F1*F2,           #6 F1F2        (0, g^3)
    F2^2,            #9 F2^2        (0, g^4)
    F1*F2^2,         #13 F1F2^2     (0, g^5) 
    F4,              #5 F4          (1, 0)
    F4*F1,           #16 F4F1       (1, g)
    F2*F3,           #10 F2F3       (1, g^2)
    F1*F2*F4,        #15 F1F2F4     (1, g^3)
    F2*F3*F2,        #23 F2F3F2     (1, g^4)
    F1*F2^2*F3,      #20 F1F2^2F3   (1, g^5)  
    F3,              #4 F3          (w, 0)
    F1*F4,           #8 F1F4        (w, g)
    F3*F2,           #19 F3F2       (w, g^2)
    F1*F2*F3,        #14 F1F2F3     (w, g^3)
    F2^2*F4,         #18 F2^2F4     (w, g^4)
    F1*F2^2*F3*F4,   #24 F1F2F3F2   (w, g^5)
    F3*F4,           #12 F3F4       (w^2, 0)
    F1*F3,           #7 F1F3        (w^2, g)
    F2*F4,           #11 F2F4       (w^2, g^2)
    F1*F3*F2,        #22 F1F3F2     (w^2, g^3) 
    F2^2*F3,         #17 F2^2F3     (w^2, g^4)
    F1*F2^2*F4       #23 F1F2^2F4   (w^2, g^5)  
];;
groupIndex     := List(groupElemsInF, elm -> GP2NP(elm)[1][1]);;
deltaIndex     := [9..32];;
yIndex         := [33..36];;

## Tetraedro $\mathcal{T}_{4}$ ($\dim V = 4$).

Sea el quandle $X = \{0,1,2,3\}$, que representa
los vértices de un tetraedro.  
La acción está dada por $i \triangleright j$, donde
$i$ fija $i$ y rota los otros tres elementos por un
tercio de vuelta siguiendo la regla de la mano
izquierda (o derecha, pero con la izquierda resulta
más progresiva).  

El cociclo es $q = -1$.
El álgebra resultante tiene dimensión $72$.  
Está generada por $x_0, x_1, x_2, x_3$ y
satisface las siguientes relaciones:

\begin{align}
x_0^2 = x_1^2 = x_2^2 = x_3^2 &= 0, \\
x_3x_2 + x_2x_1 + x_1x_3 &= 0, \\
x_3x_1 + x_1x_0 + x_0x_3 &= 0, \\
x_3x_0 + x_0x_2 + x_2x_3 &= 0, \\
x_2x_0 + x_0x_1 + x_1x_2 &= 0, \\
x_2x_1x_0x_2x_1x_0 + x_1x_0x_2x_1x_0x_2 + x_0x_2x_1x_0x_2x_1 &= 0.
\end{align}

Una base de esta álgebra se obtiene multiplicando
un elemento de cada fila de arriba hacia abajo en
todas las formas posibles:

\begin{align}
& 1, \; x_0, \\
& 1, \; x_1, \; x_1x_0, \\
& 1, \; x_2, \; x_2x_1x_0, \\
& 1, \; x_2, \; x_2x_1, \\
& 1, \; x_3.
\end{align}

El polinomio de Hilbert de esta álgebra es
$$
(1+t)^2(1+t+t^2)(1+t^3) \;=\; 
t^9 + 4t^8 + 8t^7 + 11t^6 + 12t^5 + 12t^4 + 11t^3 + 8t^2 + 4t + 1.
$$

In [58]:
#!
#! - Tetrahedron Algebra $\mathcal{T}_4$
#! 
#! The relations for the generators $x_i$ of the $T_4$ algebra over
#! $\mathbb{Q}$ are defined as follows:
#! $$
#! \begin{align*}
#!    x_i^2 &= 0 \\
#!    x_i x_j + x_{(\omega+1)i+\omega j} x_i + x_j x_{(\omega+1)i+\omega j} &= 0 \\
#!    (x_2 x_1 x_0)^2 + (x_1 x_0 x_2)^2 + (x_0 x_2 x_1)^2 &= 0
#! \end{align*}
#! $$
#! Where the indices satisfy $\forall i, j \in \mathbb{F}_4$
#! (or the corresponding finite field/#! index set), and $\omega$
#! represents a primitive element of the field.
#!
gensT4      := Elements(GF(4));;
relationsT4 := [];;

In [58]:
#! Step 1: Rels $x_i^2 = 0$
for i in [1..Length(gensT4)] do
    Add(relationsT4, gens[i+1]^2);;
od;

In [60]:
PrintNPList(List(relationsT4, el-> GP2NP(el)));

 X0^2
 X1^2
 X2^2
 X3^2

In [65]:
#! x3x2 + x2x1 + x1x3 = 0,
Add(relationsT4, X3*X2 + X2*X1 + X1*X3 );;
#! x3x1 + x1x0 + x0x3 = 0,
Add(relationsT4, X3*X1 + X1*X0 + X0*X3 );;
#! x3x0 + x0x2 + x2x3 = 0,
Add(relationsT4, X3*X0 + X0*X2 + X2*X3 );;
#! x2x0 + x0x1 + x1x2 = 0,
Add(relationsT4, X2*X0 + X0*X1 + X1*X2 );;
#! x2x1x0x2x1x0 +x1x0x2x1x0x2 +x0x2x1x0x2x1 = 0.
Add(relationsT4, X2*X1*X0*X2*X1*X0+X1*X0*X2*X1*X0*X2+X0*X2*X1*X0*X2*X1 );;

In [67]:
relsT4 := GP2NPList( relationsT4 );;
PrintNPList( relsT4 );

 X0^2
 X1^2
 X2^2
 X3^2
 X3X2 + X2X1 + X1X3
 X3X1 + X1X0 + X0X3
 X3X0 + X2X3 + X0X2
 X2X0 + X1X2 + X0X1
 X2X1X0X2X1X0 + X1X0X2X1X0X2 + X0X2X1X0X2X1

Step 2: Computation of the Gröbner Basis

In [69]:
J_T4 := SGrobner( relsT4 );;
PrintNPList( J_T4 );

 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2^2
 X3X0 + X2X3 + X0X2
 X3X1 + X1X0 + X0X3
 X3X2 + X2X1 + X1X3
 X3^2
 X1X0X1 - X0X1X0
 X2X1X2 - X1X2X1
 X2X1X0X2X1X0 + X1X0X2X1X0X2 + X0X2X1X0X2X1

In [70]:
DimQA( J_T4, 4 );

72

In [72]:
Base_T4 := BaseQA( J_T4, 4, 0 );;
PrintNPList( BaseQA( J_T4, 4, 0 ) );

 1
 X0
 X1
 X2
 X3
 X0X1
 X0X2
 X0X3
 X1X0
 X1X2
 X1X3
 X2X1
 X2X3
 X0X1X0
 X0X1X2
 X0X1X3
 X0X2X1
 X0X2X3
 X1X0X2
 X1X0X3
 X1X2X1
 X1X2X3
 X2X1X0
 X2X1X3
 X0X1X0X2
 X0X1X0X3
 X0X1X2X1
 X0X1X2X3
 X0X2X1X0
 X0X2X1X3
 X1X0X2X1
 X1X0X2X3
 X1X2X1X0
 X1X2X1X3
 X2X1X0X2
 X2X1X0X3
 X0X1X0X2X1
 X0X1X0X2X3
 X0X1X2X1X0
 X0X1X2X1X3
 X0X2X1X0X2
 X0X2X1X0X3
 X1X0X2X1X0
 X1X0X2X1X3
 X1X2X1X0X2
 X1X2X1X0X3
 X2X1X0X2X1
 X2X1X0X2X3
 X0X1X0X2X1X0
 X0X1X0X2X1X3
 X0X1X2X1X0X2
 X0X1X2X1X0X3
 X0X2X1X0X2X1
 X0X2X1X0X2X3
 X1X0X2X1X0X2
 X1X0X2X1X0X3
 X1X2X1X0X2X1
 X1X2X1X0X2X3
 X2X1X0X2X1X3
 X0X1X0X2X1X0X2
 X0X1X0X2X1X0X3
 X0X1X2X1X0X2X1
 X0X1X2X1X0X2X3
 X0X2X1X0X2X1X3
 X1X0X2X1X0X2X1
 X1X0X2X1X0X2X3
 X1X2X1X0X2X1X3
 X0X1X0X2X1X0X2X1
 X0X1X0X2X1X0X2X3
 X0X1X2X1X0X2X1X3
 X1X0X2X1X0X2X1X3
 X0X1X0X2X1X0X2X1X3

# Calculo de $\mathfrak{B}(\overline{V})$

In [74]:
###############################################################################
# x_(ij)^2 = 0, x_(ij)x_(jk)+x_(jk)x_(ik)+x_(ik)x_(ij)=0, etc. 
# (álgebra Fomin-Kirillov n=3,
###############################################################################
# Generadores x_j
relationsT4dual := [];;

# Paso 1: Relaciones cuadráticas x_j^2 = 0
for j in [1..Length(gensT4)] do
    Add(relationsT4dual, gens[yIndex[j]+1]^2);;
od;

In [75]:
PrintNPList(List(relationsT4dual, el-> GP2NP(el)));

 Y0^2
 Y1^2
 Y2^2
 Y3^2

In [80]:
## x3x2 + x2x1 + x1x3 = 0,
## Y2Y3 + Y1Y2 + Y3Y1 = 0,
Add(relationsT4dual, Y2*Y3 + Y1*Y2 + Y3*Y1 );;
## x3x1 + x1x0 + x0x3 = 0,
## Y1Y3 + Y0Y1 + Y3Y0 = 0,
Add(relationsT4dual, Y1*Y3 + Y0*Y1 + Y3*Y0 );;
## x3x0 + x0x2 + x2x3 = 0,
## Y0Y3+ Y2Y0 + Y3Y2 = 0,
Add(relationsT4dual, Y0*Y3 + Y2*Y0 + Y3*Y2 );;
## x2x0 + x0x1 + x1x2 = 0,
## Y0Y2 + Y1Y0 + Y2Y1 = 0,
Add(relationsT4dual, Y0*Y2 + Y1*Y0 + Y2*Y1 );;
## x2x1x0x2x1x0 + x1x0x2x1x0x2 +x0x2x1x0x2x1 = 0.
# Add(relationsT4dual, Y3*Y1*Y0*Y3*Y1*Y0 + Y1*Y0*Y3*Y1*Y0*Y3 + Y0*Y3*Y1*Y0*Y3*Y1 );;
## x2x1x0x2x1x0 + x1x0x2x1x0x2 +x0x2x1x0x2x1 = 0.
## Y0Y1Y2Y0Y1Y2 + Y2Y0Y1Y2Y0Y1 + Y1Y2Y0Y1Y2Y0 = 0.
Add(relationsT4dual, Y0*Y1*Y2*Y0*Y1*Y2 + Y2*Y0*Y1*Y2*Y0*Y1 + Y1*Y2*Y0*Y1*Y2*Y0 );;

In [82]:
# Imprimir las relaciones
relsT4dual := GP2NPList(relationsT4dual);;
PrintNPList(relsT4dual);

 Y0^2
 Y1^2
 Y2^2
 Y3^2
 Y3Y1 + Y2Y3 + Y1Y2
 Y3Y0 + Y1Y3 + Y0Y1
 Y3Y2 + Y2Y0 + Y0Y3
 Y2Y1 + Y1Y0 + Y0Y2
 Y2Y0Y1Y2Y0Y1 + Y1Y2Y0Y1Y2Y0 + Y0Y1Y2Y0Y1Y2

In [83]:
I := Concatenation(
    gensX,
    gensG,
    gensDeltas,
    relsT4dual    # 9 rels
);;

In [84]:
J := SGrobner(I);;

In [85]:
DimQA(J, 36);

72

In [86]:
PrintNPList( BaseQA( J, 36, 0 ) );

 1
 Y0
 Y1
 Y2
 Y3
 Y0Y1
 Y0Y2
 Y0Y3
 Y1Y0
 Y1Y2
 Y1Y3
 Y2Y0
 Y2Y3
 Y0Y1Y0
 Y0Y1Y2
 Y0Y1Y3
 Y0Y2Y0
 Y0Y2Y3
 Y1Y0Y2
 Y1Y0Y3
 Y1Y2Y0
 Y1Y2Y3
 Y2Y0Y1
 Y2Y0Y3
 Y0Y1Y0Y2
 Y0Y1Y0Y3
 Y0Y1Y2Y0
 Y0Y1Y2Y3
 Y0Y2Y0Y1
 Y0Y2Y0Y3
 Y1Y0Y2Y0
 Y1Y0Y2Y3
 Y1Y2Y0Y1
 Y1Y2Y0Y3
 Y2Y0Y1Y2
 Y2Y0Y1Y3
 Y0Y1Y0Y2Y0
 Y0Y1Y0Y2Y3
 Y0Y1Y2Y0Y1
 Y0Y1Y2Y0Y3
 Y0Y2Y0Y1Y2
 Y0Y2Y0Y1Y3
 Y1Y0Y2Y0Y1
 Y1Y0Y2Y0Y3
 Y1Y2Y0Y1Y2
 Y1Y2Y0Y1Y3
 Y2Y0Y1Y2Y0
 Y2Y0Y1Y2Y3
 Y0Y1Y0Y2Y0Y1
 Y0Y1Y0Y2Y0Y3
 Y0Y1Y2Y0Y1Y2
 Y0Y1Y2Y0Y1Y3
 Y0Y2Y0Y1Y2Y0
 Y0Y2Y0Y1Y2Y3
 Y1Y0Y2Y0Y1Y2
 Y1Y0Y2Y0Y1Y3
 Y1Y2Y0Y1Y2Y0
 Y1Y2Y0Y1Y2Y3
 Y2Y0Y1Y2Y0Y3
 Y0Y1Y0Y2Y0Y1Y2
 Y0Y1Y0Y2Y0Y1Y3
 Y0Y1Y2Y0Y1Y2Y0
 Y0Y1Y2Y0Y1Y2Y3
 Y0Y2Y0Y1Y2Y0Y3
 Y1Y0Y2Y0Y1Y2Y0
 Y1Y0Y2Y0Y1Y2Y3
 Y1Y2Y0Y1Y2Y0Y3
 Y0Y1Y0Y2Y0Y1Y2Y0
 Y0Y1Y0Y2Y0Y1Y2Y3
 Y0Y1Y2Y0Y1Y2Y0Y3
 Y1Y0Y2Y0Y1Y2Y0Y3
 Y0Y1Y0Y2Y0Y1Y2Y0Y3

# Calculo $\Bbbk G$

## El grupo $\mathbb{F}_4 \rtimes_{\omega} C_6$

Let $G$ be a group generated by the elements
$$
G = \langle f_1, f_2, f_3, f_4 \rangle,
$$
subject to the following relationships:
\begin{align*}
& f_3^2 = e, \quad f_4^2 = e, \quad f_2^3 = e, \\
& f_1^2 = f_2, \\
& f_1 f_4 f_1^{-1} = f_3, \\
& (f_3 f_4)^2 = e, \\
& f_1 f_3 f_1^{-1} = f_3 f_4.
\end{align*}
The group's presentation can be written as
$$
G = \left\langle
f_1, f_2, f_3, f_4 \;\middle|\;
\begin{array}{l}
f_3^2 = f_4^2 = f_2^3 = (f_3 f_4)^2 = e, \quad f_1^2 = f_2, \\[0.3em]
f_1 f_4 f_1^{-1} = f_3, \quad f_1 f_3 f_1^{-1} = f_3 f_4
\end{array}
\right\rangle.
$$
This group has a size of $|G| = 24$, and can be interpreted as a semi-direct product
$$
G \simeq \mathbb{F}_4 \rtimes C_6,
$$
where the subgroup
$$
\mathbb{F}_4 = \langle f_3, f_4 \rangle
$$
is generated by two commutative involutions, and
$$
C_6 = \langle f_1 \rangle
$$
is a cyclic group of order $6$.

The action
$$
T : C_6 \longrightarrow \operatorname{Aut}(\mathbb{F}_4)
$$
is  given by
$$
T(f_1)(a) = \omega(a),
$$
where $\omega$ is the automorphism of the group $\mathbb{F}_4$
induced by $f_1$. In general, for an exponent $s \in \mathbb{Z}$,
the following holds
$$
T(f_1^s)(a) = \omega^s(a),
$$
so that the action of the generator of $C_6$ on $\mathbb{F}_4$ is
described by the iteration of the automorphism $\omega$.

In [86]:
relsGroup := [
    F3^2-e,            # 1
    F4^2-e,            # 2
    F2^3-e,            # 3
    F1^2*F2^2-e,       # 4
    F1*F4*F1^5*F3-e,   # 5
    (F3*F4)^2-e,       # 6
    F3*F1*F3*F1^5*F4-e # 7
];;

In [89]:
relsGroup := GP2NPList( relsGroup );;
PrintNPList( relsGroup );

 y^2 - 1
 z^2 - 1
 x^3 - 1
 t^2x^2 - 1
 tzt^5y - 1
 yzyz - 1
 ytyt^5z - 1

In [90]:
J := SGrobner(Concatenation(
    relsGroup,
    gensX,
    # gensG,
    gensDeltas,
    gensY
    )
);;

In [91]:
PrintNPList( J );

 X0
 X1
 X2
 X3
 De
 D_(0,1)
 D_(0,2)
 D_(0,3)
 D_(0,4)
 D_(0,5)
 D_(1,0)
 D_(1,1)
 D_(1,2)
 D_(1,3)
 D_(1,4)
 D_(1,5)
 D_(w,0)
 D_(w,1)
 D_(w,2)
 D_(w,3)
 D_(w,4)
 D_(w,5)
 D_(w^2,0)
 D_(w^2,1)
 D_(w^2,2)
 D_(w^2,3)
 D_(w^2,4)
 D_(w^2,5)
 Y0
 Y1
 Y2
 Y3
 t^2 - x
 xt - tx
 yt - tz
 y^2 - 1
 zx - xy
 zy - yz
 z^2 - 1
 tyz - zt
 tzt - yx
 x^3 - 1
 xyz - yx
 xzt - tyx
 yx^2 - x^2z
 yxy - xz
 yxz - xy
 yzt - ty
 ztx - txz
 zty - tz
 ztz - ty
 x^2yx - yz

In [92]:
DimQA(J, 36);

24

In [93]:
PrintNPList(BaseQA(J, 36, 0));

 1
 t
 x
 y
 z
 tx
 ty
 tz
 x^2
 xy
 xz
 yx
 yz
 zt
 tx^2
 txy
 txz
 tyx
 x^2y
 x^2z
 xyx
 tx^2y
 tx^2z
 txyx

## Relaciones dadas por $\Bbbk^{G}$.

In [1]:
LoadPackage( "QGNAG" );

true

In [95]:
config := rec(
    m            := 6,                   # Valor para m
    q            := 4,                   # Valor para q := p^n
    xIndex       := xIndex,
    groupIndex   := groupIndex,
    deltaIndex   := deltaIndex,
    yIndex       := yIndex,
    nX           := nX,
    nGensOfG     := nGensOfG,
    nDelta       := nDelta,
    nY           := nY,
    DEFAULT      := false,
    TEST         := false,
    PROD         := false,
    DEV          := true,
);;

In [96]:
QGNAGSetConfig(config);

In [97]:
QGNAGShowConfig();

========================================
         QGNAG CONFIGURATION
========================================

Base Structures
---------------
Cyclic group order (C_m)     : 6
Finite field size (q = p^n)  : 4

Derived Objects
---------------
Cyclic ring            : Z/6Z
Finite field           : GF(4)

Index Sets
----------
xIndex     : [ 1 .. 4 ]
groupIndex : [ [  ], [ 5 ], [ 6 ], [ 5, 6 ], [ 6, 6 ], [ 5, 6, 6 ], [ 8 ],
  [ 8, 5 ], [ 6, 7 ], [ 5, 6, 8 ], [ 6, 7, 6 ], [ 5, 6, 6, 7 ], [ 7 ],
  [ 5, 8 ], [ 7, 6 ], [ 5, 6, 7 ], [ 6, 6, 8 ], [ 5, 6, 6, 7, 8 ], [ 7, 8 ],
  [ 5, 7 ], [ 6, 8 ], [ 5, 7, 6 ], [ 6, 6, 7 ], [ 5, 6, 6, 8 ] ]
deltaIndex : [ 9 .. 32 ]
yIndex     : [ 33 .. 36 ]

Dimensions
----------
Number of x generators       : 4
Number of group generators   : 4
Number of delta generators   : 24
Number of y generators       : 4

Elements Of Group
---------------
Elements:
( 0 , 0 )
( 0 , 1 )
( 0 , 2 )
( 0 , 3 )
( 0 , 4 )
( 0 , 5 )
( 1 , 0 )
( 1 , 1 )
( 1 , 2 )
( 1 , 3 )
( 1 , 4 )
( 1 , 5 )
( ζ_3 , 0 )
( ζ_3 , 1 )
( ζ_3 , 2 )
( ζ_3 , 3 )
( ζ_3 , 4 )
( ζ_3 , 5 )
( ζ_3^2 , 0 )
( ζ_3^2 , 1 )
( ζ_3^2 , 2 )
( ζ_3^2 , 3 )
( ζ_3^2 , 4 )
( ζ_3^2 , 5 )

Nichols Algebra
---------------
Number of j generators: [ 0, 1, ζ_3, ζ_3^2 ]

========================================

## The Algebra $\Bbbk^G$

We define the structure of the algebra $\Bbbk^G$ over the field $\Bbbk$.

## Relaciones dadas por $\Bbbk^{G}$.

### Álgebra de funciones sobre el grupo $G$

Sea $\Bbbk$ un cuerpo (por ejemplo $\Bbbk = \mathbb{Q}$). 
Se define el álgebra de funciones sobre el grupo
simétrico $G$ como
$$
\Bbbk^{G} = \{ f : G \to \Bbbk \},
$$
con la multiplicación puntual dada por
$$
(fg)(x) = f(x) g(x), \quad \text{para todo } x \in G.
$$

El álgebra $\Bbbk^G$ es el \emph{dual algebraico}
del álgebra de grupo $kG$, es decir, $\Bbbk^{G}
= (\Bbbk G)^{*}$.

#### Base y relaciones de $\Bbbk^{G}$

El álgebra $\Bbbk^{G}$ tiene una base natural dada
por las funciones delta
$$
\{ \delta_g \mid g \in G \},
$$
donde cada $\delta_g$ se define como
$$
\delta_g(h) =
\begin{cases}
1, & \text{si } h = g, \\[4pt]
0, & \text{si } h \ne g.
\end{cases}
$$
Estas funciones satisfacen las siguientes relaciones:

1. Idempotencia:
$$
\delta_g^2 = \delta_g.
$$
2. Ortogonalidad:
$$
\delta_g \delta_h = 0, \quad \text{si } g \ne h.
$$
3. Conmutatividad:
$$
\delta_g \delta_h = \delta_h \delta_g.
$$
Esta propiedad se deduce automáticamente de las anteriores, 
pues si $g = h$ ambos productos son $\delta_g$, y si $g \ne h$
ambos son cero.

4. _Relación de unidad_:
$$
\sum_{g \in G} \delta_g = 1.
$$

Las relaciones anteriores implican que los elementos $\delta_g$
son *idempotentes ortogonales*. En particular,
$\Bbbk^{G}$ es un álgebra conmutativa y semisimple,
isomorfa a una suma directa de copias del cuerpo:
$$
\Bbbk^{G} \cong \Bbbk^{|G|}.
$$

In [100]:
relskG     := RelationsOfkGdual(deltaIndex);;
Print("Generated ", Length(relskG), " relations in k^G.\n");
PrintNPList(relskG);

Generated 577 relations in k^G.
 De^2 - De
 DeD_(0,1)
 DeD_(0,2)
 DeD_(0,3)
 DeD_(0,4)
 DeD_(0,5)
 DeD_(1,0)
 DeD_(1,1)
 DeD_(1,2)
 DeD_(1,3)
 DeD_(1,4)
 DeD_(1,5)
 DeD_(w,0)
 DeD_(w,1)
 DeD_(w,2)
 DeD_(w,3)
 DeD_(w,4)
 DeD_(w,5)
 DeD_(w^2,0)
 DeD_(w^2,1)
 DeD_(w^2,2)
 DeD_(w^2,3)
 DeD_(w^2,4)
 DeD_(w^2,5)
 D_(0,1)De
 D_(0,1)^2 - D_(0,1)
 D_(0,1)D_(0,2)
 D_(0,1)D_(0,3)
 D_(0,1)D_(0,4)
 D_(0,1)D_(0,5)
 D_(0,1)D_(1,0)
 D_(0,1)D_(1,1)
 D_(0,1)D_(1,2)
 D_(0,1)D_(1,3)
 D_(0,1)D_(1,4)
 D_(0,1)D_(1,5)
 D_(0,1)D_(w,0)
 D_(0,1)D_(w,1)
 D_(0,1)D_(w,2)
 D_(0,1)D_(w,3)
 D_(0,1)D_(w,4)
 D_(0,1)D_(w,5)
 D_(0,1)D_(w^2,0)
 D_(0,1)D_(w^2,1)
 D_(0,1)D_(w^2,2)
 D_(0,1)D_(w^2,3)
 D_(0,1)D_(w^2,4)
 D_(0,1)D_(w^2,5)
 D_(0,2)De
 D_(0,2)D_(0,1)
 D_(0,2)^2 - D_(0,2)
 D_(0,2)D_(0,3)
 D_(0,2)D_(0,4)
 D_(0,2)D_(0,5)
 D_(0,2)D_(1,0)
 D_(0,2)D_(1,1)
 D_(0,2)D_(1,2)
 D_(0,2)D_(1,3)
 D_(0,2)D_(1,4)
 D_(0,2)D_(1,5)
 D_(0,2)D_(w,0)
 D_(0,2)D_(w,1)
 D_(0,2)D_(w,2)
 D_(0,2)D_(w,3)
 D_(0,2)D_(w,4)
 D_(0,2)D_(w,5)
 D_(0,2)D_(w^2,0)
 D_(0,2)D_(w^2,1)
 D_(0,2)D_(w^2,2)
 D_(0,2)D_(w^2,3)
 D_(0,2)D_(w^2,4)
 D_(0,2)D_(w^2,5)
 D_(0,3)De
 D_(0,3)D_(0,1)
 D_(0,3)D_(0,2)
 D_(0,3)^2 - D_(0,3)
 D_(0,3)D_(0,4)
 D_(0,3)D_(0,5)
 D_(0,3)D_(1,0)
 D_(0,3)D_(1,1)
 D_(0,3)D_(1,2)
 D_(0,3)D_(1,3)
 D_(0,3)D_(1,4)
 D_(0,3)D_(1,5)
 D_(0,3)D_(w,0)
 D_(0,3)D_(w,1)
 D_(0,3)D_(w,2)
 D_(0,3)D_(w,3)
 D_(0,3)D_(w,4)
 D_(0,3)D_(w,5)
 D_(0,3)D_(w^2,0)
 D_(0,3)D_(w^2,1)
 D_(0,3)D_(w^2,2)
 D_(0,3)D_(w^2,3)
 D_(0,3)D_(w^2,4)
 D_(0,3)D_(w^2,5)
 D_(0,4)De
 D_(0,4)D_(0,1)
 D_(0,4)D_(0,2)
 D_(0,4)D_(0,3)
 D_(0,4)^2 - D_(0,4)
 D_(0,4)D_(0,5)
 D_(0,4)D_(1,0)
 D_(0,4)D_(1,1)
 D_(0,4)D_(1,2)
 D_(0,4)D_(1,3)
 D_(0,4)D_(1,4)
 D_(0,4)D_(1,5)
 D_(0,4)D_(w,0)
 D_(0,4)D_(w,1)
 D_(0,4)D_(w,2)
 D_(0,4)D_(w,3)
 D_(0,4)D_(w,4)
 D_(0,4)D_(w,5)
 D_(0,4)D_(w^2,0)
 D_(0,4)D_(w^2,1)
 D_(0,4)D_(w^2,2)
 D_(0,4)D_(w^2,3)
 D_(0,4)D_(w^2,4)
 D_(0,4)D_(w^2,5)
 D_(0,5)De
 D_(0,5)D_(0,1)
 D_(0,5)D_(0,2)
 D_(0,5)D_(0,3)
 D_(0,5)D_(0,4)
 D_(0,5)^2 - D_(0,5)
 D_(0,5)D_(1,0)
 D_(0,5)D_(1,1)
 D_(0,5)D_(1,2)
 D_(0,5)D_(1,3)
 D_(0,5)D_(1,4)
 D_(0,5)D_(1,5)
 D_(0,5)D_(w,0)
 D_(0,5)D_(w,1)
 D_(0,5)D_(w,2)
 D_(0,5)D_(w,3)
 D_(0,5)D_(w,4)
 D_(0,5)D_(w,5)
 D_(0,5)D_(w^2,0)
 D_(0,5)D_(w^2,1)
 D_(0,5)D_(w^2,2)
 D_(0,5)D_(w^2,3)
 D_(0,5)D_(w^2,4)
 D_(0,5)D_(w^2,5)
 D_(1,0)De
 D_(1,0)D_(0,1)
 D_(1,0)D_(0,2)
 D_(1,0)D_(0,3)
 D_(1,0)D_(0,4)
 D_(1,0)D_(0,5)
 D_(1,0)^2 - D_(1,0)
 D_(1,0)D_(1,1)
 D_(1,0)D_(1,2)
 D_(1,0)D_(1,3)
 D_(1,0)D_(1,4)
 D_(1,0)D_(1,5)
 D_(1,0)D_(w,0)
 D_(1,0)D_(w,1)
 D_(1,0)D_(w,2)
 D_(1,0)D_(w,3)
 D_(1,0)D_(w,4)
 D_(1,0)D_(w,5)
 D_(1,0)D_(w^2,0)
 D_(1,0)D_(w^2,1)
 D_(1,0)D_(w^2,2)
 D_(1,0)D_(w^2,3)
 D_(1,0)D_(w^2,4)
 D_(1,0)D_(w^2,5)
 D_(1,1)De
 D_(1,1)D_(0,1)
 D_(1,1)D_(0,2)
 D_(1,1)D_(0,3)
 D_(1,1)D_(0,4)
 D_(1,1)D_(0,5)
 D_(1,1)D_(1,0)
 D_(1,1)^2 - D_(1,1)
 D_(1,1)D_(1,2)
 D_(1,1)D_(1,3)
 D_(1,1)D_(1,4)
 D_(1,1)D_(1,5)
 D_(1,1)D_(w,0)
 D_(1,1)D_(w,1)
 D_(1,1)D_(w,2)
 D_(1,1)D_(w,3)
 D_(1,1)D_(w,4)
 D_(1,1)D_(w,5)
 D_(1,1)D_(w^2,0)
 D_(1,1)D_(w^2,1)
 D_(1,1)D_(w^2,2)
 D_(1,1)D_(w^2,3)
 D_(1,1)D_(w^2,4)
 D_(1,1)D_(w^2,5)
 D_(1,2)De
 D_(1,2)D_(0,1)
 D_(1,2)D_(0,2)
 D_(1,2)D_(0,3)
 D_(1,2)D_(0,4)
 D_(1,2)D_(0,5)
 D_(1,2)D_(1,0)
 D_(1,2)D_(1,1)
 D_(1,2)^2 - D_(1,2)
 D_(1,2)D_(1,3)
 D_(1,2)D_(1,4)
 D_(1,2)D_(1,5)
 D_(1,2)D_(w,0)
 D_(1,2)D_(w,1)
 D_(1,2)D_(w,2)
 D_(1,2)D_(w,3)
 D_(1,2)D_(w,4)
 D_(1,2)D_(w,5)
 D_(1,2)D_(w^2,0)
 D_(1,2)D_(w^2,1)
 D_(1,2)D_(w^2,2)
 D_(1,2)D_(w^2,3)
 D_(1,2)D_(w^2,4)
 D_(1,2)D_(w^2,5)
 D_(1,3)De
 D_(1,3)D_(0,1)
 D_(1,3)D_(0,2)
 D_(1,3)D_(0,3)
 D_(1,3)D_(0,4)
 D_(1,3)D_(0,5)
 D_(1,3)D_(1,0)
 D_(1,3)D_(1,1)
 D_(1,3)D_(1,2)
 D_(1,3)^2 - D_(1,3)
 D_(1,3)D_(1,4)
 D_(1,3)D_(1,5)
 D_(1,3)D_(w,0)
 D_(1,3)D_(w,1)
 D_(1,3)D_(w,2)
 D_(1,3)D_(w,3)
 D_(1,3)D_(w,4)
 D_(1,3)D_(w,5)
 D_(1,3)D_(w^2,0)
 D_(1,3)D_(w^2,1)
 D_(1,3)D_(w^2,2)
 D_(1,3)D_(w^2,3)
 D_(1,3)D_(w^2,4)
 D_(1,3)D_(w^2,5)
 D_(1,4)De
 D_(1,4)D_(0,1)
 D_(1,4)D_(0,2)
 D_(1,4)D_(0,3)
 D_(1,4)D_(0,4)
 D_(1,4)D_(0,5)
 D_(1,4)D_(1,0)
 D_(1,4)D_(1,1)
 D_(1,4)D_(1,2)
 D_(1,4)D_(1,3)
 D_(1,4)^2 - D_(1,4)
 D_(1,4)D_(1,5)
 D_(1,4)D_(w,0)
 D_(1,4)D_(w,1)
 D_(1,4)D_(w,2)
 D_(1,4)D_(w,3)
 D_(1,4)D_(w,4)
 D_(1,4)D_(w,5)
 D_(1,4)D_(w^2,0)
 D_(1,4)D_(w^2,1)
 D_(1,4)D_(w^2,2)
 D_(1,4)D_(w^2,3)
 D_(1,4)D_(w^2,4)
 D_(1,4)D_(w^2,5)
 D_(1,5)De
 D_(1,5)D_(0,1)
 D_(1,5)D_(0,2)
 D_(1,5)D_(0,3)
 D_(1,5)D_(0,4)
 D_(1,5)D_(0,5)
 D_(1,5)D_(1,0)
 D_(1,5)D_(1,1)
 D_(1,5)D_(1,2)
 D_(1,5)D_(1,3)
 D_(1,5)D_(1,4)
 D_(1,5)^2 - D_(1,5)
 D_(1,5)D_(w,0)
 D_(1,5)D_(w,1)
 D_(1,5)D_(w,2)
 D_(1,5)D_(w,3)
 D_(1,5)D_(w,4)
 D_(1,5)D_(w,5)
 D_(1,5)D_(w^2,0)
 D_(1,5)D_(w^2,1)
 D_(1,5)D_(w^2,2)
 D_(1,5)D_(w^2,3)
 D_(1,5)D_(w^2,4)
 D_(1,5)D_(w^2,5)
 D_(w,0)De
 D_(w,0)D_(0,1)
 D_(w,0)D_(0,2)
 D_(w,0)D_(0,3)
 D_(w,0)D_(0,4)
 D_(w,0)D_(0,5)
 D_(w,0)D_(1,0)
 D_(w,0)D_(1,1)
 D_(w,0)D_(1,2)
 D_(w,0)D_(1,3)
 D_(w,0)D_(1,4)
 D_(w,0)D_(1,5)
 D_(w,0)^2 - D_(w,0)
 D_(w,0)D_(w,1)
 D_(w,0)D_(w,2)
 D_(w,0)D_(w,3)
 D_(w,0)D_(w,4)
 D_(w,0)D_(w,5)
 D_(w,0)D_(w^2,0)
 D_(w,0)D_(w^2,1)
 D_(w,0)D_(w^2,2)
 D_(w,0)D_(w^2,3)
 D_(w,0)D_(w^2,4)
 D_(w,0)D_(w^2,5)
 D_(w,1)De
 D_(w,1)D_(0,1)
 D_(w,1)D_(0,2)
 D_(w,1)D_(0,3)
 D_(w,1)D_(0,4)
 D_(w,1)D_(0,5)
 D_(w,1)D_(1,0)
 D_(w,1)D_(1,1)
 D_(w,1)D_(1,2)
 D_(w,1)D_(1,3)
 D_(w,1)D_(1,4)
 D_(w,1)D_(1,5)
 D_(w,1)D_(w,0)
 D_(w,1)^2 - D_(w,1)
 D_(w,1)D_(w,2)
 D_(w,1)D_(w,3)
 D_(w,1)D_(w,4)
 D_(w,1)D_(w,5)
 D_(w,1)D_(w^2,0)
 D_(w,1)D_(w^2,1)
 D_(w,1)D_(w^2,2)
 D_(w,1)D_(w^2,3)
 D_(w,1)D_(w^2,4)
 D_(w,1)D_(w^2,5)
 D_(w,2)De
 D_(w,2)D_(0,1)
 D_(w,2)D_(0,2)
 D_(w,2)D_(0,3)
 D_(w,2)D_(0,4)
 D_(w,2)D_(0,5)
 D_(w,2)D_(1,0)
 D_(w,2)D_(1,1)
 D_(w,2)D_(1,2)
 D_(w,2)D_(1,3)
 D_(w,2)D_(1,4)
 D_(w,2)D_(1,5)
 D_(w,2)D_(w,0)
 D_(w,2)D_(w,1)
 D_(w,2)^2 - D_(w,2)
 D_(w,2)D_(w,3)
 D_(w,2)D_(w,4)
 D_(w,2)D_(w,5)
 D_(w,2)D_(w^2,0)
 D_(w,2)D_(w^2,1)
 D_(w,2)D_(w^2,2)
 D_(w,2)D_(w^2,3)
 D_(w,2)D_(w^2,4)
 D_(w,2)D_(w^2,5)
 D_(w,3)De
 D_(w,3)D_(0,1)
 D_(w,3)D_(0,2)
 D_(w,3)D_(0,3)
 D_(w,3)D_(0,4)
 D_(w,3)D_(0,5)
 D_(w,3)D_(1,0)
 D_(w,3)D_(1,1)
 D_(w,3)D_(1,2)
 D_(w,3)D_(1,3)
 D_(w,3)D_(1,4)
 D_(w,3)D_(1,5)
 D_(w,3)D_(w,0)
 D_(w,3)D_(w,1)
 D_(w,3)D_(w,2)
 D_(w,3)^2 - D_(w,3)
 D_(w,3)D_(w,4)
 D_(w,3)D_(w,5)
 D_(w,3)D_(w^2,0)
 D_(w,3)D_(w^2,1)
 D_(w,3)D_(w^2,2)
 D_(w,3)D_(w^2,3)
 D_(w,3)D_(w^2,4)
 D_(w,3)D_(w^2,5)
 D_(w,4)De
 D_(w,4)D_(0,1)
 D_(w,4)D_(0,2)
 D_(w,4)D_(0,3)
 D_(w,4)D_(0,4)
 D_(w,4)D_(0,5)
 D_(w,4)D_(1,0)
 D_(w,4)D_(1,1)
 D_(w,4)D_(1,2)
 D_(w,4)D_(1,3)
 D_(w,4)D_(1,4)
 D_(w,4)D_(1,5)
 D_(w,4)D_(w,0)
 D_(w,4)D_(w,1)
 D_(w,4)D_(w,2)
 D_(w,4)D_(w,3)
 D_(w,4)^2 - D_(w,4)
 D_(w,4)D_(w,5)
 D_(w,4)D_(w^2,0)
 D_(w,4)D_(w^2,1)
 D_(w,4)D_(w^2,2)
 D_(w,4)D_(w^2,3)
 D_(w,4)D_(w^2,4)
 D_(w,4)D_(w^2,5)
 D_(w,5)De
 D_(w,5)D_(0,1)
 D_(w,5)D_(0,2)
 D_(w,5)D_(0,3)
 D_(w,5)D_(0,4)
 D_(w,5)D_(0,5)
 D_(w,5)D_(1,0)
 D_(w,5)D_(1,1)
 D_(w,5)D_(1,2)
 D_(w,5)D_(1,3)
 D_(w,5)D_(1,4)
 D_(w,5)D_(1,5)
 D_(w,5)D_(w,0)
 D_(w,5)D_(w,1)
 D_(w,5)D_(w,2)
 D_(w,5)D_(w,3)
 D_(w,5)D_(w,4)
 D_(w,5)^2 - D_(w,5)
 D_(w,5)D_(w^2,0)
 D_(w,5)D_(w^2,1)
 D_(w,5)D_(w^2,2)
 D_(w,5)D_(w^2,3)
 D_(w,5)D_(w^2,4)
 D_(w,5)D_(w^2,5)
 D_(w^2,0)De
 D_(w^2,0)D_(0,1)
 D_(w^2,0)D_(0,2)
 D_(w^2,0)D_(0,3)
 D_(w^2,0)D_(0,4)
 D_(w^2,0)D_(0,5)
 D_(w^2,0)D_(1,0)
 D_(w^2,0)D_(1,1)
 D_(w^2,0)D_(1,2)
 D_(w^2,0)D_(1,3)
 D_(w^2,0)D_(1,4)
 D_(w^2,0)D_(1,5)
 D_(w^2,0)D_(w,0)
 D_(w^2,0)D_(w,1)
 D_(w^2,0)D_(w,2)
 D_(w^2,0)D_(w,3)
 D_(w^2,0)D_(w,4)
 D_(w^2,0)D_(w,5)
 D_(w^2,0)^2 - D_(w^2,0)
 D_(w^2,0)D_(w^2,1)
 D_(w^2,0)D_(w^2,2)
 D_(w^2,0)D_(w^2,3)
 D_(w^2,0)D_(w^2,4)
 D_(w^2,0)D_(w^2,5)
 D_(w^2,1)De
 D_(w^2,1)D_(0,1)
 D_(w^2,1)D_(0,2)
 D_(w^2,1)D_(0,3)
 D_(w^2,1)D_(0,4)
 D_(w^2,1)D_(0,5)
 D_(w^2,1)D_(1,0)
 D_(w^2,1)D_(1,1)
 D_(w^2,1)D_(1,2)
 D_(w^2,1)D_(1,3)
 D_(w^2,1)D_(1,4)
 D_(w^2,1)D_(1,5)
 D_(w^2,1)D_(w,0)
 D_(w^2,1)D_(w,1)
 D_(w^2,1)D_(w,2)
 D_(w^2,1)D_(w,3)
 D_(w^2,1)D_(w,4)
 D_(w^2,1)D_(w,5)
 D_(w^2,1)D_(w^2,0)
 D_(w^2,1)^2 - D_(w^2,1)
 D_(w^2,1)D_(w^2,2)
 D_(w^2,1)D_(w^2,3)
 D_(w^2,1)D_(w^2,4)
 D_(w^2,1)D_(w^2,5)
 D_(w^2,2)De
 D_(w^2,2)D_(0,1)
 D_(w^2,2)D_(0,2)
 D_(w^2,2)D_(0,3)
 D_(w^2,2)D_(0,4)
 D_(w^2,2)D_(0,5)
 D_(w^2,2)D_(1,0)
 D_(w^2,2)D_(1,1)
 D_(w^2,2)D_(1,2)
 D_(w^2,2)D_(1,3)
 D_(w^2,2)D_(1,4)
 D_(w^2,2)D_(1,5)
 D_(w^2,2)D_(w,0)
 D_(w^2,2)D_(w,1)
 D_(w^2,2)D_(w,2)
 D_(w^2,2)D_(w,3)
 D_(w^2,2)D_(w,4)
 D_(w^2,2)D_(w,5)
 D_(w^2,2)D_(w^2,0)
 D_(w^2,2)D_(w^2,1)
 D_(w^2,2)^2 - D_(w^2,2)
 D_(w^2,2)D_(w^2,3)
 D_(w^2,2)D_(w^2,4)
 D_(w^2,2)D_(w^2,5)
 D_(w^2,3)De
 D_(w^2,3)D_(0,1)
 D_(w^2,3)D_(0,2)
 D_(w^2,3)D_(0,3)
 D_(w^2,3)D_(0,4)
 D_(w^2,3)D_(0,5)
 D_(w^2,3)D_(1,0)
 D_(w^2,3)D_(1,1)
 D_(w^2,3)D_(1,2)
 D_(w^2,3)D_(1,3)
 D_(w^2,3)D_(1,4)
 D_(w^2,3)D_(1,5)
 D_(w^2,3)D_(w,0)
 D_(w^2,3)D_(w,1)
 D_(w^2,3)D_(w,2)
 D_(w^2,3)D_(w,3)
 D_(w^2,3)D_(w,4)
 D_(w^2,3)D_(w,5)
 D_(w^2,3)D_(w^2,0)
 D_(w^2,3)D_(w^2,1)
 D_(w^2,3)D_(w^2,2)
 D_(w^2,3)^2 - D_(w^2,3)
 D_(w^2,3)D_(w^2,4)
 D_(w^2,3)D_(w^2,5)
 D_(w^2,4)De
 D_(w^2,4)D_(0,1)
 D_(w^2,4)D_(0,2)
 D_(w^2,4)D_(0,3)
 D_(w^2,4)D_(0,4)
 D_(w^2,4)D_(0,5)
 D_(w^2,4)D_(1,0)
 D_(w^2,4)D_(1,1)
 D_(w^2,4)D_(1,2)
 D_(w^2,4)D_(1,3)
 D_(w^2,4)D_(1,4)
 D_(w^2,4)D_(1,5)
 D_(w^2,4)D_(w,0)
 D_(w^2,4)D_(w,1)
 D_(w^2,4)D_(w,2)
 D_(w^2,4)D_(w,3)
 D_(w^2,4)D_(w,4)
 D_(w^2,4)D_(w,5)
 D_(w^2,4)D_(w^2,0)
 D_(w^2,4)D_(w^2,1)
 D_(w^2,4)D_(w^2,2)
 D_(w^2,4)D_(w^2,3)
 D_(w^2,4)^2 - D_(w^2,4)
 D_(w^2,4)D_(w^2,5)
 D_(w^2,5)De
 D_(w^2,5)D_(0,1)
 D_(w^2,5)D_(0,2)
 D_(w^2,5)D_(0,3)
 D_(w^2,5)D_(0,4)
 D_(w^2,5)D_(0,5)
 D_(w^2,5)D_(1,0)
 D_(w^2,5)D_(1,1)
 D_(w^2,5)D_(1,2)
 D_(w^2,5)D_(1,3)
 D_(w^2,5)D_(1,4)
 D_(w^2,5)D_(1,5)
 D_(w^2,5)D_(w,0)
 D_(w^2,5)D_(w,1)
 D_(w^2,5)D_(w,2)
 D_(w^2,5)D_(w,3)
 D_(w^2,5)D_(w,4)
 D_(w^2,5)D_(w,5)
 D_(w^2,5)D_(w^2,0)
 D_(w^2,5)D_(w^2,1)
 D_(w^2,5)D_(w^2,2)
 D_(w^2,5)D_(w^2,3)
 D_(w^2,5)D_(w^2,4)
 D_(w^2,5)^2 - D_(w^2,5)
 De + D_(0,1) + D_(0,2) + D_(0,3) + D_(0,4) + D_(0,5) + D_(1,0) + D_(1,1) + D_\
(1,2) + D_(1,3) + D_(1,4) + D_(1,5) + D_(w,0) + D_(w,1) + D_(w,2) + D_(w,3) + \
D_(w,4) + D_(w,5) + D_(w^2,0) + D_(w^2,1) + D_(w^2,2) + D_(w^2,3) + D_(w^2,4) \
+ D_(w^2,5) - 1

In [101]:
relskG;

[ [ [ [ 9, 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 9, 10 ] ], [ 1 ] ],   [ [ [ 9, 11 ] ], [ 1 ] ], [ [ [ 9, 12 ] ], [ 1 ] ],   [ [ [ 9, 13 ] ], [ 1 ] ], [ [ [ 9, 14 ] ], [ 1 ] ],   [ [ [ 9, 15 ] ], [ 1 ] ], [ [ [ 9, 16 ] ], [ 1 ] ],   [ [ [ 9, 17 ] ], [ 1 ] ], [ [ [ 9, 18 ] ], [ 1 ] ],   [ [ [ 9, 19 ] ], [ 1 ] ], [ [ [ 9, 20 ] ], [ 1 ] ],   [ [ [ 9, 21 ] ], [ 1 ] ], [ [ [ 9, 22 ] ], [ 1 ] ],   [ [ [ 9, 23 ] ], [ 1 ] ], [ [ [ 9, 24 ] ], [ 1 ] ],   [ [ [ 9, 25 ] ], [ 1 ] ], [ [ [ 9, 26 ] ], [ 1 ] ],   [ [ [ 9, 27 ] ], [ 1 ] ], [ [ [ 9, 28 ] ], [ 1 ] ],   [ [ [ 9, 29 ] ], [ 1 ] ], [ [ [ 9, 30 ] ], [ 1 ] ],   [ [ [ 9, 31 ] ], [ 1 ] ], [ [ [ 9, 32 ] ], [ 1 ] ],   [ [ [ 10, 9 ] ], [ 1 ] ], [ [ [ 10, 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 10, 11 ] ], [ 1 ] ], [ [ [ 10, 12 ] ], [ 1 ] ],   [ [ [ 10, 13 ] ], [ 1 ] ], [ [ [ 10, 14 ] ], [ 1 ] ],   [ [ [ 10, 15 ] ], [ 1 ] ], [ [ [ 10, 16 ] ], [ 1 ] ],   [ [ [ 10, 17 ] ], [ 1 ] ], [ [ [ 10, 18 ] ], [ 1 ] ],   [ [ [ 10, 19 ] ], [ 1 ] ], [ [ [ 10, 20 ] ], [ 1 ] ],   [ [ [ 10, 21 ] ], [ 1 ] ], [ [ [ 10, 22 ] ], [ 1 ] ],   [ [ [ 10, 23 ] ], [ 1 ] ], [ [ [ 10, 24 ] ], [ 1 ] ],   [ [ [ 10, 25 ] ], [ 1 ] ], [ [ [ 10, 26 ] ], [ 1 ] ],   [ [ [ 10, 27 ] ], [ 1 ] ], [ [ [ 10, 28 ] ], [ 1 ] ],   [ [ [ 10, 29 ] ], [ 1 ] ], [ [ [ 10, 30 ] ], [ 1 ] ],   [ [ [ 10, 31 ] ], [ 1 ] ], [ [ [ 10, 32 ] ], [ 1 ] ],   [ [ [ 11, 9 ] ], [ 1 ] ], [ [ [ 11, 10 ] ], [ 1 ] ],   [ [ [ 11, 11 ], [ 11 ] ], [ 1, -1 ] ], [ [ [ 11, 12 ] ], [ 1 ] ],   [ [ [ 11, 13 ] ], [ 1 ] ], [ [ [ 11, 14 ] ], [ 1 ] ],   [ [ [ 11, 15 ] ], [ 1 ] ], [ [ [ 11, 16 ] ], [ 1 ] ],   [ [ [ 11, 17 ] ], [ 1 ] ], [ [ [ 11, 18 ] ], [ 1 ] ],   [ [ [ 11, 19 ] ], [ 1 ] ], [ [ [ 11, 20 ] ], [ 1 ] ],   [ [ [ 11, 21 ] ], [ 1 ] ], [ [ [ 11, 22 ] ], [ 1 ] ],   [ [ [ 11, 23 ] ], [ 1 ] ], [ [ [ 11, 24 ] ], [ 1 ] ],   [ [ [ 11, 25 ] ], [ 1 ] ], [ [ [ 11, 26 ] ], [ 1 ] ],   [ [ [ 11, 27 ] ], [ 1 ] ], [ [ [ 11, 28 ] ], [ 1 ] ],   [ [ [ 11, 29 ] ], [ 1 ] ], [ [ [ 11, 30 ] ], [ 1 ] ],   [ [ [ 11, 31 ] ], [ 1 ] ], [ [ [ 11, 32 ] ], [ 1 ] ],   [ [ [ 12, 9 ] ], [ 1 ] ], [ [ [ 12, 10 ] ], [ 1 ] ],   [ [ [ 12, 11 ] ], [ 1 ] ], [ [ [ 12, 12 ], [ 12 ] ], [ 1, -1 ] ],   [ [ [ 12, 13 ] ], [ 1 ] ], [ [ [ 12, 14 ] ], [ 1 ] ],   [ [ [ 12, 15 ] ], [ 1 ] ], [ [ [ 12, 16 ] ], [ 1 ] ],   [ [ [ 12, 17 ] ], [ 1 ] ], [ [ [ 12, 18 ] ], [ 1 ] ],   [ [ [ 12, 19 ] ], [ 1 ] ], [ [ [ 12, 20 ] ], [ 1 ] ],   [ [ [ 12, 21 ] ], [ 1 ] ], [ [ [ 12, 22 ] ], [ 1 ] ],   [ [ [ 12, 23 ] ], [ 1 ] ], [ [ [ 12, 24 ] ], [ 1 ] ],   [ [ [ 12, 25 ] ], [ 1 ] ], [ [ [ 12, 26 ] ], [ 1 ] ],   [ [ [ 12, 27 ] ], [ 1 ] ], [ [ [ 12, 28 ] ], [ 1 ] ],   [ [ [ 12, 29 ] ], [ 1 ] ], [ [ [ 12, 30 ] ], [ 1 ] ],   [ [ [ 12, 31 ] ], [ 1 ] ], [ [ [ 12, 32 ] ], [ 1 ] ],   [ [ [ 13, 9 ] ], [ 1 ] ], [ [ [ 13, 10 ] ], [ 1 ] ],   [ [ [ 13, 11 ] ], [ 1 ] ], [ [ [ 13, 12 ] ], [ 1 ] ],   [ [ [ 13, 13 ], [ 13 ] ], [ 1, -1 ] ], [ [ [ 13, 14 ] ], [ 1 ] ],   [ [ [ 13, 15 ] ], [ 1 ] ], [ [ [ 13, 16 ] ], [ 1 ] ],   [ [ [ 13, 17 ] ], [ 1 ] ], [ [ [ 13, 18 ] ], [ 1 ] ],   [ [ [ 13, 19 ] ], [ 1 ] ], [ [ [ 13, 20 ] ], [ 1 ] ],   [ [ [ 13, 21 ] ], [ 1 ] ], [ [ [ 13, 22 ] ], [ 1 ] ],   [ [ [ 13, 23 ] ], [ 1 ] ], [ [ [ 13, 24 ] ], [ 1 ] ],   [ [ [ 13, 25 ] ], [ 1 ] ], [ [ [ 13, 26 ] ], [ 1 ] ],   [ [ [ 13, 27 ] ], [ 1 ] ], [ [ [ 13, 28 ] ], [ 1 ] ],   [ [ [ 13, 29 ] ], [ 1 ] ], [ [ [ 13, 30 ] ], [ 1 ] ],   [ [ [ 13, 31 ] ], [ 1 ] ], [ [ [ 13, 32 ] ], [ 1 ] ],   [ [ [ 14, 9 ] ], [ 1 ] ], [ [ [ 14, 10 ] ], [ 1 ] ],   [ [ [ 14, 11 ] ], [ 1 ] ], [ [ [ 14, 12 ] ], [ 1 ] ],   [ [ [ 14, 13 ] ], [ 1 ] ], [ [ [ 14, 14 ], [ 14 ] ], [ 1, -1 ] ],   [ [ [ 14, 15 ] ], [ 1 ] ], [ [ [ 14, 16 ] ], [ 1 ] ],   [ [ [ 14, 17 ] ], [ 1 ] ], [ [ [ 14, 18 ] ], [ 1 ] ],   [ [ [ 14, 19 ] ], [ 1 ] ], [ [ [ 14, 20 ] ], [ 1 ] ],   [ [ [ 14, 21 ] ], [ 1 ] ], [ [ [ 14, 22 ] ], [ 1 ] ],   [ [ [ 14, 23 ] ], [ 1 ] ], [ [ [ 14, 24 ] ], [ 1 ] ],   [ [ [ 14, 25 ] ], [ 1 ] ], [ [ [ 14, 26 ] ], [ 1 ] ],   [ [ [ 14, 27 ] ], [ 1 ] ], [ [ [ 14, 28 ] ], [ 1 ] ],   [ [ [ 14, 29 ] ], [ 1 ] ], [ [ [ 14, 30 ] ], [ 1 ] ],   [ [ [ 14, 31 ] ], [ 1 ] ], [ [ [ 14, 32 ] ], [ 1 ] ],   [ [ [ 15, 9 ] ], [ 1 ] ], [ [ [ 15, 10 ] ], [ 1 ] ],   [ [ [ 15, 11 ] ], [ 1 ] ], [ [ [ 15, 12 ] ], [ 1 ] ],   [ [ [ 15, 13 ] ], [ 1 ] ], [ [ [ 15, 14 ] ], [ 1 ] ],   [ [ [ 15, 15 ], [ 15 ] ], [ 1, -1 ] ], [ [ [ 15, 16 ] ], [ 1 ] ],   [ [ [ 15, 17 ] ], [ 1 ] ], [ [ [ 15, 18 ] ], [ 1 ] ],   [ [ [ 15, 19 ] ], [ 1 ] ], [ [ [ 15, 20 ] ], [ 1 ] ],   [ [ [ 15, 21 ] ], [ 1 ] ], [ [ [ 15, 22 ] ], [ 1 ] ],   [ [ [ 15, 23 ] ], [ 1 ] ], [ [ [ 15, 24 ] ], [ 1 ] ],   [ [ [ 15, 25 ] ], [ 1 ] ], [ [ [ 15, 26 ] ], [ 1 ] ],   [ [ [ 15, 27 ] ], [ 1 ] ], [ [ [ 15, 28 ] ], [ 1 ] ],   [ [ [ 15, 29 ] ], [ 1 ] ], [ [ [ 15, 30 ] ], [ 1 ] ],   [ [ [ 15, 31 ] ], [ 1 ] ], [ [ [ 15, 32 ] ], [ 1 ] ],   [ [ [ 16, 9 ] ], [ 1 ] ], [ [ [ 16, 10 ] ], [ 1 ] ],   [ [ [ 16, 11 ] ], [ 1 ] ], [ [ [ 16, 12 ] ], [ 1 ] ],   [ [ [ 16, 13 ] ], [ 1 ] ], [ [ [ 16, 14 ] ], [ 1 ] ],   [ [ [ 16, 15 ] ], [ 1 ] ], [ [ [ 16, 16 ], [ 16 ] ], [ 1, -1 ] ],   [ [ [ 16, 17 ] ], [ 1 ] ], [ [ [ 16, 18 ] ], [ 1 ] ],   [ [ [ 16, 19 ] ], [ 1 ] ], [ [ [ 16, 20 ] ], [ 1 ] ],   [ [ [ 16, 21 ] ], [ 1 ] ], [ [ [ 16, 22 ] ], [ 1 ] ],   [ [ [ 16, 23 ] ], [ 1 ] ], [ [ [ 16, 24 ] ], [ 1 ] ],   [ [ [ 16, 25 ] ], [ 1 ] ], [ [ [ 16, 26 ] ], [ 1 ] ],   [ [ [ 16, 27 ] ], [ 1 ] ], [ [ [ 16, 28 ] ], [ 1 ] ],   [ [ [ 16, 29 ] ], [ 1 ] ], [ [ [ 16, 30 ] ], [ 1 ] ],   [ [ [ 16, 31 ] ], [ 1 ] ], [ [ [ 16, 32 ] ], [ 1 ] ],   [ [ [ 17, 9 ] ], [ 1 ] ], [ [ [ 17, 10 ] ], [ 1 ] ],   [ [ [ 17, 11 ] ], [ 1 ] ], [ [ [ 17, 12 ] ], [ 1 ] ],   [ [ [ 17, 13 ] ], [ 1 ] ], [ [ [ 17, 14 ] ], [ 1 ] ],   [ [ [ 17, 15 ] ], [ 1 ] ], [ [ [ 17, 16 ] ], [ 1 ] ],   [ [ [ 17, 17 ], [ 17 ] ], [ 1, -1 ] ], [ [ [ 17, 18 ] ], [ 1 ] ],   [ [ [ 17, 19 ] ], [ 1 ] ], [ [ [ 17, 20 ] ], [ 1 ] ],   [ [ [ 17, 21 ] ], [ 1 ] ], [ [ [ 17, 22 ] ], [ 1 ] ],   [ [ [ 17, 23 ] ], [ 1 ] ], [ [ [ 17, 24 ] ], [ 1 ] ],   [ [ [ 17, 25 ] ], [ 1 ] ], [ [ [ 17, 26 ] ], [ 1 ] ],   [ [ [ 17, 27 ] ], [ 1 ] ], [ [ [ 17, 28 ] ], [ 1 ] ],   [ [ [ 17, 29 ] ], [ 1 ] ], [ [ [ 17, 30 ] ], [ 1 ] ],   [ [ [ 17, 31 ] ], [ 1 ] ], [ [ [ 17, 32 ] ], [ 1 ] ],   [ [ [ 18, 9 ] ], [ 1 ] ], [ [ [ 18, 10 ] ], [ 1 ] ],   [ [ [ 18, 11 ] ], [ 1 ] ], [ [ [ 18, 12 ] ], [ 1 ] ],   [ [ [ 18, 13 ] ], [ 1 ] ], [ [ [ 18, 14 ] ], [ 1 ] ],   [ [ [ 18, 15 ] ], [ 1 ] ], [ [ [ 18, 16 ] ], [ 1 ] ],   [ [ [ 18, 17 ] ], [ 1 ] ], [ [ [ 18, 18 ], [ 18 ] ], [ 1, -1 ] ],   [ [ [ 18, 19 ] ], [ 1 ] ], [ [ [ 18, 20 ] ], [ 1 ] ],   [ [ [ 18, 21 ] ], [ 1 ] ], [ [ [ 18, 22 ] ], [ 1 ] ],   [ [ [ 18, 23 ] ], [ 1 ] ], [ [ [ 18, 24 ] ], [ 1 ] ],   [ [ [ 18, 25 ] ], [ 1 ] ], [ [ [ 18, 26 ] ], [ 1 ] ],   [ [ [ 18, 27 ] ], [ 1 ] ], [ [ [ 18, 28 ] ], [ 1 ] ],   [ [ [ 18, 29 ] ], [ 1 ] ], [ [ [ 18, 30 ] ], [ 1 ] ],   [ [ [ 18, 31 ] ], [ 1 ] ], [ [ [ 18, 32 ] ], [ 1 ] ],   [ [ [ 19, 9 ] ], [ 1 ] ], [ [ [ 19, 10 ] ], [ 1 ] ],   [ [ [ 19, 11 ] ], [ 1 ] ], [ [ [ 19, 12 ] ], [ 1 ] ],   [ [ [ 19, 13 ] ], [ 1 ] ], [ [ [ 19, 14 ] ], [ 1 ] ],   [ [ [ 19, 15 ] ], [ 1 ] ], [ [ [ 19, 16 ] ], [ 1 ] ],   [ [ [ 19, 17 ] ], [ 1 ] ], [ [ [ 19, 18 ] ], [ 1 ] ],   [ [ [ 19, 19 ], [ 19 ] ], [ 1, -1 ] ], [ [ [ 19, 20 ] ], [ 1 ] ],   [ [ [ 19, 21 ] ], [ 1 ] ], [ [ [ 19, 22 ] ], [ 1 ] ],   [ [ [ 19, 23 ] ], [ 1 ] ], [ [ [ 19, 24 ] ], [ 1 ] ],   [ [ [ 19, 25 ] ], [ 1 ] ], [ [ [ 19, 26 ] ], [ 1 ] ],   [ [ [ 19, 27 ] ], [ 1 ] ], [ [ [ 19, 28 ] ], [ 1 ] ],   [ [ [ 19, 29 ] ], [ 1 ] ], [ [ [ 19, 30 ] ], [ 1 ] ],   [ [ [ 19, 31 ] ], [ 1 ] ], [ [ [ 19, 32 ] ], [ 1 ] ],   [ [ [ 20, 9 ] ], [ 1 ] ], [ [ [ 20, 10 ] ], [ 1 ] ],   [ [ [ 20, 11 ] ], [ 1 ] ], [ [ [ 20, 12 ] ], [ 1 ] ],   [ [ [ 20, 13 ] ], [ 1 ] ], [ [ [ 20, 14 ] ], [ 1 ] ],   [ [ [ 20, 15 ] ], [ 1 ] ], [ [ [ 20, 16 ] ], [ 1 ] ],   [ [ [ 20, 17 ] ], [ 1 ] ], [ [ [ 20, 18 ] ], [ 1 ] ],   [ [ [ 20, 19 ] ], [ 1 ] ], [ [ [ 20, 20 ], [ 20 ] ], [ 1, -1 ] ],   [ [ [ 20, 21 ] ], [ 1 ] ], [ [ [ 20, 22 ] ], [ 1 ] ],   [ [ [ 20, 23 ] ], [ 1 ] ], [ [ [ 20, 24 ] ], [ 1 ] ],   [ [ [ 20, 25 ] ], [ 1 ] ], [ [ [ 20, 26 ] ], [ 1 ] ],   [ [ [ 20, 27 ] ], [ 1 ] ], [ [ [ 20, 28 ] ], [ 1 ] ],   [ [ [ 20, 29 ] ], [ 1 ] ], [ [ [ 20, 30 ] ], [ 1 ] ],   [ [ [ 20, 31 ] ], [ 1 ] ], [ [ [ 20, 32 ] ], [ 1 ] ],   [ [ [ 21, 9 ] ], [ 1 ] ], [ [ [ 21, 10 ] ], [ 1 ] ],   [ [ [ 21, 11 ] ], [ 1 ] ], [ [ [ 21, 12 ] ], [ 1 ] ],   [ [ [ 21, 13 ] ], [ 1 ] ], [ [ [ 21, 14 ] ], [ 1 ] ],   [ [ [ 21, 15 ] ], [ 1 ] ], [ [ [ 21, 16 ] ], [ 1 ] ],   [ [ [ 21, 17 ] ], [ 1 ] ], [ [ [ 21, 18 ] ], [ 1 ] ],   [ [ [ 21, 19 ] ], [ 1 ] ], [ [ [ 21, 20 ] ], [ 1 ] ],   [ [ [ 21, 21 ], [ 21 ] ], [ 1, -1 ] ], [ [ [ 21, 22 ] ], [ 1 ] ],   [ [ [ 21, 23 ] ], [ 1 ] ], [ [ [ 21, 24 ] ], [ 1 ] ],   [ [ [ 21, 25 ] ], [ 1 ] ], [ [ [ 21, 26 ] ], [ 1 ] ],   [ [ [ 21, 27 ] ], [ 1 ] ], [ [ [ 21, 28 ] ], [ 1 ] ],   [ [ [ 21, 29 ] ], [ 1 ] ], [ [ [ 21, 30 ] ], [ 1 ] ],   [ [ [ 21, 31 ] ], [ 1 ] ], [ [ [ 21, 32 ] ], [ 1 ] ],   [ [ [ 22, 9 ] ], [ 1 ] ], [ [ [ 22, 10 ] ], [ 1 ] ],   [ [ [ 22, 11 ] ], [ 1 ] ], [ [ [ 22, 12 ] ], [ 1 ] ],   [ [ [ 22, 13 ] ], [ 1 ] ], [ [ [ 22, 14 ] ], [ 1 ] ],   [ [ [ 22, 15 ] ], [ 1 ] ], [ [ [ 22, 16 ] ], [ 1 ] ],   [ [ [ 22, 17 ] ], [ 1 ] ], [ [ [ 22, 18 ] ], [ 1 ] ],   [ [ [ 22, 19 ] ], [ 1 ] ], [ [ [ 22, 20 ] ], [ 1 ] ],   [ [ [ 22, 21 ] ], [ 1 ] ], [ [ [ 22, 22 ], [ 22 ] ], [ 1, -1 ] ],   [ [ [ 22, 23 ] ], [ 1 ] ], [ [ [ 22, 24 ] ], [ 1 ] ],   [ [ [ 22, 25 ] ], [ 1 ] ], [ [ [ 22, 26 ] ], [ 1 ] ],   [ [ [ 22, 27 ] ], [ 1 ] ], [ [ [ 22, 28 ] ], [ 1 ] ],   [ [ [ 22, 29 ] ], [ 1 ] ], [ [ [ 22, 30 ] ], [ 1 ] ],   [ [ [ 22, 31 ] ], [ 1 ] ], [ [ [ 22, 32 ] ], [ 1 ] ],   [ [ [ 23, 9 ] ], [ 1 ] ], [ [ [ 23, 10 ] ], [ 1 ] ],   [ [ [ 23, 11 ] ], [ 1 ] ], [ [ [ 23, 12 ] ], [ 1 ] ],   [ [ [ 23, 13 ] ], [ 1 ] ], [ [ [ 23, 14 ] ], [ 1 ] ],   [ [ [ 23, 15 ] ], [ 1 ] ], [ [ [ 23, 16 ] ], [ 1 ] ],   [ [ [ 23, 17 ] ], [ 1 ] ], [ [ [ 23, 18 ] ], [ 1 ] ],   [ [ [ 23, 19 ] ], [ 1 ] ], [ [ [ 23, 20 ] ], [ 1 ] ],   [ [ [ 23, 21 ] ], [ 1 ] ], [ [ [ 23, 22 ] ], [ 1 ] ],   [ [ [ 23, 23 ], [ 23 ] ], [ 1, -1 ] ], [ [ [ 23, 24 ] ], [ 1 ] ],   [ [ [ 23, 25 ] ], [ 1 ] ], [ [ [ 23, 26 ] ], [ 1 ] ],   [ [ [ 23, 27 ] ], [ 1 ] ], [ [ [ 23, 28 ] ], [ 1 ] ],   [ [ [ 23, 29 ] ], [ 1 ] ], [ [ [ 23, 30 ] ], [ 1 ] ],   [ [ [ 23, 31 ] ], [ 1 ] ], [ [ [ 23, 32 ] ], [ 1 ] ],   [ [ [ 24, 9 ] ], [ 1 ] ], [ [ [ 24, 10 ] ], [ 1 ] ],   [ [ [ 24, 11 ] ], [ 1 ] ], [ [ [ 24, 12 ] ], [ 1 ] ],   [ [ [ 24, 13 ] ], [ 1 ] ], [ [ [ 24, 14 ] ], [ 1 ] ],   [ [ [ 24, 15 ] ], [ 1 ] ], [ [ [ 24, 16 ] ], [ 1 ] ],   [ [ [ 24, 17 ] ], [ 1 ] ], [ [ [ 24, 18 ] ], [ 1 ] ],   [ [ [ 24, 19 ] ], [ 1 ] ], [ [ [ 24, 20 ] ], [ 1 ] ],   [ [ [ 24, 21 ] ], [ 1 ] ], [ [ [ 24, 22 ] ], [ 1 ] ],   [ [ [ 24, 23 ] ], [ 1 ] ], [ [ [ 24, 24 ], [ 24 ] ], [ 1, -1 ] ],   [ [ [ 24, 25 ] ], [ 1 ] ], [ [ [ 24, 26 ] ], [ 1 ] ],   [ [ [ 24, 27 ] ], [ 1 ] ], [ [ [ 24, 28 ] ], [ 1 ] ],   [ [ [ 24, 29 ] ], [ 1 ] ], [ [ [ 24, 30 ] ], [ 1 ] ],   [ [ [ 24, 31 ] ], [ 1 ] ], [ [ [ 24, 32 ] ], [ 1 ] ],   [ [ [ 25, 9 ] ], [ 1 ] ], [ [ [ 25, 10 ] ], [ 1 ] ],   [ [ [ 25, 11 ] ], [ 1 ] ], [ [ [ 25, 12 ] ], [ 1 ] ],   [ [ [ 25, 13 ] ], [ 1 ] ], [ [ [ 25, 14 ] ], [ 1 ] ],   [ [ [ 25, 15 ] ], [ 1 ] ], [ [ [ 25, 16 ] ], [ 1 ] ],   [ [ [ 25, 17 ] ], [ 1 ] ], [ [ [ 25, 18 ] ], [ 1 ] ],   [ [ [ 25, 19 ] ], [ 1 ] ], [ [ [ 25, 20 ] ], [ 1 ] ],   [ [ [ 25, 21 ] ], [ 1 ] ], [ [ [ 25, 22 ] ], [ 1 ] ],   [ [ [ 25, 23 ] ], [ 1 ] ], [ [ [ 25, 24 ] ], [ 1 ] ],   [ [ [ 25, 25 ], [ 25 ] ], [ 1, -1 ] ], [ [ [ 25, 26 ] ], [ 1 ] ],   [ [ [ 25, 27 ] ], [ 1 ] ], [ [ [ 25, 28 ] ], [ 1 ] ],   [ [ [ 25, 29 ] ], [ 1 ] ], [ [ [ 25, 30 ] ], [ 1 ] ],   [ [ [ 25, 31 ] ], [ 1 ] ], [ [ [ 25, 32 ] ], [ 1 ] ],   [ [ [ 26, 9 ] ], [ 1 ] ], [ [ [ 26, 10 ] ], [ 1 ] ],   [ [ [ 26, 11 ] ], [ 1 ] ], [ [ [ 26, 12 ] ], [ 1 ] ],   [ [ [ 26, 13 ] ], [ 1 ] ], [ [ [ 26, 14 ] ], [ 1 ] ],   [ [ [ 26, 15 ] ], [ 1 ] ], [ [ [ 26, 16 ] ], [ 1 ] ],   [ [ [ 26, 17 ] ], [ 1 ] ], [ [ [ 26, 18 ] ], [ 1 ] ],   [ [ [ 26, 19 ] ], [ 1 ] ], [ [ [ 26, 20 ] ], [ 1 ] ],   [ [ [ 26, 21 ] ], [ 1 ] ], [ [ [ 26, 22 ] ], [ 1 ] ],   [ [ [ 26, 23 ] ], [ 1 ] ], [ [ [ 26, 24 ] ], [ 1 ] ],   [ [ [ 26, 25 ] ], [ 1 ] ], [ [ [ 26, 26 ], [ 26 ] ], [ 1, -1 ] ],   [ [ [ 26, 27 ] ], [ 1 ] ], [ [ [ 26, 28 ] ], [ 1 ] ],   [ [ [ 26, 29 ] ], [ 1 ] ], [ [ [ 26, 30 ] ], [ 1 ] ],   [ [ [ 26, 31 ] ], [ 1 ] ], [ [ [ 26, 32 ] ], [ 1 ] ],   [ [ [ 27, 9 ] ], [ 1 ] ], [ [ [ 27, 10 ] ], [ 1 ] ],   [ [ [ 27, 11 ] ], [ 1 ] ], [ [ [ 27, 12 ] ], [ 1 ] ],   [ [ [ 27, 13 ] ], [ 1 ] ], [ [ [ 27, 14 ] ], [ 1 ] ],   [ [ [ 27, 15 ] ], [ 1 ] ], [ [ [ 27, 16 ] ], [ 1 ] ],   [ [ [ 27, 17 ] ], [ 1 ] ], [ [ [ 27, 18 ] ], [ 1 ] ],   [ [ [ 27, 19 ] ], [ 1 ] ], [ [ [ 27, 20 ] ], [ 1 ] ],   [ [ [ 27, 21 ] ], [ 1 ] ], [ [ [ 27, 22 ] ], [ 1 ] ],   [ [ [ 27, 23 ] ], [ 1 ] ], [ [ [ 27, 24 ] ], [ 1 ] ],   [ [ [ 27, 25 ] ], [ 1 ] ], [ [ [ 27, 26 ] ], [ 1 ] ],   [ [ [ 27, 27 ], [ 27 ] ], [ 1, -1 ] ], [ [ [ 27, 28 ] ], [ 1 ] ],   [ [ [ 27, 29 ] ], [ 1 ] ], [ [ [ 27, 30 ] ], [ 1 ] ],   [ [ [ 27, 31 ] ], [ 1 ] ], [ [ [ 27, 32 ] ], [ 1 ] ],   [ [ [ 28, 9 ] ], [ 1 ] ], [ [ [ 28, 10 ] ], [ 1 ] ],   [ [ [ 28, 11 ] ], [ 1 ] ], [ [ [ 28, 12 ] ], [ 1 ] ],   [ [ [ 28, 13 ] ], [ 1 ] ], [ [ [ 28, 14 ] ], [ 1 ] ],   [ [ [ 28, 15 ] ], [ 1 ] ], [ [ [ 28, 16 ] ], [ 1 ] ],   [ [ [ 28, 17 ] ], [ 1 ] ], [ [ [ 28, 18 ] ], [ 1 ] ],   [ [ [ 28, 19 ] ], [ 1 ] ], [ [ [ 28, 20 ] ], [ 1 ] ],   [ [ [ 28, 21 ] ], [ 1 ] ], [ [ [ 28, 22 ] ], [ 1 ] ],   [ [ [ 28, 23 ] ], [ 1 ] ], [ [ [ 28, 24 ] ], [ 1 ] ],   [ [ [ 28, 25 ] ], [ 1 ] ], [ [ [ 28, 26 ] ], [ 1 ] ],   [ [ [ 28, 27 ] ], [ 1 ] ], [ [ [ 28, 28 ], [ 28 ] ], [ 1, -1 ] ],   [ [ [ 28, 29 ] ], [ 1 ] ], [ [ [ 28, 30 ] ], [ 1 ] ],   [ [ [ 28, 31 ] ], [ 1 ] ], [ [ [ 28, 32 ] ], [ 1 ] ],   [ [ [ 29, 9 ] ], [ 1 ] ], [ [ [ 29, 10 ] ], [ 1 ] ],   [ [ [ 29, 11 ] ], [ 1 ] ], [ [ [ 29, 12 ] ], [ 1 ] ],   [ [ [ 29, 13 ] ], [ 1 ] ], [ [ [ 29, 14 ] ], [ 1 ] ],   [ [ [ 29, 15 ] ], [ 1 ] ], [ [ [ 29, 16 ] ], [ 1 ] ],   [ [ [ 29, 17 ] ], [ 1 ] ], [ [ [ 29, 18 ] ], [ 1 ] ],   [ [ [ 29, 19 ] ], [ 1 ] ], [ [ [ 29, 20 ] ], [ 1 ] ],   [ [ [ 29, 21 ] ], [ 1 ] ], [ [ [ 29, 22 ] ], [ 1 ] ],   [ [ [ 29, 23 ] ], [ 1 ] ], [ [ [ 29, 24 ] ], [ 1 ] ],   [ [ [ 29, 25 ] ], [ 1 ] ], [ [ [ 29, 26 ] ], [ 1 ] ],   [ [ [ 29, 27 ] ], [ 1 ] ], [ [ [ 29, 28 ] ], [ 1 ] ],   [ [ [ 29, 29 ], [ 29 ] ], [ 1, -1 ] ], [ [ [ 29, 30 ] ], [ 1 ] ],   [ [ [ 29, 31 ] ], [ 1 ] ], [ [ [ 29, 32 ] ], [ 1 ] ],   [ [ [ 30, 9 ] ], [ 1 ] ], [ [ [ 30, 10 ] ], [ 1 ] ],   [ [ [ 30, 11 ] ], [ 1 ] ], [ [ [ 30, 12 ] ], [ 1 ] ],   [ [ [ 30, 13 ] ], [ 1 ] ], [ [ [ 30, 14 ] ], [ 1 ] ],   [ [ [ 30, 15 ] ], [ 1 ] ], [ [ [ 30, 16 ] ], [ 1 ] ],   [ [ [ 30, 17 ] ], [ 1 ] ], [ [ [ 30, 18 ] ], [ 1 ] ],   [ [ [ 30, 19 ] ], [ 1 ] ], [ [ [ 30, 20 ] ], [ 1 ] ],   [ [ [ 30, 21 ] ], [ 1 ] ], [ [ [ 30, 22 ] ], [ 1 ] ],   [ [ [ 30, 23 ] ], [ 1 ] ], [ [ [ 30, 24 ] ], [ 1 ] ],   [ [ [ 30, 25 ] ], [ 1 ] ], [ [ [ 30, 26 ] ], [ 1 ] ],   [ [ [ 30, 27 ] ], [ 1 ] ], [ [ [ 30, 28 ] ], [ 1 ] ],   [ [ [ 30, 29 ] ], [ 1 ] ], [ [ [ 30, 30 ], [ 30 ] ], [ 1, -1 ] ],   [ [ [ 30, 31 ] ], [ 1 ] ], [ [ [ 30, 32 ] ], [ 1 ] ],   [ [ [ 31, 9 ] ], [ 1 ] ], [ [ [ 31, 10 ] ], [ 1 ] ],   [ [ [ 31, 11 ] ], [ 1 ] ], [ [ [ 31, 12 ] ], [ 1 ] ],   [ [ [ 31, 13 ] ], [ 1 ] ], [ [ [ 31, 14 ] ], [ 1 ] ],   [ [ [ 31, 15 ] ], [ 1 ] ], [ [ [ 31, 16 ] ], [ 1 ] ],   [ [ [ 31, 17 ] ], [ 1 ] ], [ [ [ 31, 18 ] ], [ 1 ] ],   [ [ [ 31, 19 ] ], [ 1 ] ], [ [ [ 31, 20 ] ], [ 1 ] ],   [ [ [ 31, 21 ] ], [ 1 ] ], [ [ [ 31, 22 ] ], [ 1 ] ],   [ [ [ 31, 23 ] ], [ 1 ] ], [ [ [ 31, 24 ] ], [ 1 ] ],   [ [ [ 31, 25 ] ], [ 1 ] ], [ [ [ 31, 26 ] ], [ 1 ] ],   [ [ [ 31, 27 ] ], [ 1 ] ], [ [ [ 31, 28 ] ], [ 1 ] ],   [ [ [ 31, 29 ] ], [ 1 ] ], [ [ [ 31, 30 ] ], [ 1 ] ],   [ [ [ 31, 31 ], [ 31 ] ], [ 1, -1 ] ], [ [ [ 31, 32 ] ], [ 1 ] ],   [ [ [ 32, 9 ] ], [ 1 ] ], [ [ [ 32, 10 ] ], [ 1 ] ],   [ [ [ 32, 11 ] ], [ 1 ] ], [ [ [ 32, 12 ] ], [ 1 ] ],   [ [ [ 32, 13 ] ], [ 1 ] ], [ [ [ 32, 14 ] ], [ 1 ] ],   [ [ [ 32, 15 ] ], [ 1 ] ], [ [ [ 32, 16 ] ], [ 1 ] ],   [ [ [ 32, 17 ] ], [ 1 ] ], [ [ [ 32, 18 ] ], [ 1 ] ],   [ [ [ 32, 19 ] ], [ 1 ] ], [ [ [ 32, 20 ] ], [ 1 ] ],   [ [ [ 32, 21 ] ], [ 1 ] ], [ [ [ 32, 22 ] ], [ 1 ] ],   [ [ [ 32, 23 ] ], [ 1 ] ], [ [ [ 32, 24 ] ], [ 1 ] ],   [ [ [ 32, 25 ] ], [ 1 ] ], [ [ [ 32, 26 ] ], [ 1 ] ],   [ [ [ 32, 27 ] ], [ 1 ] ], [ [ [ 32, 28 ] ], [ 1 ] ],   [ [ [ 32, 29 ] ], [ 1 ] ], [ [ [ 32, 30 ] ], [ 1 ] ],   [ [ [ 32, 31 ] ], [ 1 ] ], [ [ [ 32, 32 ], [ 32 ] ], [ 1, -1 ] ],   [ [ [ 9 ], [ 10 ], [ 11 ], [ 12 ], [ 13 ], [ 14 ], [ 15 ], [ 16 ], [ 17 ],           [ 18 ], [ 19 ], [ 20 ], [ 21 ], [ 22 ], [ 23 ], [ 24 ], [ 25 ],           [ 26 ], [ 27 ], [ 28 ], [ 29 ], [ 30 ], [ 31 ], [ 32 ], [  ] ],       [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,           1, -1 ] ] ]

In [103]:
J := SGrobner(Concatenation(
    relskG,
    gensX,
    gensG,
    # gensDeltas,
    gensY
    )
);;
DimQA(J, 36);

24

In [104]:
PrintNPList(BaseQA(J, 36, 0));

 1
 De
 D_(0,1)
 D_(0,2)
 D_(0,3)
 D_(0,4)
 D_(0,5)
 D_(1,0)
 D_(1,1)
 D_(1,2)
 D_(1,3)
 D_(1,4)
 D_(1,5)
 D_(w,0)
 D_(w,1)
 D_(w,2)
 D_(w,3)
 D_(w,4)
 D_(w,5)
 D_(w^2,0)
 D_(w^2,1)
 D_(w^2,2)
 D_(w^2,3)
 D_(w^2,4)

## Relaciones de Doble de Drinfeld de G

In [113]:
K           := DirectProduct(CyclicGroup(2), CyclicGroup(2));;
H           := CyclicGroup(6);;
AutK        := AutomorphismGroup(K);
T           := GroupHomomorphismByImages(H, AutK, [H.1], [List(AutK)[2]]);;
G           := SemidirectProduct(H, T, K);;
embK        := Embedding(G, 2);;
embH        := Embedding(G, 1);;
HinG        := List([0 .. Size(H) - 1], x -> embH(H.1^x));;
allPairsInG := Concatenation(List(K, x -> List(HinG, y -> embK(x) * y)));;

In [114]:
relsDG := CommutationRelationsGroupAndDeltas(allPairsInG, groupIndex, deltaIndex);

[ [ [ [ 9 ], [ 9 ] ], [ 1, -1 ] ], [ [ [ 10 ], [ 10 ] ], [ 1, -1 ] ],   [ [ [ 11 ], [ 11 ] ], [ 1, -1 ] ], [ [ [ 12 ], [ 12 ] ], [ 1, -1 ] ],   [ [ [ 13 ], [ 13 ] ], [ 1, -1 ] ], [ [ [ 14 ], [ 14 ] ], [ 1, -1 ] ],   [ [ [ 15 ], [ 15 ] ], [ 1, -1 ] ], [ [ [ 16 ], [ 16 ] ], [ 1, -1 ] ],   [ [ [ 17 ], [ 17 ] ], [ 1, -1 ] ], [ [ [ 18 ], [ 18 ] ], [ 1, -1 ] ],   [ [ [ 19 ], [ 19 ] ], [ 1, -1 ] ], [ [ [ 20 ], [ 20 ] ], [ 1, -1 ] ],   [ [ [ 21 ], [ 21 ] ], [ 1, -1 ] ], [ [ [ 22 ], [ 22 ] ], [ 1, -1 ] ],   [ [ [ 23 ], [ 23 ] ], [ 1, -1 ] ], [ [ [ 24 ], [ 24 ] ], [ 1, -1 ] ],   [ [ [ 25 ], [ 25 ] ], [ 1, -1 ] ], [ [ [ 26 ], [ 26 ] ], [ 1, -1 ] ],   [ [ [ 27 ], [ 27 ] ], [ 1, -1 ] ], [ [ [ 28 ], [ 28 ] ], [ 1, -1 ] ],   [ [ [ 29 ], [ 29 ] ], [ 1, -1 ] ], [ [ [ 30 ], [ 30 ] ], [ 1, -1 ] ],   [ [ [ 31 ], [ 31 ] ], [ 1, -1 ] ], [ [ [ 32 ], [ 32 ] ], [ 1, -1 ] ],   [ [ [ 9, 5 ], [ 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5 ], [ 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5 ], [ 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 12, 5 ], [ 5, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5 ], [ 5, 13 ] ], [ 1, -1 ] ],   [ [ [ 14, 5 ], [ 5, 14 ] ], [ 1, -1 ] ],   [ [ [ 15, 5 ], [ 5, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 5 ], [ 5, 28 ] ], [ 1, -1 ] ],   [ [ [ 17, 5 ], [ 5, 29 ] ], [ 1, -1 ] ],   [ [ [ 18, 5 ], [ 5, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 5 ], [ 5, 31 ] ], [ 1, -1 ] ],   [ [ [ 20, 5 ], [ 5, 32 ] ], [ 1, -1 ] ],   [ [ [ 21, 5 ], [ 5, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 5 ], [ 5, 16 ] ], [ 1, -1 ] ],   [ [ [ 23, 5 ], [ 5, 17 ] ], [ 1, -1 ] ],   [ [ [ 24, 5 ], [ 5, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 5 ], [ 5, 19 ] ], [ 1, -1 ] ],   [ [ [ 26, 5 ], [ 5, 20 ] ], [ 1, -1 ] ],   [ [ [ 27, 5 ], [ 5, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 5 ], [ 5, 22 ] ], [ 1, -1 ] ],   [ [ [ 29, 5 ], [ 5, 23 ] ], [ 1, -1 ] ],   [ [ [ 30, 5 ], [ 5, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 5 ], [ 5, 25 ] ], [ 1, -1 ] ],   [ [ [ 32, 5 ], [ 5, 26 ] ], [ 1, -1 ] ],   [ [ [ 9, 6 ], [ 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 6 ], [ 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 6 ], [ 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 12, 6 ], [ 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 6 ], [ 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 14, 6 ], [ 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 15, 6 ], [ 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 16, 6 ], [ 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 17, 6 ], [ 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 6 ], [ 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 19, 6 ], [ 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 20, 6 ], [ 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 6 ], [ 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 22, 6 ], [ 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 6 ], [ 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 24, 6 ], [ 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 25, 6 ], [ 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 6 ], [ 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 27, 6 ], [ 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 28, 6 ], [ 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 29, 6 ], [ 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 30, 6 ], [ 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 31, 6 ], [ 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 32, 6 ], [ 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 6 ], [ 5, 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 6 ], [ 5, 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 6 ], [ 5, 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 6 ], [ 5, 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 6 ], [ 5, 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 6 ], [ 5, 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 6 ], [ 5, 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 6 ], [ 5, 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 6 ], [ 5, 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 6 ], [ 5, 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 6 ], [ 5, 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 6 ], [ 5, 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 6 ], [ 5, 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 6 ], [ 5, 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 6 ], [ 5, 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 6 ], [ 5, 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 6 ], [ 5, 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 6 ], [ 5, 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 6 ], [ 5, 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 6 ], [ 5, 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 6 ], [ 5, 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 6 ], [ 5, 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 6 ], [ 5, 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 6 ], [ 5, 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 9, 6, 6 ], [ 6, 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 6, 6 ], [ 6, 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 6, 6 ], [ 6, 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 12, 6, 6 ], [ 6, 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 6, 6 ], [ 6, 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 14, 6, 6 ], [ 6, 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 15, 6, 6 ], [ 6, 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 6, 6 ], [ 6, 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 17, 6, 6 ], [ 6, 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 18, 6, 6 ], [ 6, 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 6, 6 ], [ 6, 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 20, 6, 6 ], [ 6, 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 21, 6, 6 ], [ 6, 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 6, 6 ], [ 6, 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 23, 6, 6 ], [ 6, 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 24, 6, 6 ], [ 6, 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 6, 6 ], [ 6, 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 26, 6, 6 ], [ 6, 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 27, 6, 6 ], [ 6, 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 6, 6 ], [ 6, 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 29, 6, 6 ], [ 6, 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 30, 6, 6 ], [ 6, 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 6, 6 ], [ 6, 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 32, 6, 6 ], [ 6, 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 6, 6 ], [ 5, 6, 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 6, 6 ], [ 5, 6, 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 6, 6 ], [ 5, 6, 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 6, 6 ], [ 5, 6, 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 6, 6 ], [ 5, 6, 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 6, 6 ], [ 5, 6, 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 6, 6 ], [ 5, 6, 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 6, 6 ], [ 5, 6, 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 6, 6 ], [ 5, 6, 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 6, 6 ], [ 5, 6, 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 6, 6 ], [ 5, 6, 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 6, 6 ], [ 5, 6, 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 6, 6 ], [ 5, 6, 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 6, 6 ], [ 5, 6, 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 6, 6 ], [ 5, 6, 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 6, 6 ], [ 5, 6, 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 6, 6 ], [ 5, 6, 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 6, 6 ], [ 5, 6, 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 6, 6 ], [ 5, 6, 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 6, 6 ], [ 5, 6, 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 6, 6 ], [ 5, 6, 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 6, 6 ], [ 5, 6, 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 6, 6 ], [ 5, 6, 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 6, 6 ], [ 5, 6, 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 9, 8 ], [ 8, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 8 ], [ 8, 28 ] ], [ 1, -1 ] ],   [ [ [ 11, 8 ], [ 8, 23 ] ], [ 1, -1 ] ],   [ [ [ 12, 8 ], [ 8, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 8 ], [ 8, 31 ] ], [ 1, -1 ] ],   [ [ [ 14, 8 ], [ 8, 26 ] ], [ 1, -1 ] ],   [ [ [ 15, 8 ], [ 8, 15 ] ], [ 1, -1 ] ],   [ [ [ 16, 8 ], [ 8, 22 ] ], [ 1, -1 ] ],   [ [ [ 17, 8 ], [ 8, 29 ] ], [ 1, -1 ] ],   [ [ [ 18, 8 ], [ 8, 18 ] ], [ 1, -1 ] ],   [ [ [ 19, 8 ], [ 8, 25 ] ], [ 1, -1 ] ],   [ [ [ 20, 8 ], [ 8, 32 ] ], [ 1, -1 ] ],   [ [ [ 21, 8 ], [ 8, 21 ] ], [ 1, -1 ] ],   [ [ [ 22, 8 ], [ 8, 16 ] ], [ 1, -1 ] ],   [ [ [ 23, 8 ], [ 8, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 8 ], [ 8, 24 ] ], [ 1, -1 ] ],   [ [ [ 25, 8 ], [ 8, 19 ] ], [ 1, -1 ] ],   [ [ [ 26, 8 ], [ 8, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 8 ], [ 8, 27 ] ], [ 1, -1 ] ],   [ [ [ 28, 8 ], [ 8, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 8 ], [ 8, 17 ] ], [ 1, -1 ] ],   [ [ [ 30, 8 ], [ 8, 30 ] ], [ 1, -1 ] ],   [ [ [ 31, 8 ], [ 8, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 8 ], [ 8, 20 ] ], [ 1, -1 ] ],   [ [ [ 9, 8, 5 ], [ 8, 5, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 8, 5 ], [ 8, 5, 22 ] ], [ 1, -1 ] ],   [ [ [ 11, 8, 5 ], [ 8, 5, 17 ] ], [ 1, -1 ] ],   [ [ [ 12, 8, 5 ], [ 8, 5, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 8, 5 ], [ 8, 5, 25 ] ], [ 1, -1 ] ],   [ [ [ 14, 8, 5 ], [ 8, 5, 20 ] ], [ 1, -1 ] ],   [ [ [ 15, 8, 5 ], [ 8, 5, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 8, 5 ], [ 8, 5, 16 ] ], [ 1, -1 ] ],   [ [ [ 17, 8, 5 ], [ 8, 5, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 8, 5 ], [ 8, 5, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 8, 5 ], [ 8, 5, 19 ] ], [ 1, -1 ] ],   [ [ [ 20, 8, 5 ], [ 8, 5, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 8, 5 ], [ 8, 5, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 8, 5 ], [ 8, 5, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 8, 5 ], [ 8, 5, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 8, 5 ], [ 8, 5, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 8, 5 ], [ 8, 5, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 8, 5 ], [ 8, 5, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 8, 5 ], [ 8, 5, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 8, 5 ], [ 8, 5, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 8, 5 ], [ 8, 5, 29 ] ], [ 1, -1 ] ],   [ [ [ 30, 8, 5 ], [ 8, 5, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 8, 5 ], [ 8, 5, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 8, 5 ], [ 8, 5, 32 ] ], [ 1, -1 ] ],   [ [ [ 9, 6, 7 ], [ 6, 7, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 6, 7 ], [ 6, 7, 16 ] ], [ 1, -1 ] ],   [ [ [ 11, 6, 7 ], [ 6, 7, 29 ] ], [ 1, -1 ] ],   [ [ [ 12, 6, 7 ], [ 6, 7, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 6, 7 ], [ 6, 7, 19 ] ], [ 1, -1 ] ],   [ [ [ 14, 6, 7 ], [ 6, 7, 32 ] ], [ 1, -1 ] ],   [ [ [ 15, 6, 7 ], [ 6, 7, 21 ] ], [ 1, -1 ] ],   [ [ [ 16, 6, 7 ], [ 6, 7, 28 ] ], [ 1, -1 ] ],   [ [ [ 17, 6, 7 ], [ 6, 7, 17 ] ], [ 1, -1 ] ],   [ [ [ 18, 6, 7 ], [ 6, 7, 24 ] ], [ 1, -1 ] ],   [ [ [ 19, 6, 7 ], [ 6, 7, 31 ] ], [ 1, -1 ] ],   [ [ [ 20, 6, 7 ], [ 6, 7, 20 ] ], [ 1, -1 ] ],   [ [ [ 21, 6, 7 ], [ 6, 7, 27 ] ], [ 1, -1 ] ],   [ [ [ 22, 6, 7 ], [ 6, 7, 22 ] ], [ 1, -1 ] ],   [ [ [ 23, 6, 7 ], [ 6, 7, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 6, 7 ], [ 6, 7, 30 ] ], [ 1, -1 ] ],   [ [ [ 25, 6, 7 ], [ 6, 7, 25 ] ], [ 1, -1 ] ],   [ [ [ 26, 6, 7 ], [ 6, 7, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 6, 7 ], [ 6, 7, 15 ] ], [ 1, -1 ] ],   [ [ [ 28, 6, 7 ], [ 6, 7, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 6, 7 ], [ 6, 7, 23 ] ], [ 1, -1 ] ],   [ [ [ 30, 6, 7 ], [ 6, 7, 18 ] ], [ 1, -1 ] ],   [ [ [ 31, 6, 7 ], [ 6, 7, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 6, 7 ], [ 6, 7, 26 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 6, 8 ], [ 5, 6, 8, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 6, 8 ], [ 5, 6, 8, 28 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 6, 8 ], [ 5, 6, 8, 23 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 6, 8 ], [ 5, 6, 8, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 6, 8 ], [ 5, 6, 8, 31 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 6, 8 ], [ 5, 6, 8, 26 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 6, 8 ], [ 5, 6, 8, 15 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 6, 8 ], [ 5, 6, 8, 22 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 6, 8 ], [ 5, 6, 8, 29 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 6, 8 ], [ 5, 6, 8, 18 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 6, 8 ], [ 5, 6, 8, 25 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 6, 8 ], [ 5, 6, 8, 32 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 6, 8 ], [ 5, 6, 8, 21 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 6, 8 ], [ 5, 6, 8, 16 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 6, 8 ], [ 5, 6, 8, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 6, 8 ], [ 5, 6, 8, 24 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 6, 8 ], [ 5, 6, 8, 19 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 6, 8 ], [ 5, 6, 8, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 6, 8 ], [ 5, 6, 8, 27 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 6, 8 ], [ 5, 6, 8, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 6, 8 ], [ 5, 6, 8, 17 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 6, 8 ], [ 5, 6, 8, 30 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 6, 8 ], [ 5, 6, 8, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 6, 8 ], [ 5, 6, 8, 20 ] ], [ 1, -1 ] ],   [ [ [ 9, 6, 7, 6 ], [ 6, 7, 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 6, 7, 6 ], [ 6, 7, 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 11, 6, 7, 6 ], [ 6, 7, 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 12, 6, 7, 6 ], [ 6, 7, 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 6, 7, 6 ], [ 6, 7, 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 14, 6, 7, 6 ], [ 6, 7, 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 15, 6, 7, 6 ], [ 6, 7, 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 6, 7, 6 ], [ 6, 7, 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 17, 6, 7, 6 ], [ 6, 7, 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 6, 7, 6 ], [ 6, 7, 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 6, 7, 6 ], [ 6, 7, 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 20, 6, 7, 6 ], [ 6, 7, 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 6, 7, 6 ], [ 6, 7, 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 6, 7, 6 ], [ 6, 7, 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 6, 7, 6 ], [ 6, 7, 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 6, 7, 6 ], [ 6, 7, 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 6, 7, 6 ], [ 6, 7, 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 6, 7, 6 ], [ 6, 7, 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 6, 7, 6 ], [ 6, 7, 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 6, 7, 6 ], [ 6, 7, 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 6, 7, 6 ], [ 6, 7, 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 30, 6, 7, 6 ], [ 6, 7, 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 6, 7, 6 ], [ 6, 7, 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 6, 7, 6 ], [ 6, 7, 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 16 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 29 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 19 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 32 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 21 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 28 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 17 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 24 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 31 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 20 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 27 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 22 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 11 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 30 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 25 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 14 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 15 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 10 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 23 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 18 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 13 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 6, 6, 7 ], [ 5, 6, 6, 7, 26 ] ], [ 1, -1 ] ],   [ [ [ 9, 7 ], [ 7, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 7 ], [ 7, 16 ] ], [ 1, -1 ] ],   [ [ [ 11, 7 ], [ 7, 29 ] ], [ 1, -1 ] ],   [ [ [ 12, 7 ], [ 7, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 7 ], [ 7, 19 ] ], [ 1, -1 ] ],   [ [ [ 14, 7 ], [ 7, 32 ] ], [ 1, -1 ] ],   [ [ [ 15, 7 ], [ 7, 15 ] ], [ 1, -1 ] ],   [ [ [ 16, 7 ], [ 7, 10 ] ], [ 1, -1 ] ],   [ [ [ 17, 7 ], [ 7, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 7 ], [ 7, 18 ] ], [ 1, -1 ] ],   [ [ [ 19, 7 ], [ 7, 13 ] ], [ 1, -1 ] ],   [ [ [ 20, 7 ], [ 7, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 7 ], [ 7, 21 ] ], [ 1, -1 ] ],   [ [ [ 22, 7 ], [ 7, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 7 ], [ 7, 17 ] ], [ 1, -1 ] ],   [ [ [ 24, 7 ], [ 7, 24 ] ], [ 1, -1 ] ],   [ [ [ 25, 7 ], [ 7, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 7 ], [ 7, 20 ] ], [ 1, -1 ] ],   [ [ [ 27, 7 ], [ 7, 27 ] ], [ 1, -1 ] ],   [ [ [ 28, 7 ], [ 7, 22 ] ], [ 1, -1 ] ],   [ [ [ 29, 7 ], [ 7, 11 ] ], [ 1, -1 ] ],   [ [ [ 30, 7 ], [ 7, 30 ] ], [ 1, -1 ] ],   [ [ [ 31, 7 ], [ 7, 25 ] ], [ 1, -1 ] ],   [ [ [ 32, 7 ], [ 7, 14 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 8 ], [ 5, 8, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 8 ], [ 5, 8, 28 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 8 ], [ 5, 8, 23 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 8 ], [ 5, 8, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 8 ], [ 5, 8, 31 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 8 ], [ 5, 8, 26 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 8 ], [ 5, 8, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 8 ], [ 5, 8, 10 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 8 ], [ 5, 8, 17 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 8 ], [ 5, 8, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 8 ], [ 5, 8, 13 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 8 ], [ 5, 8, 20 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 8 ], [ 5, 8, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 8 ], [ 5, 8, 22 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 8 ], [ 5, 8, 29 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 8 ], [ 5, 8, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 8 ], [ 5, 8, 25 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 8 ], [ 5, 8, 32 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 8 ], [ 5, 8, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 8 ], [ 5, 8, 16 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 8 ], [ 5, 8, 11 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 8 ], [ 5, 8, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 8 ], [ 5, 8, 19 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 8 ], [ 5, 8, 14 ] ], [ 1, -1 ] ],   [ [ [ 9, 7, 6 ], [ 7, 6, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 7, 6 ], [ 7, 6, 22 ] ], [ 1, -1 ] ],   [ [ [ 11, 7, 6 ], [ 7, 6, 17 ] ], [ 1, -1 ] ],   [ [ [ 12, 7, 6 ], [ 7, 6, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 7, 6 ], [ 7, 6, 25 ] ], [ 1, -1 ] ],   [ [ [ 14, 7, 6 ], [ 7, 6, 20 ] ], [ 1, -1 ] ],   [ [ [ 15, 7, 6 ], [ 7, 6, 21 ] ], [ 1, -1 ] ],   [ [ [ 16, 7, 6 ], [ 7, 6, 10 ] ], [ 1, -1 ] ],   [ [ [ 17, 7, 6 ], [ 7, 6, 29 ] ], [ 1, -1 ] ],   [ [ [ 18, 7, 6 ], [ 7, 6, 24 ] ], [ 1, -1 ] ],   [ [ [ 19, 7, 6 ], [ 7, 6, 13 ] ], [ 1, -1 ] ],   [ [ [ 20, 7, 6 ], [ 7, 6, 32 ] ], [ 1, -1 ] ],   [ [ [ 21, 7, 6 ], [ 7, 6, 27 ] ], [ 1, -1 ] ],   [ [ [ 22, 7, 6 ], [ 7, 6, 16 ] ], [ 1, -1 ] ],   [ [ [ 23, 7, 6 ], [ 7, 6, 23 ] ], [ 1, -1 ] ],   [ [ [ 24, 7, 6 ], [ 7, 6, 30 ] ], [ 1, -1 ] ],   [ [ [ 25, 7, 6 ], [ 7, 6, 19 ] ], [ 1, -1 ] ],   [ [ [ 26, 7, 6 ], [ 7, 6, 26 ] ], [ 1, -1 ] ],   [ [ [ 27, 7, 6 ], [ 7, 6, 15 ] ], [ 1, -1 ] ],   [ [ [ 28, 7, 6 ], [ 7, 6, 28 ] ], [ 1, -1 ] ],   [ [ [ 29, 7, 6 ], [ 7, 6, 11 ] ], [ 1, -1 ] ],   [ [ [ 30, 7, 6 ], [ 7, 6, 18 ] ], [ 1, -1 ] ],   [ [ [ 31, 7, 6 ], [ 7, 6, 31 ] ], [ 1, -1 ] ],   [ [ [ 32, 7, 6 ], [ 7, 6, 14 ] ], [ 1, -1 ] ],   [ [ [ 9, 5, 6, 7 ], [ 5, 6, 7, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 5, 6, 7 ], [ 5, 6, 7, 16 ] ], [ 1, -1 ] ],   [ [ [ 11, 5, 6, 7 ], [ 5, 6, 7, 29 ] ], [ 1, -1 ] ],   [ [ [ 12, 5, 6, 7 ], [ 5, 6, 7, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 5, 6, 7 ], [ 5, 6, 7, 19 ] ], [ 1, -1 ] ],   [ [ [ 14, 5, 6, 7 ], [ 5, 6, 7, 32 ] ], [ 1, -1 ] ],   [ [ [ 15, 5, 6, 7 ], [ 5, 6, 7, 15 ] ], [ 1, -1 ] ],   [ [ [ 16, 5, 6, 7 ], [ 5, 6, 7, 10 ] ], [ 1, -1 ] ],   [ [ [ 17, 5, 6, 7 ], [ 5, 6, 7, 23 ] ], [ 1, -1 ] ],   [ [ [ 18, 5, 6, 7 ], [ 5, 6, 7, 18 ] ], [ 1, -1 ] ],   [ [ [ 19, 5, 6, 7 ], [ 5, 6, 7, 13 ] ], [ 1, -1 ] ],   [ [ [ 20, 5, 6, 7 ], [ 5, 6, 7, 26 ] ], [ 1, -1 ] ],   [ [ [ 21, 5, 6, 7 ], [ 5, 6, 7, 21 ] ], [ 1, -1 ] ],   [ [ [ 22, 5, 6, 7 ], [ 5, 6, 7, 28 ] ], [ 1, -1 ] ],   [ [ [ 23, 5, 6, 7 ], [ 5, 6, 7, 17 ] ], [ 1, -1 ] ],   [ [ [ 24, 5, 6, 7 ], [ 5, 6, 7, 24 ] ], [ 1, -1 ] ],   [ [ [ 25, 5, 6, 7 ], [ 5, 6, 7, 31 ] ], [ 1, -1 ] ],   [ [ [ 26, 5, 6, 7 ], [ 5, 6, 7, 20 ] ], [ 1, -1 ] ],   [ [ [ 27, 5, 6, 7 ], [ 5, 6, 7, 27 ] ], [ 1, -1 ] ],   [ [ [ 28, 5, 6, 7 ], [ 5, 6, 7, 22 ] ], [ 1, -1 ] ],   [ [ [ 29, 5, 6, 7 ], [ 5, 6, 7, 11 ] ], [ 1, -1 ] ],   [ [ [ 30, 5, 6, 7 ], [ 5, 6, 7, 30 ] ], [ 1, -1 ] ],   [ [ [ 31, 5, 6, 7 ], [ 5, 6, 7, 25 ] ], [ 1, -1 ] ],   [ [ [ 32, 5, 6, 7 ], [ 5, 6, 7, 14 ] ], [ 1, -1 ] ],   [ [ [ 9, 6, 6, 8 ], [ 6, 6, 8, 9 ] ], [ 1, -1 ] ],   [ [ [ 10, 6, 6, 8 ], [ 6, 6, 8, 28 ] ], [ 1, -1 ] ],   [ [ [ 11, 6, 6, 8 ], [ 6, 6, 8, 23 ] ], [ 1, -1 ] ],   [ [ [ 12, 6, 6, 8 ], [ 6, 6, 8, 12 ] ], [ 1, -1 ] ],   [ [ [ 13, 6, 6, 8 ], [ 6, 6, 8, 31 ] ], [ 1, -1 ] ],   [ [ [ 14, 6, 6, 8 ], [ 6, 6, 8, 26 ] ], [ 1, -1 ] ],   [ [ [ 15, 6, 6, 8 ], [ 6, 6, 8, 27 ] ], [ 1, -1 ] ],   [ [ [ 16, 6, 6, 8 ], [ 6, 6, 8, 10 ] ], [ 1, -1 ] ],   [ [ [ 17, 6, 6, 8 ], [ 6, 6, 8, 17 ] ], [ 1, -1 ] ],   [ [ [ 18, 6, 6, 8 ], [ 6, 6, 8, 30 ] ], [ 1, -1 ] ],   [ [ [ 19, 6, 6, 8 ], [ 6, 6, 8, 13 ] ], [ 1, -1 ] ],   [ [ [ 20, 6, 6, 8 ], [ 6, 6, 8, 20 ] ], [ 1, -1 ] ],   [ [ [ 21, 6, 6, 8 ], [ 6, 6, 8, 15 ] ], [ 1, -1 ] ],   [ [ [ 22, 6, 6, 8 ], [ 6, 6, 8, 22 ] ], [ 1, -1 ] ],   [ [ [ 23, 6, 6, 8 ], [ 6, 6, 8, 29 ] ], [ 1, -1 ] ],   [ [ [ 24, 6, 6, 8 ], [ 6, 6, 8, 18 ] ], [ 1, -1 ] ],   [ [ [ 25, 6, 6, 8 ], [ 6, 6, 8, 25 ] ], [ 1, -1 ] ],   [ [ [ 26, 6, 6, 8 ], [ 6, 6, 8, 32 ] ], [ 1, -1 ] ],   [ [ [ 27, 6, 6, 8 ], [ 6, 6, 8, 21 ] ], [ 1, -1 ] ],   [ [ [ 28, 6, 6, 8 ], [ 6, 6, 8, 16 ] ], [ 1, -1 ] ],   [ [ [ 29, 6, 6, 8 ], [ 6, 6, 8, 11 ] ], [ 1, -1 ] ],   [ [ [ 30, 6, 6, 8 ], [ 6, 6, 8, 24 ] ], [ 1, -1 ] ],   [ [ [ 31, 6, 6, 8 ], [ 6, 6, 8

In [116]:
Print("Se generaron ", Length(relsDG), " relaciones δ_h g = g δ_{g^-1*h*g}.\n");
PrintNPList(relsDG);

Se generaron 576 relaciones δ_h g = g δ_{g^-1*h*g}.
 De - De
 D_(0,1) - D_(0,1)
 D_(0,2) - D_(0,2)
 D_(0,3) - D_(0,3)
 D_(0,4) - D_(0,4)
 D_(0,5) - D_(0,5)
 D_(1,0) - D_(1,0)
 D_(1,1) - D_(1,1)
 D_(1,2) - D_(1,2)
 D_(1,3) - D_(1,3)
 D_(1,4) - D_(1,4)
 D_(1,5) - D_(1,5)
 D_(w,0) - D_(w,0)
 D_(w,1) - D_(w,1)
 D_(w,2) - D_(w,2)
 D_(w,3) - D_(w,3)
 D_(w,4) - D_(w,4)
 D_(w,5) - D_(w,5)
 D_(w^2,0) - D_(w^2,0)
 D_(w^2,1) - D_(w^2,1)
 D_(w^2,2) - D_(w^2,2)
 D_(w^2,3) - D_(w^2,3)
 D_(w^2,4) - D_(w^2,4)
 D_(w^2,5) - D_(w^2,5)
 Det - tDe
 D_(0,1)t - tD_(0,1)
 D_(0,2)t - tD_(0,2)
 D_(0,3)t - tD_(0,3)
 D_(0,4)t - tD_(0,4)
 D_(0,5)t - tD_(0,5)
 D_(1,0)t - tD_(w^2,0)
 D_(1,1)t - tD_(w^2,1)
 D_(1,2)t - tD_(w^2,2)
 D_(1,3)t - tD_(w^2,3)
 D_(1,4)t - tD_(w^2,4)
 D_(1,5)t - tD_(w^2,5)
 D_(w,0)t - tD_(1,0)
 D_(w,1)t - tD_(1,1)
 D_(w,2)t - tD_(1,2)
 D_(w,3)t - tD_(1,3)
 D_(w,4)t - tD_(1,4)
 D_(w,5)t - tD_(1,5)
 D_(w^2,0)t - tD_(w,0)
 D_(w^2,1)t - tD_(w,1)
 D_(w^2,2)t - tD_(w,2)
 D_(w^2,3)t - tD_(w,3)
 D_(w^2,4)t - tD_(w,4)
 D_(w^2,5)t - tD_(w,5)
 Dex - xDe
 D_(0,1)x - xD_(0,1)
 D_(0,2)x - xD_(0,2)
 D_(0,3)x - xD_(0,3)
 D_(0,4)x - xD_(0,4)
 D_(0,5)x - xD_(0,5)
 D_(1,0)x - xD_(w,0)
 D_(1,1)x - xD_(w,1)
 D_(1,2)x - xD_(w,2)
 D_(1,3)x - xD_(w,3)
 D_(1,4)x - xD_(w,4)
 D_(1,5)x - xD_(w,5)
 D_(w,0)x - xD_(w^2,0)
 D_(w,1)x - xD_(w^2,1)
 D_(w,2)x - xD_(w^2,2)
 D_(w,3)x - xD_(w^2,3)
 D_(w,4)x - xD_(w^2,4)
 D_(w,5)x - xD_(w^2,5)
 D_(w^2,0)x - xD_(1,0)
 D_(w^2,1)x - xD_(1,1)
 D_(w^2,2)x - xD_(1,2)
 D_(w^2,3)x - xD_(1,3)
 D_(w^2,4)x - xD_(1,4)
 D_(w^2,5)x - xD_(1,5)
 Detx - txDe
 D_(0,1)tx - txD_(0,1)
 D_(0,2)tx - txD_(0,2)
 D_(0,3)tx - txD_(0,3)
 D_(0,4)tx - txD_(0,4)
 D_(0,5)tx - txD_(0,5)
 D_(1,0)tx - txD_(1,0)
 D_(1,1)tx - txD_(1,1)
 D_(1,2)tx - txD_(1,2)
 D_(1,3)tx - txD_(1,3)
 D_(1,4)tx - txD_(1,4)
 D_(1,5)tx - txD_(1,5)
 D_(w,0)tx - txD_(w,0)
 D_(w,1)tx - txD_(w,1)
 D_(w,2)tx - txD_(w,2)
 D_(w,3)tx - txD_(w,3)
 D_(w,4)tx - txD_(w,4)
 D_(w,5)tx - txD_(w,5)
 D_(w^2,0)tx - txD_(w^2,0)
 D_(w^2,1)tx - txD_(w^2,1)
 D_(w^2,2)tx - txD_(w^2,2)
 D_(w^2,3)tx - txD_(w^2,3)
 D_(w^2,4)tx - txD_(w^2,4)
 D_(w^2,5)tx - txD_(w^2,5)
 Dex^2 - x^2De
 D_(0,1)x^2 - x^2D_(0,1)
 D_(0,2)x^2 - x^2D_(0,2)
 D_(0,3)x^2 - x^2D_(0,3)
 D_(0,4)x^2 - x^2D_(0,4)
 D_(0,5)x^2 - x^2D_(0,5)
 D_(1,0)x^2 - x^2D_(w^2,0)
 D_(1,1)x^2 - x^2D_(w^2,1)
 D_(1,2)x^2 - x^2D_(w^2,2)
 D_(1,3)x^2 - x^2D_(w^2,3)
 D_(1,4)x^2 - x^2D_(w^2,4)
 D_(1,5)x^2 - x^2D_(w^2,5)
 D_(w,0)x^2 - x^2D_(1,0)
 D_(w,1)x^2 - x^2D_(1,1)
 D_(w,2)x^2 - x^2D_(1,2)
 D_(w,3)x^2 - x^2D_(1,3)
 D_(w,4)x^2 - x^2D_(1,4)
 D_(w,5)x^2 - x^2D_(1,5)
 D_(w^2,0)x^2 - x^2D_(w,0)
 D_(w^2,1)x^2 - x^2D_(w,1)
 D_(w^2,2)x^2 - x^2D_(w,2)
 D_(w^2,3)x^2 - x^2D_(w,3)
 D_(w^2,4)x^2 - x^2D_(w,4)
 D_(w^2,5)x^2 - x^2D_(w,5)
 Detx^2 - tx^2De
 D_(0,1)tx^2 - tx^2D_(0,1)
 D_(0,2)tx^2 - tx^2D_(0,2)
 D_(0,3)tx^2 - tx^2D_(0,3)
 D_(0,4)tx^2 - tx^2D_(0,4)
 D_(0,5)tx^2 - tx^2D_(0,5)
 D_(1,0)tx^2 - tx^2D_(w,0)
 D_(1,1)tx^2 - tx^2D_(w,1)
 D_(1,2)tx^2 - tx^2D_(w,2)
 D_(1,3)tx^2 - tx^2D_(w,3)
 D_(1,4)tx^2 - tx^2D_(w,4)
 D_(1,5)tx^2 - tx^2D_(w,5)
 D_(w,0)tx^2 - tx^2D_(w^2,0)
 D_(w,1)tx^2 - tx^2D_(w^2,1)
 D_(w,2)tx^2 - tx^2D_(w^2,2)
 D_(w,3)tx^2 - tx^2D_(w^2,3)
 D_(w,4)tx^2 - tx^2D_(w^2,4)
 D_(w,5)tx^2 - tx^2D_(w^2,5)
 D_(w^2,0)tx^2 - tx^2D_(1,0)
 D_(w^2,1)tx^2 - tx^2D_(1,1)
 D_(w^2,2)tx^2 - tx^2D_(1,2)
 D_(w^2,3)tx^2 - tx^2D_(1,3)
 D_(w^2,4)tx^2 - tx^2D_(1,4)
 D_(w^2,5)tx^2 - tx^2D_(1,5)
 Dez - zDe
 D_(0,1)z - zD_(w^2,1)
 D_(0,2)z - zD_(w,2)
 D_(0,3)z - zD_(0,3)
 D_(0,4)z - zD_(w^2,4)
 D_(0,5)z - zD_(w,5)
 D_(1,0)z - zD_(1,0)
 D_(1,1)z - zD_(w,1)
 D_(1,2)z - zD_(w^2,2)
 D_(1,3)z - zD_(1,3)
 D_(1,4)z - zD_(w,4)
 D_(1,5)z - zD_(w^2,5)
 D_(w,0)z - zD_(w,0)
 D_(w,1)z - zD_(1,1)
 D_(w,2)z - zD_(0,2)
 D_(w,3)z - zD_(w,3)
 D_(w,4)z - zD_(1,4)
 D_(w,5)z - zD_(0,5)
 D_(w^2,0)z - zD_(w^2,0)
 D_(w^2,1)z - zD_(0,1)
 D_(w^2,2)z - zD_(1,2)
 D_(w^2,3)z - zD_(w^2,3)
 D_(w^2,4)z - zD_(0,4)
 D_(w^2,5)z - zD_(1,5)
 Dezt - ztDe
 D_(0,1)zt - ztD_(w,1)
 D_(0,2)zt - ztD_(1,2)
 D_(0,3)zt - ztD_(0,3)
 D_(0,4)zt - ztD_(w,4)
 D_(0,5)zt - ztD_(1,5)
 D_(1,0)zt - ztD_(w^2,0)
 D_(1,1)zt - ztD_(1,1)
 D_(1,2)zt - ztD_(w,2)
 D_(1,3)zt - ztD_(w^2,3)
 D_(1,4)zt - ztD_(1,4)
 D_(1,5)zt - ztD_(w,5)
 D_(w,0)zt - ztD_(1,0)
 D_(w,1)zt - ztD_(w^2,1)
 D_(w,2)zt - ztD_(0,2)
 D_(w,3)zt - ztD_(1,3)
 D_(w,4)zt - ztD_(w^2,4)
 D_(w,5)zt - ztD_(0,5)
 D_(w^2,0)zt - ztD_(w,0)
 D_(w^2,1)zt - ztD_(0,1)
 D_(w^2,2)zt - ztD_(w^2,2)
 D_(w^2,3)zt - ztD_(w,3)
 D_(w^2,4)zt - ztD_(0,4)
 D_(w^2,5)zt - ztD_(w^2,5)
 Dexy - xyDe
 D_(0,1)xy - xyD_(1,1)
 D_(0,2)xy - xyD_(w^2,2)
 D_(0,3)xy - xyD_(0,3)
 D_(0,4)xy - xyD_(1,4)
 D_(0,5)xy - xyD_(w^2,5)
 D_(1,0)xy - xyD_(w,0)
 D_(1,1)xy - xyD_(w^2,1)
 D_(1,2)xy - xyD_(1,2)
 D_(1,3)xy - xyD_(w,3)
 D_(1,4)xy - xyD_(w^2,4)
 D_(1,5)xy - xyD_(1,5)
 D_(w,0)xy - xyD_(w^2,0)
 D_(w,1)xy - xyD_(w,1)
 D_(w,2)xy - xyD_(0,2)
 D_(w,3)xy - xyD_(w^2,3)
 D_(w,4)xy - xyD_(w,4)
 D_(w,5)xy - xyD_(0,5)
 D_(w^2,0)xy - xyD_(1,0)
 D_(w^2,1)xy - xyD_(0,1)
 D_(w^2,2)xy - xyD_(w,2)
 D_(w^2,3)xy - xyD_(1,3)
 D_(w^2,4)xy - xyD_(0,4)
 D_(w^2,5)xy - xyD_(w,5)
 Detxz - txzDe
 D_(0,1)txz - txzD_(w^2,1)
 D_(0,2)txz - txzD_(w,2)
 D_(0,3)txz - txzD_(0,3)
 D_(0,4)txz - txzD_(w^2,4)
 D_(0,5)txz - txzD_(w,5)
 D_(1,0)txz - txzD_(1,0)
 D_(1,1)txz - txzD_(w,1)
 D_(1,2)txz - txzD_(w^2,2)
 D_(1,3)txz - txzD_(1,3)
 D_(1,4)txz - txzD_(w,4)
 D_(1,5)txz - txzD_(w^2,5)
 D_(w,0)txz - txzD_(w,0)
 D_(w,1)txz - txzD_(1,1)
 D_(w,2)txz - txzD_(0,2)
 D_(w,3)txz - txzD_(w,3)
 D_(w,4)txz - txzD_(1,4)
 D_(w,5)txz - txzD_(0,5)
 D_(w^2,0)txz - txzD_(w^2,0)
 D_(w^2,1)txz - txzD_(0,1)
 D_(w^2,2)txz - txzD_(1,2)
 D_(w^2,3)txz - txzD_(w^2,3)
 D_(w^2,4)txz - txzD_(0,4)
 D_(w^2,5)txz - txzD_(1,5)
 Dexyx - xyxDe
 D_(0,1)xyx - xyxD_(w,1)
 D_(0,2)xyx - xyxD_(1,2)
 D_(0,3)xyx - xyxD_(0,3)
 D_(0,4)xyx - xyxD_(w,4)
 D_(0,5)xyx - xyxD_(1,5)
 D_(1,0)xyx - xyxD_(w^2,0)
 D_(1,1)xyx - xyxD_(1,1)
 D_(1,2)xyx - xyxD_(w,2)
 D_(1,3)xyx - xyxD_(w^2,3)
 D_(1,4)xyx - xyxD_(1,4)
 D_(1,5)xyx - xyxD_(w,5)
 D_(w,0)xyx - xyxD_(1,0)
 D_(w,1)xyx - xyxD_(w^2,1)
 D_(w,2)xyx - xyxD_(0,2)
 D_(w,3)xyx - xyxD_(1,3)
 D_(w,4)xyx - xyxD_(w^2,4)
 D_(w,5)xyx - xyxD_(0,5)
 D_(w^2,0)xyx - xyxD_(w,0)
 D_(w^2,1)xyx - xyxD_(0,1)
 D_(w^2,2)xyx - xyxD_(w^2,2)
 D_(w^2,3)xyx - xyxD_(w,3)
 D_(w^2,4)xyx - xyxD_(0,4)
 D_(w^2,5)xyx - xyxD_(w^2,5)
 Detx^2y - tx^2yDe
 D_(0,1)tx^2y - tx^2yD_(1,1)
 D_(0,2)tx^2y - tx^2yD_(w^2,2)
 D_(0,3)tx^2y - tx^2yD_(0,3)
 D_(0,4)tx^2y - tx^2yD_(1,4)
 D_(0,5)tx^2y - tx^2yD_(w^2,5)
 D_(1,0)tx^2y - tx^2yD_(w,0)
 D_(1,1)tx^2y - tx^2yD_(w^2,1)
 D_(1,2)tx^2y - tx^2yD_(1,2)
 D_(1,3)tx^2y - tx^2yD_(w,3)
 D_(1,4)tx^2y - tx^2yD_(w^2,4)
 D_(1,5)tx^2y - tx^2yD_(1,5)
 D_(w,0)tx^2y - tx^2yD_(w^2,0)
 D_(w,1)tx^2y - tx^2yD_(w,1)
 D_(w,2)tx^2y - tx^2yD_(0,2)
 D_(w,3)tx^2y - tx^2yD_(w^2,3)
 D_(w,4)tx^2y - tx^2yD_(w,4)
 D_(w,5)tx^2y - tx^2yD_(0,5)
 D_(w^2,0)tx^2y - tx^2yD_(1,0)
 D_(w^2,1)tx^2y - tx^2yD_(0,1)
 D_(w^2,2)tx^2y - tx^2yD_(w,2)
 D_(w^2,3)tx^2y - tx^2yD_(1,3)
 D_(w^2,4)tx^2y - tx^2yD_(0,4)
 D_(w^2,5)tx^2y - tx^2yD_(w,5)
 Dey - yDe
 D_(0,1)y - yD_(1,1)
 D_(0,2)y - yD_(w^2,2)
 D_(0,3)y - yD_(0,3)
 D_(0,4)y - yD_(1,4)
 D_(0,5)y - yD_(w^2,5)
 D_(1,0)y - yD_(1,0)
 D_(1,1)y - yD_(0,1)
 D_(1,2)y - yD_(w,2)
 D_(1,3)y - yD_(1,3)
 D_(1,4)y - yD_(0,4)
 D_(1,5)y - yD_(w,5)
 D_(w,0)y - yD_(w,0)
 D_(w,1)y - yD_(w^2,1)
 D_(w,2)y - yD_(1,2)
 D_(w,3)y - yD_(w,3)
 D_(w,4)y - yD_(w^2,4)
 D_(w,5)y - yD_(1,5)
 D_(w^2,0)y - yD_(w^2,0)
 D_(w^2,1)y - yD_(w,1)
 D_(w^2,2)y - yD_(0,2)
 D_(w^2,3)y - yD_(w^2,3)
 D_(w^2,4)y - yD_(w,4)
 D_(w^2,5)y - yD_(0,5)
 Detz - tzDe
 D_(0,1)tz - tzD_(w^2,1)
 D_(0,2)tz - tzD_(w,2)
 D_(0,3)tz - tzD_(0,3)
 D_(0,4)tz - tzD_(w^2,4)
 D_(0,5)tz - tzD_(w,5)
 D_(1,0)tz - tzD_(w^2,0)
 D_(1,1)tz - tzD_(0,1)
 D_(1,2)tz - tzD_(1,2)
 D_(1,3)tz - tzD_(w^2,3)
 D_(1,4)tz - tzD_(0,4)
 D_(1,5)tz - tzD_(1,5)
 D_(w,0)tz - tzD_(1,0)
 D_(w,1)tz - tzD_(w,1)
 D_(w,2)tz - tzD_(w^2,2)
 D_(w,3)tz - tzD_(1,3)
 D_(w,4)tz - tzD_(w,4)
 D_(w,5)tz - tzD_(w^2,5)
 D_(w^2,0)tz - tzD_(w,0)
 D_(w^2,1)tz - tzD_(1,1)
 D_(w^2,2)tz - tzD_(0,2)
 D_(w^2,3)tz - tzD_(w,3)
 D_(w^2,4)tz - tzD_(1,4)
 D_(w^2,5)tz - tzD_(0,5)
 Deyx - yxDe
 D_(0,1)yx - yxD_(w,1)
 D_(0,2)yx - yxD_(1,2)
 D_(0,3)yx - yxD_(0,3)
 D_(0,4)yx - yxD_(w,4)
 D_(0,5)yx - yxD_(1,5)
 D_(1,0)yx - yxD_(w,0)
 D_(1,1)yx - yxD_(0,1)
 D_(1,2)yx - yxD_(w^2,2)
 D_(1,3)yx - yxD_(w,3)
 D_(1,4)yx - yxD_(0,4)
 D_(1,5)yx - yxD_(w^2,5)
 D_(w,0)yx - yxD_(w^2,0)
 D_(w,1)yx - yxD_(1,1)
 D_(w,2)yx - yxD_(w,2)
 D_(w,3)yx - yxD_(w^2,3)
 D_(w,4)yx - yxD_(1,4)
 D_(w,5)yx - yxD_(w,5)
 D_(w^2,0)yx - yxD_(1,0)
 D_(w^2,1)yx - yxD_(w^2,1)
 D_(w^2,2)yx - yxD_(0,2)
 D_(w^2,3)yx - yxD_(1,3)
 D_(w^2,4)yx - yxD_(w^2,4)
 D_(w^2,5)yx - yxD_(0,5)
 Detxy - txyDe
 D_(0,1)txy - txyD_(1,1)
 D_(0,2)txy - txyD_(w^2,2)
 D_(0,3)txy - txyD_(0,3)
 D_(0,4)txy - txyD_(1,4)
 D_(0,5)txy - txyD_(w^2,5)
 D_(1,0)txy - txyD_(1,0)
 D_(1,1)txy - txyD_(0,1)
 D_(1,2)txy - txyD_(w,2)
 D_(1,3)txy - txyD_(1,3)
 D_(1,4)txy - txyD_(0,4)
 D_(1,5)txy - txyD_(w,5)
 D_(w,0)txy - txyD_(w,0)
 D_(w,1)txy - txyD_(w^2,1)
 D_(w,2)txy - txyD_(1,2)
 D_(w,3)txy - txyD_(w,3)
 D_(w,4)txy - txyD_(w^2,4)
 D_(w,5)txy - txyD_(1,5)
 D_(w^2,0)txy - txyD_(w^2,0)
 D_(w^2,1)txy - txyD_(w,1)
 D_(w^2,2)txy - txyD_(0,2)
 D_(w^2,3)txy - txyD_(w^2,3)
 D_(w^2,4)txy - txyD_(w,4)
 D_(w^2,5)txy - txyD_(0,5)
 Dex^2z - x^2zDe
 D_(0,1)x^2z - x^2zD_(w^2,1)
 D_(0,2)x^2z - x^2zD_(w,2)
 D_(0,3)x^2z - x^2zD_(0,3)
 D_(0,4)x^2z - x^2zD_(w^2,4)
 D_(0,5)x^2z - x^2zD_(w,5)
 D_(1,0)x^2z - x^2zD_(w^2,0)
 D_(1,1)x^2z - x^2zD_(0,1)
 D_(1,2)x^2z - x^2zD_(1,2)
 D_(1,3)x^2z - x^2zD_(w^2,3)
 D_(1,4)x^2z - x^2zD_(0,4)
 D_(1,5)x^2z - x^2zD_(1,5)
 D_(w,0)x^2z - x^2zD_(1,0)
 D_(w,1)x^2z - x^2zD_(w,1)
 D_(w,2)x^2z - x^2zD_(w^2,2)
 D_(w,3)x^2z - x^2zD_(1,3)
 D_(w,4)x^2z - x^2zD_(w,4)
 D_(w,5)x^2z - x^2zD_(w^2,5)
 D_(w^2,0)x^2z - x^2zD_(w,0)
 D_(w^2,1)x^2z - x^2zD_(1,1)
 D_(w^2,2)x^2z - x^2zD_(0,2)
 D_(w^2,3)x^2z - x^2zD_(w,3)
 D_(w^2,4)x^2z - x^2zD_(1,4)
 D_(w^2,5)x^2z - x^2zD_(0,5)
 Detx^2yz - tx^2yzDe
 D_(0,1)tx^2yz - tx^2yzD_(w,1)
 D_(0,2)tx^2yz - tx^2yzD_(1,2)
 D_(0,3)tx^2yz - tx^2yzD_(0,3)
 D_(0,4)tx^2yz - tx^2yzD_(w,4)
 D_(0,5)tx^2yz - tx^2yzD_(1,5)
 D_(1,0)tx^2yz - tx^2yzD_(w,0)
 D_(1,1)tx^2yz - tx^2yzD_(0,1)
 D_(1,2)tx^2yz - tx^2yzD_(w^2,2)
 D_(1,3)tx^2yz - tx^2yzD_(w,3)
 D_(1,4)tx^2yz - tx^2yzD_(0,4)
 D_(1,5)tx^2yz - tx^2yzD_(w^2,5)
 D_(w,0)tx^2yz - tx^2yzD_(w^2,0)
 D_(w,1)tx^2yz - tx^2yzD_(1,1)
 D_(w,2)tx^2yz - tx^2yzD_(w,2)
 D_(w,3)tx^2yz - tx^2yzD_(w^2,3)
 D_(w,4)tx^2yz - tx^2yzD_(1,4)
 D_(w,5)tx^2yz - tx^2yzD_(w,5)
 D_(w^2,0)tx^2yz - tx^2yzD_(1,0)
 D_(w^2,1)tx^2yz - tx^2yzD_(w^2,1)
 D_(w^2,2)tx^2yz - tx^2yzD_(0,2)
 D_(w^2,3)tx^2yz - tx^2yzD_(1,3)
 D_(w^2,4)tx^2yz - tx^2yzD_(w^2,4)
 D_(w^2,5)tx^2yz - tx^2yzD_(0,5)
 Deyz - yzDe
 D_(0,1)yz - yzD_(w,1)
 D_(0,2)yz - yzD_(1,2)
 D_(0,3)yz - yzD_(0,3)
 D_(0,4)yz - yzD_(w,4)
 D_(0,5)yz - yzD_(1,5)
 D_(1,0)yz - yzD_(1,0)
 D_(1,1)yz - yzD_(w^2,1)
 D_(1,2)yz - yzD_(0,2)
 D_(1,3)yz - yzD_(1,3)
 D_(1,4)yz - yzD_(w^2,4)
 D_(1,5)yz - yzD_(0,5)
 D_(w,0)yz - yzD_(w,0)
 D_(w,1)yz - yzD_(0,1)
 D_(w,2)yz - yzD_(w^2,2)
 D_(w,3)yz - yzD_(w,3)
 D_(w,4)yz - yzD_(0,4)
 D_(w,5)yz - yzD_(w^2,5)
 D_(w^2,0)yz - yzD_(w^2,0)
 D_(w^2,1)yz - yzD_(1,1)
 D_(w^2,2)yz - yzD_(w,2)
 D_(w^2,3)yz - yzD_(w^2,3)
 D_(w^2,4)yz - yzD_(1,4)
 D_(w^2,5)yz - yzD_(w,5)
 Dety - tyDe
 D_(0,1)ty - tyD_(1,1)
 D_(0,2)ty - tyD_(w^2,2)
 D_(0,3)ty - tyD_(0,3)
 D_(0,4)ty - tyD_(1,4)
 D_(0,5)ty - tyD_(w^2,5)
 D_(1,0)ty - tyD_(w^2,0)
 D_(1,1)ty - tyD_(w,1)
 D_(1,2)ty - tyD_(0,2)
 D_(1,3)ty - tyD_(w^2,3)
 D_(1,4)ty - tyD_(w,4)
 D_(1,5)ty - tyD_(0,5)
 D_(w,0)ty - tyD_(1,0)
 D_(w,1)ty - tyD_(0,1)
 D_(w,2)ty - tyD_(w,2)
 D_(w,3)ty - tyD_(1,3)
 D_(w,4)ty - tyD_(0,4)
 D_(w,5)ty - tyD_(w,5)
 D_(w^2,0)ty - tyD_(w,0)
 D_(w^2,1)ty - tyD_(w^2,1)
 D_(w^2,2)ty - tyD_(1,2)
 D_(w^2,3)ty - tyD_(w,3)
 D_(w^2,4)ty - tyD_(w^2,4)
 D_(w^2,5)ty - tyD_(1,5)
 Dexz - xzDe
 D_(0,1)xz - xzD_(w^2,1)
 D_(0,2)xz - xzD_(w,2)
 D_(0,3)xz - xzD_(0,3)
 D_(0,4)xz - xzD_(w^2,4)
 D_(0,5)xz - xzD_(w,5)
 D_(1,0)xz - xzD_(w,0)
 D_(1,1)xz - xzD_(1,1)
 D_(1,2)xz - xzD_(0,2)
 D_(1,3)xz - xzD_(w,3)
 D_(1,4)xz - xzD_(1,4)
 D_(1,5)xz - xzD_(0,5)
 D_(w,0)xz - xzD_(w^2,0)
 D_(w,1)xz - xzD_(0,1)
 D_(w,2)xz - xzD_(1,2)
 D_(w,3)xz - xzD_(w^2,3)
 D_(w,4)xz - xzD_(0,4)
 D_(w,5)xz - xzD_(1,5)
 D_(w^2,0)xz - xzD_(1,0)
 D_(w^2,1)xz - xzD_(w,1)
 D_(w^2,2)xz - xzD_(w^2,2)
 D_(w^2,3)xz - xzD_(1,3)
 D_(w^2,4)xz - xzD_(w,4)
 D_(w^2,5)xz - xzD_(w^2,5)
 Detyx - tyxDe
 D_(0,1)tyx - tyxD_(w,1)
 D_(0,2)tyx - tyxD_(1,2)
 D_(0,3)tyx - tyxD_(0,3)
 D_(0,4)tyx - tyxD_(w,4)
 D_(0,5)tyx - tyxD_(1,5)
 D_(1,0)tyx - tyxD_(1,0)
 D_(1,1)tyx - tyxD_(w^2,1)
 D_(1,2)tyx - tyxD_(0,2)
 D_(1,3)tyx - tyxD_(1,3)
 D_(1,4)tyx - tyxD_(w^2,4)
 D_(1,5)tyx - tyxD_(0,5)
 D_(w,0)tyx - tyxD_(w,0)
 D_(w,1)tyx - tyxD_(0,1)
 D_(w,2)tyx - tyxD_(w^2,2)
 D_(w,3)tyx - tyxD_(w,3)
 D_(w,4)tyx - tyxD_(0,4)
 D_(w,5)tyx - tyxD_(w^2,5)
 D_(w^2,0)tyx - tyxD_(w^2,0)
 D_(w^2,1)tyx - tyxD_(1,1)
 D_(w^2,2)tyx - tyxD_(w,2)
 D_(w^2,3)tyx - tyxD_(w^2,3)
 D_(w^2,4)tyx - tyxD_(1,4)
 D_(w^2,5)tyx - tyxD_(w,5)
 Dex^2y - x^2yDe
 D_(0,1)x^2y - x^2yD_(1,1)
 D_(0,2)x^2y - x^2yD_(w^2,2)
 D_(0,3)x^2y - x^2yD_(0,3)
 D_(0,4)x^2y - x^2yD_(1,4)
 D_(0,5)x^2y - x^2yD_(w^2,5)
 D_(1,0)x^2y - x^2yD_(w^2,0)
 D_(1,1)x^2y - x^2yD_(w,1)
 D_(1,2)x^2y - x^2yD_(0,2)
 D_(1,3)x^2y - x^2yD_(w^2,3)
 D_(1,4)x^2y - x^2yD_(w,4)
 D_(1,5)x^2y - x^2yD_(0,5)
 D_(w,0)x^2y - x^2yD_(1,0)
 D_(w,1)x^2y - x^2yD_(0,1)
 D_(w,2)x^2y - x^2yD_(w,2)
 D_(w,3)x^2y - x^2yD_(1,3)
 D_(w,4)x^2y - x^2yD_(0,4)
 D_(w,5)x^2y - x^2yD_(w,5)
 D_(w^2,0)x^2y - x^2yD_(w,0)
 D_(w^2,1)x^2y - x^2yD_(w^2,1)
 D_(w^2,2)x^2y - x^2yD_(1,2)
 D_(w^2,3)x^2y - x^2yD_(w,3)
 D_(w^2,4)x^2y - x^2yD_(w^2,4)
 D_(w^2,5)x^2y - x^2yD_(1,5)
 Detx^2z - tx^2zDe
 D_(0,1)tx^2z - tx^2zD_(w^2,1)
 D_(0,2)tx^2z - tx^2zD_(w,2)
 D_(0,3)tx^2z - tx^2zD_(0,3)
 D_(0,4)tx^2z - tx^2zD_(w^2,4)
 D_(0,5)tx^2z - tx^2zD_(w,5)
 D_(1,0)tx^2z - tx^2zD_(w,0)
 D_(1,1)tx^2z - tx^2zD_(1,1)
 D_(1,2)tx^2z - tx^2zD_(0,2)
 D_(1,3)tx^2z - tx^2zD_(w,3)
 D_(1,4)tx^2z - tx^2zD_(1,4)
 D_(1,5)tx^2z - tx^2zD_(0,5)
 D_(w,0)tx^2z - tx^2zD_(w^2,0)
 D_(w,1)tx^2z - tx^2zD_(0,1)
 D_(w,2)tx^2z - tx^2zD_(1,2)
 D_(w,3)tx^2z - tx^2zD_(w^2,3)
 D_(w,4)tx^2z - tx^2zD_(0,4)
 D_(w,5)tx^2z - tx^2zD_(1,5)
 D_(w^2,0)tx^2z - tx^2zD_(1,0)
 D_(w^2,1)tx^2z - tx^2zD_(w,1)
 D_(w^2,2)tx^2z - tx^2zD_(w^2,2)
 D_(w^2,3)tx^2z - tx^2zD_(1,3)
 D_(w^2,4)tx^2z - tx^2zD_(w,4)
 D_(w^2,5)tx^2z - tx^2zD_(w^2,5)

In [118]:
J := SGrobner(Concatenation(
    relsGroup,
    relskG,
    relsDG,
    gensX,
    gensY
    )
);;
DimQA(J, 36);

576

In [119]:
PrintNPList(BaseQA(J, 36, 0));

 1
 t
 x
 y
 z
 De
 D_(0,1)
 D_(0,2)
 D_(0,3)
 D_(0,4)
 D_(0,5)
 D_(1,0)
 D_(1,1)
 D_(1,2)
 D_(1,3)
 D_(1,4)
 D_(1,5)
 D_(w,0)
 D_(w,1)
 D_(w,2)
 D_(w,3)
 D_(w,4)
 D_(w,5)
 D_(w^2,0)
 D_(w^2,1)
 D_(w^2,2)
 D_(w^2,3)
 D_(w^2,4)
 tx
 ty
 tz
 tDe
 tD_(0,1)
 tD_(0,2)
 tD_(0,3)
 tD_(0,4)
 tD_(0,5)
 tD_(1,0)
 tD_(1,1)
 tD_(1,2)
 tD_(1,3)
 tD_(1,4)
 tD_(1,5)
 tD_(w,0)
 tD_(w,1)
 tD_(w,2)
 tD_(w,3)
 tD_(w,4)
 tD_(w,5)
 tD_(w^2,0)
 tD_(w^2,1)
 tD_(w^2,2)
 tD_(w^2,3)
 tD_(w^2,4)
 x^2
 xy
 xz
 xDe
 xD_(0,1)
 xD_(0,2)
 xD_(0,3)
 xD_(0,4)
 xD_(0,5)
 xD_(1,0)
 xD_(1,1)
 xD_(1,2)
 xD_(1,3)
 xD_(1,4)
 xD_(1,5)
 xD_(w,0)
 xD_(w,1)
 xD_(w,2)
 xD_(w,3)
 xD_(w,4)
 xD_(w,5)
 xD_(w^2,0)
 xD_(w^2,1)
 xD_(w^2,2)
 xD_(w^2,3)
 xD_(w^2,4)
 yx
 yz
 yDe
 yD_(0,1)
 yD_(0,2)
 yD_(0,3)
 yD_(0,4)
 yD_(0,5)
 yD_(1,0)
 yD_(1,1)
 yD_(1,2)
 yD_(1,3)
 yD_(1,4)
 yD_(1,5)
 yD_(w,0)
 yD_(w,1)
 yD_(w,2)
 yD_(w,3)
 yD_(w,4)
 yD_(w,5)
 yD_(w^2,0)
 yD_(w^2,1)
 yD_(w^2,2)
 yD_(w^2,3)
 yD_(w^2,4)
 zt
 zDe
 zD_(0,1)
 zD_(0,2)
 zD_(0,3)
 zD_(0,4)
 zD_(0,5)
 zD_(1,0)
 zD_(1,1)
 zD_(1,2)
 zD_(1,3)
 zD_(1,4)
 zD_(1,5)
 zD_(w,0)
 zD_(w,1)
 zD_(w,2)
 zD_(w,3)
 zD_(w,4)
 zD_(w,5)
 zD_(w^2,0)
 zD_(w^2,1)
 zD_(w^2,2)
 zD_(w^2,3)
 zD_(w^2,4)
 tx^2
 txy
 txz
 txDe
 txD_(0,1)
 txD_(0,2)
 txD_(0,3)
 txD_(0,4)
 txD_(0,5)
 txD_(1,0)
 txD_(1,1)
 txD_(1,2)
 txD_(1,3)
 txD_(1,4)
 txD_(1,5)
 txD_(w,0)
 txD_(w,1)
 txD_(w,2)
 txD_(w,3)
 txD_(w,4)
 txD_(w,5)
 txD_(w^2,0)
 txD_(w^2,1)
 txD_(w^2,2)
 txD_(w^2,3)
 txD_(w^2,4)
 tyx
 tyDe
 tyD_(0,1)
 tyD_(0,2)
 tyD_(0,3)
 tyD_(0,4)
 tyD_(0,5)
 tyD_(1,0)
 tyD_(1,1)
 tyD_(1,2)
 tyD_(1,3)
 tyD_(1,4)
 tyD_(1,5)
 tyD_(w,0)
 tyD_(w,1)
 tyD_(w,2)
 tyD_(w,3)
 tyD_(w,4)
 tyD_(w,5)
 tyD_(w^2,0)
 tyD_(w^2,1)
 tyD_(w^2,2)
 tyD_(w^2,3)
 tyD_(w^2,4)
 tzDe
 tzD_(0,1)
 tzD_(0,2)
 tzD_(0,3)
 tzD_(0,4)
 tzD_(0,5)
 tzD_(1,0)
 tzD_(1,1)
 tzD_(1,2)
 tzD_(1,3)
 tzD_(1,4)
 tzD_(1,5)
 tzD_(w,0)
 tzD_(w,1)
 tzD_(w,2)
 tzD_(w,3)
 tzD_(w,4)
 tzD_(w,5)
 tzD_(w^2,0)
 tzD_(w^2,1)
 tzD_(w^2,2)
 tzD_(w^2,3)
 tzD_(w^2,4)
 x^2y
 x^2z
 x^2De
 x^2D_(0,1)
 x^2D_(0,2)
 x^2D_(0,3)
 x^2D_(0,4)
 x^2D_(0,5)
 x^2D_(1,0)
 x^2D_(1,1)
 x^2D_(1,2)
 x^2D_(1,3)
 x^2D_(1,4)
 x^2D_(1,5)
 x^2D_(w,0)
 x^2D_(w,1)
 x^2D_(w,2)
 x^2D_(w,3)
 x^2D_(w,4)
 x^2D_(w,5)
 x^2D_(w^2,0)
 x^2D_(w^2,1)
 x^2D_(w^2,2)
 x^2D_(w^2,3)
 x^2D_(w^2,4)
 xyx
 xyDe
 xyD_(0,1)
 xyD_(0,2)
 xyD_(0,3)
 xyD_(0,4)
 xyD_(0,5)
 xyD_(1,0)
 xyD_(1,1)
 xyD_(1,2)
 xyD_(1,3)
 xyD_(1,4)
 xyD_(1,5)
 xyD_(w,0)
 xyD_(w,1)
 xyD_(w,2)
 xyD_(w,3)
 xyD_(w,4)
 xyD_(w,5)
 xyD_(w^2,0)
 xyD_(w^2,1)
 xyD_(w^2,2)
 xyD_(w^2,3)
 xyD_(w^2,4)
 xzDe
 xzD_(0,1)
 xzD_(0,2)
 xzD_(0,3)
 xzD_(0,4)
 xzD_(0,5)
 xzD_(1,0)
 xzD_(1,1)
 xzD_(1,2)
 xzD_(1,3)
 xzD_(1,4)
 xzD_(1,5)
 xzD_(w,0)
 xzD_(w,1)
 xzD_(w,2)
 xzD_(w,3)
 xzD_(w,4)
 xzD_(w,5)
 xzD_(w^2,0)
 xzD_(w^2,1)
 xzD_(w^2,2)
 xzD_(w^2,3)
 xzD_(w^2,4)
 yxDe
 yxD_(0,1)
 yxD_(0,2)
 yxD_(0,3)
 yxD_(0,4)
 yxD_(0,5)
 yxD_(1,0)
 yxD_(1,1)
 yxD_(1,2)
 yxD_(1,3)
 yxD_(1,4)
 yxD_(1,5)
 yxD_(w,0)
 yxD_(w,1)
 yxD_(w,2)
 yxD_(w,3)
 yxD_(w,4)
 yxD_(w,5)
 yxD_(w^2,0)
 yxD_(w^2,1)
 yxD_(w^2,2)
 yxD_(w^2,3)
 yxD_(w^2,4)
 yzDe
 yzD_(0,1)
 yzD_(0,2)
 yzD_(0,3)
 yzD_(0,4)
 yzD_(0,5)
 yzD_(1,0)
 yzD_(1,1)
 yzD_(1,2)
 yzD_(1,3)
 yzD_(1,4)
 yzD_(1,5)
 yzD_(w,0)
 yzD_(w,1)
 yzD_(w,2)
 yzD_(w,3)
 yzD_(w,4)
 yzD_(w,5)
 yzD_(w^2,0)
 yzD_(w^2,1)
 yzD_(w^2,2)
 yzD_(w^2,3)
 yzD_(w^2,4)
 ztDe
 ztD_(0,1)
 ztD_(0,2)
 ztD_(0,3)
 ztD_(0,4)
 ztD_(0,5)
 ztD_(1,0)
 ztD_(1,1)
 ztD_(1,2)
 ztD_(1,3)
 ztD_(1,4)
 ztD_(1,5)
 ztD_(w,0)
 ztD_(w,1)
 ztD_(w,2)
 ztD_(w,3)
 ztD_(w,4)
 ztD_(w,5)
 ztD_(w^2,0)
 ztD_(w^2,1)
 ztD_(w^2,2)
 ztD_(w^2,3)
 ztD_(w^2,4)
 tx^2y
 tx^2z
 tx^2De
 tx^2D_(0,1)
 tx^2D_(0,2)
 tx^2D_(0,3)
 tx^2D_(0,4)
 tx^2D_(0,5)
 tx^2D_(1,0)
 tx^2D_(1,1)
 tx^2D_(1,2)
 tx^2D_(1,3)
 tx^2D_(1,4)
 tx^2D_(1,5)
 tx^2D_(w,0)
 tx^2D_(w,1)
 tx^2D_(w,2)
 tx^2D_(w,3)
 tx^2D_(w,4)
 tx^2D_(w,5)
 tx^2D_(w^2,0)
 tx^2D_(w^2,1)
 tx^2D_(w^2,2)
 tx^2D_(w^2,3)
 tx^2D_(w^2,4)
 txyx
 txyDe
 txyD_(0,1)
 txyD_(0,2)
 txyD_(0,3)
 txyD_(0,4)
 txyD_(0,5)
 txyD_(1,0)
 txyD_(1,1)
 txyD_(1,2)
 txyD_(1,3)
 txyD_(1,4)
 txyD_(1,5)
 txyD_(w,0)
 txyD_(w,1)
 txyD_(w,2)
 txyD_(w,3)
 txyD_(w,4)
 txyD_(w,5)
 txyD_(w^2,0)
 txyD_(w^2,1)
 txyD_(w^2,2)
 txyD_(w^2,3)
 txyD_(w^2,4)
 txzDe
 txzD_(0,1)
 txzD_(0,2)
 txzD_(0,3)
 txzD_(0,4)
 txzD_(0,5)
 txzD_(1,0)
 txzD_(1,1)
 txzD_(1,2)
 txzD_(1,3)
 txzD_(1,4)
 txzD_(1,5)
 txzD_(w,0)
 txzD_(w,1)
 txzD_(w,2)
 txzD_(w,3)
 txzD_(w,4)
 txzD_(w,5)
 txzD_(w^2,0)
 txzD_(w^2,1)
 txzD_(w^2,2)
 txzD_(w^2,3)
 txzD_(w^2,4)
 tyxDe
 tyxD_(0,1)
 tyxD_(0,2)
 tyxD_(0,3)
 tyxD_(0,4)
 tyxD_(0,5)
 tyxD_(1,0)
 tyxD_(1,1)
 tyxD_(1,2)
 tyxD_(1,3)
 tyxD_(1,4)
 tyxD_(1,5)
 tyxD_(w,0)
 tyxD_(w,1)
 tyxD_(w,2)
 tyxD_(w,3)
 tyxD_(w,4)
 tyxD_(w,5)
 tyxD_(w^2,0)
 tyxD_(w^2,1)
 tyxD_(w^2,2)
 tyxD_(w^2,3)
 tyxD_(w^2,4)
 x^2yDe
 x^2yD_(0,1)
 x^2yD_(0,2)
 x^2yD_(0,3)
 x^2yD_(0,4)
 x^2yD_(0,5)
 x^2yD_(1,0)
 x^2yD_(1,1)
 x^2yD_(1,2)
 x^2yD_(1,3)
 x^2yD_(1,4)
 x^2yD_(1,5)
 x^2yD_(w,0)
 x^2yD_(w,1)
 x^2yD_(w,2)
 x^2yD_(w,3)
 x^2yD_(w,4)
 x^2yD_(w,5)
 x^2yD_(w^2,0)
 x^2yD_(w^2,1)
 x^2yD_(w^2,2)
 x^2yD_(w^2,3)
 x^2yD_(w^2,4)
 x^2zDe
 x^2zD_(0,1)
 x^2zD_(0,2)
 x^2zD_(0,3)
 x^2zD_(0,4)
 x^2zD_(0,5)
 x^2zD_(1,0)
 x^2zD_(1,1)
 x^2zD_(1,2)
 x^2zD_(1,3)
 x^2zD_(1,4)
 x^2zD_(1,5)
 x^2zD_(w,0)
 x^2zD_(w,1)
 x^2zD_(w,2)
 x^2zD_(w,3)
 x^2zD_(w,4)
 x^2zD_(w,5)
 x^2zD_(w^2,0)
 x^2zD_(w^2,1)
 x^2zD_(w^2,2)
 x^2zD_(w^2,3)
 x^2zD_(w^2,4)
 xyxDe
 xyxD_(0,1)
 xyxD_(0,2)
 xyxD_(0,3)
 xyxD_(0,4)
 xyxD_(0,5)
 xyxD_(1,0)
 xyxD_(1,1)
 xyxD_(1,2)
 xyxD_(1,3)
 xyxD_(1,4)
 xyxD_(1,5)
 xyxD_(w,0)
 xyxD_(w,1)
 xyxD_(w,2)
 xyxD_(w,3)
 xyxD_(w,4)
 xyxD_(w,5)
 xyxD_(w^2,0)
 xyxD_(w^2,1)
 xyxD_(w^2,2)
 xyxD_(w^2,3)
 xyxD_(w^2,4)
 tx^2yDe
 tx^2yD_(0,1)
 tx^2yD_(0,2)
 tx^2yD_(0,3)
 tx^2yD_(0,4)
 tx^2yD_(0,5)
 tx^2yD_(1,0)
 tx^2yD_(1,1)
 tx^2yD_(1,2)
 tx^2yD_(1,3)
 tx^2yD_(1,4)
 tx^2yD_(1,5)
 tx^2yD_(w,0)
 tx^2yD_(w,1)
 tx^2yD_(w,2)
 tx^2yD_(w,3)
 tx^2yD_(w,4)
 tx^2yD_(w,5)
 tx^2yD_(w^2,0)
 tx^2yD_(w^2,1)
 tx^2yD_(w^2,2)
 tx^2yD_(w^2,3)
 tx^2yD_(w^2,4)
 tx^2zDe
 tx^2zD_(0,1)
 tx^2zD_(0,2)
 tx^2zD_(0,3)
 tx^2zD_(0,4)
 tx^2zD_(0,5)
 tx^2zD_(1,0)
 tx^2zD_(1,1)
 tx^2zD_(1,2)
 tx^2zD_(1,3)
 tx^2zD_(1,4)
 tx^2zD_(1,5)
 tx^2zD_(w,0)
 tx^2zD_(w,1)
 tx^2zD_(w,2)
 tx^2zD_(w,3)
 tx^2zD_(w,4)
 tx^2zD_(w,5)
 tx^2zD_(w^2,0)
 tx^2zD_(w^2,1)
 tx^2zD_(w^2,2)
 tx^2zD_(w^2,3)
 tx^2zD_(w^2,4)
 txyxDe
 txyxD_(0,1)
 txyxD_(0,2)
 txyxD_(0,3)
 txyxD_(0,4)
 txyxD_(0,5)
 txyxD_(1,0)
 txyxD_(1,1)
 txyxD_(1,2)
 txyxD_(1,3)
 txyxD_(1,4)
 txyxD_(1,5)
 txyxD_(w,0)
 txyxD_(w,1)
 txyxD_(w,2)
 txyxD_(w,3)
 txyxD_(w,4)
 txyxD_(w,5)
 txyxD_(w^2,0)
 txyxD_(w^2,1)
 txyxD_(w^2,2)
 txyxD_(w^2,3)
 txyxD_(w^2,4)

# El algebra $\mathfrak{B}(V)\#\Bbbk G$

## Relaciones $(b, t^s) x_{j} = (-1)^s x_{\omega^2 b + \omega^s j}(b,t^s)$, evaluadas para todos los $(b,t^s) \in G$

### En términos de $x_{j}$ para todo $(b,t^s) \in G$


- Caso $j = 0$ entonces $i=\omega^2 b + \omega^s j=\omega^2b$, con $s=\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=0$. Entonces, $(0,t^s)X_{0}=(-1)^sX_0(0,t^s)$

\begin{aligned}
(0, t^0)\,x_{0} &= x_{0}\,(0, t^0), \\[4pt]
(0, t^1)\,x_{0} &= -\,x_{0}\,(0, t^1), \\[4pt]
(0, t^2)\,x_{0} &= x_{0}\,(0, t^2), \\[4pt]
(0, t^3)\,x_{0} &= -x_{0}\,(0, t^3), \\[4pt]
(0, t^4)\,x_{0} &= \,x_{0}\,(0, t^4), \\[4pt]
(0, t^5)\,x_{0} &= -\,x_{0}\,(0, t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2$. Entonces, $(1,t^s)X_{0}=(-1)^sX_{\omega^2}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{0} &= x_{\omega^2}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{0} &= -\,x_{\omega^2}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{0} &= x_{\omega^2}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{0} &= -\,x_{\omega^2}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{0} &= x_{\omega^2}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{0} &= -\,x_{\omega^2}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1$. Entonces, $(\omega,t^s)X_{0}=(-1)^sX_{1}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{0} &= x_{1}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{0} &= -\,x_{1}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{0} &= x_{1}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{0} &= -\,x_{1}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{0} &= x_{1}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{0} &= -\,x_{1}\,(\omega,t^5).
\end{aligned}


4. si $h=(\omega^2, t^s)$ entonces $i=\omega$. Entonces, $(\omega^2,t^s)X_{0}=(-1)^sX_{\omega}(\omega^2,t^s)$


\begin{aligned}
(\omega^2,t^0)\,x_{0} &= x_{\omega}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{0} &= x_{\omega}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{0} &= x_{\omega}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^5).
\end{aligned}

In [120]:
elmsG := GetElementsOfG();;

In [121]:
gensA:=QGNAG.Config.gensA;

[ 0*Z(2), Z(2)^0, Z(2^2), Z(2^2)^2 ]

In [125]:
Case1 := Filtered(elmsG, el -> el!.FieldPart = gensA[1]);
Case2 := Filtered(elmsG, el -> el!.FieldPart = gensA[2]);
Case3 := Filtered(elmsG, el -> el!.FieldPart = gensA[3]);
Case4 := Filtered(elmsG, el -> el!.FieldPart = gensA[4]);

[ ( 0*Z(2) , 0 ), ( 0*Z(2) , 1 ), ( 0*Z(2) , 2 ), ( 0*Z(2) , 3 ),   ( 0*Z(2) , 4 ), ( 0*Z(2) , 5 ) ]

[ ( Z(2)^0 , 0 ), ( Z(2)^0 , 1 ), ( Z(2)^0 , 2 ), ( Z(2)^0 , 3 ),   ( Z(2)^0 , 4 ), ( Z(2)^0 , 5 ) ]

[ ( Z(2^2) , 0 ), ( Z(2^2) , 1 ), ( Z(2^2) , 2 ), ( Z(2^2) , 3 ),   ( Z(2^2) , 4 ), ( Z(2^2) , 5 ) ]

[ ( Z(2^2)^2 , 0 ), ( Z(2^2)^2 , 1 ), ( Z(2^2)^2 , 2 ), ( Z(2^2)^2 , 3 ),   ( Z(2^2)^2 , 4 ), ( Z(2^2)^2 , 5 ) ]

In [127]:
rels0Case1 := RelationsGivenByNicholsSmashkG(gensA[1], Case1);;
PrintNPList(rels0Case1);

 X0 - X0
 tX0 + X0t
 xX0 - X0x
 txX0 + X0tx
 x^2X0 - X0x^2
 tx^2X0 + X0tx^2

In [129]:
rels0Case2 := RelationsGivenByNicholsSmashkG(gensA[1], Case2);;
PrintNPList(rels0Case2);

 zX0 - X3z
 ztX0 + X3zt
 xyX0 - X3xy
 txzX0 + X3txz
 xyxX0 - X3xyx
 tx^2yX0 + X3tx^2y

In [131]:
rels0Case3 := RelationsGivenByNicholsSmashkG(gensA[1], Case3);;
PrintNPList(rels0Case3);

 yX0 - X1y
 tzX0 + X1tz
 yxX0 - X1yx
 txyX0 + X1txy
 x^2zX0 - X1x^2z
 tx^2yzX0 + X1tx^2yz

In [133]:
rels0Case4 := RelationsGivenByNicholsSmashkG(gensA[1], Case4);;
PrintNPList(rels0Case4);

 yzX0 - X2yz
 tyX0 + X2ty
 xzX0 - X2xz
 tyxX0 + X2tyx
 x^2yX0 - X2x^2y
 tx^2zX0 + X2tx^2z

In [135]:
rels1Case1 := RelationsGivenByNicholsSmashkG(gensA[2], Case1);;
PrintNPList(rels1Case1);

 X1 - X1
 tX1 + X2t
 xX1 - X3x
 txX1 + X1tx
 x^2X1 - X2x^2
 tx^2X1 + X3tx^2

In [137]:
rels1Case2 := RelationsGivenByNicholsSmashkG(gensA[2], Case2);;
PrintNPList(rels1Case2);

 zX1 - X2z
 ztX1 + X1zt
 xyX1 - X0xy
 txzX1 + X2txz
 xyxX1 - X1xyx
 tx^2yX1 + X0tx^2y

In [139]:
rels1Case3 := RelationsGivenByNicholsSmashkG(gensA[2], Case3);;
PrintNPList(rels1Case3);

 yX1 - X0y
 tzX1 + X3tz
 yxX1 - X2yx
 txyX1 + X0txy
 x^2zX1 - X3x^2z
 tx^2yzX1 + X2tx^2yz

In [141]:
rels1Case4 := RelationsGivenByNicholsSmashkG(gensA[2], Case4);;
PrintNPList(rels1Case4);

 yzX1 - X3yz
 tyX1 + X0ty
 xzX1 - X1xz
 tyxX1 + X3tyx
 x^2yX1 - X0x^2y
 tx^2zX1 + X1tx^2z

In [141]:
relsOmegaCase1 := RelationsGivenByNicholsSmashkG(gensA[3], Case1);;
PrintNPList(relsOmegaCase1);

 X2 - X2
 tX2 + X3t
 xX2 - X1x
 txX2 + X2tx
 x^2X2 - X3x^2
 tx^2X2 + X1tx^2

In [145]:
relsOmegaCase2 := RelationsGivenByNicholsSmashkG(gensA[3], Case2);;
PrintNPList(relsOmegaCase2);

 zX2 - X1z
 ztX2 + X0zt
 xyX2 - X2xy
 txzX2 + X1txz
 xyxX2 - X0xyx
 tx^2yX2 + X2tx^2y

In [147]:
relsOmegaCase3 := RelationsGivenByNicholsSmashkG(gensA[3], Case3);;
PrintNPList(relsOmegaCase3);

 yX2 - X3y
 tzX2 + X2tz
 yxX2 - X0yx
 txyX2 + X3txy
 x^2zX2 - X2x^2z
 tx^2yzX2 + X0tx^2yz

In [149]:
relsOmegaCase4 := RelationsGivenByNicholsSmashkG(gensA[3], Case4);;
PrintNPList(relsOmegaCase4);

 yzX2 - X0yz
 tyX2 + X1ty
 xzX2 - X3xz
 tyxX2 + X0tyx
 x^2yX2 - X1x^2y
 tx^2zX2 + X3tx^2z

In [151]:
relsOmega2Case1 := RelationsGivenByNicholsSmashkG(gensA[4], Case1);;
PrintNPList(relsOmega2Case1);

 X3 - X3
 tX3 + X1t
 xX3 - X2x
 txX3 + X3tx
 x^2X3 - X1x^2
 tx^2X3 + X2tx^2

In [153]:
relsOmega2Case2 := RelationsGivenByNicholsSmashkG(gensA[4], Case2);;
PrintNPList(relsOmega2Case2);

 zX3 - X0z
 ztX3 + X2zt
 xyX3 - X1xy
 txzX3 + X0txz
 xyxX3 - X2xyx
 tx^2yX3 + X1tx^2y

In [153]:
relsOmega2Case3 := RelationsGivenByNicholsSmashkG(gensA[4], Case3);;
PrintNPList(relsOmega2Case3);

 yX3 - X2y
 tzX3 + X0tz
 yxX3 - X3yx
 txyX3 + X2txy
 x^2zX3 - X0x^2z
 tx^2yzX3 + X3tx^2yz

In [157]:
relsOmega2Case4 := RelationsGivenByNicholsSmashkG(gensA[4], Case4);;
PrintNPList(relsOmega2Case4);

 yzX3 - X1yz
 tyX3 + X3ty
 xzX3 - X0xz
 tyxX3 + X1tyx
 x^2yX3 - X3x^2y
 tx^2zX3 + X0tx^2z

In [158]:
relsxBos:=Concatenation(
    rels0Case1,
    rels0Case2,
    rels0Case3,
    rels0Case4,
    rels1Case1,
    rels1Case2,
    rels1Case3,
    rels1Case4,
    relsOmegaCase1,
    relsOmegaCase2,
    relsOmegaCase3,
    relsOmegaCase4,
    relsOmega2Case1,
    relsOmega2Case2,
    relsOmega2Case3,
    relsOmega2Case4
);;

In [160]:
# Test the first relation
Print("Total relations generated: ", Length(relsxBos), ".\n");
PrintNPList(relsxBos);

Total relations generated: 96.
 X0 - X0
 tX0 + X0t
 xX0 - X0x
 txX0 + X0tx
 x^2X0 - X0x^2
 tx^2X0 + X0tx^2
 zX0 - X3z
 ztX0 + X3zt
 xyX0 - X3xy
 txzX0 + X3txz
 xyxX0 - X3xyx
 tx^2yX0 + X3tx^2y
 yX0 - X1y
 tzX0 + X1tz
 yxX0 - X1yx
 txyX0 + X1txy
 x^2zX0 - X1x^2z
 tx^2yzX0 + X1tx^2yz
 yzX0 - X2yz
 tyX0 + X2ty
 xzX0 - X2xz
 tyxX0 + X2tyx
 x^2yX0 - X2x^2y
 tx^2zX0 + X2tx^2z
 X1 - X1
 tX1 + X2t
 xX1 - X3x
 txX1 + X1tx
 x^2X1 - X2x^2
 tx^2X1 + X3tx^2
 zX1 - X2z
 ztX1 + X1zt
 xyX1 - X0xy
 txzX1 + X2txz
 xyxX1 - X1xyx
 tx^2yX1 + X0tx^2y
 yX1 - X0y
 tzX1 + X3tz
 yxX1 - X2yx
 txyX1 + X0txy
 x^2zX1 - X3x^2z
 tx^2yzX1 + X2tx^2yz
 yzX1 - X3yz
 tyX1 + X0ty
 xzX1 - X1xz
 tyxX1 + X3tyx
 x^2yX1 - X0x^2y
 tx^2zX1 + X1tx^2z
 X2 - X2
 tX2 + X3t
 xX2 - X1x
 txX2 + X2tx
 x^2X2 - X3x^2
 tx^2X2 + X1tx^2
 zX2 - X1z
 ztX2 + X0zt
 xyX2 - X2xy
 txzX2 + X1txz
 xyxX2 - X0xyx
 tx^2yX2 + X2tx^2y
 yX2 - X3y
 tzX2 + X2tz
 yxX2 - X0yx
 txyX2 + X3txy
 x^2zX2 - X2x^2z
 tx^2yzX2 + X0tx^2yz
 yzX2 - X0yz
 tyX2 + X1ty
 xzX2 - X3xz
 tyxX2 + X0tyx
 x^2yX2 - X1x^2y
 tx^2zX2 + X3tx^2z
 X3 - X3
 tX3 + X1t
 xX3 - X2x
 txX3 + X3tx
 x^2X3 - X1x^2
 tx^2X3 + X2tx^2
 zX3 - X0z
 ztX3 + X2zt
 xyX3 - X1xy
 txzX3 + X0txz
 xyxX3 - X2xyx
 tx^2yX3 + X1tx^2y
 yX3 - X2y
 tzX3 + X0tz
 yxX3 - X3yx
 txyX3 + X2txy
 x^2zX3 - X0x^2z
 tx^2yzX3 + X3tx^2yz
 yzX3 - X1yz
 tyX3 + X3ty
 xzX3 - X0xz
 tyxX3 + X1tyx
 x^2yX3 - X3x^2y
 tx^2zX3 + X0tx^2z

In [161]:
J := SGrobner(Concatenation(
    relsT4,
    relsxBos,
    relsGroup,
    gensDeltas,
    gensY
    )
);;

In [162]:
DimQA(J, 36);

1728

In [163]:
72*24;

1728

# El algebra $\mathfrak{B}(\overline{V})\#\Bbbk G$
## Relaciones $y_{j}(b, t^s) = (-1)^s(b,t^s) y_{g^{-1}\cdot j}$, evaluadas para todos los $(b,t^s) \in G$

### En términos de $y_{j}$ para todo $(b,t^s) \in G$


- Caso $j = 0$ entonces $i=\omega^2 b + \omega^s j=\omega^2b$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=0$. Entonces, $(0,t^s)X_{0}=(-1)^sX_0(0,t^s)$

\begin{aligned}
(0, t^0)\,x_{0} &= x_{0}\,(0, t^0), \\[4pt]
(0, t^1)\,x_{0} &= -\,x_{0}\,(0, t^1), \\[4pt]
(0, t^2)\,x_{0} &= x_{0}\,(0, t^2), \\[4pt]
(0, t^3)\,x_{0} &= -x_{0}\,(0, t^3), \\[4pt]
(0, t^4)\,x_{0} &= \,x_{0}\,(0, t^4), \\[4pt]
(0, t^5)\,x_{0} &= -\,x_{0}\,(0, t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2$. Entonces, $(1,t^s)X_{0}=(-1)^sX_{\omega^2}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{0} &= x_{\omega^2}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{0} &= -\,x_{\omega^2}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{0} &= x_{\omega^2}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{0} &= -\,x_{\omega^2}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{0} &= x_{\omega^2}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{0} &= -\,x_{\omega^2}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1$. Entonces, $(\omega,t^s)X_{0}=(-1)^sX_{1}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{0} &= x_{1}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{0} &= -\,x_{1}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{0} &= x_{1}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{0} &= -\,x_{1}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{0} &= x_{1}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{0} &= -\,x_{1}\,(\omega,t^5).
\end{aligned}


4. si $h=(\omega^2, t^s)$ entonces $i=\omega$. Entonces, $(\omega^2,t^s)X_{0}=(-1)^sX_{\omega}(\omega^2,t^s)$


\begin{aligned}
(\omega^2,t^0)\,x_{0} &= x_{\omega}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{0} &= x_{\omega}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{0} &= x_{\omega}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^5).
\end{aligned}

In [165]:
rels0Case1:=RelationsGivenByNicholsDualSmashkG(gensA[1], Case1);;
PrintNPList(rels0Case1);

 Y0 - Y0
 Y0t + tY0
 Y0x - xY0
 Y0tx + txY0
 Y0x^2 - x^2Y0
 Y0tx^2 + tx^2Y0

In [167]:
rels0Case2:=RelationsGivenByNicholsDualSmashkG(gensA[1], Case2);;
PrintNPList(rels0Case2);

 Y0z - zY3
 Y0zt + ztY2
 Y0xy - xyY1
 Y0txz + txzY3
 Y0xyx - xyxY2
 Y0tx^2y + tx^2yY1

In [169]:
rels0Case3:=RelationsGivenByNicholsDualSmashkG(gensA[1], Case3);;
PrintNPList(rels0Case3);

 Y0y - yY1
 Y0tz + tzY3
 Y0yx - yxY2
 Y0txy + txyY1
 Y0x^2z - x^2zY3
 Y0tx^2yz + tx^2yzY2

In [171]:
rels0Case4:=RelationsGivenByNicholsDualSmashkG(gensA[1], Case4);;
PrintNPList(rels0Case4);

 Y0yz - yzY2
 Y0ty + tyY1
 Y0xz - xzY3
 Y0tyx + tyxY2
 Y0x^2y - x^2yY1
 Y0tx^2z + tx^2zY3

In [173]:
rels1Case1:=RelationsGivenByNicholsDualSmashkG(gensA[2], Case1);;
PrintNPList(rels1Case1);

 Y1 - Y1
 Y1t + tY3
 Y1x - xY2
 Y1tx + txY1
 Y1x^2 - x^2Y3
 Y1tx^2 + tx^2Y2

In [173]:
rels1Case2:=RelationsGivenByNicholsDualSmashkG(gensA[2], Case2);;
PrintNPList(rels1Case2);

 Y1z - zY2
 Y1zt + ztY1
 Y1xy - xyY3
 Y1txz + txzY2
 Y1xyx - xyxY1
 Y1tx^2y + tx^2yY3

In [177]:
rels1Case3:=RelationsGivenByNicholsDualSmashkG(gensA[2], Case3);;
PrintNPList(rels1Case3);

 Y1y - yY0
 Y1tz + tzY0
 Y1yx - yxY0
 Y1txy + txyY0
 Y1x^2z - x^2zY0
 Y1tx^2yz + tx^2yzY0

In [179]:
rels1Case4:=RelationsGivenByNicholsDualSmashkG(gensA[2], Case4);;
PrintNPList(rels1Case4);

 Y1yz - yzY3
 Y1ty + tyY2
 Y1xz - xzY1
 Y1tyx + tyxY3
 Y1x^2y - x^2yY2
 Y1tx^2z + tx^2zY1

In [179]:
relsOmegaCase1:=RelationsGivenByNicholsDualSmashkG(gensA[3], Case1);;
PrintNPList(relsOmegaCase1);

 Y2 - Y2
 Y2t + tY1
 Y2x - xY3
 Y2tx + txY2
 Y2x^2 - x^2Y1
 Y2tx^2 + tx^2Y3

In [183]:
relsOmegaCase2:=RelationsGivenByNicholsDualSmashkG(gensA[3], Case2);;
PrintNPList(relsOmegaCase2);

 Y2z - zY1
 Y2zt + ztY3
 Y2xy - xyY2
 Y2txz + txzY1
 Y2xyx - xyxY3
 Y2tx^2y + tx^2yY2

In [185]:
relsOmegaCase3:=RelationsGivenByNicholsDualSmashkG(gensA[3], Case3);;
PrintNPList(relsOmegaCase3);

 Y2y - yY3
 Y2tz + tzY2
 Y2yx - yxY1
 Y2txy + txyY3
 Y2x^2z - x^2zY2
 Y2tx^2yz + tx^2yzY1

In [187]:
relsOmegaCase4:=RelationsGivenByNicholsDualSmashkG(gensA[3], Case4);;
PrintNPList(relsOmegaCase4);

 Y2yz - yzY0
 Y2ty + tyY0
 Y2xz - xzY0
 Y2tyx + tyxY0
 Y2x^2y - x^2yY0
 Y2tx^2z + tx^2zY0

In [189]:
relsOmega2Case1:=RelationsGivenByNicholsDualSmashkG(gensA[4], Case1);;
PrintNPList(relsOmega2Case1);

 Y3 - Y3
 Y3t + tY2
 Y3x - xY1
 Y3tx + txY3
 Y3x^2 - x^2Y2
 Y3tx^2 + tx^2Y1

In [191]:
relsOmega2Case2:=RelationsGivenByNicholsDualSmashkG(gensA[4], Case2);;
PrintNPList(relsOmega2Case2);

 Y3z - zY0
 Y3zt + ztY0
 Y3xy - xyY0
 Y3txz + txzY0
 Y3xyx - xyxY0
 Y3tx^2y + tx^2yY0

In [193]:
relsOmega2Case3:=RelationsGivenByNicholsDualSmashkG(gensA[4], Case3);;
PrintNPList(relsOmega2Case3);

 Y3y - yY2
 Y3tz + tzY1
 Y3yx - yxY3
 Y3txy + txyY2
 Y3x^2z - x^2zY1
 Y3tx^2yz + tx^2yzY3

In [195]:
relsOmega2Case4:=RelationsGivenByNicholsDualSmashkG(gensA[4], Case4);;
PrintNPList(relsOmega2Case4);

 Y3yz - yzY1
 Y3ty + tyY3
 Y3xz - xzY2
 Y3tyx + tyxY1
 Y3x^2y - x^2yY3
 Y3tx^2z + tx^2zY2

In [196]:
relsyBos := Concatenation(
    rels0Case1,
    rels0Case2,
    rels0Case3,
    rels0Case4,
    rels1Case1,
    rels1Case2,
    rels1Case3,
    rels1Case4,
    relsOmegaCase1,
    relsOmegaCase2,
    relsOmegaCase3,
    relsOmegaCase4,
    relsOmega2Case1,
    relsOmega2Case2,
    relsOmega2Case3,
    relsOmega2Case4
);;

In [198]:
# Test the first relation # The algebra $\mathfrak{B}(V)\#\Bbbk^G$
Print("Total relations generated: ", Length(relsyBos), ".\n");
PrintNPList(relsyBos);

Total relations generated: 96.
 Y0 - Y0
 Y0t + tY0
 Y0x - xY0
 Y0tx + txY0
 Y0x^2 - x^2Y0
 Y0tx^2 + tx^2Y0
 Y0z - zY3
 Y0zt + ztY2
 Y0xy - xyY1
 Y0txz + txzY3
 Y0xyx - xyxY2
 Y0tx^2y + tx^2yY1
 Y0y - yY1
 Y0tz + tzY3
 Y0yx - yxY2
 Y0txy + txyY1
 Y0x^2z - x^2zY3
 Y0tx^2yz + tx^2yzY2
 Y0yz - yzY2
 Y0ty + tyY1
 Y0xz - xzY3
 Y0tyx + tyxY2
 Y0x^2y - x^2yY1
 Y0tx^2z + tx^2zY3
 Y1 - Y1
 Y1t + tY3
 Y1x - xY2
 Y1tx + txY1
 Y1x^2 - x^2Y3
 Y1tx^2 + tx^2Y2
 Y1z - zY2
 Y1zt + ztY1
 Y1xy - xyY3
 Y1txz + txzY2
 Y1xyx - xyxY1
 Y1tx^2y + tx^2yY3
 Y1y - yY0
 Y1tz + tzY0
 Y1yx - yxY0
 Y1txy + txyY0
 Y1x^2z - x^2zY0
 Y1tx^2yz + tx^2yzY0
 Y1yz - yzY3
 Y1ty + tyY2
 Y1xz - xzY1
 Y1tyx + tyxY3
 Y1x^2y - x^2yY2
 Y1tx^2z + tx^2zY1
 Y2 - Y2
 Y2t + tY1
 Y2x - xY3
 Y2tx + txY2
 Y2x^2 - x^2Y1
 Y2tx^2 + tx^2Y3
 Y2z - zY1
 Y2zt + ztY3
 Y2xy - xyY2
 Y2txz + txzY1
 Y2xyx - xyxY3
 Y2tx^2y + tx^2yY2
 Y2y - yY3
 Y2tz + tzY2
 Y2yx - yxY1
 Y2txy + txyY3
 Y2x^2z - x^2zY2
 Y2tx^2yz + tx^2yzY1
 Y2yz - yzY0
 Y2ty + tyY0
 Y2xz - xzY0
 Y2tyx + tyxY0
 Y2x^2y - x^2yY0
 Y2tx^2z + tx^2zY0
 Y3 - Y3
 Y3t + tY2
 Y3x - xY1
 Y3tx + txY3
 Y3x^2 - x^2Y2
 Y3tx^2 + tx^2Y1
 Y3z - zY0
 Y3zt + ztY0
 Y3xy - xyY0
 Y3txz + txzY0
 Y3xyx - xyxY0
 Y3tx^2y + tx^2yY0
 Y3y - yY2
 Y3tz + tzY1
 Y3yx - yxY3
 Y3txy + txyY2
 Y3x^2z - x^2zY1
 Y3tx^2yz + tx^2yzY3
 Y3yz - yzY1
 Y3ty + tyY3
 Y3xz - xzY2
 Y3tyx + tyxY1
 Y3x^2y - x^2yY3
 Y3tx^2z + tx^2zY2

In [199]:
I := Concatenation(
    gensX,
    gensDeltas,
    relsGroup,    # 7 rels
    relsyBos,     # 96 rels
    relsT4dual    # 9 rels
);;

In [200]:
J := SGrobner(I);;

In [201]:
DimQA(J, 36);

1728

In [202]:
72*24;

1728

# El algebra $\mathfrak{B}(V)\#\Bbbk^G$
## Relaciones $\delta_{(b, t^s)} x_{j} = x_{j}\delta_{g_{j}^{-1}(b,t^s)}$, evaluadas para todos los $(b,t^s) \in G, j\in \mathbb{F}_4$

### En términos de $x_{j}$ para todo $(b,t^s) \in G$


- Caso $j = 0$ entonces $i=\omega^2 b + \omega^s j=\omega^2b$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=0$. Entonces, $(0,t^s)X_{0}=(-1)^sX_0(0,t^s)$

\begin{aligned}
(0, t^0)\,x_{0} &= x_{0}\,(0, t^0), \\[4pt]
(0, t^1)\,x_{0} &= -\,x_{0}\,(0, t^1), \\[4pt]
(0, t^2)\,x_{0} &= x_{0}\,(0, t^2), \\[4pt]
(0, t^3)\,x_{0} &= -x_{0}\,(0, t^3), \\[4pt]
(0, t^4)\,x_{0} &= \,x_{0}\,(0, t^4), \\[4pt]
(0, t^5)\,x_{0} &= -\,x_{0}\,(0, t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2$. Entonces, $(1,t^s)X_{0}=(-1)^sX_{\omega^2}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{0} &= x_{\omega^2}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{0} &= -\,x_{\omega^2}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{0} &= x_{\omega^2}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{0} &= -\,x_{\omega^2}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{0} &= x_{\omega^2}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{0} &= -\,x_{\omega^2}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1$. Entonces, $(\omega,t^s)X_{0}=(-1)^sX_{1}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{0} &= x_{1}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{0} &= -\,x_{1}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{0} &= x_{1}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{0} &= -\,x_{1}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{0} &= x_{1}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{0} &= -\,x_{1}\,(\omega,t^5).
\end{aligned}


4. si $h=(\omega^2, t^s)$ entonces $i=\omega$. Entonces, $(\omega^2,t^s)X_{0}=(-1)^sX_{\omega}(\omega^2,t^s)$


\begin{aligned}
(\omega^2,t^0)\,x_{0} &= x_{\omega}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{0} &= x_{\omega}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{0} &= x_{\omega}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{0} &= -\,x_{\omega}\,(\omega^2,t^5).
\end{aligned}

- Caso $j = 1$ entonces $i=\omega^2 b + \omega^s j\omega^2 b + \omega^s$, con $s=\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=\omega^s$. Entonces, $(0,t^s)X_{1}=(-1)^sX_{\omega^s}(0,t^s)$

\begin{aligned}
(0, t^0)\,x_{1} &= x_{1}\,(0, t^0), \\[4pt]
(0, t^1)\,x_{1} &= -\,x_{\omega}\,(0, t^1), \\[4pt]
(0, t^2)\,x_{1} &= x_{\omega^2}\,(0, t^2), \\[4pt]
(0, t^3)\,x_{1} &= -x_{1}\,(0, t^3), \\[4pt]
(0, t^4)\,x_{1} &= \,x_{\omega}\,(0, t^4), \\[4pt]
(0, t^5)\,x_{1} &= -\,x_{\omega^2}\,(0, t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2+\omega^s$. Entonces, $(1,t^s)X_{1}=(-1)^sX_{\omega^2+\omega^s}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{1} &= x_{\omega^2 + 1}\,(1,t^0) = x_{\omega}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{1} &= -\,x_{\omega^2 + \omega}\,(1,t^1) = -\,x_{1}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{1} &= x_{\omega^2 + \omega^2}\,(1,t^2) = x_{0}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{1} &= -\,x_{\omega^2 + 1}\,(1,t^3) = -\,x_{\omega}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{1} &= x_{\omega^2 + \omega}\,(1,t^4) = x_{1}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{1} &= -\,x_{\omega^2 + \omega^2}\,(1,t^5) = -\,x_{0}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1+\omega^s$. Entonces, $(\omega,t^s)X_{1}=(-1)^sX_{1+\omega^s}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{1} &= x_{1 + 1}\,(\omega,t^0) = x_{0}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{1} &= -\,x_{1 + \omega}\,(\omega,t^1) = -\,x_{\omega^2}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{1} &= x_{1 + \omega^2}\,(\omega,t^2) = x_{\omega}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{1} &= -\,x_{1 + 1}\,(\omega,t^3) = -\,x_{0}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{1} &= x_{1 + \omega}\,(\omega,t^4) = x_{\omega^2}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{1} &= -\,x_{1 + \omega^2}\,(\omega,t^5) = -\,x_{\omega}\,(\omega,t^5).
\end{aligned}

4. si $h=(\omega^2, t^s)$ entonces $i=\omega+\omega^s$. Entonces, $(\omega^2,t^s)X_{1}=(-1)^sX_{\omega+\omega^s}(\omega^2,t^s)$

\begin{aligned}
(\omega^2,t^0)\,x_{1} &= x_{\omega + 1}\,(\omega^2,t^0) = x_{\omega^2}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{1} &= -\,x_{\omega + \omega}\,(\omega^2,t^1) = -\,x_{0}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{1} &= x_{\omega + \omega^2}\,(\omega^2,t^2) = x_{1}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{1} &= -\,x_{\omega + 1}\,(\omega^2,t^3) = -\,x_{\omega^2}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{1} &= x_{\omega + \omega}\,(\omega^2,t^4) = x_{0}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{1} &= -\,x_{\omega + \omega^2}\,(\omega^2,t^5) = -\,x_{1}\,(\omega^2,t^5).
\end{aligned}

- Caso $j = \omega$ entonces $i=\omega^2 b + \omega^{s+1} j=\omega^2 b+ \omega^{s+1}$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=\omega^{s+1}$. Entonces, $(0,t^s)X_{0}=(-1)^sX_{\omega^{s+1}}(0,t^s)$

\begin{aligned}
(0,t^0)\,x_{\omega} &= x_{\omega}\,(0,t^0), \\[4pt]
(0,t^1)\,x_{\omega} &= -\,x_{\omega^2}\,(0,t^1), \\[4pt]
(0,t^2)\,x_{\omega} &= x_{1}\,(0,t^2), \\[4pt]
(0,t^3)\,x_{\omega} &= -\,x_{\omega}\,(0,t^3), \\[4pt]
(0,t^4)\,x_{\omega} &= x_{\omega^2}\,(0,t^4), \\[4pt]
(0,t^5)\,x_{\omega} &= -\,x_{1}\,(0,t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2+\omega^{s+1}$. Entonces, $(1,t^s)X_{\omega}=(-1)^sX_{\omega^2+\omega^{s+1}}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{\omega} &= x_{\omega^2 + \omega}\,(1,t^0) = x_{1}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{\omega} &= -\,x_{\omega^2 + \omega^2}\,(1,t^1) = -\,x_{0}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{\omega} &= x_{\omega^2 + 1}\,(1,t^2) = x_{\omega}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{\omega} &= -\,x_{\omega^2 + \omega}\,(1,t^3) = -\,x_{1}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{\omega} &= x_{\omega^2 + \omega^2}\,(1,t^4) = x_{0}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{\omega} &= -\,x_{\omega^2 + 1}\,(1,t^5) = -\,x_{\omega}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1+\omega^{s+1}$. Entonces, $(\omega,t^s)X_{\omega}=(-1)^sX_{1+\omega^{s+1}}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{\omega} &= x_{1 + \omega}\,(\omega,t^0) = x_{\omega^2}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{\omega} &= -\,x_{1 + \omega^2}\,(\omega,t^1) = -\,x_{\omega}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{\omega} &= x_{1 + 1}\,(\omega,t^2) = x_{0}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{\omega} &= -\,x_{1 + \omega}\,(\omega,t^3) = -\,x_{\omega^2}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{\omega} &= x_{1 + \omega^2}\,(\omega,t^4) = x_{\omega}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{\omega} &= -\,x_{1 + 1}\,(\omega,t^5) = -\,x_{0}\,(\omega,t^5).
\end{aligned}

4. si $h=(\omega^2, t^s)$ entonces $i=\omega+\omega^{s+1}$. Entonces, $(\omega^2,t^s)X_{\omega}=(-1)^sX_{\omega+\omega^{s+1}}(\omega^2,t^s)$

\begin{aligned}
(\omega^2,t^0)\,x_{\omega} &= x_{\omega + \omega}\,(\omega^2,t^0) = x_{0}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{\omega} &= -\,x_{\omega + \omega^2}\,(\omega^2,t^1) = -\,x_{1}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{\omega} &= x_{\omega + 1}\,(\omega^2,t^2) = x_{\omega^2}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{\omega} &= -\,x_{\omega + \omega}\,(\omega^2,t^3) = -\,x_{0}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{\omega} &= x_{\omega + \omega^2}\,(\omega^2,t^4) = x_{1}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{\omega} &= -\,x_{\omega + 1}\,(\omega^2,t^5) = -\,x_{\omega^2}\,(\omega^2,t^5).
\end{aligned}

- Caso $j = \omega^2$ entonces $i=\omega^2 b + \omega^{s+2} j=\omega^2 b+ \omega^{s+2}$, con $s\in\{0,1,\dots, 5\}$:


1. si $h=(0, t^s)$ entonces $i=\omega^{s+2}$. Entonces, $(0,t^s)X_{\omega^2}=(-1)^sX_{\omega^{s+2}}(0,t^s)$

\begin{aligned}
(0,t^0)\,x_{\omega^2} &= x_{\omega^2}\,(0,t^0), \\[4pt]
(0,t^1)\,x_{\omega^2} &= -\,x_{1}\,(0,t^1), \\[4pt]
(0,t^2)\,x_{\omega^2} &= x_{\omega}\,(0,t^2), \\[4pt]
(0,t^3)\,x_{\omega^2} &= -\,x_{\omega^2}\,(0,t^3), \\[4pt]
(0,t^4)\,x_{\omega^2} &= x_{1}\,(0,t^4), \\[4pt]
(0,t^5)\,x_{\omega^2} &= -\,x_{\omega}\,(0,t^5).
\end{aligned}

2. si $h=(1, t^s)$ entonces $i=\omega^2+\omega^{s+2}$. Entonces, $(1,t^s)X_{\omega^2}=(-1)^sX_{\omega^2+\omega^{s+2}}(0,t^s)$

\begin{aligned}
(1,t^0)\,x_{\omega^2} &= x_{\omega^2 + \omega^2}\,(1,t^0) = x_{0}\,(1,t^0), \\[4pt]
(1,t^1)\,x_{\omega^2} &= -\,x_{\omega^2 + 1}\,(1,t^1) = -\,x_{\omega}\,(1,t^1), \\[4pt]
(1,t^2)\,x_{\omega^2} &= x_{\omega^2 + \omega}\,(1,t^2) = x_{1}\,(1,t^2), \\[4pt]
(1,t^3)\,x_{\omega^2} &= -\,x_{\omega^2 + \omega^2}\,(1,t^3) = -\,x_{0}\,(1,t^3), \\[4pt]
(1,t^4)\,x_{\omega^2} &= x_{\omega^2 + 1}\,(1,t^4) = x_{\omega}\,(1,t^4), \\[4pt]
(1,t^5)\,x_{\omega^2} &= -\,x_{\omega^2 + \omega}\,(1,t^5) = -\,x_{1}\,(1,t^5).
\end{aligned}


3. si $h=(\omega, t^s)$ entonces $i=1+\omega^{s+2}$. Entonces, $(\omega,t^s)X_{\omega^2}=(-1)^sX_{1+\omega^{s+2}}(\omega,t^s)$

\begin{aligned}
(\omega,t^0)\,x_{\omega^2} &= x_{1 + \omega^2}\,(\omega,t^0) = x_{\omega}\,(\omega,t^0), \\[4pt]
(\omega,t^1)\,x_{\omega^2} &= -\,x_{1 + 1}\,(\omega,t^1) = -\,x_{0}\,(\omega,t^1), \\[4pt]
(\omega,t^2)\,x_{\omega^2} &= x_{1 + \omega}\,(\omega,t^2) = x_{\omega^2}\,(\omega,t^2), \\[4pt]
(\omega,t^3)\,x_{\omega^2} &= -\,x_{1 + \omega^2}\,(\omega,t^3) = -\,x_{\omega}\,(\omega,t^3), \\[4pt]
(\omega,t^4)\,x_{\omega^2} &= x_{1 + 1}\,(\omega,t^4) = x_{0}\,(\omega,t^4), \\[4pt]
(\omega,t^5)\,x_{\omega^2} &= -\,x_{1 + \omega}\,(\omega,t^5) = -\,x_{\omega^2}\,(\omega,t^5).
\end{aligned}

4. si $h=(\omega^2, t^s)$ entonces $i=\omega+\omega^{s+2}$. Entonces, $(\omega^2,t^s)X_{\omega^2}=(-1)^sX_{\omega+\omega^{s+2}}(\omega^2,t^s)$

\begin{aligned}
(\omega^2,t^0)\,x_{\omega^2} &= x_{\omega + \omega^2}\,(\omega^2,t^0) = x_{1}\,(\omega^2,t^0), \\[4pt]
(\omega^2,t^1)\,x_{\omega^2} &= -\,x_{\omega + 1}\,(\omega^2,t^1) = -\,x_{\omega^2}\,(\omega^2,t^1), \\[4pt]
(\omega^2,t^2)\,x_{\omega^2} &= x_{\omega + \omega}\,(\omega^2,t^2) = x_{0}\,(\omega^2,t^2), \\[4pt]
(\omega^2,t^3)\,x_{\omega^2} &= -\,x_{\omega + \omega^2}\,(\omega^2,t^3) = -\,x_{1}\,(\omega^2,t^3), \\[4pt]
(\omega^2,t^4)\,x_{\omega^2} &= x_{\omega + 1}\,(\omega^2,t^4) = x_{\omega^2}\,(\omega^2,t^4), \\[4pt]
(\omega^2,t^5)\,x_{\omega^2} &= -\,x_{\omega + \omega}\,(\omega^2,t^5) = -\,x_{0}\,(\omega^2,t^5).
\end{aligned}

In [204]:
rels0Case1:=RelationsGivenByNicholsSmashkGDual(gensA[1], Case1);;
PrintNPList(rels0Case1);

 DeX0 - X0D_(0,5)
 D_(0,1)X0 - X0De
 D_(0,2)X0 - X0D_(0,1)
 D_(0,3)X0 - X0D_(0,2)
 D_(0,4)X0 - X0D_(0,3)
 D_(0,5)X0 - X0D_(0,4)

In [206]:
rels0Case2:=RelationsGivenByNicholsSmashkGDual(gensA[1], Case2);;
PrintNPList(rels0Case2);

 D_(1,0)X0 - X0D_(w^2,5)
 D_(1,1)X0 - X0D_(w^2,0)
 D_(1,2)X0 - X0D_(w^2,1)
 D_(1,3)X0 - X0D_(w^2,2)
 D_(1,4)X0 - X0D_(w^2,3)
 D_(1,5)X0 - X0D_(w^2,4)

In [208]:
rels0Case3:=RelationsGivenByNicholsSmashkGDual(gensA[1], Case3);;
PrintNPList(rels0Case3);

 D_(w,0)X0 - X0D_(1,5)
 D_(w,1)X0 - X0D_(1,0)
 D_(w,2)X0 - X0D_(1,1)
 D_(w,3)X0 - X0D_(1,2)
 D_(w,4)X0 - X0D_(1,3)
 D_(w,5)X0 - X0D_(1,4)

In [210]:
rels0Case4:=RelationsGivenByNicholsSmashkGDual(gensA[1], Case4);;
PrintNPList(rels0Case4);

 D_(w^2,0)X0 - X0D_(w,5)
 D_(w^2,1)X0 - X0D_(w,0)
 D_(w^2,2)X0 - X0D_(w,1)
 D_(w^2,3)X0 - X0D_(w,2)
 D_(w^2,4)X0 - X0D_(w,3)
 D_(w^2,5)X0 - X0D_(w,4)

In [212]:
rels1Case1:=RelationsGivenByNicholsSmashkGDual(gensA[2], Case1);;
PrintNPList(rels1Case1);

 DeX1 - X1D_(w^2,5)
 D_(0,1)X1 - X1D_(w^2,0)
 D_(0,2)X1 - X1D_(w^2,1)
 D_(0,3)X1 - X1D_(w^2,2)
 D_(0,4)X1 - X1D_(w^2,3)
 D_(0,5)X1 - X1D_(w^2,4)

In [214]:
rels1Case2:=RelationsGivenByNicholsSmashkGDual(gensA[2], Case2);;
PrintNPList(rels1Case2);

 D_(1,0)X1 - X1D_(0,5)
 D_(1,1)X1 - X1De
 D_(1,2)X1 - X1D_(0,1)
 D_(1,3)X1 - X1D_(0,2)
 D_(1,4)X1 - X1D_(0,3)
 D_(1,5)X1 - X1D_(0,4)

In [216]:
rels1Case3:=RelationsGivenByNicholsSmashkGDual(gensA[2], Case3);;
PrintNPList(rels1Case3);

 D_(w,0)X1 - X1D_(w,5)
 D_(w,1)X1 - X1D_(w,0)
 D_(w,2)X1 - X1D_(w,1)
 D_(w,3)X1 - X1D_(w,2)
 D_(w,4)X1 - X1D_(w,3)
 D_(w,5)X1 - X1D_(w,4)

In [218]:
rels1Case4:=RelationsGivenByNicholsSmashkGDual(gensA[2], Case4);;
PrintNPList(rels1Case4);

 D_(w^2,0)X1 - X1D_(1,5)
 D_(w^2,1)X1 - X1D_(1,0)
 D_(w^2,2)X1 - X1D_(1,1)
 D_(w^2,3)X1 - X1D_(1,2)
 D_(w^2,4)X1 - X1D_(1,3)
 D_(w^2,5)X1 - X1D_(1,4)

In [220]:
relsOmegaCase1:=RelationsGivenByNicholsSmashkGDual(gensA[3], Case1);;
PrintNPList(relsOmegaCase1);

 DeX2 - X2D_(1,5)
 D_(0,1)X2 - X2D_(1,0)
 D_(0,2)X2 - X2D_(1,1)
 D_(0,3)X2 - X2D_(1,2)
 D_(0,4)X2 - X2D_(1,3)
 D_(0,5)X2 - X2D_(1,4)

In [222]:
relsOmegaCase2:=RelationsGivenByNicholsSmashkGDual(gensA[3], Case2);;
PrintNPList(relsOmegaCase2);

 D_(1,0)X2 - X2D_(w,5)
 D_(1,1)X2 - X2D_(w,0)
 D_(1,2)X2 - X2D_(w,1)
 D_(1,3)X2 - X2D_(w,2)
 D_(1,4)X2 - X2D_(w,3)
 D_(1,5)X2 - X2D_(w,4)

In [224]:
relsOmegaCase3:=RelationsGivenByNicholsSmashkGDual(gensA[3], Case3);;
PrintNPList(relsOmegaCase3);

 D_(w,0)X2 - X2D_(0,5)
 D_(w,1)X2 - X2De
 D_(w,2)X2 - X2D_(0,1)
 D_(w,3)X2 - X2D_(0,2)
 D_(w,4)X2 - X2D_(0,3)
 D_(w,5)X2 - X2D_(0,4)

In [224]:
relsOmegaCase4:=RelationsGivenByNicholsSmashkGDual(gensA[3], Case4);;
PrintNPList(relsOmegaCase4);

 D_(w^2,0)X2 - X2D_(w^2,5)
 D_(w^2,1)X2 - X2D_(w^2,0)
 D_(w^2,2)X2 - X2D_(w^2,1)
 D_(w^2,3)X2 - X2D_(w^2,2)
 D_(w^2,4)X2 - X2D_(w^2,3)
 D_(w^2,5)X2 - X2D_(w^2,4)

In [228]:
relsOmega2Case1:=RelationsGivenByNicholsSmashkGDual(gensA[4], Case1);;
PrintNPList(relsOmegaCase1);

 DeX2 - X2D_(1,5)
 D_(0,1)X2 - X2D_(1,0)
 D_(0,2)X2 - X2D_(1,1)
 D_(0,3)X2 - X2D_(1,2)
 D_(0,4)X2 - X2D_(1,3)
 D_(0,5)X2 - X2D_(1,4)

In [230]:
relsOmega2Case2:=RelationsGivenByNicholsSmashkGDual(gensA[4], Case2);;
PrintNPList(relsOmegaCase2);

 D_(1,0)X2 - X2D_(w,5)
 D_(1,1)X2 - X2D_(w,0)
 D_(1,2)X2 - X2D_(w,1)
 D_(1,3)X2 - X2D_(w,2)
 D_(1,4)X2 - X2D_(w,3)
 D_(1,5)X2 - X2D_(w,4)

In [232]:
relsOmega2Case3:=RelationsGivenByNicholsSmashkGDual(gensA[4], Case3);;
PrintNPList(relsOmegaCase3);

 D_(w,0)X2 - X2D_(0,5)
 D_(w,1)X2 - X2De
 D_(w,2)X2 - X2D_(0,1)
 D_(w,3)X2 - X2D_(0,2)
 D_(w,4)X2 - X2D_(0,3)
 D_(w,5)X2 - X2D_(0,4)

In [234]:
relsOmega2Case4:=RelationsGivenByNicholsSmashkGDual(gensA[4], Case4);;
PrintNPList(relsOmegaCase4);

 D_(w^2,0)X2 - X2D_(w^2,5)
 D_(w^2,1)X2 - X2D_(w^2,0)
 D_(w^2,2)X2 - X2D_(w^2,1)
 D_(w^2,3)X2 - X2D_(w^2,2)
 D_(w^2,4)X2 - X2D_(w^2,3)
 D_(w^2,5)X2 - X2D_(w^2,4)

In [235]:
relsDx:=Concatenation(
    rels0Case1,
    rels0Case2,
    rels0Case3,
    rels0Case4,
    rels1Case1,
    rels1Case2,
    rels1Case3,
    rels1Case4,
    relsOmegaCase1,
    relsOmegaCase2,
    relsOmegaCase3,
    relsOmegaCase4,
    relsOmega2Case1,
    relsOmega2Case2,
    relsOmega2Case3,
    relsOmega2Case4
);;

In [237]:
# Test the first relation
Print("Total relations generated: ", Length(relsDx), ".\n");
PrintNPList(relsDx);

Total relations generated: 96.
 DeX0 - X0D_(0,5)
 D_(0,1)X0 - X0De
 D_(0,2)X0 - X0D_(0,1)
 D_(0,3)X0 - X0D_(0,2)
 D_(0,4)X0 - X0D_(0,3)
 D_(0,5)X0 - X0D_(0,4)
 D_(1,0)X0 - X0D_(w^2,5)
 D_(1,1)X0 - X0D_(w^2,0)
 D_(1,2)X0 - X0D_(w^2,1)
 D_(1,3)X0 - X0D_(w^2,2)
 D_(1,4)X0 - X0D_(w^2,3)
 D_(1,5)X0 - X0D_(w^2,4)
 D_(w,0)X0 - X0D_(1,5)
 D_(w,1)X0 - X0D_(1,0)
 D_(w,2)X0 - X0D_(1,1)
 D_(w,3)X0 - X0D_(1,2)
 D_(w,4)X0 - X0D_(1,3)
 D_(w,5)X0 - X0D_(1,4)
 D_(w^2,0)X0 - X0D_(w,5)
 D_(w^2,1)X0 - X0D_(w,0)
 D_(w^2,2)X0 - X0D_(w,1)
 D_(w^2,3)X0 - X0D_(w,2)
 D_(w^2,4)X0 - X0D_(w,3)
 D_(w^2,5)X0 - X0D_(w,4)
 DeX1 - X1D_(w^2,5)
 D_(0,1)X1 - X1D_(w^2,0)
 D_(0,2)X1 - X1D_(w^2,1)
 D_(0,3)X1 - X1D_(w^2,2)
 D_(0,4)X1 - X1D_(w^2,3)
 D_(0,5)X1 - X1D_(w^2,4)
 D_(1,0)X1 - X1D_(0,5)
 D_(1,1)X1 - X1De
 D_(1,2)X1 - X1D_(0,1)
 D_(1,3)X1 - X1D_(0,2)
 D_(1,4)X1 - X1D_(0,3)
 D_(1,5)X1 - X1D_(0,4)
 D_(w,0)X1 - X1D_(w,5)
 D_(w,1)X1 - X1D_(w,0)
 D_(w,2)X1 - X1D_(w,1)
 D_(w,3)X1 - X1D_(w,2)
 D_(w,4)X1 - X1D_(w,3)
 D_(w,5)X1 - X1D_(w,4)
 D_(w^2,0)X1 - X1D_(1,5)
 D_(w^2,1)X1 - X1D_(1,0)
 D_(w^2,2)X1 - X1D_(1,1)
 D_(w^2,3)X1 - X1D_(1,2)
 D_(w^2,4)X1 - X1D_(1,3)
 D_(w^2,5)X1 - X1D_(1,4)
 DeX2 - X2D_(1,5)
 D_(0,1)X2 - X2D_(1,0)
 D_(0,2)X2 - X2D_(1,1)
 D_(0,3)X2 - X2D_(1,2)
 D_(0,4)X2 - X2D_(1,3)
 D_(0,5)X2 - X2D_(1,4)
 D_(1,0)X2 - X2D_(w,5)
 D_(1,1)X2 - X2D_(w,0)
 D_(1,2)X2 - X2D_(w,1)
 D_(1,3)X2 - X2D_(w,2)
 D_(1,4)X2 - X2D_(w,3)
 D_(1,5)X2 - X2D_(w,4)
 D_(w,0)X2 - X2D_(0,5)
 D_(w,1)X2 - X2De
 D_(w,2)X2 - X2D_(0,1)
 D_(w,3)X2 - X2D_(0,2)
 D_(w,4)X2 - X2D_(0,3)
 D_(w,5)X2 - X2D_(0,4)
 D_(w^2,0)X2 - X2D_(w^2,5)
 D_(w^2,1)X2 - X2D_(w^2,0)
 D_(w^2,2)X2 - X2D_(w^2,1)
 D_(w^2,3)X2 - X2D_(w^2,2)
 D_(w^2,4)X2 - X2D_(w^2,3)
 D_(w^2,5)X2 - X2D_(w^2,4)
 DeX3 - X3D_(w,5)
 D_(0,1)X3 - X3D_(w,0)
 D_(0,2)X3 - X3D_(w,1)
 D_(0,3)X3 - X3D_(w,2)
 D_(0,4)X3 - X3D_(w,3)
 D_(0,5)X3 - X3D_(w,4)
 D_(1,0)X3 - X3D_(1,5)
 D_(1,1)X3 - X3D_(1,0)
 D_(1,2)X3 - X3D_(1,1)
 D_(1,3)X3 - X3D_(1,2)
 D_(1,4)X3 - X3D_(1,3)
 D_(1,5)X3 - X3D_(1,4)
 D_(w,0)X3 - X3D_(w^2,5)
 D_(w,1)X3 - X3D_(w^2,0)
 D_(w,2)X3 - X3D_(w^2,1)
 D_(w,3)X3 - X3D_(w^2,2)
 D_(w,4)X3 - X3D_(w^2,3)
 D_(w,5)X3 - X3D_(w^2,4)
 D_(w^2,0)X3 - X3D_(0,5)
 D_(w^2,1)X3 - X3De
 D_(w^2,2)X3 - X3D_(0,1)
 D_(w^2,3)X3 - X3D_(0,2)
 D_(w^2,4)X3 - X3D_(0,3)
 D_(w^2,5)X3 - X3D_(0,4)

In [238]:
J := SGrobner(Concatenation(
    relsT4,
    relskG,
    relsDx,
    gensG,
    gensY
    )
);;

In [239]:
DimQA(J, 36);

1728

In [240]:
72*24;

1728

# $\mathfrak{B}(\overline{V})\# \Bbbk^{G}$

### Generación automática de $\delta_g y_j = y_j \delta_{g_j g}$

Relaciones $\delta_{(b, t^s)} y_{j} = y_{j}\delta_{g_j (b,t^s)}$, evaluadas para todos los $(b,t^s) \in G, j\in \mathbb{F}_4$

### En términos de $y_{j}$ para todo $(b,t^s) \in G$

$$
g_jg=(j,1)*(b,t^s)=(j+\omega b, t^{s+1})
$$


- Caso $j = 0$ entonces $g_0 g=(0,1)*(b,t^s)=(\omega b, t^{s+1})$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $i=0$. Entonces, $\delta_{(0,t^s)}Y_{0}=Y_0\delta_{(0,t^{s+1})}$

\begin{aligned}
\delta_{(0, t^0)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^1)}, \\[4pt]
\delta_{(0, t^1)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^2)}, \\[4pt]
\delta_{(0, t^2)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^3)}, \\[4pt]
\delta_{(0, t^3)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^4)}, \\[4pt]
\delta_{(0, t^4)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^5)}, \\[4pt]
\delta_{(0, t^5)}\,Y_{0} &= Y_{0}\,\delta_{(0, t^0)}.
\end{aligned}

In [242]:
rels0Case1:=RelationsGivenByNicholsDualSmashkGDual(gensA[1], Case1);;
PrintNPList(rels0Case1);

 DeY0 - Y0D_(0,1)
 D_(0,1)Y0 - Y0D_(0,2)
 D_(0,2)Y0 - Y0D_(0,3)
 D_(0,3)Y0 - Y0D_(0,4)
 D_(0,4)Y0 - Y0D_(0,5)
 D_(0,5)Y0 - Y0De

2. si $h=(1, t^s)$ entonces $i=1$. Entonces, $\delta_{(1,t^s)}Y_{0}=Y_0\delta_{(\omega,t^{s+1})}$

\begin{aligned}
\delta_{(1, t^0)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^1)}, \\[4pt]
\delta_{(1, t^1)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^2)}, \\[4pt]
\delta_{(1, t^2)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^3)}, \\[4pt]
\delta_{(1, t^3)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^4)}, \\[4pt]
\delta_{(1, t^4)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^5)}, \\[4pt]
\delta_{(1, t^5)}\,Y_{0} &= Y_{0}\,\delta_{(\omega, t^0)}.
\end{aligned}

In [244]:
rels0Case2:=RelationsGivenByNicholsDualSmashkGDual(gensA[1], Case2);;
PrintNPList(rels0Case2);

 D_(1,0)Y0 - Y0D_(w,1)
 D_(1,1)Y0 - Y0D_(w,2)
 D_(1,2)Y0 - Y0D_(w,3)
 D_(1,3)Y0 - Y0D_(w,4)
 D_(1,4)Y0 - Y0D_(w,5)
 D_(1,5)Y0 - Y0D_(w,0)

3. si $h=(\omega, t^s)$ entonces $i=\omega$. Entonces, $\delta_{(\omega,t^s)}Y_{0}=Y_0\delta_{(\omega^2,t^{s+1})}$

\begin{aligned}
\delta_{(\omega, t^0)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^1)}, \\[4pt]
\delta_{(\omega, t^1)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^2)}, \\[4pt]
\delta_{(\omega, t^2)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^3)}, \\[4pt]
\delta_{(\omega, t^3)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^4)}, \\[4pt]
\delta_{(\omega, t^4)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^5)}, \\[4pt]
\delta_{(\omega, t^5)}\,Y_{0} &= Y_{0}\,\delta_{(\omega^2, t^0)}.
\end{aligned}

In [246]:
rels0Case3 := RelationsGivenByNicholsDualSmashkGDual(gensA[1], Case3);;
PrintNPList(rels0Case3);

 D_(w,0)Y0 - Y0D_(w^2,1)
 D_(w,1)Y0 - Y0D_(w^2,2)
 D_(w,2)Y0 - Y0D_(w^2,3)
 D_(w,3)Y0 - Y0D_(w^2,4)
 D_(w,4)Y0 - Y0D_(w^2,5)
 D_(w,5)Y0 - Y0D_(w^2,0)

4. si $g=(\omega^2, t^s)$ entonces $i=\omega^2$. Entonces, $\delta_{(\omega^2,t^s)}Y_{0}=Y_0\delta_{(1,t^{s+1})}$

\begin{aligned}
\delta_{(\omega^2, t^0)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^1)}, \\[4pt]
\delta_{(\omega^2, t^1)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^2)}, \\[4pt]
\delta_{(\omega^2, t^2)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^3)}, \\[4pt]
\delta_{(\omega^2, t^3)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^4)}, \\[4pt]
\delta_{(\omega^2, t^4)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^5)}, \\[4pt]
\delta_{(\omega^2, t^5)}\,Y_{0} &= Y_{0}\,\delta_{(1, t^0)}.
\end{aligned}

In [248]:
rels0Case4 := RelationsGivenByNicholsDualSmashkGDual(gensA[1], Case4);;
PrintNPList(rels0Case4);

 D_(w^2,0)Y0 - Y0D_(1,1)
 D_(w^2,1)Y0 - Y0D_(1,2)
 D_(w^2,2)Y0 - Y0D_(1,3)
 D_(w^2,3)Y0 - Y0D_(1,4)
 D_(w^2,4)Y0 - Y0D_(1,5)
 D_(w^2,5)Y0 - Y0D_(1,0)

- Caso $j = 1$ entonces $g_1 g=(1,1)*(b,t^s)=(1+\omega b, t^{s+1})$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $b=0$. Entonces, $\delta_{(0,t^s)}Y_{1}=Y_1\delta_{(1,t^{s+1})}$

\begin{aligned}
\delta_{(0, t^0)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^1)}, \\[4pt]
\delta_{(0, t^1)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^2)}, \\[4pt]
\delta_{(0, t^2)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^3)}, \\[4pt]
\delta_{(0, t^3)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^4)}, \\[4pt]
\delta_{(0, t^4)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^5)}, \\[4pt]
\delta_{(0, t^5)}\,Y_{1} &= Y_{1}\,\delta_{(1, t^0)}.
\end{aligned}

In [250]:
rels1Case1 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], Case1);;
PrintNPList(rels1Case1);

 DeY1 - Y1D_(1,1)
 D_(0,1)Y1 - Y1D_(1,2)
 D_(0,2)Y1 - Y1D_(1,3)
 D_(0,3)Y1 - Y1D_(1,4)
 D_(0,4)Y1 - Y1D_(1,5)
 D_(0,5)Y1 - Y1D_(1,0)

2. si $h=(1, t^s)$ entonces $b=1$. Entonces, $\delta_{(1,t^s)}Y_{1}=Y_1\delta_{(\omega^2,t^{s+1})}$

\begin{aligned}
\delta_{(1, t^0)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^1)}, \\[4pt]
\delta_{(1, t^1)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^2)}, \\[4pt]
\delta_{(1, t^2)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^3)}, \\[4pt]
\delta_{(1, t^3)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^4)}, \\[4pt]
\delta_{(1, t^4)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^5)}, \\[4pt]
\delta_{(1, t^5)}\,Y_{1} &= Y_{1}\,\delta_{(\omega^2, t^0)}.
\end{aligned}

In [252]:
rels1Case2 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], Case2);;
PrintNPList(rels1Case2);

 D_(1,0)Y1 - Y1D_(w^2,1)
 D_(1,1)Y1 - Y1D_(w^2,2)
 D_(1,2)Y1 - Y1D_(w^2,3)
 D_(1,3)Y1 - Y1D_(w^2,4)
 D_(1,4)Y1 - Y1D_(w^2,5)
 D_(1,5)Y1 - Y1D_(w^2,0)

3. si $h=(\omega, t^s)$ entonces $b=\omega$. Entonces, $\delta_{(\omega,t^s)}Y_{1}=Y_1\delta_{(\omega,t^{s+1})}$

\begin{aligned}
\delta_{(\omega, t^0)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^1)}, \\[4pt]
\delta_{(\omega, t^1)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^2)}, \\[4pt]
\delta_{(\omega, t^2)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^3)}, \\[4pt]
\delta_{(\omega, t^3)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^4)}, \\[4pt]
\delta_{(\omega, t^4)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^5)}, \\[4pt]
\delta_{(\omega, t^5)}\,Y_{1} &= Y_{1}\,\delta_{(\omega, t^0)}.
\end{aligned}

In [254]:
rels1Case3 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], Case3);;
PrintNPList(rels1Case3);

 D_(w,0)Y1 - Y1D_(w,1)
 D_(w,1)Y1 - Y1D_(w,2)
 D_(w,2)Y1 - Y1D_(w,3)
 D_(w,3)Y1 - Y1D_(w,4)
 D_(w,4)Y1 - Y1D_(w,5)
 D_(w,5)Y1 - Y1D_(w,0)

4. si $h=(\omega^2, t^s)$ entonces $b=\omega$. Entonces, $\delta_{(\omega^2,t^s)}Y_{1}=Y_1\delta_{(0,t^{s+1})}$

\begin{aligned}
\delta_{(\omega^2, t^0)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^1)}, \\[4pt]
\delta_{(\omega^2, t^1)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^2)}, \\[4pt]
\delta_{(\omega^2, t^2)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^3)}, \\[4pt]
\delta_{(\omega^2, t^3)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^4)}, \\[4pt]
\delta_{(\omega^2, t^4)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^5)}, \\[4pt]
\delta_{(\omega^2, t^5)}\,Y_{1} &= Y_{1}\,\delta_{(0, t^0)}.
\end{aligned}

In [256]:
rels1Case4 := RelationsGivenByNicholsDualSmashkGDual(gensA[2], Case4);;
PrintNPList(rels1Case4);

 D_(w^2,0)Y1 - Y1D_(0,1)
 D_(w^2,1)Y1 - Y1D_(0,2)
 D_(w^2,2)Y1 - Y1D_(0,3)
 D_(w^2,3)Y1 - Y1D_(0,4)
 D_(w^2,4)Y1 - Y1D_(0,5)
 D_(w^2,5)Y1 - Y1De

- Caso $j = \omega$ entonces $g_\omega g=(\omega,1)*(b,t^s)=(\omega (1+b), t^{s+1})$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $b=0$. Entonces, $\delta_{(0,t^s)}Y_{\omega}=Y_\omega\delta_{(\omega,t^{s+1})}$

\begin{aligned}
\delta_{(0, t^0)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^1)}, \\[4pt]
\delta_{(0, t^1)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^2)}, \\[4pt]
\delta_{(0, t^2)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^3)}, \\[4pt]
\delta_{(0, t^3)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^4)}, \\[4pt]
\delta_{(0, t^4)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^5)}, \\[4pt]
\delta_{(0, t^5)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega, t^0)}.
\end{aligned}

In [258]:
relsOmegaCase1 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], Case1);;
PrintNPList(relsOmegaCase1);

 DeY2 - Y2D_(w,1)
 D_(0,1)Y2 - Y2D_(w,2)
 D_(0,2)Y2 - Y2D_(w,3)
 D_(0,3)Y2 - Y2D_(w,4)
 D_(0,4)Y2 - Y2D_(w,5)
 D_(0,5)Y2 - Y2D_(w,0)

2. si $h=(1, t^s)$ entonces $b=1$. Entonces, $\delta_{(0,t^s)}Y_{\omega}=Y_\omega\delta_{(0,t^{s+1})}$

\begin{aligned}
\delta_{(1, t^0)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^1)}, \\[4pt]
\delta_{(1, t^1)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^2)}, \\[4pt]
\delta_{(1, t^2)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^3)}, \\[4pt]
\delta_{(1, t^3)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^4)}, \\[4pt]
\delta_{(1, t^4)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^5)}, \\[4pt]
\delta_{(1, t^5)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(0, t^0)}.
\end{aligned}

In [260]:
relsOmegaCase2 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], Case2);;
PrintNPList(relsOmegaCase2);

 D_(1,0)Y2 - Y2D_(0,1)
 D_(1,1)Y2 - Y2D_(0,2)
 D_(1,2)Y2 - Y2D_(0,3)
 D_(1,3)Y2 - Y2D_(0,4)
 D_(1,4)Y2 - Y2D_(0,5)
 D_(1,5)Y2 - Y2De

3. si $h=(\omega, t^s)$ entonces $b=\omega$. Entonces, $\delta_{(\omega,t^s)}Y_{\omega}=Y_\omega\delta_{(1,t^{s+1})}$

\begin{aligned}
\delta_{(\omega, t^0)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^1)}, \\[4pt]
\delta_{(\omega, t^1)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^2)}, \\[4pt]
\delta_{(\omega, t^2)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^3)}, \\[4pt]
\delta_{(\omega, t^3)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^4)}, \\[4pt]
\delta_{(\omega, t^4)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^5)}, \\[4pt]
\delta_{(\omega, t^5)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(1, t^0)}.
\end{aligned}

In [262]:
relsOmegaCase3 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], Case3);;
PrintNPList(relsOmegaCase3);

 D_(w,0)Y2 - Y2D_(1,1)
 D_(w,1)Y2 - Y2D_(1,2)
 D_(w,2)Y2 - Y2D_(1,3)
 D_(w,3)Y2 - Y2D_(1,4)
 D_(w,4)Y2 - Y2D_(1,5)
 D_(w,5)Y2 - Y2D_(1,0)

4. si $h=(\omega^2, t^s)$ entonces $b=\omega^2$. Entonces, $\delta_{(\omega^2,t^s)}Y_{\omega}=Y_\omega\delta_{(\omega^2,t^{s+1})}$

\begin{aligned}
\delta_{(\omega^2, t^0)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^1)}, \\[4pt]
\delta_{(\omega^2, t^1)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^2)}, \\[4pt]
\delta_{(\omega^2, t^2)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^3)}, \\[4pt]
\delta_{(\omega^2, t^3)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^4)}, \\[4pt]
\delta_{(\omega^2, t^4)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^5)}, \\[4pt]
\delta_{(\omega^2, t^5)}\,Y_{\omega} &= Y_{\omega}\,\delta_{(\omega^2, t^0)}.
\end{aligned}

In [264]:
relsOmegaCase4 := RelationsGivenByNicholsDualSmashkGDual(gensA[3], Case4);;
PrintNPList(relsOmegaCase4);

 D_(w^2,0)Y2 - Y2D_(w^2,1)
 D_(w^2,1)Y2 - Y2D_(w^2,2)
 D_(w^2,2)Y2 - Y2D_(w^2,3)
 D_(w^2,3)Y2 - Y2D_(w^2,4)
 D_(w^2,4)Y2 - Y2D_(w^2,5)
 D_(w^2,5)Y2 - Y2D_(w^2,0)

- Caso $j = \omega^2$ entonces $g_{\omega^2} g=(\omega^2,1)*(b,t^s)=(\omega (\omega+b), t^{s+1})$, con $s\in\{0,1,\dots, 5\}$:

1. si $h=(0, t^s)$ entonces $b=0$. Entonces, $\delta_{(0,t^s)}Y_{\omega^2}=Y_{\omega^2}\delta_{(\omega^2,t^{s+1})}$

\begin{aligned}
\delta_{(0, t^0)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^1)}, \\[4pt]
\delta_{(0, t^1)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^2)}, \\[4pt]
\delta_{(0, t^2)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^3)}, \\[4pt]
\delta_{(0, t^3)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^4)}, \\[4pt]
\delta_{(0, t^4)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^5)}, \\[4pt]
\delta_{(0, t^5)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega^2, t^0)}.
\end{aligned}

In [266]:
relsOmega2Case1 := RelationsGivenByNicholsDualSmashkGDual(gensA[4], Case1);;
PrintNPList(relsOmega2Case1);

 DeY3 - Y3D_(w^2,1)
 D_(0,1)Y3 - Y3D_(w^2,2)
 D_(0,2)Y3 - Y3D_(w^2,3)
 D_(0,3)Y3 - Y3D_(w^2,4)
 D_(0,4)Y3 - Y3D_(w^2,5)
 D_(0,5)Y3 - Y3D_(w^2,0)

2. si $h=(1, t^s)$ entonces $b=1$. Entonces, $\delta_{(1,t^s)}Y_{\omega^2}=Y_{\omega^2}\delta_{(1,t^{s+1})}$

\begin{aligned}
\delta_{(1, t^0)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^1)}, \\[4pt]
\delta_{(1, t^1)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^2)}, \\[4pt]
\delta_{(1, t^2)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^3)}, \\[4pt]
\delta_{(1, t^3)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^4)}, \\[4pt]
\delta_{(1, t^4)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^5)}, \\[4pt]
\delta_{(1, t^5)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(1, t^0)}.
\end{aligned}

In [268]:
relsOmega2Case2:=RelationsGivenByNicholsDualSmashkGDual(gensA[4], Case2);;
PrintNPList(relsOmega2Case2);

 D_(1,0)Y3 - Y3D_(1,1)
 D_(1,1)Y3 - Y3D_(1,2)
 D_(1,2)Y3 - Y3D_(1,3)
 D_(1,3)Y3 - Y3D_(1,4)
 D_(1,4)Y3 - Y3D_(1,5)
 D_(1,5)Y3 - Y3D_(1,0)

3. si $h=(\omega, t^s)$ entonces $b=\omega$. Entonces, $\delta_{(\omega,t^s)}Y_{\omega^2}=Y_{\omega^2}\delta_{(0,t^{s+1})}$

\begin{aligned}
\delta_{(\omega, t^0)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^1)}, \\[4pt]
\delta_{(\omega, t^1)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^2)}, \\[4pt]
\delta_{(\omega, t^2)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^3)}, \\[4pt]
\delta_{(\omega, t^3)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^4)}, \\[4pt]
\delta_{(\omega, t^4)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^5)}, \\[4pt]
\delta_{(\omega, t^5)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(0, t^0)}.
\end{aligned}

In [270]:
relsOmega2Case3 := RelationsGivenByNicholsDualSmashkGDual(gensA[4], Case3);;
PrintNPList(relsOmega2Case3);

 D_(w,0)Y3 - Y3D_(0,1)
 D_(w,1)Y3 - Y3D_(0,2)
 D_(w,2)Y3 - Y3D_(0,3)
 D_(w,3)Y3 - Y3D_(0,4)
 D_(w,4)Y3 - Y3D_(0,5)
 D_(w,5)Y3 - Y3De

4. si $h=(\omega^2, t^s)$ entonces $b=\omega^2$. Entonces, $\delta_{(\omega^2,t^s)}Y_{\omega^2}=Y_{\omega}\delta_{(\omega,t^{s+1})}$

\begin{aligned}
\delta_{(\omega^2, t^0)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^1)}, \\[4pt]
\delta_{(\omega^2, t^1)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^2)}, \\[4pt]
\delta_{(\omega^2, t^2)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^3)}, \\[4pt]
\delta_{(\omega^2, t^3)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^4)}, \\[4pt]
\delta_{(\omega^2, t^4)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^5)}, \\[4pt]
\delta_{(\omega^2, t^5)}\,Y_{\omega^2} &= Y_{\omega^2}\,\delta_{(\omega, t^0)}.
\end{aligned}

In [272]:
relsOmega2Case4 := RelationsGivenByNicholsDualSmashkGDual(gensA[4], Case4);;
PrintNPList(relsOmega2Case4);

 D_(w^2,0)Y3 - Y3D_(w,1)
 D_(w^2,1)Y3 - Y3D_(w,2)
 D_(w^2,2)Y3 - Y3D_(w,3)
 D_(w^2,3)Y3 - Y3D_(w,4)
 D_(w^2,4)Y3 - Y3D_(w,5)
 D_(w^2,5)Y3 - Y3D_(w,0)

In [273]:
relsDy:=Concatenation(
    rels0Case1,
    rels0Case2,
    rels0Case3,
    rels0Case4,
    rels1Case1,
    rels1Case2,
    rels1Case3,
    rels1Case4,
    relsOmegaCase1,
    relsOmegaCase2,
    relsOmegaCase3,
    relsOmegaCase4,
    relsOmega2Case1,
    relsOmega2Case2,
    relsOmega2Case3,
    relsOmega2Case4
);;

In [275]:
# Test the first relation
Print("Total relations generated: ", Length(relsDy), ".\n");
PrintNPList(relsDy);

Total relations generated: 96.
 DeY0 - Y0D_(0,1)
 D_(0,1)Y0 - Y0D_(0,2)
 D_(0,2)Y0 - Y0D_(0,3)
 D_(0,3)Y0 - Y0D_(0,4)
 D_(0,4)Y0 - Y0D_(0,5)
 D_(0,5)Y0 - Y0De
 D_(1,0)Y0 - Y0D_(w,1)
 D_(1,1)Y0 - Y0D_(w,2)
 D_(1,2)Y0 - Y0D_(w,3)
 D_(1,3)Y0 - Y0D_(w,4)
 D_(1,4)Y0 - Y0D_(w,5)
 D_(1,5)Y0 - Y0D_(w,0)
 D_(w,0)Y0 - Y0D_(w^2,1)
 D_(w,1)Y0 - Y0D_(w^2,2)
 D_(w,2)Y0 - Y0D_(w^2,3)
 D_(w,3)Y0 - Y0D_(w^2,4)
 D_(w,4)Y0 - Y0D_(w^2,5)
 D_(w,5)Y0 - Y0D_(w^2,0)
 D_(w^2,0)Y0 - Y0D_(1,1)
 D_(w^2,1)Y0 - Y0D_(1,2)
 D_(w^2,2)Y0 - Y0D_(1,3)
 D_(w^2,3)Y0 - Y0D_(1,4)
 D_(w^2,4)Y0 - Y0D_(1,5)
 D_(w^2,5)Y0 - Y0D_(1,0)
 DeY1 - Y1D_(1,1)
 D_(0,1)Y1 - Y1D_(1,2)
 D_(0,2)Y1 - Y1D_(1,3)
 D_(0,3)Y1 - Y1D_(1,4)
 D_(0,4)Y1 - Y1D_(1,5)
 D_(0,5)Y1 - Y1D_(1,0)
 D_(1,0)Y1 - Y1D_(w^2,1)
 D_(1,1)Y1 - Y1D_(w^2,2)
 D_(1,2)Y1 - Y1D_(w^2,3)
 D_(1,3)Y1 - Y1D_(w^2,4)
 D_(1,4)Y1 - Y1D_(w^2,5)
 D_(1,5)Y1 - Y1D_(w^2,0)
 D_(w,0)Y1 - Y1D_(w,1)
 D_(w,1)Y1 - Y1D_(w,2)
 D_(w,2)Y1 - Y1D_(w,3)
 D_(w,3)Y1 - Y1D_(w,4)
 D_(w,4)Y1 - Y1D_(w,5)
 D_(w,5)Y1 - Y1D_(w,0)
 D_(w^2,0)Y1 - Y1D_(0,1)
 D_(w^2,1)Y1 - Y1D_(0,2)
 D_(w^2,2)Y1 - Y1D_(0,3)
 D_(w^2,3)Y1 - Y1D_(0,4)
 D_(w^2,4)Y1 - Y1D_(0,5)
 D_(w^2,5)Y1 - Y1De
 DeY2 - Y2D_(w,1)
 D_(0,1)Y2 - Y2D_(w,2)
 D_(0,2)Y2 - Y2D_(w,3)
 D_(0,3)Y2 - Y2D_(w,4)
 D_(0,4)Y2 - Y2D_(w,5)
 D_(0,5)Y2 - Y2D_(w,0)
 D_(1,0)Y2 - Y2D_(0,1)
 D_(1,1)Y2 - Y2D_(0,2)
 D_(1,2)Y2 - Y2D_(0,3)
 D_(1,3)Y2 - Y2D_(0,4)
 D_(1,4)Y2 - Y2D_(0,5)
 D_(1,5)Y2 - Y2De
 D_(w,0)Y2 - Y2D_(1,1)
 D_(w,1)Y2 - Y2D_(1,2)
 D_(w,2)Y2 - Y2D_(1,3)
 D_(w,3)Y2 - Y2D_(1,4)
 D_(w,4)Y2 - Y2D_(1,5)
 D_(w,5)Y2 - Y2D_(1,0)
 D_(w^2,0)Y2 - Y2D_(w^2,1)
 D_(w^2,1)Y2 - Y2D_(w^2,2)
 D_(w^2,2)Y2 - Y2D_(w^2,3)
 D_(w^2,3)Y2 - Y2D_(w^2,4)
 D_(w^2,4)Y2 - Y2D_(w^2,5)
 D_(w^2,5)Y2 - Y2D_(w^2,0)
 DeY3 - Y3D_(w^2,1)
 D_(0,1)Y3 - Y3D_(w^2,2)
 D_(0,2)Y3 - Y3D_(w^2,3)
 D_(0,3)Y3 - Y3D_(w^2,4)
 D_(0,4)Y3 - Y3D_(w^2,5)
 D_(0,5)Y3 - Y3D_(w^2,0)
 D_(1,0)Y3 - Y3D_(1,1)
 D_(1,1)Y3 - Y3D_(1,2)
 D_(1,2)Y3 - Y3D_(1,3)
 D_(1,3)Y3 - Y3D_(1,4)
 D_(1,4)Y3 - Y3D_(1,5)
 D_(1,5)Y3 - Y3D_(1,0)
 D_(w,0)Y3 - Y3D_(0,1)
 D_(w,1)Y3 - Y3D_(0,2)
 D_(w,2)Y3 - Y3D_(0,3)
 D_(w,3)Y3 - Y3D_(0,4)
 D_(w,4)Y3 - Y3D_(0,5)
 D_(w,5)Y3 - Y3De
 D_(w^2,0)Y3 - Y3D_(w,1)
 D_(w^2,1)Y3 - Y3D_(w,2)
 D_(w^2,2)Y3 - Y3D_(w,3)
 D_(w^2,3)Y3 - Y3D_(w,4)
 D_(w^2,4)Y3 - Y3D_(w,5)
 D_(w^2,5)Y3 - Y3D_(w,0)

In [276]:
J := SGrobner(Concatenation(
    relsT4dual,
    relskG,
    relsDy,
    gensG,
    gensX
    )
);;

In [277]:
DimQA(J, 36);

1728

In [278]:
72*24;

1728

# Calculo $\mathfrak{B}(V)\#D(G)$

In [279]:
I := Concatenation(
    relsT4,       # 9 rels
    # ------------------------
    relsGroup,    # 7 rels
    relskG,       # 577 rels
    relsDG,       # 576 rels
    # ------------------------
    relsxBos,     # 96 rels
    relsDx,       # 96 rels
    gensY
);;

In [281]:
9 + 7 + 577 + 576 + 96*2 + 4;
Length(I);

1365

1365

- Paso 5: Calcular la base de Gröbner

In [283]:
J_D_ge_0 := SGrobner(I);;
PrintNPList( J_D_ge_0 );

 D_(w^2,5) + D_(w^2,4) + D_(w^2,3) + D_(w^2,2) + D_(w^2,1) + D_(w^2,0) + D_(w,\
5) + D_(w,4) + D_(w,3) + D_(w,2) + D_(w,1) + D_(w,0) + D_(1,5) + D_(1,4) + D_(\
1,3) + D_(1,2) + D_(1,1) + D_(1,0) + D_(0,5) + D_(0,4) + D_(0,3) + D_(0,2) + D\
_(0,1) + De - 1
 Y0
 Y1
 Y2
 Y3
 X0^2
 X1^2
 X2X0 + X1X2 + X0X1
 X2^2
 X3X0 + X2X3 + X0X2
 X3X1 + X1X0 + X0X3
 X3X2 + X2X1 + X1X3
 X3^2
 tX0 + X0t
 tX1 + X2t
 tX2 + X3t
 tX3 + X1t
 t^2 - x
 xX0 - X0x
 xX1 - X3x
 xX2 - X1x
 xX3 - X2x
 xt - tx
 yX0 - X1y
 yX1 - X0y
 yX2 - X3y
 yX3 - X2y
 yt - tz
 y^2 - 1
 zX0 - X3z
 zX1 - X2z
 zX2 - X1z
 zX3 - X0z
 zx - xy
 zy - yz
 z^2 - 1
 DeX0 - X0D_(0,5)
 DeX1 + X1D_(w^2,4) + X1D_(w^2,3) + X1D_(w^2,2) + X1D_(w^2,1) + X1D_(w^2,0) + \
X1D_(w,5) + X1D_(w,4) + X1D_(w,3) + X1D_(w,2) + X1D_(w,1) + X1D_(w,0) + X1D_(1\
,5) + X1D_(1,4) + X1D_(1,3) + X1D_(1,2) + X1D_(1,1) + X1D_(1,0) + X1D_(0,5) + \
X1D_(0,4) + X1D_(0,3) + X1D_(0,2) + X1D_(0,1) + X1De - X1
 DeX2 - X2D_(1,5)
 DeX3 - X3D_(w,5)
 Det - tDe
 Dex - xDe
 Dey - yDe
 Dez - zDe
 De^2 - De
 DeD_(0,1)
 DeD_(0,2)
 DeD_(0,3)
 DeD_(0,4)
 DeD_(0,5)
 DeD_(1,0)
 DeD_(1,1)
 DeD_(1,2)
 DeD_(1,3)
 DeD_(1,4)
 DeD_(1,5)
 DeD_(w,0)
 DeD_(w,1)
 DeD_(w,2)
 DeD_(w,3)
 DeD_(w,4)
 DeD_(w,5)
 DeD_(w^2,0)
 DeD_(w^2,1)
 DeD_(w^2,2)
 DeD_(w^2,3)
 DeD_(w^2,4)
 D_(0,1)X0 - X0De
 D_(0,1)X1 - X1D_(w^2,0)
 D_(0,1)X2 - X2D_(1,0)
 D_(0,1)X3 - X3D_(w,0)
 D_(0,1)t - tD_(0,1)
 D_(0,1)x - xD_(0,1)
 D_(0,1)y - yD_(1,1)
 D_(0,1)z - zD_(w^2,1)
 D_(0,1)De
 D_(0,1)^2 - D_(0,1)
 D_(0,1)D_(0,2)
 D_(0,1)D_(0,3)
 D_(0,1)D_(0,4)
 D_(0,1)D_(0,5)
 D_(0,1)D_(1,0)
 D_(0,1)D_(1,1)
 D_(0,1)D_(1,2)
 D_(0,1)D_(1,3)
 D_(0,1)D_(1,4)
 D_(0,1)D_(1,5)
 D_(0,1)D_(w,0)
 D_(0,1)D_(w,1)
 D_(0,1)D_(w,2)
 D_(0,1)D_(w,3)
 D_(0,1)D_(w,4)
 D_(0,1)D_(w,5)
 D_(0,1)D_(w^2,0)
 D_(0,1)D_(w^2,1)
 D_(0,1)D_(w^2,2)
 D_(0,1)D_(w^2,3)
 D_(0,1)D_(w^2,4)
 D_(0,2)X0 - X0D_(0,1)
 D_(0,2)X1 - X1D_(w^2,1)
 D_(0,2)X2 - X2D_(1,1)
 D_(0,2)X3 - X3D_(w,1)
 D_(0,2)t - tD_(0,2)
 D_(0,2)x - xD_(0,2)
 D_(0,2)y - yD_(w^2,2)
 D_(0,2)z - zD_(w,2)
 D_(0,2)De
 D_(0,2)D_(0,1)
 D_(0,2)^2 - D_(0,2)
 D_(0,2)D_(0,3)
 D_(0,2)D_(0,4)
 D_(0,2)D_(0,5)
 D_(0,2)D_(1,0)
 D_(0,2)D_(1,1)
 D_(0,2)D_(1,2)
 D_(0,2)D_(1,3)
 D_(0,2)D_(1,4)
 D_(0,2)D_(1,5)
 D_(0,2)D_(w,0)
 D_(0,2)D_(w,1)
 D_(0,2)D_(w,2)
 D_(0,2)D_(w,3)
 D_(0,2)D_(w,4)
 D_(0,2)D_(w,5)
 D_(0,2)D_(w^2,0)
 D_(0,2)D_(w^2,1)
 D_(0,2)D_(w^2,2)
 D_(0,2)D_(w^2,3)
 D_(0,2)D_(w^2,4)
 D_(0,3)X0 - X0D_(0,2)
 D_(0,3)X1 - X1D_(w^2,2)
 D_(0,3)X2 - X2D_(1,2)
 D_(0,3)X3 - X3D_(w,2)
 D_(0,3)t - tD_(0,3)
 D_(0,3)x - xD_(0,3)
 D_(0,3)y - yD_(0,3)
 D_(0,3)z - zD_(0,3)
 D_(0,3)De
 D_(0,3)D_(0,1)
 D_(0,3)D_(0,2)
 D_(0,3)^2 - D_(0,3)
 D_(0,3)D_(0,4)
 D_(0,3)D_(0,5)
 D_(0,3)D_(1,0)
 D_(0,3)D_(1,1)
 D_(0,3)D_(1,2)
 D_(0,3)D_(1,3)
 D_(0,3)D_(1,4)
 D_(0,3)D_(1,5)
 D_(0,3)D_(w,0)
 D_(0,3)D_(w,1)
 D_(0,3)D_(w,2)
 D_(0,3)D_(w,3)
 D_(0,3)D_(w,4)
 D_(0,3)D_(w,5)
 D_(0,3)D_(w^2,0)
 D_(0,3)D_(w^2,1)
 D_(0,3)D_(w^2,2)
 D_(0,3)D_(w^2,3)
 D_(0,3)D_(w^2,4)
 D_(0,4)X0 - X0D_(0,3)
 D_(0,4)X1 - X1D_(w^2,3)
 D_(0,4)X2 - X2D_(1,3)
 D_(0,4)X3 - X3D_(w,3)
 D_(0,4)t - tD_(0,4)
 D_(0,4)x - xD_(0,4)
 D_(0,4)y - yD_(1,4)
 D_(0,4)z - zD_(w^2,4)
 D_(0,4)De
 D_(0,4)D_(0,1)
 D_(0,4)D_(0,2)
 D_(0,4)D_(0,3)
 D_(0,4)^2 - D_(0,4)
 D_(0,4)D_(0,5)
 D_(0,4)D_(1,0)
 D_(0,4)D_(1,1)
 D_(0,4)D_(1,2)
 D_(0,4)D_(1,3)
 D_(0,4)D_(1,4)
 D_(0,4)D_(1,5)
 D_(0,4)D_(w,0)
 D_(0,4)D_(w,1)
 D_(0,4)D_(w,2)
 D_(0,4)D_(w,3)
 D_(0,4)D_(w,4)
 D_(0,4)D_(w,5)
 D_(0,4)D_(w^2,0)
 D_(0,4)D_(w^2,1)
 D_(0,4)D_(w^2,2)
 D_(0,4)D_(w^2,3)
 D_(0,4)D_(w^2,4)
 D_(0,5)X0 - X0D_(0,4)
 D_(0,5)X1 - X1D_(w^2,4)
 D_(0,5)X2 - X2D_(1,4)
 D_(0,5)X3 - X3D_(w,4)
 D_(0,5)t - tD_(0,5)
 D_(0,5)x - xD_(0,5)
 D_(0,5)y + yD_(w^2,4) + yD_(w^2,3) + yD_(w^2,2) + yD_(w^2,1) + yD_(w^2,0) + y\
D_(w,5) + yD_(w,4) + yD_(w,3) + yD_(w,2) + yD_(w,1) + yD_(w,0) + yD_(1,5) + yD\
_(1,4) + yD_(1,3) + yD_(1,2) + yD_(1,1) + yD_(1,0) + yD_(0,5) + yD_(0,4) + yD_\
(0,3) + yD_(0,2) + yD_(0,1) + yDe - y
 D_(0,5)z - zD_(w,5)
 D_(0,5)De
 D_(0,5)D_(0,1)
 D_(0,5)D_(0,2)
 D_(0,5)D_(0,3)
 D_(0,5)D_(0,4)
 D_(0,5)^2 - D_(0,5)
 D_(0,5)D_(1,0)
 D_(0,5)D_(1,1)
 D_(0,5)D_(1,2)
 D_(0,5)D_(1,3)
 D_(0,5)D_(1,4)
 D_(0,5)D_(1,5)
 D_(0,5)D_(w,0)
 D_(0,5)D_(w,1)
 D_(0,5)D_(w,2)
 D_(0,5)D_(w,3)
 D_(0,5)D_(w,4)
 D_(0,5)D_(w,5)
 D_(0,5)D_(w^2,0)
 D_(0,5)D_(w^2,1)
 D_(0,5)D_(w^2,2)
 D_(0,5)D_(w^2,3)
 D_(0,5)D_(w^2,4)
 D_(1,0)X0 + X0D_(w^2,4) + X0D_(w^2,3) + X0D_(w^2,2) + X0D_(w^2,1) + X0D_(w^2,\
0) + X0D_(w,5) + X0D_(w,4) + X0D_(w,3) + X0D_(w,2) + X0D_(w,1) + X0D_(w,0) + X\
0D_(1,5) + X0D_(1,4) + X0D_(1,3) + X0D_(1,2) + X0D_(1,1) + X0D_(1,0) + X0D_(0,\
5) + X0D_(0,4) + X0D_(0,3) + X0D_(0,2) + X0D_(0,1) + X0De - X0
 D_(1,0)X1 - X1D_(0,5)
 D_(1,0)X2 - X2D_(w,5)
 D_(1,0)X3 - X3D_(1,5)
 D_(1,0)t - tD_(w^2,0)
 D_(1,0)x - xD_(w,0)
 D_(1,0)y - yD_(1,0)
 D_(1,0)z - zD_(1,0)
 D_(1,0)De
 D_(1,0)D_(0,1)
 D_(1,0)D_(0,2)
 D_(1,0)D_(0,3)
 D_(1,0)D_(0,4)
 D_(1,0)D_(0,5)
 D_(1,0)^2 - D_(1,0)
 D_(1,0)D_(1,1)
 D_(1,0)D_(1,2)
 D_(1,0)D_(1,3)
 D_(1,0)D_(1,4)
 D_(1,0)D_(1,5)
 D_(1,0)D_(w,0)
 D_(1,0)D_(w,1)
 D_(1,0)D_(w,2)
 D_(1,0)D_(w,3)
 D_(1,0)D_(w,4)
 D_(1,0)D_(w,5)
 D_(1,0)D_(w^2,0)
 D_(1,0)D_(w^2,1)
 D_(1,0)D_(w^2,2)
 D_(1,0)D_(w^2,3)
 D_(1,0)D_(w^2,4)
 D_(1,1)X0 - X0D_(w^2,0)
 D_(1,1)X1 - X1De
 D_(1,1)X2 - X2D_(w,0)
 D_(1,1)X3 - X3D_(1,0)
 D_(1,1)t - tD_(w^2,1)
 D_(1,1)x - xD_(w,1)
 D_(1,1)y - yD_(0,1)
 D_(1,1)z - zD_(w,1)
 D_(1,1)De
 D_(1,1)D_(0,1)
 D_(1,1)D_(0,2)
 D_(1,1)D_(0,3)
 D_(1,1)D_(0,4)
 D_(1,1)D_(0,5)
 D_(1,1)D_(1,0)
 D_(1,1)^2 - D_(1,1)
 D_(1,1)D_(1,2)
 D_(1,1)D_(1,3)
 D_(1,1)D_(1,4)
 D_(1,1)D_(1,5)
 D_(1,1)D_(w,0)
 D_(1,1)D_(w,1)
 D_(1,1)D_(w,2)
 D_(1,1)D_(w,3)
 D_(1,1)D_(w,4)
 D_(1,1)D_(w,5)
 D_(1,1)D_(w^2,0)
 D_(1,1)D_(w^2,1)
 D_(1,1)D_(w^2,2)
 D_(1,1)D_(w^2,3)
 D_(1,1)D_(w^2,4)
 D_(1,2)X0 - X0D_(w^2,1)
 D_(1,2)X1 - X1D_(0,1)
 D_(1,2)X2 - X2D_(w,1)
 D_(1,2)X3 - X3D_(1,1)
 D_(1,2)t - tD_(w^2,2)
 D_(1,2)x - xD_(w,2)
 D_(1,2)y - yD_(w,2)
 D_(1,2)z - zD_(w^2,2)
 D_(1,2)De
 D_(1,2)D_(0,1)
 D_(1,2)D_(0,2)
 D_(1,2)D_(0,3)
 D_(1,2)D_(0,4)
 D_(1,2)D_(0,5)
 D_(1,2)D_(1,0)
 D_(1,2)D_(1,1)
 D_(1,2)^2 - D_(1,2)
 D_(1,2)D_(1,3)
 D_(1,2)D_(1,4)
 D_(1,2)D_(1,5)
 D_(1,2)D_(w,0)
 D_(1,2)D_(w,1)
 D_(1,2)D_(w,2)
 D_(1,2)D_(w,3)
 D_(1,2)D_(w,4)
 D_(1,2)D_(w,5)
 D_(1,2)D_(w^2,0)
 D_(1,2)D_(w^2,1)
 D_(1,2)D_(w^2,2)
 D_(1,2)D_(w^2,3)
 D_(1,2)D_(w^2,4)
 D_(1,3)X0 - X0D_(w^2,2)
 D_(1,3)X1 - X1D_(0,2)
 D_(1,3)X2 - X2D_(w,2)
 D_(1,3)X3 - X3D_(1,2)
 D_(1,3)t - tD_(w^2,3)
 D_(1,3)x - xD_(w,3)
 D_(1,3)y - yD_(1,3)
 D_(1,3)z - zD_(1,3)
 D_(1,3)De
 D_(1,3)D_(0,1)
 D_(1,3)D_(0,2)
 D_(1,3)D_(0,3)
 D_(1,3)D_(0,4)
 D_(1,3)D_(0,5)
 D_(1,3)D_(1,0)
 D_(1,3)D_(1,1)
 D_(1,3)D_(1,2)
 D_(1,3)^2 - D_(1,3)
 D_(1,3)D_(1,4)
 D_(1,3)D_(1,5)
 D_(1,3)D_(w,0)
 D_(1,3)D_(w,1)
 D_(1,3)D_(w,2)
 D_(1,3)D_(w,3)
 D_(1,3)D_(w,4)
 D_(1,3)D_(w,5)
 D_(1,3)D_(w^2,0)
 D_(1,3)D_(w^2,1)
 D_(1,3)D_(w^2,2)
 D_(1,3)D_(w^2,3)
 D_(1,3)D_(w^2,4)
 D_(1,4)X0 - X0D_(w^2,3)
 D_(1,4)X1 - X1D_(0,3)
 D_(1,4)X2 - X2D_(w,3)
 D_(1,4)X3 - X3D_(1,3)
 D_(1,4)t - tD_(w^2,4)
 D_(1,4)x - xD_(w,4)
 D_(1,4)y - yD_(0,4)
 D_(1,4)z - zD_(w,4)
 D_(1,4)De
 D_(1,4)D_(0,1)
 D_(1,4)D_(0,2)
 D_(1,4)D_(0,3)
 D_(1,4)D_(0,4)
 D_(1,4)D_(0,5)
 D_(1,4)D_(1,0)
 D_(1,4)D_(1,1)
 D_(1,4)D_(1,2)
 D_(1,4)D_(1,3)
 D_(1,4)^2 - D_(1,4)
 D_(1,4)D_(1,5)
 D_(1,4)D_(w,0)
 D_(1,4)D_(w,1)
 D_(1,4)D_(w,2)
 D_(1,4)D_(w,3)
 D_(1,4)D_(w,4)
 D_(1,4)D_(w,5)
 D_(1,4)D_(w^2,0)
 D_(1,4)D_(w^2,1)
 D_(1,4)D_(w^2,2)
 D_(1,4)D_(w^2,3)
 D_(1,4)D_(w^2,4)
 D_(1,5)X0 - X0D_(w^2,4)
 D_(1,5)X1 - X1D_(0,4)
 D_(1,5)X2 - X2D_(w,4)
 D_(1,5)X3 - X3D_(1,4)
 D_(1,5)t + tD_(w^2,4) + tD_(w^2,3) + tD_(w^2,2) + tD_(w^2,1) + tD_(w^2,0) + t\
D_(w,5) + tD_(w,4) + tD_(w,3) + tD_(w,2) + tD_(w,1) + tD_(w,0) + tD_(1,5) + tD\
_(1,4) + tD_(1,3) + tD_(1,2) + tD_(1,1) + tD_(1,0) + tD_(0,5) + tD_(0,4) + tD_\
(0,3) + tD_(0,2) + tD_(0,1) + tDe - t
 D_(1,5)x - xD_(w,5)
 D_(1,5)y - yD_(w,5)
 D_(1,5)z + zD_(w^2,4) + zD_(w^2,3) + zD_(w^2,2) + zD_(w^2,1) + zD_(w^2,0) + z\
D_(w,5) + zD_(w,4) + zD_(w,3) + zD_(w,2) + zD_(w,1) + zD_(w,0) + zD_(1,5) + zD\
_(1,4) + zD_(1,3) + zD_(1,2) + zD_(1,1) + zD_(1,0) + zD_(0,5) + zD_(0,4) + zD_\
(0,3) + zD_(0,2) + zD_(0,1) + zDe - z
 D_(1,5)De
 D_(1,5)D_(0,1)
 D_(1,5)D_(0,2)
 D_(1,5)D_(0,3)
 D_(1,5)D_(0,4)
 D_(1,5)D_(0,5)
 D_(1,5)D_(1,0)
 D_(1,5)D_(1,1)
 D_(1,5)D_(1,2)
 D_(1,5)D_(1,3)
 D_(1,5)D_(1,4)
 D_(1,5)^2 - D_(1,5)
 D_(1,5)D_(w,0)
 D_(1,5)D_(w,1)
 D_(1,5)D_(w,2)
 D_(1,5)D_(w,3)
 D_(1,5)D_(w,4)
 D_(1,5)D_(w,5)
 D_(1,5)D_(w^2,0)
 D_(1,5)D_(w^2,1)
 D_(1,5)D_(w^2,2)
 D_(1,5)D_(w^2,3)
 D_(1,5)D_(w^2,4)
 D_(w,0)X0 - X0D_(1,5)
 D_(w,0)X1 - X1D_(w,5)
 D_(w,0)X2 - X2D_(0,5)
 D_(w,0)X3 + X3D_(w^2,4) + X3D_(w^2,3) + X3D_(w^2,2) + X3D_(w^2,1) + X3D_(w^2,\
0) + X3D_(w,5) + X3D_(w,4) + X3D_(w,3) + X3D_(w,2) + X3D_(w,1) + X3D_(w,0) + X\
3D_(1,5) + X3D_(1,4) + X3D_(1,3) + X3D_(1,2) + X3D_(1,1) + X3D_(1,0) + X3D_(0,\
5) + X3D_(0,4) + X3D_(0,3) + X3D_(0,2) + X3D_(0,1) + X3De - X3
 D_(w,0)t - tD_(1,0)
 D_(w,0)x - xD_(w^2,0)
 D_(w,0)y - yD_(w,0)
 D_(w,0)z - zD_(w,0)
 D_(w,0)De
 D_(w,0)D_(0,1)
 D_(w,0)D_(0,2)
 D_(w,0)D_(0,3)
 D_(w,0)D_(0,4)
 D_(w,0)D_(0,5)
 D_(w,0)D_(1,0)
 D_(w,0)D_(1,1)
 D_(w,0)D_(1,2)
 D_(w,0)D_(1,3)
 D_(w,0)D_(1,4)
 D_(w,0)D_(1,5)
 D_(w,0)^2 - D_(w,0)
 D_(w,0)D_(w,1)
 D_(w,0)D_(w,2)
 D_(w,0)D_(w,3)
 D_(w,0)D_(w,4)
 D_(w,0)D_(w,5)
 D_(w,0)D_(w^2,0)
 D_(w,0)D_(w^2,1)
 D_(w,0)D_(w^2,2)
 D_(w,0)D_(w^2,3)
 D_(w,0)D_(w^2,4)
 D_(w,1)X0 - X0D_(1,0)
 D_(w,1)X1 - X1D_(w,0)
 D_(w,1)X2 - X2De
 D_(w,1)X3 - X3D_(w^2,0)
 D_(w,1)t - tD_(1,1)
 D_(w,1)x - xD_(w^2,1)
 D_(w,1)y - yD_(w^2,1)
 D_(w,1)z - zD_(1,1)
 D_(w,1)De
 D_(w,1)D_(0,1)
 D_(w,1)D_(0,2)
 D_(w,1)D_(0,3)
 D_(w,1)D_(0,4)
 D_(w,1)D_(0,5)
 D_(w,1)D_(1,0)
 D_(w,1)D_(1,1)
 D_(w,1)D_(1,2)
 D_(w,1)D_(1,3)
 D_(w,1)D_(1,4)
 D_(w,1)D_(1,5)
 D_(w,1)D_(w,0)
 D_(w,1)^2 - D_(w,1)
 D_(w,1)D_(w,2)
 D_(w,1)D_(w,3)
 D_(w,1)D_(w,4)
 D_(w,1)D_(w,5)
 D_(w,1)D_(w^2,0)
 D_(w,1)D_(w^2,1)
 D_(w,1)D_(w^2,2)
 D_(w,1)D_(w^2,3)
 D_(w,1)D_(w^2,4)
 D_(w,2)X0 - X0D_(1,1)
 D_(w,2)X1 - X1D_(w,1)
 D_(w,2)X2 - X2D_(0,1)
 D_(w,2)X3 - X3D_(w^2,1)
 D_(w,2)t - tD_(1,2)
 D_(w,2)x - xD_(w^2,2)
 D_(w,2)y - yD_(1,2)
 D_(w,2)z - zD_(0,2)
 D_(w,2)De
 D_(w,2)D_(0,1)
 D_(w,2)D_(0,2)
 D_(w,2)D_(0,3)
 D_(w,2)D_(0,4)
 D_(w,2)D_(0,5)
 D_(w,2)D_(1,0)
 D_(w,2)D_(1,1)
 D_(w,2)D_(1,2)
 D_(w,2)D_(1,3)
 D_(w,2)D_(1,4)
 D_(w,2)D_(1,5)
 D_(w,2)D_(w,0)
 D_(w,2)D_(w,1)
 D_(w,2)^2 - D_(w,2)
 D_(w,2)D_(w,3)
 D_(w,2)D_(w,4)
 D_(w,2)D_(w,5)
 D_(w,2)D_(w^2,0)
 D_(w,2)D_(w^2,1)
 D_(w,2)D_(w^2,2)
 D_(w,2)D_(w^2,3)
 D_(w,2)D_(w^2,4)
 D_(w,3)X0 - X0D_(1,2)
 D_(w,3)X1 - X1D_(w,2)
 D_(w,3)X2 - X2D_(0,2)
 D_(w,3)X3 - X3D_(w^2,2)
 D_(w,3)t - tD_(1,3)
 D_(w,3)x - xD_(w^2,3)
 D_(w,3)y - yD_(w,3)
 D_(w,3)z - zD_(w,3)
 D_(w,3)De
 D_(w,3)D_(0,1)
 D_(w,3)D_(0,2)
 D_(w,3)D_(0,3)
 D_(w,3)D_(0,4)
 D_(w,3)D_(0,5)
 D_(w,3)D_(1,0)
 D_(w,3)D_(1,1)
 D_(w,3)D_(1,2)
 D_(w,3)D_(1,3)
 D_(w,3)D_(1,4)
 D_(w,3)D_(1,5)
 D_(w,3)D_(w,0)
 D_(w,3)D_(w,1)
 D_(w,3)D_(w,2)
 D_(w,3)^2 - D_(w,3)
 D_(w,3)D_(w,4)
 D_(w,3)D_(w,5)
 D_(w,3)D_(w^2,0)
 D_(w,3)D_(w^2,1)
 D_(w,3)D_(w^2,2)
 D_(w,3)D_(w^2,3)
 D_(w,3)D_(w^2,4)
 D_(w,4)X0 - X0D_(1,3)
 D_(w,4)X1 - X1D_(w,3)
 D_(w,4)X2 - X2D_(0,3)
 D_(w,4)X3 - X3D_(w^2,3)
 D_(w,4)t - tD_(1,4)
 D_(w,4)x - xD_(w^2,4)
 D_(w,4)y - yD_(w^2,4)
 D_(w,4)z - zD_(1,4)
 D_(w,4)De
 D_(w,4)D_(0,1)
 D_(w,4)D_(0,2)
 D_(w,4)D_(0,3)
 D_(w,4)D_(0,4)
 D_(w,4)D_(0,5)
 D_(w,4)D_(1,0)
 D_(w,4)D_(1,1)
 D_(w,4)D_(1,2)
 D_(w,4)D_(1,3)
 D_(w,4)D_(1,4)
 D_(w,4)D_(1,5)
 D_(w,4)D_(w,0)
 D_(w,4)D_(w,1)
 D_(w,4)D_(w,2)
 D_(w,4)D_(w,3)
 D_(w,4)^2 - D_(w,4)
 D_(w,4)D_(w,5)
 D_(w,4)D_(w^2,0)
 D_(w,4)D_(w^2,1)
 D_(w,4)D_(w^2,2)
 D_(w,4)D_(w^2,3)
 D_(w,4)D_(w^2,4)
 D_(w,5)X0 - X0D_(1,4)
 D_(w,5)X1 - X1D_(w,4)
 D_(w,5)X2 - X2D_(0,4)
 D_(w,5)X3 - X3D_(w^2,4)
 D_(w,5)t - tD_(1,5)
 D_(w,5)x + xD_(w^2,4) + xD_(w^2,3) + xD_(w^2,2) + xD_(w^2,1) + xD_(w^2,0) + x\
D_(w,5) + xD_(w,4) + xD_(w,3) + xD_(w,2) + xD_(w,1) + xD_(w,0) + xD_(1,5) + xD\
_(1,4) + xD_(1,3) + xD_(1,2) + xD_(1,1) + xD_(1,0) + xD_(0,5) + xD_(0,4) + xD_\
(0,3) + xD_(0,2) + xD_(0,1) + xDe - x
 D_(w,5)y - yD_(1,5)
 D_(w,5)z - zD_(0,5)
 D_(w,5)De
 D_(w,5)D_(0,1)
 D_(w,5)D_(0,2)
 D_(w,5)D_(0,3)
 D_(w,5)D_(0,4)
 D_(w,5)D_(0,5)
 D_(w,5)D_(1,0)
 D_(w,5)D_(1,1)
 D_(w,5)D_(1,2)
 D_(w,5)D_(1,3)
 D_(w,5)D_(1,4)
 D_(w,5)D_(1,5)
 D_(w,5)D_(w,0)
 D_(w,5)D_(w,1)
 D_(w,5)D_(w,2)
 D_(w,5)D_(w,3)
 D_(w,5)D_(w,4)
 D_(w,5)^2 - D_(w,5)
 D_(w,5)D_(w^2,0)
 D_(w,5)D_(w^2,1)
 D_(w,5)D_(w^2,2)
 D_(w,5)D_(w^2,3)
 D_(w,5)D_(w^2,4)
 D_(w^2,0)X0 - X0D_(w,5)
 D_(w^2,0)X1 - X1D_(1,5)
 D_(w^2,0)X2 + X2D_(w^2,4) + X2D_(w^2,3) + X2D_(w^2,2) + X2D_(w^2,1) + X2D_(w^\
2,0) + X2D_(w,5) + X2D_(w,4) + X2D_(w,3) + X2D_(w,2) + X2D_(w,1) + X2D_(w,0) +\
 X2D_(1,5) + X2D_(1,4) + X2D_(1,3) + X2D_(1,2) + X2D_(1,1) + X2D_(1,0) + X2D_(\
0,5) + X2D_(0,4) + X2D_(0,3) + X2D_(0,2) + X2D_(0,1) + X2De - X2
 D_(w^2,0)X3 - X3D_(0,5)
 D_(w^2,0)t - tD_(w,0)
 D_(w^2,0)x - xD_(1,0)
 D_(w^2,0)y - yD_(w^2,0)
 D_(w^2,0)z - zD_(w^2,0)
 D_(w^2,0)De
 D_(w^2,0)D_(0,1)
 D_(w^2,0)D_(0,2)
 D_(w^2,0)D_(0,3)
 D_(w^2,0)D_(0,4)
 D_(w^2,0)D_(0,5)
 D_(w^2,0)D_(1,0)
 D_(w^2,0)D_(1,1)
 D_(w^2,0)D_(1,2)
 D_(w^2,0)D_(1,3)
 D_(w^2,0)D_(1,4)
 D_(w^2,0)D_(1,5)
 D_(w^2,0)D_(w,0)
 D_(w^2,0)D_(w,1)
 D_(w^2,0)D_(w,2)
 D_(w^2,0)D_(w,3)
 D_(w^2,0)D_(w,4)
 D_(w^2,0)D_(w,5)
 D_(w^2,0)^2 - D_(w^2,0)
 D_(w^2,0)D_(w^2,1)
 D_(w^2,0)D_(w^2,2)
 D_(w^2,0)D_(w^2,3)
 D_(w^2,0)D_(w^2,4)
 D_(w^2,1)X0 - X0D_(w,0)
 D_(w^2,1)X1 - X1D_(1,0)
 D_(w^2,1)X2 - X2D_(w^2,0)
 D_(w^2,1)X3 - X3De
 D_(w^2,1)t - tD_(w,1)
 D_(w^2,1)x - xD_(1,1)
 D_(w^2,1)y - yD_(w,1)
 D_(w^2,1)z - zD_(0,1)
 D_(w^2,1)De
 D_(w^2,1)D_(0,1)
 D_(w^2,1)D_(0,2)
 D_(w^2,1)D_(0,3)
 D_(w^2,1)D_(0,4)
 D_(w^2,1)D_(0,5)
 D_(w^2,1)D_(1,0)
 D_(w^2,1)D_(1,1)
 D_(w^2,1)D_(1,2)
 D_(w^2,1)D_(1,3)
 D_(w^2,1)D_(1,4)
 D_(w^2,1)D_(1,5)
 D_(w^2,1)D_(w,0)
 D_(w^2,1)D_(w,1)
 D_(w^2,1)D_(w,2)
 D_(w^2,1)D_(w,3)
 D_(w^2,1)D_(w,4)
 D_(w^2,1)D_(w,5)
 D_(w^2,1)D_(w^2,0)
 D_(w^2,1)^2 - D_(w^2,1)
 D_(w^2,1)D_(w^2,2)
 D_(w^2,1)D_(w^2,3)
 D_(w^2,1)D_(w^2,4)
 D_(w^2,2)X0 - X0D_(w,1)
 D_(w^2,2)X1 - X1D_(1,1)
 D_(w^2,2)X2 - X2D_(w^2,1)
 D_(w^2,2)X3 - X3D_(0,1)
 D_(w^2,2)t - tD_(w,2)
 D_(w^2,2)x - xD_(1,2)
 D_(w^2,2)y - yD_(0,2)
 D_(w^2,2)z - zD_(1,2)
 D_(w^2,2)De
 D_(w^2,2)D_(0,1)
 D_(w^2,2)D_(0,2)
 D_(w^2,2)D_(0,3)
 D_(w^2,2)D_(0,4)
 D_(w^2,2)D_(0,5)
 D_(w^2,2)D_(1,0)
 D_(w^2,2)D_(1,1)
 D_(w^2,2)D_(1,2)
 D_(w^2,2)D_(1,3)
 D_(w^2,2)D_(1,4)
 D_(w^2,2)D_(1,5)
 D_(w^2,2)D_(w,0)
 D_(w^2,2)D_(w,1)
 D_(w^2,2)D_(w,2)
 D_(w^2,2)D_(w,3)
 D_(w^2,2)D_(w,4)
 D_(w^2,2)D_(w,5)
 D_(w^2,2)D_(w^2,0)
 D_(w^2,2)D_(w^2,1)
 D_(w^2,2)^2 - D_(w^2,2)
 D_(w^2,2)D_(w^2,3)
 D_(w^2,2)D_(w^2,4)
 D_(w^2,3)X0 - X0D_(w,2)
 D_(w^2,3)X1 - X1D_(1,2)
 D_(w^2,3)X2 - X2D_(w^2,2)
 D_(w^2,3)X3 - X3D_(0,2)
 D_(w^2,3)t - tD_(w,3)
 D_(w^2,3)x - xD_(1,3)
 D_(w^2,3)y - yD_(w^2,3)
 D_(w^2,3)z - zD_(w^2,3)
 D_(w^2,3)De
 D_(w^2,3)D_(0,1)
 D_(w^2,3)D_(0,2)
 D_(w^2,3)D_(0,3)
 D_(w^2,3)D_(0,4)
 D_(w^2,3)D_(0,5)
 D_(w^2,3)D_(1,0)
 D_(w^2,3)D_(1,1)
 D_(w^2,3)D_(1,2)
 D_(w^2,3)D_(1,3)
 D_(w^2,3)D_(1,4)
 D_(w^2,3)D_(1,5)
 D_(w^2,3)D_(w,0)
 D_(w^2,3)D_(w,1)
 D_(w^2,3)D_(w,2)
 D_(w^2,3)D_(w,3)
 D_(w^2,3)D_(w,4)
 D_(w^2,3)D_(w,5)
 D_(w^2,3)D_(w^2,0)
 D_(w^2,3)D_(w^2,1)
 D_(w^2,3)D_(w^2,2)
 D_(w^2,3)^2 - D_(w^2,3)
 D_(w^2,3)D_(w^2,4)
 D_(w^2,4)X0 - X0D_(w,3)
 D_(w^2,4)X1 - X1D_(1,3)
 D_(w^2,4)X2 - X2D_(w^2,3)
 D_(w^2,4)X3 - X3D_(0,3)
 D_(w^2,4)t - tD_(w,4)
 D_(w^2,4)x - xD_(1,4)
 D_(w^2,4)y - yD_(w,4)
 D_(w^2,4)z - zD_(0,4)
 D_(w^2,4)De
 D_(w^2,4)D_(0,1)
 D_(w^2,4)D_(0,2)
 D_(w^2,4)D_(0,3)
 D_(w^2,4)D_(0,4)
 D_(w^2,4)D_(0,5)
 D_(w^2,4)D_(1,0)
 D_(w^2,4)D_(1,1)
 D_(w^2,4)D_(1,2)
 D_(w^2,4)D_(1,3)
 D_(w^2,4)D_(1,4)
 D_(w^2,4)D_(1,5)
 D_(w^2,4)D_(w,0)
 D_(w^2,4)D_(w,1)
 D_(w^2,4)D_(w,2)
 D_(w^2,4)D_(w,3)
 D_(w^2,4)D_(w,4)
 D_(w^2,4)D_(w,5)
 D_(w^2,4)D_(w^2,0)
 D_(w^2,4)D_(w^2,1)
 D_(w^2,4)D_(w^2,2)
 D_(w^2,4)D_(w^2,3)
 D_(w^2,4)^2 - D_(w^2,4)
 X1X0X1 - X0X1X0
 X2X1X2 - X1X2X1
 tyz - zt
 tzt - yx
 x^3 - 1
 xyz - yx
 xzt - tyx
 yx^2 - x^2z
 yxy - xz
 yxz - xy
 yzt - ty
 ztx - txz
 zty - tz
 ztz - ty
 x^2yx - yz
 X2X1X0X2X1X0 + X1X0X2X1X0X2 + X0X2X1X0X2X1

In [284]:
DimQA(J_D_ge_0, 36);

41472

In [285]:
72*24^2;

41472

## Relaciones dadas de la definción de $\mathfrak{D}$,
$$
\begin{aligned}
y_{(ij)} x_{(ij)} + x_{(ij)} y_{(ij)} &= 1 + (ij)(\delta_{(ij)} - \delta_e), \\
y_{(ik)} x_{(ij)} + x_{(ij)} y_{(jk)} &= (ij)(\delta_{(ik)} - \delta_{(ik)(ij)}),
\end{aligned}
$$
para todas las transposiciones $(ij), (ik) \in \mathbb{S}_{3}$.

- Relaciones del tipo $y_{(ij)}x_{(ij)} + x_{(ij)}y_{(ij)} = 1 + (ij)(\delta_{(ij)} - \delta_e)$:
$$
\begin{aligned}
y_{(12)}x_{(12)} + x_{(12)}y_{(12)} &= 1 + (12)(\delta_{(12)} - \delta_e),\\
y_{(13)}x_{(13)} + x_{(13)}y_{(13)} &= 1 + (13)(\delta_{(13)} - \delta_e),\\
y_{(23)}x_{(23)} + x_{(23)}y_{(23)} &= 1 + (23)(\delta_{(23)} - \delta_e),
\end{aligned}
$$

- Relaciones del tipo $y_{(ik)}x_{(ij)} + x_{(ij)}y_{(jk)} = (ij)(\delta_{(ik)} - \delta_{(ik)(ij)})$:
$$
\begin{aligned}
y_{(13)}x_{(12)} + x_{(12)}y_{(23)} &= (12)(\delta_{(13)} - \delta_{(123)}),\\
y_{(23)}x_{(12)} + x_{(12)}y_{(13)} &= (12)(\delta_{(23)} - \delta_{(132)}),\\
y_{(12)}x_{(13)} + x_{(13)}y_{(23)} &= (13)(\delta_{(12)} - \delta_{(132)}),\\
y_{(23)}x_{(13)} + x_{(13)}y_{(12)} &= (13)(\delta_{(23)} - \delta_{(123)}),\\
y_{(12)}x_{(23)} + x_{(23)}y_{(13)} &= (23)(\delta_{(12)} - \delta_{(123)}),\\
y_{(13)}x_{(23)} + x_{(23)}y_{(12)} &= (23)(\delta_{(13)} - \delta_{(132)}).
\end{aligned}
$$

In [286]:
PrintNP(GetConmutationRules(gensA[2], gensA[2]));

 Y1X1 + X1Y1 - 1 + ztDe - ztD_(0,3) - ztD_(1,1) + ztD_(1,4) + ztD_(w^2,2) - zt\
D_(w^2,5)

In [288]:
relsQG:=[];;
for i in gensA do
    for j in gensA do
       resl_ij := GetConmutationRules(i, j);;
       Add(relsQG, resl_ij);
    od;
od;

In [290]:
Print("Total relations generated: ", Length(relsQG), ".\n");
PrintNPList(relsQG);

Total relations generated: 16.
 Y0X0 + X0Y0 - 1 + tDe - tD_(0,1) + tD_(0,2) - tD_(0,3) + tD_(0,4) - tD_(0,5)
 Y1X0 + X0Y3 + tD_(1,0) - tD_(1,1) + tD_(1,2) - tD_(1,3) + tD_(1,4) - tD_(1,5)\

 Y2X0 + X0Y1 + tD_(w,0) - tD_(w,1) + tD_(w,2) - tD_(w,3) + tD_(w,4) - tD_(w,5)\

 Y3X0 + X0Y2 + tD_(w^2,0) - tD_(w^2,1) + tD_(w^2,2) - tD_(w^2,3) + tD_(w^2,4) \
- tD_(w^2,5)
 Y0X1 + X1Y2 + ztD_(w,2) - ztD_(w,5) + ztD_(1,0) - ztD_(1,3) - ztD_(0,1) + ztD\
_(0,4)
 Y1X1 + X1Y1 - 1 + ztDe - ztD_(0,3) - ztD_(1,1) + ztD_(1,4) + ztD_(w^2,2) - zt\
D_(w^2,5)
 Y2X1 + X1Y3 - ztD_(w,1) + ztD_(w,4) + ztD_(w^2,0) - ztD_(w^2,3) + ztD_(0,2) -\
 ztD_(0,5)
 Y3X1 + X1Y0 + ztD_(1,2) - ztD_(1,5) - ztD_(w^2,1) + ztD_(w^2,4) + ztD_(w,0) -\
 ztD_(w,3)
 Y0X2 + X2Y3 - tzD_(0,1) + tzD_(0,4) + tzD_(w^2,2) - tzD_(w^2,5) + tzD_(w,0) -\
 tzD_(w,3)
 Y1X2 + X2Y0 + tzD_(w,2) - tzD_(w,5) + tzD_(w^2,0) - tzD_(w^2,3) - tzD_(1,1) +\
 tzD_(1,4)
 Y2X2 + X2Y2 - 1 + tzDe - tzD_(0,3) + tzD_(1,2) - tzD_(1,5) - tzD_(w,1) + tzD_\
(w,4)
 Y3X2 + X2Y1 - tzD_(w^2,1) + tzD_(w^2,4) + tzD_(1,0) - tzD_(1,3) + tzD_(0,2) -\
 tzD_(0,5)
 Y0X3 + X3Y1 + tyD_(w^2,0) - tyD_(w^2,3) - tyD_(0,1) + tyD_(0,4) + tyD_(1,2) -\
 tyD_(1,5)
 Y1X3 + X3Y2 - tyD_(1,1) + tyD_(1,4) + tyD_(0,2) - tyD_(0,5) + tyD_(w,0) - tyD\
_(w,3)
 Y2X3 + X3Y0 + tyD_(w^2,2) - tyD_(w^2,5) - tyD_(w,1) + tyD_(w,4) + tyD_(1,0) -\
 tyD_(1,3)
 Y3X3 + X3Y3 - 1 + tyDe - tyD_(0,3) + tyD_(w,2) - tyD_(w,5) - tyD_(w^2,1) + ty\
D_(w^2,4)

Para concluir, afirmamos que los elementos de $V$ y $\overline{V}$ satisfacen la relación \eqref{4.5}.
En efecto, si $x \in V$ e $y \in \overline{V}$, se cumple que
$$
yx - (y_{(-1)} \cdot x)y_{(0)} =  \langle y, x \rangle - \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
por \eqref{3.5}. Por otro lado, la regla de conmutación \eqref{3.4} implica que
$$
y_{(-1)}x_{(-1)} \langle y_{(0)}, x_{(0)} \rangle = \langle y_{(-2)}, x_{(-3)} \rangle \langle y_{(0)}, \mathcal{S}(x_{(-1)}) \cdot x_{(0)} \rangle x_{(-2)}y_{(-1)}
$$
donde $\langle y_{(-2)}, x_{(-3)} \rangle$ denota el emparejamiento \eqref{3.2}; comparar con \cite[eq.~(21)]{33}. \qed

In [290]:
I := Concatenation(
    relsT4,       #  rels
    relsGroup,    #  rels
    relskG,       #  rels
    relsDG,       #  rels
    relsxBos,     # 96 rels
    relsDx,       # 96 rels
    relsDy,       # 96 rels
    relsyBos,     # 96 rels
    relsQG,       # 16 rels
    relsT4dual    #  rels
);;

In [292]:
Length(I);

1578

In [293]:
QGNAG.Config.PROD;

false

In [294]:
if QGNAG.Config.PROD then
    J := SGrobner( I );;
fi;

In [295]:

if QGNAG.Config.PROD then
    dimD := DimQA(J, 36);
    Print("DimQA(J, 36) = ", String(72 * 24 * 24 * 72), " is ", 72 * 24 * 24 * 72 = dimD);
fi;

## Data

In [296]:
if QGNAG.Config.PROD then
    Y0bis:=[];; 
    for bi in Base_T4 do
        prod := StrongNormalFormNP(MulNP(GP2NP(Y0), bi), J);
        Add(Y0bis, rec(bi := bi, prod := prod, yj := GP2NP(Y0)));
    od;
fi;

In [297]:
if QGNAG.Config.PROD then
    Y1bis:=[];; 
    for bi in Base_T4 do
        prod := StrongNormalFormNP(MulNP(GP2NP(Y1), bi), J);
        Add(Y1bis, rec(bi := bi, prod := prod, yj := GP2NP(Y1)));
    od;
fi;

In [298]:
if QGNAG.Config.PROD then
    Y2bis:=[];; 
    for bi in Base_T4 do
        prod := StrongNormalFormNP(MulNP(GP2NP(Y2), bi), J);
        Add(Y2bis, rec(bi := bi, prod := prod, yj := GP2NP(Y2)));
    od;
fi;

In [299]:
if QGNAG.Config.PROD then
    Y2bis:=[];; 
    for bi in Base_T4 do
        prod := StrongNormalFormNP(MulNP(GP2NP(Y3), bi), J);
        Add(Y3bis, rec(bi := bi, prod := prod, yj := GP2NP(Y3)));
    od;
fi;

In [300]:
PrintNPList(List(Y0bis, ys -> ys.prod));

 Y0
 tD_(0,5) - tD_(0,4) + tD_(0,3) - tD_(0,2) + tD_(0,1) - tDe - X0Y0 + 1
 Y0X1
 Y0X2
 Y0X3
 - 2X2tD_(w^2,4) - 2X2tD_(w^2,2) - 2X2tD_(w^2,0) - X2tD_(w,5) - X2tD_(w,4) - X\
2tD_(w,3) - X2tD_(w,2) - X2tD_(w,1) - X2tD_(w,0) - X2tD_(1,5) - X2tD_(1,4) - X\
2tD_(1,3) - X2tD_(1,2) - X2tD_(1,1) - X2tD_(1,0) - X2tD_(0,5) - X2tD_(0,4) - X\
2tD_(0,3) - X2tD_(0,2) - X2tD_(0,1) - X2tDe - X0Y0X1 + X2t + X1
 X3tD_(1,5) - X3tD_(1,4) + X3tD_(1,3) - X3tD_(1,2) + X3tD_(1,1) - X3tD_(1,0) -\
 X0Y0X2 + X2
 X1tD_(w,5) - X1tD_(w,4) + X1tD_(w,3) - X1tD_(w,2) + X1tD_(w,1) - X1tD_(w,0) -\
 X0Y0X3 + X3
 X3Y1X1 - X1tD_(w,5) + X1tD_(w,4) - X1tD_(w,3) + X1tD_(w,2) - X1tD_(w,1) + X1t\
D_(w,0) - X0X3Y1 - X3
 - X1Y2X2 + X0Y0X1 + X0X1Y2
 X2Y3X1 + X2X1Y0 - X1Y2X3
 X3Y1X2 - X2Y3X1 - X2X1Y0 - X1X3Y0
 - X2Y3X3 + X0Y0X2 + X0X2Y3
 - X1X2tD_(w,5) + X1X2tD_(w,4) - X1X2tD_(w,3) + X1X2tD_(w,2) - X1X2tD_(w,1) + \
X1X2tD_(w,0) - X0X3Y1X1 + X1X0 + X0X3
 - 2X2X3tD_(w^2,4) - 2X2X3tD_(w^2,2) - 2X2X3tD_(w^2,0) - X2X3tD_(w,5) - X2X3tD\
_(w,4) - X2X3tD_(w,3) - X2X3tD_(w,2) - X2X3tD_(w,1) - X2X3tD_(w,0) - X2X3tD_(1\
,5) - X2X3tD_(1,4) - X2X3tD_(1,3) - X2X3tD_(1,2) - X2X3tD_(1,1) - X2X3tD_(1,0)\
 - X2X3tD_(0,5) - X2X3tD_(0,4) - X2X3tD_(0,3) - X2X3tD_(0,2) - X2X3tD_(0,1) - \
X2X3tDe + X0X1Y2X2 + X2X3t + X1X2
 X2X1tD_(0,5) - X2X1tD_(0,4) + X2X1tD_(0,3) - X2X1tD_(0,2) + X2X1tD_(0,1) - X2\
X1tDe - X0X2Y3X1 - X0X2X1Y0 + X0X1Y2X3 + X1X3
 - X2X1tD_(0,5) + X2X1tD_(0,4) - X2X1tD_(0,3) + X2X1tD_(0,2) - X2X1tD_(0,1) + \
X2X1tDe - X1X3tD_(0,5) + X1X3tD_(0,4) - X1X3tD_(0,3) + X1X3tD_(0,2) - X1X3tD_(\
0,1) + X1X3tDe - X0X3Y1X2 + X0X2Y3X1 + X0X2X1Y0 + X0X1X3Y0 + X2X1
 - X1X0tD_(1,5) + X1X0tD_(1,4) - X1X0tD_(1,3) + X1X0tD_(1,2) - X1X0tD_(1,1) + \
X1X0tD_(1,0) - X0X3tD_(1,5) + X0X3tD_(1,4) - X0X3tD_(1,3) + X0X3tD_(1,2) - X0X\
3tD_(1,1) + X0X3tD_(1,0) + X0X2Y3X3 + X2X3
 - X2X3Y3X1 + X2X1X0Y0 - X1X3tD_(0,5) + X1X3tD_(0,4) - X1X3tD_(0,3) + X1X3tD_(\
0,2) - X1X3tD_(0,1) + X1X3tDe - X1X2X3Y0 + X1X0Y1X2 - X0X2Y3X1 - X0X2X1Y0 - X0\
X1X3Y0
 - X2X1Y0X1 - X1X3Y0X1 + X1X0Y1X3 + X1X0X3Y2
 - X1X3Y0X2 + X1X2Y2X1 + X1X2X1Y3 + X0X1Y2X1
 X1X2Y2X3 - X1X0Y1X2 - X1X0X2Y0 + X0X2Y3X1 + X0X2X1Y0 - X1X3
 - X2X3Y3X1 + X2X1tD_(0,5) - X2X1tD_(0,4) + X2X1tD_(0,3) - X2X1tD_(0,2) + X2X1\
tD_(0,1) - X2X1tDe - X1X2X3Y0 - X1X0Y1X2 - X1X0X2Y0 - X0X3Y1X2 + X0X2X1Y0 + X2\
X1
 - X2X3Y3X2 + X2X1Y0X3 + X2X1X3Y1 - X0X2Y3X2
 - X1X2X3tD_(0,5) + X1X2X3tD_(0,4) - X1X2X3tD_(0,3) + X1X2X3tD_(0,2) - X1X2X3t\
D_(0,1) + X1X2X3tDe + X0X2X3Y3X1 - X0X2X1X0Y0 + X0X1X2X3Y0 - X0X1X0Y1X2 + X1X0\
X2
 2X1X2X1tD_(w^2,4) + 2X1X2X1tD_(w^2,2) + 2X1X2X1tD_(w^2,0) + X1X2X1tD_(w,5) + \
X1X2X1tD_(w,4) + X1X2X1tD_(w,3) + X1X2X1tD_(w,2) + X1X2X1tD_(w,1) + X1X2X1tD_(\
w,0) + X1X2X1tD_(1,5) + X1X2X1tD_(1,4) + X1X2X1tD_(1,3) + X1X2X1tD_(1,2) + X1X\
2X1tD_(1,1) + X1X2X1tD_(1,0) + X1X2X1tD_(0,5) + X1X2X1tD_(0,4) + X1X2X1tD_(0,3\
) + X1X2X1tD_(0,2) + X1X2X1tD_(0,1) + X1X2X1tDe + X0X2X1Y0X1 + X0X1X3Y0X1 - X0\
X1X0Y1X3 - X0X1X0X3Y2 - X1X2X1t + X1X0X3
 - X2X1X3tD_(1,5) + X2X1X3tD_(1,4) - X2X1X3tD_(1,3) + X2X1X3tD_(1,2) - X2X1X3t\
D_(1,1) + X2X1X3tD_(1,0) + X0X1X3Y0X2 - X0X1X2Y2X1 - X0X1X2X1Y3 + X1X2X1
 - X2X1X0tD_(0,5) + X2X1X0tD_(0,4) - X2X1X0tD_(0,3) + X2X1X0tD_(0,2) - X2X1X0t\
D_(0,1) + X2X1X0tDe + X1X2X3tD_(0,5) - X1X2X3tD_(0,4) + X1X2X3tD_(0,3) - X1X2X\
3tD_(0,2) + X1X2X3tD_(0,1) - X1X2X3tDe + X0X1X3tD_(0,5) - X0X1X3tD_(0,4) + X0X\
1X3tD_(0,3) - X0X1X3tD_(0,2) + X0X1X3tD_(0,1) - X0X1X3tDe - X0X1X2Y2X3 + X0X1X\
0Y1X2 + X0X1X0X2Y0 + X1X2X3 + X0X1X3
 - X2X1X0tD_(0,5) + X2X1X0tD_(0,4) - X2X1X0tD_(0,3) + X2X1X0tD_(0,2) - X2X1X0t\
D_(0,1) + X2X1X0tDe + X1X2X3tD_(0,5) - X1X2X3tD_(0,4) + X1X2X3tD_(0,3) - X1X2X\
3tD_(0,2) + X1X2X3tD_(0,1) - X1X2X3tDe + X1X0X2tD_(0,5) - X1X0X2tD_(0,4) + X1X\
0X2tD_(0,3) - X1X0X2tD_(0,2) + X1X0X2tD_(0,1) - X1X0X2tDe + X0X2X3Y3X1 - X0X2X\
1tD_(0,5) + X0X2X1tD_(0,4) - X0X2X1tD_(0,3) + X0X2X1tD_(0,2) - X0X2X1tD_(0,1) \
+ X0X2X1tDe + X0X1X2X3Y0 + X0X1X0Y1X2 + X0X1X0X2Y0 + X2X1X0 - X0X2X1
 X1X0X3tD_(w,5) - X1X0X3tD_(w,4) + X1X0X3tD_(w,3) - X1X0X3tD_(w,2) + X1X0X3tD_\
(w,1) - X1X0X3tD_(w,0) + X0X2X3Y3X2 - X0X2X1Y0X3 - X0X2X1X3Y1 + X2X1X3
 X2X1X0Y0X1 - X1X2X3Y0X1 - 2X1X2X1tD_(w^2,4) - 2X1X2X1tD_(w^2,2) - 2X1X2X1tD_(\
w^2,0) - X1X2X1tD_(w,5) - X1X2X1tD_(w,4) - X1X2X1tD_(w,3) - X1X2X1tD_(w,2) - X\
1X2X1tD_(w,1) - X1X2X1tD_(w,0) - X1X2X1tD_(1,5) - X1X2X1tD_(1,4) - X1X2X1tD_(1\
,3) - X1X2X1tD_(1,2) - X1X2X1tD_(1,1) - X1X2X1tD_(1,0) - X1X2X1tD_(0,5) - X1X2\
X1tD_(0,4) - X1X2X1tD_(0,3) - X1X2X1tD_(0,2) - X1X2X1tD_(0,1) - X1X2X1tDe + X1\
X0X3Y2X2 - X1X0X2Y0X1 - X1X0X2X1Y2 - X0X2X1Y0X1 - X0X1X3Y0X1 - X0X1X0X3Y2 + X1\
X2X1t - X1X0X3
 X2X1X3Y1X1 - X2X1X0X3Y1 + X1X0X3tD_(w,5) - X1X0X3tD_(w,4) + X1X0X3tD_(w,3) - \
X1X0X3tD_(w,2) + X1X0X3tD_(w,1) - X1X0X3tD_(w,0) - X1X0X2Y0X3 - X2X1X3
 X1X2X3Y0X1 + 2X1X2X1tD_(w^2,4) + 2X1X2X1tD_(w^2,2) + 2X1X2X1tD_(w^2,0) + X1X2\
X1tD_(w,5) + X1X2X1tD_(w,4) + X1X2X1tD_(w,3) + X1X2X1tD_(w,2) + X1X2X1tD_(w,1)\
 + X1X2X1tD_(w,0) + X1X2X1tD_(1,5) + X1X2X1tD_(1,4) + X1X2X1tD_(1,3) + X1X2X1t\
D_(1,2) + X1X2X1tD_(1,1) + X1X2X1tD_(1,0) + X1X2X1tD_(0,5) + X1X2X1tD_(0,4) + \
X1X2X1tD_(0,3) + X1X2X1tD_(0,2) + X1X2X1tD_(0,1) + X1X2X1tDe + X1X0X3Y2X2 - X1\
X0X2X1Y2 + X0X1X3Y0X1 - X0X1X0X3Y2 - X1X2X1t - X1X0X3
 X1X2X3Y0X2 - X1X2X1Y3X3 - X1X2X1X3Y3 + X1X0X2Y0X2 + X0X1X2Y2X1 + X0X1X2X1Y3
 X2X1X3tD_(1,5) - X2X1X3tD_(1,4) + X2X1X3tD_(1,3) - X2X1X3tD_(1,2) + X2X1X3tD_\
(1,1) - X2X1X3tD_(1,0) - X2X1X0Y0X2 - X1X0X2Y0X2 + X0X2X1Y0X2 + X0X1X3Y0X2 - X\
0X1X2Y2X1 - X0X1X2X1Y3 + X1X2X1
 X2X1X3Y1X1 - X2X1X0Y0X3 - X2X1X0X3Y1 + X0X2X3Y3X2 - X0X2X1X3Y1
 - 2X1X2X1X3tD_(w^2,4) - 2X1X2X1X3tD_(w^2,2) - 2X1X2X1X3tD_(w^2,0) - X1X2X1X3t\
D_(w,5) - X1X2X1X3tD_(w,4) - X1X2X1X3tD_(w,3) - X1X2X1X3tD_(w,2) - X1X2X1X3tD_\
(w,1) - X1X2X1X3tD_(w,0) - X1X2X1X3tD_(1,5) - X1X2X1X3tD_(1,4) - X1X2X1X3tD_(1\
,3) - X1X2X1X3tD_(1,2) - X1X2X1X3tD_(1,1) - X1X2X1X3tD_(1,0) - X1X2X1X3tD_(0,5\
) - X1X2X1X3tD_(0,4) - X1X2X1X3tD_(0,3) - X1X2X1X3tD_(0,2) - X1X2X1X3tD_(0,1) \
- X1X2X1X3tDe - X0X2X1X0Y0X1 + X0X1X2X3Y0X1 - X0X1X0X3Y2X2 + X0X1X0X2Y0X1 + X0\
X1X0X2X1Y2 + X1X2X1X3t + X1X0X2X1 + X0X1X0X3
 X1X2X1X0tD_(w,5) - X1X2X1X0tD_(w,4) + X1X2X1X0tD_(w,3) - X1X2X1X0tD_(w,2) + X\
1X2X1X0tD_(w,1) - X1X2X1X0tD_(w,0) - X0X2X1X3Y1X1 + X0X2X1X0X3Y1 - X0X1X0X3tD_\
(w,5) + X0X1X0X3tD_(w,4) - X0X1X0X3tD_(w,3) + X0X1X0X3tD_(w,2) - X0X1X0X3tD_(w\
,1) + X0X1X0X3tD_(w,0) + X0X1X0X2Y0X3 + X1X0X2X3 + X0X2X1X3
 - 2X2X1X0X2tD_(w^2,4) - 2X2X1X0X2tD_(w^2,2) - 2X2X1X0X2tD_(w^2,0) - X2X1X0X2t\
D_(w,5) - X2X1X0X2tD_(w,4) - X2X1X0X2tD_(w,3) - X2X1X0X2tD_(w,2) - X2X1X0X2tD_\
(w,1) - X2X1X0X2tD_(w,0) - X2X1X0X2tD_(1,5) - X2X1X0X2tD_(1,4) - X2X1X0X2tD_(1\
,3) - X2X1X0X2tD_(1,2) - X2X1X0X2tD_(1,1) - X2X1X0X2tD_(1,0) - X2X1X0X2tD_(0,5\
) - X2X1X0X2tD_(0,4) - X2X1X0X2tD_(0,3) - X2X1X0X2tD_(0,2) - X2X1X0X2tD_(0,1) \
- X2X1X0X2tDe - 2X1X2X1X3tD_(w^2,4) - 2X1X2X1X3tD_(w^2,2) - 2X1X2X1X3tD_(w^2,0\
) - X1X2X1X3tD_(w,5) - X1X2X1X3tD_(w,4) - X1X2X1X3tD_(w,3) - X1X2X1X3tD_(w,2) \
- X1X2X1X3tD_(w,1) - X1X2X1X3tD_(w,0) - X1X2X1X3tD_(1,5) - X1X2X1X3tD_(1,4) - \
X1X2X1X3tD_(1,3) - X1X2X1X3tD_(1,2) - X1X2X1X3tD_(1,1) - X1X2X1X3tD_(1,0) - X1\
X2X1X3tD_(0,5) - X1X2X1X3tD_(0,4) - X1X2X1X3tD_(0,3) - X1X2X1X3tD_(0,2) - X1X2\
X1X3tD_(0,1) - X1X2X1X3tDe - X0X1X2X3Y0X1 - 2X0X1X2X1tD_(w^2,4) - 2X0X1X2X1tD_\
(w^2,2) - 2X0X1X2X1tD_(w^2,0) - X0X1X2X1tD_(w,5) - X0X1X2X1tD_(w,4) - X0X1X2X1\
tD_(w,3) - X0X1X2X1tD_(w,2) - X0X1X2X1tD_(w,1) - X0X1X2X1tD_(w,0) - X0X1X2X1tD\
_(1,5) - X0X1X2X1tD_(1,4) - X0X1X2X1tD_(1,3) - X0X1X2X1tD_(1,2) - X0X1X2X1tD_(\
1,1) - X0X1X2X1tD_(1,0) - X0X1X2X1tD_(0,5) - X0X1X2X1tD_(0,4) - X0X1X2X1tD_(0,\
3) - X0X1X2X1tD_(0,2) - X0X1X2X1tD_(0,1) - X0X1X2X1tDe - X0X1X0X3Y2X2 + X0X1X0\
X2X1Y2 + X2X1X0X2t + X1X2X1X3t + X0X1X2X1t + X1X2X1X0 + X0X1X0X3
 X2X1X0X3tD_(1,5) - X2X1X0X3tD_(1,4) + X2X1X0X3tD_(1,3) - X2X1X0X3tD_(1,2) + X\
2X1X0X3tD_(1,1) - X2X1X0X3tD_(1,0) - X0X1X2X3Y0X2 + X0X1X2X1Y3X3 + X0X1X2X1X3Y\
3 - X0X1X0X2Y0X2 + X1X2X1X3
 - X2X1X0X3tD_(1,5) + X2X1X0X3tD_(1,4) - X2X1X0X3tD_(1,3) + X2X1X0X3tD_(1,2) -\
 X2X1X0X3tD_(1,1) + X2X1X0X3tD_(1,0) + X1X0X2X3tD_(1,5) - X1X0X2X3tD_(1,4) + X\
1X0X2X3tD_(1,3) - X1X0X2X3tD_(1,2) + X1X0X2X3tD_(1,1) - X1X0X2X3tD_(1,0) - X0X\
2X1X3tD_(1,5) + X0X2X1X3tD_(1,4) - X0X2X1X3tD_(1,3) + X0X2X1X3tD_(1,2) - X0X2X\
1X3tD_(1,1) + X0X2X1X3tD_(1,0) + X0X2X1X0Y0X2 + X0X1X0X2Y0X2 + X2X1X0X2 - X0X1\
X2X1
 X1X0X2X1tD_(w,5) - X1X0X2X1tD_(w,4) + X1X0X2X1tD_(w,3) - X1X0X2X1tD_(w,2) + X\
1X0X2X1tD_(w,1) - X1X0X2X1tD_(w,0) - X0X2X1X3Y1X1 + X0X2X1X0Y0X3 + X0X2X1X0X3Y\
1 + X0X1X0X3tD_(w,5) - X0X1X0X3tD_(w,4) + X0X1X0X3tD_(w,3) - X0X1X0X3tD_(w,2) \
+ X0X1X0X3tD_(w,1) - X0X1X0X3tD_(w,0) + X2X1X0X3
 X2X1X0X3Y1X1 + X1X2X1X0tD_(w,5) - X1X2X1X0tD_(w,4) + X1X2X1X0tD_(w,3) - X1X2X\
1X0tD_(w,2) + X1X2X1X0tD_(w,1) - X1X2X1X0tD_(w,0) - X1X0X2X3Y1X1 + X1X0X2X1tD_\
(w,5) - X1X0X2X1tD_(w,4) + X1X0X2X1tD_(w,3) - X1X0X2X1tD_(w,2) + X1X0X2X1tD_(w\
,1) - X1X0X2X1tD_(w,0) - X0X2X1X3Y1X1 + X0X2X1X0X3Y1 - X0X1X0X2X3Y1 - X2X1X0X3\
 + X1X0X2X3 + X0X2X1X3
 X2X1X0X2Y3X1 + X2X1X0X2X1Y0 + X1X2X1X3Y3X1 - X1X2X1X0X3Y0 - X1X0X2X3Y1X2 + X1\
X0X2X1Y2X3 + X1X0X2X1X3Y0
 2X1X2X1X3tD_(w^2,4) + 2X1X2X1X3tD_(w^2,2) + 2X1X2X1X3tD_(w^2,0) + X1X2X1X3tD_\
(w,5) + X1X2X1X3tD_(w,4) + X1X2X1X3tD_(w,3) + X1X2X1X3tD_(w,2) + X1X2X1X3tD_(w\
,1) + X1X2X1X3tD_(w,0) + X1X2X1X3tD_(1,5) + X1X2X1X3tD_(1,4) + X1X2X1X3tD_(1,3\
) + X1X2X1X3tD_(1,2) + X1X2X1X3tD_(1,1) + X1X2X1X3tD_(1,0) + X1X2X1X3tD_(0,5) \
+ X1X2X1X3tD_(0,4) + X1X2X1X3tD_(0,3) + X1X2X1X3tD_(0,2) + X1X2X1X3tD_(0,1) + \
X1X2X1X3tDe + X1X2X1X0Y2X2 - X1X0X2X1Y2X2 - X0X1X2X3Y0X1 + X0X1X2X1X0Y2 - X0X1\
X0X3Y2X2 - X1X2X1X3t + X1X0X2X1 + X0X1X0X3
 - X1X2X1X3Y3X1 + X1X2X1X0Y2X3 + X1X2X1X0X3Y0 - X1X0X2X3Y1X2 + X1X0X2X1X3Y0 - \
X0X1X2X1Y3X1
 - X2X1X0X3Y1X2 + X2X1X0X2Y3X1 + X2X1X0X2X1Y0 - X1X2X1X0X3Y0 - X1X0X2X3Y1X2 + \
X1X0X2X1X3Y0 + X0X2X1X3Y1X2 - X0X1X2X1Y3X1
 - X2X1X0X3tD_(1,5) + X2X1X0X3tD_(1,4) - X2X1X0X3tD_(1,3) + X2X1X0X3tD_(1,2) -\
 X2X1X0X3tD_(1,1) + X2X1X0X3tD_(1,0) + X2X1X0X2Y3X3 + X0X2X1X0Y0X2 + X0X2X1X0X\
2Y3 - X0X1X2X3Y0X2 + X0X1X2X1X3Y3 + X1X2X1X3
 - X1X2X1X0X2tD_(w,5) + X1X2X1X0X2tD_(w,4) - X1X2X1X0X2tD_(w,3) + X1X2X1X0X2tD\
_(w,2) - X1X2X1X0X2tD_(w,1) + X1X2X1X0X2tD_(w,0) - X0X2X1X0X3Y1X1 + X0X1X0X2X3\
Y1X1 - X0X1X0X2X1tD_(w,5) + X0X1X0X2X1tD_(w,4) - X0X1X0X2X1tD_(w,3) + X0X1X0X2\
X1tD_(w,2) - X0X1X0X2X1tD_(w,1) + X0X1X0X2X1tD_(w,0) + X1X0X2X1X0 + X0X2X1X0X3\
 - X0X1X0X2X3
 - X1X2X1X0X3tD_(0,5) + X1X2X1X0X3tD_(0,4) - X1X2X1X0X3tD_(0,3) + X1X2X1X0X3tD\
_(0,2) - X1X2X1X0X3tD_(0,1) + X1X2X1X0X3tDe - X0X2X1X0X2Y3X1 - X0X2X1X0X2X1Y0 \
- X0X1X2X1X3Y3X1 + X0X1X2X1X0X3Y0 + X0X1X0X2X3Y1X2 - X0X1X0X2X1Y2X3 - X0X1X0X2\
X1X3Y0 + X1X0X2X1X3
 - 2X2X1X0X2X3tD_(w^2,4) - 2X2X1X0X2X3tD_(w^2,2) - 2X2X1X0X2X3tD_(w^2,0) - X2X\
1X0X2X3tD_(w,5) - X2X1X0X2X3tD_(w,4) - X2X1X0X2X3tD_(w,3) - X2X1X0X2X3tD_(w,2)\
 - X2X1X0X2X3tD_(w,1) - X2X1X0X2X3tD_(w,0) - X2X1X0X2X3tD_(1,5) - X2X1X0X2X3tD\
_(1,4) - X2X1X0X2X3tD_(1,3) - X2X1X0X2X3tD_(1,2) - X2X1X0X2X3tD_(1,1) - X2X1X0\
X2X3tD_(1,0) - X2X1X0X2X3tD_(0,5) - X2X1X0X2X3tD_(0,4) - X2X1X0X2X3tD_(0,3) - \
X2X1X0X2X3tD_(0,2) - X2X1X0X2X3tD_(0,1) - X2X1X0X2X3tDe - 2X0X1X2X1X3tD_(w^2,4\
) - 2X0X1X2X1X3tD_(w^2,2) - 2X0X1X2X1X3tD_(w^2,0) - X0X1X2X1X3tD_(w,5) - X0X1X\
2X1X3tD_(w,4) - X0X1X2X1X3tD_(w,3) - X0X1X2X1X3tD_(w,2) - X0X1X2X1X3tD_(w,1) -\
 X0X1X2X1X3tD_(w,0) - X0X1X2X1X3tD_(1,5) - X0X1X2X1X3tD_(1,4) - X0X1X2X1X3tD_(\
1,3) - X0X1X2X1X3tD_(1,2) - X0X1X2X1X3tD_(1,1) - X0X1X2X1X3tD_(1,0) - X0X1X2X1\
X3tD_(0,5) - X0X1X2X1X3tD_(0,4) - X0X1X2X1X3tD_(0,3) - X0X1X2X1X3tD_(0,2) - X0\
X1X2X1X3tD_(0,1) - X0X1X2X1X3tDe - X0X1X2X1X0Y2X2 + X0X1X0X2X1Y2X2 + X2X1X0X2X\
3t + X0X1X2X1X3t + X1X2X1X0X2 - X0X1X0X2X1
 X2X1X0X2X1tD_(0,5) - X2X1X0X2X1tD_(0,4) + X2X1X0X2X1tD_(0,3) - X2X1X0X2X1tD_(\
0,2) + X2X1X0X2X1tD_(0,1) - X2X1X0X2X1tDe - X1X2X1X0X3tD_(0,5) + X1X2X1X0X3tD_\
(0,4) - X1X2X1X0X3tD_(0,3) + X1X2X1X0X3tD_(0,2) - X1X2X1X0X3tD_(0,1) + X1X2X1X\
0X3tDe + X0X1X2X1X3Y3X1 - X0X1X2X1X0Y2X3 - X0X1X2X1X0X3Y0 + X0X1X0X2X3Y1X2 - X\
0X1X0X2X1X3Y0 + X1X2X1X0X3
 X2X1X0X2X1tD_(0,5) - X2X1X0X2X1tD_(0,4) + X2X1X0X2X1tD_(0,3) - X2X1X0X2X1tD_(\
0,2) + X2X1X0X2X1tD_(0,1) - X2X1X0X2X1tDe - X1X2X1X0X3tD_(0,5) + X1X2X1X0X3tD_\
(0,4) - X1X2X1X0X3tD_(0,3) + X1X2X1X0X3tD_(0,2) - X1X2X1X0X3tD_(0,1) + X1X2X1X\
0X3tDe - X1X0X2X1X3tD_(0,5) + X1X0X2X1X3tD_(0,4) - X1X0X2X1X3tD_(0,3) + X1X0X2\
X1X3tD_(0,2) - X1X0X2X1X3tD_(0,1) + X1X0X2X1X3tDe + X0X2X1X0X3Y1X2 - X0X2X1X0X\
2Y3X1 - X0X2X1X0X2X1Y0 + X0X1X2X1X0X3Y0 + X0X1X0X2X3Y1X2 - X0X1X0X2X1X3Y0 + X2\
X1X0X2X1
 - X1X0X2X1X0tD_(1,5) + X1X0X2X1X0tD_(1,4) - X1X0X2X1X0tD_(1,3) + X1X0X2X1X0tD\
_(1,2) - X1X0X2X1X0tD_(1,1) + X1X0X2X1X0tD_(1,0) + X0X2X1X0X3tD_(1,5) - X0X2X1\
X0X3tD_(1,4) + X0X2X1X0X3tD_(1,3) - X0X2X1X0X3tD_(1,2) + X0X2X1X0X3tD_(1,1) - \
X0X2X1X0X3tD_(1,0) - X0X2X1X0X2Y3X3 + X0X1X0X2X3tD_(1,5) - X0X1X0X2X3tD_(1,4) \
+ X0X1X0X2X3tD_(1,3) - X0X1X0X2X3tD_(1,2) + X0X1X0X2X3tD_(1,1) - X0X1X0X2X3tD_\
(1,0) + X2X1X0X2X3 - X0X1X2X1X3
 - X2X1X0X2X3Y3X1 + X1X2X1X0X3tD_(0,5) - X1X2X1X0X3tD_(0,4) + X1X2X1X0X3tD_(0,\
3) - X1X2X1X0X3tD_(0,2) + X1X2X1X0X3tD_(0,1) - X1X2X1X0X3tDe + X1X2X1X0X2X3Y0 \
+ X1X0X2X1X3tD_(0,5) - X1X0X2X1X3tD_(0,4) + X1X0X2X1X3tD_(0,3) - X1X0X2X1X3tD_\
(0,2) + X1X0X2X1X3tD_(0,1) - X1X0X2X1X3tDe - X1X0X2X1X0Y1X2 - X1X0X2X1X0X2Y0 +\
 X0X2X1X0X2Y3X1 + X0X1X2X1X3Y3X1 - X0X1X2X1X0X3Y0
 - X2X1X0X2X1Y0X1 + X1X2X1X0X3Y0X1 + X1X0X2X1X3Y0X1 - X1X0X2X1X0Y1X3 - X1X0X2X\
1X0X3Y2
 X1X2X1X0X3Y0X2 - X1X2X1X0X2Y2X1 - X1X2X1X0X2X1Y3 - X1X0X2X1X3Y0X2 + X0X1X2X1X\
0Y2X1
 X1X2X1X0X3tD_(0,5) - X1X2X1X0X3tD_(0,4) + X1X2X1X0X3tD_(0,3) - X1X2X1X0X3tD_(\
0,2) + X1X2X1X0X3tD_(0,1) - X1X2X1X0X3tDe - X1X2X1X0X2Y2X3 - X1X0X2X1X0Y1X2 - \
X1X0X2X1X0X2Y0 + X0X1X2X1X3Y3X1 - X0X1X2X1X0X3Y0 + X0X1X0X2X3Y1X2 - X0X1X0X2X1\
X3Y0 + X1X2X1X0X3
 X2X1X0X2X3Y3X2 - X2X1X0X2X1Y0X3 - X2X1X0X2X1X3Y1 - X0X2X1X0X2Y3X2 - X0X1X2X1X\
3Y3X2
 - X1X2X1X0X2X3tD_(0,5) + X1X2X1X0X2X3tD_(0,4) - X1X2X1X0X2X3tD_(0,3) + X1X2X1\
X0X2X3tD_(0,2) - X1X2X1X0X2X3tD_(0,1) + X1X2X1X0X2X3tDe + X0X2X1X0X2X3Y3X1 - X\
0X1X2X1X0X2X3Y0 - X0X1X0X2X1X3tD_(0,5) + X0X1X0X2X1X3tD_(0,4) - X0X1X0X2X1X3tD\
_(0,3) + X0X1X0X2X1X3tD_(0,2) - X0X1X0X2X1X3tD_(0,1) + X0X1X0X2X1X3tDe + X0X1X\
0X2X1X0Y1X2 + X0X1X0X2X1X0X2Y0 + X1X0X2X1X0X2
 2X1X2X1X0X2X1tD_(w^2,4) + 2X1X2X1X0X2X1tD_(w^2,2) + 2X1X2X1X0X2X1tD_(w^2,0) +\
 X1X2X1X0X2X1tD_(w,5) + X1X2X1X0X2X1tD_(w,4) + X1X2X1X0X2X1tD_(w,3) + X1X2X1X0\
X2X1tD_(w,2) + X1X2X1X0X2X1tD_(w,1) + X1X2X1X0X2X1tD_(w,0) + X1X2X1X0X2X1tD_(1\
,5) + X1X2X1X0X2X1tD_(1,4) + X1X2X1X0X2X1tD_(1,3) + X1X2X1X0X2X1tD_(1,2) + X1X\
2X1X0X2X1tD_(1,1) + X1X2X1X0X2X1tD_(1,0) + X1X2X1X0X2X1tD_(0,5) + X1X2X1X0X2X1\
tD_(0,4) + X1X2X1X0X2X1tD_(0,3) + X1X2X1X0X2X1tD_(0,2) + X1X2X1X0X2X1tD_(0,1) \
+ X1X2X1X0X2X1tDe + X0X2X1X0X2X1Y0X1 - X0X1X2X1X0X3Y0X1 - X0X1X0X2X1X3Y0X1 + X\
0X1X0X2X1X0Y1X3 + X0X1X0X2X1X0X3Y2 - X1X2X1X0X2X1t + X1X0X2X1X0X3
 - X2X1X0X2X1X3tD_(1,5) + X2X1X0X2X1X3tD_(1,4) - X2X1X0X2X1X3tD_(1,3) + X2X1X0\
X2X1X3tD_(1,2) - X2X1X0X2X1X3tD_(1,1) + X2X1X0X2X1X3tD_(1,0) - X0X1X2X1X0X3Y0X\
2 + X0X1X2X1X0X2Y2X1 + X0X1X2X1X0X2X1Y3 + X0X1X0X2X1X3Y0X2 + X1X2X1X0X2X1
 - X1X2X1X0X2X3tD_(0,5) + X1X2X1X0X2X3tD_(0,4) - X1X2X1X0X2X3tD_(0,3) + X1X2X1\
X0X2X3tD_(0,2) - X1X2X1X0X2X3tD_(0,1) + X1X2X1X0X2X3tDe + X1X0X2X1X0X2tD_(0,5)\
 - X1X0X2X1X0X2tD_(0,4) + X1X0X2X1X0X2tD_(0,3) - X1X0X2X1X0X2tD_(0,2) + X1X0X2\
X1X0X2tD_(0,1) - X1X0X2X1X0X2tDe + X0X2X1X0X2X1tD_(0,5) - X0X2X1X0X2X1tD_(0,4)\
 + X0X2X1X0X2X1tD_(0,3) - X0X2X1X0X2X1tD_(0,2) + X0X2X1X0X2X1tD_(0,1) - X0X2X1\
X0X2X1tDe - X0X1X2X1X0X3tD_(0,5) + X0X1X2X1X0X3tD_(0,4) - X0X1X2X1X0X3tD_(0,3)\
 + X0X1X2X1X0X3tD_(0,2) - X0X1X2X1X0X3tD_(0,1) + X0X1X2X1X0X3tDe + X0X1X2X1X0X\
2Y2X3 + X0X1X0X2X1X0Y1X2 + X0X1X0X2X1X0X2Y0 + X1X2X1X0X2X3 - X0X1X2X1X0X3
 X1X0X2X1X0X3tD_(w,5) - X1X0X2X1X0X3tD_(w,4) + X1X0X2X1X0X3tD_(w,3) - X1X0X2X1\
X0X3tD_(w,2) + X1X0X2X1X0X3tD_(w,1) - X1X0X2X1X0X3tD_(w,0) - X0X2X1X0X2X3Y3X2 \
+ X0X2X1X0X2X1Y0X3 + X0X2X1X0X2X1X3Y1 + X2X1X0X2X1X3
 X1X2X1X0X2X3Y0X1 + 2X1X2X1X0X2X1tD_(w^2,4) + 2X1X2X1X0X2X1tD_(w^2,2) + 2X1X2X\
1X0X2X1tD_(w^2,0) + X1X2X1X0X2X1tD_(w,5) + X1X2X1X0X2X1tD_(w,4) + X1X2X1X0X2X1\
tD_(w,3) + X1X2X1X0X2X1tD_(w,2) + X1X2X1X0X2X1tD_(w,1) + X1X2X1X0X2X1tD_(w,0) \
+ X1X2X1X0X2X1tD_(1,5) + X1X2X1X0X2X1tD_(1,4) + X1X2X1X0X2X1tD_(1,3) + X1X2X1X\
0X2X1tD_(1,2) + X1X2X1X0X2X1tD_(1,1) + X1X2X1X0X2X1tD_(1,0) + X1X2X1X0X2X1tD_(\
0,5) + X1X2X1X0X2X1tD_(0,4) + X1X2X1X0X2X1tD_(0,3) + X1X2X1X0X2X1tD_(0,2) + X1\
X2X1X0X2X1tD_(0,1) + X1X2X1X0X2X1tDe - X1X0X2X1X0X3Y2X2 + X1X0X2X1X0X2X1Y2 - X\
0X1X2X1X0X3Y0X1 - X0X1X0X2X1X0X3Y2 - X1X2X1X0X2X1t + X1X0X2X1X0X3
 X2X1X0X2X1X3Y1X1 - X1X0X2X1X0X3tD_(w,5) + X1X0X2X1X0X3tD_(w,4) - X1X0X2X1X0X3\
tD_(w,3) + X1X0X2X1X0X3tD_(w,2) - X1X0X2X1X0X3tD_(w,1) + X1X0X2X1X0X3tD_(w,0) \
+ X1X0X2X1X0X2Y0X3 + X1X0X2X1X0X2X3Y1 + X0X2X1X0X2X1X3Y1 - X2X1X0X2X1X3
 - X1X2X1X0X2X3Y0X2 + X1X2X1X0X2X1Y3X3 + X1X2X1X0X2X1X3Y3 + X1X0X2X1X0X2Y0X2 +\
 X0X1X2X1X0X2Y2X1 + X0X1X2X1X0X2X1Y3 + X0X1X0X2X1X3Y0X2
 - 2X1X2X1X0X2X1X3tD_(w^2,4) - 2X1X2X1X0X2X1X3tD_(w^2,2) - 2X1X2X1X0X2X1X3tD_(\
w^2,0) - X1X2X1X0X2X1X3tD_(w,5) - X1X2X1X0X2X1X3tD_(w,4) - X1X2X1X0X2X1X3tD_(w\
,3) - X1X2X1X0X2X1X3tD_(w,2) - X1X2X1X0X2X1X3tD_(w,1) - X1X2X1X0X2X1X3tD_(w,0)\
 - X1X2X1X0X2X1X3tD_(1,5) - X1X2X1X0X2X1X3tD_(1,4) - X1X2X1X0X2X1X3tD_(1,3) - \
X1X2X1X0X2X1X3tD_(1,2) - X1X2X1X0X2X1X3tD_(1,1) - X1X2X1X0X2X1X3tD_(1,0) - X1X\
2X1X0X2X1X3tD_(0,5) - X1X2X1X0X2X1X3tD_(0,4) - X1X2X1X0X2X1X3tD_(0,3) - X1X2X1\
X0X2X1X3tD_(0,2) - X1X2X1X0X2X1X3tD_(0,1) - X1X2X1X0X2X1X3tDe - X0X1X2X1X0X2X3\
Y0X1 + X0X1X0X2X1X0X3Y2X2 - X0X1X0X2X1X0X2X1Y2 + X1X2X1X0X2X1X3t + X1X0X2X1X0X\
2X1 - X0X1X0X2X1X0X3
 - X1X0X2X1X0X2X1tD_(w,5) + X1X0X2X1X0X2X1tD_(w,4) - X1X0X2X1X0X2X1tD_(w,3) + \
X1X0X2X1X0X2X1tD_(w,2) - X1X0X2X1X0X2X1tD_(w,1) + X1X0X2X1X0X2X1tD_(w,0) - X0X\
2X1X0X2X1X3Y1X1 + X0X1X0X2X1X0X3tD_(w,5) - X0X1X0X2X1X0X3tD_(w,4) + X0X1X0X2X1\
X0X3tD_(w,3) - X0X1X0X2X1X0X3tD_(w,2) + X0X1X0X2X1X0X3tD_(w,1) - X0X1X0X2X1X0X\
3tD_(w,0) - X0X1X0X2X1X0X2Y0X3 - X0X1X0X2X1X0X2X3Y1 + X1X0X2X1X0X2X3 + X0X2X1X\
0X2X1X3
 - X1X0X2X1X0X2X3tD_(1,5) + X1X0X2X1X0X2X3tD_(1,4) - X1X0X2X1X0X2X3tD_(1,3) + \
X1X0X2X1X0X2X3tD_(1,2) - X1X0X2X1X0X2X3tD_(1,1) + X1X0X2X1X0X2X3tD_(1,0) - X0X\
2X1X0X2X1X3tD_(1,5) + X0X2X1X0X2X1X3tD_(1,4) - X0X2X1X0X2X1X3tD_(1,3) + X0X2X1\
X0X2X1X3tD_(1,2) - X0X2X1X0X2X1X3tD_(1,1) + X0X2X1X0X2X1X3tD_(1,0) + X0X1X2X1X\
0X2X3Y0X2 - X0X1X2X1X0X2X1Y3X3 - X0X1X2X1X0X2X1X3Y3 - X0X1X0X2X1X0X2Y0X2 + X1X\
2X1X0X2X1X3
 - X1X2X1X0X2X1X3Y3X1 + X1X0X2X1X0X2X3Y1X2 - X1X0X2X1X0X2X1Y2X3 - 2X1X0X2X1X0X\
2X1X3Y0 + X0X1X2X1X0X2X1Y3X1
 X1X0X2X1X0X2X1X3tD_(0,5) - X1X0X2X1X0X2X1X3tD_(0,4) + X1X0X2X1X0X2X1X3tD_(0,3\
) - X1X0X2X1X0X2X1X3tD_(0,2) + X1X0X2X1X0X2X1X3tD_(0,1) - X1X0X2X1X0X2X1X3tDe \
+ X0X1X2X1X0X2X1X3Y3X1 - X0X1X0X2X1X0X2X3Y1X2 + X0X1X0X2X1X0X2X1Y2X3 + 2X0X1X0\
X2X1X0X2X1X3Y0 + X1X0X2X1X0X2X1X3

In [301]:
PrintNPList(List(Y1bis, ys -> ys.prod));

 Y1
 tD_(1,5) - tD_(1,4) + tD_(1,3) - tD_(1,2) + tD_(1,1) - tD_(1,0) - X0Y3
 Y1X1
 Y1X2
 Y1X3
 X2tD_(0,5) - X2tD_(0,4) + X2tD_(0,3) - X2tD_(0,2) + X2tD_(0,1) - X2tDe - X0Y3\
X1
 X3tD_(w,5) - X3tD_(w,4) + X3tD_(w,3) - X3tD_(w,2) + X3tD_(w,1) - X3tD_(w,0) -\
 X0Y3X2
 X1tD_(1,5) - X1tD_(1,4) + X1tD_(1,3) - X1tD_(1,2) + X1tD_(1,1) - X1tD_(1,0) -\
 X0Y3X3
 X3Y2X1 - X1tD_(1,5) + X1tD_(1,4) - X1tD_(1,3) + X1tD_(1,2) - X1tD_(1,1) + X1t\
D_(1,0) - X0X3Y3 + X0
 - X1Y1X2 + X0Y3X1 + X0X1Y0 + X2
 X2Y0X1 + X2X1Y2 - X1Y1X3 + X3
 X3Y2X2 - X2Y0X1 - X2X1Y2 - X1X3Y2 - X3
 - X2Y0X3 + X0Y3X2 + X0X2Y1
 - X1X2tD_(0,5) + X1X2tD_(0,4) - X1X2tD_(0,3) + X1X2tD_(0,2) - X1X2tD_(0,1) + \
X1X2tDe - X0X3Y3X1 + X0X1
 X2X3tD_(1,5) - X2X3tD_(1,4) + X2X3tD_(1,3) - X2X3tD_(1,2) + X2X3tD_(1,1) - X2\
X3tD_(1,0) + X0X1Y0X2
 X2X1tD_(w,5) - X2X1tD_(w,4) + X2X1tD_(w,3) - X2X1tD_(w,2) + X2X1tD_(w,1) - X2\
X1tD_(w,0) - X0X2Y1X1 - X0X2X1Y1 + X0X1Y0X3 + X0X2
 - X2X1tD_(w,5) + X2X1tD_(w,4) - X2X1tD_(w,3) + X2X1tD_(w,2) - X2X1tD_(w,1) + \
X2X1tD_(w,0) - X1X3tD_(w,5) + X1X3tD_(w,4) - X1X3tD_(w,3) + X1X3tD_(w,2) - X1X\
3tD_(w,1) + X1X3tD_(w,0) - X0X3Y3X2 + X0X2Y1X1 + X0X2X1Y1 + X0X1X3Y1
 2X1X0tD_(w^2,4) + 2X1X0tD_(w^2,2) + 2X1X0tD_(w^2,0) + X1X0tD_(w,5) + X1X0tD_(\
w,4) + X1X0tD_(w,3) + X1X0tD_(w,2) + X1X0tD_(w,1) + X1X0tD_(w,0) + X1X0tD_(1,5\
) + X1X0tD_(1,4) + X1X0tD_(1,3) + X1X0tD_(1,2) + X1X0tD_(1,1) + X1X0tD_(1,0) +\
 X1X0tD_(0,5) + X1X0tD_(0,4) + X1X0tD_(0,3) + X1X0tD_(0,2) + X1X0tD_(0,1) + X1\
X0tDe + 2X0X3tD_(w^2,4) + 2X0X3tD_(w^2,2) + 2X0X3tD_(w^2,0) + X0X3tD_(w,5) + X\
0X3tD_(w,4) + X0X3tD_(w,3) + X0X3tD_(w,2) + X0X3tD_(w,1) + X0X3tD_(w,0) + X0X3\
tD_(1,5) + X0X3tD_(1,4) + X0X3tD_(1,3) + X0X3tD_(1,2) + X0X3tD_(1,1) + X0X3tD_\
(1,0) + X0X3tD_(0,5) + X0X3tD_(0,4) + X0X3tD_(0,3) + X0X3tD_(0,2) + X0X3tD_(0,\
1) + X0X3tDe + X0X2Y1X3 - X1X0t - X0X3t
 - X2X3Y1X1 + X2X1X0Y1 - X1X3tD_(w,5) + X1X3tD_(w,4) - X1X3tD_(w,3) + X1X3tD_(\
w,2) - X1X3tD_(w,1) + X1X3tD_(w,0) - X1X2X3Y1 + X1X0Y3X2 - X0X2Y1X1 - X0X2X1Y1\
 - X0X1X3Y1 + X2X3 + 2X0X2
 - X2X1Y2X1 - X1X3Y2X1 + X1X0Y3X3 + X1X0X3Y3 + X0X3
 - X1X3Y2X2 + X1X2Y0X1 + X1X2X1Y2 + X0X1Y0X1 + X2X1 + X1X3
 X1X2Y0X3 - X1X0Y3X2 - X1X0X2Y1 + X0X2Y1X1 + X0X2X1Y1 + X2X3 - X0X2
 - X2X3Y1X1 + X2X1tD_(w,5) - X2X1tD_(w,4) + X2X1tD_(w,3) - X2X1tD_(w,2) + X2X1\
tD_(w,1) - X2X1tD_(w,0) - X1X2X3Y1 - X1X0Y3X2 - X1X0X2Y1 - X0X3Y3X2 + X0X2X1Y1\
 + X2X3
 - X2X3Y1X2 + X2X1Y2X3 + X2X1X3Y0 - X0X2Y1X2
 - X1X2X3tD_(1,5) + X1X2X3tD_(1,4) - X1X2X3tD_(1,3) + X1X2X3tD_(1,2) - X1X2X3t\
D_(1,1) + X1X2X3tD_(1,0) + X0X2X3Y2X1 - X0X2X1X0Y3 + X0X1X2X3Y3 - X0X1X0Y0X2 +\
 X0X1X2
 - X1X2X1tD_(w,5) + X1X2X1tD_(w,4) - X1X2X1tD_(w,3) + X1X2X1tD_(w,2) - X1X2X1t\
D_(w,1) + X1X2X1tD_(w,0) + X0X2X1Y1X1 + X0X1X3Y1X1 - X0X1X0Y0X3 - X0X1X0X3Y1 -\
 X0X2X1
 - X2X1X3tD_(0,5) + X2X1X3tD_(0,4) - X2X1X3tD_(0,3) + X2X1X3tD_(0,2) - X2X1X3t\
D_(0,1) + X2X1X3tDe + X0X1X3Y1X2 - X0X1X2Y3X1 - X0X1X2X1Y0
 - X2X1X0tD_(1,5) + X2X1X0tD_(1,4) - X2X1X0tD_(1,3) + X2X1X0tD_(1,2) - X2X1X0t\
D_(1,1) + X2X1X0tD_(1,0) + X1X2X3tD_(1,5) - X1X2X3tD_(1,4) + X1X2X3tD_(1,3) - \
X1X2X3tD_(1,2) + X1X2X3tD_(1,1) - X1X2X3tD_(1,0) + X0X1X3tD_(1,5) - X0X1X3tD_(\
1,4) + X0X1X3tD_(1,3) - X0X1X3tD_(1,2) + X0X1X3tD_(1,1) - X0X1X3tD_(1,0) - X0X\
1X2Y3X3 + X0X1X0Y0X2 + X0X1X0X2Y3
 - X2X1X0tD_(1,5) + X2X1X0tD_(1,4) - X2X1X0tD_(1,3) + X2X1X0tD_(1,2) - X2X1X0t\
D_(1,1) + X2X1X0tD_(1,0) + X1X2X3tD_(1,5) - X1X2X3tD_(1,4) + X1X2X3tD_(1,3) - \
X1X2X3tD_(1,2) + X1X2X3tD_(1,1) - X1X2X3tD_(1,0) + X1X0X2tD_(1,5) - X1X0X2tD_(\
1,4) + X1X0X2tD_(1,3) - X1X0X2tD_(1,2) + X1X0X2tD_(1,1) - X1X0X2tD_(1,0) + X0X\
2X3Y2X1 - X0X2X1tD_(1,5) + X0X2X1tD_(1,4) - X0X2X1tD_(1,3) + X0X2X1tD_(1,2) - \
X0X2X1tD_(1,1) + X0X2X1tD_(1,0) + X0X1X2X3Y3 + X0X1X0Y0X2 + X0X1X0X2Y3 - X0X1X\
2
 - 2X1X0X3tD_(w^2,4) - 2X1X0X3tD_(w^2,2) - 2X1X0X3tD_(w^2,0) - X1X0X3tD_(w,5) \
- X1X0X3tD_(w,4) - X1X0X3tD_(w,3) - X1X0X3tD_(w,2) - X1X0X3tD_(w,1) - X1X0X3tD\
_(w,0) - X1X0X3tD_(1,5) - X1X0X3tD_(1,4) - X1X0X3tD_(1,3) - X1X0X3tD_(1,2) - X\
1X0X3tD_(1,1) - X1X0X3tD_(1,0) - X1X0X3tD_(0,5) - X1X0X3tD_(0,4) - X1X0X3tD_(0\
,3) - X1X0X3tD_(0,2) - X1X0X3tD_(0,1) - X1X0X3tDe + X0X2X3Y2X2 - X0X2X1Y1X3 - \
X0X2X1X3Y2 + X1X0X3t
 X2X1X0Y1X1 - X1X2X3Y1X1 + X1X2X1tD_(w,5) - X1X2X1tD_(w,4) + X1X2X1tD_(w,3) - \
X1X2X1tD_(w,2) + X1X2X1tD_(w,1) - X1X2X1tD_(w,0) + X1X0X3Y3X2 - X1X0X2Y1X1 - X\
1X0X2X1Y1 - X0X2X1Y1X1 - X0X1X3Y1X1 - X0X1X0X3Y1 - X2X1X0 + X1X2X3 + 2X0X2X1 +\
 X0X1X3
 X2X1X3Y0X1 - X2X1X0X3Y2 - 2X1X0X3tD_(w^2,4) - 2X1X0X3tD_(w^2,2) - 2X1X0X3tD_(\
w^2,0) - X1X0X3tD_(w,5) - X1X0X3tD_(w,4) - X1X0X3tD_(w,3) - X1X0X3tD_(w,2) - X\
1X0X3tD_(w,1) - X1X0X3tD_(w,0) - X1X0X3tD_(1,5) - X1X0X3tD_(1,4) - X1X0X3tD_(1\
,3) - X1X0X3tD_(1,2) - X1X0X3tD_(1,1) - X1X0X3tD_(1,0) - X1X0X3tD_(0,5) - X1X0\
X3tD_(0,4) - X1X0X3tD_(0,3) - X1X0X3tD_(0,2) - X1X0X3tD_(0,1) - X1X0X3tDe - X1\
X0X2Y1X3 + X1X0X3t + X0X2X3
 X1X2X3Y1X1 - X1X2X1tD_(w,5) + X1X2X1tD_(w,4) - X1X2X1tD_(w,3) + X1X2X1tD_(w,2\
) - X1X2X1tD_(w,1) + X1X2X1tD_(w,0) + X1X0X3Y3X2 - X1X0X2X1Y1 + X0X1X3Y1X1 - X\
0X1X0X3Y1 + X2X1X0 - X1X2X3 - X0X1X3
 X1X2X3Y1X2 - X1X2X1Y2X3 - X1X2X1X3Y0 + X1X0X2Y1X2 + X0X1X2Y3X1 + X0X1X2X1Y0 +\
 X2X1X3
 X2X1X3tD_(0,5) - X2X1X3tD_(0,4) + X2X1X3tD_(0,3) - X2X1X3tD_(0,2) + X2X1X3tD_\
(0,1) - X2X1X3tDe - X2X1X0Y1X2 - X1X0X2Y1X2 + X0X2X1Y1X2 + X0X1X3Y1X2 - X0X1X2\
Y3X1 - X0X1X2X1Y0
 X2X1X3Y0X1 - X2X1X0Y1X3 - X2X1X0X3Y2 + X0X2X3Y2X2 - X0X2X1X3Y2 - X0X2X3
 X1X2X1X3tD_(0,5) - X1X2X1X3tD_(0,4) + X1X2X1X3tD_(0,3) - X1X2X1X3tD_(0,2) + X\
1X2X1X3tD_(0,1) - X1X2X1X3tDe - X0X2X1X0Y3X1 + X0X1X2X3Y3X1 - X0X1X0X3Y1X2 + X\
0X1X0X2Y3X1 + X0X1X0X2X1Y0 + X0X1X2X1
 X1X2X1X0tD_(1,5) - X1X2X1X0tD_(1,4) + X1X2X1X0tD_(1,3) - X1X2X1X0tD_(1,2) + X\
1X2X1X0tD_(1,1) - X1X2X1X0tD_(1,0) - X0X2X1X3Y2X1 + X0X2X1X0X3Y3 - X0X1X0X3tD_\
(1,5) + X0X1X0X3tD_(1,4) - X0X1X0X3tD_(1,3) + X0X1X0X3tD_(1,2) - X0X1X0X3tD_(1\
,1) + X0X1X0X3tD_(1,0) + X0X1X0X2Y3X3 + X0X1X2X3
 X2X1X0X2tD_(0,5) - X2X1X0X2tD_(0,4) + X2X1X0X2tD_(0,3) - X2X1X0X2tD_(0,2) + X\
2X1X0X2tD_(0,1) - X2X1X0X2tDe + X1X2X1X3tD_(0,5) - X1X2X1X3tD_(0,4) + X1X2X1X3\
tD_(0,3) - X1X2X1X3tD_(0,2) + X1X2X1X3tD_(0,1) - X1X2X1X3tDe - X0X1X2X3Y3X1 + \
X0X1X2X1tD_(0,5) - X0X1X2X1tD_(0,4) + X0X1X2X1tD_(0,3) - X0X1X2X1tD_(0,2) + X0\
X1X2X1tD_(0,1) - X0X1X2X1tDe - X0X1X0X3Y1X2 + X0X1X0X2X1Y0 + X0X1X2X1
 X2X1X0X3tD_(w,5) - X2X1X0X3tD_(w,4) + X2X1X0X3tD_(w,3) - X2X1X0X3tD_(w,2) + X\
2X1X0X3tD_(w,1) - X2X1X0X3tD_(w,0) - X0X1X2X3Y3X2 + X0X1X2X1Y0X3 + X0X1X2X1X3Y\
1 - X0X1X0X2Y3X2
 - X2X1X0X3tD_(w,5) + X2X1X0X3tD_(w,4) - X2X1X0X3tD_(w,3) + X2X1X0X3tD_(w,2) -\
 X2X1X0X3tD_(w,1) + X2X1X0X3tD_(w,0) + X1X0X2X3tD_(w,5) - X1X0X2X3tD_(w,4) + X\
1X0X2X3tD_(w,3) - X1X0X2X3tD_(w,2) + X1X0X2X3tD_(w,1) - X1X0X2X3tD_(w,0) - X0X\
2X1X3tD_(w,5) + X0X2X1X3tD_(w,4) - X0X2X1X3tD_(w,3) + X0X2X1X3tD_(w,2) - X0X2X\
1X3tD_(w,1) + X0X2X1X3tD_(w,0) + X0X2X1X0Y3X2 + X0X1X0X2Y3X2
 X1X0X2X1tD_(1,5) - X1X0X2X1tD_(1,4) + X1X0X2X1tD_(1,3) - X1X0X2X1tD_(1,2) + X\
1X0X2X1tD_(1,1) - X1X0X2X1tD_(1,0) - X0X2X1X3Y2X1 + X0X2X1X0Y3X3 + X0X2X1X0X3Y\
3 + X0X1X0X3tD_(1,5) - X0X1X0X3tD_(1,4) + X0X1X0X3tD_(1,3) - X0X1X0X3tD_(1,2) \
+ X0X1X0X3tD_(1,1) - X0X1X0X3tD_(1,0) - X0X1X2X3
 X2X1X0X3Y2X1 + X1X2X1X0tD_(1,5) - X1X2X1X0tD_(1,4) + X1X2X1X0tD_(1,3) - X1X2X\
1X0tD_(1,2) + X1X2X1X0tD_(1,1) - X1X2X1X0tD_(1,0) - X1X0X2X3Y2X1 + X1X0X2X1tD_\
(1,5) - X1X0X2X1tD_(1,4) + X1X0X2X1tD_(1,3) - X1X0X2X1tD_(1,2) + X1X0X2X1tD_(1\
,1) - X1X0X2X1tD_(1,0) - X0X2X1X3Y2X1 + X0X2X1X0X3Y3 - X0X1X0X2X3Y3 + X0X2X1X0\
 + X0X1X0X2
 X2X1X0X2Y0X1 + X2X1X0X2X1Y2 + X1X2X1X3Y0X1 - X1X2X1X0X3Y2 - X1X0X2X3Y2X2 + X1\
X0X2X1Y1X3 + X1X0X2X1X3Y2 + X0X2X1X3
 - X1X2X1X3tD_(0,5) + X1X2X1X3tD_(0,4) - X1X2X1X3tD_(0,3) + X1X2X1X3tD_(0,2) -\
 X1X2X1X3tD_(0,1) + X1X2X1X3tDe + X1X2X1X0Y1X2 - X1X0X2X1Y1X2 - X0X1X2X3Y3X1 +\
 X0X1X2X1X0Y0 - X0X1X0X3Y1X2 + X2X1X0X2
 - X1X2X1X3Y0X1 + X1X2X1X0Y1X3 + X1X2X1X0X3Y2 - X1X0X2X3Y2X2 + X1X0X2X1X3Y2 - \
X0X1X2X1Y0X1 + X2X1X0X3 + X1X0X2X3
 - X2X1X0X3Y2X2 + X2X1X0X2Y0X1 + X2X1X0X2X1Y2 - X1X2X1X0X3Y2 - X1X0X2X3Y2X2 + \
X1X0X2X1X3Y2 + X0X2X1X3Y2X2 - X0X1X2X1Y0X1 + X2X1X0X3 + X1X0X2X3 - X0X2X1X3
 - X2X1X0X3tD_(w,5) + X2X1X0X3tD_(w,4) - X2X1X0X3tD_(w,3) + X2X1X0X3tD_(w,2) -\
 X2X1X0X3tD_(w,1) + X2X1X0X3tD_(w,0) + X2X1X0X2Y0X3 + X0X2X1X0Y3X2 + X0X2X1X0X\
2Y1 - X0X1X2X3Y3X2 + X0X1X2X1X3Y1
 - X1X2X1X0X2tD_(0,5) + X1X2X1X0X2tD_(0,4) - X1X2X1X0X2tD_(0,3) + X1X2X1X0X2tD\
_(0,2) - X1X2X1X0X2tD_(0,1) + X1X2X1X0X2tDe - X0X2X1X0X3Y3X1 + X0X1X0X2X3Y3X1 \
- X0X1X0X2X1tD_(0,5) + X0X1X0X2X1tD_(0,4) - X0X1X0X2X1tD_(0,3) + X0X1X0X2X1tD_\
(0,2) - X0X1X0X2X1tD_(0,1) + X0X1X0X2X1tDe + X0X1X2X1X0 - X0X1X0X2X1
 - X1X2X1X0X3tD_(w,5) + X1X2X1X0X3tD_(w,4) - X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD\
_(w,2) - X1X2X1X0X3tD_(w,1) + X1X2X1X0X3tD_(w,0) - X0X2X1X0X2Y1X1 - X0X2X1X0X2\
X1Y1 - X0X1X2X1X3Y1X1 + X0X1X2X1X0X3Y1 + X0X1X0X2X3Y3X2 - X0X1X0X2X1Y0X3 - X0X\
1X0X2X1X3Y1 + X0X2X1X0X2 + 2X0X1X2X1X3
 X2X1X0X2X3tD_(1,5) - X2X1X0X2X3tD_(1,4) + X2X1X0X2X3tD_(1,3) - X2X1X0X2X3tD_(\
1,2) + X2X1X0X2X3tD_(1,1) - X2X1X0X2X3tD_(1,0) + X0X1X2X1X3tD_(1,5) - X0X1X2X1\
X3tD_(1,4) + X0X1X2X1X3tD_(1,3) - X0X1X2X1X3tD_(1,2) + X0X1X2X1X3tD_(1,1) - X0\
X1X2X1X3tD_(1,0) - X0X1X2X1X0Y0X2 + X0X1X0X2X1Y0X2
 X2X1X0X2X1tD_(w,5) - X2X1X0X2X1tD_(w,4) + X2X1X0X2X1tD_(w,3) - X2X1X0X2X1tD_(\
w,2) + X2X1X0X2X1tD_(w,1) - X2X1X0X2X1tD_(w,0) - X1X2X1X0X3tD_(w,5) + X1X2X1X0\
X3tD_(w,4) - X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD_(w,2) - X1X2X1X0X3tD_(w,1) + X1\
X2X1X0X3tD_(w,0) + X0X1X2X1X3Y1X1 - X0X1X2X1X0Y0X3 - X0X1X2X1X0X3Y1 + X0X1X0X2\
X3Y3X2 - X0X1X0X2X1X3Y1
 X2X1X0X2X1tD_(w,5) - X2X1X0X2X1tD_(w,4) + X2X1X0X2X1tD_(w,3) - X2X1X0X2X1tD_(\
w,2) + X2X1X0X2X1tD_(w,1) - X2X1X0X2X1tD_(w,0) - X1X2X1X0X3tD_(w,5) + X1X2X1X0\
X3tD_(w,4) - X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD_(w,2) - X1X2X1X0X3tD_(w,1) + X1\
X2X1X0X3tD_(w,0) - X1X0X2X1X3tD_(w,5) + X1X0X2X1X3tD_(w,4) - X1X0X2X1X3tD_(w,3\
) + X1X0X2X1X3tD_(w,2) - X1X0X2X1X3tD_(w,1) + X1X0X2X1X3tD_(w,0) + X0X2X1X0X3Y\
3X2 - X0X2X1X0X2Y1X1 - X0X2X1X0X2X1Y1 + X0X1X2X1X0X3Y1 + X0X1X0X2X3Y3X2 - X0X1\
X0X2X1X3Y1
 2X1X0X2X1X0tD_(w^2,4) + 2X1X0X2X1X0tD_(w^2,2) + 2X1X0X2X1X0tD_(w^2,0) + X1X0X\
2X1X0tD_(w,5) + X1X0X2X1X0tD_(w,4) + X1X0X2X1X0tD_(w,3) + X1X0X2X1X0tD_(w,2) +\
 X1X0X2X1X0tD_(w,1) + X1X0X2X1X0tD_(w,0) + X1X0X2X1X0tD_(1,5) + X1X0X2X1X0tD_(\
1,4) + X1X0X2X1X0tD_(1,3) + X1X0X2X1X0tD_(1,2) + X1X0X2X1X0tD_(1,1) + X1X0X2X1\
X0tD_(1,0) + X1X0X2X1X0tD_(0,5) + X1X0X2X1X0tD_(0,4) + X1X0X2X1X0tD_(0,3) + X1\
X0X2X1X0tD_(0,2) + X1X0X2X1X0tD_(0,1) + X1X0X2X1X0tDe - 2X0X2X1X0X3tD_(w^2,4) \
- 2X0X2X1X0X3tD_(w^2,2) - 2X0X2X1X0X3tD_(w^2,0) - X0X2X1X0X3tD_(w,5) - X0X2X1X\
0X3tD_(w,4) - X0X2X1X0X3tD_(w,3) - X0X2X1X0X3tD_(w,2) - X0X2X1X0X3tD_(w,1) - X\
0X2X1X0X3tD_(w,0) - X0X2X1X0X3tD_(1,5) - X0X2X1X0X3tD_(1,4) - X0X2X1X0X3tD_(1,\
3) - X0X2X1X0X3tD_(1,2) - X0X2X1X0X3tD_(1,1) - X0X2X1X0X3tD_(1,0) - X0X2X1X0X3\
tD_(0,5) - X0X2X1X0X3tD_(0,4) - X0X2X1X0X3tD_(0,3) - X0X2X1X0X3tD_(0,2) - X0X2\
X1X0X3tD_(0,1) - X0X2X1X0X3tDe - X0X2X1X0X2Y1X3 - 2X0X1X0X2X3tD_(w^2,4) - 2X0X\
1X0X2X3tD_(w^2,2) - 2X0X1X0X2X3tD_(w^2,0) - X0X1X0X2X3tD_(w,5) - X0X1X0X2X3tD_\
(w,4) - X0X1X0X2X3tD_(w,3) - X0X1X0X2X3tD_(w,2) - X0X1X0X2X3tD_(w,1) - X0X1X0X\
2X3tD_(w,0) - X0X1X0X2X3tD_(1,5) - X0X1X0X2X3tD_(1,4) - X0X1X0X2X3tD_(1,3) - X\
0X1X0X2X3tD_(1,2) - X0X1X0X2X3tD_(1,1) - X0X1X0X2X3tD_(1,0) - X0X1X0X2X3tD_(0,\
5) - X0X1X0X2X3tD_(0,4) - X0X1X0X2X3tD_(0,3) - X0X1X0X2X3tD_(0,2) - X0X1X0X2X3\
tD_(0,1) - X0X1X0X2X3tDe - X1X0X2X1X0t + X0X2X1X0X3t + X0X1X0X2X3t
 - X2X1X0X2X3Y1X1 + X1X2X1X0X3tD_(w,5) - X1X2X1X0X3tD_(w,4) + X1X2X1X0X3tD_(w,\
3) - X1X2X1X0X3tD_(w,2) + X1X2X1X0X3tD_(w,1) - X1X2X1X0X3tD_(w,0) + X1X2X1X0X2\
X3Y1 + X1X0X2X1X3tD_(w,5) - X1X0X2X1X3tD_(w,4) + X1X0X2X1X3tD_(w,3) - X1X0X2X1\
X3tD_(w,2) + X1X0X2X1X3tD_(w,1) - X1X0X2X1X3tD_(w,0) - X1X0X2X1X0Y3X2 - X1X0X2\
X1X0X2Y1 + X0X2X1X0X2Y1X1 + X0X1X2X1X3Y1X1 - X0X1X2X1X0X3Y1 + X2X1X0X2X3 - X0X\
1X2X1X3
 - X2X1X0X2X1Y2X1 + X1X2X1X0X3Y2X1 + X1X0X2X1X3Y2X1 - X1X0X2X1X0Y3X3 - X1X0X2X\
1X0X3Y3 + X0X2X1X0X3 + X0X1X0X2X3
 X1X2X1X0X3Y2X2 - X1X2X1X0X2Y0X1 - X1X2X1X0X2X1Y2 - X1X0X2X1X3Y2X2 + X0X1X2X1X\
0Y0X1 + X2X1X0X2X1 - X1X2X1X0X3 + X1X0X2X1X3
 X1X2X1X0X3tD_(w,5) - X1X2X1X0X3tD_(w,4) + X1X2X1X0X3tD_(w,3) - X1X2X1X0X3tD_(\
w,2) + X1X2X1X0X3tD_(w,1) - X1X2X1X0X3tD_(w,0) - X1X2X1X0X2Y0X3 - X1X0X2X1X0Y3\
X2 - X1X0X2X1X0X2Y1 + X0X1X2X1X3Y1X1 - X0X1X2X1X0X3Y1 + X0X1X0X2X3Y3X2 - X0X1X\
0X2X1X3Y1 + X2X1X0X2X3 - X0X1X2X1X3
 X2X1X0X2X3Y1X2 - X2X1X0X2X1Y2X3 - X2X1X0X2X1X3Y0 - X0X2X1X0X2Y1X2 - X0X1X2X1X\
3Y1X2
 - X1X2X1X0X2X3tD_(1,5) + X1X2X1X0X2X3tD_(1,4) - X1X2X1X0X2X3tD_(1,3) + X1X2X1\
X0X2X3tD_(1,2) - X1X2X1X0X2X3tD_(1,1) + X1X2X1X0X2X3tD_(1,0) + X0X2X1X0X2X3Y2X\
1 - X0X1X2X1X0X2X3Y3 - X0X1X0X2X1X3tD_(1,5) + X0X1X0X2X1X3tD_(1,4) - X0X1X0X2X\
1X3tD_(1,3) + X0X1X0X2X1X3tD_(1,2) - X0X1X0X2X1X3tD_(1,1) + X0X1X0X2X1X3tD_(1,\
0) + X0X1X0X2X1X0Y0X2 + X0X1X0X2X1X0X2Y3 + X0X1X2X1X0X2
 - X1X2X1X0X2X1tD_(w,5) + X1X2X1X0X2X1tD_(w,4) - X1X2X1X0X2X1tD_(w,3) + X1X2X1\
X0X2X1tD_(w,2) - X1X2X1X0X2X1tD_(w,1) + X1X2X1X0X2X1tD_(w,0) + X0X2X1X0X2X1Y1X\
1 - X0X1X2X1X0X3Y1X1 - X0X1X0X2X1X3Y1X1 + X0X1X0X2X1X0Y0X3 + X0X1X0X2X1X0X3Y1 \
- X0X2X1X0X2X1 + 2X0X1X2X1X0X3
 - X2X1X0X2X1X3tD_(0,5) + X2X1X0X2X1X3tD_(0,4) - X2X1X0X2X1X3tD_(0,3) + X2X1X0\
X2X1X3tD_(0,2) - X2X1X0X2X1X3tD_(0,1) + X2X1X0X2X1X3tDe - X0X1X2X1X0X3Y1X2 + X\
0X1X2X1X0X2Y3X1 + X0X1X2X1X0X2X1Y0 + X0X1X0X2X1X3Y1X2
 - X1X2X1X0X2X3tD_(1,5) + X1X2X1X0X2X3tD_(1,4) - X1X2X1X0X2X3tD_(1,3) + X1X2X1\
X0X2X3tD_(1,2) - X1X2X1X0X2X3tD_(1,1) + X1X2X1X0X2X3tD_(1,0) + X1X0X2X1X0X2tD_\
(1,5) - X1X0X2X1X0X2tD_(1,4) + X1X0X2X1X0X2tD_(1,3) - X1X0X2X1X0X2tD_(1,2) + X\
1X0X2X1X0X2tD_(1,1) - X1X0X2X1X0X2tD_(1,0) + X0X2X1X0X2X1tD_(1,5) - X0X2X1X0X2\
X1tD_(1,4) + X0X2X1X0X2X1tD_(1,3) - X0X2X1X0X2X1tD_(1,2) + X0X2X1X0X2X1tD_(1,1\
) - X0X2X1X0X2X1tD_(1,0) - X0X1X2X1X0X3tD_(1,5) + X0X1X2X1X0X3tD_(1,4) - X0X1X\
2X1X0X3tD_(1,3) + X0X1X2X1X0X3tD_(1,2) - X0X1X2X1X0X3tD_(1,1) + X0X1X2X1X0X3tD\
_(1,0) + X0X1X2X1X0X2Y3X3 + X0X1X0X2X1X0Y0X2 + X0X1X0X2X1X0X2Y3
 - 2X1X0X2X1X0X3tD_(w^2,4) - 2X1X0X2X1X0X3tD_(w^2,2) - 2X1X0X2X1X0X3tD_(w^2,0)\
 - X1X0X2X1X0X3tD_(w,5) - X1X0X2X1X0X3tD_(w,4) - X1X0X2X1X0X3tD_(w,3) - X1X0X2\
X1X0X3tD_(w,2) - X1X0X2X1X0X3tD_(w,1) - X1X0X2X1X0X3tD_(w,0) - X1X0X2X1X0X3tD_\
(1,5) - X1X0X2X1X0X3tD_(1,4) - X1X0X2X1X0X3tD_(1,3) - X1X0X2X1X0X3tD_(1,2) - X\
1X0X2X1X0X3tD_(1,1) - X1X0X2X1X0X3tD_(1,0) - X1X0X2X1X0X3tD_(0,5) - X1X0X2X1X0\
X3tD_(0,4) - X1X0X2X1X0X3tD_(0,3) - X1X0X2X1X0X3tD_(0,2) - X1X0X2X1X0X3tD_(0,1\
) - X1X0X2X1X0X3tDe - X0X2X1X0X2X3Y2X2 + X0X2X1X0X2X1Y1X3 + X0X2X1X0X2X1X3Y2 +\
 X1X0X2X1X0X3t
 X1X2X1X0X2X3Y1X1 - X1X2X1X0X2X1tD_(w,5) + X1X2X1X0X2X1tD_(w,4) - X1X2X1X0X2X1\
tD_(w,3) + X1X2X1X0X2X1tD_(w,2) - X1X2X1X0X2X1tD_(w,1) + X1X2X1X0X2X1tD_(w,0) \
- X1X0X2X1X0X3Y3X2 + X1X0X2X1X0X2X1Y1 - X0X1X2X1X0X3Y1X1 - X0X1X0X2X1X0X3Y1 - \
X1X2X1X0X2X3 + X1X0X2X1X0X2 + X0X2X1X0X2X1 + X0X1X2X1X0X3
 X2X1X0X2X1X3Y0X1 + 2X1X0X2X1X0X3tD_(w^2,4) + 2X1X0X2X1X0X3tD_(w^2,2) + 2X1X0X\
2X1X0X3tD_(w^2,0) + X1X0X2X1X0X3tD_(w,5) + X1X0X2X1X0X3tD_(w,4) + X1X0X2X1X0X3\
tD_(w,3) + X1X0X2X1X0X3tD_(w,2) + X1X0X2X1X0X3tD_(w,1) + X1X0X2X1X0X3tD_(w,0) \
+ X1X0X2X1X0X3tD_(1,5) + X1X0X2X1X0X3tD_(1,4) + X1X0X2X1X0X3tD_(1,3) + X1X0X2X\
1X0X3tD_(1,2) + X1X0X2X1X0X3tD_(1,1) + X1X0X2X1X0X3tD_(1,0) + X1X0X2X1X0X3tD_(\
0,5) + X1X0X2X1X0X3tD_(0,4) + X1X0X2X1X0X3tD_(0,3) + X1X0X2X1X0X3tD_(0,2) + X1\
X0X2X1X0X3tD_(0,1) + X1X0X2X1X0X3tDe + X1X0X2X1X0X2Y1X3 + X1X0X2X1X0X2X3Y2 + X\
0X2X1X0X2X1X3Y2 - X1X0X2X1X0X3t + X0X2X1X0X2X3
 - X1X2X1X0X2X3Y1X2 + X1X2X1X0X2X1Y2X3 + X1X2X1X0X2X1X3Y0 + X1X0X2X1X0X2Y1X2 +\
 X0X1X2X1X0X2Y3X1 + X0X1X2X1X0X2X1Y0 + X0X1X0X2X1X3Y1X2 + X2X1X0X2X1X3
 X1X2X1X0X2X1X3tD_(0,5) - X1X2X1X0X2X1X3tD_(0,4) + X1X2X1X0X2X1X3tD_(0,3) - X1\
X2X1X0X2X1X3tD_(0,2) + X1X2X1X0X2X1X3tD_(0,1) - X1X2X1X0X2X1X3tDe - X0X1X2X1X0\
X2X3Y3X1 + X0X1X0X2X1X0X3Y1X2 - X0X1X0X2X1X0X2X1Y0 + X0X1X2X1X0X2X1
 - X1X0X2X1X0X2X1tD_(1,5) + X1X0X2X1X0X2X1tD_(1,4) - X1X0X2X1X0X2X1tD_(1,3) + \
X1X0X2X1X0X2X1tD_(1,2) - X1X0X2X1X0X2X1tD_(1,1) + X1X0X2X1X0X2X1tD_(1,0) - X0X\
2X1X0X2X1X3Y2X1 + X0X1X0X2X1X0X3tD_(1,5) - X0X1X0X2X1X0X3tD_(1,4) + X0X1X0X2X1\
X0X3tD_(1,3) - X0X1X0X2X1X0X3tD_(1,2) + X0X1X0X2X1X0X3tD_(1,1) - X0X1X0X2X1X0X\
3tD_(1,0) - X0X1X0X2X1X0X2Y3X3 - X0X1X0X2X1X0X2X3Y3 + X0X1X2X1X0X2X3
 - X1X0X2X1X0X2X3tD_(w,5) + X1X0X2X1X0X2X3tD_(w,4) - X1X0X2X1X0X2X3tD_(w,3) + \
X1X0X2X1X0X2X3tD_(w,2) - X1X0X2X1X0X2X3tD_(w,1) + X1X0X2X1X0X2X3tD_(w,0) - X0X\
2X1X0X2X1X3tD_(w,5) + X0X2X1X0X2X1X3tD_(w,4) - X0X2X1X0X2X1X3tD_(w,3) + X0X2X1\
X0X2X1X3tD_(w,2) - X0X2X1X0X2X1X3tD_(w,1) + X0X2X1X0X2X1X3tD_(w,0) + X0X1X2X1X\
0X2X3Y3X2 - X0X1X2X1X0X2X1Y0X3 - X0X1X2X1X0X2X1X3Y1 - X0X1X0X2X1X0X2Y3X2
 - X1X2X1X0X2X1X3Y0X1 + X1X0X2X1X0X2X3Y2X2 - X1X0X2X1X0X2X1Y1X3 - 2X1X0X2X1X0X\
2X1X3Y2 + X0X1X2X1X0X2X1Y0X1 + X0X2X1X0X2X1X3
 X1X0X2X1X0X2X1X3tD_(w,5) - X1X0X2X1X0X2X1X3tD_(w,4) + X1X0X2X1X0X2X1X3tD_(w,3\
) - X1X0X2X1X0X2X1X3tD_(w,2) + X1X0X2X1X0X2X1X3tD_(w,1) - X1X0X2X1X0X2X1X3tD_(\
w,0) + X0X1X2X1X0X2X1X3Y1X1 - X0X1X0X2X1X0X2X3Y3X2 + X0X1X0X2X1X0X2X1Y0X3 + 2X\
0X1X0X2X1X0X2X1X3Y1

In [302]:
PrintNPList(List(Y2bis, ys -> ys.prod));

 Y2
 tD_(w,5) - tD_(w,4) + tD_(w,3) - tD_(w,2) + tD_(w,1) - tD_(w,0) - X0Y1
 Y2X1
 Y2X2
 Y2X3
 X2tD_(w,5) - X2tD_(w,4) + X2tD_(w,3) - X2tD_(w,2) + X2tD_(w,1) - X2tD_(w,0) -\
 X0Y1X1
 X3tD_(0,5) - X3tD_(0,4) + X3tD_(0,3) - X3tD_(0,2) + X3tD_(0,1) - X3tDe - X0Y1\
X2
 - 2X1tD_(w^2,4) - 2X1tD_(w^2,2) - 2X1tD_(w^2,0) - X1tD_(w,5) - X1tD_(w,4) - X\
1tD_(w,3) - X1tD_(w,2) - X1tD_(w,1) - X1tD_(w,0) - X1tD_(1,5) - X1tD_(1,4) - X\
1tD_(1,3) - X1tD_(1,2) - X1tD_(1,1) - X1tD_(1,0) - X1tD_(0,5) - X1tD_(0,4) - X\
1tD_(0,3) - X1tD_(0,2) - X1tD_(0,1) - X1tDe - X0Y1X3 + X1t
 X3Y0X1 + 2X1tD_(w^2,4) + 2X1tD_(w^2,2) + 2X1tD_(w^2,0) + X1tD_(w,5) + X1tD_(w\
,4) + X1tD_(w,3) + X1tD_(w,2) + X1tD_(w,1) + X1tD_(w,0) + X1tD_(1,5) + X1tD_(1\
,4) + X1tD_(1,3) + X1tD_(1,2) + X1tD_(1,1) + X1tD_(1,0) + X1tD_(0,5) + X1tD_(0\
,4) + X1tD_(0,3) + X1tD_(0,2) + X1tD_(0,1) + X1tDe - X0X3Y2 - X1t
 - X1Y3X2 + X0Y1X1 + X0X1Y1 - X0
 X2Y2X1 + X2X1Y3 - X1Y3X3
 X3Y0X2 - X2Y2X1 - X2X1Y3 - X1X3Y3 + X1
 - X2Y2X3 + X0Y1X2 + X0X2Y0 + X3
 - X1X2tD_(1,5) + X1X2tD_(1,4) - X1X2tD_(1,3) + X1X2tD_(1,2) - X1X2tD_(1,1) + \
X1X2tD_(1,0) - X0X3Y2X1
 X2X3tD_(0,5) - X2X3tD_(0,4) + X2X3tD_(0,3) - X2X3tD_(0,2) + X2X3tD_(0,1) - X2\
X3tDe + X0X1Y1X2 - X0X2
 - 2X2X1tD_(w^2,4) - 2X2X1tD_(w^2,2) - 2X2X1tD_(w^2,0) - X2X1tD_(w,5) - X2X1tD\
_(w,4) - X2X1tD_(w,3) - X2X1tD_(w,2) - X2X1tD_(w,1) - X2X1tD_(w,0) - X2X1tD_(1\
,5) - X2X1tD_(1,4) - X2X1tD_(1,3) - X2X1tD_(1,2) - X2X1tD_(1,1) - X2X1tD_(1,0)\
 - X2X1tD_(0,5) - X2X1tD_(0,4) - X2X1tD_(0,3) - X2X1tD_(0,2) - X2X1tD_(0,1) - \
X2X1tDe - X0X2Y0X1 - X0X2X1Y2 + X0X1Y1X3 + X2X1t - X0X3
 2X2X1tD_(w^2,4) + 2X2X1tD_(w^2,2) + 2X2X1tD_(w^2,0) + X2X1tD_(w,5) + X2X1tD_(\
w,4) + X2X1tD_(w,3) + X2X1tD_(w,2) + X2X1tD_(w,1) + X2X1tD_(w,0) + X2X1tD_(1,5\
) + X2X1tD_(1,4) + X2X1tD_(1,3) + X2X1tD_(1,2) + X2X1tD_(1,1) + X2X1tD_(1,0) +\
 X2X1tD_(0,5) + X2X1tD_(0,4) + X2X1tD_(0,3) + X2X1tD_(0,2) + X2X1tD_(0,1) + X2\
X1tDe + 2X1X3tD_(w^2,4) + 2X1X3tD_(w^2,2) + 2X1X3tD_(w^2,0) + X1X3tD_(w,5) + X\
1X3tD_(w,4) + X1X3tD_(w,3) + X1X3tD_(w,2) + X1X3tD_(w,1) + X1X3tD_(w,0) + X1X3\
tD_(1,5) + X1X3tD_(1,4) + X1X3tD_(1,3) + X1X3tD_(1,2) + X1X3tD_(1,1) + X1X3tD_\
(1,0) + X1X3tD_(0,5) + X1X3tD_(0,4) + X1X3tD_(0,3) + X1X3tD_(0,2) + X1X3tD_(0,\
1) + X1X3tDe - X0X3Y2X2 + X0X2Y0X1 + X0X2X1Y2 + X0X1X3Y2 - X2X1t - X1X3t + X0X\
3
 - X1X0tD_(w,5) + X1X0tD_(w,4) - X1X0tD_(w,3) + X1X0tD_(w,2) - X1X0tD_(w,1) + \
X1X0tD_(w,0) - X0X3tD_(w,5) + X0X3tD_(w,4) - X0X3tD_(w,3) + X0X3tD_(w,2) - X0X\
3tD_(w,1) + X0X3tD_(w,0) + X0X2Y0X3
 - X2X3Y0X1 + X2X1X0Y2 + 2X1X3tD_(w^2,4) + 2X1X3tD_(w^2,2) + 2X1X3tD_(w^2,0) +\
 X1X3tD_(w,5) + X1X3tD_(w,4) + X1X3tD_(w,3) + X1X3tD_(w,2) + X1X3tD_(w,1) + X1\
X3tD_(w,0) + X1X3tD_(1,5) + X1X3tD_(1,4) + X1X3tD_(1,3) + X1X3tD_(1,2) + X1X3t\
D_(1,1) + X1X3tD_(1,0) + X1X3tD_(0,5) + X1X3tD_(0,4) + X1X3tD_(0,3) + X1X3tD_(\
0,2) + X1X3tD_(0,1) + X1X3tDe - X1X2X3Y2 + X1X0Y2X2 - X0X2Y0X1 - X0X2X1Y2 - X0\
X1X3Y2 - X1X3t
 - X2X1Y3X1 - X1X3Y3X1 + X1X0Y2X3 + X1X0X3Y0
 - X1X3Y3X2 + X1X2Y1X1 + X1X2X1Y1 + X0X1Y1X1 - X0X1
 X1X2Y1X3 - X1X0Y2X2 - X1X0X2Y2 + X0X2Y0X1 + X0X2X1Y2 + X1X0
 - X2X3Y0X1 - 2X2X1tD_(w^2,4) - 2X2X1tD_(w^2,2) - 2X2X1tD_(w^2,0) - X2X1tD_(w,\
5) - X2X1tD_(w,4) - X2X1tD_(w,3) - X2X1tD_(w,2) - X2X1tD_(w,1) - X2X1tD_(w,0) \
- X2X1tD_(1,5) - X2X1tD_(1,4) - X2X1tD_(1,3) - X2X1tD_(1,2) - X2X1tD_(1,1) - X\
2X1tD_(1,0) - X2X1tD_(0,5) - X2X1tD_(0,4) - X2X1tD_(0,3) - X2X1tD_(0,2) - X2X1\
tD_(0,1) - X2X1tDe - X1X2X3Y2 - X1X0Y2X2 - X1X0X2Y2 - X0X3Y2X2 + X0X2X1Y2 + X2\
X1t + 2X1X0 + X0X3
 - X2X3Y0X2 + X2X1Y3X3 + X2X1X3Y3 - X0X2Y0X2 + X1X3
 - X1X2X3tD_(w,5) + X1X2X3tD_(w,4) - X1X2X3tD_(w,3) + X1X2X3tD_(w,2) - X1X2X3t\
D_(w,1) + X1X2X3tD_(w,0) + X0X2X3Y1X1 - X0X2X1X0Y1 + X0X1X2X3Y1 - X0X1X0Y3X2 -\
 X0X2X3
 - X1X2X1tD_(1,5) + X1X2X1tD_(1,4) - X1X2X1tD_(1,3) + X1X2X1tD_(1,2) - X1X2X1t\
D_(1,1) + X1X2X1tD_(1,0) + X0X2X1Y2X1 + X0X1X3Y2X1 - X0X1X0Y3X3 - X0X1X0X3Y3
 2X2X1X3tD_(w^2,4) + 2X2X1X3tD_(w^2,2) + 2X2X1X3tD_(w^2,0) + X2X1X3tD_(w,5) + \
X2X1X3tD_(w,4) + X2X1X3tD_(w,3) + X2X1X3tD_(w,2) + X2X1X3tD_(w,1) + X2X1X3tD_(\
w,0) + X2X1X3tD_(1,5) + X2X1X3tD_(1,4) + X2X1X3tD_(1,3) + X2X1X3tD_(1,2) + X2X\
1X3tD_(1,1) + X2X1X3tD_(1,0) + X2X1X3tD_(0,5) + X2X1X3tD_(0,4) + X2X1X3tD_(0,3\
) + X2X1X3tD_(0,2) + X2X1X3tD_(0,1) + X2X1X3tDe + X0X1X3Y2X2 - X0X1X2Y0X1 - X0\
X1X2X1Y2 - X2X1X3t - X0X2X1 - X0X1X3
 - X2X1X0tD_(w,5) + X2X1X0tD_(w,4) - X2X1X0tD_(w,3) + X2X1X0tD_(w,2) - X2X1X0t\
D_(w,1) + X2X1X0tD_(w,0) + X1X2X3tD_(w,5) - X1X2X3tD_(w,4) + X1X2X3tD_(w,3) - \
X1X2X3tD_(w,2) + X1X2X3tD_(w,1) - X1X2X3tD_(w,0) + X0X1X3tD_(w,5) - X0X1X3tD_(\
w,4) + X0X1X3tD_(w,3) - X0X1X3tD_(w,2) + X0X1X3tD_(w,1) - X0X1X3tD_(w,0) - X0X\
1X2Y0X3 + X0X1X0Y3X2 + X0X1X0X2Y1 - X0X2X3
 - X2X1X0tD_(w,5) + X2X1X0tD_(w,4) - X2X1X0tD_(w,3) + X2X1X0tD_(w,2) - X2X1X0t\
D_(w,1) + X2X1X0tD_(w,0) + X1X2X3tD_(w,5) - X1X2X3tD_(w,4) + X1X2X3tD_(w,3) - \
X1X2X3tD_(w,2) + X1X2X3tD_(w,1) - X1X2X3tD_(w,0) + X1X0X2tD_(w,5) - X1X0X2tD_(\
w,4) + X1X0X2tD_(w,3) - X1X0X2tD_(w,2) + X1X0X2tD_(w,1) - X1X0X2tD_(w,0) + X0X\
2X3Y1X1 - X0X2X1tD_(w,5) + X0X2X1tD_(w,4) - X0X2X1tD_(w,3) + X0X2X1tD_(w,2) - \
X0X2X1tD_(w,1) + X0X2X1tD_(w,0) + X0X1X2X3Y1 + X0X1X0Y3X2 + X0X1X0X2Y1 - X0X2X\
3
 X1X0X3tD_(0,5) - X1X0X3tD_(0,4) + X1X0X3tD_(0,3) - X1X0X3tD_(0,2) + X1X0X3tD_\
(0,1) - X1X0X3tDe + X0X2X3Y1X2 - X0X2X1Y2X3 - X0X2X1X3Y0
 X2X1X0Y2X1 - X1X2X3Y2X1 + X1X2X1tD_(1,5) - X1X2X1tD_(1,4) + X1X2X1tD_(1,3) - \
X1X2X1tD_(1,2) + X1X2X1tD_(1,1) - X1X2X1tD_(1,0) + X1X0X3Y0X2 - X1X0X2Y2X1 - X\
1X0X2X1Y3 - X0X2X1Y2X1 - X0X1X3Y2X1 - X0X1X0X3Y3 + X0X1X0
 X2X1X3Y3X1 - X2X1X0X3Y0 + X1X0X3tD_(0,5) - X1X0X3tD_(0,4) + X1X0X3tD_(0,3) - \
X1X0X3tD_(0,2) + X1X0X3tD_(0,1) - X1X0X3tDe - X1X0X2Y2X3 + X1X0X3
 X1X2X3Y2X1 - X1X2X1tD_(1,5) + X1X2X1tD_(1,4) - X1X2X1tD_(1,3) + X1X2X1tD_(1,2\
) - X1X2X1tD_(1,1) + X1X2X1tD_(1,0) + X1X0X3Y0X2 - X1X0X2X1Y3 + X0X1X3Y2X1 - X\
0X1X0X3Y3 - X0X1X0
 X1X2X3Y2X2 - X1X2X1Y1X3 - X1X2X1X3Y2 + X1X0X2Y2X2 + X0X1X2Y0X1 + X0X1X2X1Y2 -\
 X1X0X2
 - 2X2X1X3tD_(w^2,4) - 2X2X1X3tD_(w^2,2) - 2X2X1X3tD_(w^2,0) - X2X1X3tD_(w,5) \
- X2X1X3tD_(w,4) - X2X1X3tD_(w,3) - X2X1X3tD_(w,2) - X2X1X3tD_(w,1) - X2X1X3tD\
_(w,0) - X2X1X3tD_(1,5) - X2X1X3tD_(1,4) - X2X1X3tD_(1,3) - X2X1X3tD_(1,2) - X\
2X1X3tD_(1,1) - X2X1X3tD_(1,0) - X2X1X3tD_(0,5) - X2X1X3tD_(0,4) - X2X1X3tD_(0\
,3) - X2X1X3tD_(0,2) - X2X1X3tD_(0,1) - X2X1X3tDe - X2X1X0Y2X2 - X1X0X2Y2X2 + \
X0X2X1Y2X2 + X0X1X3Y2X2 - X0X1X2Y0X1 - X0X1X2X1Y2 + X2X1X3t + 2X1X0X2 - X0X2X1\
 - X0X1X3
 X2X1X3Y3X1 - X2X1X0Y2X3 - X2X1X0X3Y0 + X0X2X3Y1X2 - X0X2X1X3Y0 + X1X0X3
 X1X2X1X3tD_(w,5) - X1X2X1X3tD_(w,4) + X1X2X1X3tD_(w,3) - X1X2X1X3tD_(w,2) + X\
1X2X1X3tD_(w,1) - X1X2X1X3tD_(w,0) - X0X2X1X0Y1X1 + X0X1X2X3Y1X1 - X0X1X0X3Y3X\
2 + X0X1X0X2Y1X1 + X0X1X0X2X1Y1 + X0X2X1X0 - X0X1X2X3
 - 2X1X2X1X0tD_(w^2,4) - 2X1X2X1X0tD_(w^2,2) - 2X1X2X1X0tD_(w^2,0) - X1X2X1X0t\
D_(w,5) - X1X2X1X0tD_(w,4) - X1X2X1X0tD_(w,3) - X1X2X1X0tD_(w,2) - X1X2X1X0tD_\
(w,1) - X1X2X1X0tD_(w,0) - X1X2X1X0tD_(1,5) - X1X2X1X0tD_(1,4) - X1X2X1X0tD_(1\
,3) - X1X2X1X0tD_(1,2) - X1X2X1X0tD_(1,1) - X1X2X1X0tD_(1,0) - X1X2X1X0tD_(0,5\
) - X1X2X1X0tD_(0,4) - X1X2X1X0tD_(0,3) - X1X2X1X0tD_(0,2) - X1X2X1X0tD_(0,1) \
- X1X2X1X0tDe - X0X2X1X3Y0X1 + X0X2X1X0X3Y2 + 2X0X1X0X3tD_(w^2,4) + 2X0X1X0X3t\
D_(w^2,2) + 2X0X1X0X3tD_(w^2,0) + X0X1X0X3tD_(w,5) + X0X1X0X3tD_(w,4) + X0X1X0\
X3tD_(w,3) + X0X1X0X3tD_(w,2) + X0X1X0X3tD_(w,1) + X0X1X0X3tD_(w,0) + X0X1X0X3\
tD_(1,5) + X0X1X0X3tD_(1,4) + X0X1X0X3tD_(1,3) + X0X1X0X3tD_(1,2) + X0X1X0X3tD\
_(1,1) + X0X1X0X3tD_(1,0) + X0X1X0X3tD_(0,5) + X0X1X0X3tD_(0,4) + X0X1X0X3tD_(\
0,3) + X0X1X0X3tD_(0,2) + X0X1X0X3tD_(0,1) + X0X1X0X3tDe + X0X1X0X2Y1X3 + X1X2\
X1X0t - X0X1X0X3t
 X2X1X0X2tD_(w,5) - X2X1X0X2tD_(w,4) + X2X1X0X2tD_(w,3) - X2X1X0X2tD_(w,2) + X\
2X1X0X2tD_(w,1) - X2X1X0X2tD_(w,0) + X1X2X1X3tD_(w,5) - X1X2X1X3tD_(w,4) + X1X\
2X1X3tD_(w,3) - X1X2X1X3tD_(w,2) + X1X2X1X3tD_(w,1) - X1X2X1X3tD_(w,0) - X0X1X\
2X3Y1X1 + X0X1X2X1tD_(w,5) - X0X1X2X1tD_(w,4) + X0X1X2X1tD_(w,3) - X0X1X2X1tD_\
(w,2) + X0X1X2X1tD_(w,1) - X0X1X2X1tD_(w,0) - X0X1X0X3Y3X2 + X0X1X0X2X1Y1 - X0\
X2X1X0 + X0X1X2X3
 X2X1X0X3tD_(0,5) - X2X1X0X3tD_(0,4) + X2X1X0X3tD_(0,3) - X2X1X0X3tD_(0,2) + X\
2X1X0X3tD_(0,1) - X2X1X0X3tDe - X0X1X2X3Y1X2 + X0X1X2X1Y2X3 + X0X1X2X1X3Y0 - X\
0X1X0X2Y1X2 - X0X2X1X3
 - X2X1X0X3tD_(0,5) + X2X1X0X3tD_(0,4) - X2X1X0X3tD_(0,3) + X2X1X0X3tD_(0,2) -\
 X2X1X0X3tD_(0,1) + X2X1X0X3tDe + X1X0X2X3tD_(0,5) - X1X0X2X3tD_(0,4) + X1X0X2\
X3tD_(0,3) - X1X0X2X3tD_(0,2) + X1X0X2X3tD_(0,1) - X1X0X2X3tDe - X0X2X1X3tD_(0\
,5) + X0X2X1X3tD_(0,4) - X0X2X1X3tD_(0,3) + X0X2X1X3tD_(0,2) - X0X2X1X3tD_(0,1\
) + X0X2X1X3tDe + X0X2X1X0Y1X2 + X0X1X0X2Y1X2
 - 2X1X0X2X1tD_(w^2,4) - 2X1X0X2X1tD_(w^2,2) - 2X1X0X2X1tD_(w^2,0) - X1X0X2X1t\
D_(w,5) - X1X0X2X1tD_(w,4) - X1X0X2X1tD_(w,3) - X1X0X2X1tD_(w,2) - X1X0X2X1tD_\
(w,1) - X1X0X2X1tD_(w,0) - X1X0X2X1tD_(1,5) - X1X0X2X1tD_(1,4) - X1X0X2X1tD_(1\
,3) - X1X0X2X1tD_(1,2) - X1X0X2X1tD_(1,1) - X1X0X2X1tD_(1,0) - X1X0X2X1tD_(0,5\
) - X1X0X2X1tD_(0,4) - X1X0X2X1tD_(0,3) - X1X0X2X1tD_(0,2) - X1X0X2X1tD_(0,1) \
- X1X0X2X1tDe - X0X2X1X3Y0X1 + X0X2X1X0Y1X3 + X0X2X1X0X3Y2 - 2X0X1X0X3tD_(w^2,\
4) - 2X0X1X0X3tD_(w^2,2) - 2X0X1X0X3tD_(w^2,0) - X0X1X0X3tD_(w,5) - X0X1X0X3tD\
_(w,4) - X0X1X0X3tD_(w,3) - X0X1X0X3tD_(w,2) - X0X1X0X3tD_(w,1) - X0X1X0X3tD_(\
w,0) - X0X1X0X3tD_(1,5) - X0X1X0X3tD_(1,4) - X0X1X0X3tD_(1,3) - X0X1X0X3tD_(1,\
2) - X0X1X0X3tD_(1,1) - X0X1X0X3tD_(1,0) - X0X1X0X3tD_(0,5) - X0X1X0X3tD_(0,4)\
 - X0X1X0X3tD_(0,3) - X0X1X0X3tD_(0,2) - X0X1X0X3tD_(0,1) - X0X1X0X3tDe + X1X0\
X2X1t + X0X1X0X3t
 X2X1X0X3Y0X1 - 2X1X2X1X0tD_(w^2,4) - 2X1X2X1X0tD_(w^2,2) - 2X1X2X1X0tD_(w^2,0\
) - X1X2X1X0tD_(w,5) - X1X2X1X0tD_(w,4) - X1X2X1X0tD_(w,3) - X1X2X1X0tD_(w,2) \
- X1X2X1X0tD_(w,1) - X1X2X1X0tD_(w,0) - X1X2X1X0tD_(1,5) - X1X2X1X0tD_(1,4) - \
X1X2X1X0tD_(1,3) - X1X2X1X0tD_(1,2) - X1X2X1X0tD_(1,1) - X1X2X1X0tD_(1,0) - X1\
X2X1X0tD_(0,5) - X1X2X1X0tD_(0,4) - X1X2X1X0tD_(0,3) - X1X2X1X0tD_(0,2) - X1X2\
X1X0tD_(0,1) - X1X2X1X0tDe - X1X0X2X3Y0X1 - 2X1X0X2X1tD_(w^2,4) - 2X1X0X2X1tD_\
(w^2,2) - 2X1X0X2X1tD_(w^2,0) - X1X0X2X1tD_(w,5) - X1X0X2X1tD_(w,4) - X1X0X2X1\
tD_(w,3) - X1X0X2X1tD_(w,2) - X1X0X2X1tD_(w,1) - X1X0X2X1tD_(w,0) - X1X0X2X1tD\
_(1,5) - X1X0X2X1tD_(1,4) - X1X0X2X1tD_(1,3) - X1X0X2X1tD_(1,2) - X1X0X2X1tD_(\
1,1) - X1X0X2X1tD_(1,0) - X1X0X2X1tD_(0,5) - X1X0X2X1tD_(0,4) - X1X0X2X1tD_(0,\
3) - X1X0X2X1tD_(0,2) - X1X0X2X1tD_(0,1) - X1X0X2X1tDe - X0X2X1X3Y0X1 + X0X2X1\
X0X3Y2 - X0X1X0X2X3Y2 + X1X2X1X0t + X1X0X2X1t
 X2X1X0X2Y2X1 + X2X1X0X2X1Y3 + X1X2X1X3Y2X1 - X1X2X1X0X3Y3 - X1X0X2X3Y0X2 + X1\
X0X2X1Y3X3 + X1X0X2X1X3Y3 + X0X1X0X3
 - X1X2X1X3tD_(w,5) + X1X2X1X3tD_(w,4) - X1X2X1X3tD_(w,3) + X1X2X1X3tD_(w,2) -\
 X1X2X1X3tD_(w,1) + X1X2X1X3tD_(w,0) + X1X2X1X0Y3X2 - X1X0X2X1Y3X2 - X0X1X2X3Y\
1X1 + X0X1X2X1X0Y1 - X0X1X0X3Y3X2 + X0X1X2X3 - X0X1X0X2
 - X1X2X1X3Y2X1 + X1X2X1X0Y3X3 + X1X2X1X0X3Y3 - X1X0X2X3Y0X2 + X1X0X2X1X3Y3 - \
X0X1X2X1Y2X1 - X0X1X0X3
 - X2X1X0X3Y0X2 + X2X1X0X2Y2X1 + X2X1X0X2X1Y3 - X1X2X1X0X3Y3 - X1X0X2X3Y0X2 + \
X1X0X2X1X3Y3 + X0X2X1X3Y0X2 - X0X1X2X1Y2X1 + X1X2X1X0 + X1X0X2X1
 - X2X1X0X3tD_(0,5) + X2X1X0X3tD_(0,4) - X2X1X0X3tD_(0,3) + X2X1X0X3tD_(0,2) -\
 X2X1X0X3tD_(0,1) + X2X1X0X3tDe + X2X1X0X2Y2X3 + X0X2X1X0Y1X2 + X0X2X1X0X2Y0 -\
 X0X1X2X3Y1X2 + X0X1X2X1X3Y0 - X2X1X0X3 + X1X0X2X3
 - X1X2X1X0X2tD_(1,5) + X1X2X1X0X2tD_(1,4) - X1X2X1X0X2tD_(1,3) + X1X2X1X0X2tD\
_(1,2) - X1X2X1X0X2tD_(1,1) + X1X2X1X0X2tD_(1,0) - X0X2X1X0X3Y2X1 + X0X1X0X2X3\
Y2X1 - X0X1X0X2X1tD_(1,5) + X0X1X0X2X1tD_(1,4) - X0X1X0X2X1tD_(1,3) + X0X1X0X2\
X1tD_(1,2) - X0X1X0X2X1tD_(1,1) + X0X1X0X2X1tD_(1,0)
 2X1X2X1X0X3tD_(w^2,4) + 2X1X2X1X0X3tD_(w^2,2) + 2X1X2X1X0X3tD_(w^2,0) + X1X2X\
1X0X3tD_(w,5) + X1X2X1X0X3tD_(w,4) + X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD_(w,2) +\
 X1X2X1X0X3tD_(w,1) + X1X2X1X0X3tD_(w,0) + X1X2X1X0X3tD_(1,5) + X1X2X1X0X3tD_(\
1,4) + X1X2X1X0X3tD_(1,3) + X1X2X1X0X3tD_(1,2) + X1X2X1X0X3tD_(1,1) + X1X2X1X0\
X3tD_(1,0) + X1X2X1X0X3tD_(0,5) + X1X2X1X0X3tD_(0,4) + X1X2X1X0X3tD_(0,3) + X1\
X2X1X0X3tD_(0,2) + X1X2X1X0X3tD_(0,1) + X1X2X1X0X3tDe - X0X2X1X0X2Y0X1 - X0X2X\
1X0X2X1Y2 - X0X1X2X1X3Y0X1 + X0X1X2X1X0X3Y2 + X0X1X0X2X3Y2X2 - X0X1X0X2X1Y1X3 \
- X0X1X0X2X1X3Y2 - X1X2X1X0X3t
 X2X1X0X2X3tD_(0,5) - X2X1X0X2X3tD_(0,4) + X2X1X0X2X3tD_(0,3) - X2X1X0X2X3tD_(\
0,2) + X2X1X0X2X3tD_(0,1) - X2X1X0X2X3tDe + X0X1X2X1X3tD_(0,5) - X0X1X2X1X3tD_\
(0,4) + X0X1X2X1X3tD_(0,3) - X0X1X2X1X3tD_(0,2) + X0X1X2X1X3tD_(0,1) - X0X1X2X\
1X3tDe - X0X1X2X1X0Y1X2 + X0X1X0X2X1Y1X2 - X0X2X1X0X2
 - 2X2X1X0X2X1tD_(w^2,4) - 2X2X1X0X2X1tD_(w^2,2) - 2X2X1X0X2X1tD_(w^2,0) - X2X\
1X0X2X1tD_(w,5) - X2X1X0X2X1tD_(w,4) - X2X1X0X2X1tD_(w,3) - X2X1X0X2X1tD_(w,2)\
 - X2X1X0X2X1tD_(w,1) - X2X1X0X2X1tD_(w,0) - X2X1X0X2X1tD_(1,5) - X2X1X0X2X1tD\
_(1,4) - X2X1X0X2X1tD_(1,3) - X2X1X0X2X1tD_(1,2) - X2X1X0X2X1tD_(1,1) - X2X1X0\
X2X1tD_(1,0) - X2X1X0X2X1tD_(0,5) - X2X1X0X2X1tD_(0,4) - X2X1X0X2X1tD_(0,3) - \
X2X1X0X2X1tD_(0,2) - X2X1X0X2X1tD_(0,1) - X2X1X0X2X1tDe + 2X1X2X1X0X3tD_(w^2,4\
) + 2X1X2X1X0X3tD_(w^2,2) + 2X1X2X1X0X3tD_(w^2,0) + X1X2X1X0X3tD_(w,5) + X1X2X\
1X0X3tD_(w,4) + X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD_(w,2) + X1X2X1X0X3tD_(w,1) +\
 X1X2X1X0X3tD_(w,0) + X1X2X1X0X3tD_(1,5) + X1X2X1X0X3tD_(1,4) + X1X2X1X0X3tD_(\
1,3) + X1X2X1X0X3tD_(1,2) + X1X2X1X0X3tD_(1,1) + X1X2X1X0X3tD_(1,0) + X1X2X1X0\
X3tD_(0,5) + X1X2X1X0X3tD_(0,4) + X1X2X1X0X3tD_(0,3) + X1X2X1X0X3tD_(0,2) + X1\
X2X1X0X3tD_(0,1) + X1X2X1X0X3tDe + X0X1X2X1X3Y0X1 - X0X1X2X1X0Y1X3 - X0X1X2X1X\
0X3Y2 + X0X1X0X2X3Y2X2 - X0X1X0X2X1X3Y2 + X2X1X0X2X1t - X1X2X1X0X3t - X0X2X1X0\
X3 - X0X1X0X2X3
 - 2X2X1X0X2X1tD_(w^2,4) - 2X2X1X0X2X1tD_(w^2,2) - 2X2X1X0X2X1tD_(w^2,0) - X2X\
1X0X2X1tD_(w,5) - X2X1X0X2X1tD_(w,4) - X2X1X0X2X1tD_(w,3) - X2X1X0X2X1tD_(w,2)\
 - X2X1X0X2X1tD_(w,1) - X2X1X0X2X1tD_(w,0) - X2X1X0X2X1tD_(1,5) - X2X1X0X2X1tD\
_(1,4) - X2X1X0X2X1tD_(1,3) - X2X1X0X2X1tD_(1,2) - X2X1X0X2X1tD_(1,1) - X2X1X0\
X2X1tD_(1,0) - X2X1X0X2X1tD_(0,5) - X2X1X0X2X1tD_(0,4) - X2X1X0X2X1tD_(0,3) - \
X2X1X0X2X1tD_(0,2) - X2X1X0X2X1tD_(0,1) - X2X1X0X2X1tDe + 2X1X2X1X0X3tD_(w^2,4\
) + 2X1X2X1X0X3tD_(w^2,2) + 2X1X2X1X0X3tD_(w^2,0) + X1X2X1X0X3tD_(w,5) + X1X2X\
1X0X3tD_(w,4) + X1X2X1X0X3tD_(w,3) + X1X2X1X0X3tD_(w,2) + X1X2X1X0X3tD_(w,1) +\
 X1X2X1X0X3tD_(w,0) + X1X2X1X0X3tD_(1,5) + X1X2X1X0X3tD_(1,4) + X1X2X1X0X3tD_(\
1,3) + X1X2X1X0X3tD_(1,2) + X1X2X1X0X3tD_(1,1) + X1X2X1X0X3tD_(1,0) + X1X2X1X0\
X3tD_(0,5) + X1X2X1X0X3tD_(0,4) + X1X2X1X0X3tD_(0,3) + X1X2X1X0X3tD_(0,2) + X1\
X2X1X0X3tD_(0,1) + X1X2X1X0X3tDe + 2X1X0X2X1X3tD_(w^2,4) + 2X1X0X2X1X3tD_(w^2,\
2) + 2X1X0X2X1X3tD_(w^2,0) + X1X0X2X1X3tD_(w,5) + X1X0X2X1X3tD_(w,4) + X1X0X2X\
1X3tD_(w,3) + X1X0X2X1X3tD_(w,2) + X1X0X2X1X3tD_(w,1) + X1X0X2X1X3tD_(w,0) + X\
1X0X2X1X3tD_(1,5) + X1X0X2X1X3tD_(1,4) + X1X0X2X1X3tD_(1,3) + X1X0X2X1X3tD_(1,\
2) + X1X0X2X1X3tD_(1,1) + X1X0X2X1X3tD_(1,0) + X1X0X2X1X3tD_(0,5) + X1X0X2X1X3\
tD_(0,4) + X1X0X2X1X3tD_(0,3) + X1X0X2X1X3tD_(0,2) + X1X0X2X1X3tD_(0,1) + X1X0\
X2X1X3tDe + X0X2X1X0X3Y2X2 - X0X2X1X0X2Y0X1 - X0X2X1X0X2X1Y2 + X0X1X2X1X0X3Y2 \
+ X0X1X0X2X3Y2X2 - X0X1X0X2X1X3Y2 + X2X1X0X2X1t - X1X2X1X0X3t - X1X0X2X1X3t - \
X0X2X1X0X3 - X0X1X0X2X3
 - X1X0X2X1X0tD_(w,5) + X1X0X2X1X0tD_(w,4) - X1X0X2X1X0tD_(w,3) + X1X0X2X1X0tD\
_(w,2) - X1X0X2X1X0tD_(w,1) + X1X0X2X1X0tD_(w,0) + X0X2X1X0X3tD_(w,5) - X0X2X1\
X0X3tD_(w,4) + X0X2X1X0X3tD_(w,3) - X0X2X1X0X3tD_(w,2) + X0X2X1X0X3tD_(w,1) - \
X0X2X1X0X3tD_(w,0) - X0X2X1X0X2Y0X3 + X0X1X0X2X3tD_(w,5) - X0X1X0X2X3tD_(w,4) \
+ X0X1X0X2X3tD_(w,3) - X0X1X0X2X3tD_(w,2) + X0X1X0X2X3tD_(w,1) - X0X1X0X2X3tD_\
(w,0)
 - X2X1X0X2X3Y0X1 - 2X1X2X1X0X3tD_(w^2,4) - 2X1X2X1X0X3tD_(w^2,2) - 2X1X2X1X0X\
3tD_(w^2,0) - X1X2X1X0X3tD_(w,5) - X1X2X1X0X3tD_(w,4) - X1X2X1X0X3tD_(w,3) - X\
1X2X1X0X3tD_(w,2) - X1X2X1X0X3tD_(w,1) - X1X2X1X0X3tD_(w,0) - X1X2X1X0X3tD_(1,\
5) - X1X2X1X0X3tD_(1,4) - X1X2X1X0X3tD_(1,3) - X1X2X1X0X3tD_(1,2) - X1X2X1X0X3\
tD_(1,1) - X1X2X1X0X3tD_(1,0) - X1X2X1X0X3tD_(0,5) - X1X2X1X0X3tD_(0,4) - X1X2\
X1X0X3tD_(0,3) - X1X2X1X0X3tD_(0,2) - X1X2X1X0X3tD_(0,1) - X1X2X1X0X3tDe + X1X\
2X1X0X2X3Y2 - 2X1X0X2X1X3tD_(w^2,4) - 2X1X0X2X1X3tD_(w^2,2) - 2X1X0X2X1X3tD_(w\
^2,0) - X1X0X2X1X3tD_(w,5) - X1X0X2X1X3tD_(w,4) - X1X0X2X1X3tD_(w,3) - X1X0X2X\
1X3tD_(w,2) - X1X0X2X1X3tD_(w,1) - X1X0X2X1X3tD_(w,0) - X1X0X2X1X3tD_(1,5) - X\
1X0X2X1X3tD_(1,4) - X1X0X2X1X3tD_(1,3) - X1X0X2X1X3tD_(1,2) - X1X0X2X1X3tD_(1,\
1) - X1X0X2X1X3tD_(1,0) - X1X0X2X1X3tD_(0,5) - X1X0X2X1X3tD_(0,4) - X1X0X2X1X3\
tD_(0,3) - X1X0X2X1X3tD_(0,2) - X1X0X2X1X3tD_(0,1) - X1X0X2X1X3tDe - X1X0X2X1X\
0Y2X2 - X1X0X2X1X0X2Y2 + X0X2X1X0X2Y0X1 + X0X1X2X1X3Y0X1 - X0X1X2X1X0X3Y2 + X1\
X2X1X0X3t + X1X0X2X1X3t
 - X2X1X0X2X1Y3X1 + X1X2X1X0X3Y3X1 + X1X0X2X1X3Y3X1 - X1X0X2X1X0Y2X3 - X1X0X2X\
1X0X3Y0
 X1X2X1X0X3Y3X2 - X1X2X1X0X2Y1X1 - X1X2X1X0X2X1Y1 - X1X0X2X1X3Y3X2 + X0X1X2X1X\
0Y1X1 - X0X1X2X1X0 - X0X1X0X2X1
 - 2X1X2X1X0X3tD_(w^2,4) - 2X1X2X1X0X3tD_(w^2,2) - 2X1X2X1X0X3tD_(w^2,0) - X1X\
2X1X0X3tD_(w,5) - X1X2X1X0X3tD_(w,4) - X1X2X1X0X3tD_(w,3) - X1X2X1X0X3tD_(w,2)\
 - X1X2X1X0X3tD_(w,1) - X1X2X1X0X3tD_(w,0) - X1X2X1X0X3tD_(1,5) - X1X2X1X0X3tD\
_(1,4) - X1X2X1X0X3tD_(1,3) - X1X2X1X0X3tD_(1,2) - X1X2X1X0X3tD_(1,1) - X1X2X1\
X0X3tD_(1,0) - X1X2X1X0X3tD_(0,5) - X1X2X1X0X3tD_(0,4) - X1X2X1X0X3tD_(0,3) - \
X1X2X1X0X3tD_(0,2) - X1X2X1X0X3tD_(0,1) - X1X2X1X0X3tDe - X1X2X1X0X2Y1X3 - X1X\
0X2X1X0Y2X2 - X1X0X2X1X0X2Y2 + X0X1X2X1X3Y0X1 - X0X1X2X1X0X3Y2 + X0X1X0X2X3Y2X\
2 - X0X1X0X2X1X3Y2 + X1X2X1X0X3t + X1X0X2X1X0 - 2X0X1X0X2X3
 X2X1X0X2X3Y0X2 - X2X1X0X2X1Y3X3 - X2X1X0X2X1X3Y3 - X0X2X1X0X2Y0X2 - X0X1X2X1X\
3Y0X2 + X1X2X1X0X3 + X1X0X2X1X3
 - X1X2X1X0X2X3tD_(w,5) + X1X2X1X0X2X3tD_(w,4) - X1X2X1X0X2X3tD_(w,3) + X1X2X1\
X0X2X3tD_(w,2) - X1X2X1X0X2X3tD_(w,1) + X1X2X1X0X2X3tD_(w,0) + X0X2X1X0X2X3Y1X\
1 - X0X1X2X1X0X2X3Y1 - X0X1X0X2X1X3tD_(w,5) + X0X1X0X2X1X3tD_(w,4) - X0X1X0X2X\
1X3tD_(w,3) + X0X1X0X2X1X3tD_(w,2) - X0X1X0X2X1X3tD_(w,1) + X0X1X0X2X1X3tD_(w,\
0) + X0X1X0X2X1X0Y3X2 + X0X1X0X2X1X0X2Y1 - X0X2X1X0X2X3
 - X1X2X1X0X2X1tD_(1,5) + X1X2X1X0X2X1tD_(1,4) - X1X2X1X0X2X1tD_(1,3) + X1X2X1\
X0X2X1tD_(1,2) - X1X2X1X0X2X1tD_(1,1) + X1X2X1X0X2X1tD_(1,0) + X0X2X1X0X2X1Y2X\
1 - X0X1X2X1X0X3Y2X1 - X0X1X0X2X1X3Y2X1 + X0X1X0X2X1X0Y3X3 + X0X1X0X2X1X0X3Y3
 2X2X1X0X2X1X3tD_(w^2,4) + 2X2X1X0X2X1X3tD_(w^2,2) + 2X2X1X0X2X1X3tD_(w^2,0) +\
 X2X1X0X2X1X3tD_(w,5) + X2X1X0X2X1X3tD_(w,4) + X2X1X0X2X1X3tD_(w,3) + X2X1X0X2\
X1X3tD_(w,2) + X2X1X0X2X1X3tD_(w,1) + X2X1X0X2X1X3tD_(w,0) + X2X1X0X2X1X3tD_(1\
,5) + X2X1X0X2X1X3tD_(1,4) + X2X1X0X2X1X3tD_(1,3) + X2X1X0X2X1X3tD_(1,2) + X2X\
1X0X2X1X3tD_(1,1) + X2X1X0X2X1X3tD_(1,0) + X2X1X0X2X1X3tD_(0,5) + X2X1X0X2X1X3\
tD_(0,4) + X2X1X0X2X1X3tD_(0,3) + X2X1X0X2X1X3tD_(0,2) + X2X1X0X2X1X3tD_(0,1) \
+ X2X1X0X2X1X3tDe - X0X1X2X1X0X3Y2X2 + X0X1X2X1X0X2Y0X1 + X0X1X2X1X0X2X1Y2 + X\
0X1X0X2X1X3Y2X2 - X2X1X0X2X1X3t - X0X2X1X0X2X1 + X0X1X2X1X0X3 - X0X1X0X2X1X3
 - X1X2X1X0X2X3tD_(w,5) + X1X2X1X0X2X3tD_(w,4) - X1X2X1X0X2X3tD_(w,3) + X1X2X1\
X0X2X3tD_(w,2) - X1X2X1X0X2X3tD_(w,1) + X1X2X1X0X2X3tD_(w,0) + X1X0X2X1X0X2tD_\
(w,5) - X1X0X2X1X0X2tD_(w,4) + X1X0X2X1X0X2tD_(w,3) - X1X0X2X1X0X2tD_(w,2) + X\
1X0X2X1X0X2tD_(w,1) - X1X0X2X1X0X2tD_(w,0) + X0X2X1X0X2X1tD_(w,5) - X0X2X1X0X2\
X1tD_(w,4) + X0X2X1X0X2X1tD_(w,3) - X0X2X1X0X2X1tD_(w,2) + X0X2X1X0X2X1tD_(w,1\
) - X0X2X1X0X2X1tD_(w,0) - X0X1X2X1X0X3tD_(w,5) + X0X1X2X1X0X3tD_(w,4) - X0X1X\
2X1X0X3tD_(w,3) + X0X1X2X1X0X3tD_(w,2) - X0X1X2X1X0X3tD_(w,1) + X0X1X2X1X0X3tD\
_(w,0) + X0X1X2X1X0X2Y0X3 + X0X1X0X2X1X0Y3X2 + X0X1X0X2X1X0X2Y1 - X0X2X1X0X2X3\

 X1X0X2X1X0X3tD_(0,5) - X1X0X2X1X0X3tD_(0,4) + X1X0X2X1X0X3tD_(0,3) - X1X0X2X1\
X0X3tD_(0,2) + X1X0X2X1X0X3tD_(0,1) - X1X0X2X1X0X3tDe - X0X2X1X0X2X3Y1X2 + X0X\
2X1X0X2X1Y2X3 + X0X2X1X0X2X1X3Y0
 X1X2X1X0X2X3Y2X1 - X1X2X1X0X2X1tD_(1,5) + X1X2X1X0X2X1tD_(1,4) - X1X2X1X0X2X1\
tD_(1,3) + X1X2X1X0X2X1tD_(1,2) - X1X2X1X0X2X1tD_(1,1) + X1X2X1X0X2X1tD_(1,0) \
- X1X0X2X1X0X3Y0X2 + X1X0X2X1X0X2X1Y3 - X0X1X2X1X0X3Y2X1 - X0X1X0X2X1X0X3Y3 + \
X0X1X0X2X1X0
 X2X1X0X2X1X3Y3X1 - X1X0X2X1X0X3tD_(0,5) + X1X0X2X1X0X3tD_(0,4) - X1X0X2X1X0X3\
tD_(0,3) + X1X0X2X1X0X3tD_(0,2) - X1X0X2X1X0X3tD_(0,1) + X1X0X2X1X0X3tDe + X1X\
0X2X1X0X2Y2X3 + X1X0X2X1X0X2X3Y0 + X0X2X1X0X2X1X3Y0 - X1X0X2X1X0X3

In [303]:
PrintNPList(List(Y3bis, ys -> ys.prod));

 Y3
 - 2tD_(w^2,4) - 2tD_(w^2,2) - 2tD_(w^2,0) - tD_(w,5) - tD_(w,4) - tD_(w,3) - \
tD_(w,2) - tD_(w,1) - tD_(w,0) - tD_(1,5) - tD_(1,4) - tD_(1,3) - tD_(1,2) - t\
D_(1,1) - tD_(1,0) - tD_(0,5) - tD_(0,4) - tD_(0,3) - tD_(0,2) - tD_(0,1) - tD\
e - X0Y2 + t
 Y3X1
 Y3X2
 Y3X3
 X2tD_(1,5) - X2tD_(1,4) + X2tD_(1,3) - X2tD_(1,2) + X2tD_(1,1) - X2tD_(1,0) -\
 X0Y2X1
 - 2X3tD_(w^2,4) - 2X3tD_(w^2,2) - 2X3tD_(w^2,0) - X3tD_(w,5) - X3tD_(w,4) - X\
3tD_(w,3) - X3tD_(w,2) - X3tD_(w,1) - X3tD_(w,0) - X3tD_(1,5) - X3tD_(1,4) - X\
3tD_(1,3) - X3tD_(1,2) - X3tD_(1,1) - X3tD_(1,0) - X3tD_(0,5) - X3tD_(0,4) - X\
3tD_(0,3) - X3tD_(0,2) - X3tD_(0,1) - X3tDe - X0Y2X2 + X3t
 X1tD_(0,5) - X1tD_(0,4) + X1tD_(0,3) - X1tD_(0,2) + X1tD_(0,1) - X1tDe - X0Y2\
X3
 X3Y3X1 - X1tD_(0,5) + X1tD_(0,4) - X1tD_(0,3) + X1tD_(0,2) - X1tD_(0,1) + X1t\
De - X0X3Y0 - X1
 - X1Y0X2 + X0Y2X1 + X0X1Y3
 X2Y1X1 + X2X1Y1 - X1Y0X3 - X2
 X3Y3X2 - X2Y1X1 - X2X1Y1 - X1X3Y1
 - X2Y1X3 + X0Y2X2 + X0X2Y2 - X0
 2X1X2tD_(w^2,4) + 2X1X2tD_(w^2,2) + 2X1X2tD_(w^2,0) + X1X2tD_(w,5) + X1X2tD_(\
w,4) + X1X2tD_(w,3) + X1X2tD_(w,2) + X1X2tD_(w,1) + X1X2tD_(w,0) + X1X2tD_(1,5\
) + X1X2tD_(1,4) + X1X2tD_(1,3) + X1X2tD_(1,2) + X1X2tD_(1,1) + X1X2tD_(1,0) +\
 X1X2tD_(0,5) + X1X2tD_(0,4) + X1X2tD_(0,3) + X1X2tD_(0,2) + X1X2tD_(0,1) + X1\
X2tDe - X0X3Y0X1 - X1X2t
 X2X3tD_(w,5) - X2X3tD_(w,4) + X2X3tD_(w,3) - X2X3tD_(w,2) + X2X3tD_(w,1) - X2\
X3tD_(w,0) + X0X1Y3X2
 X2X1tD_(1,5) - X2X1tD_(1,4) + X2X1tD_(1,3) - X2X1tD_(1,2) + X2X1tD_(1,1) - X2\
X1tD_(1,0) - X0X2Y2X1 - X0X2X1Y3 + X0X1Y3X3
 - X2X1tD_(1,5) + X2X1tD_(1,4) - X2X1tD_(1,3) + X2X1tD_(1,2) - X2X1tD_(1,1) + \
X2X1tD_(1,0) - X1X3tD_(1,5) + X1X3tD_(1,4) - X1X3tD_(1,3) + X1X3tD_(1,2) - X1X\
3tD_(1,1) + X1X3tD_(1,0) - X0X3Y0X2 + X0X2Y2X1 + X0X2X1Y3 + X0X1X3Y3 - X0X1
 - X1X0tD_(0,5) + X1X0tD_(0,4) - X1X0tD_(0,3) + X1X0tD_(0,2) - X1X0tD_(0,1) + \
X1X0tDe - X0X3tD_(0,5) + X0X3tD_(0,4) - X0X3tD_(0,3) + X0X3tD_(0,2) - X0X3tD_(\
0,1) + X0X3tDe + X0X2Y2X3 - X0X3
 - X2X3Y2X1 + X2X1X0Y3 - X1X3tD_(1,5) + X1X3tD_(1,4) - X1X3tD_(1,3) + X1X3tD_(\
1,2) - X1X3tD_(1,1) + X1X3tD_(1,0) - X1X2X3Y3 + X1X0Y0X2 - X0X2Y2X1 - X0X2X1Y3\
 - X0X1X3Y3 - X1X2
 - X2X1Y1X1 - X1X3Y1X1 + X1X0Y0X3 + X1X0X3Y1 + X2X1
 - X1X3Y1X2 + X1X2Y3X1 + X1X2X1Y0 + X0X1Y3X1
 X1X2Y3X3 - X1X0Y0X2 - X1X0X2Y3 + X0X2Y2X1 + X0X2X1Y3
 - X2X3Y2X1 + X2X1tD_(1,5) - X2X1tD_(1,4) + X2X1tD_(1,3) - X2X1tD_(1,2) + X2X1\
tD_(1,1) - X2X1tD_(1,0) - X1X2X3Y3 - X1X0Y0X2 - X1X0X2Y3 - X0X3Y0X2 + X0X2X1Y3\
 + X1X2 + X0X1
 - X2X3Y2X2 + X2X1Y1X3 + X2X1X3Y2 - X0X2Y2X2 + X0X2
 2X1X2X3tD_(w^2,4) + 2X1X2X3tD_(w^2,2) + 2X1X2X3tD_(w^2,0) + X1X2X3tD_(w,5) + \
X1X2X3tD_(w,4) + X1X2X3tD_(w,3) + X1X2X3tD_(w,2) + X1X2X3tD_(w,1) + X1X2X3tD_(\
w,0) + X1X2X3tD_(1,5) + X1X2X3tD_(1,4) + X1X2X3tD_(1,3) + X1X2X3tD_(1,2) + X1X\
2X3tD_(1,1) + X1X2X3tD_(1,0) + X1X2X3tD_(0,5) + X1X2X3tD_(0,4) + X1X2X3tD_(0,3\
) + X1X2X3tD_(0,2) + X1X2X3tD_(0,1) + X1X2X3tDe + X0X2X3Y0X1 - X0X2X1X0Y2 + X0\
X1X2X3Y2 - X0X1X0Y2X2 - X1X2X3t
 - X1X2X1tD_(0,5) + X1X2X1tD_(0,4) - X1X2X1tD_(0,3) + X1X2X1tD_(0,2) - X1X2X1t\
D_(0,1) + X1X2X1tDe + X0X2X1Y3X1 + X0X1X3Y3X1 - X0X1X0Y2X3 - X0X1X0X3Y0
 - X2X1X3tD_(w,5) + X2X1X3tD_(w,4) - X2X1X3tD_(w,3) + X2X1X3tD_(w,2) - X2X1X3t\
D_(w,1) + X2X1X3tD_(w,0) + X0X1X3Y3X2 - X0X1X2Y1X1 - X0X1X2X1Y1
 2X2X1X0tD_(w^2,4) + 2X2X1X0tD_(w^2,2) + 2X2X1X0tD_(w^2,0) + X2X1X0tD_(w,5) + \
X2X1X0tD_(w,4) + X2X1X0tD_(w,3) + X2X1X0tD_(w,2) + X2X1X0tD_(w,1) + X2X1X0tD_(\
w,0) + X2X1X0tD_(1,5) + X2X1X0tD_(1,4) + X2X1X0tD_(1,3) + X2X1X0tD_(1,2) + X2X\
1X0tD_(1,1) + X2X1X0tD_(1,0) + X2X1X0tD_(0,5) + X2X1X0tD_(0,4) + X2X1X0tD_(0,3\
) + X2X1X0tD_(0,2) + X2X1X0tD_(0,1) + X2X1X0tDe - 2X1X2X3tD_(w^2,4) - 2X1X2X3t\
D_(w^2,2) - 2X1X2X3tD_(w^2,0) - X1X2X3tD_(w,5) - X1X2X3tD_(w,4) - X1X2X3tD_(w,\
3) - X1X2X3tD_(w,2) - X1X2X3tD_(w,1) - X1X2X3tD_(w,0) - X1X2X3tD_(1,5) - X1X2X\
3tD_(1,4) - X1X2X3tD_(1,3) - X1X2X3tD_(1,2) - X1X2X3tD_(1,1) - X1X2X3tD_(1,0) \
- X1X2X3tD_(0,5) - X1X2X3tD_(0,4) - X1X2X3tD_(0,3) - X1X2X3tD_(0,2) - X1X2X3tD\
_(0,1) - X1X2X3tDe - 2X0X1X3tD_(w^2,4) - 2X0X1X3tD_(w^2,2) - 2X0X1X3tD_(w^2,0)\
 - X0X1X3tD_(w,5) - X0X1X3tD_(w,4) - X0X1X3tD_(w,3) - X0X1X3tD_(w,2) - X0X1X3t\
D_(w,1) - X0X1X3tD_(w,0) - X0X1X3tD_(1,5) - X0X1X3tD_(1,4) - X0X1X3tD_(1,3) - \
X0X1X3tD_(1,2) - X0X1X3tD_(1,1) - X0X1X3tD_(1,0) - X0X1X3tD_(0,5) - X0X1X3tD_(\
0,4) - X0X1X3tD_(0,3) - X0X1X3tD_(0,2) - X0X1X3tD_(0,1) - X0X1X3tDe - X0X1X2Y1\
X3 + X0X1X0Y2X2 + X0X1X0X2Y2 - X2X1X0t + X1X2X3t + X0X1X3t - X0X1X0
 2X2X1X0tD_(w^2,4) + 2X2X1X0tD_(w^2,2) + 2X2X1X0tD_(w^2,0) + X2X1X0tD_(w,5) + \
X2X1X0tD_(w,4) + X2X1X0tD_(w,3) + X2X1X0tD_(w,2) + X2X1X0tD_(w,1) + X2X1X0tD_(\
w,0) + X2X1X0tD_(1,5) + X2X1X0tD_(1,4) + X2X1X0tD_(1,3) + X2X1X0tD_(1,2) + X2X\
1X0tD_(1,1) + X2X1X0tD_(1,0) + X2X1X0tD_(0,5) + X2X1X0tD_(0,4) + X2X1X0tD_(0,3\
) + X2X1X0tD_(0,2) + X2X1X0tD_(0,1) + X2X1X0tDe - 2X1X2X3tD_(w^2,4) - 2X1X2X3t\
D_(w^2,2) - 2X1X2X3tD_(w^2,0) - X1X2X3tD_(w,5) - X1X2X3tD_(w,4) - X1X2X3tD_(w,\
3) - X1X2X3tD_(w,2) - X1X2X3tD_(w,1) - X1X2X3tD_(w,0) - X1X2X3tD_(1,5) - X1X2X\
3tD_(1,4) - X1X2X3tD_(1,3) - X1X2X3tD_(1,2) - X1X2X3tD_(1,1) - X1X2X3tD_(1,0) \
- X1X2X3tD_(0,5) - X1X2X3tD_(0,4) - X1X2X3tD_(0,3) - X1X2X3tD_(0,2) - X1X2X3tD\
_(0,1) - X1X2X3tDe - 2X1X0X2tD_(w^2,4) - 2X1X0X2tD_(w^2,2) - 2X1X0X2tD_(w^2,0)\
 - X1X0X2tD_(w,5) - X1X0X2tD_(w,4) - X1X0X2tD_(w,3) - X1X0X2tD_(w,2) - X1X0X2t\
D_(w,1) - X1X0X2tD_(w,0) - X1X0X2tD_(1,5) - X1X0X2tD_(1,4) - X1X0X2tD_(1,3) - \
X1X0X2tD_(1,2) - X1X0X2tD_(1,1) - X1X0X2tD_(1,0) - X1X0X2tD_(0,5) - X1X0X2tD_(\
0,4) - X1X0X2tD_(0,3) - X1X0X2tD_(0,2) - X1X0X2tD_(0,1) - X1X0X2tDe + X0X2X3Y0\
X1 + 2X0X2X1tD_(w^2,4) + 2X0X2X1tD_(w^2,2) + 2X0X2X1tD_(w^2,0) + X0X2X1tD_(w,5\
) + X0X2X1tD_(w,4) + X0X2X1tD_(w,3) + X0X2X1tD_(w,2) + X0X2X1tD_(w,1) + X0X2X1\
tD_(w,0) + X0X2X1tD_(1,5) + X0X2X1tD_(1,4) + X0X2X1tD_(1,3) + X0X2X1tD_(1,2) +\
 X0X2X1tD_(1,1) + X0X2X1tD_(1,0) + X0X2X1tD_(0,5) + X0X2X1tD_(0,4) + X0X2X1tD_\
(0,3) + X0X2X1tD_(0,2) + X0X2X1tD_(0,1) + X0X2X1tDe + X0X1X2X3Y2 + X0X1X0Y2X2 \
+ X0X1X0X2Y2 - X2X1X0t + X1X2X3t + X1X0X2t - X0X2X1t - 2X0X1X0
 X1X0X3tD_(1,5) - X1X0X3tD_(1,4) + X1X0X3tD_(1,3) - X1X0X3tD_(1,2) + X1X0X3tD_\
(1,1) - X1X0X3tD_(1,0) + X0X2X3Y0X2 - X0X2X1Y3X3 - X0X2X1X3Y3 - X0X1X3
 X2X1X0Y3X1 - X1X2X3Y3X1 + X1X2X1tD_(0,5) - X1X2X1tD_(0,4) + X1X2X1tD_(0,3) - \
X1X2X1tD_(0,2) + X1X2X1tD_(0,1) - X1X2X1tDe + X1X0X3Y1X2 - X1X0X2Y3X1 - X1X0X2\
X1Y0 - X0X2X1Y3X1 - X0X1X3Y3X1 - X0X1X0X3Y0 - X1X2X1
 X2X1X3Y2X1 - X2X1X0X3Y3 + X1X0X3tD_(1,5) - X1X0X3tD_(1,4) + X1X0X3tD_(1,3) - \
X1X0X3tD_(1,2) + X1X0X3tD_(1,1) - X1X0X3tD_(1,0) - X1X0X2Y3X3 - X1X2X3
 X1X2X3Y3X1 - X1X2X1tD_(0,5) + X1X2X1tD_(0,4) - X1X2X1tD_(0,3) + X1X2X1tD_(0,2\
) - X1X2X1tD_(0,1) + X1X2X1tDe + X1X0X3Y1X2 - X1X0X2X1Y0 + X0X1X3Y3X1 - X0X1X0\
X3Y0 - X1X2X1
 X1X2X3Y3X2 - X1X2X1Y0X3 - X1X2X1X3Y1 + X1X0X2Y3X2 + X0X1X2Y1X1 + X0X1X2X1Y1 -\
 X0X1X2
 X2X1X3tD_(w,5) - X2X1X3tD_(w,4) + X2X1X3tD_(w,3) - X2X1X3tD_(w,2) + X2X1X3tD_\
(w,1) - X2X1X3tD_(w,0) - X2X1X0Y3X2 - X1X0X2Y3X2 + X0X2X1Y3X2 + X0X1X3Y3X2 - X\
0X1X2Y1X1 - X0X1X2X1Y1 + 2X0X1X2
 X2X1X3Y2X1 - X2X1X0Y3X3 - X2X1X0X3Y3 + X0X2X3Y0X2 - X0X2X1X3Y3 + X1X2X3 + X0X\
1X3
 X1X2X1X3tD_(1,5) - X1X2X1X3tD_(1,4) + X1X2X1X3tD_(1,3) - X1X2X1X3tD_(1,2) + X\
1X2X1X3tD_(1,1) - X1X2X1X3tD_(1,0) - X0X2X1X0Y2X1 + X0X1X2X3Y2X1 - X0X1X0X3Y0X\
2 + X0X1X0X2Y2X1 + X0X1X0X2X1Y3
 X1X2X1X0tD_(0,5) - X1X2X1X0tD_(0,4) + X1X2X1X0tD_(0,3) - X1X2X1X0tD_(0,2) + X\
1X2X1X0tD_(0,1) - X1X2X1X0tDe - X0X2X1X3Y3X1 + X0X2X1X0X3Y0 - X0X1X0X3tD_(0,5)\
 + X0X1X0X3tD_(0,4) - X0X1X0X3tD_(0,3) + X0X1X0X3tD_(0,2) - X0X1X0X3tD_(0,1) +\
 X0X1X0X3tDe + X0X1X0X2Y2X3 - X0X1X0X3
 X2X1X0X2tD_(1,5) - X2X1X0X2tD_(1,4) + X2X1X0X2tD_(1,3) - X2X1X0X2tD_(1,2) + X\
2X1X0X2tD_(1,1) - X2X1X0X2tD_(1,0) + X1X2X1X3tD_(1,5) - X1X2X1X3tD_(1,4) + X1X\
2X1X3tD_(1,3) - X1X2X1X3tD_(1,2) + X1X2X1X3tD_(1,1) - X1X2X1X3tD_(1,0) - X0X1X\
2X3Y2X1 + X0X1X2X1tD_(1,5) - X0X1X2X1tD_(1,4) + X0X1X2X1tD_(1,3) - X0X1X2X1tD_\
(1,2) + X0X1X2X1tD_(1,1) - X0X1X2X1tD_(1,0) - X0X1X0X3Y0X2 + X0X1X0X2X1Y3
 - 2X2X1X0X3tD_(w^2,4) - 2X2X1X0X3tD_(w^2,2) - 2X2X1X0X3tD_(w^2,0) - X2X1X0X3t\
D_(w,5) - X2X1X0X3tD_(w,4) - X2X1X0X3tD_(w,3) - X2X1X0X3tD_(w,2) - X2X1X0X3tD_\
(w,1) - X2X1X0X3tD_(w,0) - X2X1X0X3tD_(1,5) - X2X1X0X3tD_(1,4) - X2X1X0X3tD_(1\
,3) - X2X1X0X3tD_(1,2) - X2X1X0X3tD_(1,1) - X2X1X0X3tD_(1,0) - X2X1X0X3tD_(0,5\
) - X2X1X0X3tD_(0,4) - X2X1X0X3tD_(0,3) - X2X1X0X3tD_(0,2) - X2X1X0X3tD_(0,1) \
- X2X1X0X3tDe - X0X1X2X3Y2X2 + X0X1X2X1Y1X3 + X0X1X2X1X3Y2 - X0X1X0X2Y2X2 + X2\
X1X0X3t + X0X1X0X2
 2X2X1X0X3tD_(w^2,4) + 2X2X1X0X3tD_(w^2,2) + 2X2X1X0X3tD_(w^2,0) + X2X1X0X3tD_\
(w,5) + X2X1X0X3tD_(w,4) + X2X1X0X3tD_(w,3) + X2X1X0X3tD_(w,2) + X2X1X0X3tD_(w\
,1) + X2X1X0X3tD_(w,0) + X2X1X0X3tD_(1,5) + X2X1X0X3tD_(1,4) + X2X1X0X3tD_(1,3\
) + X2X1X0X3tD_(1,2) + X2X1X0X3tD_(1,1) + X2X1X0X3tD_(1,0) + X2X1X0X3tD_(0,5) \
+ X2X1X0X3tD_(0,4) + X2X1X0X3tD_(0,3) + X2X1X0X3tD_(0,2) + X2X1X0X3tD_(0,1) + \
X2X1X0X3tDe - 2X1X0X2X3tD_(w^2,4) - 2X1X0X2X3tD_(w^2,2) - 2X1X0X2X3tD_(w^2,0) \
- X1X0X2X3tD_(w,5) - X1X0X2X3tD_(w,4) - X1X0X2X3tD_(w,3) - X1X0X2X3tD_(w,2) - \
X1X0X2X3tD_(w,1) - X1X0X2X3tD_(w,0) - X1X0X2X3tD_(1,5) - X1X0X2X3tD_(1,4) - X1\
X0X2X3tD_(1,3) - X1X0X2X3tD_(1,2) - X1X0X2X3tD_(1,1) - X1X0X2X3tD_(1,0) - X1X0\
X2X3tD_(0,5) - X1X0X2X3tD_(0,4) - X1X0X2X3tD_(0,3) - X1X0X2X3tD_(0,2) - X1X0X2\
X3tD_(0,1) - X1X0X2X3tDe + 2X0X2X1X3tD_(w^2,4) + 2X0X2X1X3tD_(w^2,2) + 2X0X2X1\
X3tD_(w^2,0) + X0X2X1X3tD_(w,5) + X0X2X1X3tD_(w,4) + X0X2X1X3tD_(w,3) + X0X2X1\
X3tD_(w,2) + X0X2X1X3tD_(w,1) + X0X2X1X3tD_(w,0) + X0X2X1X3tD_(1,5) + X0X2X1X3\
tD_(1,4) + X0X2X1X3tD_(1,3) + X0X2X1X3tD_(1,2) + X0X2X1X3tD_(1,1) + X0X2X1X3tD\
_(1,0) + X0X2X1X3tD_(0,5) + X0X2X1X3tD_(0,4) + X0X2X1X3tD_(0,3) + X0X2X1X3tD_(\
0,2) + X0X2X1X3tD_(0,1) + X0X2X1X3tDe + X0X2X1X0Y2X2 + X0X1X0X2Y2X2 - X2X1X0X3\
t + X1X0X2X3t - X0X2X1X3t - 2X0X1X0X2
 X1X0X2X1tD_(0,5) - X1X0X2X1tD_(0,4) + X1X0X2X1tD_(0,3) - X1X0X2X1tD_(0,2) + X\
1X0X2X1tD_(0,1) - X1X0X2X1tDe - X0X2X1X3Y3X1 + X0X2X1X0Y2X3 + X0X2X1X0X3Y0 + X\
0X1X0X3tD_(0,5) - X0X1X0X3tD_(0,4) + X0X1X0X3tD_(0,3) - X0X1X0X3tD_(0,2) + X0X\
1X0X3tD_(0,1) - X0X1X0X3tDe - X0X1X0X3
 X2X1X0X3Y3X1 + X1X2X1X0tD_(0,5) - X1X2X1X0tD_(0,4) + X1X2X1X0tD_(0,3) - X1X2X\
1X0tD_(0,2) + X1X2X1X0tD_(0,1) - X1X2X1X0tDe - X1X0X2X3Y3X1 + X1X0X2X1tD_(0,5)\
 - X1X0X2X1tD_(0,4) + X1X0X2X1tD_(0,3) - X1X0X2X1tD_(0,2) + X1X0X2X1tD_(0,1) -\
 X1X0X2X1tDe - X0X2X1X3Y3X1 + X0X2X1X0X3Y0 - X0X1X0X2X3Y0 - X1X2X1X0 + X1X0X2X\
1
 X2X1X0X2Y1X1 + X2X1X0X2X1Y1 + X1X2X1X3Y1X1 - X1X2X1X0X3Y1 - X1X0X2X3Y3X2 + X1\
X0X2X1Y0X3 + X1X0X2X1X3Y1 - X2X1X0X2 - 2X1X2X1X3
 - X1X2X1X3tD_(1,5) + X1X2X1X3tD_(1,4) - X1X2X1X3tD_(1,3) + X1X2X1X3tD_(1,2) -\
 X1X2X1X3tD_(1,1) + X1X2X1X3tD_(1,0) + X1X2X1X0Y0X2 - X1X0X2X1Y0X2 - X0X1X2X3Y\
2X1 + X0X1X2X1X0Y3 - X0X1X0X3Y0X2
 - X1X2X1X3Y1X1 + X1X2X1X0Y0X3 + X1X2X1X0X3Y1 - X1X0X2X3Y3X2 + X1X0X2X1X3Y1 - \
X0X1X2X1Y1X1 + X0X1X2X1
 - X2X1X0X3Y3X2 + X2X1X0X2Y1X1 + X2X1X0X2X1Y1 - X1X2X1X0X3Y1 - X1X0X2X3Y3X2 + \
X1X0X2X1X3Y1 + X0X2X1X3Y3X2 - X0X1X2X1Y1X1 + 2X0X1X2X1
 2X2X1X0X3tD_(w^2,4) + 2X2X1X0X3tD_(w^2,2) + 2X2X1X0X3tD_(w^2,0) + X2X1X0X3tD_\
(w,5) + X2X1X0X3tD_(w,4) + X2X1X0X3tD_(w,3) + X2X1X0X3tD_(w,2) + X2X1X0X3tD_(w\
,1) + X2X1X0X3tD_(w,0) + X2X1X0X3tD_(1,5) + X2X1X0X3tD_(1,4) + X2X1X0X3tD_(1,3\
) + X2X1X0X3tD_(1,2) + X2X1X0X3tD_(1,1) + X2X1X0X3tD_(1,0) + X2X1X0X3tD_(0,5) \
+ X2X1X0X3tD_(0,4) + X2X1X0X3tD_(0,3) + X2X1X0X3tD_(0,2) + X2X1X0X3tD_(0,1) + \
X2X1X0X3tDe + X2X1X0X2Y1X3 + X0X2X1X0Y2X2 + X0X2X1X0X2Y2 - X0X1X2X3Y2X2 + X0X1\
X2X1X3Y2 - X2X1X0X3t - X0X2X1X0 + 2X0X1X2X3
 2X1X2X1X0X2tD_(w^2,4) + 2X1X2X1X0X2tD_(w^2,2) + 2X1X2X1X0X2tD_(w^2,0) + X1X2X\
1X0X2tD_(w,5) + X1X2X1X0X2tD_(w,4) + X1X2X1X0X2tD_(w,3) + X1X2X1X0X2tD_(w,2) +\
 X1X2X1X0X2tD_(w,1) + X1X2X1X0X2tD_(w,0) + X1X2X1X0X2tD_(1,5) + X1X2X1X0X2tD_(\
1,4) + X1X2X1X0X2tD_(1,3) + X1X2X1X0X2tD_(1,2) + X1X2X1X0X2tD_(1,1) + X1X2X1X0\
X2tD_(1,0) + X1X2X1X0X2tD_(0,5) + X1X2X1X0X2tD_(0,4) + X1X2X1X0X2tD_(0,3) + X1\
X2X1X0X2tD_(0,2) + X1X2X1X0X2tD_(0,1) + X1X2X1X0X2tDe - X0X2X1X0X3Y0X1 + X0X1X\
0X2X3Y0X1 + 2X0X1X0X2X1tD_(w^2,4) + 2X0X1X0X2X1tD_(w^2,2) + 2X0X1X0X2X1tD_(w^2\
,0) + X0X1X0X2X1tD_(w,5) + X0X1X0X2X1tD_(w,4) + X0X1X0X2X1tD_(w,3) + X0X1X0X2X\
1tD_(w,2) + X0X1X0X2X1tD_(w,1) + X0X1X0X2X1tD_(w,0) + X0X1X0X2X1tD_(1,5) + X0X\
1X0X2X1tD_(1,4) + X0X1X0X2X1tD_(1,3) + X0X1X0X2X1tD_(1,2) + X0X1X0X2X1tD_(1,1)\
 + X0X1X0X2X1tD_(1,0) + X0X1X0X2X1tD_(0,5) + X0X1X0X2X1tD_(0,4) + X0X1X0X2X1tD\
_(0,3) + X0X1X0X2X1tD_(0,2) + X0X1X0X2X1tD_(0,1) + X0X1X0X2X1tDe - X1X2X1X0X2t\
 - X0X1X0X2X1t
 - X1X2X1X0X3tD_(1,5) + X1X2X1X0X3tD_(1,4) - X1X2X1X0X3tD_(1,3) + X1X2X1X0X3tD\
_(1,2) - X1X2X1X0X3tD_(1,1) + X1X2X1X0X3tD_(1,0) - X0X2X1X0X2Y2X1 - X0X2X1X0X2\
X1Y3 - X0X1X2X1X3Y2X1 + X0X1X2X1X0X3Y3 + X0X1X0X2X3Y0X2 - X0X1X0X2X1Y3X3 - X0X\
1X0X2X1X3Y3
 X2X1X0X2X3tD_(w,5) - X2X1X0X2X3tD_(w,4) + X2X1X0X2X3tD_(w,3) - X2X1X0X2X3tD_(\
w,2) + X2X1X0X2X3tD_(w,1) - X2X1X0X2X3tD_(w,0) + X0X1X2X1X3tD_(w,5) - X0X1X2X1\
X3tD_(w,4) + X0X1X2X1X3tD_(w,3) - X0X1X2X1X3tD_(w,2) + X0X1X2X1X3tD_(w,1) - X0\
X1X2X1X3tD_(w,0) - X0X1X2X1X0Y3X2 + X0X1X0X2X1Y3X2
 X2X1X0X2X1tD_(1,5) - X2X1X0X2X1tD_(1,4) + X2X1X0X2X1tD_(1,3) - X2X1X0X2X1tD_(\
1,2) + X2X1X0X2X1tD_(1,1) - X2X1X0X2X1tD_(1,0) - X1X2X1X0X3tD_(1,5) + X1X2X1X0\
X3tD_(1,4) - X1X2X1X0X3tD_(1,3) + X1X2X1X0X3tD_(1,2) - X1X2X1X0X3tD_(1,1) + X1\
X2X1X0X3tD_(1,0) + X0X1X2X1X3Y2X1 - X0X1X2X1X0Y3X3 - X0X1X2X1X0X3Y3 + X0X1X0X2\
X3Y0X2 - X0X1X0X2X1X3Y3
 X2X1X0X2X1tD_(1,5) - X2X1X0X2X1tD_(1,4) + X2X1X0X2X1tD_(1,3) - X2X1X0X2X1tD_(\
1,2) + X2X1X0X2X1tD_(1,1) - X2X1X0X2X1tD_(1,0) - X1X2X1X0X3tD_(1,5) + X1X2X1X0\
X3tD_(1,4) - X1X2X1X0X3tD_(1,3) + X1X2X1X0X3tD_(1,2) - X1X2X1X0X3tD_(1,1) + X1\
X2X1X0X3tD_(1,0) - X1X0X2X1X3tD_(1,5) + X1X0X2X1X3tD_(1,4) - X1X0X2X1X3tD_(1,3\
) + X1X0X2X1X3tD_(1,2) - X1X0X2X1X3tD_(1,1) + X1X0X2X1X3tD_(1,0) + X0X2X1X0X3Y\
0X2 - X0X2X1X0X2Y2X1 - X0X2X1X0X2X1Y3 + X0X1X2X1X0X3Y3 + X0X1X0X2X3Y0X2 - X0X1\
X0X2X1X3Y3 - X0X1X2X1X0 - X0X1X0X2X1
 - X1X0X2X1X0tD_(0,5) + X1X0X2X1X0tD_(0,4) - X1X0X2X1X0tD_(0,3) + X1X0X2X1X0tD\
_(0,2) - X1X0X2X1X0tD_(0,1) + X1X0X2X1X0tDe + X0X2X1X0X3tD_(0,5) - X0X2X1X0X3t\
D_(0,4) + X0X2X1X0X3tD_(0,3) - X0X2X1X0X3tD_(0,2) + X0X2X1X0X3tD_(0,1) - X0X2X\
1X0X3tDe - X0X2X1X0X2Y2X3 + X0X1X0X2X3tD_(0,5) - X0X1X0X2X3tD_(0,4) + X0X1X0X2\
X3tD_(0,3) - X0X1X0X2X3tD_(0,2) + X0X1X0X2X3tD_(0,1) - X0X1X0X2X3tDe + X0X2X1X\
0X3 - X0X1X0X2X3
 - X2X1X0X2X3Y2X1 + X1X2X1X0X3tD_(1,5) - X1X2X1X0X3tD_(1,4) + X1X2X1X0X3tD_(1,\
3) - X1X2X1X0X3tD_(1,2) + X1X2X1X0X3tD_(1,1) - X1X2X1X0X3tD_(1,0) + X1X2X1X0X2\
X3Y3 + X1X0X2X1X3tD_(1,5) - X1X0X2X1X3tD_(1,4) + X1X0X2X1X3tD_(1,3) - X1X0X2X1\
X3tD_(1,2) + X1X0X2X1X3tD_(1,1) - X1X0X2X1X3tD_(1,0) - X1X0X2X1X0Y0X2 - X1X0X2\
X1X0X2Y3 + X0X2X1X0X2Y2X1 + X0X1X2X1X3Y2X1 - X0X1X2X1X0X3Y3 - X1X2X1X0X2 + X0X\
1X0X2X1
 - X2X1X0X2X1Y1X1 + X1X2X1X0X3Y1X1 + X1X0X2X1X3Y1X1 - X1X0X2X1X0Y0X3 - X1X0X2X\
1X0X3Y1 + X2X1X0X2X1 - 2X1X2X1X0X3
 X1X2X1X0X3Y1X2 - X1X2X1X0X2Y3X1 - X1X2X1X0X2X1Y0 - X1X0X2X1X3Y1X2 + X0X1X2X1X\
0Y3X1
 X1X2X1X0X3tD_(1,5) - X1X2X1X0X3tD_(1,4) + X1X2X1X0X3tD_(1,3) - X1X2X1X0X3tD_(\
1,2) + X1X2X1X0X3tD_(1,1) - X1X2X1X0X3tD_(1,0) - X1X2X1X0X2Y3X3 - X1X0X2X1X0Y0\
X2 - X1X0X2X1X0X2Y3 + X0X1X2X1X3Y2X1 - X0X1X2X1X0X3Y3 + X0X1X0X2X3Y0X2 - X0X1X\
0X2X1X3Y3
 X2X1X0X2X3Y2X2 - X2X1X0X2X1Y1X3 - X2X1X0X2X1X3Y2 - X0X2X1X0X2Y2X2 - X0X1X2X1X\
3Y2X2 + X0X2X1X0X2 + 2X0X1X2X1X3
 2X1X2X1X0X2X3tD_(w^2,4) + 2X1X2X1X0X2X3tD_(w^2,2) + 2X1X2X1X0X2X3tD_(w^2,0) +\
 X1X2X1X0X2X3tD_(w,5) + X1X2X1X0X2X3tD_(w,4) + X1X2X1X0X2X3tD_(w,3) + X1X2X1X0\
X2X3tD_(w,2) + X1X2X1X0X2X3tD_(w,1) + X1X2X1X0X2X3tD_(w,0) + X1X2X1X0X2X3tD_(1\
,5) + X1X2X1X0X2X3tD_(1,4) + X1X2X1X0X2X3tD_(1,3) + X1X2X1X0X2X3tD_(1,2) + X1X\
2X1X0X2X3tD_(1,1) + X1X2X1X0X2X3tD_(1,0) + X1X2X1X0X2X3tD_(0,5) + X1X2X1X0X2X3\
tD_(0,4) + X1X2X1X0X2X3tD_(0,3) + X1X2X1X0X2X3tD_(0,2) + X1X2X1X0X2X3tD_(0,1) \
+ X1X2X1X0X2X3tDe + X0X2X1X0X2X3Y0X1 - X0X1X2X1X0X2X3Y2 + 2X0X1X0X2X1X3tD_(w^2\
,4) + 2X0X1X0X2X1X3tD_(w^2,2) + 2X0X1X0X2X1X3tD_(w^2,0) + X0X1X0X2X1X3tD_(w,5)\
 + X0X1X0X2X1X3tD_(w,4) + X0X1X0X2X1X3tD_(w,3) + X0X1X0X2X1X3tD_(w,2) + X0X1X0\
X2X1X3tD_(w,1) + X0X1X0X2X1X3tD_(w,0) + X0X1X0X2X1X3tD_(1,5) + X0X1X0X2X1X3tD_\
(1,4) + X0X1X0X2X1X3tD_(1,3) + X0X1X0X2X1X3tD_(1,2) + X0X1X0X2X1X3tD_(1,1) + X\
0X1X0X2X1X3tD_(1,0) + X0X1X0X2X1X3tD_(0,5) + X0X1X0X2X1X3tD_(0,4) + X0X1X0X2X1\
X3tD_(0,3) + X0X1X0X2X1X3tD_(0,2) + X0X1X0X2X1X3tD_(0,1) + X0X1X0X2X1X3tDe + X\
0X1X0X2X1X0Y2X2 + X0X1X0X2X1X0X2Y2 - X1X2X1X0X2X3t - X0X1X0X2X1X3t
 - X1X2X1X0X2X1tD_(0,5) + X1X2X1X0X2X1tD_(0,4) - X1X2X1X0X2X1tD_(0,3) + X1X2X1\
X0X2X1tD_(0,2) - X1X2X1X0X2X1tD_(0,1) + X1X2X1X0X2X1tDe + X0X2X1X0X2X1Y3X1 - X\
0X1X2X1X0X3Y3X1 - X0X1X0X2X1X3Y3X1 + X0X1X0X2X1X0Y2X3 + X0X1X0X2X1X0X3Y0
 - X2X1X0X2X1X3tD_(w,5) + X2X1X0X2X1X3tD_(w,4) - X2X1X0X2X1X3tD_(w,3) + X2X1X0\
X2X1X3tD_(w,2) - X2X1X0X2X1X3tD_(w,1) + X2X1X0X2X1X3tD_(w,0) - X0X1X2X1X0X3Y3X\
2 + X0X1X2X1X0X2Y1X1 + X0X1X2X1X0X2X1Y1 + X0X1X0X2X1X3Y3X2
 2X1X2X1X0X2X3tD_(w^2,4) + 2X1X2X1X0X2X3tD_(w^2,2) + 2X1X2X1X0X2X3tD_(w^2,0) +\
 X1X2X1X0X2X3tD_(w,5) + X1X2X1X0X2X3tD_(w,4) + X1X2X1X0X2X3tD_(w,3) + X1X2X1X0\
X2X3tD_(w,2) + X1X2X1X0X2X3tD_(w,1) + X1X2X1X0X2X3tD_(w,0) + X1X2X1X0X2X3tD_(1\
,5) + X1X2X1X0X2X3tD_(1,4) + X1X2X1X0X2X3tD_(1,3) + X1X2X1X0X2X3tD_(1,2) + X1X\
2X1X0X2X3tD_(1,1) + X1X2X1X0X2X3tD_(1,0) + X1X2X1X0X2X3tD_(0,5) + X1X2X1X0X2X3\
tD_(0,4) + X1X2X1X0X2X3tD_(0,3) + X1X2X1X0X2X3tD_(0,2) + X1X2X1X0X2X3tD_(0,1) \
+ X1X2X1X0X2X3tDe - 2X1X0X2X1X0X2tD_(w^2,4) - 2X1X0X2X1X0X2tD_(w^2,2) - 2X1X0X\
2X1X0X2tD_(w^2,0) - X1X0X2X1X0X2tD_(w,5) - X1X0X2X1X0X2tD_(w,4) - X1X0X2X1X0X2\
tD_(w,3) - X1X0X2X1X0X2tD_(w,2) - X1X0X2X1X0X2tD_(w,1) - X1X0X2X1X0X2tD_(w,0) \
- X1X0X2X1X0X2tD_(1,5) - X1X0X2X1X0X2tD_(1,4) - X1X0X2X1X0X2tD_(1,3) - X1X0X2X\
1X0X2tD_(1,2) - X1X0X2X1X0X2tD_(1,1) - X1X0X2X1X0X2tD_(1,0) - X1X0X2X1X0X2tD_(\
0,5) - X1X0X2X1X0X2tD_(0,4) - X1X0X2X1X0X2tD_(0,3) - X1X0X2X1X0X2tD_(0,2) - X1\
X0X2X1X0X2tD_(0,1) - X1X0X2X1X0X2tDe - 2X0X2X1X0X2X1tD_(w^2,4) - 2X0X2X1X0X2X1\
tD_(w^2,2) - 2X0X2X1X0X2X1tD_(w^2,0) - X0X2X1X0X2X1tD_(w,5) - X0X2X1X0X2X1tD_(\
w,4) - X0X2X1X0X2X1tD_(w,3) - X0X2X1X0X2X1tD_(w,2) - X0X2X1X0X2X1tD_(w,1) - X0\
X2X1X0X2X1tD_(w,0) - X0X2X1X0X2X1tD_(1,5) - X0X2X1X0X2X1tD_(1,4) - X0X2X1X0X2X\
1tD_(1,3) - X0X2X1X0X2X1tD_(1,2) - X0X2X1X0X2X1tD_(1,1) - X0X2X1X0X2X1tD_(1,0)\
 - X0X2X1X0X2X1tD_(0,5) - X0X2X1X0X2X1tD_(0,4) - X0X2X1X0X2X1tD_(0,3) - X0X2X1\
X0X2X1tD_(0,2) - X0X2X1X0X2X1tD_(0,1) - X0X2X1X0X2X1tDe + 2X0X1X2X1X0X3tD_(w^2\
,4) + 2X0X1X2X1X0X3tD_(w^2,2) + 2X0X1X2X1X0X3tD_(w^2,0) + X0X1X2X1X0X3tD_(w,5)\
 + X0X1X2X1X0X3tD_(w,4) + X0X1X2X1X0X3tD_(w,3) + X0X1X2X1X0X3tD_(w,2) + X0X1X2\
X1X0X3tD_(w,1) + X0X1X2X1X0X3tD_(w,0) + X0X1X2X1X0X3tD_(1,5) + X0X1X2X1X0X3tD_\
(1,4) + X0X1X2X1X0X3tD_(1,3) + X0X1X2X1X0X3tD_(1,2) + X0X1X2X1X0X3tD_(1,1) + X\
0X1X2X1X0X3tD_(1,0) + X0X1X2X1X0X3tD_(0,5) + X0X1X2X1X0X3tD_(0,4) + X0X1X2X1X0\
X3tD_(0,3) + X0X1X2X1X0X3tD_(0,2) + X0X1X2X1X0X3tD_(0,1) + X0X1X2X1X0X3tDe + X\
0X1X2X1X0X2Y1X3 + X0X1X0X2X1X0Y2X2 + X0X1X0X2X1X0X2Y2 - X1X2X1X0X2X3t + X1X0X2\
X1X0X2t + X0X2X1X0X2X1t - X0X1X2X1X0X3t - X0X1X0X2X1X0
 X1X0X2X1X0X3tD_(1,5) - X1X0X2X1X0X3tD_(1,4) + X1X0X2X1X0X3tD_(1,3) - X1X0X2X1\
X0X3tD_(1,2) + X1X0X2X1X0X3tD_(1,1) - X1X0X2X1X0X3tD_(1,0) - X0X2X1X0X2X3Y0X2 \
+ X0X2X1X0X2X1Y3X3 + X0X2X1X0X2X1X3Y3 - X0X1X2X1X0X3 - X0X1X0X2X1X3
 X1X2X1X0X2X3Y3X1 - X1X2X1X0X2X1tD_(0,5) + X1X2X1X0X2X1tD_(0,4) - X1X2X1X0X2X1\
tD_(0,3) + X1X2X1X0X2X1tD_(0,2) - X1X2X1X0X2X1tD_(0,1) + X1X2X1X0X2X1tDe - X1X\
0X2X1X0X3Y1X2 + X1X0X2X1X0X2X1Y0 - X0X1X2X1X0X3Y3X1 - X0X1X0X2X1X0X3Y0 - X1X2X\
1X0X2X1
 X2X1X0X2X1X3Y2X1 - X1X0X2X1X0X3tD_(1,5) + X1X0X2X1X0X3tD_(1,4) - X1X0X2X1X0X3\
tD_(1,3) + X1X0X2X1X0X3tD_(1,2) - X1X0X2X1X0X3tD_(1,1) + X1X0X2X1X0X3tD_(1,0) \
+ X1X0X2X1X0X2Y3X3 + X1X0X2X1X0X2X3Y3 + X0X2X1X0X2X1X3Y3 - X1X2X1X0X2X3 + X0X1\
X0X2X1X3
 - X1X2X1X0X2X3Y3X2 + X1X2X1X0X2X1Y0X3 + X1X2X1X0X2X1X3Y1 + X1X0X2X1X0X2Y3X2 +\
 X0X1X2X1X0X2Y1X1 + X0X1X2X1X0X2X1Y1 + X0X1X0X2X1X3Y3X2 - X0X1X2X1X0X2
 X1X2X1X0X2X1X3tD_(1,5) - X1X2X1X0X2X1X3tD_(1,4) + X1X2X1X0X2X1X3tD_(1,3) - X1\
X2X1X0X2X1X3tD_(1,2) + X1X2X1X0X2X1X3tD_(1,1) - X1X2X1X0X2X1X3tD_(1,0) - X0X1X\

In [306]:
Print("------------ Xtop ----------------\n");
Xtop := X0*X1*X0*X2*X1*X0*X2*X1*X3;
PrintNP(GP2NP(Xtop));

------------ Xtop ----------------
 X0X1X0X2X1X0X2X1X3

(1)*x.1*(x.2*x.1*x.3)^2*x.2*x.4

# Kazhdan-Lusztig

In [307]:
NicholsGradingData := [
    rec( graded_i := 0, dimBi := 1 ),
    rec( graded_i := 1, dimBi := 4 ),
    rec( graded_i := 2, dimBi := 8 ),
    rec( graded_i := 3, dimBi := 11 ),
    rec( graded_i := 4, dimBi := 12 ),
    rec( graded_i := 5, dimBi := 12 ),
    rec( graded_i := 6, dimBi := 11 ),
    rec( graded_i := 7, dimBi := 8 ),
    rec( graded_i := 8, dimBi := 4 ),
    rec( graded_i := 9, dimBi := 1 )
];;

## Notation for the Simple $\mathcal{D}(G)$-Modules

$$
\begin{array}{|c|l||c|l||c|l||c|l|}
\hline
M_{1} & M(0,\tau_{00}) & 
M_{2} & M(0,\tau_{12}) & 
M_{3} & M(0,\tau_{01}) & 
M_{4} & M(0,\tau_{10})\\
\hline
M_{5} & M(0,\tau_{02}) & 
M_{6} & M(0,\tau_{11}) & 
M_{7} & M(3,\tau_{00}) & 
M_{8} & M(3,\tau_{12})\\
\hline
M_{9} & M(3,\tau_{01}) & 
M_{10} & M(3,\tau_{10}) & 
M_{11} & M(3,\tau_{02}) & 
M_{12} & M(3,\tau_{11})\\
\hline
M_{13} & M(0,\rho_{0}) & 
M_{14} & M(0,\rho_{1}) & 
M_{15} & M(3,\rho_{0}) & 
M_{16} & M(3,\rho_{1})\\
\hline
M_{17} & M(0,\chi_{(0,0,0)}) & 
M_{18} & M(0,\chi_{(0,0,1)}) & 
M_{19} & M(0,\chi_{(0,1,0)}) & 
M_{20} & M(0,\chi_{(0,1,1)})\\
\hline
M_{21} & M(0,\chi_{(1,0,0)}) & 
M_{22} & M(0,\chi_{(1,0,1)}) & 
M_{23} & M(0,\chi_{(1,1,0)}) & 
M_{24} & M(0,\chi_{(1,1,1)})\\
\hline
M_{25} & M(3,\chi_{(0,0,0)}) & 
M_{26} & M(3,\chi_{(0,0,1)}) & 
M_{27} & M(3,\chi_{(0,1,0)}) & 
M_{28} & M(3,\chi_{(0,1,1)})\\
\hline
M_{29} & M(3,\chi_{(1,0,0)}) & 
M_{30} & M(3,\chi_{(1,0,1)}) & 
M_{31} & M(3,\chi_{(1,1,0)}) & 
M_{32} & M(3,\chi_{(1,1,1)})\\
\hline
M_{33} & M(1,\eta_{0}) & 
M_{34} & M(1,\eta_{1}) & 
M_{35} & M(1,\eta_{2}) & 
M_{36} & M(1,\eta_{3})\\
\hline
M_{37} & M(1,\eta_{4}) & 
M_{38} & M(1,\eta_{5}) & 
M_{39} & M(2,\eta_{0}) & 
M_{40} & M(2,\eta_{1})\\
\hline
M_{41} & M(2,\eta_{2}) & 
M_{42} & M(2,\eta_{3}) & 
M_{43} & M(2,\eta_{4}) & 
M_{44} & M(2,\eta_{5})\\
\hline
M_{45} & M(4,\eta_{0}) & 
M_{46} & M(4,\eta_{1}) & 
M_{47} & M(4,\eta_{2}) & 
M_{48} & M(4,\eta_{3})\\
\hline
M_{49} & M(4,\eta_{4}) & 
M_{50} & M(4,\eta_{5}) & 
M_{51} & M(5,\eta_{0}) & 
M_{52} & M(5,\eta_{1})\\
\hline
M_{53} & M(5,\eta_{2}) & 
M_{54} & M(5,\eta_{3}) & 
M_{55} & M(5,\eta_{4}) & 
M_{56} & M(5,\eta_{5})\\
\hline
\end{array}
$$

$$
C_2=\langle -1\rangle,\qquad
C_3=\langle \omega\rangle,\qquad
C_6=\langle \zeta\rangle,
$$
where
$$
\omega=\zeta^2,\qquad -1=\zeta^3.
$$

The isomorphism
$$
\varphi:C_2\times C_3\longrightarrow C_6
$$
is given by
$$
\varphi\big((-1)^a,\omega^b\big)
=
\zeta^{3a+2b}.
$$

$$
\begin{array}{c|c|c}
(a,b) & \big((-1)^a,\omega^b\big) & \varphi\big((-1)^a,\omega^b\big) \\ \hline
(0,0) & (1,1)       & \zeta^0=1 \\
(0,1) & (1,\omega)  & \zeta^2 \\
(0,2) & (1,\omega^2)& \zeta^4 \\ \hline
(1,0) & (-1,1)       & \zeta^3 \\
(1,1) & (-1,\omega)  & \zeta^5 \\
(1,2) & (-1,\omega^2)& \zeta^7=\zeta
\end{array}
$$

Thus, in terms of the elements of $C_6$,
$$
\begin{array}{c|c}
C_2\times C_3 & C_6 \\ \hline
(1,1) & 1 \\
(1,\omega) & \zeta^2 \\
(1,\omega^2) & \zeta^4 \\
(-1,1) & \zeta^3 \\
(-1,\omega) & \zeta^5 \\
(-1,\omega^2) & \zeta
\end{array}
$$
$$
\varphi^{-1}:C_6\longrightarrow C_2\times C_3
$$

$$
\begin{array}{c|c}
C_6 & C_2\times C_3 \\ \hline
\zeta^0 & (0,0) \\
\zeta^1 & (1,2) \\
\zeta^2 & (0,1) \\
\zeta^3 & (1,0) \\
\zeta^4 & (0,2) \\
\zeta^5 & (1,1)
\end{array}
$$

where
$
a\equiv k\pmod{2},
\qquad
b\equiv 2k\pmod{3},
$
for
$
\varphi^{-1}(\zeta^k)=(a,b).
$

In [308]:
SimpleNames:=[];;

In [308]:
SimpleNames[1] := "M(0,\\tau_{00})";; # 1
SimpleNames[2] := "M(0,\\tau_{12})";; # 4
SimpleNames[3] := "M(0,\\tau_{01})";; # 6
SimpleNames[4] := "M(0,\\tau_{10})";; # 2
SimpleNames[5] := "M(0,\\tau_{02})";; # 5
SimpleNames[6] := "M(0,\\tau_{11})";; # 3

In [320]:
SimpleNames[7]  := "M(3,\\tau_{00})";; # 1
SimpleNames[8]  := "M(3,\\tau_{12})";; # 4
SimpleNames[9]  := "M(3,\\tau_{01})";; # 6
SimpleNames[10] := "M(3,\\tau_{10})";; # 2
SimpleNames[11] := "M(3,\\tau_{02})";; # 5
SimpleNames[12] := "M(3,\\tau_{11})";; # 3

In [322]:
SimpleNames[13]:="M(0,\\rho_{0})";; # 2
SimpleNames[14]:="M(0,\\rho_{1})";; # 1

In [324]:
SimpleNames[15]:="M(3,\\rho_{0})";; # 2
SimpleNames[16]:="M(3,\\rho_{1})";; # 1

In [332]:
SimpleNames[17] := "M(0,\\chi_{(0,0,0)})";; # 1
SimpleNames[18] := "M(0,\\chi_{(0,0,1)})";; # 8
SimpleNames[19] := "M(0,\\chi_{(0,1,0)})";; # 5
SimpleNames[20] := "M(0,\\chi_{(0,1,1)})";; # 4
SimpleNames[21] := "M(0,\\chi_{(1,0,0)})";; # 3
SimpleNames[22] := "M(0,\\chi_{(1,0,1)})";; # 2
SimpleNames[23] := "M(0,\\chi_{(1,1,0)})";; # 7
SimpleNames[24] := "M(0,\\chi_{(1,1,1)})";; # 6

In [340]:
SimpleNames[25] := "M(3,\\chi_{(0,0,0)})";; # 1
SimpleNames[26] := "M(3,\\chi_{(0,0,1)})";; # 8
SimpleNames[27] := "M(3,\\chi_{(0,1,0)})";; # 5
SimpleNames[28] := "M(3,\\chi_{(0,1,1)})";; # 4
SimpleNames[29] := "M(3,\\chi_{(1,0,0)})";; # 3
SimpleNames[30] := "M(3,\\chi_{(1,0,1)})";; # 2
SimpleNames[31] := "M(3,\\chi_{(1,1,0)})";; # 7
SimpleNames[32] := "M(3,\\chi_{(1,1,1)})";; # 6

In [346]:
SimpleNames[33] := "M(1,\\eta_{0})";; # 1
SimpleNames[34] := "M(1,\\eta_{1})";; # 3
SimpleNames[35] := "M(1,\\eta_{2})";; # 5
SimpleNames[36] := "M(1,\\eta_{3})";; # 2
SimpleNames[37] := "M(1,\\eta_{4})";; # 6
SimpleNames[38] := "M(1,\\eta_{5})";; # 4

In [352]:
SimpleNames[39] := "M(2,\\eta_{0})";; # 1
SimpleNames[40] := "M(2,\\eta_{1})";; # 3
SimpleNames[41] := "M(2,\\eta_{2})";; # 5
SimpleNames[42] := "M(2,\\eta_{3})";; # 2
SimpleNames[43] := "M(2,\\eta_{4})";; # 6
SimpleNames[44] := "M(2,\\eta_{5})";; # 4

In [352]:
SimpleNames[45] := "M(4,\\eta_{0})";; # 1
SimpleNames[46] := "M(4,\\eta_{1})";; # 3
SimpleNames[47] := "M(4,\\eta_{2})";; # 5
SimpleNames[48] := "M(4,\\eta_{3})";; # 2
SimpleNames[49] := "M(4,\\eta_{4})";; # 6
SimpleNames[50] := "M(4,\\eta_{5})";; # 4

In [364]:
SimpleNames[51] := "M(5,\\eta_{0})";; # 1
SimpleNames[52] := "M(5,\\eta_{1})";; # 3
SimpleNames[53] := "M(5,\\eta_{2})";; # 5
SimpleNames[54] := "M(5,\\eta_{3})";; # 2
SimpleNames[55] := "M(5,\\eta_{4})";; # 6
SimpleNames[56] := "M(5,\\eta_{5})";; # 4

In [365]:
QGNAG_SaveSimpleModulesNotationToLaTeX( "DG_mod_notation.tex", SimpleNames );

"DG_mod_notation.tex"

## Fusion rules

In [366]:
SimplesMn := [];

[  ]

In [367]:
UpdateSimpleBase := function(simple)
    local m, new_base, elems;

    m := Length(simple.base);
    elems := Elements(GF(4));

    if m = 3 then
        new_base := List([1..m], i ->
            TensorElement(ElementSDP(elems[1], i-1), [1])
        );

        simple.base := new_base;
        return simple;

    elif m = 4 then
        new_base := List([1..m], i ->
            TensorElement(ElementSDP(elems[i], 0), [1])
        );

        simple.base := new_base;
        return simple;

    else
        return simple;
    fi;
end;

function( simple ) ... end

## $1$-dimensional modules attached to $(0, s)$.

In [368]:
ordered_center := [1, 4, 6, 2, 5, 3];;

In [371]:
data_one                := GetSimplesModAttachedToElement(G, One(G),allPairsInG){[1..6]};;
SimplesModAttachedToOne := List(ordered_center, i-> data_one[i]);;
for s in SimplesModAttachedToOne do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [374]:
data_F1F2                := GetSimplesModAttachedToElement(G, G.1*G.2, allPairsInG){[1..6]};;
SimplesModAttachedToF1F2 := List(ordered_center, i-> data_F1F2[i]);;
for s in SimplesModAttachedToF1F2 do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

## $3$-dimensional modules attached to $(0, s)$ with $s=0,3$.

In [375]:
RepresentationMdim3bis := function(G, i)
    local A1, A2, A3, A4, gens, mgens, rho;

    if not (i in [0,1]) then
        Error("The parameter i must belong to {0,1}.");
    fi;

    A1 := (-1)^i*[ [ 0, 0, 1 ],
                   [ 1, 0, 0 ],
                   [ 0, 1, 0 ] ];
    
    A2 := A1^2;

    A3 := [ [ -1, -1, -1 ],
            [  0,  0,  1 ],
            [  0,  1,  0 ] ];
    
    A4 := [ [  0,  1,  0 ],
            [  1,  0,  0 ],
            [ -1, -1, -1 ] ];
    
    gens  := GeneratorsOfGroup(G);
    mgens := [A1, A2, A3, A4];
    rho := GroupHomomorphismByImages(
        G,
        Group(mgens),
        gens,
        mgens
    );
    return rho;
end;;

In [376]:
index_i := [
#   i      [(0,1)|(0,2)|(w,0)|(1,0)]->
    0,   #8 [ f1, f2, f3, f4 ] -> [ [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ],   [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],   [ [ -1, 0, 0 ], [ 0, -1, 0 ], [ 0, 0, 1 ] ],   [ [ -1, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, -1 ] ] ]
    1  #7 [ f1, f2, f3, f4 ] -> [ [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, -1, 0 ] ],   [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],   [ [ -1, 0, 0 ], [ 0, -1, 0 ], [ 0, 0, 1 ] ],   [ [ -1, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, -1 ] ] ]
];;

In [377]:
repsdim3bis := List(index_i, i -> RepresentationMdim3bis(G, i));;

In [378]:
ordered_center_dim3 := [2, 1];;

In [381]:
data_one                    := GetSimplesModAttachedToElement(G, One(G),allPairsInG){[7,8]};;
SimplesModAttachedToOneDim3 := List(ordered_center_dim3, i -> data_one[i]);;
for s in SimplesModAttachedToOneDim3 do
    #s               := UpdateSimpleBase(s);
    s.simple        := repsdim3bis[Position(SimplesModAttachedToOneDim3, s)];
    s.weight.rho    := repsdim3bis[Position(SimplesModAttachedToOneDim3, s)];
    s.weightSDP.rho := repsdim3bis[Position(SimplesModAttachedToOneDim3, s)];
    s.gensimages    := List(s.generatorsofgroup, x-> s.simple(x) );
    s               := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [384]:
data_F1F2                    := GetSimplesModAttachedToElement(G, G.1*G.2, allPairsInG){[7,8]};;
SimplesModAttachedToF1F2Dim3 := List([2, 1], i-> data_F1F2[i]);;
for s in SimplesModAttachedToF1F2Dim3 do
    #s               := UpdateSimpleBase(s);
    s.simple        := repsdim3bis[Position(SimplesModAttachedToF1F2Dim3, s)];
    s.weight.rho    := repsdim3bis[Position(SimplesModAttachedToF1F2Dim3, s)];
    s.weightSDP.rho := repsdim3bis[Position(SimplesModAttachedToF1F2Dim3, s)];
    s.gensimages    := List(s.generatorsofgroup, x-> s.simple(x) );
    s               := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

## $3$-dimensional modules attached to $(1, s)$.

In [385]:
order_dim_3 := [1, 8, 5, 4, 3, 2, 7, 6];;

In [388]:
data_F4                := GetSimplesModAttachedToElement(G, G.4, allPairsInG);;
SimplesModAttachedToF4 := List(order_dim_3, i -> data_F4[i]);;
for s in SimplesModAttachedToF4 do
    s             := UpdateSimpleBase(s);
    s             := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [391]:
data_F1F2F4                := GetSimplesModAttachedToElement(G, G.1*G.2*G.4, allPairsInG);;
SimplesModAttachedToF1F2F4 := List(order_dim_3, i -> data_F1F2F4[i]);;
for s in SimplesModAttachedToF1F2F4 do
    s             := UpdateSimpleBase(s);
    s             := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

## $4$-dimensional modules attached to $(0, s)$.

In [392]:
order_dim_4 := [1, 3, 5, 2, 6, 4];;

In [395]:
data_F1                := GetSimplesModAttachedToElement(G, G.1, allPairsInG);;
SimplesModAttachedToF1 := List(order_dim_4, i -> data_F1[i]);;
for s in SimplesModAttachedToF1 do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [398]:
data_F2                := GetSimplesModAttachedToElement(G, G.2, allPairsInG);;
SimplesModAttachedToF2 := List(order_dim_4, i -> data_F2[i]);;
for s in SimplesModAttachedToF2 do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [401]:
data_F2F2                := GetSimplesModAttachedToElement(G, G.2*G.2, allPairsInG);;
SimplesModAttachedToF2F2 := List(order_dim_4, i -> data_F2F2[i]);;
for s in SimplesModAttachedToF2F2 do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [404]:
data_F1F2F2 := GetSimplesModAttachedToElement(G, G.1*G.2*G.2, allPairsInG);;
SimplesModAttachedToF1F2F2 := List(order_dim_4, i -> data_F1F2F2[i]);;
for s in SimplesModAttachedToF1F2F2 do
    s := AttachDeltaStructureMatrices(s);
    Add(SimplesMn, s);
od;

In [421]:
QGNAG_TestRelationsForDGModSimples(SimplesMn, relsGroup, relskG, relsDG);

All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

true

## Fusion Rules by index

In [422]:
if QGNAG.Config.PROD then
    for i in [2..Length(SimplesMn)] do
        Print("--------------------------------------------------------------\n");
        for j in [i..Length(SimplesMn)] do
            MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[i], SimplesMn[j]);
            Print(QGNAG_FusionRuleToIndex( MtensorN, SimplesMn), "\n");
        od;
    od;
fi;

In [424]:
data_mats_simples:=[];;
for s in SimplesMn do
    mats_s := QGNAG_RepresentationMatrices(s);
    Add(data_mats_simples, mats_s);
od;

In [425]:
all_mat_tensor := QGNAG_AllTensorProductRepresentationMatrices(SimplesMn);;

In [426]:
data_parallel := QGNAG_FusionRulesAsVectorsParallel(all_mat_tensor, data_mats_simples);;

In [426]:
if QGNAG.Config.PROD then
    data_fr_via_gap   := QGNAG_FusionRulesAsVectors(all_mat_tensor, data_mats_simples);;
    data_fusion_rules := QGNAG_AllFusionRules( SimplesMn );;
    data_parallel = data_fr_via_gap;
    data_parallel = data_fusion_rules;
fi;

Syntax error: found an expression when a statement was expected in stream:4
    data_parallel = data_fr_via_gap;
                  ^
Syntax error: found an expression when a statement was expected in stream:5
    data_parallel = data_fusion_rules;
                  ^

In [427]:
QGNAG_PrintFusionRules( data_parallel );

--------------------------------------------------------------
M2 \otimes M2 \simeq M3
M2 \otimes M3 \simeq M4
M2 \otimes M4 \simeq M5
M2 \otimes M5 \simeq M6
M2 \otimes M6 \simeq M1
M2 \otimes M7 \simeq M8
M2 \otimes M8 \simeq M9
M2 \otimes M9 \simeq M10
M2 \otimes M10 \simeq M11
M2 \otimes M11 \simeq M12
M2 \otimes M12 \simeq M7
M2 \otimes M13 \simeq M14
M2 \otimes M14 \simeq M13
M2 \otimes M15 \simeq M16
M2 \otimes M16 \simeq M15
M2 \otimes M17 \simeq M18
M2 \otimes M18 \simeq M17
M2 \otimes M19 \simeq M20
M2 \otimes M20 \simeq M19
M2 \otimes M21 \simeq M22
M2 \otimes M22 \simeq M21
M2 \otimes M23 \simeq M24
M2 \otimes M24 \simeq M23
M2 \otimes M25 \simeq M26
M2 \otimes M26 \simeq M25
M2 \otimes M27 \simeq M28
M2 \otimes M28 \simeq M27
M2 \otimes M29 \simeq M30
M2 \otimes M30 \simeq M29
M2 \otimes M31 \simeq M32
M2 \otimes M32 \simeq M31
M2 \otimes M33 \simeq M38
M2 \otimes M34 \simeq M33
M2 \otimes M35 \simeq M34
M2 \otimes M36 \simeq M35
M2 \otimes M37 \simeq M36
M2 \otimes M38 \simeq M37
M2 \otimes M39 \simeq M44
M2 \otimes M40 \simeq M39
M2 \otimes M41 \simeq M40
M2 \otimes M42 \simeq M41
M2 \otimes M43 \simeq M42
M2 \otimes M44 \simeq M43
M2 \otimes M45 \simeq M50
M2 \otimes M46 \simeq M45
M2 \otimes M47 \simeq M46
M2 \otimes M48 \simeq M47
M2 \otimes M49 \simeq M48
M2 \otimes M50 \simeq M49
M2 \otimes M51 \simeq M56
M2 \otimes M52 \simeq M51
M2 \otimes M53 \simeq M52
M2 \otimes M54 \simeq M53
M2 \otimes M55 \simeq M54
M2 \otimes M56 \simeq M55
--------------------------------------------------------------
M3 \otimes M3 \simeq M5
M3 \otimes M4 \simeq M6
M3 \otimes M5 \simeq M1
M3 \otimes M6 \simeq M2
M3 \otimes M7 \simeq M9
M3 \otimes M8 \simeq M10
M3 \otimes M9 \simeq M11
M3 \otimes M10 \simeq M12
M3 \otimes M11 \simeq M7
M3 \otimes M12 \simeq M8
M3 \otimes M13 \simeq M13
M3 \otimes M14 \simeq M14
M3 \otimes M15 \simeq M15
M3 \otimes M16 \simeq M16
M3 \otimes M17 \simeq M17
M3 \otimes M18 \simeq M18
M3 \otimes M19 \simeq M19
M3 \otimes M20 \simeq M20
M3 \otimes M21 \simeq M21
M3 \otimes M22 \simeq M22
M3 \otimes M23 \simeq M23
M3 \otimes M24 \simeq M24
M3 \otimes M25 \simeq M25
M3 \otimes M26 \simeq M26
M3 \otimes M27 \simeq M27
M3 \otimes M28 \simeq M28
M3 \otimes M29 \simeq M29
M3 \otimes M30 \simeq M30
M3 \otimes M31 \simeq M31
M3 \otimes M32 \simeq M32
M3 \otimes M33 \simeq M37
M3 \otimes M34 \simeq M38
M3 \otimes M35 \simeq M33
M3 \otimes M36 \simeq M34
M3 \otimes M37 \simeq M35
M3 \otimes M38 \simeq M36
M3 \otimes M39 \simeq M43
M3 \otimes M40 \simeq M44
M3 \otimes M41 \simeq M39
M3 \otimes M42 \simeq M40
M3 \otimes M43 \simeq M41
M3 \otimes M44 \simeq M42
M3 \otimes M45 \simeq M49
M3 \otimes M46 \simeq M50
M3 \otimes M47 \simeq M45
M3 \otimes M48 \simeq M46
M3 \otimes M49 \simeq M47
M3 \otimes M50 \simeq M48
M3 \otimes M51 \simeq M55
M3 \otimes M52 \simeq M56
M3 \otimes M53 \simeq M51
M3 \otimes M54 \simeq M52
M3 \otimes M55 \simeq M53
M3 \otimes M56 \simeq M54
--------------------------------------------------------------
M4 \otimes M4 \simeq M1
M4 \otimes M5 \simeq M2
M4 \otimes M6 \simeq M3
M4 \otimes M7 \simeq M10
M4 \otimes M8 \simeq M11
M4 \otimes M9 \simeq M12
M4 \otimes M10 \simeq M7
M4 \otimes M11 \simeq M8
M4 \otimes M12 \simeq M9
M4 \otimes M13 \simeq M14
M4 \otimes M14 \simeq M13
M4 \otimes M15 \simeq M16
M4 \otimes M16 \simeq M15
M4 \otimes M17 \simeq M18
M4 \otimes M18 \simeq M17
M4 \otimes M19 \simeq M20
M4 \otimes M20 \simeq M19
M4 \otimes M21 \simeq M22
M4 \otimes M22 \simeq M21
M4 \otimes M23 \simeq M24
M4 \otimes M24 \simeq M23
M4 \otimes M25 \simeq M26
M4 \otimes M26 \simeq M25
M4 \otimes M27 \simeq M28
M4 \otimes M28 \simeq M27
M4 \otimes M29 \simeq M30
M4 \otimes M30 \simeq M29
M4 \otimes M31 \simeq M32
M4 \otimes M32 \simeq M31
M4 \otimes M33 \simeq M36
M4 \otimes M34 \simeq M37
M4 \otimes M35 \simeq M38
M4 \otimes M36 \simeq M33
M4 \otimes M37 \simeq M34
M4 \otimes M38 \simeq M35
M4 \otimes M39 \simeq M42
M4 \otimes M40 \simeq M43
M4 \otimes M41 \simeq M44
M4 \otimes M42 \simeq M39
M4 \otimes M43 \simeq M40
M4 \otimes M44 \simeq M41
M4 \otimes M45 \simeq M48
M4 \otimes M46 \simeq M49
M4 \otimes M47 \simeq M50
M4 \otimes M48 \simeq M45
M4 \otimes M49 \simeq M46
M4 \otimes M50 \simeq M47
M4 \otimes M51 \simeq M54
M4 \otimes M52 \simeq M55
M4 \otimes M53 \simeq M56
M4 \otimes M54 \simeq M51
M4 \otimes M55 \simeq M52
M4 \otimes M56 \simeq M53
--------------------------------------------------------------
M5 \otimes M5 \simeq M3
M5 \otimes M6 \simeq M4
M5 \otimes M7 \simeq M11
M5 \otimes M8 \simeq M12
M5 \otimes M9 \simeq M7
M5 \otimes M10 \simeq M8
M5 \otimes M11 \simeq M9
M5 \otimes M12 \simeq M10
M5 \otimes M13 \simeq M13
M5 \otimes M14 \simeq M14
M5 \otimes M15 \simeq M15
M5 \otimes M16 \simeq M16
M5 \otimes M17 \simeq M17
M5 \otimes M18 \simeq M18
M5 \otimes M19 \simeq M19
M5 \otimes M20 \simeq M20
M5 \otimes M21 \simeq M21
M5 \otimes M22 \simeq M22
M5 \otimes M23 \simeq M23
M5 \otimes M24 \simeq M24
M5 \otimes M25 \simeq M25
M5 \otimes M26 \simeq M26
M5 \otimes M27 \simeq M27
M5 \otimes M28 \simeq M28
M5 \otimes M29 \simeq M29
M5 \otimes M30 \simeq M30
M5 \otimes M31 \simeq M31
M5 \otimes M32 \simeq M32
M5 \otimes M33 \simeq M35
M5 \otimes M34 \simeq M36
M5 \otimes M35 \simeq M37
M5 \otimes M36 \simeq M38
M5 \otimes M37 \simeq M33
M5 \otimes M38 \simeq M34
M5 \otimes M39 \simeq M41
M5 \otimes M40 \simeq M42
M5 \otimes M41 \simeq M43
M5 \otimes M42 \simeq M44
M5 \otimes M43 \simeq M39
M5 \otimes M44 \simeq M40
M5 \otimes M45 \simeq M47
M5 \otimes M46 \simeq M48
M5 \otimes M47 \simeq M49
M5 \otimes M48 \simeq M50
M5 \otimes M49 \simeq M45
M5 \otimes M50 \simeq M46
M5 \otimes M51 \simeq M53
M5 \otimes M52 \simeq M54
M5 \otimes M53 \simeq M55
M5 \otimes M54 \simeq M56
M5 \otimes M55 \simeq M51
M5 \otimes M56 \simeq M52
--------------------------------------------------------------
M6 \otimes M6 \simeq M5
M6 \otimes M7 \simeq M12
M6 \otimes M8 \simeq M7
M6 \otimes M9 \simeq M8
M6 \otimes M10 \simeq M9
M6 \otimes M11 \simeq M10
M6 \otimes M12 \simeq M11
M6 \otimes M13 \simeq M14
M6 \otimes M14 \simeq M13
M6 \otimes M15 \simeq M16
M6 \otimes M16 \simeq M15
M6 \otimes M17 \simeq M18
M6 \otimes M18 \simeq M17
M6 \otimes M19 \simeq M20
M6 \otimes M20 \simeq M19
M6 \otimes M21 \simeq M22
M6 \otimes M22 \simeq M21
M6 \otimes M23 \simeq M24
M6 \otimes M24 \simeq M23
M6 \otimes M25 \simeq M26
M6 \otimes M26 \simeq M25
M6 \otimes M27 \simeq M28
M6 \otimes M28 \simeq M27
M6 \otimes M29 \simeq M30
M6 \otimes M30 \simeq M29
M6 \otimes M31 \simeq M32
M6 \otimes M32 \simeq M31
M6 \otimes M33 \simeq M34
M6 \otimes M34 \simeq M35
M6 \otimes M35 \simeq M36
M6 \otimes M36 \simeq M37
M6 \otimes M37 \simeq M38
M6 \otimes M38 \simeq M33
M6 \otimes M39 \simeq M40
M6 \otimes M40 \simeq M41
M6 \otimes M41 \simeq M42
M6 \otimes M42 \simeq M43
M6 \otimes M43 \simeq M44
M6 \otimes M44 \simeq M39
M6 \otimes M45 \simeq M46
M6 \otimes M46 \simeq M47
M6 \otimes M47 \simeq M48
M6 \otimes M48 \simeq M49
M6 \otimes M49 \simeq M50
M6 \otimes M50 \simeq M45
M6 \otimes M51 \simeq M52
M6 \otimes M52 \simeq M53
M6 \otimes M53 \simeq M54
M6 \otimes M54 \simeq M55
M6 \otimes M55 \simeq M56
M6 \otimes M56 \simeq M51
--------------------------------------------------------------
M7 \otimes M7 \simeq M1
M7 \otimes M8 \simeq M2
M7 \otimes M9 \simeq M3
M7 \otimes M10 \simeq M4
M7 \otimes M11 \simeq M5
M7 \otimes M12 \simeq M6
M7 \otimes M13 \simeq M15
M7 \otimes M14 \simeq M16
M7 \otimes M15 \simeq M13
M7 \otimes M16 \simeq M14
M7 \otimes M17 \simeq M25
M7 \otimes M18 \simeq M26
M7 \otimes M19 \simeq M27
M7 \otimes M20 \simeq M28
M7 \otimes M21 \simeq M29
M7 \otimes M22 \simeq M30
M7 \otimes M23 \simeq M31
M7 \otimes M24 \simeq M32
M7 \otimes M25 \simeq M17
M7 \otimes M26 \simeq M18
M7 \otimes M27 \simeq M19
M7 \otimes M28 \simeq M20
M7 \otimes M29 \simeq M21
M7 \otimes M30 \simeq M22
M7 \otimes M31 \simeq M23
M7 \otimes M32 \simeq M24
M7 \otimes M33 \simeq M45
M7 \otimes M34 \simeq M46
M7 \otimes M35 \simeq M47
M7 \otimes M36 \simeq M48
M7 \otimes M37 \simeq M49
M7 \otimes M38 \simeq M50
M7 \otimes M39 \simeq M51
M7 \otimes M40 \simeq M52
M7 \otimes M41 \simeq M53
M7 \otimes M42 \simeq M54
M7 \otimes M43 \simeq M55
M7 \otimes M44 \simeq M56
M7 \otimes M45 \simeq M33
M7 \otimes M46 \simeq M34
M7 \otimes M47 \simeq M35
M7 \otimes M48 \simeq M36
M7 \otimes M49 \simeq M37
M7 \otimes M50 \simeq M38
M7 \otimes M51 \simeq M39
M7 \otimes M52 \simeq M40
M7 \otimes M53 \simeq M41
M7 \otimes M54 \simeq M42
M7 \otimes M55 \simeq M43
M7 \otimes M56 \simeq M44
--------------------------------------------------------------
M8 \otimes M8 \simeq M3
M8 \otimes M9 \simeq M4
M8 \otimes M10 \simeq M5
M8 \otimes M11 \simeq M6
M8 \otimes M12 \simeq M1
M8 \otimes M13 \simeq M16
M8 \otimes M14 \simeq M15
M8 \otimes M15 \simeq M14
M8 \otimes M16 \simeq M13
M8 \otimes M17 \simeq M26
M8 \otimes M18 \simeq M25
M8 \otimes M19 \simeq M28
M8 \otimes M20 \simeq M27
M8 \otimes M21 \simeq M30
M8 \otimes M22 \simeq M29
M8 \otimes M23 \simeq M32
M8 \otimes M24 \simeq M31
M8 \otimes M25 \simeq M18
M8 \otimes M26 \simeq M17
M8 \otimes M27 \simeq M20
M8 \otimes M28 \simeq M19
M8 \otimes M29 \simeq M22
M8 \otimes M30 \simeq M21
M8 \otimes M31 \simeq M24
M8 \otimes M32 \simeq M23
M8 \otimes M33 \simeq M50
M8 \otimes M34 \simeq M45
M8 \otimes M35 \simeq M46
M8 \otimes M36 \simeq M47
M8 \otimes M37 \simeq M48
M8 \otimes M38 \simeq M49
M8 \otimes M39 \simeq M56
M8 \otimes M40 \simeq M51
M8 \otimes M41 \simeq M52
M8 \otimes M42 \simeq M53
M8 \otimes M43 \simeq M54
M8 \otimes M44 \simeq M55
M8 \otimes M45 \simeq M38
M8 \otimes M46 \simeq M33
M8 \otimes M47 \simeq M34
M8 \otimes M48 \simeq M35
M8 \otimes M49 \simeq M36
M8 \otimes M50 \simeq M37
M8 \otimes M51 \simeq M44
M8 \otimes M52 \simeq M39
M8 \otimes M53 \simeq M40
M8 \otimes M54 \simeq M41
M8 \otimes M55 \simeq M42
M8 \otimes M56 \simeq M43
--------------------------------------------------------------
M9 \otimes M9 \simeq M5
M9 \otimes M10 \simeq M6
M9 \otimes M11 \simeq M1
M9 \otimes M12 \simeq M2
M9 \otimes M13 \simeq M15
M9 \otimes M14 \simeq M16
M9 \otimes M15 \simeq M13
M9 \otimes M16 \simeq M14
M9 \otimes M17 \simeq M25
M9 \otimes M18 \simeq M26
M9 \otimes M19 \simeq M27
M9 \otimes M20 \simeq M28
M9 \otimes M21 \simeq M29
M9 \otimes M22 \simeq M30
M9 \otimes M23 \simeq M31
M9 \otimes M24 \simeq M32
M9 \otimes M25 \simeq M17
M9 \otimes M26 \simeq M18
M9 \otimes M27 \simeq M19
M9 \otimes M28 \simeq M20
M9 \otimes M29 \simeq M21
M9 \otimes M30 \simeq M22
M9 \otimes M31 \simeq M23
M9 \otimes M32 \simeq M24
M9 \otimes M33 \simeq M49
M9 \otimes M34 \simeq M50
M9 \otimes M35 \simeq M45
M9 \otimes M36 \simeq M46
M9 \otimes M37 \simeq M47
M9 \otimes M38 \simeq M48
M9 \otimes M39 \simeq M55
M9 \otimes M40 \simeq M56
M9 \otimes M41 \simeq M51
M9 \otimes M42 \simeq M52
M9 \otimes M43 \simeq M53
M9 \otimes M44 \simeq M54
M9 \otimes M45 \simeq M37
M9 \otimes M46 \simeq M38
M9 \otimes M47 \simeq M33
M9 \otimes M48 \simeq M34
M9 \otimes M49 \simeq M35
M9 \otimes M50 \simeq M36
M9 \otimes M51 \simeq M43
M9 \otimes M52 \simeq M44
M9 \otimes M53 \simeq M39
M9 \otimes M54 \simeq M40
M9 \otimes M55 \simeq M41
M9 \otimes M56 \simeq M42
--------------------------------------------------------------
M10 \otimes M10 \simeq M1
M10 \otimes M11 \simeq M2
M10 \otimes M12 \simeq M3
M10 \otimes M13 \simeq M16
M10 \otimes M14 \simeq M15
M10 \otimes M15 \simeq M14
M10 \otimes M16 \simeq M13
M10 \otimes M17 \simeq M26
M10 \otimes M18 \simeq M25
M10 \otimes M19 \simeq M28
M10 \otimes M20 \simeq M27
M10 \otimes M21 \simeq M30
M10 \otimes M22 \simeq M29
M10 \otimes M23 \simeq M32
M10 \otimes M24 \simeq M31
M10 \otimes M25 \simeq M18
M10 \otimes M26 \simeq M17
M10 \otimes M27 \simeq M20
M10 \otimes M28 \simeq M19
M10 \otimes M29 \simeq M22
M10 \otimes M30 \simeq M21
M10 \otimes M31 \simeq M24
M10 \otimes M32 \simeq M23
M10 \otimes M33 \simeq M48
M10 \otimes M34 \simeq M49
M10 \otimes M35 \simeq M50
M10 \otimes M36 \simeq M45
M10 \otimes M37 \simeq M46
M10 \otimes M38 \simeq M47
M10 \otimes M39 \simeq M54
M10 \otimes M40 \simeq M55
M10 \otimes M41 \simeq M56
M10 \otimes M42 \simeq M51
M10 \otimes M43 \simeq M52
M10 \otimes M44 \simeq M53
M10 \otimes M45 \simeq M36
M10 \otimes M46 \simeq M37
M10 \otimes M47 \simeq M38
M10 \otimes M48 \simeq M33
M10 \otimes M49 \simeq M34
M10 \otimes M50 \simeq M35
M10 \otimes M51 \simeq M42
M10 \otimes M52 \simeq M43
M10 \otimes M53 \simeq M44
M10 \otimes M54 \simeq M39
M10 \otimes M55 \simeq M40
M10 \otimes M56 \simeq M41
--------------------------------------------------------------
M11 \otimes M11 \simeq M3
M11 \otimes M12 \simeq M4
M11 \otimes M13 \simeq M15
M11 \otimes M14 \simeq M16
M11 \otimes M15 \simeq M13
M11 \otimes M16 \simeq M14
M11 \otimes M17 \simeq M25
M11 \otimes M18 \simeq M26
M11 \otimes M19 \simeq M27
M11 \otimes M20 \simeq M28
M11 \otimes M21 \simeq M29
M11 \otimes M22 \simeq M30
M11 \otimes M23 \simeq M31
M11 \otimes M24 \simeq M32
M11 \otimes M25 \simeq M17
M11 \otimes M26 \simeq M18
M11 \otimes M27 \simeq M19
M11 \otimes M28 \simeq M20
M11 \otimes M29 \simeq M21
M11 \otimes M30 \simeq M22
M11 \otimes M31 \simeq M23
M11 \otimes M32 \simeq M24
M11 \otimes M33 \simeq M47
M11 \otimes M34 \simeq M48
M11 \otimes M35 \simeq M49
M11 \otimes M36 \simeq M50
M11 \otimes M37 \simeq M45
M11 \otimes M38 \simeq M46
M11 \otimes M39 \simeq M53
M11 \otimes M40 \simeq M54
M11 \otimes M41 \simeq M55
M11 \otimes M42 \simeq M56
M11 \otimes M43 \simeq M51
M11 \otimes M44 \simeq M52
M11 \otimes M45 \simeq M35
M11 \otimes M46 \simeq M36
M11 \otimes M47 \simeq M37
M11 \otimes M48 \simeq M38
M11 \otimes M49 \simeq M33
M11 \otimes M50 \simeq M34
M11 \otimes M51 \simeq M41
M11 \otimes M52 \simeq M42
M11 \otimes M53 \simeq M43
M11 \otimes M54 \simeq M44
M11 \otimes M55 \simeq M39
M11 \otimes M56 \simeq M40
--------------------------------------------------------------
M12 \otimes M12 \simeq M5
M12 \otimes M13 \simeq M16
M12 \otimes M14 \simeq M15
M12 \otimes M15 \simeq M14
M12 \otimes M16 \simeq M13
M12 \otimes M17 \simeq M26
M12 \otimes M18 \simeq M25
M12 \otimes M19 \simeq M28
M12 \otimes M20 \simeq M27
M12 \otimes M21 \simeq M30
M12 \otimes M22 \simeq M29
M12 \otimes M23 \simeq M32
M12 \otimes M24 \simeq M31
M12 \otimes M25 \simeq M18
M12 \otimes M26 \simeq M17
M12 \otimes M27 \simeq M20
M12 \otimes M28 \simeq M19
M12 \otimes M29 \simeq M22
M12 \otimes M30 \simeq M21
M12 \otimes M31 \simeq M24
M12 \otimes M32 \simeq M23
M12 \otimes M33 \simeq M46
M12 \otimes M34 \simeq M47
M12 \otimes M35 \simeq M48
M12 \otimes M36 \simeq M49
M12 \otimes M37 \simeq M50
M12 \otimes M38 \simeq M45
M12 \otimes M39 \simeq M52
M12 \otimes M40 \simeq M53
M12 \otimes M41 \simeq M54
M12 \otimes M42 \simeq M55
M12 \otimes M43 \simeq M56
M12 \otimes M44 \simeq M51
M12 \otimes M45 \simeq M34
M12 \otimes M46 \simeq M35
M12 \otimes M47 \simeq M36
M12 \otimes M48 \simeq M37
M12 \otimes M49 \simeq M38
M12 \otimes M50 \simeq M33
M12 \otimes M51 \simeq M40
M12 \otimes M52 \simeq M41
M12 \otimes M53 \simeq M42
M12 \otimes M54 \simeq M43
M12 \otimes M55 \simeq M44
M12 \otimes M56 \simeq M39
--------------------------------------------------------------
M13 \otimes M13 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M13 \otimes M14 \simeq M2 \oplus M4 \oplus M6 \oplus 2 M14
M13 \otimes M15 \simeq M7 \oplus M9 \oplus M11 \oplus 2 M15
M13 \otimes M16 \simeq M8 \oplus M10 \oplus M12 \oplus 2 M16
M13 \otimes M17 \simeq M19 \oplus M21 \oplus M23
M13 \otimes M18 \simeq M20 \oplus M22 \oplus M24
M13 \otimes M19 \simeq M17 \oplus M21 \oplus M23
M13 \otimes M20 \simeq M18 \oplus M22 \oplus M24
M13 \otimes M21 \simeq M17 \oplus M19 \oplus M23
M13 \otimes M22 \simeq M18 \oplus M20 \oplus M24
M13 \otimes M23 \simeq M17 \oplus M19 \oplus M21
M13 \otimes M24 \simeq M18 \oplus M20 \oplus M22
M13 \otimes M25 \simeq M27 \oplus M29 \oplus M31
M13 \otimes M26 \simeq M28 \oplus M30 \oplus M32
M13 \otimes M27 \simeq M25 \oplus M29 \oplus M31
M13 \otimes M28 \simeq M26 \oplus M30 \oplus M32
M13 \otimes M29 \simeq M25 \oplus M27 \oplus M31
M13 \otimes M30 \simeq M26 \oplus M28 \oplus M32
M13 \otimes M31 \simeq M25 \oplus M27 \oplus M29
M13 \otimes M32 \simeq M26 \oplus M28 \oplus M30
M13 \otimes M33 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M34 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M35 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M36 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M37 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M38 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M39 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M40 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M41 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M42 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M43 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M44 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M45 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M46 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M47 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M48 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M49 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M50 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M51 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M52 \simeq M52 \oplus M54 \oplus M56
M13 \otimes M53 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M54 \simeq M52 \oplus M54 \oplus M56
M13 \otimes M55 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M56 \simeq M52 \oplus M54 \oplus M56
--------------------------------------------------------------
M14 \otimes M14 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M14 \otimes M15 \simeq M8 \oplus M10 \oplus M12 \oplus 2 M16
M14 \otimes M16 \simeq M7 \oplus M9 \oplus M11 \oplus 2 M15
M14 \otimes M17 \simeq M20 \oplus M22 \oplus M24
M14 \otimes M18 \simeq M19 \oplus M21 \oplus M23
M14 \otimes M19 \simeq M18 \oplus M22 \oplus M24
M14 \otimes M20 \simeq M17 \oplus M21 \oplus M23
M14 \otimes M21 \simeq M18 \oplus M20 \oplus M24
M14 \otimes M22 \simeq M17 \oplus M19 \oplus M23
M14 \otimes M23 \simeq M18 \oplus M20 \oplus M22
M14 \otimes M24 \simeq M17 \oplus M19 \oplus M21
M14 \otimes M25 \simeq M28 \oplus M30 \oplus M32
M14 \otimes M26 \simeq M27 \oplus M29 \oplus M31
M14 \otimes M27 \simeq M26 \oplus M30 \oplus M32
M14 \otimes M28 \simeq M25 \oplus M29 \oplus M31
M14 \otimes M29 \simeq M26 \oplus M28 \oplus M32
M14 \otimes M30 \simeq M25 \oplus M27 \oplus M31
M14 \otimes M31 \simeq M26 \oplus M28 \oplus M30
M14 \otimes M32 \simeq M25 \oplus M27 \oplus M29
M14 \otimes M33 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M34 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M35 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M36 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M37 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M38 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M39 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M40 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M41 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M42 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M43 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M44 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M45 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M46 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M47 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M48 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M49 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M50 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M51 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M52 \simeq M51 \oplus M53 \oplus M55
M14 \otimes M53 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M54 \simeq M51 \oplus M53 \oplus M55
M14 \otimes M55 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M56 \simeq M51 \oplus M53 \oplus M55
--------------------------------------------------------------
M15 \otimes M15 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M15 \otimes M16 \simeq M2 \oplus M4 \oplus M6 \oplus 2 M14
M15 \otimes M17 \simeq M27 \oplus M29 \oplus M31
M15 \otimes M18 \simeq M28 \oplus M30 \oplus M32
M15 \otimes M19 \simeq M25 \oplus M29 \oplus M31
M15 \otimes M20 \simeq M26 \oplus M30 \oplus M32
M15 \otimes M21 \simeq M25 \oplus M27 \oplus M31
M15 \otimes M22 \simeq M26 \oplus M28 \oplus M32

In [428]:
QGNAG_LoadAllFusionRulesToLaTeX("fusion_rules_with_index.tex", data_parallel );

## Fusion Rules by Names

In [429]:
if QGNAG.Config.PROD then
    for i in [2..Length(SimplesMn)] do
        Print("--------------------------------------------------------------\n");
        for j in [i..Length(SimplesMn)] do
            MtensorN := QGNAG_TensorProductOfSimples(SimplesMn[i], SimplesMn[j]);
            Print(QGNAG_FusionRuleToLaTeX( MtensorN, SimplesMn, SimpleNames), "\n");
    od;
od;
fi;

In [430]:
QGNAG_LoadAllFusionRulesWithNamesToLaTeX( "fusion_rules_with_names.tex", data_parallel, SimpleNames );

In [431]:
QGNAG_LoadFusionRulesToLaTeXSingleLong(
    "fusion_rules_single_long.tex",
    data_parallel,
    SimpleNames,
    3
);

### Para las matrices de $\mathfrak{B}(V)$

In [435]:
X0ActionOnBaseT4 := List(Base_T4, bi-> StrongNormalFormNP( MulNP( GP2NP(X0),  bi ), J_T4));;
X1ActionOnBaseT4 := List(Base_T4, bi-> StrongNormalFormNP( MulNP( GP2NP(X1),  bi ), J_T4));;
X2ActionOnBaseT4 := List(Base_T4, bi-> StrongNormalFormNP( MulNP( GP2NP(X2),  bi ), J_T4));;
X3ActionOnBaseT4 := List(Base_T4, bi-> StrongNormalFormNP( MulNP( GP2NP(X3),  bi ), J_T4));;

In [439]:
X0_matrix_on_Nichols := StructureMatrixForXi( X0ActionOnBaseT4, Base_T4 );;
X1_matrix_on_Nichols := StructureMatrixForXi( X1ActionOnBaseT4, Base_T4 );;
X2_matrix_on_Nichols := StructureMatrixForXi( X2ActionOnBaseT4, Base_T4 );;
X3_matrix_on_Nichols := StructureMatrixForXi( X3ActionOnBaseT4, Base_T4 );;

In [441]:
gensG     := GP2NPList([ F1,     F2, F3, F4 ]);;
inv_gensG := GP2NPList([ F1^5, F2^2, F3, F4  ]);; # validar la lista

In [445]:
F1ConjugationOnNicholsBasis := List(Base_T4, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[1], bi), inv_gensG[1]), J_D_ge_0));;
F2ConjugationOnNicholsBasis := List(Base_T4, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[2], bi), inv_gensG[2]), J_D_ge_0));;
F3ConjugationOnNicholsBasis := List(Base_T4, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[3], bi), inv_gensG[3]), J_D_ge_0));;
F4ConjugationOnNicholsBasis := List(Base_T4, bi-> StrongNormalFormNP(MulNP(MulNP(gensG[4], bi), inv_gensG[4]), J_D_ge_0));;

In [449]:
Mt_matrix_on_Nichols := StructureMatrixOfG(F1ConjugationOnNicholsBasis, Base_T4);;
Mx_matrix_on_Nichols := StructureMatrixOfG(F2ConjugationOnNicholsBasis, Base_T4);;
My_matrix_on_Nichols := StructureMatrixOfG(F3ConjugationOnNicholsBasis, Base_T4);;
Mz_matrix_on_Nichols := StructureMatrixOfG(F4ConjugationOnNicholsBasis, Base_T4);;

### Para las matrices de $\Bbbk^G$

In [473]:
De_functions        := QGNAG_DeltaFunctions(gensDeltas[1], Base_T4);;
DF1_functions       := QGNAG_DeltaFunctions(gensDeltas[2], Base_T4);;
DF2_functions       := QGNAG_DeltaFunctions(gensDeltas[3], Base_T4);;
DF1F2_functions     := QGNAG_DeltaFunctions(gensDeltas[4], Base_T4);;
DF2F2_functions     := QGNAG_DeltaFunctions(gensDeltas[5], Base_T4);;
DF1F2F2_functions   := QGNAG_DeltaFunctions(gensDeltas[6], Base_T4);;

DF4_functions       := QGNAG_DeltaFunctions(gensDeltas[7], Base_T4);;
DF4F1_functions     := QGNAG_DeltaFunctions(gensDeltas[8], Base_T4);;
DF2F3_functions     := QGNAG_DeltaFunctions(gensDeltas[9], Base_T4);;
DF1F2F4_functions   := QGNAG_DeltaFunctions(gensDeltas[10], Base_T4);;
DF2F3F2_functions   := QGNAG_DeltaFunctions(gensDeltas[11], Base_T4);;
DF1F2F2F3_functions := QGNAG_DeltaFunctions(gensDeltas[12], Base_T4);;

DF3_functions       := QGNAG_DeltaFunctions(gensDeltas[13], Base_T4);;
DF1F4_functions     := QGNAG_DeltaFunctions(gensDeltas[14], Base_T4);;
DF3F2_functions     := QGNAG_DeltaFunctions(gensDeltas[15], Base_T4);;
DF1F2F3_functions   := QGNAG_DeltaFunctions(gensDeltas[16], Base_T4);;
DF2F2F4_functions   := QGNAG_DeltaFunctions(gensDeltas[17], Base_T4);;
DF1F2F3F2_functions := QGNAG_DeltaFunctions(gensDeltas[18], Base_T4);;

DF3F4_functions     := QGNAG_DeltaFunctions(gensDeltas[19], Base_T4);;
DF1F3_functions     := QGNAG_DeltaFunctions(gensDeltas[20], Base_T4);;
DF2F4_functions     := QGNAG_DeltaFunctions(gensDeltas[21], Base_T4);;
DF1F3F2_functions   := QGNAG_DeltaFunctions(gensDeltas[22], Base_T4);;
DF2F2F3_functions   := QGNAG_DeltaFunctions(gensDeltas[23], Base_T4);;
DF1F2F2F4_functions := QGNAG_DeltaFunctions(gensDeltas[24], Base_T4);;

# Main Loop

In [478]:
data_verma_char          := [];;
data_AllMatricesByDegree := [];;
data_record_data_decomp  := [];;
data_rec_info            := [];;
data_reps_mats           := [];

[  ]

In [479]:
for index_s in [1..Length(SimplesMn)] do
    simpleM := SimplesMn[index_s];;

    ## Matrices de $\mathfrak{B}(V)$ 
    X0_matrix := QGNAG_XiMatrixAction(X0_matrix_on_Nichols, simpleM);;
    X1_matrix := QGNAG_XiMatrixAction(X1_matrix_on_Nichols, simpleM);;
    X2_matrix := QGNAG_XiMatrixAction(X2_matrix_on_Nichols, simpleM);;
    X3_matrix := QGNAG_XiMatrixAction(X3_matrix_on_Nichols, simpleM);;
    all_matrix_rep_nichols := [ X0_matrix, X1_matrix, X2_matrix, X3_matrix ];;
    
    ## Matrices de $G$
    # 
    Mt_matrix := QGNAG_GiMatrixAction(Mt_matrix_on_Nichols, simpleM.simple(G.1));;
    Mx_matrix := QGNAG_GiMatrixAction(Mx_matrix_on_Nichols, simpleM.simple(G.2));;
    My_matrix := QGNAG_GiMatrixAction(My_matrix_on_Nichols, simpleM.simple(G.3));;
    Mz_matrix := QGNAG_GiMatrixAction(Mz_matrix_on_Nichols, simpleM.simple(G.4));;
    all_matrix_rep_kG := [Mt_matrix, Mx_matrix, My_matrix, Mz_matrix];;
    
    ## Matrices de $\delta_h$ con $h\in G$.
    # 
    De_matrix        := QGNAG_DeltaMatrix(De_functions, simpleM);;
    DF1_matrix       := QGNAG_DeltaMatrix(DF1_functions, simpleM);;
    DF2_matrix       := QGNAG_DeltaMatrix(DF2_functions, simpleM);;
    DF1F2_matrix     := QGNAG_DeltaMatrix(DF1F2_functions, simpleM);;
    DF2F2_matrix     := QGNAG_DeltaMatrix(DF2F2_functions, simpleM);;
    DF1F2F2_matrix   := QGNAG_DeltaMatrix(DF1F2F2_functions, simpleM);;
    
    DF4_matrix       := QGNAG_DeltaMatrix(DF4_functions, simpleM);;
    DF4F1_matrix     := QGNAG_DeltaMatrix(DF4F1_functions, simpleM);;
    DF2F3_matrix     := QGNAG_DeltaMatrix(DF2F3_functions, simpleM);;
    DF1F2F4_matrix   := QGNAG_DeltaMatrix(DF1F2F4_functions, simpleM);;
    DF2F3F2_matrix   := QGNAG_DeltaMatrix(DF2F3F2_functions, simpleM);;
    DF1F2F2F3_matrix := QGNAG_DeltaMatrix(DF1F2F2F3_functions, simpleM);;
    
    DF3_matrix       := QGNAG_DeltaMatrix(DF3_functions, simpleM);;
    DF1F4_matrix     := QGNAG_DeltaMatrix(DF1F4_functions, simpleM);;
    DF3F2_matrix     := QGNAG_DeltaMatrix(DF3F2_functions, simpleM);;
    DF1F2F3_matrix   := QGNAG_DeltaMatrix(DF1F2F3_functions, simpleM);;
    DF2F2F4_matrix   := QGNAG_DeltaMatrix(DF2F2F4_functions, simpleM);;
    DF1F2F3F2_matrix := QGNAG_DeltaMatrix(DF1F2F3F2_functions, simpleM);;
    
    DF3F4_matrix     := QGNAG_DeltaMatrix(DF3F4_functions, simpleM);;
    DF1F3_matrix     := QGNAG_DeltaMatrix(DF1F3_functions, simpleM);;
    DF2F4_matrix     := QGNAG_DeltaMatrix(DF2F4_functions, simpleM);;
    DF1F3F2_matrix   := QGNAG_DeltaMatrix(DF1F3F2_functions, simpleM);;
    DF2F2F3_matrix   := QGNAG_DeltaMatrix(DF2F2F3_functions, simpleM);;
    DF1F2F2F4_matrix := QGNAG_DeltaMatrix(DF1F2F2F4_functions, simpleM);;
    
    all_matrix_rep_kG_dual := [
        De_matrix,
        DF1_matrix,
        DF2_matrix,
        DF1F2_matrix,
        DF2F2_matrix,
        DF1F2F2_matrix,
        DF4_matrix,
        DF4F1_matrix,
        DF2F3_matrix,
        DF1F2F4_matrix,
        DF2F3F2_matrix,
        DF1F2F2F3_matrix,
        DF3_matrix,
        DF1F4_matrix,
        DF3F2_matrix,
        DF1F2F3_matrix,
        DF2F2F4_matrix,
        DF1F2F3F2_matrix,
        DF3F4_matrix,
        DF1F3_matrix,
        DF2F4_matrix,
        DF1F3F2_matrix,
        DF2F2F3_matrix,
        DF1F2F2F4_matrix
    ];;
    
    # Matrices de $Y_j$
    # 
    list_mat_in_DG := QGNAG_ConstructDGActionMatrices(simpleM, allPairsInG, Base_T4);;
    Y0_matrix := MatrixActionYiOnNicholsBasis(Y0bis, simpleM, Base_T4, list_mat_in_DG);;
    Y1_matrix := MatrixActionYiOnNicholsBasis(Y1bis, simpleM, Base_T4, list_mat_in_DG);;
    Y2_matrix := MatrixActionYiOnNicholsBasis(Y2bis, simpleM, Base_T4, list_mat_in_DG);;
    Y3_matrix := MatrixActionYiOnNicholsBasis(Y3bis, simpleM, Base_T4, list_mat_in_DG);;
    all_matrix_rep_nichols_dual := [ Y0_matrix, Y1_matrix, Y2_matrix, Y3_matrix ];;
    
    # 
    all_matrix_rep_DG := Concatenation( all_matrix_rep_kG, all_matrix_rep_kG_dual );
    data_reps_mats[index_s] := all_matrix_rep_DG;
    
    # 
    all_matrix_rep    := Concatenation( all_matrix_rep_nichols, all_matrix_rep_DG, all_matrix_rep_nichols_dual );;

    #
    Print("index s = ", index_s, ", Simple: ", SimpleNames[index_s], " \n");
    QGNAG_CheckRelationsShift( relsxBos, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsDx, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsyBos, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsDy, all_matrix_rep , 0 );
    QGNAG_CheckRelationsShift( relsQG, all_matrix_rep , 0 );
    
    # Verma Module
    # 
    F  := CF(6);;
    D  := AlgebraWithOne( F, all_matrix_rep );;
    Nm := Length(simpleM.base)*Length(Base_T4);;
    L  := LeftAlgebraModule(D, \*, F^Nm );
    
    verma_char := QGNAG_Character( L, simpleM, Base_T4, NicholsGradingData );;
    Add(data_verma_char, verma_char);;
    
    AllMatricesByDegree := QGNAG_AllMatricesByDegree( verma_char, all_matrix_rep_DG );;
    Add(data_AllMatricesByDegree, AllMatricesByDegree);;

    record_data_decomp := QGNAG_SimpleVermaModuleDecomposition( SimplesMn, allPairsInG, Base_T4, AllMatricesByDegree );
    Add(data_record_data_decomp, record_data_decomp );;
    
    rec_info := QGNAG_Decomposition(record_data_decomp);
    Add(data_rec_info, rec_info);;
od;

index s = 1, Simple: M(0,\tau_{00})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 2, Simple: M(0,\tau_{12})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 3, Simple: M(0,\tau_{01})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 4, Simple: M(0,\tau_{10})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 5, Simple: M(0,\tau_{02})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 6, Simple: M(0,\tau_{11})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 7, Simple: M(3,\tau_{00})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 8, Simple: M(3,\tau_{12})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 9, Simple: M(3,\tau_{01})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 10, Simple: M(3,\tau_{10})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 11, Simple: M(3,\tau_{02})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 12, Simple: M(3,\tau_{11})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 13, Simple: M(0,\rho_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 14, Simple: M(0,\rho_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 15, Simple: M(3,\rho_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 16, Simple: M(3,\rho_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 17, Simple: M(0,\chi_{(0,0,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 18, Simple: M(0,\chi_{(0,0,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 19, Simple: M(0,\chi_{(0,1,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 20, Simple: M(0,\chi_{(0,1,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 21, Simple: M(0,\chi_{(1,0,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 22, Simple: M(0,\chi_{(1,0,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 23, Simple: M(0,\chi_{(1,1,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 24, Simple: M(0,\chi_{(1,1,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 25, Simple: M(3,\chi_{(0,0,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 26, Simple: M(3,\chi_{(0,0,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 27, Simple: M(3,\chi_{(0,1,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 28, Simple: M(3,\chi_{(0,1,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 29, Simple: M(3,\chi_{(1,0,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 30, Simple: M(3,\chi_{(1,0,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 31, Simple: M(3,\chi_{(1,1,0)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 32, Simple: M(3,\chi_{(1,1,1)})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 33, Simple: M(1,\eta_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 34, Simple: M(1,\eta_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 35, Simple: M(1,\eta_{2})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 36, Simple: M(1,\eta_{3})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 37, Simple: M(1,\eta_{4})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 38, Simple: M(1,\eta_{5})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 39, Simple: M(2,\eta_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 40, Simple: M(2,\eta_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 41, Simple: M(2,\eta_{2})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 42, Simple: M(2,\eta_{3})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 43, Simple: M(2,\eta_{4})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 44, Simple: M(2,\eta_{5})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 45, Simple: M(4,\eta_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 46, Simple: M(4,\eta_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 47, Simple: M(4,\eta_{2})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 48, Simple: M(4,\eta_{3})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 49, Simple: M(4,\eta_{4})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 50, Simple: M(4,\eta_{5})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 51, Simple: M(5,\eta_{0})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 52, Simple: M(5,\eta_{1})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 53, Simple: M(5,\eta_{2})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 54, Simple: M(5,\eta_{3})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 55, Simple: M(5,\eta_{4})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
index s = 56, Simple: M(5,\eta_{5})
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.
All relations are satisfied.

In [480]:
QGNAG_LoadHilbertPolynomialsToLaTeX( "hilbert_series_T4.tex", data_verma_char, SimpleNames );;

In [481]:
QGNAG_LoadCharactersToLaTeXT:=function(filename, data_rec_info, SimpleNames)
    local out, i, rec_info, degrees, d, pair, mult, idx, first, term, LName;
    out := OutputTextFile(filename, false);
    for i in [1..Length(data_rec_info)] do
        rec_info := data_rec_info[i];
        # Obtener e,rho a partir de M(e,rho)
        LName := SimpleNames[i]{[3..Length(SimpleNames[i])-1]};
        AppendTo(out, "\\subsubsection{$L(", LName, ")$}\n");
        AppendTo(out, "\\[\n");
        AppendTo(out, "\\operatorname{Char}(", LName, ") = ");
        degrees := List(RecNames(rec_info), Int);
        Sort(degrees);
        first := true;
        for d in degrees do
            for pair in rec_info.(String(d)) do
                mult := pair[1];
                idx  := pair[2];
                if mult = 1 then
                    term := StringFormatted("{}[{}]",
                        SimpleNames[idx], d);
                else
                    term := StringFormatted("{}\\,{}[{}]",
                        mult, SimpleNames[idx], d);
                fi;
                if first then
                    AppendTo(out, term);
                    first := false;
                else
                    AppendTo(out, " + ", term);
                fi;
            od;
        od;
        AppendTo(out, "\n\\]\n\n");
    od;
    CloseStream(out);
end;

function( filename, data_rec_info, SimpleNames ) ... end

In [1500]:
QGNAG_LoadCharactersToLaTeXByIndex:=function(filename, data_rec_info)
    local out, i, rec_info, degrees, d, pair, mult, idx, first, term;
    out := OutputTextFile(filename, false);
    for i in [1..Length(data_rec_info)] do
        rec_info := data_rec_info[i];
        # Obtener e,rho a partir de M(e,rho)
        AppendTo(out, "\\subsubsection{$L_{", String(i), "}$}\n");
        AppendTo(out, "\\[\n");
        AppendTo(out, "\\operatorname{Char}_{", String(i), "} = ");
        degrees := List(RecNames(rec_info), Int);
        Sort(degrees);
        first := true;
        for d in degrees do
            for pair in rec_info.(String(d)) do
                mult := pair[1];
                idx  := pair[2];
                if mult = 1 then
                    term := StringFormatted("M_{{{}}}[{}]", String(idx), d);
                else
                    term := StringFormatted("{}\\,M_{{{}}}[{}]", mult, String(idx), d);
                fi;
                if first then
                    AppendTo(out, term);
                    first := false;
                else
                    AppendTo(out, " + ", term);
                fi;
            od;
        od;
        AppendTo(out, "\n\\]\n\n");
    od;
    CloseStream(out);
end;

function( filename, data_rec_info ) ... end

In [1501]:
QGNAG_LoadCharactersToLaTeXByIndex("characters_T4_by_index.tex", data_rec_info);

In [482]:
QGNAG_LoadCharactersToLaTeXT( "characters_T4.tex", data_rec_info, SimpleNames );

In [491]:
List(data_rec_info, r-> Minimum(List(RecNames(r), Int)));

[ 9, 6, 3, 0, 3, 6, 0, 3, 6, 9, 6, 3, 3, 0, 0, 3, 3, 0, 3, 0, 3, 6, 3, 6, 0,   3, 0, 3, 6, 3, 6, 3, 4, 1, 4, 7, 4, 1, 5, 2, 5, 2, 5, 2, 7, 4, 1, 4, 1, 4,   2, 5, 2, 5, 2, 5 ]

In [1405]:
index_beta_top:=data_rec_info[1];

rec( 9 := [ [ 1, 10 ] ] )

index_beta_top: 10

In [1493]:
QGNAG_BottomWeightPermutation := function(data_record_data_decomp, data_fusion_rules)
    local record_data_decomp_beta_top, rec_info_beta_top, n_top, 
          beta_top_keys, index_beta_top, theta, action_list, i, k, mult, target_k;
          
    # 1. Extract the beta_top decomposition data
    record_data_decomp_beta_top := data_record_data_decomp[1];
    rec_info_beta_top           := QGNAG_Decomposition(record_data_decomp_beta_top);
    
    # 2. Find the top degree n_top
    n_top         := Maximum(List(RecNames(record_data_decomp_beta_top[1]), Int));
    beta_top_keys := RecNames(rec_info_beta_top);
    
    # 3. Sanity checks
    if Length(beta_top_keys) <> 1 then
        Print("Error: rec_info_beta_top has more than one key.\n");
        return fail;
    fi;
    if Int(beta_top_keys[1]) <> n_top then
        Print("Error: The key does not match n_top.\n");
        return fail;
    fi;
    
    # 4. Get the index of the 1-dimensional module beta_top
    index_beta_top := rec_info_beta_top.(String(n_top))[1][2];
    Print("index_beta_top: ", index_beta_top, "\n\n");
    
    # 5. Compute the action on the simple modules
    theta       := Maximum(List(data_fusion_rules, r -> r.second));
    action_list := [];
    
    for i in [1..theta] do
        if i = 1 then
            Print("M_", i, " \\otimes M_", index_beta_top, " \\simeq M_", index_beta_top, "\n");
            Add(action_list, index_beta_top);
        else 
            target_k := fail;
            for k in [1..theta] do
                mult := QGNAG_GetTensorVectorEntry(data_fusion_rules, i, index_beta_top, k);
                if mult > 0 then
                    target_k := k;
                    Add(action_list, k);
                    # Break the inner loop early: since beta_top is 1-dimensional,
                    # the tensor product is irreducible and has multiplicity 1.
                    break; 
                fi;
            od;
            
            if target_k <> fail then
                Print("M_", i, " \\otimes M_", index_beta_top, " \\simeq M_", target_k, "\n");
            else
                Print("Error: No fusion rule found for M_", i, " \\otimes M_", index_beta_top, "\n");
            fi;
        fi;
    od;
    
    # Return the permutation representing the action of beta_top
    return PermList(action_list);
end;

function( data_record_data_decomp, data_fusion_rules ) ... end

In [1494]:
QGNAG_BottomWeightPermutation(data_record_data_decomp, data_parallel);

index_beta_top: 10

M_1 \otimes M_10 \simeq M_10
M_2 \otimes M_10 \simeq M_11
M_3 \otimes M_10 \simeq M_12
M_4 \otimes M_10 \simeq M_7
M_5 \otimes M_10 \simeq M_8
M_6 \otimes M_10 \simeq M_9
M_7 \otimes M_10 \simeq M_4
M_8 \otimes M_10 \simeq M_5
M_9 \otimes M_10 \simeq M_6
M_10 \otimes M_10 \simeq M_1
M_11 \otimes M_10 \simeq M_2
M_12 \otimes M_10 \simeq M_3
M_13 \otimes M_10 \simeq M_16
M_14 \otimes M_10 \simeq M_15
M_15 \otimes M_10 \simeq M_14
M_16 \otimes M_10 \simeq M_13
M_17 \otimes M_10 \simeq M_26
M_18 \otimes M_10 \simeq M_25
M_19 \otimes M_10 \simeq M_28
M_20 \otimes M_10 \simeq M_27
M_21 \otimes M_10 \simeq M_30
M_22 \otimes M_10 \simeq M_29
M_23 \otimes M_10 \simeq M_32
M_24 \otimes M_10 \simeq M_31
M_25 \otimes M_10 \simeq M_18
M_26 \otimes M_10 \simeq M_17
M_27 \otimes M_10 \simeq M_20
M_28 \otimes M_10 \simeq M_19
M_29 \otimes M_10 \simeq M_22
M_30 \otimes M_10 \simeq M_21
M_31 \otimes M_10 \simeq M_24
M_32 \otimes M_10 \simeq M_23
M_33 \otimes M_10 \simeq M_48
M_34 \otimes M_10 \simeq M_49
M_35 \otimes M_10 \simeq M_50
M_36 \otimes M_10 \simeq M_45
M_37 \otimes M_10 \simeq M_46
M_38 \otimes M_10 \simeq M_47
M_39 \otimes M_10 \simeq M_54
M_40 \otimes M_10 \simeq M_55
M_41 \otimes M_10 \simeq M_56
M_42 \otimes M_10 \simeq M_51
M_43 \otimes M_10 \simeq M_52
M_44 \otimes M_10 \simeq M_53
M_45 \otimes M_10 \simeq M_36
M_46 \otimes M_10 \simeq M_37
M_47 \otimes M_10 \simeq M_38
M_48 \otimes M_10 \simeq M_33
M_49 \otimes M_10 \simeq M_34
M_50 \otimes M_10 \simeq M_35
M_51 \otimes M_10 \simeq M_42
M_52 \otimes M_10 \simeq M_43
M_53 \otimes M_10 \simeq M_44
M_54 \otimes M_10 \simeq M_39
M_55 \otimes M_10 \simeq M_40
M_56 \otimes M_10 \simeq M_41

(1,10)(2,11)(3,12)(4,7)(5,8)(6,9)(13,16)(14,15)(17,26)(18,25)(19,28)(20,27)(21,30)(22,29)(23,32)(24,31)(33,48)(34,49)(35,50)(36,45)(37,46)(38,47)(39,54)(40,55)(41,56)(42,51)(43,52)(44,53)

The permutation is: 
$$( 1,10)( 2,11)( 3,12)( 4, 7)( 5, 8)( 6, 9)(13,16)(14,15)(17,26)(18,25)\\
(19,28)(20,27)(21,30)(22,29)(23,32)(24,31)(33,48)(34,49)(35,50)(36,45)(37,46)\\
(38,47)(39,54)(40,55)(41,56)(42,51)(43,52)(44,53)$$

Is the permutation correct?: true

The permutation is $\tau$: $\texttt{false}$.

The permutation is $\sigma$: $\texttt{false}$.

In [493]:
ShiftKeysToZero := function( data_rec_info )
    local result, r, names, min_key, new_r, name, new_key;
    result := [];
    for r in data_rec_info do
        names := RecNames(r);
        # Manejo de seguridad por si hay algún registro vacío
        if IsEmpty(names) then
            Add(result, rec());
            continue;
        fi;
        # 1. Capturamos el mínimo de las claves del registro actual
        min_key := Minimum(List(names, Int));
        # 2. Creamos un nuevo registro vacío para guardar el desplazamiento
        new_r := rec();
        # 3. Restamos el mínimo a cada clave y copiamos el valor
        for name in names do
            new_key := String(Int(name) - min_key);
            new_r.(new_key) := r.(name);
        od;        
        Add(result, new_r);
    od;
    return result;
end;

function( data_rec_info ) ... end

In [495]:
data_rec_info_to_zero := ShiftKeysToZero( data_rec_info );

[ rec( 0 := [ [ 1, 10 ] ] ),   rec( 0 := [ [ 1, 6 ] ], 1 := [ [ 1, 37 ] ], 2 := [ [ 1, 44 ] ],       3 := [ [ 1, 11 ] ] ),   rec( 0 := [ [ 1, 8 ] ], 1 := [ [ 1, 47 ] ], 2 := [ [ 1, 52 ], [ 1, 54 ] ],       3 := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       4 := [ [ 1, 36 ], [ 1, 38 ] ], 5 := [ [ 1, 43 ] ], 6 := [ [ 1, 12 ] ] ),  rec( 0 := [ [ 1, 4 ] ], 1 := [ [ 1, 33 ] ], 2 := [ [ 1, 40 ], [ 1, 44 ] ],       3 := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       4 := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       5 := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       6 := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       7 := [ [ 1, 35 ], [ 1, 37 ] ], 8 := [ [ 1, 42 ] ], 9 := [ [ 1, 7 ] ] ),   rec( 0 := [ [ 1, 12 ] ], 1 := [ [ 1, 49 ] ], 2 := [ [ 1, 54 ], [ 1, 56 ] ],       3 := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       4 := [ [ 1, 34 ], [ 1, 36 ] ], 5 := [ [ 1, 41 ] ], 6 := [ [ 1, 8 ] ] ),   rec( 0 := [ [ 1, 2 ] ], 1 := [ [ 1, 35 ] ], 2 := [ [ 1, 40 ] ],       3 := [ [ 1, 9 ] ] ),   rec( 0 := [ [ 1, 7 ] ], 1 := [ [ 1, 48 ] ], 2 := [ [ 1, 53 ], [ 1, 55 ] ],       3 := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       4 := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       5 := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       6 := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       7 := [ [ 1, 46 ], [ 1, 50 ] ], 8 := [ [ 1, 51 ] ], 9 := [ [ 1, 4 ] ] ),   rec( 0 := [ [ 1, 3 ] ], 1 := [ [ 1, 34 ] ], 2 := [ [ 1, 39 ], [ 1, 41 ] ],       3 := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       4 := [ [ 1, 45 ], [ 1, 49 ] ], 5 := [ [ 1, 56 ] ], 6 := [ [ 1, 5 ] ] ),   rec( 0 := [ [ 1, 11 ] ], 1 := [ [ 1, 50 ] ], 2 := [ [ 1, 55 ] ],       3 := [ [ 1, 6 ] ] ), rec( 0 := [ [ 1, 1 ] ] ),   rec( 0 := [ [ 1, 9 ] ], 1 := [ [ 1, 46 ] ], 2 := [ [ 1, 53 ] ],       3 := [ [ 1, 2 ] ] ),   rec( 0 := [ [ 1, 5 ] ], 1 := [ [ 1, 38 ] ], 2 := [ [ 1, 39 ], [ 1, 43 ] ],       3 := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       4 := [ [ 1, 45 ], [ 1, 47 ] ], 5 := [ [ 1, 52 ] ], 6 := [ [ 1, 3 ] ] ),   rec( 0 := [ [ 1, 16 ] ], 1 := [ [ 1, 47 ], [ 1, 49 ] ],       2 := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       3 := [ [ 2, 13 ], [ 1, 21 ], [ 1, 23 ] ],       4 := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ], 5 := [ [ 1, 41 ], [ 1, 43 ] ],      6 := [ [ 1, 16 ] ] ),   rec( 0 := [ [ 1, 14 ] ], 1 := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       2 := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       3 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ], [ 1, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 4 := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       5 := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       6 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ], [ 1, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 7 := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       8 := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], 9 := [ [ 1, 15 ] ] ),   rec( 0 := [ [ 1, 15 ] ], 1 := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       2 := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       3 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ], [ 1, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 4 := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       5 := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       6 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ], [ 1, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 7 := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       8 := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], 9 := [ [ 1, 14 ] ] ),   rec( 0 := [ [ 1, 13 ] ], 1 := [ [ 1, 34 ], [ 1, 38 ] ],       2 := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       3 := [ [ 2, 16 ], [ 1, 30 ], [ 1, 32 ] ],       4 := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ], 5 := [ [ 1, 52 ], [ 1, 56 ] ],      6 := [ [ 1, 13 ] ] ),   rec( 0 := [ [ 1, 26 ] ], 1 := [ [ 1, 47 ], [ 1, 49 ] ],       2 := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       3 := [ [ 2, 17 ], [ 1, 21 ], [ 1, 23 ] ],       4 := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ], 5 := [ [ 1, 41 ], [ 1, 43 ] ],      6 := [ [ 1, 26 ] ] ),   rec( 0 := [ [ 1, 18 ] ], 1 := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       2 := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       3 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ], [ 1, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 4 := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       5 := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       6 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ], [ 1, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 7 := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       8 := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], 9 := [ [ 1, 25 ] ] ),   rec( 0 := [ [ 1, 28 ] ], 1 := [ [ 1, 47 ], [ 1, 49 ] ],       2 := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       3 := [ [ 2, 19 ], [ 1, 21 ], [ 1, 23 ] ],       4 := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ], 5 := [ [ 1, 41 ], [ 1, 43 ] ],      6 := [ [ 1, 28 ] ] ),   rec( 0 := [ [ 1, 20 ] ], 1 := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       2 := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       3 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 4, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 4 := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       5 := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       6 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 4, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 7 := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       8 := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], 9 := [ [ 1, 27 ] ] ),   rec( 0 := [ [ 1, 32 ] ], 1 := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       2 := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       3 := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       4 := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       5 := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], 6 := [ [ 1, 30 ] ] ),   rec( 0 := [ [ 1, 24 ] ], 1 := [ [ 1, 35 ], [ 1, 37 ] ],       2 := [ [ 1, 40 ], [ 1, 44 ] ], 3 := [ [ 1, 29 ] ] ),   rec( 0 := [ [ 1, 30 ] ], 1 := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       2 := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       3 := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       4 := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       5 := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], 6 := [ [ 1, 32 ] ] ),   rec( 0 := [ [ 1, 22 ] ], 1 := [ [ 1, 35 ], [ 1, 37 ] ],       2 := [ [ 1, 40 ], [ 1, 44 ] ], 3 := [ [ 1, 31 ] ] ),   rec( 0 := [ [ 1, 25 ] ], 1 := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       2 := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       3 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ], [ 1, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 4 := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       5 := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       6 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ], [ 1, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 7 := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       8 := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], 9 := [ [ 1, 18 ] ] ),   rec( 0 := [ [ 1, 17 ] ], 1 := [ [ 1, 34 ], [ 1, 38 ] ],       2 := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       3 := [ [ 2, 26 ], [ 1, 30 ], [ 1, 32 ] ],       4 := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ], 5 := [ [ 1, 52 ], [ 1, 56 ] ],      6 := [ [ 1, 17 ] ] ),   rec( 0 := [ [ 1, 27 ] ], 1 := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       2 := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       3 := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 4, 20 ],           [ 2, 22 ], [ 2, 24 ] ], 4 := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       5 := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       6 := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 4, 27 ],           [ 2, 29 ], [ 2, 31 ] ], 7 := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       8 := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], 9 := [ [ 1, 20 ] ] ),   rec( 0 := [ [ 1, 19 ] ], 1 := [ [ 1, 34 ], [ 1, 38 ] ],       2 := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       3 := [ [ 2, 28 ], [ 1, 30 ], [ 1, 32 ] ],       4 := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ], 5 := [ [ 1, 52 ], [ 1, 56 ] ],      6 := [ [ 1, 19 ] ] ),   rec( 0 := [ [ 1, 31 ] ], 1 := [ [ 1, 46 ], [ 1, 50 ] ],       2 := [ [ 1, 53 ], [ 1, 55 ] ], 3 := [ [ 1, 22 ] ] ),   rec( 0 := [ [ 1, 23 ] ], 1 := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       2 := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       3 := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       4 := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       5 := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], 6 := [ [ 1, 21 ] ] ),   rec( 0 := [ [ 1, 29 ] ], 1 := [ [ 1, 46 ], [ 1, 50 ] ],       2 := [ [ 1, 53 ], [ 1, 55 ] ], 3 := [ [ 1, 24 ] ] ),   rec( 0 := [ [ 1, 21 ] ], 1 := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       2 := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       3 := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       4 := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       5 := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], 6 := [ [ 1, 23 ] ] ),   rec( 0 := [ [ 1, 51 ] ], 1 := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],      2 := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       3 := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       4 := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ], 5 := [ [ 1, 48 ] ] )    ,   rec( 0 := [ [ 1, 41 ] ],       1 := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ] ]        , 2 := [ [ 3, 45 ], [ 2, 47 ], [ 3, 49 ] ],       3 := [ [ 4, 52 ], [ 4, 54 ], [ 3, 56 ] ],       4 := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ], [ 3, 19 ],           [ 3, 21 ], [ 3, 23 ] ], 5 := [ [ 3, 34 ], [ 4, 36 ], [ 4, 38 ] ],       6 := [ [ 3, 39 ], [ 3, 41 ], [ 2, 43 ] ],       7 := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ]          ], 8 := [ [ 1, 49 ] ] ),   rec( 0 := [ [ 1, 55 ] ],       1 := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ], [ 1, 24 ] ]        , 2 := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       3 := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       4 := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ], [ 1, 31 ]          ], 5 := [ [ 1, 50 ] ] ),   rec( 0 := [ [ 1, 39 ] ], 1 := [ [ 1, 30 ], [ 1, 32 ] ], 2 := [ [ 1, 45 ] ] )    ,   rec( 0 := [ [ 1, 53 ] ],       1 := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ], [ 1, 24 ] ]        , 2 := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       3 := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       4 := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ], [ 1, 31 ] ]        , 5 := [ [ 1, 46 ] ] ),   rec( 0 := [ [ 1, 43 ] ],       1 := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ]          ], 2 := [ [ 3, 45 ], [ 3, 47 ], [ 2, 49 ] ],       3 := [ [ 3, 52 ], [ 4, 54 ], [ 4, 56 ] ],       4 := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ], [ 3, 19 ],           [ 3, 21 ], [ 3, 23 ] ], 5 := [ [ 4, 34 ], [ 4, 36 ], [ 3, 38 ] ],       6 := [ [ 3, 39 ], [ 2, 41 ], [ 3, 43 ] ],       7 := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ] ]        , 8 := [ [ 1, 47 ] ] ),   rec( 0 := [ [ 1, 36 ] ], 1 := [ [ 1, 41 ], [ 1, 43 ] ],       2 := [ [ 1, 8 ], [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       3 := [ [ 1, 47 ], [ 1, 49 ] ], 4 := [ [ 1, 54 ] ] ),   rec( 0 := [ [ 1, 50 ] ], 1 := [ [ 1, 51 ], [ 2, 53 ], [ 1, 55 ] ],       2 := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ],           [ 2, 24 ] ], 3 := [ [ 4, 33 ], [ 3, 35 ], [ 4, 37 ] ],       4 := [ [ 3, 40 ], [ 4, 42 ], [ 4, 44 ] ],       5 := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ],           [ 2, 31 ] ], 6 := [ [ 2, 46 ], [ 1, 48 ], [ 1, 50 ] ],       7 := [ [ 1, 55 ] ] ),   rec( 0 := [ [ 1, 34 ] ], 1 := [ [ 1, 39 ], [ 2, 43 ] ],       2 := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ]          ], 3 := [ [ 1, 45 ], [ 2, 47 ] ], 4 := [ [ 1, 56 ] ] ),   rec( 0 := [ [ 1, 48 ] ], 1 := [ [ 2, 51 ], [ 1, 53 ], [ 1, 55 ] ],       2 := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       3 := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       4 := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       5 := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       6 := [ [ 1, 46 ], [ 2, 48 ], [ 1, 50 ] ], 7 := [ [ 1, 51 ] ] ),   rec( 0 := [ [ 1, 38 ] ], 1 := [ [ 1, 39 ], [ 2, 41 ] ],       2 := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ], [ 1, 32 ]          ], 3 := [ [ 1, 45 ], [ 2, 49 ] ], 4 := [ [ 1, 52 ] ] ),   rec( 0 := [ [ 1, 46 ] ], 1 := [ [ 1, 51 ], [ 1, 53 ], [ 2, 55 ] ],       2 := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ],           [ 2, 24 ] ], 3 := [ [ 4, 33 ], [ 4, 35 ], [ 3, 37 ] ],       4 := [ [ 4, 40 ], [ 4, 42 ], [ 3, 44 ] ],       5 := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ],           [ 2, 31 ] ], 6 := [ [ 1, 46 ], [ 1, 48 ], [ 2, 50 ] ],       7 := [ [ 1, 53 ] ] ),   rec( 0 := [ [ 1, 54 ] ], 1 := [ [ 1, 21 ], [ 1, 23 ] ], 2 := [ [ 1, 36 ] ] )    ,   rec( 0 := [ [ 1, 44 ] ],       1 := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ], [ 1, 31 ]          ], 2 := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       3 := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       4 := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ], [ 1, 24 ] ]        , 5 := [ [ 1, 37 ] ] ),   rec( 0 := [ [ 1, 52 ] ],       1 := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 2 := [ [ 2, 34 ], [ 3, 36 ], [ 3, 38 ] ],       3 := [ [ 4, 39 ], [ 4, 41 ], [ 3, 43 ] ],       4 := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ], [ 3, 28 ],           [ 3, 30 ], [ 3, 32 ] ], 5 := [ [ 4, 45 ], [ 3, 47 ], [ 4, 49 ] ],       6 := [ [ 3, 52 ], [ 3, 54 ], [ 2, 56 ] ],       7 := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 8 := [ [ 1, 38 ] ] ),   rec( 0 := [ [ 1, 42 ] ], 1 := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],      2 := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       3 := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       4 := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ], 5 := [ [ 1, 33 ] ] )    ,   rec( 0 := [ [ 1, 56 ] ],       1 := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 2 := [ [ 3, 34 ], [ 3, 36 ], [ 2, 38 ] ],       3 := [ [ 4, 39 ], [ 3, 41 ], [ 4, 43 ] ],       4 := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ], [ 3, 28 ],           [ 3, 30 ], [ 3, 32 ] ], 5 := [ [ 4, 45 ], [ 4, 47 ], [ 3, 49 ] ],       6 := [ [ 2, 52 ], [ 3, 54 ], [ 3, 56 ] ],       7 := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 8 := [ [ 1, 34 ] ] ),   rec( 0 := [ [ 1, 40 ] ],       1 := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ], [ 1, 31 ] ]        , 2 := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       3 := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       4 := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ], [ 1, 24 ] ]        , 5 := [ [ 1, 35 ] ] ),   rec( 0 := [ [ 1, 33 ] ], 1 := [ [ 1, 40 ], [ 2, 42 ], [ 1, 44 ] ],       2 := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       3 := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       4 := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       5 := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       6 := [ [ 2, 33 ], [ 1, 35 ], [ 1, 37 ] ], 7 := [ [ 1, 42 ] ] ),   rec( 0 := [ [ 1, 47 ] ], 1 := [ [ 1, 54 ], [ 2, 56 ] ],       2 := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 3 := [ [ 2, 34 ], [ 1, 36 ] ], 4 := [ [ 1, 43 ] ] ),   rec( 0 := [ [ 1, 37 ] ], 1 := [ [ 2, 40 ], [ 1, 42 ], [ 1, 44 ] ],       2 := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ],           [ 2, 31 ] ], 3 := [ [ 3, 46 ], [ 4, 48 ], [ 4, 50 ] ],       4 := [ [ 4, 51 ], [ 3, 53 ], [ 4, 55 ] ],       5 := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ],           [ 2, 24 ] ], 6 := [ [ 1, 33 ], [ 2, 35 ], [ 1, 37 ] ],       7 := [ [ 1, 44 ] ] ),   rec( 0 := [ [ 1, 45 ] ], 1 := [ [ 1, 52 ], [ 1, 56 ] ],       2 := [ [ 1, 3 ], [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       3 := [ [ 1, 34 ], [ 1, 38 ] ], 4 := [ [ 1, 39 ] ] ),   rec( 0 := [ [ 1, 35 ] ], 1 := [ [ 1, 40 ], [ 1, 42 ], [ 2, 44 ] ],       2 := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ],           [ 2, 31 ] ], 3 := [ [ 4, 46 ], [ 4, 48 ], [ 3, 50 ] ],       4 := [ [ 4, 51 ], [ 4, 53 ], [ 3, 55 ] ],       5 := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ],           [ 2, 24 ] ], 6 := [ [ 1, 33 ], [ 1, 35 ], [ 2, 37 ] ],       7 := [ [ 1, 40 ] ] ),   rec( 0 := [ [ 1, 49 ] ], 1 := [ [ 2, 52 ], [ 1, 54 ] ],       2 := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ], [ 1, 23 ] ]        , 3 := [ [ 1, 36 ], [ 2, 38 ] ], 4 := [ [ 1, 41 ] ] ) ]

In [1503]:
QGNAG_LoadCharactersToLaTeXByIndex("characters_T4_to_zero_by_index.tex", data_rec_info_to_zero);

In [496]:
QGNAG_LoadCharactersToLaTeXT( "characters_T4_to_zero.tex", data_rec_info_to_zero, SimpleNames );

In [497]:
InvertKeySigns := function( record_list )
    local new_list, r, new_r, k, num_k;
    new_list := [];    
    for r in record_list do
        new_r := rec();
        for k in RecNames(r) do
            num_k := Int(k); # GAP returns keys as strings (e.g., "1", "2")
            if num_k <> fail then
                # Change the sign and use String() so GAP accepts it as a key
                new_r.(String(-num_k)) := r.(k);
            else
                # Fallback in case there is a non-numeric key
                new_r.(k) := r.(k);
            fi;
        od;
        Add(new_list, new_r);
    od;
    return new_list;
end;

function( record_list ) ... end

In [498]:
# Apply it to your variable
data_rec_info_to_zero_negative := InvertKeySigns( data_rec_info_to_zero );

[ rec( 0 := [ [ 1, 10 ] ] ),   rec( ("-1") := [ [ 1, 37 ] ], ("-2") := [ [ 1, 44 ] ],       ("-3") := [ [ 1, 11 ] ], 0 := [ [ 1, 6 ] ] ),   rec( ("-1") := [ [ 1, 47 ] ], ("-2") := [ [ 1, 52 ], [ 1, 54 ] ],       ("-3") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-4") := [ [ 1, 36 ], [ 1, 38 ] ], ("-5") := [ [ 1, 43 ] ],       ("-6") := [ [ 1, 12 ] ], 0 := [ [ 1, 8 ] ] ),   rec( ("-1") := [ [ 1, 33 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],       ("-3") := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-4") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-5") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-7") := [ [ 1, 35 ], [ 1, 37 ] ], ("-8") := [ [ 1, 42 ] ],       ("-9") := [ [ 1, 7 ] ], 0 := [ [ 1, 4 ] ] ),   rec( ("-1") := [ [ 1, 49 ] ], ("-2") := [ [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ] ], ("-5") := [ [ 1, 41 ] ],       ("-6") := [ [ 1, 8 ] ], 0 := [ [ 1, 12 ] ] ),   rec( ("-1") := [ [ 1, 35 ] ], ("-2") := [ [ 1, 40 ] ],       ("-3") := [ [ 1, 9 ] ], 0 := [ [ 1, 2 ] ] ),   rec( ("-1") := [ [ 1, 48 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-4") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-5") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-6") := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-7") := [ [ 1, 46 ], [ 1, 50 ] ], ("-8") := [ [ 1, 51 ] ],       ("-9") := [ [ 1, 4 ] ], 0 := [ [ 1, 7 ] ] ),   rec( ("-1") := [ [ 1, 34 ] ], ("-2") := [ [ 1, 39 ], [ 1, 41 ] ],       ("-3") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 49 ] ], ("-5") := [ [ 1, 56 ] ],       ("-6") := [ [ 1, 5 ] ], 0 := [ [ 1, 3 ] ] ),   rec( ("-1") := [ [ 1, 50 ] ], ("-2") := [ [ 1, 55 ] ],       ("-3") := [ [ 1, 6 ] ], 0 := [ [ 1, 11 ] ] ), rec( 0 := [ [ 1, 1 ] ] ),   rec( ("-1") := [ [ 1, 46 ] ], ("-2") := [ [ 1, 53 ] ],       ("-3") := [ [ 1, 2 ] ], 0 := [ [ 1, 9 ] ] ),   rec( ("-1") := [ [ 1, 38 ] ], ("-2") := [ [ 1, 39 ], [ 1, 43 ] ],       ("-3") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ] ], ("-5") := [ [ 1, 52 ] ],       ("-6") := [ [ 1, 3 ] ], 0 := [ [ 1, 5 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 16 ] ],       0 := [ [ 1, 16 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 15 ] ],       0 := [ [ 1, 14 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 14 ] ],       0 := [ [ 1, 15 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 13 ] ],       0 := [ [ 1, 13 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 17 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 26 ] ],       0 := [ [ 1, 26 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 25 ] ],       0 := [ [ 1, 18 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 19 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 28 ] ],       0 := [ [ 1, 28 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ],           [ 4, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ],           [ 4, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 27 ] ],       0 := [ [ 1, 20 ] ] ),   rec( ("-1") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       ("-4") := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       ("-5") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 30 ] ],       0 := [ [ 1, 32 ] ] ),   rec( ("-1") := [ [ 1, 35 ], [ 1, 37 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],      ("-3") := [ [ 1, 29 ] ], 0 := [ [ 1, 24 ] ] ),   rec( ("-1") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       ("-4") := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       ("-5") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 32 ] ],       0 := [ [ 1, 30 ] ] ),   rec( ("-1") := [ [ 1, 35 ], [ 1, 37 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],      ("-3") := [ [ 1, 31 ] ], 0 := [ [ 1, 22 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 18 ] ],       0 := [ [ 1, 25 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 26 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 17 ] ],       0 := [ [ 1, 17 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ],           [ 4, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ],           [ 4, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 20 ] ],       0 := [ [ 1, 27 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 28 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 19 ] ],       0 := [ [ 1, 19 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 50 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],      ("-3") := [ [ 1, 22 ] ], 0 := [ [ 1, 31 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-2") := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       ("-4") := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], ("-6") := [ [ 1, 21 ] ],       0 := [ [ 1, 23 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 50 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],      ("-3") := [ [ 1, 24 ] ], 0 := [ [ 1, 29 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-2") := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       ("-4") := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], ("-6") := [ [ 1, 23 ] ],       0 := [ [ 1, 21 ] ] ),   rec( ("-1") := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-2") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-3") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-4") := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-5") := [ [ 1, 48 ] ], 0 := [ [ 1, 51 ] ] ),   rec( ("-1") := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-2") := [ [ 3, 45 ], [ 2, 47 ], [ 3, 49 ] ],       ("-3") := [ [ 4, 52 ], [ 4, 54 ], [ 3, 56 ] ],       ("-4") := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ],           [ 3, 19 ], [ 3, 21 ], [ 3, 23 ] ],       ("-5") := [ [ 3, 34 ], [ 4, 36 ], [ 4, 38 ] ],       ("-6") := [ [ 3, 39 ], [ 3, 41 ], [ 2, 43 ] ],       ("-7") := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-8") := [ [ 1, 49 ] ], 0 := [ [ 1, 41 ] ] ),   rec( ("-1") := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-2") := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-3") := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       ("-4") := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-5") := [ [ 1, 50 ] ], 0 := [ [ 1, 55 ] ] ),   rec( ("-1") := [ [ 1, 30 ], [ 1, 32 ] ], ("-2") := [ [ 1, 45 ] ],       0 := [ [ 1, 39 ] ] ),   rec( ("-1") := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-2") := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-3") := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       ("-4") := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-5") := [ [ 1, 46 ] ], 0 := [ [ 1, 53 ] ] ),   rec( ("-1") := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-2") := [ [ 3, 45 ], [ 3, 47 ], [ 2, 49 ] ],       ("-3") := [ [ 3, 52 ], [ 4, 54 ], [ 4, 56 ] ],       ("-4") := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ],           [ 3, 19 ], [ 3, 21 ], [ 3, 23 ] ],       ("-5") := [ [ 4, 34 ], [ 4, 36 ], [ 3, 38 ] ],       ("-6") := [ [ 3, 39 ], [ 2, 41 ], [ 3, 43 ] ],       ("-7") := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-8") := [ [ 1, 47 ] ], 0 := [ [ 1, 43 ] ] ),   rec( ("-1") := [ [ 1, 41 ], [ 1, 43 ] ],       ("-2") := [ [ 1, 8 ], [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-3") := [ [ 1, 47 ], [ 1, 49 ] ], ("-4") := [ [ 1, 54 ] ],       0 := [ [ 1, 36 ] ] ),   rec( ("-1") := [ [ 1, 51 ], [ 2, 53 ], [ 1, 55 ] ],       ("-2") := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 4, 33 ], [ 3, 35 ], [ 4, 37 ] ],       ("-4") := [ [ 3, 40 ], [ 4, 42 ], [ 4, 44 ] ],       ("-5") := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 2, 46 ], [ 1, 48 ], [ 1, 50 ] ], ("-7") := [ [ 1, 55 ] ],       0 := [ [ 1, 50 ] ] ),   rec( ("-1") := [ [ 1, 39 ], [ 2, 43 ] ],       ("-2") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-3") := [ [ 1, 45 ], [ 2, 47 ] ],       ("-4") := [ [ 1, 56 ] ], 0 := [ [ 1, 34 ] ] ),   rec( ("-1") := [ [ 2, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-2") := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-4") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-5") := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 1, 46 ], [ 2, 48 ], [ 1, 50 ] ], ("-7") := [ [ 1, 51 ] ],       0 := [ [ 1, 48 ] ] ),   rec( ("-1") := [ [ 1, 39 ], [ 2, 41 ] ],       ("-2") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-3") := [ [ 1, 45 ], [ 2, 49 ] ],       ("-4") := [ [ 1, 52 ] ], 0 := [ [ 1, 38 ] ] ),   rec( ("-1") := [ [ 1, 51 ], [ 1, 53 ], [ 2, 55 ] ],       ("-2") := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 4, 33 ], [ 4, 35 ], [ 3, 37 ] ],       ("-4") := [ [ 4, 40 ], [ 4, 42 ], [ 3, 44 ] ],       ("-5") := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 1, 46 ], [ 1, 48 ], [ 2, 50 ] ], ("-7") := [ [ 1, 53 ] ],       0 := [ [ 1, 46 ] ] ),   rec( ("-1") := [ [ 1, 21 ], [ 1, 23 ] ], ("-2") := [ [ 1, 36 ] ],       0 := [ [ 1, 54 ] ] ),   rec( ("-1") := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-2") := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       ("-3") := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-4") := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-5") := [ [ 1, 37 ] ], 0 := [ [ 1, 44 ] ] ),   rec( ("-1") := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-2") := [ [ 2, 34 ], [ 3, 36 ], [ 3, 38 ] ],       ("-3") := [ [ 4, 39 ], [ 4, 41 ], [ 3, 43 ] ],       ("-4") := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ],           [ 3, 28 ], [ 3, 30 ], [ 3, 32 ] ],       ("-5") := [ [ 4, 45 ], [ 3, 47 ], [ 4, 49 ] ],       ("-6") := [ [ 3, 52 ], [ 3, 54 ], [ 2, 56 ] ],       ("-7") := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-8") := [ [ 1, 38 ] ], 0 := [ [ 1, 52 ] ] ),   rec( ("-1") := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-2") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-3") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-4") := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-5") := [ [ 1, 33 ] ], 0 := [ [ 1, 42 ] ] ),   rec( ("-1") := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-2") := [ [ 3, 34 ], [ 3, 36 ], [ 2, 38 ] ],       ("-3") := [ [ 4, 39 ], [ 3, 41 ], [ 4, 43 ] ],       ("-4") := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ],           [ 3, 28 ], [ 3, 30 ], [ 3, 32 ] ],       ("-5") := [ [ 4, 45 ], [ 4, 47 ], [ 3, 49 ] ],       ("-6") := [ [ 2, 52 ], [ 3, 54 ], [ 3, 56 ] ],       ("-7") := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-8") := [ [ 1, 34 ] ], 0 := [ [ 1, 56 ] ] ),   rec( ("-1") := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-2") := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       ("-3") := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-4") := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-5") := [ [ 1, 35 ] ], 0 := [ [ 1, 40 ] ] ),   rec( ("-1") := [ [ 1, 40 ], [ 2, 42 ], [ 1, 44 ] ],       ("-2") := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-4") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-5") := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 2, 33 ], [ 1, 35 ], [ 1, 37 ] ], ("-7") := [ [ 1, 42 ] ],       0 := [ [ 1, 33 ] ] ),   rec( ("-1") := [ [ 1, 54 ], [ 2, 56 ] ],       ("-2") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-3") := [ [ 2, 34 ], [ 1, 36 ] ],       ("-4") := [ [ 1, 43 ] ], 0 := [ [ 1, 47 ] ] ),   rec( ("-1") := [ [ 2, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-2") := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 3, 46 ], [ 4, 48 ], [ 4, 50 ] ],       ("-4") := [ [ 4, 51 ], [ 3, 53 ], [ 4, 55 ] ],       ("-5") := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 1, 33 ], [ 2, 35 ], [ 1, 37 ] ], ("-7") := [ [ 1, 44 ] ],       0 := [ [ 1, 37 ] ] ),   rec( ("-1") := [ [ 1, 52 ], [ 1, 56 ] ],       ("-2") := [ [ 1, 3 ], [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-3") := [ [ 1, 34 ], [ 1, 38 ] ], ("-4") := [ [ 1, 39 ] ],       0 := [ [ 1, 45 ] ] ),   rec( ("-1") := [ [ 1, 40 ], [ 1, 42 ], [ 2, 44 ] ],       ("-2") := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 4, 46 ], [ 4, 48 ], [ 3, 50 ] ],       ("-4") := [ [ 4, 51 ], [ 4, 53 ], [ 3, 55 ] ],       ("-5") := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 1, 33 ], [ 1, 35 ], [ 2, 37 ] ], ("-7") := [ [ 1, 40 ] ],       0 := [ [ 1, 35 ] ] ),   rec( ("-1") := [ [ 2, 52 ], [ 1, 54 ] ],       ("-2") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-3") := [ [ 1, 36 ], [ 2, 38 ] ],       ("-4") := [ [ 1, 41 ] ], 0 := [ [ 1, 49 ] ] ) ]

In [1504]:
QGNAG_LoadCharactersToLaTeXByIndex("characters_T4_to_zero_negative_by_index.tex", data_rec_info_to_zero_negative);

In [499]:
QGNAG_LoadCharactersToLaTeXT( "characters_T4_to_zero_negative.tex", data_rec_info_to_zero_negative, SimpleNames );

In [500]:
tau := PermList(List(data_rec_info_to_zero_negative, r-> r.(0)[1][2]));

(1,10)(2,6)(3,8)(5,12)(9,11)(13,16)(17,26)(19,28)(21,32)(22,24)(23,30)(29,31)(33,51)(34,41)(35,55)(36,39)(37,53)(38,43)(40,50)(42,48)(44,46)(45,54)(47,52)(49,56)

In [501]:
data_rec_info_to_zero_negative_permuted := Permuted( data_rec_info_to_zero_negative, tau );

[ rec( 0 := [ [ 1, 1 ] ] ),   rec( ("-1") := [ [ 1, 35 ] ], ("-2") := [ [ 1, 40 ] ],       ("-3") := [ [ 1, 9 ] ], 0 := [ [ 1, 2 ] ] ),   rec( ("-1") := [ [ 1, 34 ] ], ("-2") := [ [ 1, 39 ], [ 1, 41 ] ],       ("-3") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 49 ] ], ("-5") := [ [ 1, 56 ] ],       ("-6") := [ [ 1, 5 ] ], 0 := [ [ 1, 3 ] ] ),   rec( ("-1") := [ [ 1, 33 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],       ("-3") := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-4") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-5") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-7") := [ [ 1, 35 ], [ 1, 37 ] ], ("-8") := [ [ 1, 42 ] ],       ("-9") := [ [ 1, 7 ] ], 0 := [ [ 1, 4 ] ] ),   rec( ("-1") := [ [ 1, 38 ] ], ("-2") := [ [ 1, 39 ], [ 1, 43 ] ],       ("-3") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ] ], ("-5") := [ [ 1, 52 ] ],       ("-6") := [ [ 1, 3 ] ], 0 := [ [ 1, 5 ] ] ),   rec( ("-1") := [ [ 1, 37 ] ], ("-2") := [ [ 1, 44 ] ],       ("-3") := [ [ 1, 11 ] ], 0 := [ [ 1, 6 ] ] ),   rec( ("-1") := [ [ 1, 48 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-4") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-5") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-6") := [ [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-7") := [ [ 1, 46 ], [ 1, 50 ] ], ("-8") := [ [ 1, 51 ] ],       ("-9") := [ [ 1, 4 ] ], 0 := [ [ 1, 7 ] ] ),   rec( ("-1") := [ [ 1, 47 ] ], ("-2") := [ [ 1, 52 ], [ 1, 54 ] ],       ("-3") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-4") := [ [ 1, 36 ], [ 1, 38 ] ], ("-5") := [ [ 1, 43 ] ],       ("-6") := [ [ 1, 12 ] ], 0 := [ [ 1, 8 ] ] ),   rec( ("-1") := [ [ 1, 46 ] ], ("-2") := [ [ 1, 53 ] ],       ("-3") := [ [ 1, 2 ] ], 0 := [ [ 1, 9 ] ] ), rec( 0 := [ [ 1, 10 ] ] ),   rec( ("-1") := [ [ 1, 50 ] ], ("-2") := [ [ 1, 55 ] ],       ("-3") := [ [ 1, 6 ] ], 0 := [ [ 1, 11 ] ] ),   rec( ("-1") := [ [ 1, 49 ] ], ("-2") := [ [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ] ], ("-5") := [ [ 1, 41 ] ],       ("-6") := [ [ 1, 8 ] ], 0 := [ [ 1, 12 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 13 ] ],       0 := [ [ 1, 13 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 15 ] ],       0 := [ [ 1, 14 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 4, 14 ], [ 1, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 4, 15 ], [ 1, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 14 ] ],       0 := [ [ 1, 15 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 16 ] ],       0 := [ [ 1, 16 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 26 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 17 ] ],       0 := [ [ 1, 17 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 25 ] ],       0 := [ [ 1, 18 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 38 ] ],       ("-2") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ],       ("-3") := [ [ 2, 28 ], [ 1, 30 ], [ 1, 32 ] ],       ("-4") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 56 ] ], ("-6") := [ [ 1, 19 ] ],       0 := [ [ 1, 19 ] ] ),   rec( ("-1") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-2") := [ [ 2, 40 ], [ 2, 42 ], [ 2, 44 ] ],       ("-3") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ],           [ 4, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-4") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-5") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-6") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ],           [ 4, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-7") := [ [ 2, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-8") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ], ("-9") := [ [ 1, 27 ] ],       0 := [ [ 1, 20 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-2") := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       ("-4") := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], ("-6") := [ [ 1, 23 ] ],       0 := [ [ 1, 21 ] ] ),   rec( ("-1") := [ [ 1, 35 ], [ 1, 37 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],      ("-3") := [ [ 1, 31 ] ], 0 := [ [ 1, 22 ] ] ),   rec( ("-1") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-2") := [ [ 2, 39 ], [ 2, 41 ], [ 2, 43 ] ],       ("-3") := [ [ 2, 16 ], [ 2, 26 ], [ 2, 28 ], [ 2, 30 ], [ 2, 32 ] ],       ("-4") := [ [ 2, 45 ], [ 2, 47 ], [ 2, 49 ] ],       ("-5") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ], ("-6") := [ [ 1, 21 ] ],       0 := [ [ 1, 23 ] ] ),   rec( ("-1") := [ [ 1, 35 ], [ 1, 37 ] ], ("-2") := [ [ 1, 40 ], [ 1, 44 ] ],      ("-3") := [ [ 1, 29 ] ], 0 := [ [ 1, 24 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 4, 18 ],           [ 1, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 4, 25 ],           [ 1, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 18 ] ],       0 := [ [ 1, 25 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 17 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 26 ] ],       0 := [ [ 1, 26 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-2") := [ [ 2, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-3") := [ [ 1, 2 ], [ 1, 4 ], [ 1, 6 ], [ 1, 14 ], [ 1, 18 ],           [ 4, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-4") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-5") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-6") := [ [ 1, 7 ], [ 1, 9 ], [ 1, 11 ], [ 1, 15 ], [ 1, 25 ],           [ 4, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-7") := [ [ 2, 46 ], [ 2, 48 ], [ 2, 50 ] ],       ("-8") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ], ("-9") := [ [ 1, 20 ] ],       0 := [ [ 1, 27 ] ] ),   rec( ("-1") := [ [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 1, 52 ], [ 1, 54 ], [ 1, 56 ] ],       ("-3") := [ [ 2, 19 ], [ 1, 21 ], [ 1, 23 ] ],       ("-4") := [ [ 1, 34 ], [ 1, 36 ], [ 1, 38 ] ],       ("-5") := [ [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 28 ] ],       0 := [ [ 1, 28 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 50 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],      ("-3") := [ [ 1, 24 ] ], 0 := [ [ 1, 29 ] ] ),   rec( ("-1") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       ("-4") := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       ("-5") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 32 ] ],       0 := [ [ 1, 30 ] ] ),   rec( ("-1") := [ [ 1, 46 ], [ 1, 50 ] ], ("-2") := [ [ 1, 53 ], [ 1, 55 ] ],      ("-3") := [ [ 1, 22 ] ], 0 := [ [ 1, 31 ] ] ),   rec( ("-1") := [ [ 1, 45 ], [ 1, 47 ], [ 1, 49 ] ],       ("-2") := [ [ 2, 52 ], [ 2, 54 ], [ 2, 56 ] ],       ("-3") := [ [ 2, 13 ], [ 2, 17 ], [ 2, 19 ], [ 2, 21 ], [ 2, 23 ] ],       ("-4") := [ [ 2, 34 ], [ 2, 36 ], [ 2, 38 ] ],       ("-5") := [ [ 1, 39 ], [ 1, 41 ], [ 1, 43 ] ], ("-6") := [ [ 1, 30 ] ],       0 := [ [ 1, 32 ] ] ),   rec( ("-1") := [ [ 1, 40 ], [ 2, 42 ], [ 1, 44 ] ],       ("-2") := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 3, 46 ], [ 3, 48 ], [ 3, 50 ] ],       ("-4") := [ [ 3, 51 ], [ 3, 53 ], [ 3, 55 ] ],       ("-5") := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 2, 33 ], [ 1, 35 ], [ 1, 37 ] ], ("-7") := [ [ 1, 42 ] ],       0 := [ [ 1, 33 ] ] ),   rec( ("-1") := [ [ 1, 39 ], [ 2, 43 ] ],       ("-2") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-3") := [ [ 1, 45 ], [ 2, 47 ] ],       ("-4") := [ [ 1, 56 ] ], 0 := [ [ 1, 34 ] ] ),   rec( ("-1") := [ [ 1, 40 ], [ 1, 42 ], [ 2, 44 ] ],       ("-2") := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 4, 46 ], [ 4, 48 ], [ 3, 50 ] ],       ("-4") := [ [ 4, 51 ], [ 4, 53 ], [ 3, 55 ] ],       ("-5") := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 1, 33 ], [ 1, 35 ], [ 2, 37 ] ], ("-7") := [ [ 1, 40 ] ],       0 := [ [ 1, 35 ] ] ),   rec( ("-1") := [ [ 1, 41 ], [ 1, 43 ] ],       ("-2") := [ [ 1, 8 ], [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ] ],       ("-3") := [ [ 1, 47 ], [ 1, 49 ] ], ("-4") := [ [ 1, 54 ] ],       0 := [ [ 1, 36 ] ] ),   rec( ("-1") := [ [ 2, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-2") := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-3") := [ [ 3, 46 ], [ 4, 48 ], [ 4, 50 ] ],       ("-4") := [ [ 4, 51 ], [ 3, 53 ], [ 4, 55 ] ],       ("-5") := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-6") := [ [ 1, 33 ], [ 2, 35 ], [ 1, 37 ] ], ("-7") := [ [ 1, 44 ] ],       0 := [ [ 1, 37 ] ] ),   rec( ("-1") := [ [ 1, 39 ], [ 2, 41 ] ],       ("-2") := [ [ 1, 10 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-3") := [ [ 1, 45 ], [ 2, 49 ] ],       ("-4") := [ [ 1, 52 ] ], 0 := [ [ 1, 38 ] ] ),   rec( ("-1") := [ [ 1, 30 ], [ 1, 32 ] ], ("-2") := [ [ 1, 45 ] ],       0 := [ [ 1, 39 ] ] ),   rec( ("-1") := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-2") := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       ("-3") := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-4") := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-5") := [ [ 1, 35 ] ], 0 := [ [ 1, 40 ] ] ),   rec( ("-1") := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-2") := [ [ 3, 45 ], [ 2, 47 ], [ 3, 49 ] ],       ("-3") := [ [ 4, 52 ], [ 4, 54 ], [ 3, 56 ] ],       ("-4") := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ],           [ 3, 19 ], [ 3, 21 ], [ 3, 23 ] ],       ("-5") := [ [ 3, 34 ], [ 4, 36 ], [ 4, 38 ] ],       ("-6") := [ [ 3, 39 ], [ 3, 41 ], [ 2, 43 ] ],       ("-7") := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-8") := [ [ 1, 49 ] ], 0 := [ [ 1, 41 ] ] ),   rec( ("-1") := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-2") := [ [ 1, 46 ], [ 1, 48 ], [ 1, 50 ] ],       ("-3") := [ [ 1, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-4") := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-5") := [ [ 1, 33 ] ], 0 := [ [ 1, 42 ] ] ),   rec( ("-1") := [ [ 1, 12 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-2") := [ [ 3, 45 ], [ 3, 47 ], [ 2, 49 ] ],       ("-3") := [ [ 3, 52 ], [ 4, 54 ], [ 4, 56 ] ],       ("-4") := [ [ 1, 1 ], [ 1, 3 ], [ 1, 5 ], [ 3, 13 ], [ 3, 17 ],           [ 3, 19 ], [ 3, 21 ], [ 3, 23 ] ],       ("-5") := [ [ 4, 34 ], [ 4, 36 ], [ 3, 38 ] ],       ("-6") := [ [ 3, 39 ], [ 2, 41 ], [ 3, 43 ] ],       ("-7") := [ [ 1, 8 ], [ 1, 16 ], [ 1, 26 ], [ 1, 28 ], [ 1, 30 ],           [ 1, 32 ] ], ("-8") := [ [ 1, 47 ] ], 0 := [ [ 1, 43 ] ] ),   rec( ("-1") := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-2") := [ [ 2, 46 ], [ 3, 48 ], [ 2, 50 ] ],       ("-3") := [ [ 3, 51 ], [ 2, 53 ], [ 2, 55 ] ],       ("-4") := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-5") := [ [ 1, 37 ] ], 0 := [ [ 1, 44 ] ] ),   rec( ("-1") := [ [ 1, 52 ], [ 1, 56 ] ],       ("-2") := [ [ 1, 3 ], [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ] ],       ("-3") := [ [ 1, 34 ], [ 1, 38 ] ], ("-4") := [ [ 1, 39 ] ],       0 := [ [ 1, 45 ] ] ),   rec( ("-1") := [ [ 1, 51 ], [ 1, 53 ], [ 2, 55 ] ],       ("-2") := [ [ 1, 2 ], [ 1, 4 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 4, 33 ], [ 4, 35 ], [ 3, 37 ] ],       ("-4") := [ [ 4, 40 ], [ 4, 42 ], [ 3, 44 ] ],       ("-5") := [ [ 1, 7 ], [ 1, 9 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 1, 46 ], [ 1, 48 ], [ 2, 50 ] ], ("-7") := [ [ 1, 53 ] ],       0 := [ [ 1, 46 ] ] ),   rec( ("-1") := [ [ 1, 54 ], [ 2, 56 ] ],       ("-2") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-3") := [ [ 2, 34 ], [ 1, 36 ] ],       ("-4") := [ [ 1, 43 ] ], 0 := [ [ 1, 47 ] ] ),   rec( ("-1") := [ [ 2, 51 ], [ 1, 53 ], [ 1, 55 ] ],       ("-2") := [ [ 2, 14 ], [ 2, 18 ], [ 2, 20 ], [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 3, 33 ], [ 3, 35 ], [ 3, 37 ] ],       ("-4") := [ [ 3, 40 ], [ 3, 42 ], [ 3, 44 ] ],       ("-5") := [ [ 2, 15 ], [ 2, 25 ], [ 2, 27 ], [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 1, 46 ], [ 2, 48 ], [ 1, 50 ] ], ("-7") := [ [ 1, 51 ] ],       0 := [ [ 1, 48 ] ] ),   rec( ("-1") := [ [ 2, 52 ], [ 1, 54 ] ],       ("-2") := [ [ 1, 1 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-3") := [ [ 1, 36 ], [ 2, 38 ] ],       ("-4") := [ [ 1, 41 ] ], 0 := [ [ 1, 49 ] ] ),   rec( ("-1") := [ [ 1, 51 ], [ 2, 53 ], [ 1, 55 ] ],       ("-2") := [ [ 1, 4 ], [ 1, 6 ], [ 2, 14 ], [ 2, 18 ], [ 2, 20 ],           [ 2, 22 ], [ 2, 24 ] ],       ("-3") := [ [ 4, 33 ], [ 3, 35 ], [ 4, 37 ] ],       ("-4") := [ [ 3, 40 ], [ 4, 42 ], [ 4, 44 ] ],       ("-5") := [ [ 1, 7 ], [ 1, 11 ], [ 2, 15 ], [ 2, 25 ], [ 2, 27 ],           [ 2, 29 ], [ 2, 31 ] ],       ("-6") := [ [ 2, 46 ], [ 1, 48 ], [ 1, 50 ] ], ("-7") := [ [ 1, 55 ] ],       0 := [ [ 1, 50 ] ] ),   rec( ("-1") := [ [ 1, 4 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ] ],       ("-2") := [ [ 1, 33 ], [ 1, 35 ], [ 1, 37 ] ],       ("-3") := [ [ 1, 40 ], [ 1, 42 ], [ 1, 44 ] ],       ("-4") := [ [ 1, 7 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ] ],       ("-5") := [ [ 1, 48 ] ], 0 := [ [ 1, 51 ] ] ),   rec( ("-1") := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-2") := [ [ 2, 34 ], [ 3, 36 ], [ 3, 38 ] ],       ("-3") := [ [ 4, 39 ], [ 4, 41 ], [ 3, 43 ] ],       ("-4") := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ],           [ 3, 28 ], [ 3, 30 ], [ 3, 32 ] ],       ("-5") := [ [ 4, 45 ], [ 3, 47 ], [ 4, 49 ] ],       ("-6") := [ [ 3, 52 ], [ 3, 54 ], [ 2, 56 ] ],       ("-7") := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-8") := [ [ 1, 38 ] ], 0 := [ [ 1, 52 ] ] ),   rec( ("-1") := [ [ 1, 2 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-2") := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-3") := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       ("-4") := [ [ 1, 9 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-5") := [ [ 1, 46 ] ], 0 := [ [ 1, 53 ] ] ),   rec( ("-1") := [ [ 1, 21 ], [ 1, 23 ] ], ("-2") := [ [ 1, 36 ] ],       0 := [ [ 1, 54 ] ] ),   rec( ("-1") := [ [ 1, 6 ], [ 1, 14 ], [ 1, 18 ], [ 1, 20 ], [ 1, 22 ],           [ 1, 24 ] ], ("-2") := [ [ 3, 33 ], [ 2, 35 ], [ 2, 37 ] ],       ("-3") := [ [ 2, 40 ], [ 3, 42 ], [ 2, 44 ] ],       ("-4") := [ [ 1, 11 ], [ 1, 15 ], [ 1, 25 ], [ 1, 27 ], [ 1, 29 ],           [ 1, 31 ] ], ("-5") := [ [ 1, 50 ] ], 0 := [ [ 1, 55 ] ] ),   rec( ("-1") := [ [ 1, 5 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-2") := [ [ 3, 34 ], [ 3, 36 ], [ 2, 38 ] ],       ("-3") := [ [ 4, 39 ], [ 3, 41 ], [ 4, 43 ] ],       ("-4") := [ [ 1, 8 ], [ 1, 10 ], [ 1, 12 ], [ 3, 16 ], [ 3, 26 ],           [ 3, 28 ], [ 3, 30 ], [ 3, 32 ] ],       ("-5") := [ [ 4, 45 ], [ 4, 47 ], [ 3, 49 ] ],       ("-6") := [ [ 2, 52 ], [ 3, 54 ], [ 3, 56 ] ],       ("-7") := [ [ 1, 3 ], [ 1, 13 ], [ 1, 17 ], [ 1, 19 ], [ 1, 21 ],           [ 1, 23 ] ], ("-8") := [ [ 1, 34 ] ], 0 := [ [ 1, 56 ] ] ) ]

In [1505]:
QGNAG_LoadCharactersToLaTeXByIndex("characters_T4_to_zero_negative_permuted_by_index.tex", data_rec_info_to_zero_negative_permuted);

In [1378]:
QGNAG_LoadCharactersToLaTeXT( "characters_T4_to_zero_negative_permuted_by_tau.tex", data_rec_info_to_zero_negative_permuted, SimpleNames );

## Characters

the socle $S(\lambda)$ written as character

\begin{align*}
\text{char } \lambda &= \lambda_1[2] \oplus \lambda_2[3] \oplus \lambda_3[3] \oplus \lambda_4[4] \\
&\quad \uparrow \text{ ``example''} \\
&= q^2 \lambda_1 + q^3 \lambda_2 + q^3 \lambda_3 + q^4 \lambda_4
\end{align*}

But: this is not the $``\operatorname{char} \lambda''$ that We want, we call it $s\text{char } \lambda$ (S for socle) 

First: fix the grading ($\overline{\text{var}}$)

\begin{align*}
\overline{s\text{char } \lambda} &= \lambda_4[-4] \oplus \lambda_2[-3] \oplus \lambda_3[-3] \oplus \lambda_1[-2] \\
&= q^{-4} \lambda_4 + q^{-3} \lambda_2 + q^{-3} \lambda_3 + q^{-2} \lambda_1
\end{align*}

second: Briung to degree $\underline{0}$ (shift $[\cdot]$)

\begin{equation*}
\overline{s\text{char } \lambda} [2] = \underbrace{\lambda_4[-2] \oplus \lambda_2[-1] \oplus \lambda_3[-1] \oplus \lambda_1[0]}_{\text{This is char } \lambda_1}
\end{equation*}

This is what we are looking for

\begin{equation*}
\text{char } \lambda_1 = \lambda_1 + q^{-1} \lambda_2 + q^{-1} \lambda_3 + q^{-2} \lambda_4=\overline{s\text{char } \lambda} [2]=q^2 \overline{s\text{char } \lambda}
\end{equation*}

That is,
\begin{equation*}
\text{char } \lambda_1 = q^2 \overline{s\text{char } \lambda}
\end{equation*}

In [505]:
bijs_by_degree    := List( data_record_data_decomp, QGNAG_MultiplicitiesByNegativeDegree );;
data_rec_info_neg := List( bijs_by_degree, QGNAG_NegativeDecompositionFromMultiplicities );;
QGNAG_LoadCharactersToLaTeX( "characters_neg_option_1.tex", data_rec_info_neg, SimpleNames );

## Braided Equivalence

In [506]:
QGNAG_PermutationFromRecInfo( data_rec_info )=QGNAG_PermutationFromRecInfo( data_rec_info_neg );

true

In [507]:
sigma := QGNAG_PermutationFromRecInfo( data_rec_info_neg );

(2,9)(3,5)(4,7)(6,11)(8,12)(14,15)(18,25)(20,27)(21,23)(22,31)(24,29)(30,32)(33,42)(34,56)(35,40)(36,54)(37,44)(38,52)(39,45)(41,49)(43,47)(46,53)(48,51)(50,55)

In [508]:
QGNAG_PrintFusionRules(data_parallel);

--------------------------------------------------------------
M2 \otimes M2 \simeq M3
M2 \otimes M3 \simeq M4
M2 \otimes M4 \simeq M5
M2 \otimes M5 \simeq M6
M2 \otimes M6 \simeq M1
M2 \otimes M7 \simeq M8
M2 \otimes M8 \simeq M9
M2 \otimes M9 \simeq M10
M2 \otimes M10 \simeq M11
M2 \otimes M11 \simeq M12
M2 \otimes M12 \simeq M7
M2 \otimes M13 \simeq M14
M2 \otimes M14 \simeq M13
M2 \otimes M15 \simeq M16
M2 \otimes M16 \simeq M15
M2 \otimes M17 \simeq M18
M2 \otimes M18 \simeq M17
M2 \otimes M19 \simeq M20
M2 \otimes M20 \simeq M19
M2 \otimes M21 \simeq M22
M2 \otimes M22 \simeq M21
M2 \otimes M23 \simeq M24
M2 \otimes M24 \simeq M23
M2 \otimes M25 \simeq M26
M2 \otimes M26 \simeq M25
M2 \otimes M27 \simeq M28
M2 \otimes M28 \simeq M27
M2 \otimes M29 \simeq M30
M2 \otimes M30 \simeq M29
M2 \otimes M31 \simeq M32
M2 \otimes M32 \simeq M31
M2 \otimes M33 \simeq M38
M2 \otimes M34 \simeq M33
M2 \otimes M35 \simeq M34
M2 \otimes M36 \simeq M35
M2 \otimes M37 \simeq M36
M2 \otimes M38 \simeq M37
M2 \otimes M39 \simeq M44
M2 \otimes M40 \simeq M39
M2 \otimes M41 \simeq M40
M2 \otimes M42 \simeq M41
M2 \otimes M43 \simeq M42
M2 \otimes M44 \simeq M43
M2 \otimes M45 \simeq M50
M2 \otimes M46 \simeq M45
M2 \otimes M47 \simeq M46
M2 \otimes M48 \simeq M47
M2 \otimes M49 \simeq M48
M2 \otimes M50 \simeq M49
M2 \otimes M51 \simeq M56
M2 \otimes M52 \simeq M51
M2 \otimes M53 \simeq M52
M2 \otimes M54 \simeq M53
M2 \otimes M55 \simeq M54
M2 \otimes M56 \simeq M55
--------------------------------------------------------------
M3 \otimes M3 \simeq M5
M3 \otimes M4 \simeq M6
M3 \otimes M5 \simeq M1
M3 \otimes M6 \simeq M2
M3 \otimes M7 \simeq M9
M3 \otimes M8 \simeq M10
M3 \otimes M9 \simeq M11
M3 \otimes M10 \simeq M12
M3 \otimes M11 \simeq M7
M3 \otimes M12 \simeq M8
M3 \otimes M13 \simeq M13
M3 \otimes M14 \simeq M14
M3 \otimes M15 \simeq M15
M3 \otimes M16 \simeq M16
M3 \otimes M17 \simeq M17
M3 \otimes M18 \simeq M18
M3 \otimes M19 \simeq M19
M3 \otimes M20 \simeq M20
M3 \otimes M21 \simeq M21
M3 \otimes M22 \simeq M22
M3 \otimes M23 \simeq M23
M3 \otimes M24 \simeq M24
M3 \otimes M25 \simeq M25
M3 \otimes M26 \simeq M26
M3 \otimes M27 \simeq M27
M3 \otimes M28 \simeq M28
M3 \otimes M29 \simeq M29
M3 \otimes M30 \simeq M30
M3 \otimes M31 \simeq M31
M3 \otimes M32 \simeq M32
M3 \otimes M33 \simeq M37
M3 \otimes M34 \simeq M38
M3 \otimes M35 \simeq M33
M3 \otimes M36 \simeq M34
M3 \otimes M37 \simeq M35
M3 \otimes M38 \simeq M36
M3 \otimes M39 \simeq M43
M3 \otimes M40 \simeq M44
M3 \otimes M41 \simeq M39
M3 \otimes M42 \simeq M40
M3 \otimes M43 \simeq M41
M3 \otimes M44 \simeq M42
M3 \otimes M45 \simeq M49
M3 \otimes M46 \simeq M50
M3 \otimes M47 \simeq M45
M3 \otimes M48 \simeq M46
M3 \otimes M49 \simeq M47
M3 \otimes M50 \simeq M48
M3 \otimes M51 \simeq M55
M3 \otimes M52 \simeq M56
M3 \otimes M53 \simeq M51
M3 \otimes M54 \simeq M52
M3 \otimes M55 \simeq M53
M3 \otimes M56 \simeq M54
--------------------------------------------------------------
M4 \otimes M4 \simeq M1
M4 \otimes M5 \simeq M2
M4 \otimes M6 \simeq M3
M4 \otimes M7 \simeq M10
M4 \otimes M8 \simeq M11
M4 \otimes M9 \simeq M12
M4 \otimes M10 \simeq M7
M4 \otimes M11 \simeq M8
M4 \otimes M12 \simeq M9
M4 \otimes M13 \simeq M14
M4 \otimes M14 \simeq M13
M4 \otimes M15 \simeq M16
M4 \otimes M16 \simeq M15
M4 \otimes M17 \simeq M18
M4 \otimes M18 \simeq M17
M4 \otimes M19 \simeq M20
M4 \otimes M20 \simeq M19
M4 \otimes M21 \simeq M22
M4 \otimes M22 \simeq M21
M4 \otimes M23 \simeq M24
M4 \otimes M24 \simeq M23
M4 \otimes M25 \simeq M26
M4 \otimes M26 \simeq M25
M4 \otimes M27 \simeq M28
M4 \otimes M28 \simeq M27
M4 \otimes M29 \simeq M30
M4 \otimes M30 \simeq M29
M4 \otimes M31 \simeq M32
M4 \otimes M32 \simeq M31
M4 \otimes M33 \simeq M36
M4 \otimes M34 \simeq M37
M4 \otimes M35 \simeq M38
M4 \otimes M36 \simeq M33
M4 \otimes M37 \simeq M34
M4 \otimes M38 \simeq M35
M4 \otimes M39 \simeq M42
M4 \otimes M40 \simeq M43
M4 \otimes M41 \simeq M44
M4 \otimes M42 \simeq M39
M4 \otimes M43 \simeq M40
M4 \otimes M44 \simeq M41
M4 \otimes M45 \simeq M48
M4 \otimes M46 \simeq M49
M4 \otimes M47 \simeq M50
M4 \otimes M48 \simeq M45
M4 \otimes M49 \simeq M46
M4 \otimes M50 \simeq M47
M4 \otimes M51 \simeq M54
M4 \otimes M52 \simeq M55
M4 \otimes M53 \simeq M56
M4 \otimes M54 \simeq M51
M4 \otimes M55 \simeq M52
M4 \otimes M56 \simeq M53
--------------------------------------------------------------
M5 \otimes M5 \simeq M3
M5 \otimes M6 \simeq M4
M5 \otimes M7 \simeq M11
M5 \otimes M8 \simeq M12
M5 \otimes M9 \simeq M7
M5 \otimes M10 \simeq M8
M5 \otimes M11 \simeq M9
M5 \otimes M12 \simeq M10
M5 \otimes M13 \simeq M13
M5 \otimes M14 \simeq M14
M5 \otimes M15 \simeq M15
M5 \otimes M16 \simeq M16
M5 \otimes M17 \simeq M17
M5 \otimes M18 \simeq M18
M5 \otimes M19 \simeq M19
M5 \otimes M20 \simeq M20
M5 \otimes M21 \simeq M21
M5 \otimes M22 \simeq M22
M5 \otimes M23 \simeq M23
M5 \otimes M24 \simeq M24
M5 \otimes M25 \simeq M25
M5 \otimes M26 \simeq M26
M5 \otimes M27 \simeq M27
M5 \otimes M28 \simeq M28
M5 \otimes M29 \simeq M29
M5 \otimes M30 \simeq M30
M5 \otimes M31 \simeq M31
M5 \otimes M32 \simeq M32
M5 \otimes M33 \simeq M35
M5 \otimes M34 \simeq M36
M5 \otimes M35 \simeq M37
M5 \otimes M36 \simeq M38
M5 \otimes M37 \simeq M33
M5 \otimes M38 \simeq M34
M5 \otimes M39 \simeq M41
M5 \otimes M40 \simeq M42
M5 \otimes M41 \simeq M43
M5 \otimes M42 \simeq M44
M5 \otimes M43 \simeq M39
M5 \otimes M44 \simeq M40
M5 \otimes M45 \simeq M47
M5 \otimes M46 \simeq M48
M5 \otimes M47 \simeq M49
M5 \otimes M48 \simeq M50
M5 \otimes M49 \simeq M45
M5 \otimes M50 \simeq M46
M5 \otimes M51 \simeq M53
M5 \otimes M52 \simeq M54
M5 \otimes M53 \simeq M55
M5 \otimes M54 \simeq M56
M5 \otimes M55 \simeq M51
M5 \otimes M56 \simeq M52
--------------------------------------------------------------
M6 \otimes M6 \simeq M5
M6 \otimes M7 \simeq M12
M6 \otimes M8 \simeq M7
M6 \otimes M9 \simeq M8
M6 \otimes M10 \simeq M9
M6 \otimes M11 \simeq M10
M6 \otimes M12 \simeq M11
M6 \otimes M13 \simeq M14
M6 \otimes M14 \simeq M13
M6 \otimes M15 \simeq M16
M6 \otimes M16 \simeq M15
M6 \otimes M17 \simeq M18
M6 \otimes M18 \simeq M17
M6 \otimes M19 \simeq M20
M6 \otimes M20 \simeq M19
M6 \otimes M21 \simeq M22
M6 \otimes M22 \simeq M21
M6 \otimes M23 \simeq M24
M6 \otimes M24 \simeq M23
M6 \otimes M25 \simeq M26
M6 \otimes M26 \simeq M25
M6 \otimes M27 \simeq M28
M6 \otimes M28 \simeq M27
M6 \otimes M29 \simeq M30
M6 \otimes M30 \simeq M29
M6 \otimes M31 \simeq M32
M6 \otimes M32 \simeq M31
M6 \otimes M33 \simeq M34
M6 \otimes M34 \simeq M35
M6 \otimes M35 \simeq M36
M6 \otimes M36 \simeq M37
M6 \otimes M37 \simeq M38
M6 \otimes M38 \simeq M33
M6 \otimes M39 \simeq M40
M6 \otimes M40 \simeq M41
M6 \otimes M41 \simeq M42
M6 \otimes M42 \simeq M43
M6 \otimes M43 \simeq M44
M6 \otimes M44 \simeq M39
M6 \otimes M45 \simeq M46
M6 \otimes M46 \simeq M47
M6 \otimes M47 \simeq M48
M6 \otimes M48 \simeq M49
M6 \otimes M49 \simeq M50
M6 \otimes M50 \simeq M45
M6 \otimes M51 \simeq M52
M6 \otimes M52 \simeq M53
M6 \otimes M53 \simeq M54
M6 \otimes M54 \simeq M55
M6 \otimes M55 \simeq M56
M6 \otimes M56 \simeq M51
--------------------------------------------------------------
M7 \otimes M7 \simeq M1
M7 \otimes M8 \simeq M2
M7 \otimes M9 \simeq M3
M7 \otimes M10 \simeq M4
M7 \otimes M11 \simeq M5
M7 \otimes M12 \simeq M6
M7 \otimes M13 \simeq M15
M7 \otimes M14 \simeq M16
M7 \otimes M15 \simeq M13
M7 \otimes M16 \simeq M14
M7 \otimes M17 \simeq M25
M7 \otimes M18 \simeq M26
M7 \otimes M19 \simeq M27
M7 \otimes M20 \simeq M28
M7 \otimes M21 \simeq M29
M7 \otimes M22 \simeq M30
M7 \otimes M23 \simeq M31
M7 \otimes M24 \simeq M32
M7 \otimes M25 \simeq M17
M7 \otimes M26 \simeq M18
M7 \otimes M27 \simeq M19
M7 \otimes M28 \simeq M20
M7 \otimes M29 \simeq M21
M7 \otimes M30 \simeq M22
M7 \otimes M31 \simeq M23
M7 \otimes M32 \simeq M24
M7 \otimes M33 \simeq M45
M7 \otimes M34 \simeq M46
M7 \otimes M35 \simeq M47
M7 \otimes M36 \simeq M48
M7 \otimes M37 \simeq M49
M7 \otimes M38 \simeq M50
M7 \otimes M39 \simeq M51
M7 \otimes M40 \simeq M52
M7 \otimes M41 \simeq M53
M7 \otimes M42 \simeq M54
M7 \otimes M43 \simeq M55
M7 \otimes M44 \simeq M56
M7 \otimes M45 \simeq M33
M7 \otimes M46 \simeq M34
M7 \otimes M47 \simeq M35
M7 \otimes M48 \simeq M36
M7 \otimes M49 \simeq M37
M7 \otimes M50 \simeq M38
M7 \otimes M51 \simeq M39
M7 \otimes M52 \simeq M40
M7 \otimes M53 \simeq M41
M7 \otimes M54 \simeq M42
M7 \otimes M55 \simeq M43
M7 \otimes M56 \simeq M44
--------------------------------------------------------------
M8 \otimes M8 \simeq M3
M8 \otimes M9 \simeq M4
M8 \otimes M10 \simeq M5
M8 \otimes M11 \simeq M6
M8 \otimes M12 \simeq M1
M8 \otimes M13 \simeq M16
M8 \otimes M14 \simeq M15
M8 \otimes M15 \simeq M14
M8 \otimes M16 \simeq M13
M8 \otimes M17 \simeq M26
M8 \otimes M18 \simeq M25
M8 \otimes M19 \simeq M28
M8 \otimes M20 \simeq M27
M8 \otimes M21 \simeq M30
M8 \otimes M22 \simeq M29
M8 \otimes M23 \simeq M32
M8 \otimes M24 \simeq M31
M8 \otimes M25 \simeq M18
M8 \otimes M26 \simeq M17
M8 \otimes M27 \simeq M20
M8 \otimes M28 \simeq M19
M8 \otimes M29 \simeq M22
M8 \otimes M30 \simeq M21
M8 \otimes M31 \simeq M24
M8 \otimes M32 \simeq M23
M8 \otimes M33 \simeq M50
M8 \otimes M34 \simeq M45
M8 \otimes M35 \simeq M46
M8 \otimes M36 \simeq M47
M8 \otimes M37 \simeq M48
M8 \otimes M38 \simeq M49
M8 \otimes M39 \simeq M56
M8 \otimes M40 \simeq M51
M8 \otimes M41 \simeq M52
M8 \otimes M42 \simeq M53
M8 \otimes M43 \simeq M54
M8 \otimes M44 \simeq M55
M8 \otimes M45 \simeq M38
M8 \otimes M46 \simeq M33
M8 \otimes M47 \simeq M34
M8 \otimes M48 \simeq M35
M8 \otimes M49 \simeq M36
M8 \otimes M50 \simeq M37
M8 \otimes M51 \simeq M44
M8 \otimes M52 \simeq M39
M8 \otimes M53 \simeq M40
M8 \otimes M54 \simeq M41
M8 \otimes M55 \simeq M42
M8 \otimes M56 \simeq M43
--------------------------------------------------------------
M9 \otimes M9 \simeq M5
M9 \otimes M10 \simeq M6
M9 \otimes M11 \simeq M1
M9 \otimes M12 \simeq M2
M9 \otimes M13 \simeq M15
M9 \otimes M14 \simeq M16
M9 \otimes M15 \simeq M13
M9 \otimes M16 \simeq M14
M9 \otimes M17 \simeq M25
M9 \otimes M18 \simeq M26
M9 \otimes M19 \simeq M27
M9 \otimes M20 \simeq M28
M9 \otimes M21 \simeq M29
M9 \otimes M22 \simeq M30
M9 \otimes M23 \simeq M31
M9 \otimes M24 \simeq M32
M9 \otimes M25 \simeq M17
M9 \otimes M26 \simeq M18
M9 \otimes M27 \simeq M19
M9 \otimes M28 \simeq M20
M9 \otimes M29 \simeq M21
M9 \otimes M30 \simeq M22
M9 \otimes M31 \simeq M23
M9 \otimes M32 \simeq M24
M9 \otimes M33 \simeq M49
M9 \otimes M34 \simeq M50
M9 \otimes M35 \simeq M45
M9 \otimes M36 \simeq M46
M9 \otimes M37 \simeq M47
M9 \otimes M38 \simeq M48
M9 \otimes M39 \simeq M55
M9 \otimes M40 \simeq M56
M9 \otimes M41 \simeq M51
M9 \otimes M42 \simeq M52
M9 \otimes M43 \simeq M53
M9 \otimes M44 \simeq M54
M9 \otimes M45 \simeq M37
M9 \otimes M46 \simeq M38
M9 \otimes M47 \simeq M33
M9 \otimes M48 \simeq M34
M9 \otimes M49 \simeq M35
M9 \otimes M50 \simeq M36
M9 \otimes M51 \simeq M43
M9 \otimes M52 \simeq M44
M9 \otimes M53 \simeq M39
M9 \otimes M54 \simeq M40
M9 \otimes M55 \simeq M41
M9 \otimes M56 \simeq M42
--------------------------------------------------------------
M10 \otimes M10 \simeq M1
M10 \otimes M11 \simeq M2
M10 \otimes M12 \simeq M3
M10 \otimes M13 \simeq M16
M10 \otimes M14 \simeq M15
M10 \otimes M15 \simeq M14
M10 \otimes M16 \simeq M13
M10 \otimes M17 \simeq M26
M10 \otimes M18 \simeq M25
M10 \otimes M19 \simeq M28
M10 \otimes M20 \simeq M27
M10 \otimes M21 \simeq M30
M10 \otimes M22 \simeq M29
M10 \otimes M23 \simeq M32
M10 \otimes M24 \simeq M31
M10 \otimes M25 \simeq M18
M10 \otimes M26 \simeq M17
M10 \otimes M27 \simeq M20
M10 \otimes M28 \simeq M19
M10 \otimes M29 \simeq M22
M10 \otimes M30 \simeq M21
M10 \otimes M31 \simeq M24
M10 \otimes M32 \simeq M23
M10 \otimes M33 \simeq M48
M10 \otimes M34 \simeq M49
M10 \otimes M35 \simeq M50
M10 \otimes M36 \simeq M45
M10 \otimes M37 \simeq M46
M10 \otimes M38 \simeq M47
M10 \otimes M39 \simeq M54
M10 \otimes M40 \simeq M55
M10 \otimes M41 \simeq M56
M10 \otimes M42 \simeq M51
M10 \otimes M43 \simeq M52
M10 \otimes M44 \simeq M53
M10 \otimes M45 \simeq M36
M10 \otimes M46 \simeq M37
M10 \otimes M47 \simeq M38
M10 \otimes M48 \simeq M33
M10 \otimes M49 \simeq M34
M10 \otimes M50 \simeq M35
M10 \otimes M51 \simeq M42
M10 \otimes M52 \simeq M43
M10 \otimes M53 \simeq M44
M10 \otimes M54 \simeq M39
M10 \otimes M55 \simeq M40
M10 \otimes M56 \simeq M41
--------------------------------------------------------------
M11 \otimes M11 \simeq M3
M11 \otimes M12 \simeq M4
M11 \otimes M13 \simeq M15
M11 \otimes M14 \simeq M16
M11 \otimes M15 \simeq M13
M11 \otimes M16 \simeq M14
M11 \otimes M17 \simeq M25
M11 \otimes M18 \simeq M26
M11 \otimes M19 \simeq M27
M11 \otimes M20 \simeq M28
M11 \otimes M21 \simeq M29
M11 \otimes M22 \simeq M30
M11 \otimes M23 \simeq M31
M11 \otimes M24 \simeq M32
M11 \otimes M25 \simeq M17
M11 \otimes M26 \simeq M18
M11 \otimes M27 \simeq M19
M11 \otimes M28 \simeq M20
M11 \otimes M29 \simeq M21
M11 \otimes M30 \simeq M22
M11 \otimes M31 \simeq M23
M11 \otimes M32 \simeq M24
M11 \otimes M33 \simeq M47
M11 \otimes M34 \simeq M48
M11 \otimes M35 \simeq M49
M11 \otimes M36 \simeq M50
M11 \otimes M37 \simeq M45
M11 \otimes M38 \simeq M46
M11 \otimes M39 \simeq M53
M11 \otimes M40 \simeq M54
M11 \otimes M41 \simeq M55
M11 \otimes M42 \simeq M56
M11 \otimes M43 \simeq M51
M11 \otimes M44 \simeq M52
M11 \otimes M45 \simeq M35
M11 \otimes M46 \simeq M36
M11 \otimes M47 \simeq M37
M11 \otimes M48 \simeq M38
M11 \otimes M49 \simeq M33
M11 \otimes M50 \simeq M34
M11 \otimes M51 \simeq M41
M11 \otimes M52 \simeq M42
M11 \otimes M53 \simeq M43
M11 \otimes M54 \simeq M44
M11 \otimes M55 \simeq M39
M11 \otimes M56 \simeq M40
--------------------------------------------------------------
M12 \otimes M12 \simeq M5
M12 \otimes M13 \simeq M16
M12 \otimes M14 \simeq M15
M12 \otimes M15 \simeq M14
M12 \otimes M16 \simeq M13
M12 \otimes M17 \simeq M26
M12 \otimes M18 \simeq M25
M12 \otimes M19 \simeq M28
M12 \otimes M20 \simeq M27
M12 \otimes M21 \simeq M30
M12 \otimes M22 \simeq M29
M12 \otimes M23 \simeq M32
M12 \otimes M24 \simeq M31
M12 \otimes M25 \simeq M18
M12 \otimes M26 \simeq M17
M12 \otimes M27 \simeq M20
M12 \otimes M28 \simeq M19
M12 \otimes M29 \simeq M22
M12 \otimes M30 \simeq M21
M12 \otimes M31 \simeq M24
M12 \otimes M32 \simeq M23
M12 \otimes M33 \simeq M46
M12 \otimes M34 \simeq M47
M12 \otimes M35 \simeq M48
M12 \otimes M36 \simeq M49
M12 \otimes M37 \simeq M50
M12 \otimes M38 \simeq M45
M12 \otimes M39 \simeq M52
M12 \otimes M40 \simeq M53
M12 \otimes M41 \simeq M54
M12 \otimes M42 \simeq M55
M12 \otimes M43 \simeq M56
M12 \otimes M44 \simeq M51
M12 \otimes M45 \simeq M34
M12 \otimes M46 \simeq M35
M12 \otimes M47 \simeq M36
M12 \otimes M48 \simeq M37
M12 \otimes M49 \simeq M38
M12 \otimes M50 \simeq M33
M12 \otimes M51 \simeq M40
M12 \otimes M52 \simeq M41
M12 \otimes M53 \simeq M42
M12 \otimes M54 \simeq M43
M12 \otimes M55 \simeq M44
M12 \otimes M56 \simeq M39
--------------------------------------------------------------
M13 \otimes M13 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M13 \otimes M14 \simeq M2 \oplus M4 \oplus M6 \oplus 2 M14
M13 \otimes M15 \simeq M7 \oplus M9 \oplus M11 \oplus 2 M15
M13 \otimes M16 \simeq M8 \oplus M10 \oplus M12 \oplus 2 M16
M13 \otimes M17 \simeq M19 \oplus M21 \oplus M23
M13 \otimes M18 \simeq M20 \oplus M22 \oplus M24
M13 \otimes M19 \simeq M17 \oplus M21 \oplus M23
M13 \otimes M20 \simeq M18 \oplus M22 \oplus M24
M13 \otimes M21 \simeq M17 \oplus M19 \oplus M23
M13 \otimes M22 \simeq M18 \oplus M20 \oplus M24
M13 \otimes M23 \simeq M17 \oplus M19 \oplus M21
M13 \otimes M24 \simeq M18 \oplus M20 \oplus M22
M13 \otimes M25 \simeq M27 \oplus M29 \oplus M31
M13 \otimes M26 \simeq M28 \oplus M30 \oplus M32
M13 \otimes M27 \simeq M25 \oplus M29 \oplus M31
M13 \otimes M28 \simeq M26 \oplus M30 \oplus M32
M13 \otimes M29 \simeq M25 \oplus M27 \oplus M31
M13 \otimes M30 \simeq M26 \oplus M28 \oplus M32
M13 \otimes M31 \simeq M25 \oplus M27 \oplus M29
M13 \otimes M32 \simeq M26 \oplus M28 \oplus M30
M13 \otimes M33 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M34 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M35 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M36 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M37 \simeq M33 \oplus M35 \oplus M37
M13 \otimes M38 \simeq M34 \oplus M36 \oplus M38
M13 \otimes M39 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M40 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M41 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M42 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M43 \simeq M39 \oplus M41 \oplus M43
M13 \otimes M44 \simeq M40 \oplus M42 \oplus M44
M13 \otimes M45 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M46 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M47 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M48 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M49 \simeq M45 \oplus M47 \oplus M49
M13 \otimes M50 \simeq M46 \oplus M48 \oplus M50
M13 \otimes M51 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M52 \simeq M52 \oplus M54 \oplus M56
M13 \otimes M53 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M54 \simeq M52 \oplus M54 \oplus M56
M13 \otimes M55 \simeq M51 \oplus M53 \oplus M55
M13 \otimes M56 \simeq M52 \oplus M54 \oplus M56
--------------------------------------------------------------
M14 \otimes M14 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M14 \otimes M15 \simeq M8 \oplus M10 \oplus M12 \oplus 2 M16
M14 \otimes M16 \simeq M7 \oplus M9 \oplus M11 \oplus 2 M15
M14 \otimes M17 \simeq M20 \oplus M22 \oplus M24
M14 \otimes M18 \simeq M19 \oplus M21 \oplus M23
M14 \otimes M19 \simeq M18 \oplus M22 \oplus M24
M14 \otimes M20 \simeq M17 \oplus M21 \oplus M23
M14 \otimes M21 \simeq M18 \oplus M20 \oplus M24
M14 \otimes M22 \simeq M17 \oplus M19 \oplus M23
M14 \otimes M23 \simeq M18 \oplus M20 \oplus M22
M14 \otimes M24 \simeq M17 \oplus M19 \oplus M21
M14 \otimes M25 \simeq M28 \oplus M30 \oplus M32
M14 \otimes M26 \simeq M27 \oplus M29 \oplus M31
M14 \otimes M27 \simeq M26 \oplus M30 \oplus M32
M14 \otimes M28 \simeq M25 \oplus M29 \oplus M31
M14 \otimes M29 \simeq M26 \oplus M28 \oplus M32
M14 \otimes M30 \simeq M25 \oplus M27 \oplus M31
M14 \otimes M31 \simeq M26 \oplus M28 \oplus M30
M14 \otimes M32 \simeq M25 \oplus M27 \oplus M29
M14 \otimes M33 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M34 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M35 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M36 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M37 \simeq M34 \oplus M36 \oplus M38
M14 \otimes M38 \simeq M33 \oplus M35 \oplus M37
M14 \otimes M39 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M40 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M41 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M42 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M43 \simeq M40 \oplus M42 \oplus M44
M14 \otimes M44 \simeq M39 \oplus M41 \oplus M43
M14 \otimes M45 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M46 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M47 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M48 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M49 \simeq M46 \oplus M48 \oplus M50
M14 \otimes M50 \simeq M45 \oplus M47 \oplus M49
M14 \otimes M51 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M52 \simeq M51 \oplus M53 \oplus M55
M14 \otimes M53 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M54 \simeq M51 \oplus M53 \oplus M55
M14 \otimes M55 \simeq M52 \oplus M54 \oplus M56
M14 \otimes M56 \simeq M51 \oplus M53 \oplus M55
--------------------------------------------------------------
M15 \otimes M15 \simeq M1 \oplus M3 \oplus M5 \oplus 2 M13
M15 \otimes M16 \simeq M2 \oplus M4 \oplus M6 \oplus 2 M14
M15 \otimes M17 \simeq M27 \oplus M29 \oplus M31
M15 \otimes M18 \simeq M28 \oplus M30 \oplus M32
M15 \otimes M19 \simeq M25 \oplus M29 \oplus M31
M15 \otimes M20 \simeq M26 \oplus M30 \oplus M32
M15 \otimes M21 \simeq M25 \oplus M27 \oplus M31
M15 \otimes M22 \simeq M26 \oplus M28 \oplus M32

In [509]:
failures := QGNAG_PermutationFusionRulesFailures( sigma, SimplesMn, data_parallel );

[  ]

In [510]:
QGNAG_TestPermutationFusionRules( sigma, SimplesMn, data_parallel );

========================================
  Permutation fusion test: PASSED
========================================
The permutation preserves all fusion rules.

true

## $\tau=\sigma\circ(\_)^\vee$

In [511]:
tau := QGNAG_PermutationVarChars(data_rec_info_neg);

(1,10)(2,6)(3,8)(5,12)(9,11)(13,16)(17,26)(19,28)(21,32)(22,24)(23,30)(29,31)(33,51)(34,41)(35,55)(36,39)(37,53)(38,43)(40,50)(42,48)(44,46)(45,54)(47,52)(49,56)

In [512]:
SimpleNames;

[ "M(0,\\tau_{00})", "M(0,\\tau_{12})", "M(0,\\tau_{01})", "M(0,\\tau_{10})",   "M(0,\\tau_{02})", "M(0,\\tau_{11})", "M(3,\\tau_{00})", "M(3,\\tau_{12})",   "M(3,\\tau_{01})", "M(3,\\tau_{10})", "M(3,\\tau_{02})", "M(3,\\tau_{11})",   "M(0,\\rho_{0})", "M(0,\\rho_{1})", "M(3,\\rho_{0})", "M(3,\\rho_{1})",   "M(0,\\chi_{(0,0,0)})", "M(0,\\chi_{(0,0,1)})", "M(0,\\chi_{(0,1,0)})",   "M(0,\\chi_{(0,1,1)})", "M(0,\\chi_{(1,0,0)})", "M(0,\\chi_{(1,0,1)})",   "M(0,\\chi_{(1,1,0)})", "M(0,\\chi_{(1,1,1)})", "M(3,\\chi_{(0,0,0)})",   "M(3,\\chi_{(0,0,1)})", "M(3,\\chi_{(0,1,0)})", "M(3,\\chi_{(0,1,1)})",   "M(3,\\chi_{(1,0,0)})", "M(3,\\chi_{(1,0,1)})", "M(3,\\chi_{(1,1,0)})",   "M(3,\\chi_{(1,1,1)})", "M(1,\\eta_{0})", "M(1,\\eta_{1})",   "M(1,\\eta_{2})", "M(1,\\eta_{3})", "M(1,\\eta_{4})", "M(1,\\eta_{5})",   "M(2,\\eta_{0})", "M(2,\\eta_{1})", "M(2,\\eta_{2})", "M(2,\\eta_{3})",   "M(2,\\eta_{4})", "M(2,\\eta_{5})", "M(4,\\eta_{0})", "M(4,\\eta_{1})",   "M(4,\\eta_{2})", "M(4,\\eta_{3})", "M(4,\\eta_{4})", "M(4,\\eta_{5})",   "M(5,\\eta_{0})", "M(5,\\eta_{1})", "M(5,\\eta_{2})", "M(5,\\eta_{3})",   "M(5,\\eta_{4})", "M(5,\\eta_{5})" ]

In [513]:
QGNAG_GetLName(data_record_data_decomp, SimpleNames);

[ "L(3,\\tau_{10})", "L(0,\\tau_{11})", "L(3,\\tau_{12})", "L(0,\\tau_{10})",   "L(3,\\tau_{11})", "L(0,\\tau_{12})", "L(3,\\tau_{00})", "L(0,\\tau_{01})",   "L(3,\\tau_{02})", "L(0,\\tau_{00})", "L(3,\\tau_{01})", "L(0,\\tau_{02})",   "L(3,\\rho_{1})", "L(0,\\rho_{1})", "L(3,\\rho_{0})", "L(0,\\rho_{0})",   "L(3,\\chi_{(0,0,1)})", "L(0,\\chi_{(0,0,1)})", "L(3,\\chi_{(0,1,1)})",   "L(0,\\chi_{(0,1,1)})", "L(3,\\chi_{(1,1,1)})", "L(0,\\chi_{(1,1,1)})",   "L(3,\\chi_{(1,0,1)})", "L(0,\\chi_{(1,0,1)})", "L(3,\\chi_{(0,0,0)})",   "L(0,\\chi_{(0,0,0)})", "L(3,\\chi_{(0,1,0)})", "L(0,\\chi_{(0,1,0)})",   "L(3,\\chi_{(1,1,0)})", "L(0,\\chi_{(1,1,0)})", "L(3,\\chi_{(1,0,0)})",   "L(0,\\chi_{(1,0,0)})", "L(5,\\eta_{0})", "L(2,\\eta_{2})",   "L(5,\\eta_{4})", "L(2,\\eta_{0})", "L(5,\\eta_{2})", "L(2,\\eta_{4})",   "L(1,\\eta_{3})", "L(4,\\eta_{5})", "L(1,\\eta_{1})", "L(4,\\eta_{3})",   "L(1,\\eta_{5})", "L(4,\\eta_{1})", "L(5,\\eta_{3})", "L(2,\\eta_{5})",   "L(5,\\eta_{1})", "L(2,\\eta_{3})", "L(5,\\eta_{5})", "L(2,\\eta_{1})",   "L(1,\\eta_{0})", "L(4,\\eta_{2})", "L(1,\\eta_{4})", "L(4,\\eta_{0})",   "L(1,\\eta_{2})", "L(4,\\eta_{4})" ]

In [514]:
QGNAG_GetLNameOrdered(data_record_data_decomp, SimpleNames);

[ "L(0,\\tau_{00})", "L(0,\\tau_{12})", "L(0,\\tau_{01})", "L(0,\\tau_{10})",   "L(0,\\tau_{02})", "L(0,\\tau_{11})", "L(3,\\tau_{00})", "L(3,\\tau_{12})",   "L(3,\\tau_{01})", "L(3,\\tau_{10})", "L(3,\\tau_{02})", "L(3,\\tau_{11})",   "L(0,\\rho_{0})", "L(0,\\rho_{1})", "L(3,\\rho_{0})", "L(3,\\rho_{1})",   "L(0,\\chi_{(0,0,0)})", "L(0,\\chi_{(0,0,1)})", "L(0,\\chi_{(0,1,0)})",   "L(0,\\chi_{(0,1,1)})", "L(0,\\chi_{(1,0,0)})", "L(0,\\chi_{(1,0,1)})",   "L(0,\\chi_{(1,1,0)})", "L(0,\\chi_{(1,1,1)})", "L(3,\\chi_{(0,0,0)})",   "L(3,\\chi_{(0,0,1)})", "L(3,\\chi_{(0,1,0)})", "L(3,\\chi_{(0,1,1)})",   "L(3,\\chi_{(1,0,0)})", "L(3,\\chi_{(1,0,1)})", "L(3,\\chi_{(1,1,0)})",   "L(3,\\chi_{(1,1,1)})", "L(1,\\eta_{0})", "L(1,\\eta_{1})",   "L(1,\\eta_{2})", "L(1,\\eta_{3})", "L(1,\\eta_{4})", "L(1,\\eta_{5})",   "L(2,\\eta_{0})", "L(2,\\eta_{1})", "L(2,\\eta_{2})", "L(2,\\eta_{3})",   "L(2,\\eta_{4})", "L(2,\\eta_{5})", "L(4,\\eta_{0})", "L(4,\\eta_{1})",   "L(4,\\eta_{2})", "L(4,\\eta_{3})", "L(4,\\eta_{4})", "L(4,\\eta_{5})",   "L(5,\\eta_{0})", "L(5,\\eta_{1})", "L(5,\\eta_{2})", "L(5,\\eta_{3})",   "L(5,\\eta_{4})", "L(5,\\eta_{5})" ]

# Descomposición de $\mathfrak{B}(V)$ como $D(G)-\text{mod}$

In [515]:
ActionMatrixByGenerator := function( BaseNichols, J_Nichols, gen )
    local N, Amat, Lt, genGi, bj, pol, mon, PolG2, PolG2Norm, pos, coeffss, bi;
    N := Length(BaseNichols);
    Amat := NullMat(N, N);
    # Precálculos fuera del bucle
    Lt := List(QGNAG.Config.gensA, ElementFq);
    genGi := QGNAG.Config.elmsG[Position( allPairsInG, gen )];
    for bj in [1..N] do
        pol := BaseNichols[bj];
        mon := pol[1];
        PolG2     := [[List(mon[1], m -> Position(Lt, genGi * QGNAG.Config.gensA[m]))], [1]];
        PolG2Norm := StrongNormalFormNP(PolG2, J_Nichols);
        pos       := List(PolG2Norm[1], tx -> Position(BaseNichols, [[tx], [1]]));
        coeffss   := PolG2Norm[2] * ChiForSemidirectProduct( genGi )^Length(pol[1][1]);
        for bi in pos do
            Amat[bi][bj] := coeffss[Position(pos, bi)];
        od;
    od;
    return Amat;
end;

function( BaseNichols, J_Nichols, gen ) ... end

In [519]:
F1NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_T4, allPairsInG, G.1 );;
F2NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_T4, allPairsInG, G.2 );;
F3NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_T4, allPairsInG, G.3 );;
F4NicholsBasisAction:=QGNAG_NicholsBasisAction(Base_T4, allPairsInG, G.4 );;

In [523]:
PolsNormF1 := List(F1NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_T4));;
PolsNormF2 := List(F2NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_T4));;
PolsNormF3 := List(F3NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_T4));;
PolsNormF4 := List(F4NicholsBasisAction, Pol -> StrongNormalFormNP(Pol, J_T4));;

In [527]:
F1_mats := QGNAG_GroupActionOnNicholsBasis( Base_T4, PolsNormF1, allPairsInG, G.1 );;
F2_mats := QGNAG_GroupActionOnNicholsBasis( Base_T4, PolsNormF2, allPairsInG, G.2 );;
F3_mats := QGNAG_GroupActionOnNicholsBasis( Base_T4, PolsNormF3, allPairsInG, G.3 );;
F4_mats := QGNAG_GroupActionOnNicholsBasis( Base_T4, PolsNormF4, allPairsInG, G.4 );;

In [531]:
F1_mats = ActionMatrixByGenerator( Base_T4, J_T4, G.1 );
F2_mats = ActionMatrixByGenerator( Base_T4, J_T4, G.2 );
F3_mats = ActionMatrixByGenerator( Base_T4, J_T4, G.3 );
F4_mats = ActionMatrixByGenerator( Base_T4, J_T4, G.4 );

true

true

true

true

In [532]:
block_mats_s_via_pkg:=Concatenation(
        [
            QGNAG_ActionBlocksByGenerator( Base_T4, PolsNormF1, allPairsInG, G.1 ),
            QGNAG_ActionBlocksByGenerator( Base_T4, PolsNormF2, allPairsInG, G.2 ),
            QGNAG_ActionBlocksByGenerator( Base_T4, PolsNormF3, allPairsInG, G.3 ),
            QGNAG_ActionBlocksByGenerator( Base_T4, PolsNormF4, allPairsInG, G.4 )
        ],
        QGNAG_DeltaBlocksByDegree( Base_T4 )
);

[ rec( 0 := [ [ 1 ] ],       1 := [ [ -1, 0, 0, 0 ], [ 0, 0, 0, -1 ], [ 0, -1, 0, 0 ],           [ 0, 0, -1, 0 ] ],       2 := [ [ 0, 0, 1, -1, 0, 0, 0, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, -1 ], [ 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, -1, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 1, -1, 0 ], [ 0, 0, 0, 0, 1, 0, 0, 0 ] ],       3 := [ [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, 0, 1, 0, 0, -1, 0, 0 ],           [ 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1 ],           [ 0, -1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ -1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0 ] ],       5 := [ [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ] ],       6 := [ [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, -1, 0, -1, -1, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ] ],       7 := [ [ 0, 0, 0, -1, 0, 0, 0, 0 ], [ 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 1, 0, 0 ], [ 1, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0, -1, 0, 0 ] ],       8 := [ [ 0, -1, 0, 0 ], [ 0, 0, -1, 0 ], [ 1, 0, 0, 0 ], [ 0, 0, 0, 1 ]          ], 9 := [ [ -1 ] ] ),   rec( 0 := [ [ 1 ] ],       1 := [ [ 1, 0, 0, 0 ], [ 0, 0, 1, 0 ], [ 0, 0, 0, 1 ], [ 0, 1, 0, 0 ] ],      2 := [ [ 0, 1, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 1, -1, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, -1, 0, 0, 0 ], [ 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, 0, 0, -1, 1, 0 ],           [ 0, 0, 0, 0, 0, -1, 0, 0 ], [ 0, 0, 0, -1, 0, 0, 0, 0 ] ],       3 := [ [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 1, 0, -1, 0, 0, 1, 0, 0 ],           [ 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, -1, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 1, -1, 0 ],           [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ -1, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ] ],       5 := [ [ 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ] ],       6 := [ [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, -1, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 1, 0, -1, 0, 0, 0, 0 ],           [ 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ] ],       7 := [ [ -1, 0, 0, -1, 0, 0, 0, 0 ], [ 0, 0, -1, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, -1, 0, 1, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, -1, 0, 0 ], [ 0, 0, 0, 0, 0, 0, -1, 0 ] ],       8 := [ [ 0, 0, 1, 0 ], [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, 0, 1 ]          ], 9 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ],       1 := [ [ 0, 1, 0, 0 ], [ 1, 0, 0, 0 ], [ 0, 0, 0, 1 ], [ 0, 0, 1, 0 ] ],      2 := [ [ 0, 0, 0, 1, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 1, -1, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0 ], [ 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0 ], [ 0, 1, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 0, -1 ], [ 0, 0, 0, 0, 0, 0, -1, 0 ] ],       3 := [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],           [ 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, 0, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],       4 := [ [ 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 1, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0 ],           [ 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ] ],       5 := [ [ 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ] ],       6 := [ [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 1, 1, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ],           [ 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ],       7 := [ [ 0, 1, 0, 0, 0, 1, 0, 0 ], [ 1, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0 ], [ 0, 0, 0, 0, 0, -1, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1 ], [ 0, 0, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 1, 0, 0, 0 ] ],       8 := [ [ 0, -1, 0, 0 ], [ -1, 0, 0, 0 ], [ 0, 0, 0, 1 ], [ 0, 0, 1, 0 ]          ], 9 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ],       1 := [ [ 0, 0, 0, 1 ], [ 0, 0, 1, 0 ], [ 0, 1, 0, 0 ], [ 1, 0, 0, 0 ] ],      2 := [ [ 0, 0, 0, 0, 0, -1, 0, 0 ], [ 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 0, -1, 0, 0, 0, 0, 0, 0 ], [ 0, -1, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, 0, 0, 0, -1, 1, 0 ], [ -1, 0, 0, 0, 0, 0, 0, 0 ],           [ -1, 0, 0, 0, 1, 0, 0, 0 ], [ 0, 0, -1, 1, 0, 0, 0, 0 ] ],       3 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0 ],           [ 0, 0, -1, 0, 0, -1, 0, 0, 1, 0, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, -1, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, -1, 0 ],           [ 0, 1, 0, 0, 0, 0, -1, 0, 1, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ],           [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       5 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0 ],           [ 0, 0, 0, 1, -1, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0 ],           [ 1, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, -1, 0, 0, 0, 0, -1, 0, 0, 0, 0, 0 ] ],       6 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],           [ 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ],           [ 0, 0, 0, 0, -1, 0, 1, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 1, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 1, 1, 0, -1, 0, 0, 0, 0 ],           [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],           [ 0, -1, 0, 0, 0, 0, 1, 0, 0, 1, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       7 := [ [ 0, 0, 0, 0, -1, 0, 0, 0 ], [ 0, 0, 1, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 1, 0, -1, 0 ],           [ -1, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, -1, 0, 0, 0, 0, -1 ],           [ -1, 0, 0, -1, 0, 0, 0, 0 ], [ 0, -1, 0, 0, 0, -1, 0, 0 ] ],       8 := [ [ 0, 0, 0, 1 ], [ 0, 0, -1, 0 ], [ 0, -1, 0, 0 ], [ 1, 0, 0, 0 ]          ], 9 := [ [ 1 ] ] ),   rec( 0 := [ [ 1 ] ],       1 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      2 := [ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ] ],       3 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       5 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       6 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       7 := [ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ] ],       8 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      9 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ],       1 := [ [ 1, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      2 := [ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ] ],       3 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       5 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       6 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       7 := [ [ 1, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 1, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ] ],       8 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      9 := [ [ 0 ] ] ),   rec( 0 := [ [ 0 ] ],       1 := [ [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ], [ 0, 0, 0, 0 ] ],      2 := [ [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0 ], [ 0, 0, 0, 0, 0, 1, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 1, 0 ], [ 0, 0, 0, 0, 0, 0, 0, 0 ] ],       3 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       4 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ],       5 := [ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],           [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],   

In [533]:
QGNAG_TestRelationsForAllDegrees(block_mats_s_via_pkg, relsGroup, relskG, relsDG);

========================================
Testing degree 0
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 1
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 2
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 3
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 4
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 5
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 6
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 7
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 8
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Testing degree 9
========================================
All simple modules satisfy the defining relations of the group algebra kG, k^G\
 and the Drinfeld double D(G).

========================================
Finished testing all degrees.
========================================

In [534]:
record_data_decomp_nichols := QGNAG_DecompNicholsAlgebra(
    SimplesMn,
    allPairsInG,
    Base_T4,
    block_mats_s_via_pkg
);

[ rec( 0 := 1, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 1, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 1, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 1, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 1 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 1, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 1, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 1, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 1, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 1, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 1, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 1, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 1,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 1, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 1,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 1, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 1, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 1, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 1, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 1, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 0, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ),   rec( 0 := 0, 1 := 0, 2 := 0, 3 := 0, 4 := 0, 5 := 1, 6 := 0, 7 := 0,       8 := 0, 9 := 0 ) ]

In [535]:
QGNAG_RecordListToHTMLTable(record_data_decomp_nichols, true);

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56
0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1
6,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
rec_info_nichols := QGNAG_Decomposition(record_data_decomp_nichols);;

In [537]:
QGNAG_PrintDecomposition(rec_info_nichols);

degree 0 = M1
degree 1 = M36
degree 2 = M41 + M43
degree 3 = M8 + M12 + M16 + M26 + M28
degree 4 = M45 + M47 + M49
degree 5 = M52 + M54 + M56
degree 6 = M3 + M5 + M13 + M17 + M19
degree 7 = M34 + M38
degree 8 = M39
degree 9 = M10

In [538]:
QGNAG_CharacterSummaryLaTeX(rec_info_nichols, SimplesMn, SimpleNames);

\operatorname{Char}(3,\tau_{10}) = M(0,\tau_{00})[0] + M(1,\eta_{3})[1] + M(2,\
\eta_{2})[2] + M(2,\eta_{4})[2] + M(3,\tau_{12})[3] + M(3,\tau_{11})[3] + M(3,\
\rho_{1})[3] + M(3,\chi_{(0,0,1)})[3] + M(3,\chi_{(0,1,1)})[3] + M(4,\eta_{0})\
[4] + M(4,\eta_{2})[4] + M(4,\eta_{4})[4] + M(5,\eta_{1})[5] + M(5,\eta_{3})[5\
] + M(5,\eta_{5})[5] + M(0,\tau_{01})[6] + M(0,\tau_{02})[6] + M(0,\rho_{0})[6\
] + M(0,\chi_{(0,0,0)})[6] + M(0,\chi_{(0,1,0)})[6] + M(1,\eta_{1})[7] + M(1,\
\eta_{5})[7] + M(2,\eta_{0})[8] + M(3,\tau_{10})[9]



==================================================
Degree 0
==================================================
-------------------
Simple M(0,\tau_{00})
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ 1 ] ], [ [ 1 ] ], [ [ 1 ] ],
  [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

==================================================
Degree 1
==================================================
-------------------
Simple M(1,\eta_{3})
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 2
==================================================
-------------------
Simple M(2,\eta_{2})
-------------------

* Weight:
  - g: ( 0 , 2 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ E(3)^2 ] ], [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(2,\eta_{4})
-------------------

* Weight:
  - g: ( 0 , 2 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ E(3) ] ], [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 3
==================================================
-------------------
Simple M(3,\tau_{12})
-------------------

* Weight:
  - g: ( 0 , 3 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ -E(3)^2 ] ], [ [ E(3) ] ],
  [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1
-------------------
Simple M(3,\tau_{11})
-------------------

* Weight:
  - g: ( 0 , 3 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ -E(3) ] ], [ [ E(3)^2 ] ],
  [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1
-------------------
Simple M(3,\rho_{1})
-------------------

* Weight:
  - g: ( 0 , 3 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) ->
[ [ [ 0, 0, -1 ], [ -1, 0, 0 ], [ 0, -1, 0 ] ],
  [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],
  [ [ -1, -1, -1 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],
  [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ -1, -1, -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 0, 1, 0 ], (( 0 , 0 )) ⊗ [ 1, 0, 0 ],
  (( 0 , 0 )) ⊗ [ 0, 0, 1 ] ]

* Dimension: 3
-------------------
Simple M(3,\chi_{(0,0,1)})
-------------------

* Weight:
  - g: ( 1 , 3 )
  - rho: Pcgs([ f1*f2, f3, f4 ]) -> [ [ [ -1 ] ], [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ], (( 0 , 2 )) ⊗ [ 1 ]
 ]

* Dimension: 3
-------------------
Simple M(3,\chi_{(0,1,1)})
-------------------

* Weight:
  - g: ( 1 , 3 )
  - rho: Pcgs([ f1*f2, f3, f4 ]) -> [ [ [ -1 ] ], [ [ -1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ], (( 0 , 2 )) ⊗ [ 1 ]
 ]

* Dimension: 3

==================================================
Degree 4
==================================================
-------------------
Simple M(4,\eta_{0})
-------------------

* Weight:
  - g: ( 0 , 4 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(4,\eta_{2})
-------------------

* Weight:
  - g: ( 0 , 4 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ E(3)^2 ] ], [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(4,\eta_{4})
-------------------

* Weight:
  - g: ( 0 , 4 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ E(3) ] ], [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 5
==================================================
-------------------
Simple M(5,\eta_{1})
-------------------

* Weight:
  - g: ( 0 , 5 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -E(3) ] ], [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(5,\eta_{3})
-------------------

* Weight:
  - g: ( 0 , 5 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(5,\eta_{5})
-------------------

* Weight:
  - g: ( 0 , 5 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -E(3)^2 ] ], [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 6
==================================================
-------------------
Simple M(0,\tau_{01})
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ E(3) ] ], [ [ E(3)^2 ] ],
  [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1
-------------------
Simple M(0,\tau_{02})
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ E(3)^2 ] ], [ [ E(3) ] ],
  [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1
-------------------
Simple M(0,\rho_{0})
-------------------

* Weight:
  - g: ( 0 , 0 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) ->
[ [ [ 0, 0, 1 ], [ 1, 0, 0 ], [ 0, 1, 0 ] ],
  [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ 1, 0, 0 ] ],
  [ [ -1, -1, -1 ], [ 0, 0, 1 ], [ 0, 1, 0 ] ],
  [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ -1, -1, -1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 0, 1, 0 ], (( 0 , 0 )) ⊗ [ 1, 0, 0 ],
  (( 0 , 0 )) ⊗ [ 0, 0, 1 ] ]

* Dimension: 3
-------------------
Simple M(0,\chi_{(0,0,0)})
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f1*f2, f3, f4 ]) -> [ [ [ 1 ] ], [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ], (( 0 , 2 )) ⊗ [ 1 ]
 ]

* Dimension: 3
-------------------
Simple M(0,\chi_{(0,1,0)})
-------------------

* Weight:
  - g: ( 1 , 0 )
  - rho: Pcgs([ f1*f2, f3, f4 ]) -> [ [ [ 1 ] ], [ [ -1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( 0 , 1 )) ⊗ [ 1 ], (( 0 , 2 )) ⊗ [ 1 ]
 ]

* Dimension: 3

==================================================
Degree 7
==================================================
-------------------
Simple M(1,\eta_{1})
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -E(3) ] ], [ [ E(3)^2 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4
-------------------
Simple M(1,\eta_{5})
-------------------

* Weight:
  - g: ( 0 , 1 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ -E(3)^2 ] ], [ [ E(3) ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 8
==================================================
-------------------
Simple M(2,\eta_{0})
-------------------

* Weight:
  - g: ( 0 , 2 )
  - rho: Pcgs([ f1, f2 ]) -> [ [ [ 1 ] ], [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ], (( ζ_3 , 0 )) ⊗ [ 1 ],
  (( 1 , 0 )) ⊗ [ 1 ], (( ζ_3^2 , 0 )) ⊗ [ 1 ] ]

* Dimension: 4

==================================================
Degree 9
==================================================
-------------------
Simple M(3,\tau_{10})
-------------------

* Weight:
  - g: ( 0 , 3 )
  - rho: Pcgs([ f1, f2, f3, f4 ]) -> [ [ [ -1 ] ], [ [ 1 ] ], [ [ 1 ] ],
  [ [ 1 ] ] ]

* Base: [ (( 0 , 0 )) ⊗ [ 1 ] ]

* Dimension: 1

In [539]:
QGNAG_CharacterSummaryToLaTeX( "character_nichols_T4.tex", rec_info_nichols, SimpleNames );

For a fixed simple module $M_s \in \{M_1,M_2,...,M_\theta\}$, the function constructs the multiplicity table
$$
d_{sk}^{\,j}
=
\sum_{i=1}^{n} N_k^{i,s} b_{ij},
\qquad
0\leq j\leq \ell,\quad 1\leq k\leq n.
$$
The table has $\ell+1$ rows and $n$ columns: each row corresponds to a
degree $j$ of $\mathfrak{B}$, while each column corresponds to a simple
module $M_k$.

$$
\begin{array}{ccc}
\texttt{data\_fusion\_rules/data\_parallel} & & \texttt{rec\_info\_nichols} \\
\searrow & & \swarrow \\
& \texttt{data\_graded} & \\
& \downarrow & \\
& \texttt{GradedFusionRulesVector} & \\
& \downarrow & \\
& \epsilon_s
\end{array}
$$

In [540]:
data_graded := QGNAG_AllGradedFusionData( rec_info_nichols, data_parallel);;

## Vectors $\nu_{i,j}$

\begin{array}{c|c|c||c|c|c}
L_i & d_{\min}(L_i) & \text{Shift }(\nu) & L_i & d_{\min}(L_i) & \text{Shift }(\nu) \\ \hline
L(0,\tau_{00}) & -9 & \nu_{1,d}, d=-9,\dots,0 & L(3,\chi_{(1,0,0)}) & -6 & \nu_{29,d}, d=-6,\dots,0 \\ 
L(0,\tau_{12}) & -6 & \nu_{2,d}, d=-6,\dots,0 & L(3,\chi_{(1,0,1)}) & -3 & \nu_{30,d}, d=-3,\dots,0 \\ 
L(0,\tau_{01}) & -3 & \nu_{3,d}, d=-3,\dots,0 & L(3,\chi_{(1,1,0)}) & -6 & \nu_{31,d}, d=-6,\dots,0 \\ 
L(0,\tau_{10}) & 0 & \nu_{4,0} & L(3,\chi_{(1,1,1)}) & -3 & \nu_{32,d}, d=-3,\dots,0 \\ 
L(0,\tau_{02}) & -3 & \nu_{5,d}, d=-3,\dots,0 & L(1,\eta_{0}) & -4 & \nu_{33,d}, d=-4,\dots,0 \\ 
L(0,\tau_{11}) & -6 & \nu_{6,d}, d=-6,\dots,0 & L(1,\eta_{1}) & -1 & \nu_{34,d}, d=-1,\dots,0 \\ 
L(3,\tau_{00}) & 0 & \nu_{7,0} & L(1,\eta_{2}) & -4 & \nu_{35,d}, d=-4,\dots,0 \\ 
L(3,\tau_{12}) & -3 & \nu_{8,d}, d=-3,\dots,0 & L(1,\eta_{3}) & -7 & \nu_{36,d}, d=-7,\dots,0 \\ 
L(3,\tau_{01}) & -6 & \nu_{9,d}, d=-6,\dots,0 & L(1,\eta_{4}) & -4 & \nu_{37,d}, d=-4,\dots,0 \\ 
L(3,\tau_{10}) & -9 & \nu_{10,d}, d=-9,\dots,0 & L(1,\eta_{5}) & -1 & \nu_{38,d}, d=-1,\dots,0 \\ 
L(3,\tau_{02}) & -6 & \nu_{11,d}, d=-6,\dots,0 & L(2,\eta_{0}) & -5 & \nu_{39,d}, d=-5,\dots,0 \\ 
L(3,\tau_{11}) & -3 & \nu_{12,d}, d=-3,\dots,0 & L(2,\eta_{1}) & -2 & \nu_{40,d}, d=-2,\dots,0 \\ 
L(0,\rho_{0}) & -3 & \nu_{13,d}, d=-3,\dots,0 & L(2,\eta_{2}) & -5 & \nu_{41,d}, d=-5,\dots,0 \\ 
L(0,\rho_{1}) & 0 & \nu_{14,0} & L(2,\eta_{3}) & -2 & \nu_{42,d}, d=-2,\dots,0 \\ 
L(3,\rho_{0}) & 0 & \nu_{15,0} & L(2,\eta_{4}) & -5 & \nu_{43,d}, d=-5,\dots,0 \\ 
L(3,\rho_{1}) & -3 & \nu_{16,d}, d=-3,\dots,0 & L(2,\eta_{5}) & -2 & \nu_{44,d}, d=-2,\dots,0 \\ 
L(0,\chi_{(0,0,0)}) & -3 & \nu_{17,d}, d=-3,\dots,0 & L(4,\eta_{0}) & -7 & \nu_{45,d}, d=-7,\dots,0 \\ 
L(0,\chi_{(0,0,1)}) & 0 & \nu_{18,0} & L(4,\eta_{1}) & -4 & \nu_{46,d}, d=-4,\dots,0 \\ 
L(0,\chi_{(0,1,0)}) & -3 & \nu_{19,d}, d=-3,\dots,0 & L(4,\eta_{2}) & -1 & \nu_{47,d}, d=-1,\dots,0 \\ 
L(0,\chi_{(0,1,1)}) & 0 & \nu_{20,0} & L(4,\eta_{3}) & -4 & \nu_{48,d}, d=-4,\dots,0 \\ 
L(0,\chi_{(1,0,0)}) & -3 & \nu_{21,d}, d=-3,\dots,0 & L(4,\eta_{4}) & -1 & \nu_{49,d}, d=-1,\dots,0 \\ 
L(0,\chi_{(1,0,1)}) & -6 & \nu_{22,d}, d=-6,\dots,0 & L(4,\eta_{5}) & -4 & \nu_{50,d}, d=-4,\dots,0 \\ 
L(0,\chi_{(1,1,0)}) & -3 & \nu_{23,d}, d=-3,\dots,0 & L(5,\eta_{0}) & -2 & \nu_{51,d}, d=-2,\dots,0 \\ 
L(0,\chi_{(1,1,1)}) & -6 & \nu_{24,d}, d=-6,\dots,0 & L(5,\eta_{1}) & -5 & \nu_{52,d}, d=-5,\dots,0 \\ 
L(3,\chi_{(0,0,0)}) & 0 & \nu_{25,0} & L(5,\eta_{2}) & -2 & \nu_{53,d}, d=-2,\dots,0 \\ 
L(3,\chi_{(0,0,1)}) & -3 & \nu_{26,d}, d=-3,\dots,0 & L(5,\eta_{3}) & -5 & \nu_{54,d}, d=-5,\dots,0 \\ 
L(3,\chi_{(0,1,0)}) & 0 & \nu_{27,0} & L(5,\eta_{4}) & -2 & \nu_{55,d}, d=-2,\dots,0 \\ 
L(3,\chi_{(0,1,1)}) & -3 & \nu_{28,d}, d=-3,\dots,0 & L(5,\eta_{5}) & -5 & \nu_{56,d}, d=-5,\dots,0 \\ 
\hline
\end{array}

\begin{align*}
\text{Total} &&& \mathbf{248} \\ 
\end{align*}

In [700]:
bijs_by_degree := List( data_record_data_decomp, QGNAG_MultiplicitiesByNegativeDegree );

[ [ rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0 ] ),       rec( ("-6") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0 ] ),       rec( ("-6") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1 ] ),       rec( ("-6") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0 ] ),       rec( ("-3") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [710]:
bijs_by_degree_old:=QGNAG_MultiplicitiesByNegativeDegree(data_record_data_decomp[1]);

[ rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ]

In [1059]:
record_data_decomp := data_record_data_decomp[2];;
degrees            := List( RecNames( record_data_decomp[1] ), Int );;
n_top              := Maximum( degrees );;
bijs_by_degree_new := rec();;
for j in [0 .. n_top] do
    bijs                            := QGNAG_MultiplicitiesAtNegativeDegree( j, record_data_decomp );
    bijs_by_degree_new.(String(-j)) := bijs.(String(-j));
od;
bijs_by_degree_new;

rec( -1 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -2 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -3 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -4 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -5 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -6 := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -7 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -8 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -9 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] )

In [716]:
is_equal := true;
for r in bijs_by_degree_old do
    # Extract the name of the only key in this record
    key := RecNames(r)[1];
    
    # Check if it exists in 'new' and if the values match
    if not IsBound(bijs_by_degree_new.(key)) then
        Print("Key ", key, " is missing in 'new'.\n");
        is_equal := false;
    elif bijs_by_degree_new.(key) <> r.(key) then
        Print("Value for key ", key, " does not match.\n");
        is_equal := false;
    fi;
od;
# Check if 'new' has extra keys that 'old' did not have
if Length(RecNames(bijs_by_degree_new)) <> Length(bijs_by_degree_old) then
    Print("'new' has a different number of keys.\n");
    is_equal := false;
fi;
Print("Are they exactly equal?: ", is_equal, "\n");

Are they exactly equal?: true

true

En esta, hemos creando vectores $v_{j}\in \mathbb{Q}^{\theta}$ con $j=-n_{top}, \dots, -1, 0.$

In [542]:
bijs_shifted   := List( bijs_by_degree, QGNAG_GetShiftedBijs );

[ [ rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0 ] ),       rec( ("-3") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0 ] ),       rec( ("-6") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1 ] ),       rec( ("-3") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0 ] ),       rec( ("-3") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [1208]:
n_top        := Length(RecNames(bijs_by_degree_new))-1;;
zero_vector  := List( bijs_by_degree_new.(0), x -> 0);; # Get a zero vector of the appropriate length.
nonzero_keys := Filtered( RecNames(bijs_by_degree_new), key -> Sum(bijs_by_degree_new.(key)) <> 0 );;
if IsEmpty(nonzero_keys) then # If everything is zero, return the original degree range.
    Print("Error");
fi;
first_nonzero_degree := Maximum( List( nonzero_keys, Int ) );;
shift                := -first_nonzero_degree;; # Translate this degree to zero.
# 3. Initialize the new shifted record and the list of used degrees
shifted      := rec();; 
used_degrees := [];

# 4. Shift all non-zero keys
for key in nonzero_keys do
    degree                       := Int(key);                  # Convert string key to integer
    value                        := bijs_by_degree_new.(key);; # Get the corresponding list
    new_degree                   := degree + shift;;           # Apply the shift
    shifted.(String(new_degree)) := value;;                    # Store the value in the new record using the shifted degree as key
    Add(used_degrees, new_degree);;                            # Keep track of the new degrees used
od;

# Optional: Sort used_degrees if you need them in ascending order
Sort(used_degrees);
remaining_degrees := Filtered([-(n_top) .. 0], d -> not d in used_degrees); # The remaining degrees are filled with zero vectors.
Print(RecNames(shifted), "\n");
for d in remaining_degrees do
    shifted.(String(d)) := zero_vector;
od;
shifted;

[ "0", "-1", "-2", "-3" ]

[ -3, -2, -1, 0 ]

[ -9, -8, -7, -6, -5, -4 ]

rec( -1 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -2 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -3 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -4 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -5 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -6 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -7 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -8 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], -9 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 0 := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] )

In [964]:
bijs_by_degree       := QGNAG_MultiplicitiesByNegativeDegree( record_data_decomp );;
nonzero              := Filtered( bijs_by_degree, r -> Sum(r.(RecNames(r)[1])) <> 0); # Find the non-zero records.
first_nonzero_degree := Maximum(List(nonzero, r -> Int(RecNames(r)[1])));; # Find the non-zero degree closest to zero.
shift                := -first_nonzero_degree; # Translate this degree to zero.
shifted              := [];;
used_degrees         := [];;

[ rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ]

9

In [1285]:
SimpleNames;

[ "M(0,\\tau_{00})", "M(0,\\tau_{12})", "M(0,\\tau_{01})", "M(0,\\tau_{10})",   "M(0,\\tau_{02})", "M(0,\\tau_{11})", "M(3,\\tau_{00})", "M(3,\\tau_{12})",   "M(3,\\tau_{01})", "M(3,\\tau_{10})", "M(3,\\tau_{02})", "M(3,\\tau_{11})",   "M(0,\\rho_{0})", "M(0,\\rho_{1})", "M(3,\\rho_{0})", "M(3,\\rho_{1})",   "M(0,\\chi_{(0,0,0)})", "M(0,\\chi_{(0,0,1)})", "M(0,\\chi_{(0,1,0)})",   "M(0,\\chi_{(0,1,1)})", "M(0,\\chi_{(1,0,0)})", "M(0,\\chi_{(1,0,1)})",   "M(0,\\chi_{(1,1,0)})", "M(0,\\chi_{(1,1,1)})", "M(3,\\chi_{(0,0,0)})",   "M(3,\\chi_{(0,0,1)})", "M(3,\\chi_{(0,1,0)})", "M(3,\\chi_{(0,1,1)})",   "M(3,\\chi_{(1,0,0)})", "M(3,\\chi_{(1,0,1)})", "M(3,\\chi_{(1,1,0)})",   "M(3,\\chi_{(1,1,1)})", "M(1,\\eta_{0})", "M(1,\\eta_{1})",   "M(1,\\eta_{2})", "M(1,\\eta_{3})", "M(1,\\eta_{4})", "M(1,\\eta_{5})",   "M(2,\\eta_{0})", "M(2,\\eta_{1})", "M(2,\\eta_{2})", "M(2,\\eta_{3})",   "M(2,\\eta_{4})", "M(2,\\eta_{5})", "M(4,\\eta_{0})", "M(4,\\eta_{1})",   "M(4,\\eta_{2})", "M(4,\\eta_{3})", "M(4,\\eta_{4})", "M(4,\\eta_{5})",   "M(5,\\eta_{0})", "M(5,\\eta_{1})", "M(5,\\eta_{2})", "M(5,\\eta_{3})",   "M(5,\\eta_{4})", "M(5,\\eta_{5})" ]

In [1312]:
tau;
sigma;

(1,10)(2,6)(3,8)(5,12)(9,11)(13,16)(17,26)(19,28)(21,32)(22,24)(23,30)(29,31)(33,51)(34,41)(35,55)(36,39)(37,53)(38,43)(40,50)(42,48)(44,46)(45,54)(47,52)(49,56)

(2,9)(3,5)(4,7)(6,11)(8,12)(14,15)(18,25)(20,27)(21,23)(22,31)(24,29)(30,32)(33,42)(34,56)(35,40)(36,54)(37,44)(38,52)(39,45)(41,49)(43,47)(46,53)(48,51)(50,55)

In [1502]:
SimpleNamesPermuted:=Permuted(Permuted(SimpleNames, sigma), tau);

[ "M(3,\\tau_{10})", "M(3,\\tau_{02})", "M(3,\\tau_{11})", "M(3,\\tau_{00})",   "M(3,\\tau_{12})", "M(3,\\tau_{01})", "M(0,\\tau_{10})", "M(0,\\tau_{02})",   "M(0,\\tau_{11})", "M(0,\\tau_{00})", "M(0,\\tau_{12})", "M(0,\\tau_{01})",   "M(3,\\rho_{1})", "M(3,\\rho_{0})", "M(0,\\rho_{1})", "M(0,\\rho_{0})",   "M(3,\\chi_{(0,0,1)})", "M(3,\\chi_{(0,0,0)})", "M(3,\\chi_{(0,1,1)})",   "M(3,\\chi_{(0,1,0)})", "M(3,\\chi_{(1,0,1)})", "M(3,\\chi_{(1,0,0)})",   "M(3,\\chi_{(1,1,1)})", "M(3,\\chi_{(1,1,0)})", "M(0,\\chi_{(0,0,1)})",   "M(0,\\chi_{(0,0,0)})", "M(0,\\chi_{(0,1,1)})", "M(0,\\chi_{(0,1,0)})",   "M(0,\\chi_{(1,0,1)})", "M(0,\\chi_{(1,0,0)})", "M(0,\\chi_{(1,1,1)})",   "M(0,\\chi_{(1,1,0)})", "M(4,\\eta_{3})", "M(4,\\eta_{4})",   "M(4,\\eta_{5})", "M(4,\\eta_{0})", "M(4,\\eta_{1})", "M(4,\\eta_{2})",   "M(5,\\eta_{3})", "M(5,\\eta_{4})", "M(5,\\eta_{5})", "M(5,\\eta_{0})",   "M(5,\\eta_{1})", "M(5,\\eta_{2})", "M(1,\\eta_{3})", "M(1,\\eta_{4})",   "M(1,\\eta_{5})", "M(1,\\eta_{0})", "M(1,\\eta_{1})", "M(1,\\eta_{2})",   "M(2,\\eta_{3})", "M(2,\\eta_{4})", "M(2,\\eta_{5})", "M(2,\\eta_{0})",   "M(2,\\eta_{1})", "M(2,\\eta_{2})" ]

In [1376]:
Print(SimpleNamesPermuted);

[ "M(3,\\tau_{10})", "M(3,\\tau_{02})", "M(3,\\tau_{11})", "M(3,\\tau_{00})",
  "M(3,\\tau_{12})", "M(3,\\tau_{01})", "M(0,\\tau_{10})", "M(0,\\tau_{02})",
  "M(0,\\tau_{11})", "M(0,\\tau_{00})", "M(0,\\tau_{12})", "M(0,\\tau_{01})",
  "M(3,\\rho_{1})", "M(3,\\rho_{0})", "M(0,\\rho_{1})", "M(0,\\rho_{0})",
  "M(3,\\chi_{(0,0,1)})", "M(3,\\chi_{(0,0,0)})", "M(3,\\chi_{(0,1,1)})",
  "M(3,\\chi_{(0,1,0)})", "M(3,\\chi_{(1,0,1)})", "M(3,\\chi_{(1,0,0)})",
  "M(3,\\chi_{(1,1,1)})", "M(3,\\chi_{(1,1,0)})", "M(0,\\chi_{(0,0,1)})",
  "M(0,\\chi_{(0,0,0)})", "M(0,\\chi_{(0,1,1)})", "M(0,\\chi_{(0,1,0)})",
  "M(0,\\chi_{(1,0,1)})", "M(0,\\chi_{(1,0,0)})", "M(0,\\chi_{(1,1,1)})",
  "M(0,\\chi_{(1,1,0)})", "M(4,\\eta_{3})", "M(4,\\eta_{4})",
  "M(4,\\eta_{5})", "M(4,\\eta_{0})", "M(4,\\eta_{1})", "M(4,\\eta_{2})",
  "M(5,\\eta_{3})", "M(5,\\eta_{4})", "M(5,\\eta_{5})", "M(5,\\eta_{0})",
  "M(5,\\eta_{1})", "M(5,\\eta_{2})", "M(1,\\eta_{3})", "M(1,\\eta_{4})",
  "M(1,\\eta_{5})", "M(1,\\eta_{0})", "M(1,\\eta_{1})", "M(1,\\eta_{2})",
  "M(2,\\eta_{3})", "M(2,\\eta_{4})", "M(2,\\eta_{5})", "M(2,\\eta_{0})",
  "M(2,\\eta_{1})", "M(2,\\eta_{2})" ]

In [1393]:
# 1. Find the position of each element of the permuted list inside the original list.
# This actually gives us the inverse of the permutation we want.
indices := List( SimpleNamesPermuted, name -> Position( SimpleNames, name ) );;
# 2. Convert the list of indices into a permutation and invert it (^-1)
# to get the permutation 'p' that maps the original list to the permuted one.
perm := PermList( indices )^-1;;

# 3. Check that applying this permutation to the original list yields the permuted list
is_correct := Permuted( SimpleNames, perm ) = SimpleNamesPermuted;

Print("The permutation is: ", perm, "\n");
Print("Is the permutation correct?: ", is_correct, "\n");
Print("The permutation is tau: ", perm=tau, "\n");
Print("The permutation is sigma: ", perm=sigma, "\n");

The permutation is: ( 1,10)( 2,11)( 3,12)( 4, 7)( 5, 8)( 6, 9)(13,16)(14,15)
(17,26)(18,25)(19,28)(20,27)(21,30)(22,29)(23,32)(24,31)(33,48)(34,49)(35,50)
(36,45)(37,46)(38,47)(39,54)(40,55)(41,56)(42,51)(43,52)(44,53)
Is the permutation correct?: true
The permutation is tau: false
The permutation is sigma: false

true

In [1276]:
Print("Computing shifted vectors:\n");
bijs_shifted_permuted := Permuted(bijs_shifted, sigma );
names                 := [];;
theta                 := Length(bijs_shifted);;
for i in [1..theta] do
    Print("----------------------------------------\n");
    nu_ij            := QGNAG_AllShiftLeft( bijs_shifted_permuted[i] );
    number_of_shifts := Length( nu_ij );
    if number_of_shifts = 1 then
        Print(number_of_shifts, "\n");
    else
        Print("d = 0,...,", number_of_shifts-1, "\n");
    fi;
    for j in [0..number_of_shifts-1] do
        if j = 0 then
            nu_j:= Concatenation("\\nu_{", String(i), "}" );
            Add(names, nu_j);
        else
            nu_j:= Concatenation("\\boldsymbol{q}^{-", String(j),"}\\nu_{", String(i), "}" );
            Add(names, nu_j);
        fi;
        Print(nu_j, "\n");
    od;
od;

Computing shifted vectors:
----------------------------------------
d = 0,...,9
\nu_{1}
\boldsymbol{q}^{-1}\nu_{1}
\boldsymbol{q}^{-2}\nu_{1}
\boldsymbol{q}^{-3}\nu_{1}
\boldsymbol{q}^{-4}\nu_{1}
\boldsymbol{q}^{-5}\nu_{1}
\boldsymbol{q}^{-6}\nu_{1}
\boldsymbol{q}^{-7}\nu_{1}
\boldsymbol{q}^{-8}\nu_{1}
\boldsymbol{q}^{-9}\nu_{1}
----------------------------------------
d = 0,...,6
\nu_{2}
\boldsymbol{q}^{-1}\nu_{2}
\boldsymbol{q}^{-2}\nu_{2}
\boldsymbol{q}^{-3}\nu_{2}
\boldsymbol{q}^{-4}\nu_{2}
\boldsymbol{q}^{-5}\nu_{2}
\boldsymbol{q}^{-6}\nu_{2}
----------------------------------------
d = 0,...,3
\nu_{3}
\boldsymbol{q}^{-1}\nu_{3}
\boldsymbol{q}^{-2}\nu_{3}
\boldsymbol{q}^{-3}\nu_{3}
----------------------------------------
1
\nu_{4}
----------------------------------------
d = 0,...,3
\nu_{5}
\boldsymbol{q}^{-1}\nu_{5}
\boldsymbol{q}^{-2}\nu_{5}
\boldsymbol{q}^{-3}\nu_{5}
----------------------------------------
d = 0,...,6
\nu_{6}
\boldsymbol{q}^{-1}\nu_{6}
\boldsymbol{q}^{-2}\nu_{6}
\boldsymbol{q}^{-3}\nu_{6}
\boldsymbol{q}^{-4}\nu_{6}
\boldsymbol{q}^{-5}\nu_{6}
\boldsymbol{q}^{-6}\nu_{6}
----------------------------------------
1
\nu_{7}
----------------------------------------
d = 0,...,3
\nu_{8}
\boldsymbol{q}^{-1}\nu_{8}
\boldsymbol{q}^{-2}\nu_{8}
\boldsymbol{q}^{-3}\nu_{8}
----------------------------------------
d = 0,...,6
\nu_{9}
\boldsymbol{q}^{-1}\nu_{9}
\boldsymbol{q}^{-2}\nu_{9}
\boldsymbol{q}^{-3}\nu_{9}
\boldsymbol{q}^{-4}\nu_{9}
\boldsymbol{q}^{-5}\nu_{9}
\boldsymbol{q}^{-6}\nu_{9}
----------------------------------------
d = 0,...,9
\nu_{10}
\boldsymbol{q}^{-1}\nu_{10}
\boldsymbol{q}^{-2}\nu_{10}
\boldsymbol{q}^{-3}\nu_{10}
\boldsymbol{q}^{-4}\nu_{10}
\boldsymbol{q}^{-5}\nu_{10}
\boldsymbol{q}^{-6}\nu_{10}
\boldsymbol{q}^{-7}\nu_{10}
\boldsymbol{q}^{-8}\nu_{10}
\boldsymbol{q}^{-9}\nu_{10}
----------------------------------------
d = 0,...,6
\nu_{11}
\boldsymbol{q}^{-1}\nu_{11}
\boldsymbol{q}^{-2}\nu_{11}
\boldsymbol{q}^{-3}\nu_{11}
\boldsymbol{q}^{-4}\nu_{11}
\boldsymbol{q}^{-5}\nu_{11}
\boldsymbol{q}^{-6}\nu_{11}
----------------------------------------
d = 0,...,3
\nu_{12}
\boldsymbol{q}^{-1}\nu_{12}
\boldsymbol{q}^{-2}\nu_{12}
\boldsymbol{q}^{-3}\nu_{12}
----------------------------------------
d = 0,...,3
\nu_{13}
\boldsymbol{q}^{-1}\nu_{13}
\boldsymbol{q}^{-2}\nu_{13}
\boldsymbol{q}^{-3}\nu_{13}
----------------------------------------
1
\nu_{14}
----------------------------------------
1
\nu_{15}
----------------------------------------
d = 0,...,3
\nu_{16}
\boldsymbol{q}^{-1}\nu_{16}
\boldsymbol{q}^{-2}\nu_{16}
\boldsymbol{q}^{-3}\nu_{16}
----------------------------------------
d = 0,...,3
\nu_{17}
\boldsymbol{q}^{-1}\nu_{17}
\boldsymbol{q}^{-2}\nu_{17}
\boldsymbol{q}^{-3}\nu_{17}
----------------------------------------
1
\nu_{18}
----------------------------------------
d = 0,...,3
\nu_{19}
\boldsymbol{q}^{-1}\nu_{19}
\boldsymbol{q}^{-2}\nu_{19}
\boldsymbol{q}^{-3}\nu_{19}
----------------------------------------
1
\nu_{20}
----------------------------------------
d = 0,...,3
\nu_{21}
\boldsymbol{q}^{-1}\nu_{21}
\boldsymbol{q}^{-2}\nu_{21}
\boldsymbol{q}^{-3}\nu_{21}
----------------------------------------
d = 0,...,6
\nu_{22}
\boldsymbol{q}^{-1}\nu_{22}
\boldsymbol{q}^{-2}\nu_{22}
\boldsymbol{q}^{-3}\nu_{22}
\boldsymbol{q}^{-4}\nu_{22}
\boldsymbol{q}^{-5}\nu_{22}
\boldsymbol{q}^{-6}\nu_{22}
----------------------------------------
d = 0,...,3
\nu_{23}
\boldsymbol{q}^{-1}\nu_{23}
\boldsymbol{q}^{-2}\nu_{23}
\boldsymbol{q}^{-3}\nu_{23}
----------------------------------------
d = 0,...,6
\nu_{24}
\boldsymbol{q}^{-1}\nu_{24}
\boldsymbol{q}^{-2}\nu_{24}
\boldsymbol{q}^{-3}\nu_{24}
\boldsymbol{q}^{-4}\nu_{24}
\boldsymbol{q}^{-5}\nu_{24}
\boldsymbol{q}^{-6}\nu_{24}
----------------------------------------
1
\nu_{25}
----------------------------------------
d = 0,...,3
\nu_{26}
\boldsymbol{q}^{-1}\nu_{26}
\boldsymbol{q}^{-2}\nu_{26}
\boldsymbol{q}^{-3}\nu_{26}
----------------------------------------
1
\nu_{27}
----------------------------------------
d = 0,...,3
\nu_{28}
\boldsymbol{q}^{-1}\nu_{28}
\boldsymbol{q}^{-2}\nu_{28}
\boldsymbol{q}^{-3}\nu_{28}
----------------------------------------
d = 0,...,6
\nu_{29}
\boldsymbol{q}^{-1}\nu_{29}
\boldsymbol{q}^{-2}\nu_{29}
\boldsymbol{q}^{-3}\nu_{29}
\boldsymbol{q}^{-4}\nu_{29}
\boldsymbol{q}^{-5}\nu_{29}
\boldsymbol{q}^{-6}\nu_{29}
----------------------------------------
d = 0,...,3
\nu_{30}
\boldsymbol{q}^{-1}\nu_{30}
\boldsymbol{q}^{-2}\nu_{30}
\boldsymbol{q}^{-3}\nu_{30}
----------------------------------------
d = 0,...,6
\nu_{31}
\boldsymbol{q}^{-1}\nu_{31}
\boldsymbol{q}^{-2}\nu_{31}
\boldsymbol{q}^{-3}\nu_{31}
\boldsymbol{q}^{-4}\nu_{31}
\boldsymbol{q}^{-5}\nu_{31}
\boldsymbol{q}^{-6}\nu_{31}
----------------------------------------
d = 0,...,3
\nu_{32}
\boldsymbol{q}^{-1}\nu_{32}
\boldsymbol{q}^{-2}\nu_{32}
\boldsymbol{q}^{-3}\nu_{32}
----------------------------------------
d = 0,...,2
\nu_{33}
\boldsymbol{q}^{-1}\nu_{33}
\boldsymbol{q}^{-2}\nu_{33}
----------------------------------------
d = 0,...,5
\nu_{34}
\boldsymbol{q}^{-1}\nu_{34}
\boldsymbol{q}^{-2}\nu_{34}
\boldsymbol{q}^{-3}\nu_{34}
\boldsymbol{q}^{-4}\nu_{34}
\boldsymbol{q}^{-5}\nu_{34}
----------------------------------------
d = 0,...,2
\nu_{35}
\boldsymbol{q}^{-1}\nu_{35}
\boldsymbol{q}^{-2}\nu_{35}
----------------------------------------
d = 0,...,5
\nu_{36}
\boldsymbol{q}^{-1}\nu_{36}
\boldsymbol{q}^{-2}\nu_{36}
\boldsymbol{q}^{-3}\nu_{36}
\boldsymbol{q}^{-4}\nu_{36}
\boldsymbol{q}^{-5}\nu_{36}
----------------------------------------
d = 0,...,2
\nu_{37}
\boldsymbol{q}^{-1}\nu_{37}
\boldsymbol{q}^{-2}\nu_{37}
----------------------------------------
d = 0,...,5
\nu_{38}
\boldsymbol{q}^{-1}\nu_{38}
\boldsymbol{q}^{-2}\nu_{38}
\boldsymbol{q}^{-3}\nu_{38}
\boldsymbol{q}^{-4}\nu_{38}
\boldsymbol{q}^{-5}\nu_{38}
----------------------------------------
d = 0,...,7
\nu_{39}
\boldsymbol{q}^{-1}\nu_{39}
\boldsymbol{q}^{-2}\nu_{39}
\boldsymbol{q}^{-3}\nu_{39}
\boldsymbol{q}^{-4}\nu_{39}
\boldsymbol{q}^{-5}\nu_{39}
\boldsymbol{q}^{-6}\nu_{39}
\boldsymbol{q}^{-7}\nu_{39}
----------------------------------------
d = 0,...,4
\nu_{40}
\boldsymbol{q}^{-1}\nu_{40}
\boldsymbol{q}^{-2}\nu_{40}
\boldsymbol{q}^{-3}\nu_{40}
\boldsymbol{q}^{-4}\nu_{40}
----------------------------------------
d = 0,...,1
\nu_{41}
\boldsymbol{q}^{-1}\nu_{41}
----------------------------------------
d = 0,...,4
\nu_{42}
\boldsymbol{q}^{-1}\nu_{42}
\boldsymbol{q}^{-2}\nu_{42}
\boldsymbol{q}^{-3}\nu_{42}
\boldsymbol{q}^{-4}\nu_{42}
----------------------------------------
d = 0,...,1
\nu_{43}
\boldsymbol{q}^{-1}\nu_{43}
----------------------------------------
d = 0,...,4
\nu_{44}
\boldsymbol{q}^{-1}\nu_{44}
\boldsymbol{q}^{-2}\nu_{44}
\boldsymbol{q}^{-3}\nu_{44}
\boldsymbol{q}^{-4}\nu_{44}
----------------------------------------
d = 0,...,5
\nu_{45}
\boldsymbol{q}^{-1}\nu_{45}
\boldsymbol{q}^{-2}\nu_{45}
\boldsymbol{q}^{-3}\nu_{45}
\boldsymbol{q}^{-4}\nu_{45}
\boldsymbol{q}^{-5}\nu_{45}
----------------------------------------
d = 0,...,2
\nu_{46}
\boldsymbol{q}^{-1}\nu_{46}
\boldsymbol{q}^{-2}\nu_{46}
----------------------------------------
d = 0,...,5
\nu_{47}
\boldsymbol{q}^{-1}\nu_{47}
\boldsymbol{q}^{-2}\nu_{47}
\boldsymbol{q}^{-3}\nu_{47}
\boldsymbol{q}^{-4}\nu_{47}
\boldsymbol{q}^{-5}\nu_{47}
----------------------------------------
d = 0,...,2
\nu_{48}
\boldsymbol{q}^{-1}\nu_{48}
\boldsymbol{q}^{-2}\nu_{48}
----------------------------------------
d = 0,...,5
\nu_{49}
\boldsymbol{q}^{-1}\nu_{49}
\boldsymbol{q}^{-2}\nu_{49}
\boldsymbol{q}^{-3}\nu_{49}
\boldsymbol{q}^{-4}\nu_{49}
\boldsymbol{q}^{-5}\nu_{49}
----------------------------------------
d = 0,...,2
\nu_{50}
\boldsymbol{q}^{-1}\nu_{50}
\boldsymbol{q}^{-2}\nu_{50}
----------------------------------------
d = 0,...,4
\nu_{51}
\boldsymbol{q}^{-1}\nu_{51}
\boldsymbol{q}^{-2}\nu_{51}
\boldsymbol{q}^{-3}\nu_{51}
\boldsymbol{q}^{-4}\nu_{51}
----------------------------------------
d = 0,...,1
\nu_{52}
\boldsymbol{q}^{-1}\nu_{52}
----------------------------------------
d = 0,...,4
\nu_{53}
\boldsymbol{q}^{-1}\nu_{53}
\boldsymbol{q}^{-2}\nu_{53}
\boldsymbol{q}^{-3}\nu_{53}
\boldsymbol{q}^{-4}\nu_{53}
----------------------------------------
d = 0,...,7
\nu_{54}
\boldsymbol{q}^{-1}\nu_{54}
\boldsymbol{q}^{-2}\nu_{54}
\boldsymbol{q}^{-3}\nu_{54}
\boldsymbol{q}^{-4}\nu_{54}
\boldsymbol{q}^{-5}\nu_{54}
\boldsymbol{q}^{-6}\nu_{54}
\boldsymbol{q}^{-7}\nu_{54}
----------------------------------------
d = 0,...,4
\nu_{55}
\boldsymbol{q}^{-1}\nu_{55}
\boldsymbol{q}^{-2}\nu_{55}
\boldsymbol{q}^{-3}\nu_{55}
\boldsymbol{q}^{-4}\nu_{55}
----------------------------------------
d = 0,...,1
\nu_{56}
\boldsymbol{q}^{-1}\nu_{56}

[ [ rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1 ] ),       rec( ("-3") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0 ] ),       rec( ("-3") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0 ] ),       rec( ("-3") := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,               1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0 ] ),       rec( ("-6") := [ 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,               0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,               0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ) ],   [       rec( 0 := [ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-1") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-2") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-3") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-9") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-8") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-7") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-6") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-5") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),       rec( ("-4") := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,               0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [543]:
NuVectorNames := QGNAG_NuNames( bijs_shifted );

[ "\\nu_{1}", "\\boldsymbol{q}^{-1}\\nu_{1}", "\\boldsymbol{q}^{-2}\\nu_{1}",   "\\boldsymbol{q}^{-3}\\nu_{1}", "\\boldsymbol{q}^{-4}\\nu_{1}",   "\\boldsymbol{q}^{-5}\\nu_{1}", "\\boldsymbol{q}^{-6}\\nu_{1}",   "\\boldsymbol{q}^{-7}\\nu_{1}", "\\boldsymbol{q}^{-8}\\nu_{1}",   "\\boldsymbol{q}^{-9}\\nu_{1}", "\\nu_{2}", "\\boldsymbol{q}^{-1}\\nu_{2}",   "\\boldsymbol{q}^{-2}\\nu_{2}", "\\boldsymbol{q}^{-3}\\nu_{2}",   "\\boldsymbol{q}^{-4}\\nu_{2}", "\\boldsymbol{q}^{-5}\\nu_{2}",   "\\boldsymbol{q}^{-6}\\nu_{2}", "\\nu_{3}", "\\boldsymbol{q}^{-1}\\nu_{3}",   "\\boldsymbol{q}^{-2}\\nu_{3}", "\\boldsymbol{q}^{-3}\\nu_{3}", "\\nu_{4}",   "\\nu_{5}", "\\boldsymbol{q}^{-1}\\nu_{5}", "\\boldsymbol{q}^{-2}\\nu_{5}",   "\\boldsymbol{q}^{-3}\\nu_{5}", "\\nu_{6}", "\\boldsymbol{q}^{-1}\\nu_{6}",   "\\boldsymbol{q}^{-2}\\nu_{6}", "\\boldsymbol{q}^{-3}\\nu_{6}",   "\\boldsymbol{q}^{-4}\\nu_{6}", "\\boldsymbol{q}^{-5}\\nu_{6}",   "\\boldsymbol{q}^{-6}\\nu_{6}", "\\nu_{7}", "\\nu_{8}",   "\\boldsymbol{q}^{-1}\\nu_{8}", "\\boldsymbol{q}^{-2}\\nu_{8}",   "\\boldsymbol{q}^{-3}\\nu_{8}", "\\nu_{9}", "\\boldsymbol{q}^{-1}\\nu_{9}",   "\\boldsymbol{q}^{-2}\\nu_{9}", "\\boldsymbol{q}^{-3}\\nu_{9}",   "\\boldsymbol{q}^{-4}\\nu_{9}", "\\boldsymbol{q}^{-5}\\nu_{9}",   "\\boldsymbol{q}^{-6}\\nu_{9}", "\\nu_{10}",   "\\boldsymbol{q}^{-1}\\nu_{10}", "\\boldsymbol{q}^{-2}\\nu_{10}",   "\\boldsymbol{q}^{-3}\\nu_{10}", "\\boldsymbol{q}^{-4}\\nu_{10}",   "\\boldsymbol{q}^{-5}\\nu_{10}", "\\boldsymbol{q}^{-6}\\nu_{10}",   "\\boldsymbol{q}^{-7}\\nu_{10}", "\\boldsymbol{q}^{-8}\\nu_{10}",   "\\boldsymbol{q}^{-9}\\nu_{10}", "\\nu_{11}",   "\\boldsymbol{q}^{-1}\\nu_{11}", "\\boldsymbol{q}^{-2}\\nu_{11}",   "\\boldsymbol{q}^{-3}\\nu_{11}", "\\boldsymbol{q}^{-4}\\nu_{11}",   "\\boldsymbol{q}^{-5}\\nu_{11}", "\\boldsymbol{q}^{-6}\\nu_{11}",   "\\nu_{12}", "\\boldsymbol{q}^{-1}\\nu_{12}",   "\\boldsymbol{q}^{-2}\\nu_{12}", "\\boldsymbol{q}^{-3}\\nu_{12}",   "\\nu_{13}", "\\boldsymbol{q}^{-1}\\nu_{13}",   "\\boldsymbol{q}^{-2}\\nu_{13}", "\\boldsymbol{q}^{-3}\\nu_{13}",   "\\nu_{14}", "\\nu_{15}", "\\nu_{16}", "\\boldsymbol{q}^{-1}\\nu_{16}",   "\\boldsymbol{q}^{-2}\\nu_{16}", "\\boldsymbol{q}^{-3}\\nu_{16}",   "\\nu_{17}", "\\boldsymbol{q}^{-1}\\nu_{17}",   "\\boldsymbol{q}^{-2}\\nu_{17}", "\\boldsymbol{q}^{-3}\\nu_{17}",   "\\nu_{18}", "\\nu_{19}", "\\boldsymbol{q}^{-1}\\nu_{19}",   "\\boldsymbol{q}^{-2}\\nu_{19}", "\\boldsymbol{q}^{-3}\\nu_{19}",   "\\nu_{20}", "\\nu_{21}", "\\boldsymbol{q}^{-1}\\nu_{21}",   "\\boldsymbol{q}^{-2}\\nu_{21}", "\\boldsymbol{q}^{-3}\\nu_{21}",   "\\nu_{22}", "\\boldsymbol{q}^{-1}\\nu_{22}",   "\\boldsymbol{q}^{-2}\\nu_{22}", "\\boldsymbol{q}^{-3}\\nu_{22}",   "\\boldsymbol{q}^{-4}\\nu_{22}", "\\boldsymbol{q}^{-5}\\nu_{22}",   "\\boldsymbol{q}^{-6}\\nu_{22}", "\\nu_{23}",   "\\boldsymbol{q}^{-1}\\nu_{23}", "\\boldsymbol{q}^{-2}\\nu_{23}",   "\\boldsymbol{q}^{-3}\\nu_{23}", "\\nu_{24}",   "\\boldsymbol{q}^{-1}\\nu_{24}", "\\boldsymbol{q}^{-2}\\nu_{24}",   "\\boldsymbol{q}^{-3}\\nu_{24}", "\\boldsymbol{q}^{-4}\\nu_{24}",   "\\boldsymbol{q}^{-5}\\nu_{24}", "\\boldsymbol{q}^{-6}\\nu_{24}",   "\\nu_{25}", "\\nu_{26}", "\\boldsymbol{q}^{-1}\\nu_{26}",   "\\boldsymbol{q}^{-2}\\nu_{26}", "\\boldsymbol{q}^{-3}\\nu_{26}",   "\\nu_{27}", "\\nu_{28}", "\\boldsymbol{q}^{-1}\\nu_{28}",   "\\boldsymbol{q}^{-2}\\nu_{28}", "\\boldsymbol{q}^{-3}\\nu_{28}",   "\\nu_{29}", "\\boldsymbol{q}^{-1}\\nu_{29}",   "\\boldsymbol{q}^{-2}\\nu_{29}", "\\boldsymbol{q}^{-3}\\nu_{29}",   "\\boldsymbol{q}^{-4}\\nu_{29}", "\\boldsymbol{q}^{-5}\\nu_{29}",   "\\boldsymbol{q}^{-6}\\nu_{29}", "\\nu_{30}",   "\\boldsymbol{q}^{-1}\\nu_{30}", "\\boldsymbol{q}^{-2}\\nu_{30}",   "\\boldsymbol{q}^{-3}\\nu_{30}", "\\nu_{31}",   "\\boldsymbol{q}^{-1}\\nu_{31}", "\\boldsymbol{q}^{-2}\\nu_{31}",   "\\boldsymbol{q}^{-3}\\nu_{31}", "\\boldsymbol{q}^{-4}\\nu_{31}",   "\\boldsymbol{q}^{-5}\\nu_{31}", "\\boldsymbol{q}^{-6}\\nu_{31}",   "\\nu_{32}", "\\boldsymbol{q}^{-1}\\nu_{32}",   "\\boldsymbol{q}^{-2}\\nu_{32}", "\\boldsymbol{q}^{-3}\\nu_{32}",   "\\nu_{33}", "\\boldsymbol{q}^{-1}\\nu_{33}",   "\\boldsymbol{q}^{-2}\\nu_{33}", "\\boldsymbol{q}^{-3}\\nu_{33}",   "\\boldsymbol{q}^{-4}\\nu_{33}", "\\nu_{34}",   "\\boldsymbol{q}^{-1}\\nu_{34}", "\\nu_{35}",   "\\boldsymbol{q}^{-1}\\nu_{35}", "\\boldsymbol{q}^{-2}\\nu_{35}",   "\\boldsymbol{q}^{-3}\\nu_{35}", "\\boldsymbol{q}^{-4}\\nu_{35}",   "\\nu_{36}", "\\boldsymbol{q}^{-1}\\nu_{36}",   "\\boldsymbol{q}^{-2}\\nu_{36}", "\\boldsymbol{q}^{-3}\\nu_{36}",   "\\boldsymbol{q}^{-4}\\nu_{36}", "\\boldsymbol{q}^{-5}\\nu_{36}",   "\\boldsymbol{q}^{-6}\\nu_{36}", "\\boldsymbol{q}^{-7}\\nu_{36}",   "\\nu_{37}", "\\boldsymbol{q}^{-1}\\nu_{37}",   "\\boldsymbol{q}^{-2}\\nu_{37}", "\\boldsymbol{q}^{-3}\\nu_{37}",   "\\boldsymbol{q}^{-4}\\nu_{37}", "\\nu_{38}",   "\\boldsymbol{q}^{-1}\\nu_{38}", "\\nu_{39}",   "\\boldsymbol{q}^{-1}\\nu_{39}", "\\boldsymbol{q}^{-2}\\nu_{39}",   "\\boldsymbol{q}^{-3}\\nu_{39}", "\\boldsymbol{q}^{-4}\\nu_{39}",   "\\boldsymbol{q}^{-5}\\nu_{39}", "\\nu_{40}",   "\\boldsymbol{q}^{-1}\\nu_{40}", "\\boldsymbol{q}^{-2}\\nu_{40}",   "\\nu_{41}", "\\boldsymbol{q}^{-1}\\nu_{41}",   "\\boldsymbol{q}^{-2}\\nu_{41}", "\\boldsymbol{q}^{-3}\\nu_{41}",   "\\boldsymbol{q}^{-4}\\nu_{41}", "\\boldsymbol{q}^{-5}\\nu_{41}",   "\\nu_{42}", "\\boldsymbol{q}^{-1}\\nu_{42}",   "\\boldsymbol{q}^{-2}\\nu_{42}", "\\nu_{43}",   "\\boldsymbol{q}^{-1}\\nu_{43}", "\\boldsymbol{q}^{-2}\\nu_{43}",   "\\boldsymbol{q}^{-3}\\nu_{43}", "\\boldsymbol{q}^{-4}\\nu_{43}",   "\\boldsymbol{q}^{-5}\\nu_{43}", "\\nu_{44}",   "\\boldsymbol{q}^{-1}\\nu_{44}", "\\boldsymbol{q}^{-2}\\nu_{44}",   "\\nu_{45}", "\\boldsymbol{q}^{-1}\\nu_{45}",   "\\boldsymbol{q}^{-2}\\nu_{45}", "\\boldsymbol{q}^{-3}\\nu_{45}",   "\\boldsymbol{q}^{-4}\\nu_{45}", "\\boldsymbol{q}^{-5}\\nu_{45}",   "\\boldsymbol{q}^{-6}\\nu_{45}", "\\boldsymbol{q}^{-7}\\nu_{45}",   "\\nu_{46}", "\\boldsymbol{q}^{-1}\\nu_{46}",   "\\boldsymbol{q}^{-2}\\nu_{46}", "\\boldsymbol{q}^{-3}\\nu_{46}",   "\\boldsymbol{q}^{-4}\\nu_{46}", "\\nu_{47}",   "\\boldsymbol{q}^{-1}\\nu_{47}", "\\nu_{48}",   "\\boldsymbol{q}^{-1}\\nu_{48}", "\\boldsymbol{q}^{-2}\\nu_{48}",   "\\boldsymbol{q}^{-3}\\nu_{48}", "\\boldsymbol{q}^{-4}\\nu_{48}",   "\\nu_{49}", "\\boldsymbol{q}^{-1}\\nu_{49}", "\\nu_{50}",   "\\boldsymbol{q}^{-1}\\nu_{50}", "\\boldsymbol{q}^{-2}\\nu_{50}",   "\\boldsymbol{q}^{-3}\\nu_{50}", "\\boldsymbol{q}^{-4}\\nu_{50}",   "\\nu_{51}", "\\boldsymbol{q}^{-1}\\nu_{51}",   "\\boldsymbol{q}^{-2}\\nu_{51}", "\\nu_{52}",   "\\boldsymbol{q}^{-1}\\nu_{52}", "\\boldsymbol{q}^{-2}\\nu_{52}",   "\\boldsymbol{q}^{-3}\\nu_{52}", "\\boldsymbol{q}^{-4}\\nu_{52}",   "\\boldsymbol{q}^{-5}\\nu_{52}", "\\nu_{53}",   "\\boldsymbol{q}^{-1}\\nu_{53}", "\\boldsymbol{q}^{-2}\\nu_{53}",   "\\nu_{54}", "\\boldsymbol{q}^{-1}\\nu_{54}",   "\\boldsymbol{q}^{-2}\\nu_{54}", "\\boldsymbol{q}^{-3}\\nu_{54}",   "\\boldsymbol{q}^{-4}\\nu_{54}", "\\boldsymbol{q}^{-5}\\nu_{54}",   "\\nu_{55}", "\\boldsymbol{q}^{-1}\\nu_{55}",   "\\boldsymbol{q}^{-2}\\nu_{55}", "\\nu_{56}",   "\\boldsymbol{q}^{-1}\\nu_{56}", "\\boldsymbol{q}^{-2}\\nu_{56}",   "\\boldsymbol{q}^{-3}\\nu_{56}", "\\boldsymbol{q}^{-4}\\nu_{56}",   "\\boldsymbol{q}^{-5}\\nu_{56}" ]

In [544]:
nu := QGNAG_AllShiftLeftAsVector(data_record_data_decomp);

Computing shifted vectors:
----------------------------------------
j = 1 / 56
  L = L1
d_min = 0
shifts = 10
  total vectors = 10
----------------------------------------
j = 2 / 56
  L = L2
d_min = -3
shifts = 7
  total vectors = 17
----------------------------------------
j = 3 / 56
  L = L3
d_min = -6
shifts = 4
  total vectors = 21
----------------------------------------
j = 4 / 56
  L = L4
d_min = -9
shifts = 1
  total vectors = 22
----------------------------------------
j = 5 / 56
  L = L5
d_min = -6
shifts = 4
  total vectors = 26
----------------------------------------
j = 6 / 56
  L = L6
d_min = -3
shifts = 7
  total vectors = 33
----------------------------------------
j = 7 / 56
  L = L7
d_min = -9
shifts = 1
  total vectors = 34
----------------------------------------
j = 8 / 56
  L = L8
d_min = -6
shifts = 4
  total vectors = 38
----------------------------------------
j = 9 / 56
  L = L9
d_min = -3
shifts = 7
  total vectors = 45
----------------------------------------
j = 10 / 56
  L = L10
d_min = 0
shifts = 10
  total vectors = 55
----------------------------------------
j = 11 / 56
  L = L11
d_min = -3
shifts = 7
  total vectors = 62
----------------------------------------
j = 12 / 56
  L = L12
d_min = -6
shifts = 4
  total vectors = 66
----------------------------------------
j = 13 / 56
  L = L13
d_min = -6
shifts = 4
  total vectors = 70
----------------------------------------
j = 14 / 56
  L = L14
d_min = -9
shifts = 1
  total vectors = 71
----------------------------------------
j = 15 / 56
  L = L15
d_min = -9
shifts = 1
  total vectors = 72
----------------------------------------
j = 16 / 56
  L = L16
d_min = -6
shifts = 4
  total vectors = 76
----------------------------------------
j = 17 / 56
  L = L17
d_min = -6
shifts = 4
  total vectors = 80
----------------------------------------
j = 18 / 56
  L = L18
d_min = -9
shifts = 1
  total vectors = 81
----------------------------------------
j = 19 / 56
  L = L19
d_min = -6
shifts = 4
  total vectors = 85
----------------------------------------
j = 20 / 56
  L = L20
d_min = -9
shifts = 1
  total vectors = 86
----------------------------------------
j = 21 / 56
  L = L21
d_min = -6
shifts = 4
  total vectors = 90
----------------------------------------
j = 22 / 56
  L = L22
d_min = -3
shifts = 7
  total vectors = 97
----------------------------------------
j = 23 / 56
  L = L23
d_min = -6
shifts = 4
  total vectors = 101
----------------------------------------
j = 24 / 56
  L = L24
d_min = -3
shifts = 7
  total vectors = 108
----------------------------------------
j = 25 / 56
  L = L25
d_min = -9
shifts = 1
  total vectors = 109
----------------------------------------
j = 26 / 56
  L = L26
d_min = -6
shifts = 4
  total vectors = 113
----------------------------------------
j = 27 / 56
  L = L27
d_min = -9
shifts = 1
  total vectors = 114
----------------------------------------
j = 28 / 56
  L = L28
d_min = -6
shifts = 4
  total vectors = 118
----------------------------------------
j = 29 / 56
  L = L29
d_min = -3
shifts = 7
  total vectors = 125
----------------------------------------
j = 30 / 56
  L = L30
d_min = -6
shifts = 4
  total vectors = 129
----------------------------------------
j = 31 / 56
  L = L31
d_min = -3
shifts = 7
  total vectors = 136
----------------------------------------
j = 32 / 56
  L = L32
d_min = -6
shifts = 4
  total vectors = 140
----------------------------------------
j = 33 / 56
  L = L33
d_min = -7
shifts = 3
  total vectors = 143
----------------------------------------
j = 34 / 56
  L = L34
d_min = -4
shifts = 6
  total vectors = 149
----------------------------------------
j = 35 / 56
  L = L35
d_min = -7
shifts = 3
  total vectors = 152
----------------------------------------
j = 36 / 56
  L = L36
d_min = -4
shifts = 6
  total vectors = 158
----------------------------------------
j = 37 / 56
  L = L37
d_min = -7
shifts = 3
  total vectors = 161
----------------------------------------
j = 38 / 56
  L = L38
d_min = -4
shifts = 6
  total vectors = 167
----------------------------------------
j = 39 / 56
  L = L39
d_min = -2
shifts = 8
  total vectors = 175
----------------------------------------
j = 40 / 56
  L = L40
d_min = -5
shifts = 5
  total vectors = 180
----------------------------------------
j = 41 / 56
  L = L41
d_min = -8
shifts = 2
  total vectors = 182
----------------------------------------
j = 42 / 56
  L = L42
d_min = -5
shifts = 5
  total vectors = 187
----------------------------------------
j = 43 / 56
  L = L43
d_min = -8
shifts = 2
  total vectors = 189
----------------------------------------
j = 44 / 56
  L = L44
d_min = -5
shifts = 5
  total vectors = 194
----------------------------------------
j = 45 / 56
  L = L45
d_min = -4
shifts = 6
  total vectors = 200
----------------------------------------
j = 46 / 56
  L = L46
d_min = -7
shifts = 3
  total vectors = 203
----------------------------------------
j = 47 / 56
  L = L47
d_min = -4
shifts = 6
  total vectors = 209
----------------------------------------
j = 48 / 56
  L = L48
d_min = -7
shifts = 3
  total vectors = 212
----------------------------------------
j = 49 / 56
  L = L49
d_min = -4
shifts = 6
  total vectors = 218
----------------------------------------
j = 50 / 56
  L = L50
d_min = -7
shifts = 3
  total vectors = 221
----------------------------------------
j = 51 / 56
  L = L51
d_min = -5
shifts = 5
  total vectors = 226
----------------------------------------
j = 52 / 56
  L = L52
d_min = -8
shifts = 2
  total vectors = 228
----------------------------------------
j = 53 / 56
  L = L53
d_min = -5
shifts = 5
  total vectors = 233
----------------------------------------
j = 54 / 56
  L = L54
d_min = -2
shifts = 8
  total vectors = 241
----------------------------------------
j = 55 / 56
  L = L55
d_min = -5
shifts = 5
  total vectors = 246
----------------------------------------
j = 56 / 56
  L = L56
d_min = -8
shifts = 2
  total vectors = 248
----------------------------------------
Finished. Total number of vectors = 248

[ [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0 ],   [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [546]:
QGNAG_LoadNuTableToLaTeX( "nu_table_pos.tex", data_record_data_decomp, SimpleNames, 1 );
QGNAG_LoadNuTableToLaTeX( "nu_table_neg.tex", data_record_data_decomp, SimpleNames, 1 );

For each simple module $L_i$, let $d_{\min}(L_i)$ be the minimum
degree in which $L_i$ occurs. We consider the shifted vectors
$$
\nu_{i,d},
\qquad
d=0,\ldots,\ell-d_{\min}(L_i),
$$

where $\nu_{i,d}$ is placed in the global graded space at degree $d_{\min}(L_i)+d.$
Thus, the collection of shifted vectors is determined by the minimum
degrees $d_{\min}(L_i)$, rather than by a common range
$d=0,\ldots,\ell$. In the present case, the total number of shifted
vectors is
$$
\sum_{i=1}^{\theta}\bigl(\ell-d_{\min}(L_i)+1\bigr)=N_\theta.
$$

For each $s$, let $\epsilon_s$ be the graded fusion vector. We express
it as a linear combination of the shifted vectors:
$$\epsilon_s=\sum_{i=1}^{\theta}\sum_{d=0}^{\ell-d_{\min}(L_i)}c_{i,d}^{(s)}\,\nu_{i,d}.$$

Equivalently, if $A$ is the matrix whose columns are the shifted
vectors $\nu_{i,d}$, we solve $A\,c^{(s)}=\epsilon_s,$ where $c^{(s)}$ is the vector of coefficients $c_{i,d}^{(s)}$.

The consistency of the system is checked by
$\operatorname{rank}(A)=\operatorname{rank}(A\mid\epsilon_s).$
Hence $\epsilon_s$ belongs to the span of the shifted vectors, and the
coefficients are obtained by solving the corresponding linear system.

**Theorem:** $\{ v_{j,l} \} = \mathcal{B}$ is a basis of..

Going for $V_i = \text{Verma}(S_i)$, with $i=1,\dots,\theta$.

- Formula modified as requested (increasing graduation)

$$ \operatorname{char} V_i = \sum_{j=1}^\theta \sum_{l=0}^{n_{top}} S_j[-l] $$

- Note: the sum is structured to account for the degrees $0, -1, \dots, -n_{top}$. To express it strictly in increasing order of degrees, it can be equivalently written as $\sum_{l=-n_{\top}}^{0} S_j[l]$.

Notes from this section on the whiteboard:

- Arrow pointing to $e_{j,l}$ indicating: $``New''$ data

$$ \mathcal{E}_i = ( e_{1,-n_{top}}, \dots, e_{\theta,-n_{top}}, \dots, e_{1,0}, e_{2,0}, \dots, e_{\theta,0} ) $$

Here:
$$ e_{j,l} = \sum_{p} N_j^{p_i} b_{p,l} \quad \text{(\textit{Immed. previous task})} $$

$$
\fbox{
    $b_{p,l} = \text{mult of } S_p \text{ in } \mathfrak{B}^{l}(V)$
}
$$

If $B(V) = \bigoplus_{p,k} S_p[k] \implies V_i = B \otimes S_i$
\begin{align*}
V_i &= \bigoplus_{p,k} S_p^{\oplus b_{p,k}}[k] \\
    &= \bigoplus_{p,k} \bigoplus_{q} (S_q)^{\oplus N_q^{p_i} b_{p,k}}[k] \\
    &= \bigoplus_{q,k} \underbrace{\left( \sum_p N_q^{p_i} b_{p,k} \right)}_{e_{q,k}} S_q[k]
\end{align*}


$\theta(n_{\top}+1)$ vectors in $\mathbb{Q}^{\theta(n_{\top}+1)}$


Goal: Calculate the coordinates of $\mathcal{E}_i$ in the basis $\mathcal{B}$:
$$ \mathcal{E}_i = \sum_{j,l} f_{j,l}^i v_{j,l} $$

In [553]:
index_s:=4;;
data_graded;;
theta     := Length(data_graded);;
ell       := Maximum(List(RecNames(data_graded[1][1]), Int));;
epsilon := [];;
for index_j in [ell, ell-1..0] do
    Print(index_j);
    for index_k in [1 .. theta] do
        Add( epsilon, data_graded[index_s][index_k].(String(index_j)) );
    od;
od;
if RankMat(TransposedMat(nu)) = RankMat( TransposedMat( Concatenation(nu, [epsilon]) ) ) then
    coefficients := SolutionMat( nu, epsilon );;
    Print("\n", coefficients, "\n");
fi;

9876543210
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

In [557]:
data_graded;;
theta := Length(data_graded);;
ell   := Maximum(List(RecNames(data_graded[1][1]), Int));;

for index_s in [1..theta] do
    # Reset epsilon once per index_s (so it collects all degrees j)
    epsilon := []; 
    
    for index_j in [ell, ell-1..0] do
        for index_k in [1 .. theta] do
            Add( epsilon, data_graded[index_s][index_k].(String(index_j)) );
        od;
    od;    

    # epsilon now has length 560, matching the column dimension of nu
    if RankMat(nu) = RankMat( Concatenation(nu, [epsilon]) ) then
        coefficients := SolutionMat( nu, epsilon );;
        Print("Solution found at index_s: ", index_s, "\n");
        Print(coefficients, "\n\n");
    fi;
od;

Solution found at index_s: 1
[ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 2
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 3
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 4
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 5
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 6
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 7
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 8
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 9
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 10
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 11
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 12
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 13
[ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
  1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 14
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 15
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 16
[ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 17
[ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 18
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 19
[ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 20
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 21
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 22
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 23
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 24
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
  0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 25
[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

Solution found at index_s: 26
[ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [557]:
QGNAG_RepresentTheVermaModuleCharacter:=function( index_s, data_graded )
    local epsilon,
          index_j,
          index_k,
          theta,
          n_top;

    theta   := Length( data_graded );
    n_top   := Maximum( List( RecNames( data_graded[1][1] ), Int ) );
    epsilon := [];
    for index_j in [n_top, n_top-1..0] do
        for index_k in [1 .. theta] do
            Add( epsilon, data_graded[index_s][index_k].(String(index_j)) );
        od;
    od;
    return epsilon;
end;

Error, Variable: 'QGNAG_RepresentTheVermaModuleCharacter' is read only
not in any function at stream:17

In [559]:
index_s   := 1;;
epsilon_1 := QGNAG_RepresentTheVermaModuleCharacter(index_s, data_graded);

[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,   0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,   0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,   0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,   0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]

In [567]:
epsilon_and_coeffs:=QGNAG_VermaModuleCharactersAndCoefficients( data_graded, nu );

[ rec( coefficients := [ 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,           0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,           0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,           0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,           0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,           0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,           0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,           1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],       vector := [ 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,           0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] ),   rec( coefficients := [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,           0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,           0, 0, 0

In [1325]:
QGNAG_PrintQP(epsilon_and_coeffs[4].coefficients, QGNAG_NuNames( Permuted(bijs_shifted, sigma )));;

\epsilon = \nu_{4}

$\epsilon = \nu_{1} + \boldsymbol{q}^{-9}\nu_{10} + \boldsymbol{q}^{-1}\nu_{36} + \boldsymbol{q}^{-4}\nu_{45}$

$$\epsilon_1 = \nu_{1} + \boldsymbol{q}^{-9}\nu_{10} + \boldsymbol{q}^{-1}\nu_{36} + \boldsymbol{q}^{-4}\nu_{45}$$

In [1531]:
QGNAG_EpsilonToLaTeX := function(index_s, epsilon_and_coeffs, nu_names)
    local terms, coeffs, i, c, s, result;

    terms := [];

    coeffs := epsilon_and_coeffs[index_s].coefficients;

    for i in [1 .. Length(coeffs)] do
        c := coeffs[i];

        if c <> 0 then

            if c = 1 then
                s := nu_names[i];

            elif c = -1 then
                s := Concatenation("-", nu_names[i]);

            else
                s := Concatenation(String(c), " ", nu_names[i]);
            fi;

            Add(terms, s);
        fi;
    od;

    if Length(terms) = 0 then
        result := StringFormatted("\\epsilon_{{{}}} = 0", index_s);
    else
        result := StringFormatted("\\epsilon_{{{}}} = ", index_s);

        for i in [1 .. Length(terms)] do

            if i = 1 then
                result := Concatenation(result, terms[i]);

            else
                if terms[i][1] = '-' then
                    result := Concatenation(
                        result,
                        " - ",
                        terms[i]{[2 .. Length(terms[i])]}
                    );
                else
                    result := Concatenation(result, " + ", terms[i]);
                fi;
            fi;

        od;
    fi;

    return result;
end;;

In [1538]:
names;

[ "\\nu_{1}", "\\boldsymbol{q}^{-1}\\nu_{1}", "\\boldsymbol{q}^{-2}\\nu_{1}",   "\\boldsymbol{q}^{-3}\\nu_{1}", "\\boldsymbol{q}^{-4}\\nu_{1}",   "\\boldsymbol{q}^{-5}\\nu_{1}", "\\boldsymbol{q}^{-6}\\nu_{1}",   "\\boldsymbol{q}^{-7}\\nu_{1}", "\\boldsymbol{q}^{-8}\\nu_{1}",   "\\boldsymbol{q}^{-9}\\nu_{1}", "\\nu_{2}", "\\boldsymbol{q}^{-1}\\nu_{2}",   "\\boldsymbol{q}^{-2}\\nu_{2}", "\\boldsymbol{q}^{-3}\\nu_{2}",   "\\boldsymbol{q}^{-4}\\nu_{2}", "\\boldsymbol{q}^{-5}\\nu_{2}",   "\\boldsymbol{q}^{-6}\\nu_{2}", "\\nu_{3}", "\\boldsymbol{q}^{-1}\\nu_{3}",   "\\boldsymbol{q}^{-2}\\nu_{3}", "\\boldsymbol{q}^{-3}\\nu_{3}", "\\nu_{4}",   "\\nu_{5}", "\\boldsymbol{q}^{-1}\\nu_{5}", "\\boldsymbol{q}^{-2}\\nu_{5}",   "\\boldsymbol{q}^{-3}\\nu_{5}", "\\nu_{6}", "\\boldsymbol{q}^{-1}\\nu_{6}",   "\\boldsymbol{q}^{-2}\\nu_{6}", "\\boldsymbol{q}^{-3}\\nu_{6}",   "\\boldsymbol{q}^{-4}\\nu_{6}", "\\boldsymbol{q}^{-5}\\nu_{6}",   "\\boldsymbol{q}^{-6}\\nu_{6}", "\\nu_{7}", "\\nu_{8}",   "\\boldsymbol{q}^{-1}\\nu_{8}", "\\boldsymbol{q}^{-2}\\nu_{8}",   "\\boldsymbol{q}^{-3}\\nu_{8}", "\\nu_{9}", "\\boldsymbol{q}^{-1}\\nu_{9}",   "\\boldsymbol{q}^{-2}\\nu_{9}", "\\boldsymbol{q}^{-3}\\nu_{9}",   "\\boldsymbol{q}^{-4}\\nu_{9}", "\\boldsymbol{q}^{-5}\\nu_{9}",   "\\boldsymbol{q}^{-6}\\nu_{9}", "\\nu_{10}",   "\\boldsymbol{q}^{-1}\\nu_{10}", "\\boldsymbol{q}^{-2}\\nu_{10}",   "\\boldsymbol{q}^{-3}\\nu_{10}", "\\boldsymbol{q}^{-4}\\nu_{10}",   "\\boldsymbol{q}^{-5}\\nu_{10}", "\\boldsymbol{q}^{-6}\\nu_{10}",   "\\boldsymbol{q}^{-7}\\nu_{10}", "\\boldsymbol{q}^{-8}\\nu_{10}",   "\\boldsymbol{q}^{-9}\\nu_{10}", "\\nu_{11}",   "\\boldsymbol{q}^{-1}\\nu_{11}", "\\boldsymbol{q}^{-2}\\nu_{11}",   "\\boldsymbol{q}^{-3}\\nu_{11}", "\\boldsymbol{q}^{-4}\\nu_{11}",   "\\boldsymbol{q}^{-5}\\nu_{11}", "\\boldsymbol{q}^{-6}\\nu_{11}",   "\\nu_{12}", "\\boldsymbol{q}^{-1}\\nu_{12}",   "\\boldsymbol{q}^{-2}\\nu_{12}", "\\boldsymbol{q}^{-3}\\nu_{12}",   "\\nu_{13}", "\\boldsymbol{q}^{-1}\\nu_{13}",   "\\boldsymbol{q}^{-2}\\nu_{13}", "\\boldsymbol{q}^{-3}\\nu_{13}",   "\\nu_{14}", "\\nu_{15}", "\\nu_{16}", "\\boldsymbol{q}^{-1}\\nu_{16}",   "\\boldsymbol{q}^{-2}\\nu_{16}", "\\boldsymbol{q}^{-3}\\nu_{16}",   "\\nu_{17}", "\\boldsymbol{q}^{-1}\\nu_{17}",   "\\boldsymbol{q}^{-2}\\nu_{17}", "\\boldsymbol{q}^{-3}\\nu_{17}",   "\\nu_{18}", "\\nu_{19}", "\\boldsymbol{q}^{-1}\\nu_{19}",   "\\boldsymbol{q}^{-2}\\nu_{19}", "\\boldsymbol{q}^{-3}\\nu_{19}",   "\\nu_{20}", "\\nu_{21}", "\\boldsymbol{q}^{-1}\\nu_{21}",   "\\boldsymbol{q}^{-2}\\nu_{21}", "\\boldsymbol{q}^{-3}\\nu_{21}",   "\\nu_{22}", "\\boldsymbol{q}^{-1}\\nu_{22}",   "\\boldsymbol{q}^{-2}\\nu_{22}", "\\boldsymbol{q}^{-3}\\nu_{22}",   "\\boldsymbol{q}^{-4}\\nu_{22}", "\\boldsymbol{q}^{-5}\\nu_{22}",   "\\boldsymbol{q}^{-6}\\nu_{22}", "\\nu_{23}",   "\\boldsymbol{q}^{-1}\\nu_{23}", "\\boldsymbol{q}^{-2}\\nu_{23}",   "\\boldsymbol{q}^{-3}\\nu_{23}", "\\nu_{24}",   "\\boldsymbol{q}^{-1}\\nu_{24}", "\\boldsymbol{q}^{-2}\\nu_{24}",   "\\boldsymbol{q}^{-3}\\nu_{24}", "\\boldsymbol{q}^{-4}\\nu_{24}",   "\\boldsymbol{q}^{-5}\\nu_{24}", "\\boldsymbol{q}^{-6}\\nu_{24}",   "\\nu_{25}", "\\nu_{26}", "\\boldsymbol{q}^{-1}\\nu_{26}",   "\\boldsymbol{q}^{-2}\\nu_{26}", "\\boldsymbol{q}^{-3}\\nu_{26}",   "\\nu_{27}", "\\nu_{28}", "\\boldsymbol{q}^{-1}\\nu_{28}",   "\\boldsymbol{q}^{-2}\\nu_{28}", "\\boldsymbol{q}^{-3}\\nu_{28}",   "\\nu_{29}", "\\boldsymbol{q}^{-1}\\nu_{29}",   "\\boldsymbol{q}^{-2}\\nu_{29}", "\\boldsymbol{q}^{-3}\\nu_{29}",   "\\boldsymbol{q}^{-4}\\nu_{29}", "\\boldsymbol{q}^{-5}\\nu_{29}",   "\\boldsymbol{q}^{-6}\\nu_{29}", "\\nu_{30}",   "\\boldsymbol{q}^{-1}\\nu_{30}", "\\boldsymbol{q}^{-2}\\nu_{30}",   "\\boldsymbol{q}^{-3}\\nu_{30}", "\\nu_{31}",   "\\boldsymbol{q}^{-1}\\nu_{31}", "\\boldsymbol{q}^{-2}\\nu_{31}",   "\\boldsymbol{q}^{-3}\\nu_{31}", "\\boldsymbol{q}^{-4}\\nu_{31}",   "\\boldsymbol{q}^{-5}\\nu_{31}", "\\boldsymbol{q}^{-6}\\nu_{31}",   "\\nu_{32}", "\\boldsymbol{q}^{-1}\\nu_{32}",   "\\boldsymbol{q}^{-2}\\nu_{32}", "\\boldsymbol{q}^{-3}\\nu_{32}",   "\\nu_{33}", "\\boldsymbol{q}^{-1}\\nu_{33}",   "\\boldsymbol{q}^{-2}\\nu_{33}", "\\nu_{34}",   "\\boldsymbol{q}^{-1}\\nu_{34}", "\\boldsymbol{q}^{-2}\\nu_{34}",   "\\boldsymbol{q}^{-3}\\nu_{34}", "\\boldsymbol{q}^{-4}\\nu_{34}",   "\\boldsymbol{q}^{-5}\\nu_{34}", "\\nu_{35}",   "\\boldsymbol{q}^{-1}\\nu_{35}", "\\boldsymbol{q}^{-2}\\nu_{35}",   "\\nu_{36}", "\\boldsymbol{q}^{-1}\\nu_{36}",   "\\boldsymbol{q}^{-2}\\nu_{36}", "\\boldsymbol{q}^{-3}\\nu_{36}",   "\\boldsymbol{q}^{-4}\\nu_{36}", "\\boldsymbol{q}^{-5}\\nu_{36}",   "\\nu_{37}", "\\boldsymbol{q}^{-1}\\nu_{37}",   "\\boldsymbol{q}^{-2}\\nu_{37}", "\\nu_{38}",   "\\boldsymbol{q}^{-1}\\nu_{38}", "\\boldsymbol{q}^{-2}\\nu_{38}",   "\\boldsymbol{q}^{-3}\\nu_{38}", "\\boldsymbol{q}^{-4}\\nu_{38}",   "\\boldsymbol{q}^{-5}\\nu_{38}", "\\nu_{39}",   "\\boldsymbol{q}^{-1}\\nu_{39}", "\\boldsymbol{q}^{-2}\\nu_{39}",   "\\boldsymbol{q}^{-3}\\nu_{39}", "\\boldsymbol{q}^{-4}\\nu_{39}",   "\\boldsymbol{q}^{-5}\\nu_{39}", "\\boldsymbol{q}^{-6}\\nu_{39}",   "\\boldsymbol{q}^{-7}\\nu_{39}", "\\nu_{40}",   "\\boldsymbol{q}^{-1}\\nu_{40}", "\\boldsymbol{q}^{-2}\\nu_{40}",   "\\boldsymbol{q}^{-3}\\nu_{40}", "\\boldsymbol{q}^{-4}\\nu_{40}",   "\\nu_{41}", "\\boldsymbol{q}^{-1}\\nu_{41}", "\\nu_{42}",   "\\boldsymbol{q}^{-1}\\nu_{42}", "\\boldsymbol{q}^{-2}\\nu_{42}",   "\\boldsymbol{q}^{-3}\\nu_{42}", "\\boldsymbol{q}^{-4}\\nu_{42}",   "\\nu_{43}", "\\boldsymbol{q}^{-1}\\nu_{43}", "\\nu_{44}",   "\\boldsymbol{q}^{-1}\\nu_{44}", "\\boldsymbol{q}^{-2}\\nu_{44}",   "\\boldsymbol{q}^{-3}\\nu_{44}", "\\boldsymbol{q}^{-4}\\nu_{44}",   "\\nu_{45}", "\\boldsymbol{q}^{-1}\\nu_{45}",   "\\boldsymbol{q}^{-2}\\nu_{45}", "\\boldsymbol{q}^{-3}\\nu_{45}",   "\\boldsymbol{q}^{-4}\\nu_{45}", "\\boldsymbol{q}^{-5}\\nu_{45}",   "\\nu_{46}", "\\boldsymbol{q}^{-1}\\nu_{46}",   "\\boldsymbol{q}^{-2}\\nu_{46}", "\\nu_{47}",   "\\boldsymbol{q}^{-1}\\nu_{47}", "\\boldsymbol{q}^{-2}\\nu_{47}",   "\\boldsymbol{q}^{-3}\\nu_{47}", "\\boldsymbol{q}^{-4}\\nu_{47}",   "\\boldsymbol{q}^{-5}\\nu_{47}", "\\nu_{48}",   "\\boldsymbol{q}^{-1}\\nu_{48}", "\\boldsymbol{q}^{-2}\\nu_{48}",   "\\nu_{49}", "\\boldsymbol{q}^{-1}\\nu_{49}",   "\\boldsymbol{q}^{-2}\\nu_{49}", "\\boldsymbol{q}^{-3}\\nu_{49}",   "\\boldsymbol{q}^{-4}\\nu_{49}", "\\boldsymbol{q}^{-5}\\nu_{49}",   "\\nu_{50}", "\\boldsymbol{q}^{-1}\\nu_{50}",   "\\boldsymbol{q}^{-2}\\nu_{50}", "\\nu_{51}",   "\\boldsymbol{q}^{-1}\\nu_{51}", "\\boldsymbol{q}^{-2}\\nu_{51}",   "\\boldsymbol{q}^{-3}\\nu_{51}", "\\boldsymbol{q}^{-4}\\nu_{51}",   "\\nu_{52}", "\\boldsymbol{q}^{-1}\\nu_{52}", "\\nu_{53}",   "\\boldsymbol{q}^{-1}\\nu_{53}", "\\boldsymbol{q}^{-2}\\nu_{53}",   "\\boldsymbol{q}^{-3}\\nu_{53}", "\\boldsymbol{q}^{-4}\\nu_{53}",   "\\nu_{54}", "\\boldsymbol{q}^{-1}\\nu_{54}",   "\\boldsymbol{q}^{-2}\\nu_{54}", "\\boldsymbol{q}^{-3}\\nu_{54}",   "\\boldsymbol{q}^{-4}\\nu_{54}", "\\boldsymbol{q}^{-5}\\nu_{54}",   "\\boldsymbol{q}^{-6}\\nu_{54}", "\\boldsymbol{q}^{-7}\\nu_{54}",   "\\nu_{55}", "\\boldsymbol{q}^{-1}\\nu_{55}",   "\\boldsymbol{q}^{-2}\\nu_{55}", "\\boldsymbol{q}^{-3}\\nu_{55}",   "\\boldsymbol{q}^{-4}\\nu_{55}", "\\nu_{56}",   "\\boldsymbol{q}^{-1}\\nu_{56}" ]

In [1571]:
index_s  := 56;;
NuVectorNamesPermuted := QGNAG_NuNames( Permuted(bijs_shifted, sigma ));;
Print(QGNAG_EpsilonToLaTeX(index_s, epsilon_and_coeffs, NuVectorNamesPermuted));
# \epsilon_{56} = \boldsymbol{q}^{-1}\nu_{50} + \boldsymbol{q}^{-4}\nu_{56}

\epsilon_{56} = \boldsymbol{q}^{-5}\nu_{49} + \nu_{56}

In [1579]:
QGNAG_PrintQuantumPolynomials := function(epsilon_and_coeffs, nu_names)
    local theta, index_s;
    theta := Length(epsilon_and_coeffs);
    for index_s in [1 .. theta] do
        Print(QGNAG_EpsilonToLaTeX(index_s, epsilon_and_coeffs, nu_names ), "\n");
    od;
end;;

In [1580]:
QGNAG_PrintQuantumPolynomials(epsilon_and_coeffs, NuVectorNamesPermuted);

\epsilon_{1} = \nu_{1} + \boldsymbol{q}^{-9}\nu_{10} + \boldsymbol{q}^{-1}\nu_\
{36} + \boldsymbol{q}^{-4}\nu_{45}
\epsilon_{2} = \nu_{2} + \boldsymbol{q}^{-6}\nu_{6} + \boldsymbol{q}^{-2}\nu_{\
42}
\epsilon_{3} = \nu_{3} + \boldsymbol{q}^{-3}\nu_{8}
\epsilon_{4} = \nu_{4}
\epsilon_{5} = \nu_{5} + \boldsymbol{q}^{-3}\nu_{12}
\epsilon_{6} = \boldsymbol{q}^{-6}\nu_{2} + \nu_{6} + \boldsymbol{q}^{-2}\nu_{\
42}
\epsilon_{7} = \nu_{7}
\epsilon_{8} = \boldsymbol{q}^{-3}\nu_{3} + \nu_{8}
\epsilon_{9} = \nu_{9} + \boldsymbol{q}^{-6}\nu_{11} + \boldsymbol{q}^{-2}\nu_\
{51}
\epsilon_{10} = \boldsymbol{q}^{-9}\nu_{1} + \nu_{10} + \boldsymbol{q}^{-4}\nu\
_{36} + \boldsymbol{q}^{-1}\nu_{45}
\epsilon_{11} = \boldsymbol{q}^{-6}\nu_{9} + \nu_{11} + \boldsymbol{q}^{-2}\nu\
_{51}
\epsilon_{12} = \boldsymbol{q}^{-3}\nu_{5} + \nu_{12}
\epsilon_{13} = \boldsymbol{q}^{-6}\nu_{1} + \boldsymbol{q}^{-3}\nu_{10} + \nu\
_{13} + \boldsymbol{q}^{-3}\nu_{16} + \boldsymbol{q}^{-1}\nu_{36} + \boldsymbo\
l{q}^{-2}\nu_{39} + \boldsymbol{q}^{-4}\nu_{45} + \boldsymbol{q}^{-5}\nu_{54}
\epsilon_{14} = \nu_{14}
\epsilon_{15} = \nu_{15}
\epsilon_{16} = \boldsymbol{q}^{-3}\nu_{1} + \boldsymbol{q}^{-6}\nu_{10} + \bo\
ldsymbol{q}^{-3}\nu_{13} + \nu_{16} + \boldsymbol{q}^{-4}\nu_{36} + \boldsymbo\
l{q}^{-5}\nu_{39} + \boldsymbol{q}^{-1}\nu_{45} + \boldsymbol{q}^{-2}\nu_{54}
\epsilon_{17} = \boldsymbol{q}^{-6}\nu_{1} + \boldsymbol{q}^{-3}\nu_{10} + \nu\
_{17} + \boldsymbol{q}^{-3}\nu_{26} + \boldsymbol{q}^{-1}\nu_{36} + \boldsymbo\
l{q}^{-2}\nu_{39} + \boldsymbol{q}^{-4}\nu_{45} + \boldsymbol{q}^{-5}\nu_{54}
\epsilon_{18} = \nu_{18}
\epsilon_{19} = \boldsymbol{q}^{-6}\nu_{1} + \boldsymbol{q}^{-3}\nu_{10} + \nu\
_{19} + \boldsymbol{q}^{-3}\nu_{28} + \boldsymbol{q}^{-1}\nu_{36} + \boldsymbo\
l{q}^{-2}\nu_{39} + \boldsymbol{q}^{-4}\nu_{45} + \boldsymbol{q}^{-5}\nu_{54}
\epsilon_{20} = \nu_{20}
\epsilon_{21} = \nu_{21} + \boldsymbol{q}^{-3}\nu_{32}
\epsilon_{22} = \nu_{22} + \boldsymbol{q}^{-6}\nu_{24} + \boldsymbol{q}^{-1}\n\
u_{33}
\epsilon_{23} = \nu_{23} + \boldsymbol{q}^{-3}\nu_{30}
\epsilon_{24} = \boldsymbol{q}^{-6}\nu_{22} + \nu_{24} + \boldsymbol{q}^{-1}\n\
u_{33}
\epsilon_{25} = \nu_{25}
\epsilon_{26} = \boldsymbol{q}^{-3}\nu_{1} + \boldsymbol{q}^{-6}\nu_{10} + \bo\
ldsymbol{q}^{-3}\nu_{17} + \nu_{26} + \boldsymbol{q}^{-4}\nu_{36} + \boldsymbo\
l{q}^{-5}\nu_{39} + \boldsymbol{q}^{-1}\nu_{45} + \boldsymbol{q}^{-2}\nu_{54}
\epsilon_{27} = \nu_{27}
\epsilon_{28} = \boldsymbol{q}^{-3}\nu_{1} + \boldsymbol{q}^{-6}\nu_{10} + \bo\
ldsymbol{q}^{-3}\nu_{19} + \nu_{28} + \boldsymbol{q}^{-4}\nu_{36} + \boldsymbo\
l{q}^{-5}\nu_{39} + \boldsymbol{q}^{-1}\nu_{45} + \boldsymbol{q}^{-2}\nu_{54}
\epsilon_{29} = \nu_{29} + \boldsymbol{q}^{-6}\nu_{31} + \boldsymbol{q}^{-1}\n\
u_{48}
\epsilon_{30} = \boldsymbol{q}^{-3}\nu_{23} + \nu_{30}
\epsilon_{31} = \boldsymbol{q}^{-6}\nu_{29} + \nu_{31} + \boldsymbol{q}^{-1}\n\
u_{48}
\epsilon_{32} = \boldsymbol{q}^{-3}\nu_{21} + \nu_{32}
\epsilon_{33} = \boldsymbol{q}^{-2}\nu_{9} + \boldsymbol{q}^{-2}\nu_{11} + \bo\
ldsymbol{q}^{-5}\nu_{22} + \boldsymbol{q}^{-5}\nu_{24} + \nu_{33} + \boldsymbo\
l{q}^{-4}\nu_{51}
\epsilon_{34} = \nu_{34} + \boldsymbol{q}^{-1}\nu_{41}
\epsilon_{35} = \nu_{35} + \boldsymbol{q}^{-4}\nu_{55}
\epsilon_{36} = \boldsymbol{q}^{-5}\nu_{1} + \boldsymbol{q}^{-8}\nu_{10} + \bo\
ldsymbol{q}^{-2}\nu_{16} + \boldsymbol{q}^{-2}\nu_{26} + \boldsymbol{q}^{-2}\n\
u_{28} + \nu_{36} + 2 \boldsymbol{q}^{-1}\nu_{39} + \boldsymbol{q}^{-7}\nu_{39\
} + \boldsymbol{q}^{-3}\nu_{45}
\epsilon_{37} = \nu_{37} + \boldsymbol{q}^{-4}\nu_{53}
\epsilon_{38} = \nu_{38} + \boldsymbol{q}^{-1}\nu_{43}
\epsilon_{39} = \boldsymbol{q}^{-4}\nu_{1} + \boldsymbol{q}^{-1}\nu_{10} + \bo\
ldsymbol{q}^{-1}\nu_{16} + \boldsymbol{q}^{-1}\nu_{26} + \boldsymbol{q}^{-1}\n\
u_{28} + \boldsymbol{q}^{-5}\nu_{36} + \nu_{39} + 2 \boldsymbol{q}^{-6}\nu_{39\
} + \boldsymbol{q}^{-2}\nu_{45}
\epsilon_{40} = \nu_{40} + \boldsymbol{q}^{-2}\nu_{50}
\epsilon_{41} = \boldsymbol{q}^{-5}\nu_{34} + \nu_{41}
\epsilon_{42} = \boldsymbol{q}^{-4}\nu_{2} + \boldsymbol{q}^{-4}\nu_{6} + \bol\
dsymbol{q}^{-1}\nu_{29} + \boldsymbol{q}^{-1}\nu_{31} + \nu_{42} + \boldsymbol\
{q}^{-2}\nu_{48}
\epsilon_{43} = \boldsymbol{q}^{-5}\nu_{38} + \nu_{43}
\epsilon_{44} = \nu_{44} + \boldsymbol{q}^{-2}\nu_{46}
\epsilon_{45} = \boldsymbol{q}^{-8}\nu_{1} + \boldsymbol{q}^{-5}\nu_{10} + \bo\
ldsymbol{q}^{-2}\nu_{13} + \boldsymbol{q}^{-2}\nu_{17} + \boldsymbol{q}^{-2}\n\
u_{19} + \boldsymbol{q}^{-3}\nu_{36} + \nu_{45} + 2 \boldsymbol{q}^{-1}\nu_{54\
} + \boldsymbol{q}^{-7}\nu_{54}
\epsilon_{46} = \boldsymbol{q}^{-4}\nu_{44} + \nu_{46}
\epsilon_{47} = \nu_{47} + \boldsymbol{q}^{-1}\nu_{52}
\epsilon_{48} = \boldsymbol{q}^{-2}\nu_{2} + \boldsymbol{q}^{-2}\nu_{6} + \bol\
dsymbol{q}^{-5}\nu_{29} + \boldsymbol{q}^{-5}\nu_{31} + \boldsymbol{q}^{-4}\nu\
_{42} + \nu_{48}
\epsilon_{49} = \nu_{49} + \boldsymbol{q}^{-1}\nu_{56}
\epsilon_{50} = \boldsymbol{q}^{-4}\nu_{40} + \nu_{50}
\epsilon_{51} = \boldsymbol{q}^{-4}\nu_{9} + \boldsymbol{q}^{-4}\nu_{11} + \bo\
ldsymbol{q}^{-1}\nu_{22} + \boldsymbol{q}^{-1}\nu_{24} + \boldsymbol{q}^{-2}\n\
u_{33} + \nu_{51}
\epsilon_{52} = \boldsymbol{q}^{-5}\nu_{47} + \nu_{52}
\epsilon_{53} = \boldsymbol{q}^{-2}\nu_{37} + \nu_{53}
\epsilon_{54} = \boldsymbol{q}^{-1}\nu_{1} + \boldsymbol{q}^{-4}\nu_{10} + \bo\
ldsymbol{q}^{-1}\nu_{13} + \boldsymbol{q}^{-1}\nu_{17} + \boldsymbol{q}^{-1}\n\
u_{19} + \boldsymbol{q}^{-2}\nu_{36} + \boldsymbol{q}^{-5}\nu_{45} + \nu_{54} \
+ 2 \boldsymbol{q}^{-6}\nu_{54}
\epsilon_{55} = \boldsymbol{q}^{-2}\nu_{35} + \nu_{55}
\epsilon_{56} = \boldsymbol{q}^{-5}\nu_{49} + \nu_{56}

In [1576]:
QGNAG_LoadQuantumCharactersToLaTeXT:= function(filename, epsilon_and_coeffs, NuVectorNames, SimpleNames)
    local isValid,
          out,
          index_s,
          epsilon,
          sNames,
          coefficients,
          theta,
          result;

    isValid := IsList(epsilon_and_coeffs) 
               and not IsEmpty(epsilon_and_coeffs)
               and ForAll(epsilon_and_coeffs, r -> 
                   IsRecord(r) 
                   and IsBound(r.vector) and IsList(r.vector)
                   and IsBound(r.coefficients) and IsList(r.coefficients)
               );

    if not isValid then
        Error("Invalid 'epsilon_and_coeffs' argument.\n",
              "It must be a list of records with 'vector' and 'coefficients' fields.\n",
              "Please generate it using:\n",
              "  epsilon_and_coeffs := QGNAG_QuantumCharatersAndCoefficients( data_graded, nu );\n");
    fi;

    out    := OutputTextFile(filename, false);
    sNames := List(SimpleNames, QGNAG_ExtractTuple);
    theta   := Length(epsilon_and_coeffs);;
    for index_s in [1..theta] do
        epsilon      := epsilon_and_coeffs[index_s].vector;
        coefficients := epsilon_and_coeffs[index_s].coefficients;
        result       := QGNAG_EpsilonToLaTeX(index_s, epsilon_and_coeffs, NuVectorNames);
        
        #AppendTo(out, Concatenation("\\subsubsection*{$L", sNames[index_s], "$}\n"));
        AppendTo(out, Concatenation("\\subsubsection*{$L_{", String(index_s), "}$}\n"));
        AppendTo(out, "$\n");
        AppendTo(out, result);
        AppendTo(out, "\n$\n\n");
    od;
    
    CloseStream(out);
end;

function( filename, epsilon_and_coeffs, NuVectorNames, SimpleNames ) ... end

In [1578]:
QGNAG_LoadQuantumCharactersToLaTeXT("quantum_characters_T4_permuted_by_sigma.tex", epsilon_and_coeffs, NuVectorNamesPermuted, SimpleNames);

## Polynomials $t_{j,p}(\boldsymbol{q})$

In [1591]:
data_quantum_pols := QGNAG_QuantumPolynomialsToRecord( Permuted(data_record_data_decomp, sigma), epsilon_and_coeffs );;

Length(nu) = 248
Shift counts = [ 10, 7, 4, 1, 4, 7, 1, 4, 7, 10, 7, 4, 4, 1, 1, 4, 4, 1, 4,
  1, 4, 7, 4, 7, 1, 4, 1, 4, 7, 4, 7, 4, 3, 6, 3, 6, 3, 6, 8, 5, 2, 5, 2, 5,
  6, 3, 6, 3, 6, 3, 5, 2, 5, 8, 5, 2 ]

In [ ]:
data_quantum_pols;

In [1595]:
data_quantum_pols_eval := QGNAG_EvaluateQuantumPolynomialsRecord(data_quantum_pols);

[ rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 1, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 1, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 1, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 1, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 1, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 1, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 1, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 1, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 1, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 1, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 1, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 1, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 1, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 1, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 1, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 1, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 1 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 1, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 1, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 1 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 1, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 1, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 1, 14 := 0, 15 := 0, 16 := 1,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 1, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 1, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 1, 14 := 0, 15 := 0, 16 := 1,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 1, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 1, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 1, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 1, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 1, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 1, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 1, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 1, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 1, 23 := 0,       24 := 1, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 1, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 1,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 1,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 1, 23 := 0,       24 := 1, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 1, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 1, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 1, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 1, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 1, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 1, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 1, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 1, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 1, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 1, 3 := 0, 30 := 0,       31 := 1, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 1, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 1,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 1,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 1, 3 := 0, 30 := 0,       31 := 1, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 1, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 1, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 1, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 1, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 1, 23 := 0,       24 := 1, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 1, 34 := 0, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 1, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 1 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 1, 35 := 0, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 1, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 1, 36 := 0, 37 := 0, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 1, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 1, 10 := 1, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 1,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 1, 27 := 0, 28 := 1, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 1, 37 := 0, 38 := 0,       39 := 3, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 1,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 0, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 := 0, 11 := 0, 12 := 0, 13 := 0, 14 := 0, 15 := 0, 16 := 0,       17 := 0, 18 := 0, 19 := 0, 2 := 0, 20 := 0, 21 := 0, 22 := 0, 23 := 0,       24 := 0, 25 := 0, 26 := 0, 27 := 0, 28 := 0, 29 := 0, 3 := 0, 30 := 0,       31 := 0, 32 := 0, 33 := 0, 34 := 0, 35 := 0, 36 := 0, 37 := 1, 38 := 0,       39 := 0, 4 := 0, 40 := 0, 41 := 0, 42 := 0, 43 := 0, 44 := 0, 45 := 0,       46 := 0, 47 := 0, 48 := 0, 49 := 0, 5 := 0, 50 := 0, 51 := 0, 52 := 0,       53 := 1, 54 := 0, 55 := 0, 56 := 0, 6 := 0, 7 := 0, 8 := 0, 9 := 0 ),   rec( 1 := 0, 10 :=

In [1598]:
Print(data_quantum_pols_eval[56]);

rec(
  1 := 0,
  10 := 0,
  11 := 0,
  12 := 0,
  13 := 0,
  14 := 0,
  15 := 0,
  16 := 0,
  17 := 0,
  18 := 0,
  19 := 0,
  2 := 0,
  20 := 0,
  21 := 0,
  22 := 0,
  23 := 0,
  24 := 0,
  25 := 0,
  26 := 0,
  27 := 0,
  28 := 0,
  29 := 0,
  3 := 0,
  30 := 0,
  31 := 0,
  32 := 0,
  33 := 0,
  34 := 0,
  35 := 0,
  36 := 0,
  37 := 0,
  38 := 0,
  39 := 0,
  4 := 0,
  40 := 0,
  41 := 0,
  42 := 0,
  43 := 0,
  44 := 0,
  45 := 0,
  46 := 0,
  47 := 0,
  48 := 0,
  49 := 1,
  5 := 0,
  50 := 0,
  51 := 0,
  52 := 0,
  53 := 0,
  54 := 0,
  55 := 0,
  56 := 1,
  6 := 0,
  7 := 0,
  8 := 0,
  9 := 0 )

In [ ]:
NonZeroKeys := function(r)
    return Filtered(RecNames(r), k -> r.(k) <> 0);
end;

In [ ]:
NonZeroKeys(data_quantum_pols_eval[1]);

In [ ]:
TransposeRecordList := function(record_list)
    local keys, sortedKeys, n, newlist, key, i, newrec;

    keys := RecNames(record_list[1]);

    # si las claves son numéricas, ordenarlas como enteros
    if ForAll(keys, k -> ForAll(k, c -> c in "-0123456789")) then
        sortedKeys := List(keys, Int);
        Sort(sortedKeys);
        sortedKeys := List(sortedKeys, String);
    else
        sortedKeys := keys;
    fi;

    n := Length(record_list);
    newlist := [];
    for key in sortedKeys do
        newrec := rec();
        for i in [1..n] do
            newrec.(String(i)) := record_list[i].(key);
        od;
        Add(newlist, newrec);
    od;

    return newlist;
end;

In [1593]:
QGNAG_RecordListToHTMLTable(data_quantum_pols_eval, true);

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56
1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
2,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
10,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
11,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
12,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
14,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
36,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
37,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,3,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
41,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
43,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
45,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
47,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
48,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
50,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
51,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0
53,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
54,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,3,0,0
55,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
56,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1

In [1594]:
QGNAG_ThePolynomialCoefficients( "the_polynomial_coefficients.tex", Permuted(data_record_data_decomp, sigma), epsilon_and_coeffs, SimpleNames );

Length(nu) = 248
Shift counts = [ 10, 7, 4, 1, 4, 7, 1, 4, 7, 10, 7, 4, 4, 1, 1, 4, 4, 1, 4,
  1, 4, 7, 4, 7, 1, 4, 1, 4, 7, 4, 7, 4, 3, 6, 3, 6, 3, 6, 8, 5, 2, 5, 2, 5,
  6, 3, 6, 3, 6, 3, 5, 2, 5, 8, 5, 2 ]

## Block Clasification

In [1603]:
data_quantum_pols[56].49;

[ 0, 0, 0, 0, 0, 1 ]

In [1604]:
block_classification := QGNAG_ClassifySimplesIntoBlocksContiguous( data_quantum_pols );;

In [1605]:
block_classification;

rec( 1 := [ 1, 10, 13, 16, 17, 19, 26, 28, 36, 39, 45, 54 ], 10 := [ 18 ], 11 := [ 20 ], 12 := [ 21, 32 ], 13 := [ 23, 30 ], 14 := [ 25 ], 15 := [ 27 ], 16 := [ 34, 41 ], 17 := [ 35, 55 ], 18 := [ 37, 53 ], 19 := [ 38, 43 ], 2 := [ 2, 6, 29, 31, 42, 48 ], 20 := [ 40, 50 ], 21 := [ 44, 46 ], 22 := [ 47, 52 ], 23 := [ 49, 56 ], 3 := [ 3, 8 ], 4 := [ 4 ], 5 := [ 5, 12 ], 6 := [ 7 ], 7 := [ 9, 11, 22, 24, 33, 51 ], 8 := [ 14 ], 9 := [ 15 ] )

In [1606]:
QGNAG_LoadBlockClassificationToLaTeX( "block_classification.tex", block_classification, SimpleNames );

## Separation into blocks


\begin{array}{c|c|l}
\text{Block} & \text{Indices} & \text{Simple }D(H)\text{-modules} \\\hline
B_{1} & \{ 1, 2, 6\}   \cup& \{ L(0,\tau_{00}), L(0,\tau_{12}), L(0,\tau_{11}) \}\cup \\ 
      & \{ 9, 10, 11 \}\cup& \{ L(3,\tau_{01}), L(3,\tau_{10}), L(3,\tau_{02}) \}\cup \\ 
      &\{ 13, 16, \}\cup& \{ L(0,\rho_{0}), L(3,\rho_{1}) \}\cup\\ 
      &\{ 17, 19, 22, 24\}\cup& \{ L(0,\chi_{(0,0,0)}), L(0,\chi_{(0,1,0)}), L(0,\chi_{(1,0,1)}), L(0,\chi_{(1,1,1)})\}\cup\\ 
      &\{ 26, 28, 29, 31\}\cup& \{ L(3,\chi_{(0,0,1)}), L(3,\chi_{(0,1,1)}), L(3,\chi_{(1,0,0)}), L(3,\chi_{(1,1,0)})\}\cup\\
  &\{33\leq i\leq 56\} &  \{M(s,\eta_\ell): s=1,2,4,6,\ell=0,1,...,5\}\\
B_{2} & \{3,\ 8\} & L(0,\tau_{01}),\ L(3,\tau_{12}) \\
B_{3} & \{4\} & L(0,\tau_{10}) \\
B_{4} & \{5,\ 12\} & L(0,\tau_{02}),\ L(3,\tau_{11}) \\
B_{5} & \{7\} & L(3,\tau_{00}) \\
B_{6} & \{14\} & L(0,\rho_{1}) \\
B_{7} & \{15\} & L(3,\rho_{0}) \\
B_{8} & \{18\} & L(0,\chi_{(0,0,1)}) \\
B_{9} & \{20\} & L(0,\chi_{(0,1,1)}) \\
B_{10} & \{21,\ 32\} & L(0,\chi_{(1,0,0)}),\ L(3,\chi_{(1,1,1)}) \\
B_{11} & \{23,\ 30\} & L(0,\chi_{(1,1,0)}),\ L(3,\chi_{(1,0,1)}) \\
B_{12} & \{25\} & L(3,\chi_{(0,0,0)}) \\
B_{13} & \{27\} & L(3,\chi_{(0,1,0)}) \\
\end{array}

## Graph

In [1607]:
QGNAG_GraphComputeLayoutTest := function( fig )
    local adjacency,
          node, 
          e, 
          p, 
          q, 
          visited, 
          components, 
          comp, 
          queue,
          current, 
          neighbor, 
          level, 
          hGap, 
          vGap, 
          blockGap, 
          coords,
          nodes, 
          edges,
          xOffset, 
          maxlevel, 
          byLevel, 
          lvl, 
          ns, 
          i, 
          y, 
          x, 
          nodeIndex,
          maxWidth, 
          isChain, 
          isolated, 
          rest, 
          isolatedNodes;

    nodes := fig.nodes;
    edges := fig.edges;
    # indexar nodos 1..n internamente, pero conservando sus ids reales
    nodeIndex := rec();
    for i in [1..Length(nodes)] do
        nodeIndex.(String(nodes[i])) := i;
    od;
    adjacency := rec();
    for node in nodes do
        adjacency.(String(node)) := [];
    od;
    for e in edges do
        p := e[1];
        q := e[2];
        Add( adjacency.(String(p)), q );
        Add( adjacency.(String(q)), p );
    od;

    visited := rec();
    for node in nodes do
        visited.(String(node)) := false;
    od;

    components := [];
    level      := rec();

    for node in nodes do
        if not visited.(String(node)) then
            comp := [];
            level.(String(node)) := 0;
            queue := [node];
            visited.(String(node)) := true;
            while Length(queue) > 0 do
                current := Remove(queue, 1);
                Add(comp, current);
                for neighbor in adjacency.(String(current)) do
                    if not visited.(String(neighbor)) then
                        visited.(String(neighbor)) := true;
                        level.(String(neighbor)) := level.(String(current)) + 1;
                        Add(queue, neighbor);
                    fi;
                od;
            od;
            Sort(comp);
            Add(components, comp);
        fi;
    od;
    Sort( components, function(a,b) return a[1] < b[1]; end );

    if IsBound(fig.hGap )  then 
        hGap := fig.hGap ;  
    else 
        hGap := 8/5; 
    fi;
    if IsBound(fig.vGap )  then 
        vGap := fig.vGap ;  
    else 
        vGap := 13/10;  
    fi;
    
    if IsBound( fig.blockGap )  then 
        blockGap := fig.blockGap;
    else 
        blockGap := 11/5;  
    fi;
    if IsBound( fig.xOffset )  then 
        xOffset := fig.xOffset;
    else 
        xOffset  := 0; 
    fi;
    coords   := rec();
    

    # nodos aislados (componentes de un solo nodo, sin aristas): van
    # todos juntos en una unica columna, no una columna por nodo
    isolated := Filtered( components, c -> Length(c) = 1 );
    rest     := Filtered( components, c -> Length(c) > 1 );

    isolatedNodes := List( isolated, c -> c[1] );
    Sort( isolatedNodes );

    if Length(isolatedNodes) > 0 then
        for i in [1..Length(isolatedNodes)] do
            coords.(String(isolatedNodes[i])) := [ xOffset, (i-1)*vGap ];
        od;
        xOffset := xOffset + blockGap;
    fi;

    for comp in rest do
        maxlevel := Maximum( List( comp, node -> level.(String(node)) ) );
        byLevel  := rec();
        for node in comp do
            lvl := String( level.(String(node)) );
            if not IsBound( byLevel.(lvl) ) then
                byLevel.(lvl) := [];
            fi;
            Add( byLevel.(lvl), node );
        od;

        # si la componente es una cadena simple (un solo nodo por nivel,
        # sin ramificarse), se dibuja en vertical en vez de horizontal
        maxWidth := Maximum( List( RecNames(byLevel), lvl -> Length(byLevel.(lvl)) ) );
        isChain  := (maxWidth = 1);

        for lvl in RecNames(byLevel) do
            ns := byLevel.(lvl);
            Sort(ns);
            for i in [1..Length(ns)] do
                if isChain then
                    x := xOffset;
                    y := Int(lvl) * vGap;
                else
                    y := ( (Length(ns)+1)/2 - i ) * vGap;
                    x := xOffset + Int(lvl) * hGap;
                fi;
                coords.(String(ns[i])) := [ x, y ];
            od;
        od;

        if isChain then
            xOffset := xOffset + blockGap;
        else
            xOffset := xOffset + maxlevel*hGap + blockGap;
        fi;
    od;

    return coords;
end;

function( fig ) ... end

In [1608]:
QGNAG_GraphRenderTest := function( fig )
    local width, 
          height, 
          margin,
          minCoordGap, 
          nodeRadius,
          fill,
          stroke,
          stroke_width,
          text_anchor,
          font_family,
          nodes, 
          edges, 
          coords,
          scale,
          minX, 
          maxX, 
          minY, 
          maxY, 
          PlotX, 
          PlotY, 
          svg, 
          e, 
          p, 
          q,
          x1, 
          y1, 
          x2, 
          y2, 
          node, 
          px, 
          py, 
          cleanTitle, 
          html_output;

if IsBound(fig.width)  then 
    width  := fig.width;  
else 
    width  := 1000; 
fi;

if IsBound(fig.height) then 
    height := fig.height; 
else 
    height := 600; 
fi;
if IsBound(fig.margin)  then 
    margin := fig.margin;  
else 
    margin := 40;
fi;

if IsBound(fig.nodeRadius) then 
    nodeRadius := fig.nodeRadius; 
else 
    nodeRadius := 12;
fi;

if IsBound(fig.fill) then 
    fill := fig.fill; 
else 
    fill := "#eef2ff";
fi; 

if IsBound(fig.stroke) then 
    stroke := fig.stroke; 
else 
    stroke := "black";
fi; 

if IsBound(fig.stroke_width) then 
    stroke_width := fig.stroke_width; 
else 
    stroke_width := 1.5;
fi; 

if IsBound(fig.font_family) then 
    font_family := fig.font_family; 
else 
    font_family := "sans-serif";
fi;

if IsBound(fig.text_anchor) then 
    text_anchor := fig.text_anchor; 
else 
    text_anchor := "middle";
fi;

if IsBound(fig.vGap) then 
    vGap := fig.vGap; 
else 
    vGap := 13/10; 
fi;
if not IsBound(fig.nodes) or not IsBound(fig.edges) then
    Error("fig debe tener 'nodes' y 'edges'.");
fi;

nodes := fig.nodes;;
edges := fig.edges;; 

if IsBound(fig.coords) then
    coords := fig.coords;
else
    coords := QGNAG_GraphComputeLayoutTest(fig);
fi;

# largo minimo de linea visible que quiero ver entre dos nodos conectados (px)

if IsBound(fig.minEdgeLen ) then 
    minEdgeLen  := fig.minEdgeLen;
else 
    minEdgeLen := 3;;
fi;

minCoordGap := Minimum( List( edges, e ->
    Sqrt( Float( (coords.(String(e[1]))[1]-coords.(String(e[2]))[1])^2
                + (coords.(String(e[1]))[2]-coords.(String(e[2]))[2])^2 ) )
) );;

# escala tal que el par de nodos MAS cercano (conectado) siempre deje
# al menos minEdgeLen pixeles de linea visible entre sus dos circulos
scale := (minEdgeLen + 2*nodeRadius) / minCoordGap;;


minX := Minimum( List(nodes, node -> Float(coords.(String(node))[1])) );;
maxX := Maximum( List(nodes, node -> Float(coords.(String(node))[1])) );;
minY := Minimum( List(nodes, node -> Float(coords.(String(node))[2])) );;
maxY := Maximum( List(nodes, node -> Float(coords.(String(node))[2])) );;

if maxX = minX then 
    maxX := minX + 1.0; 
fi;;

if maxY = minY then 
    maxY := minY + 1.0; 
fi;;

# pixeles por unidad de coordenada (esto es lo que controla la separacion real)
# el canvas se calcula a partir de la escala, no al reves

PlotX := function(x)
    return margin + nodeRadius + Int( (Float(x) - minX) * (width - 2*margin - 2*nodeRadius) / (maxX - minX) );
end;;

PlotY := function(y)
    # Invertimos el eje Y (para SVG) manteniendo el centro vertical
    return Int( height / 2 - Float(y) * (height - 2*margin - 2*nodeRadius) / (maxY - minY + 1.0) );
end;;
# --- Corregir binding de vGap ---
# --- SVG ---
svg := Concatenation( "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"", String(width), "\" height=\"", String(height), "\">" );;
svg := Concatenation(svg, "<rect x=\"0\" y=\"0\" width=\"", String(width), "\" height=\"", String(height), "\" fill=\"white\" stroke=\"black\"/>" );;

# aristas primero, para que queden debajo de los nodos
for e in edges do
        p := e[1]; 
        q := e[2];
        x1 := PlotX(coords.(String(p))[1]); y1 := PlotY(coords.(String(p))[2]);
        x2 := PlotX(coords.(String(q))[1]); y2 := PlotY(coords.(String(q))[2]);
        svg := Concatenation(svg,
            "<line x1=\"", String(x1), 
               "\" y1=\"", String(y1),
               "\" x2=\"", String(x2), 
               "\" y2=\"", String(y2),
               "\" stroke=\"", stroke,
               "\" stroke-width=\"", String(stroke_width), "\"/>"
        );
od;

# nodos
for node in nodes do
    px := PlotX(coords.(String(node))[1]);
    py := PlotY(coords.(String(node))[2]);
    svg := Concatenation(svg,
            "<circle cx=\"", String(px), 
                "\" cy=\"", String(py),
                "\" r=\"", String(nodeRadius),
                "\" fill=\"",  fill,
                "\" stroke=\"", stroke,
                "\" stroke-width=\"", String(stroke_width), "\"/>",
            "<text x=\"", String(px),
                  "\" y=\"", String(py+5),
                  "\" text-anchor=\"", text_anchor,
                  "\" font-size=\"", String(14),
                  "\" font-family=\"", font_family, 
                  "\">", String(node), "</text>"
    );
od;
svg := Concatenation(svg, "</svg>");;
# --- capa HTML (titulo opcional, misma filosofia que GAPPlot_Render) ---
html_output := Concatenation( "<div style=\"position: relative; width: ", String(width), "px; height: auto; background: white;\">" );;

if IsBound(fig.title) then
    cleanTitle := QGNAG_UrlEncode(QGNAG_PrepareLaTeX(fig.title));
    html_output := Concatenation(html_output,
            "<div style=\"text-align:center; padding: 6px 0;\">",
            "<img src=\"https://latex.codecogs.com/svg.image?\\displaystyle%20",
            cleanTitle, "\" style=\"height: 22px;\" />",
            "</div>"
    );;
fi;;
html_output := Concatenation(html_output, svg, "</div>");;
return JupyterRenderable(
        rec(("text/html") := html_output),
        rec(("text/html") := rec(width := width, height := height))
    );
end;

Syntax warning: Unbound global variable in stream:90
    vGap := fig.vGap;
    ^^^^
Syntax warning: Unbound global variable in stream:92
    vGap := 13/10;
    ^^^^
Syntax warning: Unbound global variable in stream:110
    minEdgeLen  := fig.minEdgeLen;
    ^^^^^^^^^^
Syntax warning: Unbound global variable in stream:112
    minEdgeLen := 3;;
    ^^^^^^^^^^
Syntax warning: Unbound global variable in stream:122
scale := (minEdgeLen + 2*nodeRadius) / minCoordGap;;
          ^^^^^^^^^^

function( fig ) ... end

In [1615]:
fig              := QGNAG_GraphFromSimples( data_quantum_pols );;
fig.title        := "Blocks $\\mathcal{T}_{4}$";;
fig.margin       := 30;;
fig.nodeRadius   := 12.5;;
#fig.scale        := 25;;
fig.hGap         := 2;;
#fig.vGap         := 80;;
fig.blockGap     := 2;;
#fig.maxColHeight := 16;;
QGNAG_GraphRenderTest( fig );

In [1616]:
sigma;

(2,9)(3,5)(4,7)(6,11)(8,12)(14,15)(18,25)(20,27)(21,23)(22,31)(24,29)(30,32)(33,42)(34,56)(35,40)(36,54)(37,44)(38,52)(39,45)(41,49)(43,47)(46,53)(48,51)(50,55)